### ISSUE TITLE
Rename button not active in Bouquet Editor

### ISSUE THREAD

**Issue by Alexwilmac** [E2OpenPlugins/e2openplugin-OpenWebif#1000]
As of the subject, I noticed that the Rename button in Bouquet Editor is no longer working.

![Schermata 2020-04-15 alle 12 44 14](https://user-images.githubusercontent.com/25823585/79389939-1fcf5400-7f6f-11ea-95f9-ec6d98589034.png)

**Comment by jbleyel** [comment]
You can only rename marker.
That's by design.
