### ISSUE TITLE
Support for third party plugins

### ISSUE THREAD

**Issue by MacDisein** [E2OpenPlugins/e2openplugin-OpenWebif#1001]
I am the current maintainer of the SerienRecorder plugin and have a question regarding the integration of third party plugins like the SerienRecorder - because I am writting on a new Webinterface for the SerienRecorder.

There is a loop to integrate all plugins who registered a webinterface - but this is restricted:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/e7002c22b7aadeb8b7be687856763e15337594a4/plugin/controllers/base.py#L344

There is a SR.py in controllers - so I have to create that kind of file for my new webinterface?

**Comment by jbleyel** [comment]
Hi MacDesin,
you have 2 options.

A) You create you own webinterface like lcd4linux
B) You update the current api interface (see sr.py) and then build an html file with javascript like autotimer, epgrefresh

I can help you with the integration in openwebif.

**Comment by jbleyel** [comment]
Update:  The file SerienRecorderResource.py no longer exists and this is the old implementation for option B.

**Comment by jbleyel** [comment]
I know only this ->

https://github.com/einfall/serienrecorder/commit/a4227d0c2eec2d3e952ebe551292a1f23eb13899#diff-159428751763673bc0705adb8d2013d0

**Comment by MacDisein** [comment]
Dann können wir das ja auf Deutsch fortsetzen.
Mir geht es darum, dass ein Link zu meinem neuen SerienRecorder Webinterface im OWI eingefügt wird. Im Dreambox Webinterface funktioniert das automatisch durch das addExternalChild. Wie ich oben geschrieben hatte, wird dieser Mechanismus im OWI kastriert, weil dort nur bestimmte Plugins berücksichtigt werden.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/e7002c22b7aadeb8b7be687856763e15337594a4/plugin/controllers/base.py#L345

Wenn ich meinen neuen Namespace dort ergänze, wird mir der Link unter „Extras“ im OWI angezeigt. Ich frage mich wieso dieses Feature nur auf bestimmte Plugins beschränkt ist?

Der OWI Weg wäre also die zusätzliche SR.py im OWI - die muss ich dann an mein neues Interface anpassen? Damit das dann funktioniert, muss die Datei in allen Images, die das OWI nutzen, ausgetauscht werden.

Eigentlich wäre mir der automatische Weg lieber, weil dann kein zusätzliches Modul im OWI nötig ist und alles zentral im SerienRecorder wäre.

**Comment by jbleyel** [comment]
Die Zeile 345 ist nur dafür da, das extra Plugins links im openwebif mit angezeigt werden.
Die SR.py ist dafür da, das deine Api funktioniert.
Diese Api scheint es aber nicht mehr zu geben.

Zumindest nicht hier -> https://github.com/einfall/serienrecorder

**Comment by MacDisein** [comment]
Ich habe das Gefühl, dass wir aneinander vorbei reden.

Die API ist noch bei mir im Labor - ich muss erstmal die Infrastruktur schaffen, bevor ich sie veröffentlichen kann.
Ich habe meine API so implementiert wie es für das Dreambox Webinterface nötig ist, und sie funktioniert auch auf mit dem OWI auf meiner openATV Entwicklerbox.
Was mir fehlt ist der Link im "Extras" Menü - den bekomme ich nur, wenn ich die von mir zitierte Zeile 345 um meinen Namespace erweitere.

![OWI-Patch](https://user-images.githubusercontent.com/8401876/79699661-34725b80-8291-11ea-95fe-d27b6c09b6d6.png)

Wie bekomme ich einen Link zu meinem eigenen Webinterface ins OWI, wie in meiner gepatchten Version?

**Comment by jbleyel** [comment]
Dann schick mir mal deine Anpassung und ich bau das ein.

**Comment by MacDisein** [comment]
Super, das Array in der oben zitierte 345 um "serienrecorderui" ergänzen.
`if plugins[0] in ["fancontrol", "iptvplayer", "serienrecorderui"]: `

**Comment by MacDisein** [comment]
Könntest du bitte auch noch die plugin/controllers/SR.py Datei löschen - diese Version des Webinterfaces gibt es schon mehrere Jahre im SerienRecorder Plugin nicht mehr. Im Moment verursacht das Modul nur unnötige Meldungen im DebugLog.

**Comment by jbleyel** [comment]
Wie sieht denn die neue Api aus?
Oder gibt es diese nicht mehr?

Es geht hier nicht um das Webinterface sondern um die web api.

**Comment by MacDisein** [comment]
Ich habe dir eben die zukünftige API per Mail geschickt.

**Comment by jbleyel** [comment]
Der alte code ist jetzt draussen.

**Comment by MacDisein** [comment]
I need to reopen the ticket.

At the moment the SerienRecorder web interface opens in a new browser window and not in a new browser tab.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/ed563e04c4f36898d83b279eef4e2b3492589a71/plugin/controllers/base.py#L391

Some time ago the code was changed so that I can decide how the web interface should be opened via addExternalChild.

I think that you can remove the entry "serienrecorderui":
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/ed563e04c4f36898d83b279eef4e2b3492589a71/plugin/controllers/base.py#L389

**Comment by jbleyel** [comment]
Hi @MacDisein, please check this out.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1326

**Comment by MacDisein** [comment]
Ja, mir ist schon klar was geändert werden muss, ich hatte nur nicht damit gerechnet, dass du meinen Änderungswunsch so schnell umsetzen würdest. Der Wunsch kam aus dem VU+ Forum, ich habe das dort diskutiert, auch was wo geändert werden muss und dann beschwert sich genau der User hier mit einem neuen Ticket, weil es nach deiner Änderung nicht mehr funktioniert.
Ich mache am Wochenende eine neue Version, ich arbeite Vollzeit als Softwareentwickler und der SerienRecorder ist nur mein Hobbyprojekt.

**Comment by jbleyel** [comment]
Ich bin auch Vollzeit Dev und alles andere ist privat.
Kein Stress !!!

**Comment by MacDisein** [comment]
Ich verstehe das sowieso nicht, seit Jahren ist eine uralte Version des OpenWebIf auf dem VTI Feed und seit es das neue SerienRecorder Webinterface gibt, und die Leute das im Extras Menü sehen wollen, was ja nur mit einer aktuelleren Version des OpenWebif geht, installieren sich viele täglich ein neues Nightly Build vom OpenWebif und wundern sich dann, wenn mal etwas nicht funktioniert.

**Comment by MacDisein** [comment]
Du kannst den SerienRecorder wieder rausnehmen, die neue Version ist ausgerollt.
Danke!
