### ISSUE TITLE
No icon for pip zap timer and no case for selecting.

### ISSUE THREAD

**Issue by demosat** [E2OpenPlugins/e2openplugin-OpenWebif#1003]
Hi,
They are not possibility for selecting pip zap timer on interface graphic.
No icon for pip zap timer and no case for selecting.

But there had been the possibility with this issue
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/997

And if there was the possibility of adding the language translation of this function thank you
Bests regards

**Comment by jbleyel** [comment]
I don't think so.

That's the commit.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/cc1825060af3ecede946de9af0615c581e494c79

**Comment by demosat** [comment]
I do not understand, I use satdreamgr and I did not check box option "Use as PiP if possible:" on the GUI.
i use enigma2-plugin-extensions-openwebif_1.3.9-e2openpluginsgit20200501_all.ipk
https://zupimages.net/up/20/18/b301.jpg

no check box option "USE as PIP if possible" on the GUI
https://zupimages.net/up/20/18/jizm.jpg

**Comment by jbleyel** [comment]
Hi @demosat, please check the imagedistro value of this output.
http://BOXIP/api/about

**Comment by demosat** [comment]
Hi jbleyel,
Thanks,
This is screenshoot for myBOX/api/about
https://zupimages.net/viewer.php?id=20/18/5zq7.jpg

**Comment by jbleyel** [comment]
my last commit should fix your issue.

**Comment by demosat** [comment]
Thanks you so much. :-)
