### ISSUE TITLE
Bug : wrong URL for timer added from EPG results in no recording

### ISSUE THREAD

**Issue by telemach1337** [E2OpenPlugins/e2openplugin-OpenWebif#1004]
Tuner : RedEagle TwinBox LCD
FW : OpenHDF 6.4 #137
OW : 1.3.9

Using E2m3u2bouquet I add my m3u and source EPG and using EPGimporter I load this source (http://epg.ovh/pl.xml).

- if I add timer manually or from EPG using remote it works and records
- if I add timer manually from OpenWebif using 'add timer' it works and records

timers.xml has this 

<timer begin="1588601280" end="1588601400" serviceref="1:0:1:C:A9D:6A9C:0:0:0:0:http%3a//000.00.00.000%3a25444/QcXXXXXXu/UXXXXXXb/56882:POLSAT VIASAT NATURE" repeated="0" name="b" description="bd" afterevent="auto" eit="6360" tags="" disabled="0" justplay="0" always_zap="0" descramble="1" record_ecm="0" isAutoTimer="0">
</timer>

- if use OpenWebif and select from EPG certain program and then I click on icon 'add timer' then it adds new timer position but different than others

<timer begin="1588601280" end="1588601400" serviceref="1:0:1:C:A9D:6A9C:0:0:0:0:http%253a//000.00.00.000%253a25444/QcXXXXXXu/UXXXXXXb/56882:POLSAT VIASAT NATURE" repeated="0" name="b" description="bd" afterevent="auto" eit="6360" tags="" disabled="0" justplay="0" always_zap="0" descramble="1" record_ecm="0" isAutoTimer="0">
</timer>

so it records but file is empty because of %253a instead of %3 in URL

second issue shows in Timers in Enigma2 menu when entered from remote on TV

https://i.imgur.com/S92YYo3.jpg

timer added using 'add timer' has Stream as source and timer added using EPG has 0.0E

**Comment by jbleyel** [comment]
Please do these steps.

Create a not working timer using openwebif.
Provide the part of the timer.xml of this new timer here.
Delete this timer and create the exact timer using the box OSD and provide the timer.xml again.

I need the differences of the timer.xml

**Comment by telemach1337** [comment]
OK I will do that but have to find a way to proper insert because I did before and the code was deleted by github

**Comment by jbleyel** [comment]
you can make a screenshot or make a txt file

**Comment by telemach1337** [comment]
Here you see the difference

https://0paste.com/66707

**Comment by rdamas** [comment]
Looks like a double encode percent sign: %253a vs %3a (%25 is the "%" sign(

**Comment by telemach1337** [comment]
> 
> 
> Looks like a double encoded percent sign: %253a vs %3a (%25 is the "%" sign)

that's exactly what I wrote in the first post
