### ISSUE TITLE
EPG and timer issues

### ISSUE THREAD

**Issue by telemach1337** [E2OpenPlugins/e2openplugin-OpenWebif#1005]
This is continuation of 

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1004

because I discovered more problems

Timer added from EPG doesn't record but if I go to Timers and then edit that timer and change to Record+Zap then it records but if I try to change back from Record+Zap to Record then the choice is not saved and I have to go to OSD to make this change which results that it records.

Another issue is with timer added from Bouquets - Show EPG for station - Add timer;
timer added like that has serviceref without URL

I emailed details to jbleyel but if more developers want I can share here

**Comment by jbleyel** [comment]
I can't fix this if the timers in timer.xml via OSD and openwebif are equal.
Sorry.

**Comment by telemach1337** [comment]
But there is a difference in timers.xml

https://0paste.com/66853

Do you say that  a timer that after edit has Record+ZAP and can't be undone do just Record is beyond fixing ?

Maybe a workaround will be having an extra code that after adding new timer to timers.xml will do Record+ZAP and then back to Record
