### ISSUE TITLE
Show Streaming Clients in Webif?

### ISSUE THREAD

**Issue by mensa84** [E2OpenPlugins/e2openplugin-OpenWebif#1016]
Hello,

is it possible to see the streaming clients directly in the Webif?
I know that the menu of the box is also possible in the Webif, but if streaming clients would be shown directly in "Receiver informatino" it would be much more comfortable.

Could you please add that information there?

**Comment by jbleyel** [comment]
Yes and No.
It depends on your image.
Some image have the stream client info and some images not.

**Comment by mensa84** [comment]
I have the openATV 6.3 image and see the screen client info in the menu of the box.
So should I find the info also in Webif?

**Comment by jbleyel** [comment]
This info is already implemented via api but not in browser UI.

Please note!!
The transcoded stream will be displayed in reciever info as recording in tuner info section.
The normal stream currently not because there is no tuner info available.

That's why.

Please check this -> 

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/879
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/435

**Comment by mensa84** [comment]
No, I was talking about the "Stream-Clients" where one can see the channel and IP address of the client.

Could one make that available in the Webif please?

https://i.imgur.com/CFy4x1L.png

**Comment by jbleyel** [comment]
I know.
My implementation shows all used tuner with the correspondending channel and stream client.
The last part is not so easy or not possible.

I can try to add the stream clients as extra section without tuner info.

**Comment by mensa84** [comment]
Yes, that would be very cool!
I use a box for me and my brother and it would be very fine if one would see directly in the Webif if any client (and which IP address) is currently streaming over the network.

**Comment by mensa84** [comment]
closed wtithout solution?

**Comment by mensa84** [comment]
So now oke will see the streaming clients in the Webif? Only old Webif or also new one?

**Comment by jbleyel** [comment]
For now only in "normal" webif and not in the responsive design version.
