### ISSUE TITLE
Different ports for streaming in Webif?

### ISSUE THREAD

**Issue by mensa84** [E2OpenPlugins/e2openplugin-OpenWebif#1017]
Hello,

why do I get M3U files with different ports created, when I click on the streaming icon in the Webif?
Please look at the screenshot: https://i.imgur.com/T8usx4H.png

**Comment by jbleyel** [comment]
What is Port 9001?
I don't find 9001 inside of the code.

**Comment by mensa84** [comment]
I also don't know how it came there.
Am I able to configure it that way? I habe a port forwarding from external port 9001 to 8001, but I don't know why the Webif knows that.

**Comment by jbleyel** [comment]
Please check /etc/enigma2/settings and search for config.OpenWebif.streamport

**Comment by mensa84** [comment]
Ok, thx, there I have set that port 9001:

`config.OpenWebif.streamport=9001`

But why isn't it then only used at one area marked on the screenshot and not on both?

**Comment by jbleyel** [comment]
Because of 8001 as fixed value in service m3u or xspf.

**Comment by mensa84** [comment]
But both links do creat a M3U file!
Why is one M3U file created containing port 9001 and the other 8001?? Which sense does this make?

**Comment by mensa84** [comment]
Closed with amy amswer????

**Comment by jbleyel** [comment]
See commit 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/93d387c53bc9e2df921da1e926ea4c230e9605a4

**Comment by mensa84** [comment]
So now the port from the config will be used for both sections?
