### ISSUE TITLE
What is the syntax for sending a username and password in a url?

### ISSUE THREAD

**Issue by gaussey** [E2OpenPlugins/e2openplugin-OpenWebif#1018]
I’ve tried adding &username=xx&password=xxx in both /api/ and /web/ but the interface is still requesting credentials. I need this functionality to enable me to use webhooks to control my E2 box.

**Comment by jbleyel** [comment]
You have to use basic http authentication.
`http://user:Password@IP:PORT/api/...
`

**Comment by gaussey** [comment]
Which doesn’t work, it was the first thing I tried.

**Comment by jbleyel** [comment]
You may have problems if:
* the password is empty
* the password has ':' or '@' inside
* open the link in a browser

I don't know your exact use case and can't help you because of that.
Many users so am i don't have any problems with this link format.
