### ISSUE TITLE
Any chance for a player inside a modern browser?

### ISSUE THREAD

**Issue by mensa84** [E2OpenPlugins/e2openplugin-OpenWebif#1019]
Hello,

is there any chance to get a working stream directly in a modern browser (i.e. Edge)?
HTML 5 or something like that? Or why is thsi not possible, to show the video directly in the browser?

**Comment by jbleyel** [comment]
Duplicate #723

**Comment by wedebe** [comment]
For future readers, here's some background: #issuecomment-576045395
