### ISSUE TITLE
Again changed grab picture ?

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#1031]
Omg, when again somebody changed, that grabed picture before saving is grabed again ? Why this nonsence ?

**Comment by jbleyel** [comment]
What exactly do you mean ?
I don’t have changed this. 
All modifications for PY3 should have no impact.

**Comment by ims21** [comment]
Make screenshoot (with turned off "actualize"), wait some time and then use R-mouse and Save picture as ... 
and you will see, that saved picture is newly grabbed screen and no "paused" picture on screen. If somebody wants really "fresh picture", then it should be configurable somewhere.  I thought, that some time ago it was "save what you see", imho. May be, it is my mistake...

**Comment by jbleyel** [comment]
Do you have checked different browser?

**Comment by ims21** [comment]
Weird ...  It only happens occasionally.
