### ISSUE TITLE
Kodi causes many open files in VuPlus Duo2

### ISSUE THREAD

**Issue by JojoS62** [E2OpenPlugins/e2openplugin-OpenWebif#1033]
**Describe the bug**
VuPlus opens many files /dev/input/event0 until 1356 files are open in enigma2 process and the enigma2 process becomes unresponsive. The WebIF reports 'too many open files and cannot display the html page, streaming stops and the client disconnects. After rebooting the box, it works fine but open files continues again. It takes about 1-2 days until the crash happens.

I've tried a lot to trace the problem and have disabled already many plugins that where not used frequently.
This behaviour seems to be related to using Kodi with VuPlus/Enigma2 plugin. When the clients are not connected, the growing file no. is not observed.

As a workaround, I see now that setting the query interval for the movielist to several hours relaxes the problem. Open file no. is growing much slower, but there are still many /dev/input/event0 files that never gets closed. 
From my understanding, this is the IR hardware access and the client should have nothing to do with the IR in the receiver. The filesize for the movielist request is about 423 kB (>300 movies), the default query interval was 120 s.

I have raised this issue also in the pvr.vuplus repo, but it looks more like a problem in the software on the box. I don't know the exact relations between all the software parts, so if you thing its not a matter of the WebIF, please give me a clue where to ask.

https://github.com/kodi-pvr/pvr.vuplus/issues/293

There is a similier problem about resource leak, maybe its related:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/751

**To Reproduce**
1. start Vu and observe  the no. of open files, e.g. 'lsof  wc -l'
2. access Vu with a Kodi client
3. check the no. of open files after some hours again
4. check the opened files with 'lsof' for the /dev/input/event0 entries

**Expected behavior**
no leaking open files, not open many event0 files

**Screenshots**

**Image (please complete the following information):**

OE-System: OpenVuplus 2.1
Firmware-Version: VTi-Team Image 14.0.6 (2020-02-25-vti-master (216bc5d2a))
Kernel / Treiber: 3.13.5 / 3.13.5-20190429.r0

**Desktop (please complete the following information):**

**Additional context**
thanks for regarding this issue. Further information like Wireshark captures can be supplied.

**Comment by jbleyel** [comment]
#751 is a memory leak in movielist.py of enigma2.
VTi is closed source so please contact the VTi Team to find the leak in movielist.py.

**Comment by jbleyel** [comment]
```
lsof wc -l | grep input
1262	/usr/bin/dvb_server	/dev/input/event0
1802	/usr/bin/enigma2	/dev/input/event0
1802	/usr/bin/enigma2	/dev/input/mouse0
1802	/usr/bin/enigma2	/dev/input/mice

```
call 
/api/movielist
100 times
```
lsof wc -l | grep input
1262	/usr/bin/dvb_server	/dev/input/event0
1802	/usr/bin/enigma2	/dev/input/event0
1802	/usr/bin/enigma2	/dev/input/mouse0
1802	/usr/bin/enigma2	/dev/input/mice

```
