### ISSUE TITLE
Autotimer not working in OpenWebif

### ISSUE THREAD

**Issue by mhn80** [E2OpenPlugins/e2openplugin-OpenWebif#1035]
Since the last update of OpenPLI (7.3) the autotimer plugin is not working any more.
When I click the autotomer menu item in OpenWebif nothing happens.
No error, nothing loads. 
Autotimer is working however. Programs are succesfully added to my timer list.
Autotimer plugin is also working from the Xtrend ET9500 menu in OpenPLI.

When I change the OpenWebif setting from using the new interface style to old, autotimer does work in OpenWebif.

**Comment by jbleyel** [comment]
Please use a browser with developer tools like Chrome and check the error if you open autotimer.

**Comment by mhn80** [comment]
Here's the output from dev tool in Chrome.
![image](https://user-images.githubusercontent.com/69631131/90228295-3fd82c80-de16-11ea-8cbe-dbba14487ffc.png)

**Comment by ims21** [comment]
Is it not vti closed source image ?!

**Comment by jbleyel** [comment]
Please open http://xtrend ... /ajax/at and provide the output
You need to enable the debug switch in openwebif first. (it's the last switch below)

**Comment by mhn80** [comment]
Do you mean this?

![image](https://user-images.githubusercontent.com/69631131/90271902-d596aa80-de5c-11ea-9694-6fe232847b48.png)

I cannot find the debug switch?

**Comment by jbleyel** [comment]
You don't have the latest l18n.py.

**Comment by mhn80** [comment]
> You don't have the latest l18n.py.

it doesn't update? Is it in the openpli repository?
Or do I have to download and install it manually?

**Comment by jbleyel** [comment]
I can only support the files here on github.
Any other repositories are not my responsibility.

**Comment by jbleyel** [comment]
The openwebif for pli should be from here.

SRC_URI = "git://github.com/E2OpenPlugins/e2openplugin-${MODULE}.git;protocol=git"

https://github.com/OpenPLi/openpli-oe-core/blob/release-7.3/meta-openpli/recipes-openpli/e2openplugins/packagegroup-openplugins.bb

**Comment by WanWizard** [comment]
In 7.3-release, OpenWebIf is pinned on fcf12a42d446022a90b7617a297ba676fc6cfcfe.

The TS fails to report that he is using the new design UI, which may be of influence. It works fine in HEAD.

**Comment by stefan1983** [comment]
I've got the same issue with newest 1.3.9 OpenWebif on latest 14.0.6 VTi Image as well as on latest OpenPLI 7.3.

**Comment by stefan1983** [comment]
Reopen? @jbleyel

**Comment by jbleyel** [comment]
You don't have the latest version!!
VTi is only supported if you use the openwebif from github.

Please read the comment from @WanWizard . -> _It works fine in HEAD._
