### ISSUE TITLE
API: webradioFS Web Interface doesn't appear in newer OpenWebif / OpenATV version

### ISSUE THREAD

**Issue by blueicehaller** [E2OpenPlugins/e2openplugin-OpenWebif#1039]
**Describe the bug**
webradioFS Web Interface doesn't appear in newer OpenWebif / OpenATV version.
Was there an API change?
How to implement it?

**To Reproduce**
1. Open OpenWebif
2. append /webradiofs to the URL (Example: http://xpeedlx3/webradiofs )
3. Result:
```
Error 404: Page not found
The requested URL was not found on this server.
```

**Expected behavior**
In _OpenATV 6.3 / enigma2-plugin-extensions-openwebif - 1.3.5+git3383+b79cfb7-r0_ the expected page is shown.

**Screenshots**

**Image (please complete the following information):**
 - OS: OpenATV
 - Version: 6.3 works, 6.4 Error 404 Not found

**Desktop (please complete the following information):**
 - Browser: Mozilla Firefox
 - Version: 80.0.1 (64-Bit)

**Additional context**

**Environment**
2 x Golden Interstar Xpeed LX3:

- Wohnzimmer - Produktiv
  - OpenATV 6.3.0 (2020-02-18)
  - Python 2.7.15
  - enigma2-plugin-extensions-openwebif - 1.3.5+git3383+b79cfb7-r0
  - enigma2-plugin-extensions-webradiofs - 18.15

- Schlafzimmer - Test
  - OpenATV 6.4.20200528 (2020-05-28)
  - Python 2.7.16
  - enigma2-plugin-extensions-openwebif - 1.3.9+git3429+8688157-r0
  - enigma2-plugin-extensions-webradiofs - 19.28

webradioFS Plugin | [Info](https://www.fs-plugins.de/webradiofs/) | [Download](https://www.fs-plugins.de/plugins/)
Discussion that the Plugin is closed source. [add webradioFS? #537](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/537)
[Xpeed LX3, webradioFS Steuerung 404 Not Found, OpenATV 6.4.20200528 (2020-05-28) - OpenATV Forum](https://www.opena.tv/golden-interstar-xpeed-lx3/53446-xpeed-lx3-webradiofs-steuerung-404-found-openatv-6-4-20200528-2020-05-28-a.html)

Same behaviour with E2iPlayer, see [Post #2](https://www.opena.tv/golden-interstar-xpeed-lx3/53446-xpeed-lx3-webradiofs-steuerung-404-found-openatv-6-4-20200528-2020-05-28-a.html#post451011)

**Comment by jbleyel** [comment]
closed source plugins are not supported.

**Comment by jbleyel** [comment]
external plugins needs to use this interface.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/pluginshook.src#L4

**Comment by jbleyel** [comment]
Please check this:

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/453

**Comment by blueicehaller** [comment]
Thank you.
When I call http://xpeedlx3/api/external it shows:
```
{
  "exception": "TypeError(\"FilePath('/usr/lib/enigma2/python/Plugins/Extensions/webradioFS') is not JSON serializable\",)",
  "request": "/api/external",
  "result": false
}
``´

**Comment by jbleyel** [comment]
Please check the call in webradioFS.
The correct syntax is?

addExternalChild( ("webradiofs", root, "Web Radio", '1.0') )

root must be a twisted Resource class.

I can't help you if don't have the source of the webradioFS plugin.

**Comment by jbleyel** [comment]
I will change the addExternalChild function to support more than 4 parameter.

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/09861495e7cce25f833f73816d0a7f59283eb0ab

**Comment by blueicehaller** [comment]
> _@jbleyel wrote_
> 
> Please check this:
> 
> #453

What was your intention that I should have an look at?

I tried on both Receivers to call the pre-installed FAN Control ( _enigma2-plugin-systemplugins-fancontrol - 6.4+git2632+5d93773-r1_ ) by appending /fancontrol to the URL (Example: http://xpeedlx3/fancontrol ) and both show 
```
Error 404: Page not found
The requested URL was not found on this server.
```

**Comment by jbleyel** [comment]
# syntax
# addExternalChild( (Link, Resource, Name, Version, HasGUI, WebTarget) )
# example addExternalChild( ("webadmin", root, "WebAdmin", 1, True, "_self") )

**Comment by blueicehaller** [comment]
Why does it still not work?

```
        if reason == 0 and kwargs.has_key("session"):
                from Plugins.Extensions.WebInterface.WebChilds.Toplevel import
addExternalChild
                from webradioFSSite import webradioFSweb
                from twisted.web import static
                root =
static.File("/usr/lib/enigma2/python/Plugins/Extensions/webradioFS")
                root.putChild("", webradioFSweb())
                f=open("/tmp/wbrfsweb.txt","a")
                if
os.path.exists("/usr/lib/enigma2/python/Plugins/Extensions/WebInterface/web/external.xml"):
                        try:
                                addExternalChild( ("webradiofs", root, "webradioFS", myversion, True) )
                                f.write("use new WebIf\n")
                        except:
                                addExternalChild( ("webradiofs", root) )
                                f.write("Error, fall back to old WebIf\n")
                else:
                        addExternalChild( ("webradiofs", root) )
                        f.write("use old WebIf")
                if
os.path.exists("/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/pluginshook.src"):
                        try:
                                addExternalChild( ("webradiofs", root, "webradioFS", myversion) )
                                f.write("use OpenWebIf\n")
                        except:
                                f.write(str(e)+"\n")
                f.close()
```

**Comment by jbleyel** [comment]
Do we talk about fancontrol or webradio.
Do you have only openwebif or do you have also the webinterface plugin installed?

**Comment by blueicehaller** [comment]
We're talking about webradioFS. I only have OpenWebif but the code contains an detection if old or new is used.
```
root@schlafzimmer-receiver:~# opkg list-installed | grep webi
enigma2-plugin-extensions-openwebif - 1.3.9+git3699+d89a95b-r0
enigma2-plugin-extensions-openwebif-terminal - 1.3.9+git3699+d89a95b-r0
enigma2-plugin-extensions-openwebif-webtv - 1.3.9+git3699+d89a95b-r0
```

**Comment by jbleyel** [comment]
Then open terminal to the box.
Type **init 5** 
Type **enigma2**

Open  http://schlafzimmer-receiver/webradiofs in a browser.

Post the terminal output after open the link here.

Type CTRL+C
Type **init 3**

**Comment by blueicehaller** [comment]
```
19:33:41.9921 dvb/epgcache.cpp:1611 finishEPG [EPGCache] next update in 60 min
19:33:55.2339 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:33:55+0100 [-] "::ffff:192.168.123.97" - - [07/Dec/2020:18:34:12 +0000] "GET /api/statusinfo?_=1607278624993 HTTP/1.1" 200 516 "http://192.168.123.12/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
19:34:10.2424 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:10+0100 [-] "::ffff:192.168.123.97" - - [07/Dec/2020:18:34:12 +0000] "GET /api/statusinfo?_=1607278624994 HTTP/1.1" 200 516 "http://192.168.123.12/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
19:34:25.2554 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:25+0100 [-] "::ffff:192.168.123.97" - - [07/Dec/2020:18:34:12 +0000] "GET /api/statusinfo?_=1607278624995 HTTP/1.1" 200 516 "http://192.168.123.12/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
19:34:32.3724 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:32+0100 [-] Timing out client: IPv6Address(type='TCP', host='::ffff:192.168.123.97', port=62820, flowInfo=0, scopeID=0)
19:34:32.4016 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:32+0100 [-] [OpenWebif] page '/robots.txt' not found
19:34:32.4067 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:32+0100 [-] "::ffff:192.168.123.179" - - [07/Dec/2020:18:34:32 +0000] "GET /robots.txt HTTP/1.1" 404 151 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
19:34:32.5483 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:32+0100 [-] [OpenWebif] page '/webradiofs' not found
19:34:32.5534 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:32+0100 [-] "::ffff:192.168.123.179" - - [07/Dec/2020:18:34:32 +0000] "GET /webradiofs HTTP/1.1" 404 151 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
19:34:32.6569 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:32+0100 [-] [OpenWebif] page '/favicon.ico' not found
19:34:32.6619 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:32+0100 [-] "::ffff:192.168.123.179" - - [07/Dec/2020:18:34:32 +0000] "GET /favicon.ico HTTP/1.1" 404 151 "http://192.168.123.12/webradiofs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
19:34:40.2711 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:40+0100 [-] "::ffff:192.168.123.97" - - [07/Dec/2020:18:34:32 +0000] "GET /api/statusinfo?_=1607278624996 HTTP/1.1" 200 516 "http://192.168.123.12/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
19:34:55.2748 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2020-12-07 19:34:55+0100 [-] "::ffff:192.168.123.97" - - [07/Dec/2020:18:34:40 +0000] "GET /api/statusinfo?_=1607278624997 HTTP/1.1" 200 516 "http://192.168.123.12/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"

```

**Comment by jbleyel** [comment]
The Problem must be here ->

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/db35923e081aa582b09abb3d31410151b784d037/plugin/httpserver.py#L171

A) loaded_plugins does not contain webradiofs in the time of calling HttpdStart
B) something is wrong with this root value: 

```
                root =
static.File("/usr/lib/enigma2/python/Plugins/Extensions/webradioFS")
                root.putChild("", webradioFSweb())
```

**Comment by blueicehaller** [comment]
OK.

And who need to fix that and how?

**Comment by jbleyel** [comment]
I can try this, but i need the full source of the webradioFS plugin.
I't must be the exact version as you have.

**Comment by jbleyel** [comment]
I can only find a closed source version of webradioFS.
I will never install closed source plugins on my box.
Therefore i can't help you.

**Comment by blueicehaller** [comment]
It would be good if you can mention 3rd party open source plugins from that webradioFS (which is unfortunately closed source) can copy that code part of the "interface" to work again.

I would like to understand the basics how OpenWebif is handling and communicating with 3rd party Plugins like webradioFS.

Which Plugin initiate the communication - OpenWebif or the 3rd party plugin?

Does OpenWebif search for files in any path or any other condition and tries to call them via the example call provided in https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1039#issuecomment-737530778 ?

Thank you in advance.

**Comment by jbleyel** [comment]
I have found the problem.
It's the name of the plugin.

All plugins will be loaded by alphabet.
webradioFS will loaded after openwebif.

I will try to fix this.
