### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1042]
**Is your feature request related to a problem? Please describe.**
I'd like to develop/modernise the html templates using the latest html5/css3/es6.

**Describe the solution you'd like**
What level of browser support is there with owif? Do legacy browsers need to be supported?

**Describe alternatives you've considered**
Should I create a brand new set of template as "modern" was done?

**Additional context**

**Comment by jbleyel** [comment]
Feel free.

But .. Please test these Browsers:
Firefox, Chrome on Windows, Mac and Linux
Safari on Mac
IE, Edge on Windows

Please make the changes step by step.
You can start with the responsive parts.
