### ISSUE TITLE
Classic/Old Design - AutoTimer screen fails to open

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1089]
In OWIF, clicking on AutoTImer button under Extras fails to open the AutoTimer editor screen.

Steps to reproduce the behaviour:
1. Use classic design
2. Click on 'AutoTimer'
3. Observe that the editor screen didn't open

http://{box-name_or_address}/ajax/at returns with -
"Processing Failed"

Image :
 - OS: beyonwiz 
 - Version 19.3.20201031

Desktop:
 - Browser Chrome, Edge, Firefox

Additional context:
The other options under Extras (Box Info, Settings, BouquetEditor) do all work.
If I switch to the new (Responsive/Materialize) design, the AutoTimer editor does open.

Can this be fixed please?

Cheers, 
Geoff

**Comment by jbleyel** [comment]
Please provide the full output of http://{box-name_or_address}/ajax/at
You need to enable "Debug - Display Tracebacks in browser".

**Comment by wedebe** [comment]
Adding myself to this thread

**Comment by Grumpy-Geoff** [comment]
> Please provide the full output of http://{box-name_or_address}/ajax/at
> You need to enable "Debug - Display Tracebacks in browser".

I'm sorry, I don't where to do that.

**Comment by Grumpy-Geoff** [comment]
Oh, I found it in enigma2, Plugins, OpenWebif Configuration.  :)

```
web.Server Traceback (most recent call last):
exceptions.KeyError: 'at_reload'
/usr/lib/python2.7/site-packages/twisted/web/server.py:197 in process
196
197
198
/usr/lib/python2.7/site-packages/twisted/web/server.py:257 in render
256
257
258
/DATA/Beyonwiz/19.3/builds/beyonwiz/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+cbc32ffed1-r0/git/plugin/controllers/base.py:211 in render
210
211
212
/DATA/Beyonwiz/19.3/builds/beyonwiz/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+cbc32ffed1-r0/git/plugin/controllers/base.py:123 in loadTemplate
122
123
124
/usr/lib/python2.7/site-packages/Cheetah/Template.py:1005 in __str__
1004
1005
1006
/DATA/Beyonwiz/19.3/builds/beyonwiz/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+cbc32ffed1-r0/git/plugin/controllers/views/ajax/at.py:566 in respond
565
566
567
exceptions.KeyError: 'at_reload'

```

**Comment by wedebe** [comment]
That's me, I'll get a bugfix up in the morning.

**Comment by wedebe** [comment]
@jbleyel , could I get permissions to add labels and assign issues to myself, please?
