### ISSUE TITLE
New design - EPG event info shows empty popup

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1090]
**Describe the bug**
When clicking on an event in the EPG, the resultant popup box doesn't show any event details, it only contains "X" and "Close".
The same empty popup occurs when clicking on the "More Details" hint link of the event name from the Television (channel/services) now/next list.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use new/Responsive design
2. Click on EPG, then click on any event shown, or click on Television, then click on any event name
3. Observe the empty popup

**Expected behaviour**
The resultant popup should contain the event information.

**Screenshots**
Refer screenshots

![OWIF_EPG_empty_event_popup](https://user-images.githubusercontent.com/71379214/97841330-915ecc00-1d20-11eb-9fe5-53d7e795fbad.png)
![OWIF_TV_empty_event_popup](https://user-images.githubusercontent.com/71379214/97841333-93288f80-1d20-11eb-8031-30b4952a10cc.png)

**Image:**
 - OS: beyonwiz
 - Version 19.3.20201031

**Desktop:**
 - Browser - FireFox, Edge

**Additional context**
The event info successfully displays when using the classic design.

Cheers,
Geoff

**Comment by wedebe** [comment]
Hi @Grumpy-Geoff , could you get a console log from the browser of this happening, please? ("Inspect page | Console").

**Comment by Grumpy-Geoff** [comment]
Pardon my ignorance, is that the below that I got from the browser console?
```
GET http://beyonwizt4/ajax/event?idev=62140&sRef=1%3A0%3A19%3A684%3A607%3A1014%3AEEEE0000%3A0%3A0%3A0%3A 500 (Internal Server Error)		jquery.min.js:4 
send	@	jquery.min.js:4
ajax	@	jquery.min.js:4
n.fn.load	@	jquery.min.js:4
loadeventepg	@	vti-responsive.min.js:1
onclick	@	(index):1
```

**Comment by Grumpy-Geoff** [comment]
http://beyonwizt4/ajax/event?idev=1644&sRef=1%3A0%3A16%3A683%3A607%3A1014%3AEEEE0000%3A0%3A0%3A0%3A
The above was shown in the console as _"500 (Internal Server Error)"_. When running the above in a new tab, I observed this error result -
```
web.Server Traceback (most recent call last):
NameMapper.NotFound: cannot find 'begin' while searching for 'event.begin'
/usr/lib/python2.7/site-packages/twisted/web/server.py:197 in process
196
197
198
/usr/lib/python2.7/site-packages/twisted/web/server.py:257 in render
256
257
258
/DATA/Beyonwiz/19.3/builds/beyonwiz/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+cbc32ffed1-r0/git/plugin/controllers/base.py:211 in render
210
211
212
/DATA/Beyonwiz/19.3/builds/beyonwiz/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+cbc32ffed1-r0/git/plugin/controllers/base.py:123 in loadTemplate
122
123
124
/usr/lib/python2.7/site-packages/Cheetah/Template.py:1005 in __str__
1004
1005
1006
/DATA/Beyonwiz/19.3/builds/beyonwiz/release/inihdp/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+cbc32ffed1-r0/git/plugin/controllers/views/responsive/ajax/event.py:89 in respond
88
89
90
NameMapper.NotFound: cannot find 'begin' while searching for 'event.begin'
```

**Comment by wedebe** [comment]
@Grumpy-Geoff ,this should be fixed now.

**Comment by Grumpy-Geoff** [comment]
Hi @wedebe 

Yes, because I tried the change by modifying one of the failing URLs and it returned the expected data, thus I'm sure your fix will work,

Cheers.
