### ISSUE TITLE
Search Type changes to OWIF AutoTimer editor screen can cause AutoTimer plugin to crash

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1091]
**Is your feature request related to a problem? Please describe.**
Changes to OpenWebif's AutoTimer editor screen can allow the user to create AutoTimer definitions which use EPG search types that are not handled in some versions of the AutoTimer plugin.

The OpenWebif changes allow additional search types of "full", "shortdesc", or "title_shortdesc". 
These additional search types have not been implemented in some AutoTimer plugin versions, only search types of "exact", "partial", "start", and "description" are implemented. 

Selecting one of the newer additions results in the AutoTimer plugin crashing.

The OWIF changes appear to have come in with this commit -
_"Sync VTi Openwebif
jbleyel committed on Apr 13"_
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/a83f6f043fd4c6d567aa007363c2e22eb30edd7f#diff-0c00f457364f34092c52f92c42e31f82

**Describe the solution you'd like**
Can OWIF's AutoTimer editor screen pleased be changed to restrict the ability to select the additional search types ("full", "shortdesc", or "title_shortdesc") only for box types that have a corresponding AutoTimer plugin version that supports them?

**Additional context**
I originally reported this as [Issue #399 AutoTimer "search type lookup" crash](https://github.com/oe-alliance/enigma2-plugins/issues/399), in the oe-alliance / enigma2-plugins repository.
There hasn't been any traction there

Cheers,
Geoff

**Comment by wedebe** [comment]
I've had a similar problem for a number of months. I'll investigate if any of my changes have affected it.

@Grumpy-Geoff , could you clarify whether you're using the old/classic or new/responsive interface, please?

**Comment by Grumpy-Geoff** [comment]
Hi wedebe,

The additional search types display in both designs.
I don't know much about this, but I think it is in "at.tmpl" in both old and new designs.  
Perhaps the new design has had the additions for a while, and the change from last April added it to the old design.

The oe-alliance AutoTimer plugin only caters for -
```
typeMap = {
	"exact": eEPGCache.EXAKT_TITLE_SEARCH,
	"partial": eEPGCache.PARTIAL_TITLE_SEARCH,
	"start": eEPGCache.START_TITLE_SEARCH,
	"description": -99
}

```
If the extra search types of "full", "shortdesc", and "title_shortdesc" could be made conditional like the "start" search type below, then I'd be appreciative -
```
#if $types.has_key('start')
	<option value="start">$tstrings['at_start_match']</option>
#end if
```
Exactly how you'd determine the condition, I wouldn't know.
If it helps, the Beyonwiz models show Box Info "Firmware version:" string as, examples -
beyonwiz 19.3.20201011 (19.3-346-g6461e3a)
beyonwiz 19.3.20201102 (19.3-364-g56ff68e)

**Comment by wedebe** [comment]
@Grumpy-Geoff , this should now be fixed.

**Comment by Grumpy-Geoff** [comment]
@wedebe. as the OWIF changes won't be included until we have a new firmware build for the Beyonwiz models, I'm unable to say if it's fixed for me.
However, I'm happy for this to be closed.  If there's an issue when we've new Beyonwiz f/w, then I can either re-open or create a new issue.

Cheers

**Comment by Grumpy-Geoff** [comment]
This issue has returned, but only with the "classic" view.
The additional OpenVTi search types ("full", "shortdesc", or "title_shortdesc") have reappeared.
I can only guess they came in with this commit -
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/971dce522625d27addbbde8747e45a8b955acc21

**Comment by jbleyel** [comment]
What is OpenVTi?

**Comment by jbleyel** [comment]
Please provide the github or similar link to the autotimer plugin source of OpenVTi.

**Comment by Grumpy-Geoff** [comment]
> Please provide the github or similar link to the autotimer plugin source of OpenVTi.

Okay, so I got the name wrong.
It's "VTi".

**Comment by jbleyel** [comment]
VTi is using a very old and modified closed source version of openwebif.
Same for autotimer and other plugins.

No Source .. So Support!

**Comment by jbleyel** [comment]
You can make a pull request with the changes for VTi, but this change should not affect other images.

**Comment by Grumpy-Geoff** [comment]
Someone, somewhere made a change to the E2OpenPlugins OpenWebif codebase in the last month or so.
This change has undone the good work @wedebe did back in November in actioning this feature request.

I don't use VTi - I don't know what it is nor do I care what it is.
I just made a reference to the recent commit merged by you, that may (or may not) have had an impact on the OWIF AutoTimer editor and which re-introduced the three VTi options that will crash the AutoTimer plugin if selected.

**Comment by Grumpy-Geoff** [comment]
> You can make a pull request with the changes for VTi, but this change should not affect other images.

Yet that is exactly what has happened :(

**Comment by jbleyel** [comment]
This commit -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/971dce522625d27addbbde8747e45a8b955acc21
is only for localization.

**Comment by jbleyel** [comment]
The classic selection is different and needs to be adapted like the modern design.

**Comment by Grumpy-Geoff** [comment]
Okay, fair enough.  Then it's some other recent change that has reintroduced the unwanted options -

![AT_Classic_search_type](https://user-images.githubusercontent.com/71379214/105623763-3cca7900-5e57-11eb-86aa-886fab589fe0.png)

As I said, it's not in the Modern view - that is unaffected (its Search type still only has the four options).
The Classic drop-down was fixed originally.
