### ISSUE TITLE
/api/gettags returning empty set

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1092]
**Describe the bug**
`/api/gettags`
returns
```
{
 "result": true,
 "tags": []
}
```
even though individual AutoTimers have tags

**To Reproduce**
Go to `{box_ip}/api/gettags`

**Expected behavior**
All tags should be returned

**Screenshots**

**Image (please complete the following information):**
 - OS: OpenATV
 - Version 6.5

**Desktop (please complete the following information):**
API

**Additional context**

**Comment by jbleyel** [comment]
Please check this file -> /etc/enigma2/movietags

```
	tags = []
	if fileExists(MOVIETAGFILE):
		for tag in open(MOVIETAGFILE).read().split("\n"):
			if len(tag.strip()) > 0:
				tags.append(tag.strip())
	return {
		"result": True,
		"tags": tags
	}

```

**Comment by wedebe** [comment]
Thanks! So should I add unique tags to available dropdown options if they're found in autotimers.xml or are they added programmatically to MOVIETAGFILE at some point?

**Comment by jbleyel** [comment]
MOVIETAGFILE will be used by OSD for new timers and for autotimer.
We should add an tageditor inside of settings.

**Comment by wedebe** [comment]
New PR submitted which will merge movietag file entries and tags found in autotimer xml
