### ISSUE TITLE
New/Responsive design - AutoTimer editor issues

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1095]
1. The "Not before/after" date selection is broken.
Neither date pickers work.
The browser console reports - `The specified value "13.11.20" does not conform to the required format, "yyyy-MM-dd".`

2. The "Enable Filtering" / add action initially shows a weekday filtering value of Monday by default.
When filtering on Weekday, the text input filter field still shows.

3. Edited to add-
Bouquet or Service restrictions not shown

**Comment by Grumpy-Geoff** [comment]
Adding some screenshots.

![NotBefore_full](https://user-images.githubusercontent.com/71379214/98062452-03eabb80-1e89-11eb-8055-5ac776e6460c.png)
![NotBefore_small](https://user-images.githubusercontent.com/71379214/98062448-02b98e80-1e89-11eb-921d-214cedac4966.png)
![Errant_weekday](https://user-images.githubusercontent.com/71379214/98062574-4c09de00-1e89-11eb-95a5-cd708e3c7840.png)

**Comment by Grumpy-Geoff** [comment]
**_The specified value "13.11.20" does not conform to the required format, "yyyy-MM-dd"._**
So the responsive form is using dd.mm.yy format, what is performing the validation and requiring the format to be yyyy-mm-dd?

In an older version of OWIF running on another box I have, using the responsive form, ticking/selecting "Not before:" uses the default date of today and displays as "Not before: 05.11.20"
The same with "Not after:".
Thus, it would appear a change that has occurred in the last few weeks/months has created this "validation" issue.

**Comment by Grumpy-Geoff** [comment]
I've very little (read "no specific") knowledge in this area, but I think it's possibly this change from a week ago -
"AutoTimer page - Searchable tag, channel and bouquet lists" #1084 
@wedebe - any possibility it was this?

**Comment by Grumpy-Geoff** [comment]
Another AutoTimer editor issue in the modern design.
The definition's specified bouquet or service doesn't show after the definition is saved and some time later subsequently retrieved.

Example.
From the AutoTimer definitions file we can see the definition has a bouquet restriction, snippet -
```
<timer name="test - National Nine News (Mon-Thu, Sun)" match="National Nine News" enabled="yes" id="66" from="17:50" to="19:00" offset="5,110" searchType="exact" searchCase="sensitive" overrideAlternatives="1">
 <bouquet>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet</bouquet> <!-- Favourites (TV) -->
 <exclude where="dayofweek">4</exclude>
 <exclude where="dayofweek">5</exclude>
</timer>
```
Yet it's not shown in the editor.
Screenshot -

![AT_Modern_missing_bouquet](https://user-images.githubusercontent.com/71379214/98430509-c8e6c300-20e8-11eb-8a40-f4cbb851a6da.png)

It appears that if the bouquet specified doesn't actually exist (has been deleted), then the first bouquet from the bouquet list is shown.
Otherwise the bouquet name isn't shown even though it does exist.

A similar issue happens with service restrictions -

```
<timer name="test - Mr. Maker" match="mister maker" enabled="no" id="57" avoidDuplicateDescription="2" searchType="start" overrideAlternatives="1">
 <serviceref>1:0:1:2E4:261:3201:EEEE0000:0:0:0:</serviceref> <!-- ABC ME -->
</timer>
```
![AT_Modern_missing_service](https://user-images.githubusercontent.com/71379214/98430512-d1d79480-20e8-11eb-8629-f43e723d094e.png)

**Comment by Grumpy-Geoff** [comment]
Another screwup with bouquets.
I added "Favourites" and "Last Scanned" bouquets to an existing definition and saved.
I the selected an existing different definition from the drop-down list.  The resultant display incorrectly showed the same Favourites and Last Scanned bouquets that I had added to the previous definition even though they're not defined for the current definition, and in addition it didn't show the actual defined bouquet (Favourites (TV)).
```
<timer name="800 Words" match="800 Words" enabled="no" id="22" offset="5,21" avoidDuplicateDescription="1" encoding="UTF-8" overrideAlternatives="1">
<e2service>
<e2servicereference>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet</e2servicereference>
<e2servicename>Favourites (TV)</e2servicename>
</e2service>
</timer>

```

**Comment by Grumpy-Geoff** [comment]
I think it's looking more and more like it was this change that buggered up the bouquet and service display -
_AutoTimer page - Searchable tag, channel and bouquet lists_
@wedebe committed 9 days ago
-- e2openplugin-OpenWebif/sourcefiles/themes/absb/js/vti-responsive-at.js
Oct 29, 2020
https://github.com/wedebe/e2openplugin-OpenWebif/commit/44aa6743599d102d8c67fac043e30ad9e6f1ec3c#diff-edf7eb7e25702f0aade11f3aefbeb73c615efa20b54bc7c413b3e7deefb077ed

**Comment by wedebe** [comment]
> Another screwup with bouquets.
> I added "Favourites" and "Last Scanned" bouquets to an existing definition and saved.
> I the selected an existing different definition from the drop-down list. The resultant display incorrectly showed the same Favourites and Last Scanned bouquets that I had added to the previous definition even though they're not defined for the current definition, and in addition it didn't show the actual defined bouquet (Favourites (TV)).
> 
> ```
> <timer name="800 Words" match="800 Words" enabled="no" id="22" offset="5,21" avoidDuplicateDescription="1" encoding="UTF-8" overrideAlternatives="1">
> <e2service>
> <e2servicereference>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet</e2servicereference>
> <e2servicename>Favourites (TV)</e2servicename>
> </e2service>
> </timer>
> ```

@Grumpy-Geoff , thanks for the level of detail and xml samples 👍🏻 I came across a similar issue with the tags selector to I'll apply the same logic and populate bouquets and services with values found in autotimers.xml

**Comment by wedebe** [comment]
> 2. The "Enable Filtering" / add action initially shows a weekday filtering value of Monday by default.
>    When filtering on Weekday, the text input filter field still shows.

Running an image from 2020-07-02, I can see this is a pre-existing issue but one to be fixed nevertheless.

**Comment by Grumpy-Geoff** [comment]
> Just thinking more on this... should there perhaps be an indication that the channel/bouquet no longer exists?

That'd be great.

A slightly similar issue occurs with the location field - if the directory doesn't currently exist (and it need not as the recording will create the directory), then the directory value doesn't actually show in the form.  Every time you open the AutoTimer definition (or another with the same location value), the non-existent location is added _again_ to the list of bookmarks shown for selection.

**Comment by wedebe** [comment]
> Another screwup with bouquets.
> I added "Favourites" and "Last Scanned" bouquets to an existing definition and saved.
> I the selected an existing different definition from the drop-down list. The resultant display incorrectly showed the same Favourites and Last Scanned bouquets that I had added to the previous definition even though they're not defined for the current definition, and in addition it didn't show the actual defined bouquet (Favourites (TV)).
> 
> ```
> <timer name="800 Words" match="800 Words" enabled="no" id="22" offset="5,21" avoidDuplicateDescription="1" encoding="UTF-8" overrideAlternatives="1">
> <e2service>
> <e2servicereference>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet</e2servicereference>
> <e2servicename>Favourites (TV)</e2servicename>
> </e2service>
> </timer>
> ```

With this one, I intend to
- initially display a list of AutoTimers
- each with an `Edit` button
- a `New` AutoTimer button
- a `Save` button to do that, then return to the list of AutoTimers

...which should hopefully resolve the population issue.

What date is your image from, @Grumpy-Geoff ? I've been making changes on a rolling basis so it's handy for me to refer back to

**Comment by Grumpy-Geoff** [comment]
> What date is your image from, @Grumpy-Geoff ? I've been making changes on a rolling basis so it's handy for me to refer back to

Whatever there was merged as of 2020-11-02.

**Comment by wedebe** [comment]
> > What date is your image from, @Grumpy-Geoff ? I've been making changes on a rolling basis so it's handy for me to refer back to
> 
> Whatever there was merged as of 2020-11-02.

Looks like I've already got the fix in for 
1095#issuecomment-723380959 channel/bouquet repopulation (#1094 - 2020-11-03 🙂) Can you check whenever you flash the latest version and let me know if that problem still occurs?

Per that change, the checkbox is now ticked but no entry appears in the field, however this is an existing bug per 2020-07-02 (see screenshot)

<img width="637" alt="Screen Shot 2020-11-07 at 10 29 38" src="https://user-images.githubusercontent.com/9741693/98438998-54128980-20e6-11eb-84d3-6b9a70fece33.png">
<img width="1287" alt="Screen Shot 2020-11-07 at 10 29 09" src="https://user-images.githubusercontent.com/9741693/98439002-596fd400-20e6-11eb-8638-a465ca9f7039.png">

**Comment by wedebe** [comment]
Fixing the deleted channel will lead to a new issue where the channel won't have a name, just an sref. This is because channels are looked up using `/api/getallservices` which actually only returns all services _that are within bouquets_ - unless I'm missing something (and perhaps Bouquet Editor has the functionality), we'll need a way to reference `lamedb` to map the channel name.

**Comment by wedebe** [comment]
> > Just thinking more on this... should there perhaps be an indication that the channel/bouquet no longer exists?
> 
> That'd be great.
> 
> A slightly similar issue occurs with the location field - if the directory doesn't currently exist (and it need not as the recording will create the directory), then the directory value doesn't actually show in the form. Every time you open the AutoTimer definition (or another with the same location value), the non-existent location is added _again_ to the list of bookmarks shown for selection.

I haven't (knowingly) changed any functionality around the location dropdown but will investigate. Could you check whether the duplicates appear in the xml?

**Comment by Grumpy-Geoff** [comment]
> Fixing the deleted channel will lead to a new issue where the channel won't have a name, just an sref. This is because channels are looked up using `/api/getallservices` which actually only returns all services _that are within bouquets_ - unless I'm missing something (and perhaps Bouquet Editor has the functionality), we'll need a way to reference `lamedb` to map the channel name.

That shouldn't be an issue - if a service is not in any bouquet then it's very likely to be an old reference, and just showing the sref  should be enough to alert the user to choose a new service.

**Comment by Grumpy-Geoff** [comment]
> I haven't (knowingly) changed any functionality around the location dropdown but will investigate. Could you check whether the duplicates appear in the xml?

I didn't (re-)save the definition, but every one after that that I opened and went back to the original had an ever-growing locations list.
It's not a multiple selection so there shouldn't be more than one value written.
There's no concept of valid/invalid locations - they're just bookmarks.  The directory may or may not exist.
One well used trick is to delete a directory once all recordings have been watched.  When a new episode appears in the EPG, the AutoTimer plugin will generate a new timer with the specified location (which doesn't exist).  When the timer is actioned, the directory will be created and the recording written to it.  The appearance of the directory indicates to the user that there's a new episode to view :)

**Comment by wedebe** [comment]
RE `not before`/`not after`, I think `from date`/`to date` would be... more unconfusing 😆
