### ISSUE TITLE
New/Responsive design - IMDb search fails

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1096]
In Television (channel/services) now/next list, the "Show EPG for {service name}" button results in a list of events for the service.
From this resultant list, the "IMDb" button (with hint "Search IMDb") fails.

This appears to be a responsive issue, as similar action succeeds from the classic design.

Cheers,
Geoff

**Comment by wedebe** [comment]
@Grumpy-Geoff - By "fails", are you seeing a new window with no content?

**Comment by Grumpy-Geoff** [comment]
Yes, just an "about:blank" tab from that single channel EPG.

**Comment by Grumpy-Geoff** [comment]
The same "about:blank" tab result occurs when clicking on the IMDb search
button from the "EPG Search" results display (i.e. search for a program,
click on "IMDb" from the resultant display).
