### ISSUE TITLE
New/Responsive design - "City Lights" - Dropdown lists are mostly unreadable

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1097]
With theme mode "City Lights" enabled, the foreground/background colour choice in the dropdown make the lists practically unreadable, as it appears to be using a very pale font colour on a white background  for -

- Movies - Subdirs 
- Settings

 
![CityLights_Movies_Subdirs_ddl](https://user-images.githubusercontent.com/71379214/97956201-072b6c00-1de3-11eb-9394-4724eb915405.png)
![CityLights_Settings_ddl](https://user-images.githubusercontent.com/71379214/97956204-085c9900-1de3-11eb-9dab-79afbce817c0.png)

With the Settings dropdown, the font colour and background change to a readable style once you select a setting to display.  This can't be achieved in the movie list.

Cheers,
Geoff

**Comment by wedebe** [comment]
Hi @Grumpy-Geoff , which browser and version does this happen in? How does the AutoTimer dropdown in that corner appear for you?

I haven't started working on the Movies or Settings pages... yet 😏

**Comment by Grumpy-Geoff** [comment]
Hi wedebe,

Microsoft Edge - Version 86.0.622.61
Firefox - 82.0.2
Google Chrome - Version 86.0.4240.183 

"Select an AutoTimer" dropdown list is fine, thanks :)

**Comment by Azureit** [comment]
Try cleaning browser cache.

**Comment by wedebe** [comment]
Movies now uses system dropdown.

Settings no longer exhibits this behaviour in Chrome.
<img width="1081" alt="Screen Shot 2021-09-02 at 17 30 54" src="https://user-images.githubusercontent.com/9741693/131882400-2c42fc9e-5fa8-42c6-8f71-08ba7202d303.png">

Please feel free to re-open if this still appears to bean issue.
