### ISSUE TITLE
Clarification sought - AutoTimer Parse / Simulate / Test

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1102]
Hi, could someone clarify the difference between Parse / Simulate / Test, please?
Do some apply to the currently-selected/new entry, or all entries in autotimer.xml

Thanks!

**Comment by jbleyel** [comment]
Parse -> Scan EPG and create timer
Simulate -> Scan EPG and list but don't create timer
Test -> Ask the developer of AutoTimer Plugin.

**Comment by Grumpy-Geoff** [comment]
"Simulate (or "Preview" in GUI) matches against the EPG, but doesn't generate/alter timers, nor does it apply uniqueness tests
"Test" will also list the events that didn't match due to bouquet/service/timespan restrictions.  I don't think "Test" is available in the GUI, it's an OWIF special.

**Comment by wedebe** [comment]
Great, thanks!

**Comment by jbleyel** [comment]
"Test" can be ignored in GUI.

Test is 90% like Simulate but not 100%

https://github.com/opendreambox/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L114
https://github.com/opendreambox/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L156

**Comment by wedebe** [comment]
Ok, in that case I'll remove `test` from the responsive button set. Thanks!

**Comment by jbleyel** [comment]
Yep.
