### ISSUE TITLE
grab screenshot uses wrong arg

### ISSUE THREAD

**Issue by adoxa** [E2OpenPlugins/e2openplugin-OpenWebif#1104]
"High resolution" unchecked should grab a 720 width image, but it still grabs a high resolution image. This is because it passes `r=720`, but `grab.py` is testing arg `f`.

**Comment by Grumpy-Geoff** [comment]
The parameter used to be "r".  Typo in the change?
Was:
```
		if "r" in request.args:
			size = request.args["r"][0]
```
Now:
```
		size = getUrlArg(request, "f")
		if size != None:
```
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/b52928713d374765bead43ebb7a5036598661160#diff-f24a33fd431449a78356f3b8edffee8fabe8b320d68c9a48d8734fad2e292dd2L51

**Comment by wedebe** [comment]
Adding myself to this as I'm thinking of adding a select dropdown with resolutions and .ext choices in the responsive config.
