### ISSUE TITLE
Modern design - Movie list changes

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1121]
(i) Show date/time in each entry
Currently, only the day of week is shown, e.g.
_"Footy Classified - 9HD Perth
Wed
88:20 min. / 2.41 GB"_

Hmm, which Wednesday was that?
Therefore, the date and time is also needed.

(ii) When the movie list is initially invoked, please show a spinner to acknowledge the request.
It does subsequently show if altering the displayed directory.

Cheers,
Geoff

**Comment by wedebe** [comment]
@Grumpy-Geoff , this should be fixed in the next build
