### ISSUE TITLE
Classic design - Movie list - day display anomaly

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1122]
Minor display issue.
Day name is repeated when recording date is from this year.
It's shown correctly (as a single day) when date is from a prior year.

Examples:
_Serengeti - New
9HD Perth / **Wed Wed** 01/01, 19:25
99:56 min. / 3.29 GB
Invasion
The families of the Serengeti await the annual great migration._

_Wisting
SBS ONE HD / Mon 30/12/2019, 23:49
83:43 min. / 2.11 GB
Aided by FBI agents Maggie and John, Wisting tracks American serial killer Robert Godwin to a remote farm, but will they manage to keep their mission secret from the press before Godwin bolts?
Consumer Advice: L._

**Comment by jbleyel** [comment]
This is the html code:

```
<div>
#set $da = $tstrings[("day_" + (time.strftime("%w", time.localtime($movie.recordingtime))))]
<span class="tm_title">$movie.eventname</span><br /> $movie.servicename / $da $movie.begintime<br /> $movie.length min. / $movie.filesize_readable
</div>

```

This is py code:

```
fuzzy_rtime = FuzzyTime(rtime)
movie['begintime'] = fuzzy_rtime[0] + ", " + fuzzy_rtime[1] 

```

**FuzzyTime is not part of the OWF.**

**Comment by Grumpy-Geoff** [comment]
But OWIF _is_ doing the display.
So then:
$da is {day}
$movie.begintime is either -
{day} {dd/mm}, {hh24:mi} 
{dd/mm/yyyy}, {hh24:mi}

Then how about conditionally not displaying $da if $movie.begintime already includes it as a prefix (i.e. "day dd/mm, hh:mi")  - if len($movie.begintime) == 16

**Comment by jbleyel** [comment]
This is your example.

9HD Perth / Wed Wed 01/01, 19:25

The fist **Wed** comes from :
```
#set $da = $tstrings[("day_" + (time.strftime("%w", time.localtime($movie.recordingtime))))]
```


The second **Wed** come from:
```
fuzzy_rtime = FuzzyTime(rtime)
movie['begintime'] = fuzzy_rtime[0] + ", " + fuzzy_rtime[1] 

```

**Comment by jbleyel** [comment]
Please check this :

-> https://github.com/openatv/enigma2/blob/6.4/lib/python/Tools/FuzzyDate.py
-> https://github.com/openpli/enigma2/blob/master/lib/python/Tools/FuzzyDate.py

and compare this with the py on your box.

**Comment by Grumpy-Geoff** [comment]
> This is your example.
> 
> 9HD Perth / Wed Wed 01/01, 19:25
> 
> The fist **Wed** comes from :
> 
> ```
> #set $da = $tstrings[("day_" + (time.strftime("%w", time.localtime($movie.recordingtime))))]
> ```
> 
> The second **Wed** come from:
> 
> ```
> fuzzy_rtime = FuzzyTime(rtime)
> movie['begintime'] = fuzzy_rtime[0] + ", " + fuzzy_rtime[1] 
> ```

Yes, so as I said - 
conditionally don't display $da \_if_ the fuzzy time already has the day

**Comment by jbleyel** [comment]
There is only one problem:
I do not have any recordings with this issue on my box.
I cannot reproduce this.

**Comment by Grumpy-Geoff** [comment]
> Please check this :
> 
> -> https://github.com/openatv/enigma2/blob/6.4/lib/python/Tools/FuzzyDate.py
> -> https://github.com/openpli/enigma2/blob/master/lib/python/Tools/FuzzyDate.py
> 
> and compare this with the py on your box.

Our FuzzyDate is quite different, it's the version from OpenVix I believe, and supports "Adaptive date display" -
https://bitbucket.org/beyonwiz/easy-ui-4/src/master/lib/python/Tools/FuzzyDate.py

`getConfigListEntry(_("Use adaptive date display"), config.movielist.use_fuzzy_dates, _("Adaptive date display allows recent dates to be displayed as 'Today' or 'Yesterday'.  It hides the year for recordings made this year.  It hides the day of the week for recordings made in previous years.")),
`

**Comment by Grumpy-Geoff** [comment]
Actually, it's slightly different than I reported.
With "adaptive date display" we can have day descriptions of "Today" and "Yesterday" in the GUI.  But we don't get seem to get "Yesterday" in OWIF.
Examples, today is Monday 9-Nov, "Overhaulin'" was recorded this morning whilst "Motorsport: MotoGP" was recorded yesterday -
```
Overhaulin'
9Rush Perth / Mon Today, 06:55
89:00 min. / 1.86 GB
[Rpt] CNN Hummer Special
A CNN Hummer that saw sterling service in Iraq gets an overhaul in honour of the reporters and soldiers who served there.

Motorsport: MotoGP
10 BOLD / Sun Sun 8/11, 20:25
119:00 min. / 3.70 GB
2020 - Race 13 - Grand Prix Of Europe
Round 13 of the 2020 Grand Prix takes place at the Ricardo Tormo Circuit in Valencia, Spain.
```

I think it gets even worse for non-zero filled single-digit days, months (we shouldn't to take the time into consideration). Ugh!
So we can have, taking into account zero/non-zero filling:
```
Today,         6-bytes
Wed 1/1,       8-bytes
Sun 8/11,      9-bytes
Sun 18/10,    10-bytes
1/9/2019,      9-bytes
1/10/2019,    10-bytes
31/10/2019,   11-bytes
```
So, clearly a length test is out.  So it's messy.
Unless you can do a regular expression pattern match to test for the already-applied prefix -
don't display $da if $movie.begintime =~ ^Today|Sun|Mon|Tue|Wed|Thu|Fri|Sat   
(however you need to write it).

Otherwise, forget it.

**Comment by Grumpy-Geoff** [comment]
> There is only one problem:
> I do not have any recordings with this issue on my box.
> I cannot reproduce this.

As for your test data, I think that's easy to solve.  Simply create a test recording.  
Once the recording has completed, use vi, nano, or even File Commander to edit the {test recording}*.ts.meta file.
Change line 4 to be a Unix timestamp from last year, here's one for 31/12/2019 23:59:59 :)
```1577807999```

```
root@beyonwizt4:~# date --date=@1577807999
Tue Dec 31 23:59:59 AWST 2019
root@beyonwizt4:~#
```

Cheers,
Geoff

**Comment by jbleyel** [comment]
I prefer :
remove this -> 

```
#set $da = $tstrings[("day_" + (time.strftime("%w", time.localtime($movie.recordingtime))))]
```

**Comment by jbleyel** [comment]
How about this:

```
def FuzzyTime(t):
	d = localtime(t)
	n = localtime()
	dayOfWeek = (_("Mon"), _("Tue"), _("Wed"), _("Thu"), _("Fri"), _("Sat"), _("Sun"))

	if d[:3] == n[:3]:
		day = _("Today")
	elif d[0] == n[0] and d[7] == n[7] - 1:
		day = _("Yesterday")
	else:
		day = dayOfWeek[d[6]]
	
	if d[0] == n[0]:
		date = _("%s %02d.%02d.") % (day, d[2], d[1])
	else:
		date = _("%s %02d.%02d.%d") % (day, d[2], d[1], d[0])

	timeres = _("%02d:%02d") % (d[3], d[4])
	return date, timeres

```
