### ISSUE TITLE
Modern design - AutoTimer bouquet name display "corrupted"

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1144]
The bouquet name shows as -

`"1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet.favourites.tv%22%20ORDER%20BY%20bouquet"
`

AutoTimer definition -
```
 <timer name="Pokemon XY" match="Pokemon XY" enabled="yes" from="12:00" to="16:00" overrideAlternatives="1">
  <bouquet>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet</bouquet> <!-- Favourites (TV) -->
 </timer>

```
Bouquet name is valid -
```
root@beyonwizt2:~# cat /etc/enigma2/bouquets.tv
#NAME User - bouquets (TV)
#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet
#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.terrestrial_lcn.tv" ORDER BY bouquet
#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.LastScanned.tv" ORDER BY bouquet
root@beyonwizt2:~#

root@beyonwizt2:~# ls -al /etc/enigma2/userbouquet.*
-rw-r--r--    1 root     root          2629 Sep 17 09:13 /etc/enigma2/userbouquet.LastScanned.tv
-rw-r--r--    1 root     root            26 Aug  3  2017 /etc/enigma2/userbouquet.favourites.radio
-rw-r--r--    1 root     root           912 Oct  8 07:55 /etc/enigma2/userbouquet.favourites.tv
-rw-r--r--    1 root     root         10193 Sep 17 09:13 /etc/enigma2/userbouquet.terrestrial_lcn.radio
-rw-r--r--    1 root     root         10097 Jul  4  2019 /etc/enigma2/userbouquet.terrestrial_lcn.radio.del
-rw-r--r--    1 root     root         10402 Sep 17 09:13 /etc/enigma2/userbouquet.terrestrial_lcn.tv
-rw-r--r--    1 root     root            75 Jan 20  2019 /etc/enigma2/userbouquet.test_non_standard__tv_.tv.del
root@beyonwizt2:~#

```

**Comment by rdamas** [comment]
I tried hard to reproduce this issue, but seemingly can't. Is this still the case for you? Can you make a screen shot?

**Comment by Grumpy-Geoff** [comment]
> Can you make a screen shot?

Sure.

![AT_Modern_bouquet_encoded](https://user-images.githubusercontent.com/71379214/101864790-9c263f80-3baf-11eb-99b4-06a5d81079c8.png)

![AT_Modern_bouquet_encoded_list](https://user-images.githubusercontent.com/71379214/101864788-99c3e580-3baf-11eb-8045-26bf36c9f5fb.png)

**Comment by rdamas** [comment]
I see - the service reference msut not be uri encoded here. I've created a PR (#1194)

**Comment by Grumpy-Geoff** [comment]
Updating issue.
The change was better, but an issue still persists whereby for every definition one opens then a new pure text entry straight from the bouquet predicate in the definition is added to the available bouquets list.

![AT_Modern_bouquet_encoded_list#2](https://user-images.githubusercontent.com/71379214/103971691-35904380-51a6-11eb-848a-152aa205436f.png)
