### ISSUE TITLE
Modern design - Incorrect timer presented for editing

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1145]
From either the multi-EPG (EPG, /#myepg&epgmode=tv) or the now/next EPG (Television, /#tv), if an event with a record timer set is selected, and then the Edit Timer button is chosen, incorrectly the last viewed timer is presented for editing instead of the selected event's timer.

![Wrong_timer_edit_Modern](https://user-images.githubusercontent.com/71379214/99179377-14881500-2758-11eb-805b-9f64e45590d1.png)

If no timer has previously been selected, e.g. if this is the first timer edit for this session, the empty "Add a timer" panel is shown instead.

**Comment by wedebe** [comment]
@Grumpy-Geoff ,if you select a third timer, does it show the first or second event for you?

**Comment by wedebe** [comment]
Also, does this also happen when you attempt to edit a timer from Timers (/#timers) ?

**Comment by Grumpy-Geoff** [comment]
It seems to always be the last opened for edit, opened for add/edit, or if this is the first for the session then empty/new - not the existing timer for the selected event.
There is no issue when editing from the timer list.

**Comment by wedebe** [comment]
Thanks. Any error in the browser console?

**Comment by Grumpy-Geoff** [comment]
Hi @wedebe 
> Thanks @Grumpy-Geoff, are you getting any error in the browser console?

No errors.

> 
> Is there a difference between clicking the timer (left) side or pencil (right) side of the Edit button?

No difference

> 
> Are you closing the edit dialog using the top-right `X`, `Close` button or by clicking outside the edit dialog?

"X" or "Close" button.

> 
> Could you also try pasting
> `$('#TimerModal').modal('show')`
> into the console after each close of your steps above? The edit dialog should appear empty each time.

That gives an empty timer dialog except for start/end times of Now/Now+1hr
> 
> If I send you a js file would you be able to upload to your receiver to test?

Yes I can do that,

> 
> [own thoughts
> 
> * modal not being cleared between clicks?
> * timer list not being saved between edits?
> * second icon assumed target of click event
>   ]

**Comment by wedebe** [comment]
Thanks a mill, Geoff! I've put in what I hope will fix the issue - #1152

**Comment by Grumpy-Geoff** [comment]
Confirm this is fixed
