### ISSUE TITLE
Feature: Stereoscopic support in stream

### ISSUE THREAD

**Issue by fbradyirl** [E2OpenPlugins/e2openplugin-OpenWebif#115]
Hi there,

Would it be possible, for OpenWebif to somehow allow the receiving end to know that a stream is a 3D stereoscopic video? I am trying to get XBMC running on another TV, to auto-detect that the PVR channel is not a normal 3D movie for Sky 3D. 

The way this is done with normal files, is by adding '3DSBS' into the name of the file. 

Obviously, there is no way for me to change the URL for a stream coming from OpenWebif.  I have checked the video properties in XBMC, and I don't see anything different in a 3D source, to a 2D source. Maybe OpenWebif can fill the gap here.

Am I thinking about this the right way, or is there something I'm missing here?

Note: this is a follow on from my discussion here:
https://github.com/PavelKuzub/service.3denabler.samsungtv/issues/1

Thanks a million.
-Finbarr

**Comment by jbleyel** [comment]
no update since years ...
