### ISSUE TITLE
Regression in multiepg

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#1153]
Commits 80f928be and 144425a6 moved an inner function of getMultiEpg() to outside. This newly created function getTimerEventStatus() unfortunately recomputes the partition of timers into services references every time the function is called. Which makes getMultiEpg() noticeable  slower.

Please consider reverting or reworking that change.

**Comment by jbleyel** [comment]
D'accord. The timerlist should be get only once in getMultiEpg().
You should also check the autotimer flag once.
Try / except for autotimer flag is a bad idea.

**Comment by wedebe** [comment]
#1156 retrieves the timer list once and passes it through, instead of each event retrieving it.

**Comment by jbleyel** [comment]
Please change also the Try / except for autotimer flag

**Comment by jbleyel** [comment]
if hasattr(timer, "isAutoTimer"):

**Comment by rdamas** [comment]
It is still not at the level of before the change; the partition of timers into service reference lists is still computed every time the function is called; for me the leads to a more than 1 second delay between the old version and the current version.

**Comment by jbleyel** [comment]
Hi @wedebe ,  please revert to the getTimerEventStatus internal function.
You can change this function like this:

```
	def getTimerEventStatus(event):	
		startTime = event[1]	
		endTime = event[1] + event[6] - 120	
		serviceref = event[4]	
		if serviceref not in timerlist:	
			return None
		for timer in timerlist[serviceref]:	
			if timer.begin <= startTime and timer.end >= endTime:
				basicStatus = 'timer'
				isEnabled = 1
				isAutoTimer = -1
				if hasattr(timer, "isAutoTimer"):
					isAutoTimer = timer.isAutoTimer
				if timer.disabled:	
					basicStatus = 'timer disabled'
					isEnabled = 0
				timerDetails = {
						'isEnabled': isEnabled,
						'isZapOnly': int(timer.justplay)
						'basicStatus': basicStatus
						'isAutoTimer': isAutoTimer,
					}
				return timerDetails
		
		return None
```

**Comment by rdamas** [comment]
Having had a closer look at the code, the issue here with multi epg is:

In multi epg naturally many events are processed; If you have many timers, it is therefore expensive, if you have to check for every event if it has an associated timer. The idea behind the partition is to narrow the list of timers you have to check against to timers of the service reference of the event.

That way the number of comparisons is kept reasonably low.

I don't see an elegant solution other than to either keep the function inline or to pass the timers partition to the function.

**Comment by rdamas** [comment]
The workaround solves the issue; closing here, thanks.
