### ISSUE TITLE
Modern design: Timer list - Start time repeated

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1162]
In the "Timers" list (/#timers), the timer start time is repeated in a full day date/time timezone formatted string after the start/end times.
ddd dd.mm.yyyy hh:mm - dd.mm.yyyy hh:mm **ddd dd mon yyyy hh:mm:ss tz**

![TimerList_additional_start](https://user-images.githubusercontent.com/71379214/99922204-3a21a980-2d6a-11eb-8ffb-a3403e7dd4f4.png)

**Comment by wedebe** [comment]
Already fixed in a recent release :)

**Comment by Grumpy-Geoff** [comment]
Thanks.  It must be a very recent one :) 
I'll close this then.
Ta.
