### ISSUE TITLE
Possible issue with /api/epgsimilar endpoint

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1182]
**Describe the bug**
`/api/epgsimilar?sRef=[SREF]&eventid=[EVID]`
returns an empty result set for an event on a channel that returns a list on the e2 box.

**To Reproduce**
Steps to reproduce the behaviour:
Find an event (specific episode) on a channel that occurs multiple times.
Use that sref and event id with the url `/api/epgsimilar?sRef=[SREF]&eventid=[EVID]`

Result:
```
{
 "events": [], 
 "result": true
}
```

**Expected behavior**
`events` should be populated with events or an error returned.

**Screenshots**
<img width="718" alt="Screen Shot" src="https://user-images.githubusercontent.com/9741693/101334696-21d48300-3870-11eb-9eff-e8f51f06db1a.png">

**Image (please complete the following information):**
 - OS: OpenATV
 - Version 6.4

**Desktop (please complete the following information):**
 - n/a

**Additional context**
STB GUI returns a list of matching events.

**Comment by jbleyel** [comment]
Please do not change the API if empty result!

**Comment by jbleyel** [comment]
There is no BUG.
This is by design,

```
	epgcache = eEPGCache.getInstance()
	events = epgcache.search(('IBDTSENRW', 128, eEPGCache.SIMILAR_BROADCASTINGS_SEARCH, ref, eventid))

```

**Comment by jbleyel** [comment]
That's the code in OSD.

https://github.com/openatv/enigma2/blob/f7ce295ceea7663e607d11277271fc537b1acd7b/lib/python/Screens/EventView.py#L311

**Comment by jbleyel** [comment]
I don't know the difference between 100 and 128

```
OWF -> 
events = epgcache.search(('IBDTSENRW', 128, eEPGCache.SIMILAR_BROADCASTINGS_SEARCH, ref, eventid))

OSD -> 
ret = epgcache.search(('NB', 100, eEPGCache.SIMILAR_BROADCASTINGS_SEARCH, refstr, id))

```

**Comment by wedebe** [comment]
Thanks! Despite trying several events on a number of channels earlier, I could never get a result set. I've finally found a combination that works :)

/api/epgsimilar?sRef=1:0:1:2876:800:2:11A0000:0:0:0:&eventid=24678
[epgsimilar.json.txt](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/5655575/epgsimilar.json.txt)
