### ISSUE TITLE
Api call for service reference

### ISSUE THREAD

**Issue by Headhunter70** [E2OpenPlugins/e2openplugin-OpenWebif#1196]
Hi there,
would it be possible to have a call for the servicename and to get the servicererence as return ?
thx and rgds

**Comment by jbleyel** [comment]
Why? The servicename is not unique.
You probably can get more than one result.

**Comment by Headhunter70** [comment]
I have a little script in my home automation project that allows switching channels via Alexa. Via ap call i think I would be more flexible to find the needed servicerefernces, For now I have a selected number of channels (name:references) in an arraylist.

**Comment by jbleyel** [comment]
As I said. Possible yes but what should be done if the channel name is not unique.
Search only in a specific bouquet, in all bouquets or in the full servicelist?

**Comment by Headhunter70** [comment]
I think in a first stage the search in full service list and returning the first match would be okay, if needed we can think about searching in specific bouquets. My biggest concern would be the time needed for the search. When using getallservices it takes a few seconds for the answer

**Comment by Headhunter70** [comment]
thx jbleyel, working as expected, great job, many many thanks again
