### ISSUE TITLE
Modern - EPG Search from banner bar (shortcut "f") doesn't work

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1198]
The EPG Search from the banner bar returns an empty result, whereas the same search string entered in the EPG search bar on the EPG screen returns results.

**Comment by wedebe** [comment]
So you see a weird-looking [OK] or [GO] button on the far-left just under the search bar?

**Comment by Grumpy-Geoff** [comment]
Yes - "GO"
Hit that or the search icon - nil result.

Ahh, "sstr=click"!!!
![Modern_search_nil_result](https://user-images.githubusercontent.com/71379214/102703122-f907b100-42a5-11eb-92fd-08a74e0bc22e.png)


![Modern_EPGsearch_result](https://user-images.githubusercontent.com/71379214/102703127-fe64fb80-42a5-11eb-990e-31135dd93f26.png)

**Comment by wedebe** [comment]
The [go] button was fixed in 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/959ee7290ef605d0dadb65b9ba6d70380663bc01#diff-e2330d198dabf415b16911095711385f53f72c550165bbd59cc1b6bd49ab5a96

PR #1200 will fix the 'click' search term bug.

**Comment by Grumpy-Geoff** [comment]
Unable to test as yet.
Closing based upon pull request.
