### ISSUE TITLE
/api/zap slow

### ISSUE THREAD

**Issue by rlucassen2** [E2OpenPlugins/e2openplugin-OpenWebif#1203]
I would like to use OpenWebif to control the box using curl or wget. This works well, but zapping from one to another station takes a few seconds on my ET7000, while a remote control zap command (left or right) makes the box zap immediately. When sending a zap command, the json reply takes about two seconds:

`curl http://192.168.64.111/api/zap?sRef=1:0:2:6EF3:445:1:C00000:0:0:0:`
`{`
` "message": "Active service is now '1:0:2:6EF3:445:1:C00000:0:0:0:'", `
` "result": true`
`}`

While zapping using the remotecontrol almost instantly zaps:

`curl 'http://192.168.64.111/api/remotecontrol?command=105'`
`{`
` "message": "RC command '105' has been issued", `
` "result": true`
`}`

Why is the zap taking such a long time? What is webif waiting for?

R.

**Comment by rdamas** [comment]
Doesn't happen here (VU+ Solo4k), switching channels including network overhead happens within 0.3 seconds; how many elements do your bouquets contain? How many bouquets do you have?

**Comment by rlucassen2** [comment]
There are quite a few bouquets, "Hans-13-19-23-28" and 1 favourite bouquet containing 33 FTA radio ID's. The ET7000 is quite a few years old of course, but the difference between "remotecontrol" and "zap" is quite big. I will try to remove the Hans-13-19-23-28 plugin just to see what happens.

**Comment by rlucassen2** [comment]
I removed all the unneccesary bouquets and indeed, there is no difference anymore. Thnx!
