### ISSUE TITLE
HbbTV

### ISSUE THREAD

**Issue by Joey-1970** [E2OpenPlugins/e2openplugin-OpenWebif#1204]
Hello!

Is it possible to get informations with this API, when the user use HbbTV (for example "ARD Mediathek") on a Enigma2-Receiver?

Joachim

**Comment by jbleyel** [comment]
What information do you want?

**Comment by Joey-1970** [comment]
Hello jbleyel,

first: thank you for your reply!

Short: The more, the better! ;-)

A good minimum informations would be, that the receiver is in "HbbTV-Mode", second maybe what kind of provider is running (like in display) f.e. "ARD Mediathek".

Is this possible?

Joachim

**Comment by jbleyel** [comment]
The HbbTV link/url from the current playing service on the box can be easy detect.
But the info if HbbTV is active or not needs to implement in enigma2 code and in the HbbTV plugin.

**Comment by Joey-1970** [comment]
Hello jbleyel,

again thanks for your answer!

I don't no if I unterstood it very well:
To get more information is not possible without changes in the HbbTV-Plugin and the enigma2-code - sad but true.

But how can I detect the current playing service?

Joachim

**Comment by jbleyel** [comment]
No you don't understand.
The current info is already there -> /api/getcurrent
It's possible to make something like this.
-> /api/getcurrenthbbtv
This new request can have the HbbTV link info.
But this is only the info if the current channel has HbbTV and not what you want.

**Comment by bjoernmuenchau** [comment]
@jbleyel: That's exactly what I am looking for! It would be great if you could add the AIT URL (=link to HbbTV app) to either `getcurrent` or create a dedicated endpoint for it. Thanks so much!

**Comment by jbleyel** [comment]
I’m no longer maintaining this git repro.
There is a new one .

-> https://github.com/oe-alliance/OpenWebif

**Comment by jbleyel** [comment]
Hello @bjoernmuenchau :
So you wanna have the HbbTV info in getcurrent or getcurrenthbbtv?
What exactly do you need in the result?
You can provide an example.

But !!

This will be only implemented in the new openwebif.

**Comment by bjoernmuenchau** [comment]
Hello @jbleyel!

Apologies for not opening the issue in the new Openwebif. I just stumbled upon the topic here and of course it would be totally fine to only have the feature in the newer version.

This being said, what I need is to the URL which points to the HbbTV application and that is part of the 
Application Information Table (AIT) within the Program-Specific Information (PSI) in the transport stream, see [here](https://developer.hbbtv.org/guide/launching-hbbtv-applications-from-a-broadcast-channel/introduction-to-ait-and-its-role-in-hbbtv/) for more high level details.

I use OpenPli and the URL is already displayed in the "Service Info" menu but I have no clue how it gets there, see bottom of attached screenshot.

Does that help or do you need more information?
 
![Uploading 1_0_19_283D_3FB_1_C00000_0_0_0_20241230123859.jpg…]()

**Comment by jbleyel** [comment]
Added in version 2.2.1 -> https://github.com/oe-alliance/OpenWebif

**Comment by bjoernmuenchau** [comment]
Thank you very much!
