### ISSUE TITLE
Remove VXGplayer

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1211]
We can remove the VXG, BUT, I do not want to make this decision alone.

See here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1208#issuecomment-758327263

**Comment by rdamas** [comment]
Yes, please do so. It seems to me that for future proof stream support nowadays a DASH implementation is required.

**Comment by Schimmelreiter** [comment]
Why would we want to remove it while it still works (By adding --enable-nacl to the chrome command line) and we do not have a better solution?

![image](https://user-images.githubusercontent.com/2022025/104421315-7b208800-557b-11eb-9416-f8c4e5df1443.png)

**Comment by Schimmelreiter** [comment]
Please note:
That doesn't mean I'm against a cleaner/better solution, only against breaking what we have **before** we have anything better.

**Comment by wedebe** [comment]
How about splitting it off as an installable extension for those who want to keep using it and adding instructions on how to install and run by `adding --enable-nacl to the chrome command line`.

2.3MB per release per image per year for mostly-unknown about functionality would save a _huge_ amount of bandwidth cost!

**Comment by Schimmelreiter** [comment]
That has been implemented as of about day #1 of WebTV/VXG.

https://github.com/oe-alliance/oe-alliance-core/blob/4.4/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-extensions-openwebif.bb#L60-L62

**Comment by wedebe** [comment]
> That has been implemented as of about day #1 of WebTV/VXG.
> 
> https://github.com/oe-alliance/oe-alliance-core/blob/4.4/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugin-extensions-openwebif.bb#L60-L62

Perhaps it's just a case of not automatically building 
`public/vxg/.*$', 'enigma2-plugin-%s-vxg`
`*\.pexe$', 'enigma2-plugin-%s-vxg`
into each enigma image?

**Comment by jbleyel** [comment]
We can also make the split here via travis-ci.
And we should not remove it because it's working with "--enable-nacl".

**Comment by wedebe** [comment]
> We can also make the split here via travis-ci.
> And we should not remove it because it's working with "--enable-nacl".

There are checks for the vgx pexe filepath, I'll go through some tests to make sure there'll be no crash if the vxg plugin isn't installed by default.

**Comment by jbleyel** [comment]
I will update the build script.

**Comment by jbleyel** [comment]
-> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/gh-pages
