### ISSUE TITLE
support .meit files - Editor for the description

### ISSUE THREAD

**Issue by doglover3920** [E2OpenPlugins/e2openplugin-OpenWebif#1212]
The file list of recordings does show the contents of the .eit files of the recordings.

However when you add in the file lists you add an MKV or MP4 file (or AVI etc...) there is no description.
If one installs the TMDB plug-in, one can assign a description to the these files.  This description is stored in a .meit file.
The structure is the same as for the .eit files.
Why there has been chosen to call these files .meit files and not the standard .eit is unknown to me.

My request is:  Can these .meit be shown in the recordings list as you do for .eit files?

Secondly, the existing edit of the recordings is limited to the name only.
Can this be extended to the name, short description and long description in the .eit and .meit files?

**Comment by wedebe** [comment]
I think a preferred solution would be to have the TMDB plugin manage movie descriptions in `.eit` files. Otherwise, OpenWebif could end up having to support a multitude of external extensions and changes to same to avoid OpenWebif crashes.

**Comment by doglover3920** [comment]
TMDB could of course be changed to use the .eit filename.
However an .eit file is not shown in OpenWebif is the file is a .mkv or .mp4.
So you still have to enabled this.

And a .meit file is exactly the same as an .eit file.  There is no difference.

**Comment by jbleyel** [comment]
The openwebif do not read the EIT file, this is part of enigma2.

**Comment by jbleyel** [comment]
**Your second question:**
_Secondly, the existing edit of the recordings is limited to the name only.
Can this be extended to the name, short description and long description in the .eit and .meit files?_
**Answer:** 
_Definitely not!_

The name change is only a rename of the file.

The EIT format description is here -> https://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.05.01_40/en_300468v010501o.pdf

Trust me .. I have made an EIT Editor as part of e2Remote for Mac.
