### ISSUE TITLE
Wrong about on OpenPLI 8

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1216]
This is an example xml result of /web/about on OpenPLI 8

I't looks like standby.

The e2servicename is wrong and should be empty.

```
<e2abouts>
	<e2about>
		<e2oeversion>PLi-OE</e2oeversion>
		<e2enigmaversion>2021-01-11-release-8.0</e2enigmaversion>
		<e2distroversion>openpli</e2distroversion>
		<e2imageversion>8.0-release</e2imageversion>
		<e2driverdate>20151124</e2driverdate>
		<e2webifversion>OWIF 1.4.0</e2webifversion>
		<e2fpversion>0</e2fpversion>
		<e2model>Solo</e2model>
		<e2lanmac>xx</e2lanmac>
		<e2landhcp>True</e2landhcp>
		<e2lanip>xx</e2lanip>
		<e2lanmask>255.255.255.0</e2lanmask>
		<e2langw>xx</e2langw>
		<e2tunerinfo>
			<e2nim>
				<name>Tuner A</name>
				<type>BCM7325 DVB-S2 NIM (internal) (DVB-S2)</type>
			</e2nim>
		</e2tunerinfo>
		<e2servicename>FROM BOUQUET &amp;quot;userbouquet.favourites.tv&amp;quot; ORDER BY bouquet</e2servicename>
		<e2servicenamespace>0</e2servicenamespace>
		<e2serviceaspect>N/A</e2serviceaspect>
		<e2serviceprovider></e2serviceprovider>
		<e2videowidth>N/A</e2videowidth>
		<e2videoheight>N/A</e2videoheight>
		<e2servicevideosize>N/AxN/A</e2servicevideosize>
		<e2apid>N/A</e2apid>
		<e2vpid>N/A</e2vpid>
		<e2pcrpid>524297</e2pcrpid>
		<e2pmtpid>524296</e2pmtpid>
		<e2txtpid>524296</e2txtpid>
		<e2tsid>0</e2tsid>
		<e2onid>0</e2onid>
		<e2sid>0</e2sid>
	</e2about>
</e2abouts>
```

**Comment by jbleyel** [comment]
@PLi Team .. Please take over.

**Comment by WanWizard** [comment]
No idea what this is about, if I check on my box, e2servicename is empty in standby.

However, if I check another box that I've just updated and rebooted, it does have an e2servicename. If I check the OWIF interface, it says "BBC One HD   -   N/A" instead of "Nothing playing", and the Television/Current tab also displays "BBC One HD", even though the box starts up to standby:

![image](https://user-images.githubusercontent.com/456954/115423881-187ffd80-a1f6-11eb-8e7c-e3cc6e83d6ae.png)

**Comment by WanWizard** [comment]
Difference between the boxes is that this H9 doesn't have any local DVB-S tuners active, it uses OpenPLi's fallback tuner to pull a stream in my main box, and BBC One HD is my startup channel.

**Comment by jbleyel** [comment]
The e2servicename should be empty or N/A in standby if you call  
/web/about 

Then name comes from:
```
info = session.nav.getCurrentService().info()
info.getName()
```

**Comment by jbleyel** [comment]
The code of serviceinfo.py is a little bit different.

```

			if self.session.nav.getCurrentlyPlayingServiceOrGroup():
				name = ServiceReference(self.session.nav.getCurrentlyPlayingServiceReference()).getServiceName()
				refstr = self.session.nav.getCurrentlyPlayingServiceReference().toString()
				reftype = self.session.nav.getCurrentlyPlayingServiceReference().type
			else:
				name = _("N/A")
				refstr = _("N/A")
				reftype = 0
```

**Comment by WanWizard** [comment]
Where is this code from?

**Comment by WanWizard** [comment]
The e2servicename is not empty on my H9, it also says "BBC One HD".

**Comment by jbleyel** [comment]
This is the current code from OWF:
```
info = session.nav.getCurrentService().info()
info.getName()

```

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/services.py#L135

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/services.py#L162

**Comment by WanWizard** [comment]
If I switch the box on, zap once, and but it back in standby, the channel disappears in OWIF. So it is related to the startup channel configured in Enigma, which it switches to when it starts up.

**Comment by jbleyel** [comment]
It's seams there is a wrong value on startup in session.nav.getCurrentService().info().

**Comment by WanWizard** [comment]
I'll see if I can have one of the devs have a look...

**Comment by WanWizard** [comment]
Afaik this should be addressed, I can't reproduce it anymore on the current develop.
