### ISSUE TITLE
Modern - AutoTimer editor - broken filtering

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1218]
The AutoTimer definition -
```
 <timer name="Studio 10 (weekend)" match="Studio 10" enabled="yes" id="75" searchType="start" searchCase="sensitive" overrideAlternatives="1">
  <serviceref>1:0:19:684:607:1014:EEEE0000:0:0:0:</serviceref> <!-- 10 HD -->
  <include where="dayofweek">weekend</include>
 </timer>

```
Refer screenshot -
Predicate value is not shown
Entire filter entry is not editable

![AT_Modern_filtering#1](https://user-images.githubusercontent.com/71379214/105621120-3cbe7f00-5e3f-11eb-8426-ed88b006fab1.png)

In another example, the predicate value is shown but the entry is still not editable -

![AT_Modern_filtering#2](https://user-images.githubusercontent.com/71379214/105621119-3b8d5200-5e3f-11eb-84ac-f1e70bbd949e.png)

**Comment by wedebe** [comment]
I'm in the process of working the AutoTimers page and will take this into account.

**Comment by wedebe** [comment]
This appears to have been by design. I've tested it using an image from July 2020 and the same occurs. It seems existing filters need to be deleted and new values set, which isn't very user friendly.

**Comment by wedebe** [comment]
`on weekday` and `on weekend` will show no `day` values as they are implied, however the layout does look wrong.

 <img width="1065" alt="Screen Shot 2021-02-28 at 01 25 14" src="https://user-images.githubusercontent.com/9741693/109405024-f1c6e880-7963-11eb-8889-c913d7f4ba7b.png">

**Comment by jbleyel** [comment]
Weekend has no value but weekday should have a value?
You can show "<N/A>" or Sa./So. if weekend and disable the textfield.
The classic Autotimer has no Weekend.

**Comment by wedebe** [comment]
`weekday` is used as both the `select` form field name, and the text equivalent of all days in the range `mon-fri`

I agree, `N/A` would be more intuitive than a blank, disabled field.

**Comment by jbleyel** [comment]
The Autotimer plugin has no weekend filter.
For weekend you need 2 separate filter one for Sa. and one for So.

https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L332

**Comment by Grumpy-Geoff** [comment]
> The Autotimer plugin has no weekend filter.
> For weekend you need 2 separate filter one for Sa. and one for So.
> 
> https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L332

Yes it does.
The value "weekend" is handled in "checkExcluded" (as is "weekday")
https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerComponent.py#L355

**Comment by jbleyel** [comment]
Maybe .. But there is not api call here 
-> https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L332

**Comment by Grumpy-Geoff** [comment]
> Maybe .. But there is not api call here
> -> https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L332

Isn't that just populating the attributes of the autotimer definition before it's written?

Here's a definition -
```
 <timer name="Gogglebox" match="Gogglebox" enabled="yes" id="3" searchType="start" overrideAlternatives="1">
  <bouquet>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet</bouquet> <!-- Favourites (TV) -->
  <exclude where="title">Encore</exclude>
  <exclude where="dayofweek">weekend</exclude>
 </timer>
```

Here's the UI editor of the same -

![AT_wday_wend](https://user-images.githubusercontent.com/71379214/109579118-48365180-7b33-11eb-9200-213d2e594e9a.jpg)

**Comment by jbleyel** [comment]
Sorry, my fault.
Weekday can be a single day, weekday or weekend.

**Comment by Grumpy-Geoff** [comment]
> `on weekday` and `on weekend` will show no `day` values, as they are implied, however the layout does look wrong.

To even it up, instead of `on weekday` and `on weekend`, you could have `on day` with selectable days of the week plus the weekday and weekend values
```
Include   On day   Monday
Include   On day   Weekend
```

**Comment by wedebe** [comment]
Still working on AutoTimers, here's what I've got so far for the filters issue. (Note that I haven't yet updated the dropdown `on weekday` text to `on days`. Feedback appreciated.

<img width="1101" alt="" src="https://user-images.githubusercontent.com/9741693/111003614-6136d200-837f-11eb-9eca-dcea5dafd93f.png">

<img width="1107" alt="" src="https://user-images.githubusercontent.com/9741693/111003618-61cf6880-837f-11eb-9c5c-dc9f3e2759e0.png">

**Comment by wedebe** [comment]
@Grumpy-Geoff , #1302 reworks AutoTimers js completely, including filters functionality.

**Comment by Grumpy-Geoff** [comment]
> @Grumpy-Geoff , #1302 reworks AutoTimers js completely, including filters functionality.

@wedebe - There appears to now be a mismatch between the GUI plugin and these changes, "weekday" and "weekend" GUI values aren't catered for -
`  <exclude where="dayofweek">weekend</exclude>
`

**Comment by Grumpy-Geoff** [comment]
@wedebe
Hi Ben,
There's been no response.
Are you intending to put back "weekday" and "weekend" values? 

Cheers,
Geoff

**Comment by Grumpy-Geoff** [comment]
@wedebe 
It's been nearly 2 months now since I reported #1302 broke the AutoTimer filtering.
I see there's _still_ been no change to the weekday/weekend filtering that was left out of the updated editor.

The definition is displayed as -
Studio 10 (weekend)   
Certain days, any time
10 HD

The autotimer.xml definition has "weekend" filtering -
```
 <timer name="Studio 10 (weekend)" match="Studio 10" enabled="no" id="75" searchType="start" searchCase="sensitive" overrideAlternatives="1">
  <serviceref>1:0:19:684:607:1014:EEEE0000:0:0:0:</serviceref> <!-- 10 HD -->
  <include where="dayofweek">weekend</include>
 </timer>
```

Once this definition is opened with the modern interface's AutoTimer editor, the day filtering is changed to Monday -
`  <include where="dayofweek">0</include>`


Given there's been no acknowledgement of the issue - I'll not be bothering with the Modern interface, as a "pretty" but functionally deficient editor isn't of use to me.

**Comment by Grumpy-Geoff** [comment]
Changes were made to weekday/weekend filtering
