### ISSUE TITLE
Modern - AutoTimer editor - wrong times shown for "Simulate" results

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1219]
On some entries of the parse simulation, the minutes have replaced the hours value

![AT_Modern_Simulate](https://user-images.githubusercontent.com/71379214/105621371-bd7e7a80-5e41-11eb-9ed8-faa4d50cfe29.png)

I'm guessing the result is purely from a formatting error, as it is correctly shown in the Classic i/f

![AT_Classic_Simulate](https://user-images.githubusercontent.com/71379214/105621370-bce5e400-5e41-11eb-9006-12e21ac6e941.png)

**Comment by wedebe** [comment]
I'm in the process of working the AutoTimers page and will take this into account.

**Comment by wedebe** [comment]
Hi @Grumpy-Geoff , sorry I know I've asked this before, but which language do you use on the box and on your browser?

**Comment by Grumpy-Geoff** [comment]
> Hi @Grumpy-Geoff , sorry I know I've asked this before, but which language do you use on the box and on your browser?

For browser, this?
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1098#issuecomment-723511887

Where do I find the enigma2 language setting?

**Comment by wedebe** [comment]
If you do a view source, you'll see `<html lang="...`

**Comment by Grumpy-Geoff** [comment]
> If you do a view source, you'll see `<html lang="...`

Okay, the OWIF page shows
`<html lang="en_GB">`
