### ISSUE TITLE
movies.py - cannot find 'split' 

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1220]
Occurs in both Classic and Modern view.
`http://beyonwizu4/ajax/movies?dirname=/media/usb/Recordings/Blood%20+%20Thunder_%20The%20Sound%20Of%20Alberts`

/plugin/controllers/views/responsive/ajax/movies.py:137 in respond
136
137
138
NameMapper.NotFound: cannot find 'split' while searching for 'split'

/plugin/controllers/views/ajax/movies.py:129 in respond
128
129
130
NameMapper.NotFound: cannot find 'split' while searching for 'split'

Directory -
`root@beyonwizu4:/media/usb/Recordings/Blood + Thunder_ The Sound Of Alberts#`
I suspect it's the "+" in the directory name not being encoded to %2B, as the below works -
```
http://beyonwizu4/ajax/movies?dirname=/media/usb/Recordings/Blood+%2B+Thunder_+The+Sound+Of+Alberts
http://beyonwizu4/ajax/movies?dirname=/media/usb/Recordings/Blood%20%2B%20Thunder_%20The%20Sound%20Of%20Alberts
```

**Comment by jbleyel** [comment]
Who is caller of the link?

**Comment by jbleyel** [comment]
I have found only this line:

`<button onclick="load_maincontent_spin('ajax/movies?dirname='+escape('$path'));">$dir</button>`

**Comment by jbleyel** [comment]
You can try this for testing.

`<button onclick="load_maincontent_spin('ajax/movies?dirname='+escape('$path').replace('+','%2B'));">$dir</button>`

**Comment by Grumpy-Geoff** [comment]
> Who is caller of the link?

OWIF -
![OWIF_Movies_USB_selection](https://user-images.githubusercontent.com/71379214/105837825-32041580-600a-11eb-8287-f5abe31439c8.png)

In console -
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://beyonwizu4/ajax/movies?dirname=/media/usb/Recordings/Blood%20+%20Thunder_%20The%20Sound%20Of%20Alberts

**Comment by Grumpy-Geoff** [comment]
> You can try this for testing.
> 
> `<button onclick="load_maincontent_spin('ajax/movies?dirname='+escape('$path').replace('+','%2B'));">$dir</button>`

How/where do I test that?
I already stated using "%2B" works -
> I suspect it's the "+" in the directory name not being encoded to %2B, as the below works -
> ```
> http://beyonwizu4/ajax/movies?dirname=/media/usb/Recordings/Blood+%2B+Thunder_+The+Sound+Of+Alberts
> http://beyonwizu4/ajax/movies?dirname=/media/usb/Recordings/Blood%20%2B%20Thunder_%20The%20Sound%20Of%20Alberts
> ```

**Comment by jbleyel** [comment]
I'll check this.

**Comment by Grumpy-Geoff** [comment]
> You can try this for testing.
> 
> `<button onclick="load_maincontent_spin('ajax/movies?dirname='+escape('$path').replace('+','%2B'));">$dir</button>`

I have the skills to modify -
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/movies.tmpl
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/responsive/ajax/movies.tmpl
... but how do I generate those locally modified template files (movies.tmpl) into python .py source files (which would then get compiled at run time into optimised .pyo files, AFAIUI).
