### ISSUE TITLE
Keine Einstellmöglichkeit für H.265 in den Transkodingeinstellungen im Webinterface 

### ISSUE THREAD

**Issue by zeini** [E2OpenPlugins/e2openplugin-OpenWebif#1222]
Es gibt im Webinterface keine Einstellmöglichkeit für H.264, bzw. H.265  in den Transkodingeinstellungen
![grafik](https://user-images.githubusercontent.com/942674/106313009-d2a34100-6267-11eb-80b6-743fbec272d3.png)

Direkt am Receiver gibt es diese Möglichkeit in den Einstellungen.
![grafik](https://user-images.githubusercontent.com/942674/106313225-257cf880-6268-11eb-9285-47ebb097eccb.png)

Es wäre fein, wenn man das auch im Webinterface einstellen könnte.

**Comment by jbleyel** [comment]
Die Einstellungen sind dynamisch. 

Das openwebif holt sich die Infos aus dieser Datei.

/usr/share/enigma2/setup.xml

..sowie aus diesen Dateien:

/usr/lib/enigma2/python/Plugins/*/*/setup.xml

This needs to be done in enigma2.

**Comment by jbleyel** [comment]
Please provide the link to the source of the transcoding plugin.

**Comment by zeini** [comment]
I don't know the source of the transcoding plugin. But this is a systemplugin on my box Zgemma H8.Twin, named MultiTransCodingSetup. 
And in  /usr/lib/enigma2/python/Plugins/SystemPlugins/MultiTransCodingSetup/setup.xml there is no entry for video codec
<setupxml>
	<setup key="transcoding" title="Transcoding Setup" showOpenWebIF="1">
		<item level="0" text="Encoder Bitrate" description="Setup your timezone.">config.plugins.transcodingsetup.bitrate</item>
		<item level="0" text="Encoder Framerate" description="Setup your timezone.">config.plugins.transcodingsetup.framerate</item>
		<item level="0" text="Encoder Resolution" description="Setup your timezone.">config.plugins.transcodingsetup.resolution</item>
		<item level="0" text="Encoder Aspect Ratio" description="Setup your timezone.">config.plugins.transcodingsetup.aspectratio</item>
		<item level="0" text="Encoder Interlaced" description="Setup your timezone.">config.plugins.transcodingsetup.interlaced</item>
	</setup>
</setupxml>

**Comment by jbleyel** [comment]
That's the problem.

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/oe-alliance-plugins/issues/390
