### ISSUE TITLE
Responsive EPG list on mobile devices

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1223]
<img width="488" alt="Bildschirmfoto 2021-01-30 um 22 50 30" src="https://user-images.githubusercontent.com/964927/106368931-bf6aa100-634d-11eb-80f2-3f05335bfb74.png">

**Comment by Doc-Theo** [comment]
The question is: "What is the question?"
The screenshot seems to be cut off at the right side. Or the mobile UI does not fit into the screen.
Okay, I can confirm that. I think a solution could be put the "control buttons" below the "progress bar".
That would result in less Channel per page and thus in more up and down scrolling. 
![OWIF_Mobile](https://user-images.githubusercontent.com/78260427/106382971-41e17800-63c3-11eb-8614-16387fd2e393.jpeg)

**Comment by wedebe** [comment]
I had played around with a solution ages ago using dev tools but forgot to save before I refreshed 🤦🏻‍♂️

It's certainly possible, perhaps removing the progress bar to start?
