### ISSUE TITLE
Remove old /mobile webif

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1224]
I would suggest we remove the old mobile UI and show the responsive UI instead.

What do you think?

<img width="542" alt="Bildschirmfoto 2021-01-30 um 23 11 22" src="https://user-images.githubusercontent.com/964927/106369297-87189200-6350-11eb-8128-cda8baca96a3.png">

**Comment by Doc-Theo** [comment]
Hello @jbleyel !
After switching a lot back and forth between the "classic" design with different themes and the new responsive design, I would agree and recommend to completely drop the old UI and use the new responsive design exclusively. Best regards, T. (aka theos2)

**Comment by wedebe** [comment]
I agree. I've never seen the mobile interface during mobile device testing - does the detection even work still? 🤔

Happy to take this on if someone makes the final call.

**Comment by jbleyel** [comment]
I will do the change if #1223 is fixed.

**Comment by Doc-Theo** [comment]
I do agree. Drop the old stuff and go for the new modern look!

**Comment by wedebe** [comment]
> I will do the change if #1223 is fixed.
#1233 has been rectified :)

<img width="381" alt="Screen Shot 2021-09-02 at 17 38 59" src="https://user-images.githubusercontent.com/9741693/131883697-db65c1bd-35bd-4e7d-85d1-2650ec5a309e.png">

**Comment by jbleyel** [comment]
I have prepared the new mobile UI but not activated.
-> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/root.py#L108

**Comment by wedebe** [comment]
Update on mobile detection:
[User-Agent Client Hints](https://web.dev/migrate-to-ua-ch/)

[Can I use... HTTP request header: `Sec-CH-UA-Mobile`](https://caniuse.com/mdn-http_headers_sec-ch-ua-mobile)

**Comment by jbleyel** [comment]
Looks like not supported in Safari.

**Comment by jbleyel** [comment]
Will be fixed in 2.0
