### ISSUE TITLE
Selection of the displayed "Remote Control" ...more options?

### ISSUE THREAD

**Issue by Doc-Theo** [E2OpenPlugins/e2openplugin-OpenWebif#1225]
Hi,
as far as I have found out, there are only two possible choices on which type of remote control is shown.
You can either have the "digital/virtual" remote control or the "analogue" look.
Is there any way to add more choices for the remote control?
Or is the "analogue look" necessarily attached to the box type that is detected by OpenWebif?

<img width="305" alt="Remote_Virtual" src="https://user-images.githubusercontent.com/78260427/106381535-bfa08600-63b9-11eb-9d82-bd4ddab5fa7a.png">
<img width="292" alt="Remote_Original" src="https://user-images.githubusercontent.com/78260427/106381540-c29b7680-63b9-11eb-8b16-0282b4b093ca.png">

**Comment by wedebe** [comment]
There's an option to show `Full remote`, which in this case is the Vu image.
<img width="298" alt="Screen Shot 2021-02-03 at 14 25 08" src="https://user-images.githubusercontent.com/9741693/106760737-03022b00-662c-11eb-9448-cfb69550aa77.png">

The grid-layout remote (top image here) has arrows to expand with more buttons above and below.
<img width="298" alt="Screen Shot 2021-02-03 at 14 28 15" src="https://user-images.githubusercontent.com/9741693/106760810-16ad9180-662c-11eb-83c9-bce1584851e0.png">

Could you provide more detail on your query `Is there any way to add more choices for the remote control?`, please?

**Comment by Doc-Theo** [comment]
Well, of course I have already seen the way to expand the view on the digital remote control.
My very own screenshot shows the "extended view".
But I do not have the choice to change the look of the virtual Remote control. The remote control picture always shows the same picture (VU+ Type 4).
I hope I have made my issue clear.

**Comment by jbleyel** [comment]
Hi @Doc-Theo, the picture of the remote is based on the model detection.
It's normally useless to show a remote for a different model.
There is only one picture in OWF for each model, as i know.

**Comment by Doc-Theo** [comment]
Okay! This issue can be marked as "answered and solved".
Thank you for the answers!   ;-)
