### ISSUE TITLE
multi epg timeline channel display issue if name is longer

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1227]
<img width="259" alt="Bildschirmfoto 2021-01-31 um 15 58 28" src="https://user-images.githubusercontent.com/964927/106388121-4b77d980-63dd-11eb-9a12-c2f63a986bbb.png">

**Comment by wedebe** [comment]
🤔 Should we show channel name text along with the picon or do what's done elsewhere and show one or the other?

**Comment by jbleyel** [comment]
I think we have only a few long channelnames.
We can do smaller font or more space or truncate.

I prefere smaller font and more space.

**Comment by wedebe** [comment]
Fixed submitted - #1262
