### ISSUE TITLE
Movie / recording search

### ISSUE THREAD

**Issue by AnTri** [E2OpenPlugins/e2openplugin-OpenWebif#1230]
Hello, 
I have updated from version 1.28 VTI to the current version 1.43. After the update I can no longer search in my recordings/movies. Until now I could search the movie list with Ctrl+M. Does this function no longer exist?

**Comment by jbleyel** [comment]
@rdamas : Could you please check this. Thanks.
I don't find any shortcuts here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/views/responsive/main.tmpl#L120

**Comment by rdamas** [comment]
I've never used the modern design extensively, and I can't find any shortcuts neither, except for this code:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/5fd360953f988e21f1bd7276c565fb11c441c761/sourcefiles/modern/js/vti-responsive.js#L964

That seems to be identical to the code in the old sources I've searched.

**Comment by jbleyel** [comment]
I think, it's there -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/modern/js/vti-responsive.js#L64

**Comment by jbleyel** [comment]
Shortcut m is used to open recordings and also opens the moviesearch.
Chrome/Safari Mac -> control + option + m

**Comment by AnTri** [comment]
Does the search function (and shortcut) work for you? Search is not working for me. Can the search be called without a shortcut?

**Comment by jbleyel** [comment]
The shortcut only works if you see the movie search button on top.
This movie search button will only displayed if you image distribution is VTi.

@rdamas : can you please check this : 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/fe629f03b2ff5b9ca64cd5ac137b4043d4811786/plugin/controllers/base.py#L428

**Comment by AnTri** [comment]
I've no movie search button. I'm using VTI 15 on my VU Ultimo 4K (last screenshot)

![image](https://user-images.githubusercontent.com/6997604/107849893-7bbc7080-6dfe-11eb-8f5a-4f7822cb1cc1.png)

![image](https://user-images.githubusercontent.com/6997604/107849902-8c6ce680-6dfe-11eb-9525-3f0e85e1aeb1.png)
![image](https://user-images.githubusercontent.com/6997604/107849908-955db800-6dfe-11eb-8fdf-94a3b757a742.png)

![image](https://user-images.githubusercontent.com/6997604/107849936-baeac180-6dfe-11eb-9e2d-c1f94c49b657.png)

**Comment by jbleyel** [comment]
The movie search button should be displayed with my last commit.

**Comment by AnTri** [comment]
Thanks, how can i get the latest version? Normaly I use ipkg packages...

**Comment by jbleyel** [comment]
Using the same way as you get the current version on your box.

**Comment by rdamas** [comment]
@AnTri: I'll build an ipk for VTi and post it in the thread where you already asked for this specific issue.

**Comment by AnTri** [comment]
Thanks for the great support !!!!

@rdamas: Is the VTI ipk different from the "e2openplugin-OpenWebif/enigma2-plugin-extensions-openwebif_1.4.3-latest_all.ipk" ?

**Comment by rdamas** [comment]
Yes; it only includes the remotes for the hardware the VTi supports. And I don't know if the "lastest" ipk does include the latest commit.

**Comment by AnTri** [comment]
Thank you very much for the quick help and the bugfix.
