### ISSUE TITLE
Check defaults.py Todo

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1235]
Do we need setMobile function?
Do we need global for MOBILEDEVICE var?

improve PICON_PATH, GLOBALPICONPATH
Do we need refreshPiconPath?

**Comment by wedebe** [comment]
I don't believe there's any further need for any reference to `*mobile*` given the recent work that's been done to remove it.

Users now have an option to manually set `legacy` or `modern` interface.

**Comment by jbleyel** [comment]
That's not my goal. I wanna remove the jquery mobile part completely and auto switch to modern on mobile device.
And then we need the MOBILEDEVICE var.

**Comment by wedebe** [comment]
What's the determinator for a mobile device in OWIf?

I still see `/openwebif/plugin/public/mobile` in current builds.

**Comment by jbleyel** [comment]
Because of a non 100% working modern UI on a mobile device ;-)
