### ISSUE TITLE
Event Info dialog when title contains special character

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1236]
Clicking Event Info button in modern ui on a title with, eg. `'` or `:` will open an unpopulated dialog, or previously-clicked event info.

**Comment by jbleyel** [comment]
Where exactly do you click?
I do not have problems if title contains `:`

**Comment by jbleyel** [comment]
<img width="868" alt="Bildschirmfoto 2021-03-30 um 23 21 08" src="https://user-images.githubusercontent.com/964927/113058599-a09e5480-91ae-11eb-8bb9-68f4e9ec6936.png">

**Comment by jbleyel** [comment]
I think we can close this.
