### ISSUE TITLE
`/api/signal` returns empty values when receiver is showing Signal Finder screen

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1237]
**Describe the bug**
`/api/signal` returns empty values when receiver is showing Signal Finder screen

**To Reproduce**
Go to Reception -> Signal Finder on receiver
Go to `http://BOX_IP/api/signal` in browser
result shows
```
{
 "tunertype": "",
 "tunernumber": "",
 "snr": "",
 "snr_db": "",
 "agc": "",
 "ber": ""
}
```

**Expected behavior**
something along the lines of...
```
{
 "tunertype": "DVB-T",
 "tunernumber": 2,
 "snr": 49,
 "snr_db": "24.67",
 "agc": 92,
 "ber": 0
}
```

**Screenshots**
n/a

**Image (please complete the following information):**
 - OS: OpenATV
 - Version 6.5

**Desktop (please complete the following information):**
 - any

**Additional context**
Not sure whether this is an enigma2 or OpenwebIf limitation.

**Comment by jbleyel** [comment]
This will not work while signal finder in enigma2:

```
	service = session.nav.getCurrentService()
	if service is None:
		return inf
```
