### ISSUE TITLE
The "recursive" argument to movielist API only reads one level deep

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#1241]
**Describe the bug**
The "recursive" argument to movielist API only reads one level deep. If there are any more levels of folders any recordings in those folders will not be read.

**To Reproduce**
1. Create two levels of folder in `/media/hdd/movie` like `Shows/MyShows`
2. Put recordings in both levels `Shows` and `Shows/MyShows`.
3. Can this URL in a broswer: http://192.168.1.201/web/movielist?dirname=%2Fmedia%2Fhdd%2Fmovie%2F&recursive=1
4. Only the recordings in the root and `Shows` will be returned. Any recordings in `Shows/MyShows` will not.

**Expected behavior**
All shows should be returned.

**Screenshots**

**Image (please complete the following information):**
 - OS: OpenVix
 - Version 5.4

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 88

**Additional context**
Trying to fix an issue in the Kodi Engima2 plugin.

**Comment by jbleyel** [comment]
This is not a bug ;-)

**Comment by jbleyel** [comment]
I cannot reproduce this on OpenATV 6.4 and OpenATV 6.5

**Comment by phunkyfish** [comment]
See #1242
