### ISSUE TITLE
Performance problem modern UI epgrefresh

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1243]
**Describe the bug**
Slow start of epgrefresh in modern UI

**To Reproduce**
* klick on extras epgrefresh in modern U > 3 aprox seconds
* klick on extras epgrefresh in classic UI > lower 1 second

**Expected behavior**
* epgrefresh should open much faster

**Image (please complete the following information):**
 - OS: [e.g. OpenATV, OpenPLI]
 - Version [e.g. 6.4]

**Desktop (please complete the following information):**
 - Browser: chrome, safari
 - Version: latest

**Comment by jbleyel** [comment]
The Page /ajax/epgr in a browser opens in a few milliseconds.

**Comment by jbleyel** [comment]
The open delay is gone if you comment out this line:
`
<script src="/modern/js/vti-responsive-epgr.min.js"></script>`

**Comment by jbleyel** [comment]
**Problem found!!**

These 2 lines of the js are extemely slow

```
$("#channels").append( options);
$('#channels').selectpicker('refresh');

```
If the channel list is very long.

**Comment by wedebe** [comment]
How many channels did you have for this test?

**Comment by jbleyel** [comment]
> 10000 but this is not the case. The same function in the classic UI has no performance problem.

**Comment by jbleyel** [comment]
I have many IPTV channels and i never want to add these channels as EPGRefresh.
I think we should filter out IPTV in this case.
Maybe by an extra setting.

**Comment by jbleyel** [comment]
Step 1: 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/be464afab8df82308cce768d45f07c584056210b

@wedebe : Could you please do the filter of iptv in js for Autotimer and Epgrefresh?

**Comment by jbleyel** [comment]
Step 2:
modern autotimer finished!!!
