### ISSUE TITLE
Scroll problem on modern UI

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1246]
**Describe the bug**
Scrolling the left menu will also scroll the right content.

**To Reproduce**
Scroll left menu.

**Expected behavior**
Left menu scroll action should not scroll the content.

**Comment by wedebe** [comment]
Additionally, the left menu doesn't always fill the vertical space of window resize.

There's a plugin called `slimscroll` in use, which also causes Chrome to log the following
```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
_onWheel @ jquery.slimscroll.js:318
```

**Comment by jbleyel** [comment]
Do we need this plugin?

**Comment by jbleyel** [comment]
I have removed slimscroll -> no effect.

**Comment by wedebe** [comment]
I tested locally and it'll break scrolling the right-side config/skins scroll as well as show thick scrollbars in Edge 😕

Removing it also won't fix the original scroll problem.

**Comment by jbleyel** [comment]
The scroll issue is not in Safari but in Chrome and Opera on Mac.

**Comment by jbleyel** [comment]
setSkinListHeightAndScroll, setSettingListHeightAndScroll and activateNotificationAndTasksScroll needs to be changed if we wanna remove the slimscroll plugin.

The left menu scroll issue is gone if you remove the plugin.

**Comment by jbleyel** [comment]
setSkinListHeightAndScroll, setSettingListHeightAndScroll and activateNotificationAndTasksScroll and Slimscroll can be removed If you change the right menu like this.

```
<div class="tab-content" style="
    overflow-y: auto;
    position: relative;
    height: 90vh;
">
```

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/no-slimscroll

**Comment by wedebe** [comment]
> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/no-slimscroll

I'll use this for a few days and note any regressions.

**Comment by jbleyel** [comment]
Okay. Please remove it completely.
