### ISSUE TITLE
Suppress logging for "GET /api/statusinfo HTTP/1.1"

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1247]
`/statusinfo` is called very frequently and pollutes `tmp/twisted.log`

**Comment by jbleyel** [comment]
It's not really a bug.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/778f4a09be227cd916c00d3d6c4c1aa5205fe1d8/sourcefiles/modern/js/vti-responsive.js#L90

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/149a83f5a010fd7ae14da765093132a2e4ae28d6/sourcefiles/js/openwebif.js#L81

**Comment by rdamas** [comment]
... and there's already https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/2e16916626c06199205eb770353efd0dd3fdbe81/plugin/controllers/web.py#L187 which is aiui supposed to suppress exactly these entries, albeit I don't know if and how it's supposed to work.

**Comment by jbleyel** [comment]
This is a OWF setting only.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/56f15eb03f3cf1d2aadb1f6215554b1c3bd857bb/plugin/controllers/base.py#L207

**Comment by rdamas** [comment]
Well, isn't what @wedebe asks for about OWF? The comment in L186 says "# we don't need to fill logs with this api (it's called too many times)". I may have misinterpreted the topic though...

**Comment by wedebe** [comment]
Indeed self.suppressLog = True has been in web.py, but doesn't appear to work as intended.

<img width="1099" alt="Screen Shot 2021-03-01 at 13 44 37" src="https://user-images.githubusercontent.com/9741693/109505518-947e8480-7a94-11eb-9ea8-decc1a3a6531.png">

**Comment by jbleyel** [comment]
suppressLog is an OWF only option and not used actually.
```

				# if not self.suppresslog:
					# print "[OpenWebif] page '%s' without content" % request.uri
```

**Comment by jbleyel** [comment]
This needs to fix in enigma.
