### ISSUE TITLE
modern UI remove duplicate js import

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1254]
Do we need the at-2.9.min.js for modern UI?

**Comment by wedebe** [comment]
Currently, yes, as modern UI utilises `isBQ`, `FillAT()` and `reloadAT()`.

I'm in the process of overhauling the AutoTimers modern ui code and the removal of `at-2.9.min.js` has been done as part of that.

**Comment by jbleyel** [comment]
I think you should move the modern/classic js mixed code to a separate js file to prevent duplicates.

**Comment by wedebe** [comment]
#1302 takes care of this
