### ISSUE TITLE
Question about entry-app.js

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1255]
Do we need this file?
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/public/js/entry-app.js

Why is this file so big?
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/public/modern/js/entry-app.js

**Comment by wedebe** [comment]
`/plugin/public/js/entry-app.js` seems to have been missed in a git delete, it's not used.

`/public/modern/js/entry-app.js` contains browser polyfills 
```
  "dependencies": {
    "@babel/runtime": "^7.12.5",
    "core-js": "^2.6.11"
  },
```
built in by parcel
