### ISSUE TITLE
Modern - duplicate translation json dumps

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1258]
`initJsTranslation` atop and `initJsTranslationAddon` below are both generated in the html and appear to be duplicates of each other.

Furthermore (but a lot of re-writing), translations should use a more efficient methodology. Perhaps something like 
[Polyglotjs](https://phrase.com/blog/posts/step-step-guide-javascript-localization/#Polyglotjs)

(Sorry I don't have auth to change label to `Improvement` which isn't listed as a `New issue` type).

**Comment by jbleyel** [comment]
will be fixed in 2.0
