### ISSUE TITLE
Terminal is not working (openwebif version 1.3.9a)

### ISSUE THREAD

**Issue by paparas12** [E2OpenPlugins/e2openplugin-OpenWebif#1272]
**Describe the bug**
If i push the "Terminal'  button ,a msg appears which says "Could not connect"

**To Reproduce**
1. Go to 'Main menu...'
2. Click on 'Terminal'
3. 
4. See Title

**Image (please complete the following information):**
nwenigma2
 - image daily 2021-02-21

**Desktop (please complete the following information):**
 - Mozilla Firefox]
 - Version [86.0 (64bit)

Dreambox dm920

thnx

**Comment by jbleyel** [comment]
This is not a BUG of OWF.
The terminal is an extra plugin called shellinabox.

**Comment by Schimmelreiter** [comment]
![image](https://user-images.githubusercontent.com/2022025/110216544-f6355900-7eaf-11eb-9988-550e783f3fc8.png)

**Comment by paparas12** [comment]
Yes , i have found a new version and the plugin.
thnx
