### ISSUE TITLE
EPG SEARCH scope?

### ISSUE THREAD

**Issue by paparas12** [E2OpenPlugins/e2openplugin-OpenWebif#1273]
Can i anywhere define the search scope of EPG Search (like certain Bouquets) and not all channels ?
Also a search list for the repeated words
and search in Titles or Description or both?

Dreambox dm920 (nwenigma2)

**Comment by jbleyel** [comment]
The EPG search in OWF is using the epgcache search function of enigma2.
There are no limitations in OWF but in enigma2.

Title + description search is implemented already based on the enigma2 features.
Search filter by bouquets is not part of the epgcache search function.
