### ISSUE TITLE
Screen grab now save the filename has:  channelname_timestamp.jpg

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-OpenWebif#1274]
**Describe the bug**
When performing a screenshot (grab screen) from OpenWebif the default name include the full service reference.
Now it is replaced by the channelname.

**To Reproduce**
1. Go into screenshot menu
2. Right click on the image
3. Select save as... and watch the default proposed name.

**Expected behavior**
Please provide an option to retrieve the old behavior.  This was really the easiest way to cut and paste the currently watched channels service-reference.
I could not find anywhere else in the OpenWebif the currently watched channel service reference where I can cut and paster it easily.

This was really useful to report changes to people managing the XMLTV EPG file (in my case Doglover for the RytecEPG).

So please either:
- if you want the name please also include the service reference
- if you don't want the service reference please display it somewhere where we can easily perform a cut and paster of it.
- Having just the channelname + timestamp you miss an important information because for example I can receive 5 times the same channel with the same name from 3 differents satellites + DVB-C  so TF1_20210306....jpg is not mentionning where the screenshot was taken from only the service reference provide the full information (I can receive it twice on 5°W also so adding the satellite is neither an option).

**Image (please complete the following information):**
 - OS:  OpenPLI
 - Version 8 develop

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 89.0.4389.82

**Additional context**
Have an easy to retrieve and cut and paste the currently watched TV show service references.

**Comment by Grumpy-Geoff** [comment]
Can't you get that info under "Channel Info" - 
Classic: Television / Current
Modern: Television / hamburger / Current, or Extras / Channel Info
http://{STB}/#current

**Comment by WanWizard** [comment]
The service reference isn't mentioned anywhere in the classic UI. It would be handy to add it to the "Current event" block.
