### ISSUE TITLE
Timers view throws exception

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#1275]
**Describe the bug**
Timers view throws exception

**Image (please complete the following information):**
VTi current, OWF-1.4.4

**Additional context**
Traceback:

```
web.Server Traceback (most recent call last):
exceptions.TypeError: FuzzyTime() got an unexpected keyword argument 'inPast'
/usr/lib/python2.7/site-packages/twisted/web/server.py:183 in process
/usr/lib/python2.7/site-packages/twisted/web/server.py:234 in render
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py:206 in render
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/ajax.py:230 in P_timers
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/timers.py:149 in getTimers
149 fuzzyBegin = ' '.join(str(i) for i in FuzzyTime(timer.begin, inPast = True))
exceptions.TypeError: FuzzyTime() got an unexpected keyword argument 'inPast'
```

There's no `inPast` parameter in Tools.FuzzyTime here. 

Please fix or revert ac14ef786192245c19710da47a4d83fc74a85af5

**Comment by rdamas** [comment]
(Ich kann das Issue nicht wieder öffnen!?)

Danke für den Fix - das Ergebnis ist aber nicht zufriendenstellend: Datum und Uhrzeit werden gesperrt angezeigt; warum?

<img width="1046" alt="Bildschirmfoto 2021-03-07 um 12 41 06" src="https://user-images.githubusercontent.com/15088943/110238770-b9b33d00-7f43-11eb-97c9-f5c8489db51c.png">

Hier der erzeugte Code:
```
<div class="col-sm-4">
  <time style="white-space: nowrap;">M o   0 8 . 0 3 . ,   1 8 : 3 0</time>
  - <time style="white-space: nowrap;">8</time>
  <span class="event__duration" style="opacity: 0.4; margin-left: 0.4ch;">(30 Minuten)</span>
   
  <div class="m-t-10" style="font-weight: bold;">
  wartend
  </div>
</div>
```

**Comment by jbleyel** [comment]
Schau ich mir gleich an.

**Comment by jbleyel** [comment]
@wedebe .. Please check my timer date changes.

**Comment by rdamas** [comment]
Remark: Now in classic view ok again, in modern view only time of day is shown, but no date.

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/ea113e740837f1afe8cbb97614699a3f2017103d
