### ISSUE TITLE
Origin mod - EPG refresh problem

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#1276]
When I want see EPG Refresh settings, there are nonsences. I must open Autotimer first, then EPG refresh has relevant info. Weird.
On all boxes.

**Comment by jbleyel** [comment]
I cannot reproduce your problem in classic UI and modern UI.

**Comment by ims21** [comment]
![obrazek](https://user-images.githubusercontent.com/1208763/110238727-7e187300-7f43-11eb-9b68-75f21ab4d9c1.png)

and after open/close Autotimer

![obrazek](https://user-images.githubusercontent.com/1208763/110238758-a99b5d80-7f43-11eb-869e-2be051093b82.png)


On Vu Duo4k it was solved with reboot box, vs1500 and Axas still same... weird

**Comment by jbleyel** [comment]
This looks like a javascript error on the first start.
Could you please check this in your browser.

**Comment by ims21** [comment]
Uncaught ReferenceError: ru is not defined

**Comment by ims21** [comment]
![obrazek](https://user-images.githubusercontent.com/1208763/110239726-b9697080-7f48-11eb-9cd3-bdd169425708.png)

**Comment by jbleyel** [comment]
I will check this.
