### ISSUE TITLE
EPG Search settings also in Openwebif

### ISSUE THREAD

**Issue by paparas12** [E2OpenPlugins/e2openplugin-OpenWebif#1277]
To be able to change the EPGsearch setting in Openwebif

**Comment by jbleyel** [comment]
What Image do you use and what version of the OWF?

**Comment by paparas12** [comment]
OWF version 1.4.9, image nwenigma2 on Dreambox dm920

**Comment by jbleyel** [comment]
The latest OWF version is 1.4.4.

The modern design OWF has 2 checkboxes and the next update of the classic design has also 2 checkboxes.

**Comment by jbleyel** [comment]
See here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/c4ff663a26e6c406a12036ca75e6b816d7b619ad

**Comment by paparas12** [comment]
Here mine version.
Where the checkboxes?
![Snap7](https://user-images.githubusercontent.com/80169305/110428054-63640c80-80b1-11eb-87a3-e01f6ff07e65.jpg)

**Comment by jbleyel** [comment]
This looks like an newnigma special version of OWF.

The only supported version is the GitHub version.
