### ISSUE TITLE
Does not reader the picons path from webif config 

### ISSUE THREAD

**Issue by paparas12** [E2OpenPlugins/e2openplugin-OpenWebif#1278]
If i change the path to alternative picon location other then defaults... Openwebif does not read the new path.
I have solved this problem with setting a symlink from /user/enigma2/picon to /picons/piconHD (as you see)
![Snap8](https://user-images.githubusercontent.com/80169305/110448986-64556800-80ca-11eb-8480-b386871daaba.jpg)

**Comment by jbleyel** [comment]
This is not a bug. It's by design.
The valid picon paths are:

"/media/cf/",
"/media/mmc/",
"/media/usb/",
"/media/hdd/",
"/usr/share/enigma2/",
"/"

+ "picon/"
