### ISSUE TITLE
Better readability of service list in OpenWebIF (old-style)?

### ISSUE THREAD

**Issue by Papi2000-new** [E2OpenPlugins/e2openplugin-OpenWebif#1280]
Readability of the service lists in the OpenWebIF (old style) could be enhanced.

Readability of the service lists in the OpenWebIF (old style) looks better for me, when the color of the background of the services from light-blue [#F0F7FC] would be changed to a marginal darker blue [#D0F7FC].

I tested locally changing in the "http://gbquad4k-3/css/theme_original.css", and looks nice.
(See the attached example)

Screenshot new:
![image](https://user-images.githubusercontent.com/80783721/111365644-06f58400-8693-11eb-8859-14462103d787.png)

[WebIF, Class fr change request 1.pdf](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/6151643/WebIF.Class.fr.change.request.1.pdf)

**Comment by jbleyel** [comment]
#D0F7FC is turquoise and not blue.

<img width="792" alt="Bildschirmfoto 2021-03-17 um 19 06 16" src="https://user-images.githubusercontent.com/964927/111516214-f2c58b80-8753-11eb-94eb-028bc0a64502.png">

You will lost contrast to the text if you make the background darker. (imho)

I would prefer #79b7e755

<img width="786" alt="Bildschirmfoto 2021-03-17 um 19 11 52" src="https://user-images.githubusercontent.com/964927/111516817-a62e8000-8754-11eb-9360-7b8cde3d4d01.png">

**Comment by Papi2000-new** [comment]
I agree, and accept your proposal. Thanks for regarding the topic at all.
