### ISSUE TITLE
a *.deb installation file

### ISSUE THREAD

**Issue by paparas12** [E2OpenPlugins/e2openplugin-OpenWebif#1281]
For OE2.5-nwenigma image!

**Comment by jbleyel** [comment]
Wo ist das deb File?

**Comment by paparas12** [comment]
@jbleyel : Das ist eine Forderung! 
Du bis doch der programmiere des Plugins oder ?
Warum erstellt du nicht das *.deb file?

**Comment by e2world** [comment]
Ich denke Dir fehlt etwas Wissen um die Zusammenhänge. Es gibt kein OpenWebif für DreamOS.

**Comment by jbleyel** [comment]
Bitte genau lesen! Ich brauche das deb file von der 1.4.9 aus dem Forum weil ich das selber nicht runterladen kann.

**Comment by paparas12** [comment]
@jbleyel 
Bitte genau lesen!, Ich brauche das *.deb file von dein 1.4.4. so das ich es auf meine Box installieren kann.
Die marke ist "Feature Request"
@e2world 
Dir fehlt das "Wissen um die Zusammenhänge", es existiert ein Openwebif for DreamOS und zwar sogar version 1.4.9a habe das auf mein DreamOs  installiert!

**Comment by Schimmelreiter** [comment]
Da ist aber jemand im Schweinsgalopp durch die Kinderstube gegangen ...

**Comment by Papi2000-new** [comment]
> @jbleyel : Das ist eine Forderung!
> Du bis doch der programmiere des Plugins oder ?
> Warum erstellt du nicht das *.deb file?

Du kannst lesen?

**Comment by jbleyel** [comment]
Hallo @paparas12,

das deb kann man jetzt hier runterladen.
-> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/gh-pages

ABER:
Das dab hier ist so nicht unter DreamOS benutzbar und muss erst angepasst werden.

Das deb 1.4.9a aus dem Forum hab ich mir mittlerweile angeschaut und hier meine Anmerkungen:
* die Version passt nicht, denn die Version reflektiert nicht den Stand der API 
(wenn hier eine neue Funktion in die API eingebaut wird und dann die Version 1.4.5 ist, dann hat die Version 1.4.9 aus dem Forum nicht automatisch diese neue API)
* das OWF aus dem Forum kann kein Python3
* das original OWF braucht die python six library Version >= 1.14 aber DreamOS hat nur die Version 1.10
* die Anpassungen vom OWF aus dem Forum sind nur rudimentär hingepfuscht, das es läuft
(Dies entspricht nicht meinem Qualitätsanspruch)
* das OWF aus dem Forum existiert nur as deb und nicht z.B. als fork hier auf Github
(Dadurch sind die Anpassung extrem schwierig zu prüfen)

Ich möchte dem Entwickler von der MOD aus dem Forum nicht zu nahe treten, aber wenn dann bitte richtig machen und nicht nur hinfummeln.

**Comment by paparas12** [comment]
Hallo @jbleyel 
Die Version aus dem Forum habe nur installiert weil es die einzige ist, die für DreamOs existiert und sogar als Installationspaket ( *.deb.)
Da ich kein programmiere bin kann ich deine Anmerkungen nicht nachvollziehen!.
Momentan lauft OWF aus dem Forum ohne Problem.
Sollte eine Version 1.4.5 hier erscheinen, die alle deine Anmerkungen berücksichtigt, werde ich sie natürlich installieren. 
mfg

**Comment by paparas12** [comment]
Das ist doch eine neue version (1.4.5) oder nicht?
