### ISSUE TITLE
Terminal eingabe zurück bringen

### ISSUE THREAD

**Issue by Masta2002** [E2OpenPlugins/e2openplugin-OpenWebif#1293]
Ich habe im VU+ Supportforum diesen Thread gefunden
https://www.vuplus-support.org/wbb4/index.php?thread/142130-open-webif-aktuell

Daraufhin habe ich das update installiert und musste leider feststellen das es die Funktion der Terminal eingabe nicht mehr gibt. Ich persönlich und auch schon ein paar andere im Board fanden dieses feature allerdings recht nützlich. Daher die frage ob es evtl. möglich wäre dies wieder zurück zu bringen.

**Comment by jbleyel** [comment]
Das Terminal ist keine Funktion vom OWF. Man braucht dazu shellinabox.
Das OWF zeigt links das Terminal zur Auswahl an, wenn diese Datei auf der Box ist.

/usr/bin/shellinaboxd

**Comment by Masta2002** [comment]
Okay danke für deine antwort. Kann es also sein das dieses durch die instalation der neuen OWF deinstalliert wurde? Weist du wie ich das dann wieder installieren kann?

**Comment by jbleyel** [comment]
Dann liegt das Problem an shellinabox, das OWF startete nur den ReverseProxy auf Port 4200.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/4162b2be75cb5e2ae0c18ea203d717bbe75558ef/plugin/controllers/root.py#L67

**Comment by Masta2002** [comment]
Ich bin mir eigentlich 100% sicher das beim Installieren der aktuellen IPK von OWF 3 Pakete angepasst wurden und da waren auch deinstallationen dabei.....

Bekomme auch leider das Terminal nach wie vor nicht zum laufen.  Wie kann ich diesen reverse Proxy prüfen ob dieser passt?

**Comment by jbleyel** [comment]
shellinabox ist nicht Bestandteil vom OWF und wird weder installiert noch deinstalliert.

Die Datei /usr/bin/shellinaboxd auf die Box kopieren reicht natürlich nicht.
Du musst das shellinabox plugin vom Feed installieren.
Wenn das nicht auf dem Feed ist, dann muss das jemand dort hinlegen.

**Comment by jbleyel** [comment]
Du brauchst auch noch die `/etc/init.d/shellinabox` denn shellinaboxd ist ein daemon der über das init script gestartet werden muss.

Auf meiner Box gibt es diese Dateien.
```

/etc/rc1.d/K20shellinabox
/etc/rc5.d/S20shellinabox
/etc/rc0.d/K20shellinabox
/etc/init.d/shellinabox
/etc/rc2.d/S20shellinabox
/etc/rc4.d/S20shellinabox
/etc/rc6.d/K20shellinabox
/etc/rc3.d/S20shellinabox
/usr/bin/shellinaboxd
```

**Comment by Masta2002** [comment]
Hab es mittlerweile über das feed installiert und deine datei auflistung ist auch alles vorhanden bei mir nur läuft es leider trotzdem noch nicht.

**Comment by jbleyel** [comment]
Poste mal die /etc/init.d/shellinabox hier.
Und dann schau mal mit `ifconfig` ob du auch IPv6 hast.

**Comment by Masta2002** [comment]
root@vuuno4kse:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:1d:ec:14:b0:32
          inet addr:192.168.178.55  Bcast:192.168.178.255  Mask:255.255.255.0
          inet6 addr: 2001:16b8:3fbb:de00:21d:ecff:fe14:b032/64 Scope:Global
          inet6 addr: fe80::21d:ecff:fe14:b032/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:32794 errors:0 dropped:8391 overruns:0 frame:0
          TX packets:10220 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5270505 (5.0 MiB)  TX bytes:4215132 (4.0 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:420 (420.0 B)  TX bytes:420 (420.0 B)




[shellinabox.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/6214168/shellinabox.zip)

**Comment by jbleyel** [comment]
Dann probier mal diesen Link im browser.
https://192.168.178.55:4200

**Comment by jbleyel** [comment]
Wenn das geht, dann ändere mal die Zeile 42 in der /etc/init.d/shellinabox

ALT:
`start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON -o -- --cert $SHELLINABOX_CONFIG_DIR -q --background=$PIDFILE -p $SHELLINABOX_PORT --user-css Normal:+$SHELLINABOX_CONFIG_DIR/vti.css`

NEU:
`start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON -o --  -q --background=$PIDFILE -p $SHELLINABOX_PORT --user-css Normal:+$SHELLINABOX_CONFIG_DIR/vti.css --disable-ssl --localhost-only`

**Comment by Masta2002** [comment]
der link geht leider auch nicht

**Comment by jbleyel** [comment]
Dann stimmt vermutlich was mit dem script `/etc/init.d/shellinabox` nicht.
Das müsste sich mal jemand mit linux skills auf deiner Box direkt anschauen.

**Comment by jbleyel** [comment]
Oder ich teste das mal auf meiner Box .. das kann aber bissel dauern.

**Comment by Masta2002** [comment]
Okay viele dank für deine hilfe

**Comment by Masta2002** [comment]
> 
> 
> Dann probier mal diesen Link im browser.
> https://192.168.178.55:4200

das geht nun mittlerweile

aber die änderunghen in zeile 42 einzutragen bewirkt das es wieder nicht mehr funktioniert

**Comment by anudanan** [comment]
Ich habe Masta2002 im vti unterstützt beim Debuggen mit shellinabox. 
Er ist jetzt soweit, dass https vom Rechner auf Port 4200 geht. Daher werden wir jetzt das Abschalten von ssl machen, da das openwebif scheinbar http macht.
Danach geht es vermutlich

**Comment by jbleyel** [comment]
Danke

**Comment by anudanan** [comment]
@Masta2002 
Nach der Änderung aus Zeile 42 geht HTTPS nicht mehr, dann geht nur noch HTTP vom Rechner aus.

**Comment by jbleyel** [comment]
Mit `--localhost-only` sollte es dann nur noch über den reverse Proxy gehen.
Der twisted ReverseProxy geht aber leider nicht mit VTi.
Frag mich nicht warum.

**Comment by anudanan** [comment]
Du meinst es wird jetzt trotzdem nicht vom openwebif funktionieren? Er probiert das gerade

**Comment by jbleyel** [comment]
Auf meiner Box wo es läuft ist twisted 19.7.0.
Auf der VTi Box wo es nicht läuft ist twisted 16.2.0.

Die alte Version von twisted kann wohl kein ipv6.
Ich fix das mal im OWF.

Allerdings muss man in die Zeile 42 in wie oben beschrieben ändern.

**Comment by anudanan** [comment]
Ist das mit ipv6 erst vor einiger Zeit ins openwebif reingekommen? Das könnte das erklären.

Auf der Box von @Masta2002 sieht man, dass der shellinabox daemon den Port 4200 nur auf ipv4 öffnet, bei ipv6 gibt es da keinen Listener

**Comment by jbleyel** [comment]
Dann liegt es am shellinabox.
Das kann ich aber nicht mit dem OWF abfragen.

**Comment by Schimmelreiter** [comment]
Das lief schon immer mit IPv6.

**Comment by anudanan** [comment]
D.h. der shellinabox Daemon muss ein listen auf Ipv6 machen, damit es geht?

**Comment by jbleyel** [comment]
Bei meiner Box wo es geht, sieht das so aus.

tcp        0      0 localhost:4200          :::*                    LISTEN

**Comment by jbleyel** [comment]
Ich vermute das die VTi version von shellinabox kein IPv6 kann.

**Comment by anudanan** [comment]
Das sieht so aus, Ich lasse mir da mal die Hilfe ausgeben, was es da für Parameter gibt
Immer dieser Huddel mit ipv4 und ipv6, vermutlich wird das noch 100 Jahre so sein ;-)

**Comment by jbleyel** [comment]
Meine version von shellinabox ist  
2.22 (revision a2b7bc0)

die VTi version ist  
2.20 (revision 5c7fb5c)

**Comment by Schimmelreiter** [comment]
Shellinabox richtet bei localhost only einen reinen IPv6-Listener ein.
Ohne localhost only wäre es aber ein Sicherheitsrisiko.

**Comment by jbleyel** [comment]
Hi @Schimmelreiter , "localhost only" IPv6 geht aber nicht mit der 2.20

**Comment by Schimmelreiter** [comment]
Ok, wenn VTi einen anderen Build von shellinabox hat, kann es genau anders herum sein, also IPv4-only.
Ich vermute aber fast, daß VTi das Rezept wie üblich bei OpenATV geklaut und dann nicht mehr aktualisiert hat.

**Comment by anudanan** [comment]
Yepp, er hat die 2.20 installiert. Dann wird das wohl nichts.

Wundert mich aber immer noch, dass er sagt, dass es mal getan hat. Vielleicht war das noch ein sehr alten OWIF, wo das mit IPv4 ging. Das passt allerdings nicht dazu, dass @Schimmelreiter geschrieben hat, dass OWIF shellinabox immer mit ipv6 gemacht hat.

**Comment by jbleyel** [comment]
Doch das passt, denn die OWF version von VTi ist schon lange ein fork.

**Comment by anudanan** [comment]
Dann braucht er also eine neuere shellinabox

**Comment by jbleyel** [comment]
Nö .. nur die Zeile 42 und meine Änderungen vom OWF die ich gleich mache.

**Comment by anudanan** [comment]
Ah, ok, ich dachte, das ginge nicht. Du stellst also auf ipv4 für shellinabox um?

**Comment by jbleyel** [comment]
Schau mal meinen letzen commit

**Comment by anudanan** [comment]
Cool, das wird dann passen. Dann schreibe ich ihm das noch. Herzlichen Dank.

**Comment by jbleyel** [comment]
Nicht vergessen!

`--disable-ssl --localhost-only`

**Comment by anudanan** [comment]
Yepp, hat er schon gemacht und habe ich ihm auch nochmal drauf hingewiesen

**Comment by Masta2002** [comment]
Vielen dank an alle hier es funktioniert nun wieder!!!! Super arbeit!!
