### ISSUE TITLE
Testers needed for AutoTimers page

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1294]
Hi, I've been working on a rewrite and modernisation of the AutoTimers page js code. If you've got some time, please check it out and let me know of any issues you come across!

(include as much detail as possible)

https://github.com/wedebe/e2openplugin-OpenWebif/tree/autotimers

Outstanding TODOs:
  * @todo fix dropdown styling
 * ~@todo handle autotimer creation from event~
 * ~@todo fix vps etc. params~
 * ~@todo consolidate !Array.isArray~
 * @todo check/fix iptv exclusion
 * @todo apply decodeHtml to filters
 * ~@todo i10n~
 * @todo handle defaults (maybe show as [value])
 * @todo consolidate e2simplexmlresult handling
 * @todo filter/sort atlist by name/date added/enabled etc
 * @toto better handle `tstr_` and `tstrings_` (global change)
 * @todo JSDoc https://jsdoc.app/index.html

Added from testing:
* code parse functionality
* `autoadjust` values
* ...

**Comment by jbleyel** [comment]
Hi @wedebe , you have removed some l10n strings. This will break the classic autotimer.

**Comment by wedebe** [comment]
I believe there are two entries, which were also updated in classic. (if you see others, please let me know)

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/compare/master...wedebe:autotimers?expand=1#diff-855443aca187c0a6083ba7f0e4c1fd19d97e46d5f3cf0355e79c72fe9fa66eff

**Comment by jbleyel** [comment]
I should check the hole diff. ;-)

**Comment by jbleyel** [comment]
TEST Results:

Parse color / icon position 
<img width="830" alt="Bildschirmfoto 2021-03-27 um 10 37 18" src="https://user-images.githubusercontent.com/964927/112716744-82073780-8ee8-11eb-8c0f-f5646c6583d7.png">

---

to much space between the lines
.atform__fields-container -> top margin

<img width="1224" alt="Bildschirmfoto 2021-03-27 um 10 39 26" src="https://user-images.githubusercontent.com/964927/112716802-d27e9500-8ee8-11eb-8fd6-a0fc92de7771.png">

---

VPS / save mode checkbox

<img width="320" alt="Bildschirmfoto 2021-03-27 um 10 42 42" src="https://user-images.githubusercontent.com/964927/112716875-3d2fd080-8ee9-11eb-8df3-52a858dc2c47.png">
<img width="664" alt="Bildschirmfoto 2021-03-27 um 10 43 38" src="https://user-images.githubusercontent.com/964927/112716885-4e78dd00-8ee9-11eb-8478-7237877e523d.png">

---

disabled folder checkbox not saved
<img width="798" alt="Bildschirmfoto 2021-03-27 um 10 52 56" src="https://user-images.githubusercontent.com/964927/112717110-b976e380-8eea-11eb-9b69-0a8b533f45da.png">

**Comment by wedebe** [comment]
Thanks @jbleyel , 

I've added `Parse` to the todo list (I'd disabled the button until it was ready. Is this considered a blocker for release?

Re: the spacing, that's what's in place at the moment, I'll clean up styling separately to this release.

Could you tell me what logic should go around VPS, please? I don't have or use the plugin.
If you could explain parameter and value relationships too that'd be great!

I;'m not sure about the location checkbox, could you clarify, please?

**Comment by jbleyel** [comment]
The location attribute in xml needs to be removed if uncheck "recording location ..".

The VPS save mode checkbox is only visible if VPS checkbox is checked and should be in the same line in html.
"VPS" checked -> XML attribute "vps_enabled=yes"
"VPS save mode" unchecked -> XML attribute "vps_overwrite=yes"

**Comment by wedebe** [comment]
Actually, could you grab the text from the browser's js console when you click to edit an entry with both tickboxes checked, please?

You should see something like this, which'll help me determine exactly what's expected
```
[text] <input type=​"text" name=​"name" required autocomplete=​"off" autocapitalize=​"on" placeholder=​"Enter a name for this AutoTimer" class=​"form-control">​ name 00000 test
entry-app.js:521 [text] <input type=​"text" name=​"match" required autocomplete=​"off" autocapitalize=​"off" placeholder=​"Enter the text to find in the EPG" class=​"form-control">​ match 00000 test
entry-app.js:521 [checkbox] <input type=​"checkbox" name=​"enabled" value=​"1" class=​"form-control chk--skinned" checked>​ enabled 1
entry-app.js:521 [N/A] id 1
entry-app.js:521 [select-one] <select name=​"location" class=​"form-control show-tick" tabindex=​"-98">​…​</select>​ location /media/hdd/movie/autotimer/
entry-app.js:521 [N/A] lastBegin 1616131500
```

**Comment by jbleyel** [comment]
The VPS checkboxes are disabled.

**Comment by jbleyel** [comment]
The autotimer/edit request should not have "location=xxx" if the location checkbox is unchecked.

**Comment by jbleyel** [comment]
The two VPS checkboxes are not checkable.

-

The autotimer/edit request should not have "location=xxx".
You need to modify the form submit request and remove location if the location checkbox is checked.

**Comment by jbleyel** [comment]
vps_overwrite -> vpssm(invers)

```
#if $hasVPS == 1
											<div class="atform__fields-container">
												<div class="atform__details__title">
													<input type="checkbox" id="vps" class="form-control chk--skinned">
													<label for="vps">$tstrings['vps']</label>
												</div>
												<div class="atform__details__element">
													<span id="vpsE">
														<input type="checkbox" id="vpssm" class="form-control chk--skinned">
														<label for="vpssm">$tstrings['safe_mode']</label>
													</span>
												</div>
											</div>
#end if

```

**Comment by jbleyel** [comment]
```
#if $hasSeriesPlugin == 1
											<div class="atform__fields-container">
												<div class="atform__details__title">
													<input type="checkbox" id="series_labeling" class="form-control chk--skinned">
													<label for="series_labeling">$tstrings['at_label_series']</label>
												</div>
												<div class="atform__details__element">
												</div>
											</div>
#end if

```

**Comment by jbleyel** [comment]
```
	this.vps = false;
	this.vpso = false;
	if(xml.attr("vps_enabled") === "yes") {
		this.vps = true;
		if(xml.attr("vps_overwrite") === "yes") {
			this.vpso = true;
		}
	}
	
	this.series_labeling = false;
	if(xml.attr("series_labeling") === "yes") {
		this.series_labeling = true;
	}
	
	this.autoadjust = false;
	if(xml.attr("autoadjust") === "1") {
		this.autoadjust = true;
	}
	this.allow_duplicate = true;
	if(xml.attr("allow_duplicate") === "0") {
		this.allow_duplicate = false;
	}
	this.avoidDuplicateMovies = false;
	if(xml.attr("avoidDuplicateMovies") === "1") {
		this.avoidDuplicateMovies = true;
	}
```

**Comment by jbleyel** [comment]
These 3 values are 0/1 in xml!

```
#if $autoadjust == 1
											<div class="atform__fields-container">
												<div class="atform__details__title">
													<input type="checkbox" id="autoadjust" class="form-control chk--skinned">
													<label for="autoadjust">$tstrings['autoadjust']</label>
												</div>
												<div class="atform__details__element"></div>
											</div>

											<div class="atform__fields-container">
												<div class="atform__details__title">
													<input type="checkbox" id="avoidDuplicateMovies" class="form-control chk--skinned">
													<label for="avoidDuplicateMovies">$tstrings['avoidDuplicateMovies']</label>
												</div>
												<div class="atform__details__element"></div>
											</div>

											<div class="atform__fields-container">
												<div class="atform__details__title">
													<input type="checkbox" id="allow_duplicate" class="form-control chk--skinned">
													<label for="allow_duplicate">$tstrings['allow_duplicate']</label>
												</div>
												<div class="atform__details__element"></div>
											</div>
#end if

```

**Comment by wedebe** [comment]
https://github.com/wedebe/e2openplugin-OpenWebif/commit/338e02686f2c6ae2c54a9b89eb7382efcea4e233
addresses VPS and deselected location (et al) input submission issues.

**Comment by jbleyel** [comment]
VPS Safe mode is visible on first load.
<img width="707" alt="Bildschirmfoto 2021-03-28 um 11 58 33" src="https://user-images.githubusercontent.com/964927/112748604-0d51fd00-8fbd-11eb-92b4-13feb2d89a6f.png">

**Comment by jbleyel** [comment]
Set VPS checkboxes is not correct.

XML: 
vps_enabled="yes" vps_overwrite="yes" -> VPS checked / SafeMode unchecked
vps_enabled="yes" vps_overwrite="no" -> VPS checked / SafeMode checked
vps_enabled="no" vps_overwrite="no" -> VPS unchecked / SafeMode unchecked and hidden

vps_enabled and vps_overwrite are optional in XML and the default is "no" if not exists.

The url parameter values for vps_enabled and vps_overwrite are 0,1,no,yes
-> https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L383

Please note !!
vps_overwrite(yes) = savemode (no)
vps_overwrite(no) = savemode (yes)
vps_overwrite(not exists)  = savemode (yes)

**Comment by jbleyel** [comment]
The series_labeling XML attribute is "yes" / "no".
Default is "no".

The autoadjust, allow_duplicate, avoidDuplicateMovies XML attributes are "1" / "0".
allow_duplicate default is "1"
autoadjust, avoidDuplicateMovies default is "0"

**Comment by wedebe** [comment]
> Set VPS checkboxes is not correct.
> 
> XML:
> vps_enabled="yes" vps_overwrite="yes" -> VPS checked / SafeMode unchecked
> vps_enabled="yes" vps_overwrite="no" -> VPS checked / SafeMode checked
> vps_enabled="no" vps_overwrite="no" -> VPS unchecked / SafeMode unchecked and hidden
> 
> vps_enabled and vps_overwrite are optional in XML and the default is "no" if not exists.
> 
> The url parameter values for vps_enabled and vps_overwrite are 0,1,no,yes
> -> https://github.com/oe-alliance/enigma2-plugins/blob/master/autotimer/src/AutoTimerResource.py#L383
> 
> Please note !!
> vps_overwrite(yes) = savemode (no)
> vps_overwrite(no) = savemode (yes)
> vps_overwrite(not exists) = savemode (yes)

@jbleyel How about something like this for the input?
<img width="808" alt="Screen Shot 2021-03-28 at 12 20 38" src="https://user-images.githubusercontent.com/9741693/112750375-31630d80-8fc0-11eb-962d-73d97a77780b.png">

**Comment by jbleyel** [comment]
This can confuse the user because there is no overwrite mode.
The vps plugin has only Enabled =  "No", "Yes", "Yes (Safe mode)"

https://github.com/oe-alliance/enigma2-plugins/blob/2c36f9421cb975d550e2e46629d291ff079f2438/vps/src_py/Modifications.py#L166

**Comment by wedebe** [comment]
I'm puzzled by the setting of (and defaulting) a non-existent parameter to the inverse of an existing parameter.

Forgive my curiousity, but wouldn't it make sense to modify `AutoTimerResource.py` to the following (not tested) code?

```
# vps
vps_enabled = get("vps_enabled")
if vps_enabled is not None:
	try: vps_enabled = int(vps_enabled)
	except ValueError: vps_enabled = vps_enabled == "yes"
	timer.vps_enabled = vps_enabled

vps_safemode = get("vps_safemode")
if vps_safemode is not None:
	try: vps_safemode = int(vps_safemode)
	except ValueError: vps_safemode = vps_safemode == "yes"
	vps_overwrite_s = !vps_safemode
	timer.vps_overwrite = vps_overwrite_s

if vps_overwrite_s is None:
	vps_overwrite = get("vps_overwrite")

if vps_overwrite is not None:
	try: vps_overwrite = int(vps_overwrite)
	except ValueError: vps_overwrite = vps_overwrite == "yes"
	timer.vps_overwrite = vps_overwrite
else:
	vps_overwrite = 0 # or False or "no"
if not timer.vps_enabled and timer.vps_overwrite:
	timer.vps_overwrite = False
```

My concern is that, without the code above, _every single_ mobile app, html interface and anything else that uses the /autotimer API will have to explicitly keep track of an extra parameter in order to handle what is essentially a plugin (VPS) that's not only an extra to the AutoTimers plugin, but to the OpenWebIf plugin too!

**Comment by jbleyel** [comment]
This is a bad idea because of too many different autotimer plugin versions.

**Comment by jbleyel** [comment]
I dont't understand your problem.
You only need to calculate the request parameter here -> .
https://github.com/wedebe/e2openplugin-OpenWebif/blob/autotimers/sourcefiles/modern/js/autotimers.js#L557
before you send the request.

**Comment by jbleyel** [comment]
Please check this:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/js/at.js#L638
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/js/at.js#L752
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/js/at.js#L922
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/js/at.js#L1016

**Comment by wedebe** [comment]
@jbleyel , could you test 
https://github.com/wedebe/e2openplugin-OpenWebif/commit/b21261eec6b5a125377e41e2fb87cf6c34b1e3ad
when you get a chance please and let me know your findings for vps, please?

**Comment by jbleyel** [comment]
**Save autotimer looks good.**

**Safe mode checkbox looks good.**

**VPS checkbox is always not checked.**

XML no vps attributes
-> 
<img width="686" alt="Bildschirmfoto 2021-03-28 um 21 54 35" src="https://user-images.githubusercontent.com/964927/112766046-50898b80-9010-11eb-88fc-600a17ceaa23.png">

XML vps_enabled="yes"
-> 
<img width="686" alt="Bildschirmfoto 2021-03-28 um 21 54 35" src="https://user-images.githubusercontent.com/964927/112766050-541d1280-9010-11eb-8249-ad0fd6ffa14e.png">

XML vps_enabled="yes" vps_overwrite="yes" 
-> 
<img width="551" alt="Bildschirmfoto 2021-03-28 um 21 57 12" src="https://user-images.githubusercontent.com/964927/112766132-a78f6080-9010-11eb-9daa-00db2e16d1ca.png">

**Comment by wedebe** [comment]
Sorry 🤦🏻‍♂️ I'd overlooked the `yes` response string.

https://github.com/wedebe/e2openplugin-OpenWebif/commit/941466f9874fe4f315f24a8c6ee7c3c568703dbb
rectifies that.

**Comment by jbleyel** [comment]
Nope.. (Sorry) Same result.
The response for vps_enabled is 1/0.
The xml attribute value is "yes", "no" or not exists.

**Comment by jbleyel** [comment]
vps_overwrite works as expected.

**Comment by jbleyel** [comment]
It's working now!!

**Comment by wedebe** [comment]
🎉 😄

Thanks!

I'll work on remaining issues during the week.

**Comment by wedebe** [comment]
https://github.com/wedebe/e2openplugin-OpenWebif/commit/6992c8613a5a95e914dc20d4a836f48b8e2c7c4f
should rectify `autoadjust` and `seriesplugin` inputs.

**Comment by jbleyel** [comment]
Empty autotimer list.
```

<autotimer version="7">
<defaults id="-1"> </defaults>
</autotimer>
```

<img width="1318" alt="Bildschirmfoto 2021-03-29 um 20 11 07" src="https://user-images.githubusercontent.com/964927/112880630-f7326280-90ca-11eb-863b-e704d66ec85a.png">

**Comment by jbleyel** [comment]
<input type="checkbox" name="series_labeling" value="**yes**" id="checkbox--series_labeling" class="form-control chk--skinned">

**Comment by jbleyel** [comment]
`<input type="checkbox" name="series_labeling" value="1" id="checkbox--series_labeling" class="form-control chk--skinned">`

**_`value = "yes"`_**

**Comment by jbleyel** [comment]
Nearly finished !!!

`#if $autoadjust == True or $debugMode
`

avoidDuplicateMovies -> OK
autoadjust -> OK
allow_duplicate -> OK !! BUT the default is "1" 
if xml has no allow_duplicate then value = 1


```
	this.autoadjust = false;
	if(xml.attr("autoadjust") === "1") {
		this.autoadjust = true;
	}
	this.allow_duplicate = true;
	if(xml.attr("allow_duplicate") === "0") {
		this.allow_duplicate = false;
	}
	this.avoidDuplicateMovies = false;
	if(xml.attr("avoidDuplicateMovies") === "1") {
		this.avoidDuplicateMovies = true;
	}
```

Example 1:
`
<timer name="AAA" match="BBB" enabled="yes" id="1" autoadjust="1" avoidDuplicateMovies="1" searchType="full" series_labeling="yes"> </timer>`

-> All 3 checkboxes are checked.

Example 2:
`
<timer name="AAA" match="BBB" enabled="yes" id="1" allow_duplicate="0" autoadjust="0" avoidDuplicateMovies="0" searchType="full" series_labeling="yes"> </timer>`

-> All 3 checkboxes are not checked.

Example 3:
`
<timer name="AAA" match="BBB" enabled="yes" id="1" searchType="full" series_labeling="yes"> </timer>`

-> Only allow_duplicate checkbox is checked.

**Comment by wedebe** [comment]
> Nearly finished !!!
> ...
> avoidDuplicateMovies -> OK
> autoadjust -> OK
> allow_duplicate -> OK !! BUT the default is "1"
> if xml has no allow_duplicate then value = 1
> 

https://github.com/wedebe/e2openplugin-OpenWebif/commit/0ca0541da9d8ba694ebbac2df28a75cdc75238d3
sets allow_duplicate to 1 by default

**Comment by wedebe** [comment]
Please also let me know if you find any special character/umlaut issies in `name`, `match text` or `filter text` fields.

**Comment by jbleyel** [comment]
XML ->
```
<timer name="Ä" match="Ä" enabled="yes" id="95" encoding="UTF-8" searchType="exact" overrideAlternatives="1">
<include where="title">Ü</include>
<include where="shortdescription">Ä</include>
<include where="description">Ö</include>
</timer>
```

Success!!

**Comment by jbleyel** [comment]
CSS issue:

<img width="764" alt="Bildschirmfoto 2021-03-30 um 12 41 24" src="https://user-images.githubusercontent.com/964927/112976525-445b1680-9155-11eb-89a0-7850a04eb7e9.png">

**Comment by jbleyel** [comment]
There are some another issues in my mind.
1. You should switch back to list if you have open an autotimer for edit and you click the "autotimer list" left menu item.
2. If you click cancel in autotimer edit you get always the question (discard? ...) also if you do not have changed something
(it's difficult .. i know)

**Comment by wedebe** [comment]
> There are some another issues in my mind.
> 
> 1. You should switch back to list if you have open an autotimer for edit and you click the "autotimer list" left menu item.
I tried a fix for this, but it introduces a bigger issue whereby the page flickers, spinner loads and page re-shows. It's something that I (eventually) intend to be fixed. Essentially `load_maincontent` and its relatives consider anything with #at as the same page, so won't request a reload. Rather than fudge a fix to handle this scenario, I believe a proper routing library would really help here, but the other owif pages aren't in the right state currently to implement such a thing in the best way possible.

> 2. If you click cancel in autotimer edit you get always the question (discard? ...) also if you do not have changed something
>    (it's difficult .. i know)
The latest code switches `discard` to `save` which is less confusing, as the user won't think they've lost anything. They could still lose data input by changing url/clicking a menu item./etc...
Detecting form entry change would need the use of a library to get right, and even then it's a pain in the nuts to do! >_<

**Comment by wedebe** [comment]
> XML ->
> 
> ```
> <timer name="Ä" match="Ä" enabled="yes" id="95" encoding="UTF-8" searchType="exact" overrideAlternatives="1">
> <include where="title">Ü</include>
> <include where="shortdescription">Ä</include>
> <include where="description">Ö</include>
> </timer>
> ```
> 
> Success!!

Are these read back into the form fields correctly for you too?

**Comment by wedebe** [comment]
@jbleyel , do you consider there to be any issues/bugs that would prevent this being released in its current form?

Any small issues would of course be worked on at a later date.

**Comment by jbleyel** [comment]
I think you can make the pull.
I see only a few small css issues.

**Comment by wedebe** [comment]
Thanks @jbleyel !!
