### ISSUE TITLE
sleeptimer API endpoint not working

### ISSUE THREAD

**Issue by mkllrtxn** [E2OpenPlugins/e2openplugin-OpenWebif#1295]
I have been trying to use the API endpoint to set a sleeptimer but without success.

It seems there is some kind of bug or problem, when I try the "get" command of sleeptimer I receive:

404 Client Error: Not Found for url: http://xxx.xxx.xxx.xxx:yyyy/api/sleeptimer?cmd=get

And if I try to "set" a sleeptimer I always receive a False result:

{'message': 'SleepTimer error', 'result': False}

I am running the Openwebif version available with the latest OpenATV 6.4 version on a Gigablue QUAD 4K

I have not been able to debug the problem even if I tried to do so by activating the debug mode in Openwebif configuration.

If you need more information, let me know.

Thanks

**Comment by jbleyel** [comment]
Please get the last update and try again.

**Comment by mkllrtxn** [comment]
Excuse my ignorance, but how can I update to the latest version of the repo?

I have to do it by copying the files? The update manager on openATV shows no software updates

Thanks

**Comment by jbleyel** [comment]
You need to wait until tomorrow.

**Comment by mkllrtxn** [comment]
It is working now, at least I receive an answer when performing a 'get' command and I can 'set' an sleeptimer.

But I think it is still not working properly. If I set a sleeptimer using the UI on openATV when I perform a 'get' command I receive that the sleeptimer is enabled but the time is incorrect. Perfoming a 'get' command always returns a 60 minute duration. Perhaps it has to work as it is because openwebif is unable to obtain the minutes of a running sleeptimer.

The same happens when I send a 'set' command and then a 'get' command the minutes are incorrect, always 60. 

After 'set':
{'action': 'shutdown', 'minutes': 15, 'message': 'Temporizador de apagado activado', 'enabled': True}

After 'get':
{'action': 'deepstandby', 'minutes': 60, 'message': 'Temporizador de apagado activado', 'enabled': True}

Thanks for your help

**Comment by jbleyel** [comment]
The next update should fix your issue.

**Comment by mkllrtxn** [comment]
Hi!

The 'set' command is now fully working. However, the 'get' is still not working properly.

If I set the sleeptimer using the UI I receive the minutes that have been configured. But I should receive the remaining time right?

And If I 'set' the sleeptimer using the command of the API, the 'get' command always returns 0 minutes.

After 'set':
{'action': 'standby', 'minutes': 23, 'message': 'Temporizador de apagado activado', 'enabled': True}

After 'get':
{'action': 'standby', 'minutes': 0, 'message': 'Temporizador de apagado activado', 'enabled': True}

**Comment by jbleyel** [comment]
Set sleeptimer allows not all values for time.
The next update will use 60 minutes if the value is not valid.

The remaining time will be included in one of the next updates if possible.

**Comment by jbleyel** [comment]
The sleeptimer should be ok on OpenATV now.
But it needs to be checked for images based on OpenPLI.

**Comment by jbleyel** [comment]
Hi @mkllrtxn , can we close this issue?

**Comment by mkllrtxn** [comment]
Hi, sorry for the delayed response. It seems to be working fine now. You can close the issue.

Thanks!
