### ISSUE TITLE
Timer anlegen im Menue Fernsehen per EPG nicht möglich

### ISSUE THREAD

**Issue by ThomasderErste** [E2OpenPlugins/e2openplugin-OpenWebif#1296]
wenn ich links auf "Fernsehen" klicke, dann einen Sender auswähle, dann auf das EPG für diesen Sender gehe, dann eine Sendung mit "Timer bearbeiten" auswähle, wird kein Sendungsname angezeigt, und ich kann so keinen Timer anlegen.
Es ist kein Name/ Beschreibung angegeben.
VTI 15.0.0.
OWIF 1.4.5.

**Comment by jbleyel** [comment]
Hi @wedebe : edit timer not working in channel epg.
It's the second button here -> 

<img width="1168" alt="Bildschirmfoto 2021-03-29 um 17 15 10" src="https://user-images.githubusercontent.com/964927/112858731-6ea7c800-90b2-11eb-8862-30b468d13a75.png">

The first button works.

**Comment by jbleyel** [comment]
```
      var epgEvent;
      try {
        var dataAttr = 'metadata';
        epgEvent = JSON.parse(e.relatedTarget.closest('[data-' + dataAttr + ']').dataset[dataAttr]);
      } catch (ex) {
		console.log(ex);
        epgEvent = {};
      }

```


<img width="729" alt="Bildschirmfoto 2021-03-29 um 17 49 20" src="https://user-images.githubusercontent.com/964927/112863414-1f17cb00-90b7-11eb-83ad-72bbaabeba3e.png">

**Comment by wedebe** [comment]
I can't replicate this, could you outline the steps to reproduce, please?
Does it always happen, or just intermittently?
Has it always happened or broken in a recent build (I'm not aware of there being any changes to that part of owif lately)
Which browser and version?

**Comment by jbleyel** [comment]
Chrome Mac.

`<a href="javascript:void(0);" class="link--skinned" data-dismiss="modal" data-toggle="modal" data-target="#TimerModal" data-evid="5890" data-ref="1:0:19:283D:3FB:1:C00000:0:0:0:" title="Timer bearbeiten"><i class="material-icons material-icons-centered">alarm</i></a>
`

**Comment by jbleyel** [comment]
I have done some more log and this result is null.
`e.relatedTarget.closest('[data-' + dataAttr + ']')`


```
      try {
        var dataAttr = 'metadata';
		console.log(e);
		console.log(e.relatedTarget);
		console.log(e.relatedTarget.closest('[data-' + dataAttr + ']'));
        epgEvent = JSON.parse(e.relatedTarget.closest('[data-' + dataAttr + ']').dataset[dataAttr]);
      } catch (ex) {
		console.log(ex);
        epgEvent = {};
      }

```

<img width="738" alt="Bildschirmfoto 2021-03-30 um 11 37 24" src="https://user-images.githubusercontent.com/964927/112968179-54222d00-914c-11eb-9b77-938a2959db49.png">

**Comment by jbleyel** [comment]
It works if i use the second button here.
<img width="573" alt="Bildschirmfoto 2021-03-30 um 11 43 36" src="https://user-images.githubusercontent.com/964927/112969138-428d5500-914d-11eb-9ad9-086ddab200b5.png">


<img width="725" alt="Bildschirmfoto 2021-03-30 um 11 44 42" src="https://user-images.githubusercontent.com/964927/112969221-55a02500-914d-11eb-918e-e11a52435e69.png">

**Comment by jbleyel** [comment]
Please check .. ->
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/5d1d81a07b17f52826370f5892e48bd334e7878e

**Comment by wedebe** [comment]
Even with a fresh install I couldn't get add-edit from epg dialog to break.

#1299 should fix

**Comment by jbleyel** [comment]
Do you see my commit?
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/5d1d81a07b17f52826370f5892e48bd334e7878e

**Comment by jbleyel** [comment]
In the channel is no metadata attribute and the old js needs data-metadata.
So therefore you must have the issue or you have a different template.

Your pull should also fix this but makes the html much larger and you have sref,evid twice.
