### ISSUE TITLE
Installation in Dreambox dm920 -nwenigma2 (vers. OWF 1.4.45)

### ISSUE THREAD

**Issue by paparas12** [E2OpenPlugins/e2openplugin-OpenWebif#1298]
Installiert das *.Deb file aus dem paketmanager
Nach der Restart der Box habe ich folgende Nachricht
Some Plugins are not available:
Extensions/Openwebif(cannot import name iNetwork)
Der OWF erscheint nicht unter PLUGINs.

**Comment by jbleyel** [comment]
LESEN!!!!

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1281#issuecomment-808712962
