### ISSUE TITLE
modern UI mutliepg timer indication

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1300]
I think this ellipsis looks not that good.

<img width="337" alt="Bildschirmfoto 2021-03-30 um 23 46 25" src="https://user-images.githubusercontent.com/964927/113061406-443d3400-91b2-11eb-93ff-f8ebd1167dad.png">

**Comment by rdamas** [comment]
Full ack! (I've changed that locally for me in multiepg.tmpl:
```
@@ -58,14 +58,14 @@
        .epg__event.event--has-timer::after {
                content: '';
     display: block;
-    border-radius: 50%;
+    border-radius: 0;
     top: -25%;
-    right: -5%;
+    right: 0;
     bottom: -10%;
-    left: -10%;
+    left: -10px;
     position: absolute;
-    border-width: 2px;
-               border-style: solid;
+    border-style: solid;
+    border-width: 0 0 0 3px;
   }
```
)

While we are at it: hovering in Multi EPG over the 2 hour time slots is, well, unfortunate - it changes background color equal to white; my fix in multiepg.tmpl is:

```        #fulltbl .theme--city-lights .table-striped>tbody>tr:nth-of-type(odd):hover { 
-    background-color: initial;
+    /* background-color: initial; */
        }
```
