### ISSUE TITLE
API - EPG refresh/generated time

### ISSUE THREAD

**Issue by ciuly** [E2OpenPlugins/e2openplugin-OpenWebif#1306]
**Is your feature request related to a problem? Please describe.**
In my project, I implemented caching support to speed things up. Now the problem is that the EventID will change once the EPG is refreshed/recreated. It will stay the same for a while though, doing consecutive gets on the epg (hence my caching idea).
I tried to figure out a sure-tell for when to invalidate the cache but can't seem to figure out the right time/condition.
This results in my case in wrong created timers, errors in some cases about invalid EventID, and all sorts of weird things due to the caching.

**Describe the solution you'd like**
I think having some way of telling when the EPG re-creates the event IDs would be of some help in these kinds of situations 
Eg: having the time the epg is re-created on the epg apis (EpgGeneratedTime or such), or maybe a unique (incremental) EpgID, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

I'm willing to implement this myself if there is no time for this in the next few weeks, but in order to save everybody time and headache, we should agree on the solution first.

Thanks

**Comment by jbleyel** [comment]
I think you are on the wrong place here.
This API needs to be implemented in EPGRefresh plugin but this will also not help because the EPG cache is part of enigma2.

**Comment by rdamas** [comment]
Furthermore, stations change the event id's of their programme at will (or not) - that completely depends on the station. Unfortunately the event id is nothing you can depend on.

**Comment by ciuly** [comment]
@jbleyel  you could be right; I am new to this openwebif and enigma stuff.
Is this the project you mention? https://github.com/OpenPLi/enigma2-plugins/tree/master/epgrefresh

@rdamas actually, the API itself has a lot of calls based on the eventID, so no matter who and when changes that, the API is still able to handle it somehow and not act on the wrong event (ok, this last part I am just assuming, but I figure it would be pretty nasty to not be like that).

**Comment by jbleyel** [comment]
The epgrefreh plugin is only a scheduled task to get the epg data by switching through the channel list and writes the epg data in the cache. The eventid is not a unique id.

**Comment by rdamas** [comment]
If you are referring to OpenPLi, it's rather https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/epgcache.cpp that's involved.

**Comment by ciuly** [comment]
Thank you both. It does seem that this is getting a bit too complex (spread all over the place) so instead I will go with another local solution: will generate a unique ID based on the event details and cache by that.
I guess I will close this request then.
