### ISSUE TITLE
Modern Design - Linkes Menü scrollt zu wenig

### ISSUE THREAD

**Issue by SattSeher** [E2OpenPlugins/e2openplugin-OpenWebif#1309]
Abhängig von Display Einstellung und -Auflösung scrollt der linke Bereich nicht weit genug, so dass die EXTRAS nicht oder nur teilweise zu sehen sind.
Ist am Tablet und am PC im Browser auch von mehreren im VU+ Forum gemeldet worden.
Beim alten Design scrollt ja die "ganze Seite"

Danke für´s Fixen.

**Comment by jbleyel** [comment]
Hi @wedebe : the left menu have a scroll issue if you display the remote control.
Extras are not visible.

<img width="298" alt="Bildschirmfoto 2021-04-10 um 20 35 45" src="https://user-images.githubusercontent.com/964927/114281023-56ce2d80-9a3c-11eb-9dd1-7ea1b600fada.png">

**Comment by SattSeher** [comment]
Even without the remote control, the scroll area is not sufficient with a higher zoom level and / or corresponding screen resolution

**Comment by SattSeher** [comment]
seems ALL to be working - thanks
however there is now "television" instead of "Fernsehen" and "FTP" instead of "Fernbedienung"

**Comment by jbleyel** [comment]
Please provide a screenshot with the wrong text.

**Comment by SattSeher** [comment]
![grafik](https://user-images.githubusercontent.com/82285274/114573802-fd067700-9c78-11eb-8182-1116fcfb3ba4.png)

**Comment by jbleyel** [comment]
FTP finde ich nirgends.
Television ist der englische default text.
Da passt was mit deinen po Dateien nicht.

**Comment by SattSeher** [comment]
Ne, aktuelles Update hat´s gefixt ;-)  
Danke

**Comment by jbleyel** [comment]
Die mo Dateien haben in dem ipk gefehlt.
FTP verstehe ich aber trotzdem nicht.

**Comment by jbleyel** [comment]
Ohne die mo Datei steht bei mir "Remote" und nicht FTP .. Das muss wohl am Image liegen.

**Comment by SattSeher** [comment]
Wie gesagt, hier passt es wieder
![grafik](https://user-images.githubusercontent.com/82285274/114592312-10bad900-9c8b-11eb-8022-7c10b51a52f7.png)
