### ISSUE TITLE
Bottom Scrollbar in EPG-View missing

### ISSUE THREAD

**Issue by thorbytes** [E2OpenPlugins/e2openplugin-OpenWebif#1310]
In the EPG-View only on Thursday and Friday the bottom scrollbar is missing. If I switch to the next calendar week it appears. Tested on several Browsers with empty cache and version 1.4.5-git20210410.

**Comment by jbleyel** [comment]
I have the scrollbar on Sa. So. and Th. of the current week only.
This looks like an issue of the content data.

**Comment by wedebe** [comment]
Hi @thorbytes , could you attach a screenshot of the full problematic page, please?

**Comment by jbleyel** [comment]
Hi @wedebe .. the issue occurs if the first row is longer than the screen.
See red marked area.

<img width="687" alt="Bildschirmfoto 2021-04-12 um 17 08 14" src="https://user-images.githubusercontent.com/964927/114417317-c87bb800-9bb1-11eb-8ce4-f1f7af520f1d.png">

**Comment by thorbytes** [comment]
Hi @wedebe , here a screenshot of a page without bottom scrollbar.

![grafik](https://user-images.githubusercontent.com/40144141/114427888-d7676800-9bbb-11eb-9eee-cf4206080ce1.png)

**Comment by wedebe** [comment]
Can the area still be scrolled horizontally by mouse/trackpad/touch?

**Comment by jbleyel** [comment]
Yes .. scrolling is possible. It's only a bottom scrollbar visibility problem.

**Comment by thorbytes** [comment]
Yes, it can be scrolled by arrow keys.

**Comment by wedebe** [comment]
Most likely a regression from #1290 

Screenshot from a July 2020 image for reference:

<img width="1680" alt="Screen Shot 2021-04-13 at 00 33 06" src="https://user-images.githubusercontent.com/9741693/114475439-31822080-9bf0-11eb-8992-90c15529d2ae.png">

**Comment by wedebe** [comment]
Most likely a regression from #1290

Screenshot from a July 2020 build of OpenATV:

<img width="1314" alt="" src="https://user-images.githubusercontent.com/9741693/114475563-6c845400-9bf0-11eb-92b3-e3c6b3c8e222.png">

**Comment by thorbytes** [comment]
Fixed with latest version 1.4.6 of today :-)
