### ISSUE TITLE
Streams are no longer displayed

### ISSUE THREAD

**Issue by SattSeher** [E2OpenPlugins/e2openplugin-OpenWebif#1312]
The new design only shows whether and which recordings are in progress. 
Streams are no longer displayed. 
Can you put that back in? (Question from the VTI forum)

**Comment by jbleyel** [comment]
Is this a new design issue only.

**Comment by SattSeher** [comment]
yes, in the old design the display doesn't exist (never or no more). 
At the time of the screenshot, there was 1 recording and an additional stream. The recording is displayed, the stream is not. Other users in the forum were of the opinion that streams were also displayed there beforehand.
never or no more
![grafik](https://user-images.githubusercontent.com/82285274/114386879-1385d300-9b92-11eb-9aad-bcbe905ce6d4.png)

**Comment by jbleyel** [comment]
I need the info.py from the OWF where this feature is working.
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models

**Comment by jbleyel** [comment]
Please start a stream and the open this link in a browser.

`http://<IP OF THE BOX>/api/about`

.. and provide the output.

**Comment by SattSeher** [comment]
the output:  just the square brackets without content
**streams: [ ]**

**Comment by jbleyel** [comment]
Then i need this file.

/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/info.py
or
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/info.pyc
or
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/info.pyo

**Comment by SattSeher** [comment]
[info.py.txt](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/6298937/info.py.txt)

**Comment by jbleyel** [comment]
Sorry my fault.
I need this file from the running version.

**Comment by jbleyel** [comment]
Please get the latest version and try again.

**Comment by SattSeher** [comment]
sorry, I didn't report it here. The problem has been fixed with the FIX for scrolling. Thank you and can be set as done
