### ISSUE TITLE
"Serienrecorder" is missing

### ISSUE THREAD

**Issue by SattSeher** [E2OpenPlugins/e2openplugin-OpenWebif#1326]
Hello, in the last version the menu item "Serienrecorder" is missing at EXTRAS

![grafik](https://user-images.githubusercontent.com/82285274/115716645-ac2e0700-a379-11eb-811c-42f4e8ddfce5.png)

**Comment by jbleyel** [comment]
No BUG.
It's a request from the dev.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1001

**Comment by SattSeher** [comment]
OK

**Comment by jbleyel** [comment]
Das Serienrecorder Webinterface funktioniert.
Du brauchst die neuste version vom openwebif und die version 4.3.0 vom serienrecorder.
In de Einstellungen vom serienrecorder musst du Webinterface aktivieren.
Dann Neustart enigma und es geht.
