### ISSUE TITLE
Scrolling EPG list in web browser issue

### ISSUE THREAD

**Issue by feartech** [E2OpenPlugins/e2openplugin-OpenWebif#1327]
**Describe the bug**
Scrolling down the EPG in web browser stops before showing the whole day epg (missing scroll bars)

**To Reproduce**
open up web browser, navigate to box and then EPG. try and scroll down

**Expected behavior**
EPG should carry on listing the day's epg and should show up and down scroll bars

**Screenshots**
what it looks like currently:
https://www.feartech.co.uk/1.jpg 

and this is what it should look like after editing the css code - #fulltbl and disabling the "overflow-y"
https://www.feartech.co.uk/2.jpg 

**Image (please complete the following information):**
 - OS: OpenATV
 - Version [e.g. 6.4]

**Desktop (please complete the following information):**
 - Browser issues on all browsers

**Additional context**

**Comment by jbleyel** [comment]
Removal of "overflow-y" will fix the scroll issue but after that you will have a new issue.
The bottom of the epg data overlaps the footer.

**Comment by feartech** [comment]
> Removal of "overflow-y" will fix the scroll issue but after that you will have a new issue.
> The bottom of the epg data overlaps the footer.

doesn't seem like it:
https://www.feartech.co.uk/3.jpg 

or maybe it should be set to scroll ?

**Comment by feartech** [comment]
everything was fine before, maybe this messed it up:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/1316 

or something similar?

**Comment by feartech** [comment]
thank you for fixing this :)
