### ISSUE TITLE
Cannot delete movie with double quotes around its title

### ISSUE THREAD

**Issue by elmicha** [E2OpenPlugins/e2openplugin-OpenWebif#1330]
I cannot delete the movie _"Mir ist es egal, wenn wir als Barbaren in die Geschichte eingehen" - arte HD_ (note the double quotes that are in the title). In the JS console I see `Uncaught SyntaxError: '' string literal contains an unescaped line break"`. 

The `a` tag on the delete button looks strange:

    <a href="javascript:void(0);" onclick="deleteMovie('1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3A/media/usb/movies/20210428%202230%20-%20_Mir%20ist%20es%20egal%2C%20wenn%20wir%20als%20Barbaren%20in%20die%20Geschichte%20eingehen_.ts', '8', '" mir="" ist="" es="" egal,="" wenn="" wir="" als="" barbaren="" in="" die="" geschichte="" eingehen"');="" return="" false;"="" title="Aufnahme löschen"><i class="material-icons material-icons-centered">delete</i></a>

For other movies the `a` tag looks normal:

    <a href="javascript:void(0);" onclick="deleteMovie('1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3A/media/usb/movies/20210427%202055%20-%20Doctor%20Who%20%284%29.ts', '9', 'Doctor Who (4)'); return false;" title="Aufnahme löschen"><i class="material-icons material-icons-centered">delete</i></a>

 - OS: OpenATV
 - Version 6.5

 - Browser: Firefox 88.0
 - In Chrome 87.0.4280.88 the problem is the same, only the error message is a bit different: "Uncaught SyntaxError: Invalid or unexpected token"

**Comment by jbleyel** [comment]
Wie ist der genau Dateiname von der TS Datei auf der Box?
Und bitte mal die TS.META hier posten.
