### ISSUE TITLE
Error create autotimer from EPG / Responsive UI

### ISSUE THREAD

**Issue by ThomasderErste** [E2OpenPlugins/e2openplugin-OpenWebif#1335]
Beim Versuch, einen Autotimer anzulegen, wird zwar die Autotimer-Liste geladen, aber der entsprechende Timer wird nicht übernommen. 
VTI 15.0.0
Windows 10
Firefox 88.0.1 64 bit
openwebif_1.4.6-git20210511_vti.ipk

**Comment by jbleyel** [comment]
Ich kann den Fehler nicht nachstellen, daher muss das ein Problem vom autotimer Plugin auf VTi sein.
Das muss jemand anders fixen.

**Comment by rdamas** [comment]
Der Bug-Report ist leider alles andere als ausführlich, ich habe auch erst im dritten Anlauf verstanden, wie der Fehler reproduzierbar ist; und bin mir auch nicht sicher, ob der Fehler VTi spezifisch ist. Wenn ja, schaue ich gerne weiter.

Schritte um den Fehler im **Responsive Design** zu reproduzieren (im classic mode funktioniert alles): 
- wähle Menupunkt "Fernsehen"
- öffne bei einer beliebigen Sendung die Sendungsdetails ("more details", Klick auf den Sendungsnamen)
- im jetzt geöffneten modalen Dialog in der untersten Zeile mit den Timer-Icons rechts den Autotimer-Button wählen (warum sieht diese Icon anders aus als die anderen Icons?)
- es wird eine URL /#/at/create mit Parametern für den neuen Autotimer aufgerufen
- die Autotimer-Liste wird geöffnet, aber sonst passiert nichts; kein neuer Eintrag, kein Editor für einen neuen Eintrag

Wobei ich schon nicht mehr durchschaue, wie und wo das Routing der URL hier passiert und funktionieren sollte.

**Comment by MacDisein** [comment]
Das Verhalten habe ich übrigens auch, wenn aus dem EPG über den AutoTimer Button einen AutoTimer anlegen möchte.
Die URL die aufgerufen wird, sieht dann so:
http://e4hd/#/at/create?name=Quarks%20im%20Ersten&match=Quarks%20im%20Ersten&timespanFrom=11:30&timespanTo=12:00&sref=1:0:19:283D:3FB:1:C00000:0:0:0:

![image](https://user-images.githubusercontent.com/8401876/118355853-a5f30b00-b572-11eb-86cd-229550800e04.png)


Bei mir erscheint dann allerdings ein leerer Eintrag in der AutoTimer Liste den man aber weder bearbeiten noch löschen kann.
![image](https://user-images.githubusercontent.com/8401876/118355873-bf945280-b572-11eb-952a-0bbb9262b928.png)

Ist übrigens kein VTI sondern openATV

**Comment by jbleyel** [comment]
Hi @wedebe , create autotimer from epg nor working.

**Comment by jbleyel** [comment]
Bitte neue Version holen und prüfen.

**Comment by rdamas** [comment]
Passt.
