### ISSUE TITLE
Filter packages

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1336]
I'm not sure if here is the right place or not (sorry) but would you please add an option to opkg.py to hide extra/developer files?

I mean ('-dev', '-staticdev', '-dbg', '-doc', '-src', '-po')

**Comment by persianpros** [comment]
Thank you :+1:

**Comment by jbleyel** [comment]
Please test!!!

**Comment by persianpros** [comment]
Thanks a lot, you're so fast :+1: 

But I didn't find any options to enable/disable it, for example in OV we have:

https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/lib/python/Plugins/SystemPlugins/SoftwareManager/plugin.py#L1593

We call those developer packages so disabled by default (all of them).

**Comment by jbleyel** [comment]
step1 API 
step2 UI

**Comment by persianpros** [comment]
For me it loads and loads and no results ...

**Comment by jbleyel** [comment]
> For me it loads and loads and no results ...

Please check the enigma debug log.

**Comment by jbleyel** [comment]
Hi @persianpros , can I close this?

**Comment by persianpros** [comment]
Yes 👍
