### ISSUE TITLE
Bouquet-Editor - Import not working on modern UI

### ISSUE THREAD

**Issue by Masta2002** [E2OpenPlugins/e2openplugin-OpenWebif#1339]
Wenn ich versuche sendelisten zu importieren passiert bei mir leider nichts. Es kommt zwar eine erfolgreich meldung ich finde aber leider nirgends etwas

**Image (please complete the following information):**
 - VTI
 - V15 mit den letzten updates

**Desktop (please complete the following information):**
 - Firefox
 - 88.0.1

**Comment by jbleyel** [comment]
Hi @wedebe, the apiRequest makes an GET request but must be POST.

```
              const formData = new FormData(fileUploadForm);
              apiRequest(fileUploadForm.action, {
                method: fileUploadForm.method,
                body: formData,
              })
                .then(() => {});

```

**Comment by Masta2002** [comment]
any hope that this will fixed anytime soon?

**Comment by jbleyel** [comment]
Hi @wedebe , could you please check this.
Thanks

**Comment by jbleyel** [comment]
Hello @Masta2002 , please try again using the latest version.

**Comment by Masta2002** [comment]
hello @jbleyel with latest verion iz works now for me! Thank you!
