### ISSUE TITLE
Modern - AutoTimer editor - sort order

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1341]
The previous editor design had a drop-down list sorted on definition name.

The revamped editor just lists the definitions in the order they're found in the autotimer.xml file.
This makes the editor unusable.
One can't even use a CTRL-F to find the definition by name; as this opens up the "EPG Search" field.

**Comment by wedebe** [comment]
I'd like to add filter & sort options, the modern js has a baseline ready for this. In the meantime I'll set to sort by name.
