### ISSUE TITLE
Customize / Anpassen menu item 

### ISSUE THREAD

**Issue by SattSeher** [E2OpenPlugins/e2openplugin-OpenWebif#1343]
Do not know whether it is intended and it is not a real bug.
If you click on Settings in the modern view, the "Customize" item opens.
Four points below, the same settings come again under "Anpassen".
So it's double.

**Comment by jbleyel** [comment]
Please provide a screenshot.

**Comment by SattSeher** [comment]
![grafik](https://user-images.githubusercontent.com/82285274/119714620-5f9b8700-be63-11eb-8224-8c2856b7485a.png)

![grafik](https://user-images.githubusercontent.com/82285274/119714424-26631700-be63-11eb-9aa6-d47419cf6b59.png)

![grafik](https://user-images.githubusercontent.com/82285274/119714543-485c9980-be63-11eb-81b1-dec5200cc288.png)
