### ISSUE TITLE
Autotimer Test Resource for VTi needs argument "id=n"

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#1344]
VTi still has AutoTimer API version 1.3 (and probably won't upgrade anyway).

/autotimer/test here needs an argument "?id=n" to complete. 

I haven't tested Autotimer API version 1.6, but from the source code it seems to not need that argument!? (If that's true: why was that API changed in the first place, and why wasn't the version number raised to 2.0 then? In my opinion the API version number needs to be checked here to avoid incompatible changes like this.)

As a consequence, in classic design the "Test" button ("atbutton6") has to add the "id=n" argument to /autotimer/test

In modern design, the "Preview" button needs to be put in the Autotimer edit dialog and probably alongside the edit/toggle/delete buttons in the autotimer list.

What would be the best way to achieve this? I'm absolutely willing to help here.

**Comment by jbleyel** [comment]
I think we do not really need the test button. Parse and simulate should be enough.

**Comment by rdamas** [comment]
Yeah, maybe. 

On the other hand: /autotimer/test will search only programs related to that specific Autotimer, so it is useful to check, if the settings for the specific Autotimer entry will find what you had in mind.

**Comment by jbleyel** [comment]
Okay. I need to fix the OE autotimer plugin first.

**Comment by wedebe** [comment]
For reference, here's a query I had in relation to this - #1102

And here's a proposal for where to place the new button:
<img width="890" alt="Screen Shot-prev" src="https://user-images.githubusercontent.com/9741693/119968684-a7c2c280-bfa5-11eb-969c-ef708230008e.png">

However, passing an id didn't work as expected at the time I worked on this.

**Comment by rdamas** [comment]
Yeah, probably because API 1.6 doesn't take the "id" argument; here's the relevant code from API 1.3:

```
class AutoTimerTestResource(AutoTimerBackgroundingResource):
        def renderBackground(self, req):
                id = req.args.get("id")
                ret = []
                if id:
                        autotimer = self.getAutoTimerInstance()
                        ret = autotimer.parseEPG(simulateOnly = True, testtimer = str(id[0]))
   ...
```
and this is what 1.6 looks like:

```
class AutoTimerTestResource(AutoTimerBaseResource):
        def parsecallback(self, timers, skipped):
                ret = self.renderBackground(self.req, timers, skipped)
                self.req.write(ret)
                self.req.finish()

        def render(self, req):
                self.req = req
                # todo timeout / error handling
                autotimer.parseEPG(simulateOnly=True, callback=self.parsecallback)
                return server.NOT_DONE_YET

    ...
```

For me passing an "id" argument returns an XML document with the program entries found for the specific Autotimer.

**Comment by jbleyel** [comment]
I have fixed the OE plugin and i have also changed the xml tag name from test to simulate.
This is now the same implementation like the original DMM autotimer.
VTi should also change the xml tag name.

**Comment by rdamas** [comment]
The root tag name usually doesn't matter.

**Comment by jbleyel** [comment]
not so easy..check this.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/abe8d9d3644651a41c89c14353366fb35e3bc3c4

**Comment by jbleyel** [comment]
TODO: Test, minimize js, implement in modern UI

**Comment by rdamas** [comment]
We can easily fix this within at.js - in ``parsetest_simulate()`` change the selector for ``find()`` to ``$(xml).find("e2simulatetimer,e2testtimer")`` 

BTW: there's a bug in constructing the autotimer/test URL - please use "?" instead of "&".

**Comment by rdamas** [comment]
Works for me in classic mode - thanks!

**Comment by rdamas** [comment]
Everything fixed, I guess, so closing.
