### ISSUE TITLE
AutoTimer preview - broken

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1349]
In the Modern interface, there's an individual definition preview button.
This chucks up a spinner and never clears.

In the Classic interface, "Simulate" gives rise to an empty results list ("NO Timer found").
However, the "Test" function does return results.

In both interfaces, _all_ of the AutoTimer definitions are parsed (as evidenced in the debug log).
Thus this appears to be a half-arsed implementation.

**Comment by wedebe** [comment]
There's a typo `date[` in place of `data[` in a recent change.

**Comment by jbleyel** [comment]
Hi @wedebe, do you have the latest version of the autotimer plugin?

**Comment by Grumpy-Geoff** [comment]
> There's a typo `date[` in place of `data[` in a recent change which may be the culprit.

Another typo?  "e2simulate**d**timer" ==> "e2simulatetimer"
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/0b475780a7a6d2bf0efafc24e0a1772b2f6f4c5c



> I plan to restore the Preview (ALL) button as non-support of that in any particular image should present an error message instead of having the functionality removed (users may still want to preview ALL events that are matched by ALL ATs, and images which are kept up-to-date shouldn't suffer from such functionality removals!).

There seems to be no point in moving to individual preview/simulate actions for each definition if all of the definitions are parsed against the EPG.
