### ISSUE TITLE
Modern - AutoTimer "test" - previous results not cleared

### ISSUE THREAD

**Issue by Grumpy-Geoff** [E2OpenPlugins/e2openplugin-OpenWebif#1351]
The previous list of results from the "test" action are not cleared upon the next "test" action.
e.g. from below debug log entries -
#1 Overhaulin' has results and returned a list
#2 Salvage Hunters: Classic Cars has no results, but the previous Overhaulin' results was shown
#3 Screen Time has no results, but the previous Overhaulin' results was shown
```
{875}<  1222.385> [eEPGCache] lookup events, title starting with 'Overhaulin'' (case sensitive)
{592}<  1222.939> [Task] job Components.Task.Job name=AutoTimer #tasks=2 completed with [] in None
{592}<  1251.032> [AutoTimer] No changes in configuration, won't parse
{592}<  1251.059> [Task] job Components.Task.Job name=AutoTimer #tasks=1 completed with [] in None
{592}<  1274.532> [AutoTimer] No changes in configuration, won't parse
{874}<  1274.552> [eEPGCache] lookup events, title starting with 'Salvage Hunters: Classic Cars' (ignore case)
{592}<  1275.066> [Task] job Components.Task.Job name=AutoTimer #tasks=2 completed with [] in None
{592}<  1382.619> [AutoTimer] No changes in configuration, won't parse
{874}<  1382.640> [eEPGCache] lookup events, title starting with 'Screen Time' (ignore case)
{592}<  1383.155> [Task] job Components.Task.Job name=AutoTimer #tasks=2 completed with [] in None

```

[The button is labelled "Preview" but the "test" function is actually run.]

**Comment by jbleyel** [comment]
Is this a modern UI issue only? What are the results via classic UI?

**Comment by Grumpy-Geoff** [comment]
> Is this a modern UI issue only? What are the results via classic UI?

Yes, that's why I wrote "Modern" in the issue title.
