### ISSUE TITLE
BUG Button  radio Extend Remote  for VTI Vu+ Duo4K SE

### ISSUE THREAD

**Issue by IncendioMoussy** [E2OpenPlugins/e2openplugin-OpenWebif#1357]
In classique mode The Extend Remote  for VTI Vu+ Duo4K SE, the virtual Keyboard button radio no run 
Version teste : enigma2-plugin-extensions-openwebif_1.4.8-git20210611-r9_vti.ipk

Système OE: | OpenVuplus 2.1
-- | --
Version du firmware: | VTi-Team Image 15.0.0 (2021-02-01-vti-master (531279a93))
Version du noyau / Pilotes: | 4.1.45 / 20200903
Open Source Web Interface pour récepteur Linux
Version: OWIF 1.4.8
Site et sources: Github

![image](https://user-images.githubusercontent.com/34140882/121773309-70463f80-cb7b-11eb-8676-09d5b6f94ef1.png)

**Comment by rdamas** [comment]
Can you try to change the second last line in the file 
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/public/static/remotes/vu_normal_02.html:

<area shape="rect" coords="100.328.120.338" id ="385" title="radio" onclick="pressMenuRemote('385');">

to 

<area shape="rect" coords="100,328,120,338" id ="385" title="radio" onclick="pressMenuRemote('385');">

I wonder who had the not so great idea to use ip address syntax for map coordinates here...

I can  prepare a PR, but @jbleyel might be quicker than me to change that file :-)

**Comment by jbleyel** [comment]
Please do the PR.

**Comment by IncendioMoussy** [comment]
THX
