### ISSUE TITLE
Choice of the complete remote control

### ISSUE THREAD

**Issue by IncendioMoussy** [E2OpenPlugins/e2openplugin-OpenWebif#1359]
In the current version, the remote control is automatically selected according to the version of the box.

I changed the remote control on my VU + (wear, ergonomics, etc.)
I would like to have the same virtual remote control on Openwebpif.

I do this manually by changing files.

/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/public/static/remotes/xyz.html
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/public/images/remotes/xyz.png

It will be practical if the user could choose in a preferance the remote control which suits him?

THX

**Comment by wedebe** [comment]
Something like... you've got a `VU+ Duo`, but you'd rather see the `Mut@nt HD51` remote in the sidebar?
