### ISSUE TITLE
Utilise commit hook to build asset sources

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1376]
**Is your feature request related to a problem? Please describe.**
Currently assets source code must be compiled manually and both committed

**Describe the solution you'd like**
It would be great to have source compiled at the commit stage using a [commit hook](https://githooks.com/) by running `npm build-XYZ`
Where XYZ refers to classic and modern separately

**Comment by jbleyel** [comment]
I'll check this.
