### ISSUE TITLE
Direct link to ipk files

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1381]
Is there a way to link directly to the latest .ipk files? The files currently contain build references in their names.
eg.: `enigma2-plugin-extensions-openwebif_1.4.8-git20210718-r4_all.ipk` -> `enigma2-plugin-extensions-openwebif_latest_all.ipk`

Perhaps alsoadd ipk files to /e2openplugin-OpenWebif/releases?

**Comment by jbleyel** [comment]
Releases is not that good.
link to the latest can be done by a symlink .. probably

**Comment by jbleyel** [comment]
I think we should put the download link here (*) because the ipk name should be not `_latest_` ...

(*) http://e2openplugins.github.io/e2openplugin-OpenWebif/
This index.html will be created within the build action.
