### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#1385]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/security/dependabot/sourcefiles/modern/plugins/jquery/jquery.js/jquery/open

**Comment by jbleyel** [comment]
This needs to be tested !!!

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/jQuery-3.6

**Comment by jbleyel** [comment]
Hi @wedebe , can you please test this?

**Comment by wedebe** [comment]
I'm gonna invest any time I contribute into removing jQuery instead. I previously updated it to the most recent major (non-breaking changes) version. 

Historically, jQuery and related plugins tend to trigger a Pandora's box of problems unless they're _all_ updated at the same time; some plugins don't then work with breaking changes/deprecations/api changes that were introduced.

**Comment by jbleyel** [comment]
Please think about the classic UI. There is no plan to remove this! The classic UI needs jQuery.

**Comment by wedebe** [comment]
> Please think about the classic UI. There is no plan to remove this! The classic UI needs jQuery.

I've split the js so that both classic and modern code is now independent - #1397

**Comment by jbleyel** [comment]
Will be fixed in 2.0
