### ISSUE TITLE
Stream funktioniert nicht wenn "Authentifizierung für Streaming aktivieren" aktiviert ist

### ISSUE THREAD

**Issue by LevelOne2k** [E2OpenPlugins/e2openplugin-OpenWebif#1386]
Hallo @jbleyel ,

ich möchte von einer Ultimo 4K an eine Zero 4K streamen. Wenn ich an der Zero 4K den zu streamenden Sender einschalte, dann kommt bei der Ultimo 4K nichts an (eigentlich sollte an der Ultimo 4K ja dann das REC-Symbol blinken).

Der Eintrag für die Sender in den Bouquets sieht wie folgt aus:

> #NAME Stream from Home
> #SERVICE 1:0:19:69:C:85:FFFF0000:0:0:0:http%3A//benutzer%3apasswort@dyn.dnsvpn.de%3a8001/1%3A0%3A19%3A69%3AC%3A85%3AFFFF0000%3A0%3A0%3A0:Sky Sport Bundesliga 1 HD

Warum da hinten jetzt Fragezeichen sind, weiß ich nicht. Eigentlich sieht es so aus:

<img width="815" alt="Bildschirmfoto 2021-07-23 um 07 16 46" src="https://user-images.githubusercontent.com/25386824/126740184-3c15e398-5d80-407c-b5eb-fce8b2f032ed.png">

Wenn ich dann die Option "Authentifizierung für Streaming aktivieren" deaktiviere, funktioniert der Stream sofort. Obwohl der Eintrag oben unverändert ist, also mit den Benutzerdaten. 

Ich weiß das es mal exakt so funktioniert hat. Seit gestern bin ich in meiner Ferienwohnung und es funktioniert plötzlich nicht mehr obwohl weder auf der einen, noch auf der anderen Box (außer Updates) etwas verändert wurde.

Auch wenn ich es ohne den Syntax "%3A" teste und dann stattdessen den : nehme, funktioniert es nicht.

Hast Du eine Ahnung was da jetzt los sein kann?

Danke schon mal.

**Comment by jbleyel** [comment]
Du müsstest diesen Link :

`http://benutzer:passwort@dyn.dnsvpn.de:8001/1%3A0%3A19%3A69%3AC%3A85%3AFFFF0000%3A0%3A0%3A0
`
im VLC auf einem PC testen.

Und diesen im lokalen Netz wo die Ultimo steht.

`http://benutzer:passwort@<IP der Ultimo>:8001/1%3A0%3A19%3A69%3AC%3A85%3AFFFF0000%3A0%3A0%3A0
`

**Comment by jbleyel** [comment]
Kommando zurück!!

Welches Image hast du?

**Comment by LevelOne2k** [comment]
Im VLC funktioniert es problemlos. Und ich habe dann mit Absicht mal einen falschen Benutzer und/oder Passwort in VLC eingegeben, dann läuft der stream nicht. 

Aktuelles VTI.

**Comment by jbleyel** [comment]
Bei VTi kann ich leider nicht helfen.
Das muss jemand fixen, der VTi hat.

**Comment by LevelOne2k** [comment]
Hmm. Und was müssten die da fixen? Das ich einen Anhaltspunkt habe und das weitergebe.

**Comment by jbleyel** [comment]
Wenn der VLC geht, dann liegt es vermutlich am Player auf der Zero und nicht an der Ultimo.

**Comment by LevelOne2k** [comment]
Hast du vielleicht einen Tipp den ich da direkt anschrieben kann? Weil auf mein Thema hat da bisher keiner reagiert außer normale User.

**Comment by jbleyel** [comment]
Nein, leider nicht.

**Comment by LevelOne2k** [comment]
Das glaube ich dir, werde mal sehen ob ich da jemanden erreicht bekomme von den VTI Jungs.  Sollte es mit openATV funktionieren?

**Comment by jbleyel** [comment]
Klar geht das mit ATV und wenn nicht, dann kann man das schnell fixen.

**Comment by LevelOne2k** [comment]
@jbleyel ,

es funktioniert auch mit openATV nicht. Hier verhält es sich genau so wie beim VTi. Der Stream läuft kurz an, also nicht das Bild auf der Zero 4K, sondern das REC-Symbol auf der Ultimo 4K fängt an zu blinken und hört dann wieder auf zu blinken.

`#SERVICE 1:0:19:10B:6:85:FFFF0000:0:0:0:http%3A//benutzer%3Apasswort@dyn.dns.org%3A8001/1%3A0%3A19%3A10B%3A6%3A85%3AFFFF0000%3A0%3A0%3A0:Sky Sport Bundesliga 2 HD`

Mit VLC geht es:
`http://benutzer:passwort@dyn.dns.org:8001/1%3A0%3A19%3A69%3AC%3A85%3AFFFF0000%3A0%3A0%3A0`

**Comment by jbleyel** [comment]
Was ist auf der Zero 4K drauf?

**Comment by LevelOne2k** [comment]
Das aktuelle openATV "openatv-6.4-vuzero4k-20210722"

**Comment by jbleyel** [comment]
Ich kann das leider nicht nachstellen.
VLC fragt nach Passwort und der Stream geht.
Meine andere Box kann den Stream auch abspielen.
Bei mir sind aber beide Boxen im gleichen Netzwerk.
Sorry

Zudem hat das ganze nix mit dem Openwebif zu tun.
Der Stream Link http://<IP>:8001/...  läuft komplett ohne openwebif .. zumindest bei mir.

**Comment by jbleyel** [comment]
Bei OpenATV wird Streaming Authentication über das Setting `config.streaming.authentication` aktiviert.
Das Setting im Openwebif heist `config.OpenWebif.auth_for_streaming` und hat nix damit zu tun.

JA: das ist verwirrend und auch nicht so toll.
Irgendwann werde ich das mal ändern.

**Comment by LevelOne2k** [comment]
Ich werde auf der Ultimo 4K jetzt auch mal das openATV installieren und mal gucken wie es sich dann verhält. Bisher habe ich openATV ja nur auf die Zero 4K installiert und diese holt sich den Stream von der Ultimo 4K wo noch VTi drauf ist.

**Comment by jbleyel** [comment]
Menu -> Einstellungen -> Bedienung & Oberfläche -> Extras.

<img width="427" alt="Bildschirmfoto 2021-07-23 um 20 54 38" src="https://user-images.githubusercontent.com/964927/126828506-375f588b-78f1-416f-a4e0-edd67e312956.png">

**Comment by LevelOne2k** [comment]
Da war es natürlich aus. Habe es gerade eingeschaltet, aber selbes Verhalten. REC-Symbol kommt kurz und dann Ende.

Hatte die Authentifizierung bis vorhin nur hier auf JA
![1_0_19_8B_2_85_C00000_0_0_0](https://user-images.githubusercontent.com/25386824/126829180-46fcd0f5-ceb4-456a-94b3-9e4829dc5cb5.jpg)

Ich schmeisse jetzt auf die Ultimo 4K auch mal das openATV drauf.

**Comment by jbleyel** [comment]
Ich denke das Problem ist auf deiner Ultimo und nicht auf der Zero.

**Comment by LevelOne2k** [comment]
ATV wird grad auf der Ultimo installiert.

**Comment by jbleyel** [comment]
Ich kenne den Code von VTi nicht weil der Teil closed source ist.

**Comment by LevelOne2k** [comment]
Bin gespannt ob es mit ATV jetzt gleich funktioniert. Es ist ja auch schon komisch, dass obwohl die Authentifizierung im VTi aktiviert ist, ich über VLC auch ohne Benutzerdaten streamen kann.

Habe das ja hier schon angesprochen:
https://www.vuplus-support.org/wbb4/index.php?thread/144335-an-die-vti-jungs-wo-kann-man-diesen-bug-melden/

**Comment by jbleyel** [comment]
Das darf nicht sein.

**Comment by LevelOne2k** [comment]
Ganz genau. Wenn ich den Stream über das Bouquet einfüge mit Benutzerdaten, dann geht es nicht. Nehme ich die Benutzerdaten aus dem Bouquet raus, dann geht es. Dabei ist es egal ob die Authentifizierung im VTi aktiviert ist oder nicht.

**Comment by LevelOne2k** [comment]
Hmm, wenn ich jetzt in VLC
`http://192.168.178.29:8001/1%3A0%3A19%3A69%3AC%3A85%3AFFFF0000%3A0%3A0%3A0` eingebe dann fragt VLC nach Benutzerdaten, das war ja bei VTi auch schon nicht. Wenn ich die Benutzerdaten eingebe, kommt allerdings auch kein Bild. An der Ultimo blinkt auch kein REC-Symbol oder so. Weiß nicht ob ich das bei ATV einstellen muss das da dann was blinkt.

**Comment by jbleyel** [comment]
Der Stream muss schon laufen, da kann jetzt nur noch ein Problem mit dem Passwort sein.

Das mit dem Rec Symbol kann sein, das das nicht geht.
Kann man aber sicher einbauen, wenn das unbedingt sein muss.

**Comment by LevelOne2k** [comment]
Benutzername habe ich root genommen und dann das dazugehörige Passwort. Ins webif und ftp geht damit auch.

**Comment by jbleyel** [comment]
Sind da Sonderzeichen drin?
Wenn ja, welches?

**Comment by LevelOne2k** [comment]
Keine Sonderzeichen. Nur Buchstaben und zahlen.

**Comment by jbleyel** [comment]
Dann versteht ich's nicht.

**Comment by jbleyel** [comment]
Das Rec Symbol Blinkt bei mir nicht, das ist wohl nur bei VTi.

**Comment by LevelOne2k** [comment]
Ok. Ich habe dir mal eine Nachricht ans Postfach gesendet.

**Comment by LevelOne2k** [comment]
Mit openATV funktioniert es. Mit VTi nicht. Danke.
