### ISSUE TITLE
GitHub Issues cleanup suggestion

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1393]
I was gonna go through old issues here to see what's still relevant. Wonder if @'ing the original submitters to see if each issue still applies would be a good step, or perhaps just closing issues from x amount of time ago? I can see there's stuff still _open_ from 9 years ago 😬

**Comment by jbleyel** [comment]
Some old issues are open because there is no solution available yet but maybe later
Some of them are not so easy to fix.

I do normally close all old issue if "won't fix".

**Comment by jbleyel** [comment]
Some issues can be closed if the modern UI is working 100% on a mobile device.

**Comment by jbleyel** [comment]
I will remove some issues here.
