### ISSUE TITLE
Manual Download instruction not working

### ISSUE THREAD

**Issue by darzu84** [E2OpenPlugins/e2openplugin-OpenWebif#1400]
**Describe the bug**
Inside the Readme there is a section how can the package manually installed, but in section of downloading through wget the ipk package where the file location/name is not correct

# fetch OpenWebif ipk
wget -O openwebif.ipk https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/gh-pages/enigma2-plugin-extensions-openwebif_1.4.8-git20210718-r4_all.ipk

**To Reproduce**
1. Go to 'Readme.md'
2. Click on 'Instalation Section'
3. Scroll down to '# fetch OpenWebif ipk'

**Expected behavior**
It should download the latest stable version of .ipk

**Screenshots**
![openwebif_error](https://user-images.githubusercontent.com/24730085/133896860-2624aaa7-81fe-4b5e-a976-07d35dd20aed.png)

**Image (please complete the following information):**
 - OS: [OpenATV]
 - Version [ 6.0]

**Desktop (please complete the following information):**
 - Browser [firefox]
 - Version [92.0]

**Additional context**
I checked in the gh-pages branch and i can't find the specified filename specified in the Readme.md

**Comment by e2world** [comment]
Use .. wget -O openwebif.ipk https://github.com/E2OpenPlugins/e2openplugin-OpenWebif

**Comment by darzu84** [comment]
thanks it worked to download the file but i was not able to install using
`opkg install openwebif.ipk`

i receive an error

`* open_outer: Failed to open package 'openwebif.ipk': Unrecognized archive format
 * pkg_extract_control_file_to_stream: Failed to extract control.tar.gz from package 'openwebif.ipk'.
 * pkg_init_from_file: Failed to extract control file from openwebif.ipk.`

**Comment by e2world** [comment]
Yes, please ignore was my mistake. Has already been deleted.
