### ISSUE TITLE
Streaming stops working on James Donkey HD Duo

### ISSUE THREAD

**Issue by JoseGlz888** [E2OpenPlugins/e2openplugin-OpenWebif#1401]
Streaming stops working after randomly changing channels.
Using latest version of OpenATV and the same with OpenSPA.

**Comment by atvcaptain** [comment]
for me issue with hardware drivers, send bug report to the Hardware Company

**Comment by jbleyel** [comment]
This is not an OWF issue.

**Comment by wedebe** [comment]
I think this is something that should be addressed in OpenATV (similar to `recordings can abort`...) as an option to disallow channel change while streaming.

https://github.com/openatv/enigma2/issues

**Comment by jbleyel** [comment]
Nope. OpenSPA same issue !!
