### ISSUE TITLE
Lastseen always 0

### ISSUE THREAD

**Issue by christianfees** [E2OpenPlugins/e2openplugin-OpenWebif#1402]
Using OpenWebIf 1.4.8 on VTI 15 returns always 0 for all movies although they have progess http://192.168.0.1/api/movielist?dirname=%2Fmedia%2Fhdd%2Fmovie%2F
Using OpenWebIf 1.3.0 works fine.

**Comment by jbleyel** [comment]
VTi do not have MovieList.moviePlayState or you have a wrong cuts file.
This is a VTi issue.

**Comment by christianfees** [comment]
Thanks.
