### ISSUE TITLE
Autotimer is empty

### ISSUE THREAD

**Issue by githuzzel** [E2OpenPlugins/e2openplugin-OpenWebif#1408]
After update to enigma2-plugin-extensions-openwebif_1.4.9-git20211001-r5_vti
the Autotimer List is complete empty.
![grafik](https://user-images.githubusercontent.com/91947761/135997630-fd225f5c-8a30-4674-84ca-982f7f2ec7b7.png)

**Comment by jbleyel** [comment]
@rdamas , could you please check this.

**Comment by rdamas** [comment]
I can confirm this.

**Comment by jbleyel** [comment]
No issue on my box. Looks like a VTi issue.

**Comment by rdamas** [comment]
Probably, yes; maybe another incompatibility with the Autotimer version used in VTi. 

I'd debug it, if I had an idea where and how the Autotimer list is constructed after the last updates. It used to work...

**Comment by wedebe** [comment]
@rdamas , do you have an exception log or error message that was triggered?
