### ISSUE TITLE
Unescaped js string

### ISSUE THREAD

**Issue by privatissimo** [E2OpenPlugins/e2openplugin-OpenWebif#1414]
Hi, there is an issue in OpenWebif with the link to stream the current service (tooltip "Stream:<program name>") located in the top right on the OpenWebif page ("osd" div).
When a recording is played and the filename (i.e. the name of the recorded program/transmission) contains one or more single quotes (that is an apostrophe, so is relatively common in some language) the browser (chrome in my test) console show the error "Uncaught SyntaxError: missing ) after argument list".

The problem is that internally the onclick event call the jumper80(<path>) javascript function (remember, when playing a recorded program) with the filename as argument and the filename is not properly escaped, so if it contains a single quote (and potentially other characters?).......it breaks.

For the record I'm using OWIF 1.4.8 with VU+ Suo4K SE with OpenPli 8.1-release build 2021-09-15, last update 2021-10-12, but I think the problem exists in any decoder using OpenWebif.

**Comment by jbleyel** [comment]
Do you use classic or modern interface?
Please provide the full filename including the full path if the path has extra signs.

**Comment by privatissimo** [comment]
Just tested with modern interface, it still fail but differently, using modern the new page/tab opened by the link point to:
http://WebIfAddress/web/ts.m3u?file=/media/hdd/movie/20211013%202110%20-%20LA7%20HD%20-%20Non%20e

So, the url is truncated at the first single quote.

**Comment by WanWizard** [comment]
Imho you can't make any assumption on what is and what is not in a filename.

In the case of a recording, you can have something like:
````
-rwxrwxrwx    1 openpli  users          732 Oct 13 23:44 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY.eit
-rwxrwxrwx    1 openpli  users    210223104 Oct 13 23:51 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY.ts
-rwxrwxrwx    1 openpli  users          269 Oct 13 23:52 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY.ts.meta
-rwxrwxrwx    1 openpli  users       147984 Oct 13 23:51 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY.ts.sc
-rwxrwxrwx    1 openpli  users    3099443764 Oct 14 01:00 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY_001.ts
-rwxrwxrwx    1 openpli  users        69232 Oct 14 01:00 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY_001.ts.ap
-rwxrwxrwx    1 openpli  users           12 Oct 14 01:00 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY_001.ts.cuts
-rwxrwxrwx    1 openpli  users          271 Oct 14 22:30 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY_001.ts.meta
-rwxrwxrwx    1 openpli  users      1645808 Oct 14 00:59 20211013_2345_-_BBC_FOUR_HD_-_ORBIT__EARTH'S_EXTRAORDINARY_JOURNEY_001.ts.sc
````
but it could also be something that is downloaded. The name should  be properly URL encoded, and that includes all special chareacters, not only spaces. So the name needs to be urllib quoted...

**Comment by jbleyel** [comment]
Yes, i can.
Please check this.
https://github.com/OpenPLi/enigma2/blob/bd5113bd4e0c4a6c73d8c3841d8efed717e2eb6a/lib/python/Tools/Directories.py#L329

The `'` should be also add to the non_allowed_characters.

**Comment by WanWizard** [comment]
Imho there is a difference between "characters not allowed in a filename" (which is dicated by the filesystem), and "characters not allowed in a URI", which is dictacted by the relevant RFC's. And you shouldn't mix the two.

If the URL in the m3u is properly quoted, the characters used in the filename are no longer relevant.

Don't fix an issue on the left by tweaking code on the right (and it also doesn't solve the issue with downloaded files).

**Comment by privatissimo** [comment]
Yes, the filename encoding is utf8, but since all characters are low ascii (<127) I think it makes little difference.

I find it strange that in your box the filename is escaped, in your box is it escaped by the backend service (info.py) or by the js in the browser (openwebif.js)? How does the json from /api/statusifo looks like? (see my second post here)

Looking at both (info.py and openwebif.js) in the master branch here in github, I cannot find where the filename is escaped, are you running OpenWebif code from the master branch?

**Comment by jbleyel** [comment]
Yes .. i'm using the latest version from the master here.
But i'm running ATV 7.0 and this is python3.

**Comment by jbleyel** [comment]
Please provide all files as zip from the recording except the big .TS file.

**Comment by privatissimo** [comment]
The stream (download) "button" is fixed and works, the title (tooltip) is still unescaped so it's not displayed correctly (it is truncated) but....that's a minor issue
