### ISSUE TITLE
EPG / ZAP and streaming links doesn't work if channel name contain simple quote...

### ISSUE THREAD

**Issue by Creteil** [E2OpenPlugins/e2openplugin-OpenWebif#1416]
Clicking on EPG and stream (normal or transcoded) links doesn't work when channel name contain simple quote. 

Try to click on EPG or stream links for a channel name containing simple quote.

Links must work.

![Capture du 30-10-2021 à 11-19-46](https://user-images.githubusercontent.com/27310214/139527420-70635b9e-fa13-4d2d-8e8b-b10028034230.png)

 - OS : OpenATV
 - Version : 6.4

 - Browser : Firefox, Chrome, etc.
 - Version : 93.0

Can you please deal properly with names of channels that contain simple quote ?

**Comment by wedebe** [comment]
Hi @Creteil, could you try this in the modern interface and let me know if there are similar issues, please?

**Comment by Creteil** [comment]
Hi @wedebe, it can look funny, but how I switch to « modern interface » ?

**Comment by wedebe** [comment]
On the left menu near the bottom, there should be a `Settings' link, once there, tick the `Use modern interface` tickbox.

To return to classic, click the cog on the top-right, then `Use classic interface` in the vertical menu that appears.

**Comment by Creteil** [comment]
Ok, found it and it work properly in the « modern interface »...

**Comment by wedebe** [comment]
Great, thanks 🙂

**Comment by jbleyel** [comment]
Hi @wedebe, can you please check and fix this for classic UI?

**Comment by wedebe** [comment]
> Hi @wedebe, can you please check and fix this for classic UI?

My focus is on the modern UI only; I can't justify spending my time on the classic UI 😉

**Comment by jbleyel** [comment]
It's also not working on modern UI.

this line do not work.

`#set $channelName = $channel.name.replace("'", r"\'")
`

**Comment by jbleyel** [comment]
Modern:

`<a href="javascript:zapChannel('1:0:19:2076:432:1:C00000:0:0:0:', 'L'EQUIPE');" class="link--skinned" title="Zap to L'EQUIPE">L'EQUIPE</a>`


Classic:
`
<a href="#" onclick="zapChannel('1:0:19:2076:432:1:C00000:0:0:0:', 'L'EQUIPE'); return false" title="Zap to L'EQUIPE">L'EQUIPE</a>`

**Comment by jbleyel** [comment]
Click on the channel name not working in modern and classic.

**Comment by jbleyel** [comment]
Classic UI should be fixed.
Zap on modern UI needs to be fixed.

**Comment by jbleyel** [comment]
All these buttons are not working.
<img width="157" alt="Bildschirmfoto 2021-11-04 um 12 48 33" src="https://user-images.githubusercontent.com/964927/140308502-b5f3dc8c-5eb7-4df4-9478-04732c0024c7.png">

<img width="866" alt="Bildschirmfoto 2021-11-04 um 12 49 06" src="https://user-images.githubusercontent.com/964927/140308583-25845274-88b1-4e42-af98-f71730fef938.png">

**Comment by wedebe** [comment]
I intend to rework the `zap` and `stream` triggers completely in the modern UI. I haven't looked, but I can't imagine the channel name is useful anymore in the zap command? And for streaming, the channel name is included in the .m3u playlist file. EPG is more complicated 'cos the dialog relies on a bunch of data.

**Comment by Creteil** [comment]
> I haven't looked, but I can't imagine the channel name is useful anymore in the zap command?

I agree, keep it simple...

**Comment by wedebe** [comment]
I wonder whether encodedSref and encodedChannelName values should be returned by the services endpoint 🤔

**Comment by jbleyel** [comment]
> I wonder whether encodedSref and encodedChannelName values should be returned by the services endpoint 🤔

No, please not. This has a huge performance impact on large lists.

**Comment by wedebe** [comment]
> > I wonder whether encodedSref and encodedChannelName values should be returned by the services endpoint 🤔
> 
> No, please not. This has a huge performance impact on large lists.

In which case, we should really consider caching.

**Comment by jbleyel** [comment]
We can implement cache but there is no trigger to invalidate the cache.
So, when do you wanna clean the cache?
Trust me, I have this problem in my app too.

Anyway, we have only a problem with a channel name and sref, this issue can be fixed by using json requests and javascript rendering.
This is state of the art and faster as the current template rendering.

**Comment by wedebe** [comment]
Agreed a quick fix is best for this, but it's a good time to initiate the conversation about what improvements can be made in the future 🙂
