### ISSUE TITLE
Translation using Weblate

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1418]
**Is your feature request related to a problem? Please describe.**
I'd like to see more translation of OpenWebif

**Describe the solution you'd like**
OpenATV recently implemented [Weblate](https://hosted.weblate.org/engage/openatv/), it'd be interesting to implement here, too.

**Additional context**
Any thoughts?

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/Weblate

**Comment by jbleyel** [comment]
https://hosted.weblate.org/projects/e2openplugin-openwebif/e2openplugin-openwebif/

**Comment by jbleyel** [comment]
I have removed the extra branch for Weblate.
By the way, do you need the other extra branches?

**Comment by jbleyel** [comment]
Weblate removed because of not approved for free hosting.

**Comment by jbleyel** [comment]
DONE
