### ISSUE TITLE
Incorrect endtime beign sent to epgcache.lookupEvent()

### ISSUE THREAD

**Issue by original-birdman** [E2OpenPlugins/e2openplugin-OpenWebif#1419]
`epgcache.lookupEvent()` can be given a `begintime` and `endtime` to limit the range of EPG hits to retuirn.

The `endtime` is actually the *extent* of time after `begintime` to look for - in **minutes**.  The comment in the C++ code now states this (it used to say something different, and wrong).

However, various calls in `plugin/controllers/models/services.py` still appear to think that `endtime` is something other than what it actually is. In particular, `endtime` is given a default setting of -1, which really is taken as a negative time interval.

Not sure of the specific knock-on effects of this, but whenever the code is used it will not be behaving as expected.

**Comment by jbleyel** [comment]
lookupEvent with endTime = -1 means ignore endTime and get all EPG entries without filter.

Why do you think this is wrong?

**Comment by original-birdman** [comment]
Because that's not how I read the code in `epgcache.cpp`.

`endtime` is the 4th element (index 3) of the tuple, and the code is:
```
                                        case 3:
                                                minutes=PyInt_AsLong(entry);
                                                break;
```
`minutes` then gets used as
```
                                if (!startTimeQuery(ref, stime, minutes))
```
and I can't see anything in `startTimeQuery` that treats any value as special. I just see it being used as an offset from `begin`.

**Comment by jbleyel** [comment]
Please call 

/api/epgservice?sRef=XXX

You will see it's working.

**Comment by jbleyel** [comment]
You may have overseen this:

```
if(minutes) {
...
}
```

**Comment by jbleyel** [comment]
By the way .. the epgcache code is full of crap and very fragil.

**Comment by original-birdman** [comment]
> You may have overseen this:
> 
> ```
> if(minutes) {
> ...
> }
> ```

No, I saw that.  Anything other than 0 is True.  So -1 should drop into that block.

**Comment by original-birdman** [comment]
> By the way .. the epgcache code is full of crap and very fragil.

That is true. It seems to take very roundabout ways to achieve one end.

**Comment by original-birdman** [comment]
OK. I will admit that sending -1 as the `endTime` gets everything.
But I have no idea how.
