### ISSUE TITLE
Tele-/Videotext

### ISSUE THREAD

**Issue by PaulchenPantherI** [E2OpenPlugins/e2openplugin-OpenWebif#1420]
When the Tele-/Videotext is open, the OpenWebif-Remote dosn't work anymore.

**Comment by wedebe** [comment]
Hi @PaulchenPantherI, does this happen in classic/modern/both interfaces? Do any buttons work at all/have any effect (eg. numbers or red/green/yellow/blue)

**Comment by PaulchenPantherI** [comment]
Hi,
I try it in the classic interface. No buttons work. The collor buttons also.

**Comment by ims21** [comment]
It is feature. Teletext is standallone cpp modul in e2.

**Comment by wedebe** [comment]
I wonder if there's any way to determine that teletext is active? If so, we could show a dialog to say that buttons won't work

**Comment by jbleyel** [comment]
You can use OpenATV if you want this.

**Comment by wedebe** [comment]
Can TeleText be activated by OpenWebif's remote control buttons function? If so, the button should be changed to something else.

**Comment by betacentauri** [comment]
Which image is affected?
In the past the teletext "module" handled all key presses on it's own. In E2 the handling was disabled when teletext was started.

I have changed that several years ago. Key presses are now handled from e2 and are forwarded to the teletext module.
You can now change the teletext buttons in the keymap and you can e.g. change the volume while teletext is running.

I would guess (not tested yet), that you should be able control the box via web if if teletext is running. At least in some images like OpenPLi, OpenATV, ...

**Comment by PaulchenPantherI** [comment]
For me it's the VTI image.

Yes. The box can still be controlled via WebIf.

For example, you can switch the program.

The teletext remains and changes to the corresponding board of the new program.

But the information from the previous program remains in the front display.

In the OEM image of my Dreamboxes 8000, the teletext works fine via web remote.

**Comment by jbleyel** [comment]
This needs to fix in VTi.

**Comment by PaulchenPantherI** [comment]
Ok.
