### ISSUE TITLE
python-cheetah debian package

### ISSUE THREAD

**Issue by Seagen6** [E2OpenPlugins/e2openplugin-OpenWebif#1425]
Hi there is and has been an incompatible issue with DreamOS images since there is no python-cheetah module for those images.
DreamProperty will not provide that package into their git build enviroment so as long as you don't the .deb package version is not working. I suggest you remove it from the build or add an build option where the python-cheetah module is built into OW :)

Regards Seagen

**Comment by jbleyel** [comment]
I can remove the deb build on Github.
But I will never implement cheetah into OWF, because this is nonsense.
Maybe in a very very next version we do no longer need cheetah.
Probably in 2023 or later.

**Comment by Seagen6** [comment]
I agree better to remove the deb build then build cheetah into OWF and rather leave as it is.
Nice work and an amazing plugin

**Comment by jbleyel** [comment]
It's very easy to build a cheetah deb package.
You can also install cheetah manually.

**Comment by jbleyel** [comment]
Please note!
OWF do not support DreamOS by default.
You may need to do some changes.

**Comment by wedebe** [comment]
> I can remove the deb build on Github. But I will never implement cheetah into OWF, because this is nonsense. Maybe in a very very next version we do no longer need cheetah. Probably in 2023 or later.

What do you think would be a likely candidate to replace Cheetah, @jbleyel?

**Comment by jbleyel** [comment]
> What do you think would be a likely candidate to replace Cheetah, @jbleyel?

There is no candidate.
You need to refactor all templates to json and then create static html files with client side json request.
This is a lot of work.
I wont do that and you too.

**Comment by jbleyel** [comment]
We have many other open issues.
DreamOS is out of focus.
