### ISSUE TITLE
Kein EPG

### ISSUE THREAD

**Issue by SattSeher** [E2OpenPlugins/e2openplugin-OpenWebif#1427]
Habe eben die neueste Version für das VTI auf meine Duo 4k installiert.
Jetzt wird das EPG nicht geladen - es bleibt die "Eieruhr"
Scheint also zumindest bei uns noch nicht zu funktionieren.

I just installed the latest version for the VTI on my Duo 4k.
Now the EPG is not loaded - the "egg timer" remains
So at least it doesn't seem to work for us yet.

**Comment by jbleyel** [comment]
You need to update the templates.

**Comment by jbleyel** [comment]
Please provide the full error details of this link.

http://XXX/ajax/multiepg?epgmode=tv

XXX is the IP

**Comment by rdamas** [comment]
![traceback](https://user-images.githubusercontent.com/15088943/145246455-7a45c9df-2e09-42ac-a847-6dcb569d8374.jpg)

**Comment by jbleyel** [comment]
sollte gefixt sein.

**Comment by rdamas** [comment]
Ist gefixt. Danke 👍

**Comment by jbleyel** [comment]
HI @SattSeher , @rdamas was ist bei VTi los?

**Comment by rdamas** [comment]
Ja, das haben wir auch gemerkt - mal schauen wie lange es dauert, bis es jemand merkt, der Root-Zugriff auf den Webserver oder die VM hat. Würde mich inzwischen nicht mehr wundern, wenn es länger dauert. Keine Ahnung, ob es da seitens Admins eine Meldekette gibt. Seit dem Abgang von plnick geht das alles langsam aber sicher den Bach runter...

**Comment by jbleyel** [comment]
Ich hätte da eine Lösung, aber die will von den Admins keiner hören.

**Comment by rdamas** [comment]
Leider :-)
