### ISSUE TITLE
Small menu - layout

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#1428]
Why is there this layout ? Which box has EXIT diagonally to OK ? 

In 99% is EXIT on the right of OK or is EXIT under OK.  This layout is very strange.

**Comment by wedebe** [comment]
Feel free to use full remote available in settings to match your box!

Relative to the `OK` button... 

Samsung, LG, OneFor All remotes have `back`/`return` bottom-left and `exit` bottom-right.

Panasonic `exit` top-right, `back`/`return bottom-right. 

Sony have `exit` bottom-left. 

Mut@nt `exit` bottom-left, `epg` bottom-right.

There's no consistency as to where manufacturers place remote buttons, but `back` or `return` would seem to be sensible on the left, right-side has a _go forwards_ connotation.


I'm keen to investigate examples of other brand's button placements though!

**Comment by jbleyel** [comment]
You can switch to the old small remote if you want.

**Comment by jbleyel** [comment]
<img width="420" alt="Bildschirmfoto 2021-12-09 um 23 15 26" src="https://user-images.githubusercontent.com/964927/145484338-b39112af-7853-4b98-a0d2-fe702be28705.png">

**Comment by ims21** [comment]
> Feel free to use full remote available in settings to match your box!
> 
> Relative to the `OK` button...
> 
> Samsung, LG, OneFor All remotes have `back`/`return` bottom-left and `exit` bottom-right.
> 
> Panasonic `exit` top-right, `back`/`return bottom-right.
> 
> Sony have `exit` bottom-left.
> 
> Mut@nt `exit` bottom-left, `epg` bottom-right.
> 
> There's no consistency as to where manufacturers place remote buttons, and it'll never be possible to satisfy **all** user-preferred configurations; but `back` or `return` would seem to be sensible on the left, right-side has a _go forwards_ or -_finish_ connotation.
> 
> I'm keen to investigate examples of other brand's button placements though!

I do not know, If you see, that this is not for controll TV, but for boxes ... And - if there was more than 10 year used OK ... EXIT. I will rebuild it later...
