### ISSUE TITLE
New Certificate every restart

### ISSUE THREAD

**Issue by romestylez** [E2OpenPlugins/e2openplugin-OpenWebif#1430]
Hi guys,

since im using openATV 6.4 there is a problem with the HTTPS Certificate on my vu+ duo² (vu+ zero running fine). Everytime i restart the receiver the files "key.pem" and "cert.pem" are newly created.

I dont understand why this happens. If i check the certificate "Valid from" is the date/time the box started. When i do this

`init 4 && init 3`

or

`wget -O - -q http://127.0.0.1/web/powerstate?newstate=3 | grep "\(<\|</\)e2instandby" | tr -d '\n' | sed "s/.*<e2instandby>\(.*\)<\/e2instandby.*/\\1\n/""`

The certificate also gets newly created so it must be something in enigma2 or the OpenWebIF ? I cant find the error but its annoying even if i create my own certificate it gets overwritten after a restart.

**Comment by romestylez** [comment]
Ive checked it a little bit deeper. When i restart enigma2 or just the whole receiver on my vu+ duo² the "cert.pem" and "key.pem" getting deleted. Im connect with WinSCP and see that both files are gone after the restart. Then like ~30-60 seconds later they are back with a new creation date.

So i guess OpenWebIF is doing everything fine. But it seems like enigma2 is deleting the files so OpenWebIF recreates them. Cant understand why that problem just exists on my vu+ duo² and the vu+ zero is running fine.

**Comment by nickersk** [comment]
please try to remark or remove lines 32-35 in /usr/bin/enigma2.sh and reboot, if issue will reappear. thx

**Comment by romestylez** [comment]
At the receiver with the problem i have this in my settings file

`config.misc.firstrun=False`

on the other receiver where its working it looks like

`config.misc.firstrun=false`

When i change it to a small "f" and do 

`init 3 && init 5`

the certificate isnt getting deleted ! So it seems like the check in /usr/bin/enigma2.sh is case sensitive. Also a reboot is working. When i change the "false" to "False" and restart it seems like Enigma is changing it back to "false" i cant understand why :D

So lets see what helped and may need to be done. As mm not a coding guy this maybe is wrong but from your tip/idea i guess line 32-35 in /usr/bin/enigma2.sh should be changed to

`# workaround for corrupt ssl files
if [ ! "$(grep -i config.misc.firstrun /etc/enigma2/settings)" == "config.misc.firstrun=false" ]; then
	rm -rf /etc/enigma2/cert.pem &
	rm -rf /etc/enigma2/key.pem &
fi`

Thank you so much for your help man !

**Comment by nickersk** [comment]
ok, we will change the grep. thank you.

**Comment by Papi2000-new** [comment]
So in his case infos from oATV7.0 might being used in older oATV version?

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/235266300b60318039995acf92dcdcc0cb83c3d7
