### ISSUE TITLE
Buttons on new 'small remote'

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#1439]
There is problem, when is used multiple pressing on button and mouse moves slightly - then is selected text (or is activate some function in browser) instead run button code... very annoying, when user must type something with virtual keyboard...

There should be all this buttons without doubleclick, move etc ... only for L-mouse click only, imho... 

![obrazek](https://user-images.githubusercontent.com/1208763/147870093-458ca6ff-1d16-4d05-98ff-226a029e4925.png)

**Comment by wedebe** [comment]
For dev: see css for remote buttons in `modern` interface to rectify this issue.

**Comment by ims21** [comment]
'Testing version' for ims style, where are keys as buttons was merged
