### ISSUE TITLE
openwebif_1.5.0-git20220301-r2_vti.ipk

### ISSUE THREAD

**Issue by SattSeher** [E2OpenPlugins/e2openplugin-OpenWebif#1454]
![grafik](https://user-images.githubusercontent.com/82285274/156231438-df3fef97-94ea-4cf8-8c8d-777bef523def.png)

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/19ec719a2d005789a731c895db733727fd18378a
