### ISSUE TITLE
Timer not visible in EPG

### ISSUE THREAD

**Issue by WanWizard** [E2OpenPlugins/e2openplugin-OpenWebif#1455]
for some channels, but not for all. I can't pinpoint the cause, I first thought it was because I have a DESCRIPTION in the userbouquet file, both as a keyword and at the end of the service ref, but removing it doesn't make a difference.

Example:
![image](https://user-images.githubusercontent.com/456954/156415746-a0e4f92d-2f97-4167-af27-c2126b221b3d.png)

![image](https://user-images.githubusercontent.com/456954/156415992-ec47de87-5a5c-4191-849a-004fafa28082.png)

I've double checked, channel number 1196 is the same as the one shown in the EPG.

The problem is present is both the classic and the modern interface, so it is a data issue.

Willing to debug if required.

It is not marked as a recording in the channel EPG either:

![image](https://user-images.githubusercontent.com/456954/156416451-a00df880-98f1-4bd6-bef2-a77b2a0602dc.png)

It is marked as a recording on the box itself:

![image](https://user-images.githubusercontent.com/456954/156416874-c2eeef20-70bc-48a7-abd9-bd839d7d5f8e.png)

**Comment by jbleyel** [comment]
You mean the timer was not shown in multi epg?

**Comment by WanWizard** [comment]
The timer indicator, yes.

I have no TV connected to my recording box, so have to do everything using the webif. A bit annoying if you can't see the timers in the EPG, I now have to check the timers themselfs to make sure I haven't planned any duplicates... :grimacing:

**Comment by WanWizard** [comment]
To be clear, this indicator:

![image](https://user-images.githubusercontent.com/456954/156419203-f3eeb774-f0d1-4722-8894-faf637e8113b.png)

**Comment by jbleyel** [comment]
The timer indicator is based on the sref and begin/end time.
Do you use alternative channel groups?

**Comment by jbleyel** [comment]
This is the important part for the channel epg list.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/views/ajax/epgpop.tmpl#L144

You can check the website source and search for.

var t = [...]

This should include your timers.

**Comment by WanWizard** [comment]
> The timer indicator is based on the sref and begin/end time. Do you use alternative channel groups?

Nope, nothing fancy.

Timer:
````
<timer begin="1646423700" end="1646428200" serviceref="1:0:19:1E46:809:2:11A0000:0:0:0:" repeated="0" name="New: Susan Calman&apos;s Grand Day Out" description="" afterevent="auto" eit="11" location="/media/nas/Misc/" justplay="0" always_
zap="0" pipzap="0" zap_wakeup="always" rename_repeat="1" conflict_detection="1" descramble="1" record_ecm="0" flags="Susan autotimer Calman&amp;apos;s Grand Day Out">
</timer>
````

Bouquet entry:
````
#SERVICE 1:0:19:1E46:809:2:11A0000:0:0:0::Channel 5 HD
````

**Comment by WanWizard** [comment]
> You can check the website source and search for.

Have to find a moment the box isn't recording,

**Comment by jbleyel** [comment]
I think I have found the issue.
The bouquet entry should be.

`#SERVICE 1:0:19:1E46:809:2:11A0000:0:0:0:`

But I will try to fix this.

**Comment by jbleyel** [comment]
Update.. 
I have also such entry in my bouquet and the timer indicator for this channel works.
But your timer should look like this.

```
<timer begin="1646423700" end="1646428200" serviceref="1:0:19:1E46:809:2:11A0000:0:0:0::Channel 5 HD" repeated="0" name="New: Susan Calman&apos;s Grand Day Out" description="" afterevent="auto" eit="11" location="/media/nas/Misc/" justplay="0" always_
zap="0" pipzap="0" zap_wakeup="always" rename_repeat="1" conflict_detection="1" descramble="1" record_ecm="0" flags="Susan autotimer Calman&amp;apos;s Grand Day Out">
</timer>
```

**Comment by WanWizard** [comment]
The timer is made by autotimer, so that suggests the bug is actually in autotimer. 

I'll pass that on, thanks!

**Comment by jbleyel** [comment]
Yep .. i have create an autotimer and I have the same issue.

**Comment by jbleyel** [comment]
We should think about to remove the name from the sref in enigma.
The correct bouquet entry should be.

```
#SERVICE 1:0:19:1E46:809:2:11A0000:0:0:0:
#DESCRIPTION Channel 5 HD

```

**Comment by WanWizard** [comment]
Agreed, but DreamboxEdit seems to create
````
#SERVICE 1:0:19:1E46:809:2:11A0000:0:0:0::Channel 5 HD
#DESCRIPTION Channel 5 HD
````

**Comment by jbleyel** [comment]
i will try to fix OWF

**Comment by WanWizard** [comment]
> We should think about to remove the name from the sref in enigma.

You mean when reading the userbouquet files? Yes, that is also an option. But that may be complicated, as the last field in the service ref can also contain other (valid) things, like a URL.

What does OpenWebif do if you create a (auto)timer from a stream entry? My guess is the same problem?

**Comment by WanWizard** [comment]
Works like a treat. Thanks a millon Jörg!

**Comment by WanWizard** [comment]
Sorry to be a pain @jbleyel, but autotimer edit has the same problem:

![image](https://user-images.githubusercontent.com/456954/156941742-e916fd3d-74b9-4b79-a7e4-b721a48ad6d3.png)

Channels field is empty if a channel with a description in the service ref is selected.
