### ISSUE TITLE
Current channel info - picon fixed size

### ISSUE THREAD

**Issue by tinola** [E2OpenPlugins/e2openplugin-OpenWebif#1456]
Hi,

I am skipping the old interface... But in responsive one we have fixed picon size declared as width=100px and height=60px...

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/0336f8a85a4b779f2f4bd8b6a08c73ac70bad8f2/plugin/controllers/views/responsive/ajax/current.tmpl#L23

When we have got different dimensions picons set installed other than 100x60px (eg. 220x132px or even 400x170px), in this view picons should scale properly.

**Comment by wedebe** [comment]
Hi @tinola, could you attach two or three picon images that look particularly squished in the modern ui, please?

**Comment by tinola** [comment]
Sure! Here're two samples:

220x132px picon:

![220x132px](https://user-images.githubusercontent.com/3160125/156664286-a745e0a4-1fb3-4656-ae6f-74311ba55f5a.png)

400x170px picon:

![400x170](https://user-images.githubusercontent.com/3160125/156664294-a53286f1-75b0-4337-b84b-dc2223ec0216.png)

Channel Info view as follows:

![scr](https://user-images.githubusercontent.com/3160125/156664297-7d727af0-10b4-43df-8f57-56deaf11bcfb.png)

**Comment by wedebe** [comment]
Exactly what I need, thanks!
