### ISSUE TITLE
global name "listdir" is not defined

### ISSUE THREAD

**Issue by koivo** [E2OpenPlugins/e2openplugin-OpenWebif#1457]
Hi,

currently all builds breaks the function of openwebif.

global name "listdir" is not defined

BR

**Comment by jbleyel** [comment]
Please provide more info.

**Comment by koivo** [comment]
Sure, what do you need?
openhdf 6.4 build from oe-core 4.4
openhdf 7.0 build from oe-core 5.0
Both images show the error message "Extensions/OpenWebif (global name "listdir" is not defined)"

I have try a fresh build just some minutes ago with the same error.
Builds from 29.01. without error. We are building not an image every day.

**Comment by koivo** [comment]
debug log shows:
/usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-03-11 19:42:13+0100 [-] NameError: global name 'listdir' is not defined

**Comment by jbleyel** [comment]
This is a bug in your Directories.py.

File "/usr/lib/enigma2/python/Tools/Directories.py", line 538, in isPluginInstalled
NameError: global name 'listdir' is not defined
