### ISSUE TITLE
Key mapping error

### ISSUE THREAD

**Issue by TENSytems** [E2OpenPlugins/e2openplugin-OpenWebif#1458]
When using OWIF (VTi) with the preset remote control (the one with the symbols) , one cannot call up the EPG with the EPG button. When using the original remote control (complete remote control) the EPG can be called up with the EPG button.

**Comment by wedebe** [comment]
Hi @TENSytems , could you confirm whether this happens with the `modern`, `classic` or both interfaces?

**Comment by TENSytems** [comment]
I am reporting this issue for another user who doesn't speak english ;) , so I don't have all details.
Yes, this happens with both interfaces and it occurs while using the SmartEPGvu+ Plugin.

**Comment by jbleyel** [comment]
Sorry, but VTI needs to fix this.
Wrong keymaps needs to fix in enigma and not in OWF.
