### ISSUE TITLE
Zgemma H9.2H SE shown as unknown

### ISSUE THREAD

**Issue by stefanopet91** [E2OpenPlugins/e2openplugin-OpenWebif#1459]
I have a Zgemma H9.2H SE that is shown as unknown in openwebif 1.4.9.
Looking at https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/8239b92a7955e9fca6f5cba390b0a042b7176385/plugin/controllers/models/owibranding.py#L498 I see that the model is retrieved from the file _/proc/stb/info/boxtype_ and the file content in my box is H9.2H.SE, thus not matching with the above string comparison.
Is this a bug in openwebif or my _/proc/stb/info/boxtype_ is wrong?

**Screenshots**
![image](https://user-images.githubusercontent.com/13435225/158878698-de21d357-ed58-44e6-99f6-80e5803dfdfd.png)
**Image (please complete the following information):**
 - OS: OpenPLI
 - Version 8.1

**Comment by WanWizard** [comment]
Are you using the OpenWebif version that is included in OpenPLi 8.1, or did you upgrade from source (or build your own image with an updated OpenWebif?)

Zgemma has been fooling around with strings in capitals, which was been changed in later driver versions.

**Comment by stefanopet91** [comment]
It's the OpenWebIF that comes with OpenPLi 8.1.
As far as I understand the issue is not related to capital letters but the strings are different. The code checks for `h9se.2h` while the box has `h9.2h.se`.  This second form seems more reasonable and I would expect that this issue affects everyone with this box.

**Comment by WanWizard** [comment]
The correct one is `h9se.2h`, and as said, afaik this issue has been adressed. You can flash a nightly build to check.

OpenPLi 8.1 will not be updated anymore, 8.2 is due soon, which is based on the current nightly build.

**Comment by stefanopet91** [comment]
I have just installed an openpli-develop (2022-03-18) and the issue is still there

![image](https://user-images.githubusercontent.com/13435225/159124464-e97998bf-f945-428c-95a0-0ec48a919c9a.png)

**Comment by WanWizard** [comment]
hmm, I'll see if I can find the time to have a look.

**Comment by WanWizard** [comment]
![image](https://user-images.githubusercontent.com/456954/159191406-917bfd71-b619-4bd2-b677-31eb534e0520.png)
