### ISSUE TITLE
API endpoint to retrieve default_path

### ISSUE THREAD

**Issue by WanWizard** [E2OpenPlugins/e2openplugin-OpenWebif#1460]
Afaik there is no API endpoint to retrieve the configured default recording path (config.usage.default_path.value).

Any objections if I add this?

**Comment by jbleyel** [comment]
Do you need this for timers or movies?
Or in other words, what’s the use case?

**Comment by WanWizard** [comment]
OpenPLi has a feature called "remote timer", which allows you to create a timer on a remote box. A new timer (local or remote) opens with the default recording path set.

Currently, there are endpoints to retrieve the current path (i.e. the last path selected in the movie list) and a list of all bookmarks, but not the default recording path, with which the timer should open.

Currently our code uses the current path, but that is very dependent on what the last user of the remote box did in the movielist.

**Comment by WanWizard** [comment]
Here an example, I press the green "add timer" button in the EPG, define it should be a remote (fallback) timer, and the location shows the last used movie path on the remote box. So it always needs to be changed, you can't simply press green again to save the timer.

![image](https://user-images.githubusercontent.com/456954/191488214-43af06e7-105b-43f7-afe2-5ad58b884fa1.png)
