### ISSUE TITLE
Dump remotes / Un-default the Dream remote

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#148]
I'm much in favor of dumping all those different remotes.

Reasons:
- It's a lot of work to create the grids for each and every new remote on the market
- Some people do not even use the original remote but universal remotes and I estimate their percentage to be even higher on E2 boxes
- It bloats the OpenWebif git
- Some remotes might be ergonomic if hold in your hand but aren't even closely optimized for use inside the OpenWebif as a picture, especially the roundish Dream/One4All remote

Benefits:
- none?

Especially the last reason in the list above makes me think it's time to dump the concept of using "dmm" as default remote.
The Dreambox original firmwares are nowadays about the only ones that do NOT contain the OWIF, so why would the OWIF default be a Dream remote then?
Especially as the dmm remote is about the worst to be used in OWIF (Most of the space inside its picture is wasted due to the shape of the remote) and lacks most of the keys todays users got common with...

I suggest creating ONE remote with an optimized layout (rectangular shape), labels optimized for web and international use (common pictograms preferred over text), rectangular buttons and so on.
This one should be created from scratch using vector painting programs and probably also stored as vector format for better scalability on larger screens (svg).

**Comment by RobvanderDoes** [comment]
Sehe http://forums.openpli.org/topic/38245-no-recordplay-pausestopffrw-buttons-one-the-webif-remote-control/?view=findpost&p=496940 für additionale Diskussion.

**Comment by jbleyel** [comment]
Will be fixed in 2.0
