### ISSUE TITLE
EPG search returns no hits for renamed services

### ISSUE THREAD

**Issue by kluese** [E2OpenPlugins/e2openplugin-OpenWebif#1481]
**Describe the bug**
When searching on the EPG page. OWIf don't find results from renamed services.
This only happens, with setting "epg search" "limited to favorites" ("limitiert auf Favoriten").

**To Reproduce**
1. Rename a Service
2. Go to page EPG
3. Search for a event, that should produce a result on the renamed service

**Expected behavior**
EPG search should find results on renamed services.

**Screenshot**
![owif-epg-search](https://user-images.githubusercontent.com/65507964/164696576-56307b7b-cceb-41c7-9481-7bf5842c6e7c.PNG)
ZDF is renamed to ZDF SD

**Image (please complete the following information):**
 - OS: VTi 15
 - enigma2-plugin-extensions-openwebif_1.5.0-git20220404-r2_vti.ipk

**Desktop (please complete the following information):**
 - chrome, but I think its browser independent

Regards

**Comment by kluese** [comment]
The attached patch solved the problem for me.
It removes the descriptions from the service references in 
/plugin/controllers/models/services.py
def getSearchEpg()
[e2openplugin-OpenWebif-patch-for1481.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/8540290/e2openplugin-OpenWebif-patch-for1481.zip)

**Comment by wedebe** [comment]
Thanks for that, @kluese .

I think it's time we looked at refactoring how renamed channels are handled in OWIF; there've been a number of related issues fixed individually...

https://www.reddit.com/r/ProgrammerHumor/comments/ud0yar/when_i_fix_the_code_from_the_wrong_place_but_it/
😬
