### ISSUE TITLE
EPG does shows current time with 2hours offset

### ISSUE THREAD

**Issue by kgroot** [E2OpenPlugins/e2openplugin-OpenWebif#1482]
When I show the multi-epg (EPG), a window is opened and there is a blue line on the current time. This line is however 2hours early and disappears after approximately 8 seconds. Only a refresh screen (F5) shows this line again.
![OpenWebif_timeOffset_wrong](https://user-images.githubusercontent.com/3846231/165578388-846f7d8f-6a53-47d9-8e16-049b8c96856c.jpg)

I am using the OpenWebIF (OWIF 1.5.0) with a Dreambox dm920 running OpenATV.
I have tried Firefox on Linux (LMDE5) and Win10 and Microsoft Edge on Win10, but this makes no difference.

I have this problem for a year, so this is not a recent problem. 

Do you have any idea how to solve this?

**Comment by wedebe** [comment]
I can see this is caused by a calculation error on the `.timetable-now` element which I'll investigate further.

`left` is initially set to `151px`, then `2.75182e8px` (275,182,000px)

```
element.style {
    left: 2.75182e8px;
    height: 6120px;
}
```

**Comment by wedebe** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/af253057ec819a7fa57f2eca0d7347127f67b4e7/sourcefiles/modern/js/vti-responsive-multiepg.js#L3

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/af253057ec819a7fa57f2eca0d7347127f67b4e7/plugin/controllers/views/responsive/ajax/multiepg.tmpl#L328

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/af253057ec819a7fa57f2eca0d7347127f67b4e7/plugin/controllers/views/responsive/ajax/multiepg.tmpl#L177

**Comment by wedebe** [comment]
Calling the following using the tmpl $offset value will present the EPG at the current time.

`jQuery('#tblinner').scrollLeft(offset);`

However, I haven't tested the effects of such a change.

**Comment by kgroot** [comment]
Wedebe, sorry I missed your question.
My timezone in OpenWebif is set to "Europe, Amsterdam":
![Screenshot from 2022-04-28 17-24-52](https://user-images.githubusercontent.com/3846231/165787876-fe64b10a-8b9b-48d1-9397-329bba0e1305.png)

On the dm920 it is:
root@dm920:~# date
Thu Apr 28 17:19:42 CEST 2022
root@dm920:~# date +"%Z %z"
CEST +0200
root@dm920:~# cat /etc/timezone
Europe/Amsterdam

so this seems the same.

**Comment by wedebe** [comment]
@kgroot, could you check the same using the classic interface too, please?

**Comment by kgroot** [comment]
I did not know there was a classic interface. It is not bad at all:
![OpenWebif_ClassicInterface](https://user-images.githubusercontent.com/3846231/165831907-4997c79a-17c0-4ca1-a8ca-3bd5bf56135f.png)

Here the current time line is present and almost correct. It seems a few minutes off. In view 3 channels show programs that are started (grey), but the current time is just before these programs. Also see the laptop clock on the bottom right.

This deviation is however not too bad. I will use this classic interface!

**Comment by wedebe** [comment]
Something _verrry_ bizarre going on here for sure...

Modern:
<img width="800" alt="" src="https://user-images.githubusercontent.com/9741693/167617111-32c8c087-38f5-464d-a5c8-ad958232b488.png">

Classic:
<img width="800" alt="" src="https://user-images.githubusercontent.com/9741693/167617579-22c88ebf-772e-4d62-bef0-7e0a0d061396.png">


Whenever I get some proper time, I'll look into the classic code to see where modern's going wrong 🙈

**Comment by wedebe** [comment]
I'll revert to 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/6ee978c9deafd163cd3348f2266025a4fb7ff872/plugin/controllers/views/responsive/ajax/multiepg.tmpl
in order to 'fix' this.

MultiEPG is due a complete overhaul, for which I intend to use CSS grid, so I won't spend time trying to figure out the underlying issue.

**Comment by kgroot** [comment]
Wedebe,

Thanks for your effort. It now works perfectly!
