### ISSUE TITLE
Stream IPTV/URL through Enigma2 box

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1493]
How can we stream an IPTV/URL through an m3u served via the box (the m3u should _not_ link directly to an internet stream!)

In some cases a device with OpenWebif access might only have LAN access with no internet.

I think specifically, I'm looking to craft an m3u with the proper sref.

**Comment by wedebe** [comment]
For reference I've figured out the url to use :)

/web/stream.m3u?ref=4097%3A0%3A2%3A0%3A0%3A0%3A0%3A0%3A0%3A3%3Ahttps%3a//streamssl.chilltrax.com/&name=Chilltrax&fname=Chilltrax&device=etc

(which is basically the url-encoded form of the following):
/web/stream.m3u?ref=4097:0:2:0:0:0:0:0:0:3:https://streamssl.chilltrax.com/&name=Chilltrax&fname=Chilltrax&device=etc

I plan to introduce a setting to `Stream IPTV/URLs through box instead of directly`*.
(*it'll need to be shorter than that to fit in the side menu, so suggestions welcome!)

**Comment by jbleyel** [comment]
What you are describing is playback vs stream. The extra setting makes no sense imho.
