### ISSUE TITLE
Missing Transcoding Setup

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#1507]
Why there missing Transcoding Setup item in menu for boxes with transcoding ? 

It seems, transcoding stream not works too (except my Vu duo4k )

**Comment by jbleyel** [comment]
Transcoding Setup menu is not part of the Openwebif.

**Comment by ims21** [comment]
Yes and no ...  see https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/search?q=Transcoding

**Comment by ims21** [comment]
But it seems, problem will be in e2

**Comment by ims21** [comment]
Our e2 was fixed. Menu "Transcoding Setup" is not in Settings displayed still. 

When I tried debug, there is TRANSCODING set as true. Where is filled list for "Setings" menu in Owif, pls ?

**Comment by ims21** [comment]
I think, it could be somewhere in [this rebuild](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/6d99f6e1e3402f929d8d7d735ba9b068cdbedfbe), because "setup.xml" for Transcoding plugin is found there, but is not added to Setting.

**Comment by ims21** [comment]
Problem found.  In our setup.xml is 2 years "showOpenWib**IF**" instead "showOpenWebIf". Weird, that almost 2 years it worked.

**Comment by ims21** [comment]
mmm ... due [this](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/e47b6ade55187403bbcbbce7564324ce83ab3b0e).  We cannot check each change in Owif ...  there should be done backward compatibility ...
