### ISSUE TITLE
Pushing translations from weblate project

### ISSUE THREAD

**Issue by tinola** [E2OpenPlugins/e2openplugin-OpenWebif#1514]
Hello,

There're new translations commits on weblate OpenWebif project https://hosted.weblate.org/projects/e2openplugin-openwebif/e2openplugin-openwebif/ 
How to push them to our master branch? Is there any auto tool, or maintainer has to do it manually?
Cheers!

**Comment by tinola** [comment]
Thanks!
Forgot to ask about pushing changes from us to weblate, for example lowercase 'receiver' was changed to 'Receiver' as of commit: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/f2d3d9413fede68f08a6a6a7216610ae763df033

**Comment by jbleyel** [comment]
fixed

**Comment by tinola** [comment]
Thx a lot! In few minutes I'll fix translation in my native language on weblate =)

**Comment by tinola** [comment]
@jbleyel Could you please check our "weblate" changes and push them to the master branch?...

BTW - how can volunteers push translations change of any language from [@weblate](https://hosted.weblate.org/projects/e2openplugin-openwebif/e2openplugin-openwebif/) to ours master without your approval? Just curious... :)
