### ISSUE TITLE
model/info.py

### ISSUE THREAD

**Issue by WanWizard** [E2OpenPlugins/e2openplugin-OpenWebif#1516]
In several places, the code of info.py has the comment
````
# iNetwork.getAdapterAttribute is crap and not portable
````

As I wholeheartedly agree with the first bit, I intend to refactor it completely, but ideally I want to address as many issues as possible. 
What exactly isn't portable about it / what exactly should be portable, and to where?

As far as I can see, the code used in info,py isn't much different from the code in iNetwork, and suffers from the same problems (for example no IP displayed for wlan interfaces that become active after E2 has started).

@jbleyel @Schimmelreiter

**Comment by jbleyel** [comment]
The major plan for OWI 2.0 is :
* remove all brandlings
* use boxinfo
* remove all images and remotes

**Comment by WanWizard** [comment]
Thanks. Does boxinfo also provide this kind of interface data?

I still have to look into that, for OpenPLi boxinfo is complex because we don't have a one-to-one between image and box.

**Comment by WanWizard** [comment]
@jbleyel do you have an idea of due date for OWI 2.0? So we can make sure we're ready for it?

**Comment by jbleyel** [comment]
Not yet .. the remote control files are not finished and this is one of the important part.

**Comment by wedebe** [comment]
Is there a specific branch for 2.0?

**Comment by jbleyel** [comment]
NO .. I will start from scratch.
New repro.

**Comment by jbleyel** [comment]
This will be fixed in Version 2.0 and not here.
