### ISSUE TITLE
Radio timers do not work

### ISSUE THREAD

**Issue by kybos** [E2OpenPlugins/e2openplugin-OpenWebif#1524]
**Describe the bug**
New design: 
There is no possibility to create a timer for radio at all.
Classic design:
Radio timer can be created but the settings get lost (radio check box + channel)

**To Reproduce**
1. Go to Timers
2. Click on Add timer
3. Enter settings and Save
4. Open again with Edit timer

**Expected behavior**
Ability to create a consistent radio timer.

**Screenshots**

**Image (please complete the following information):**
 - OS: VTi
 - Version 15.0.0

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version 90.0

**Additional context**
OpenWebIf version: 1.5.1

**Comment by jbleyel** [comment]
I cannot reproduce this.
I have created a radio timer and then edit the timer and i see no issue.

**Comment by jbleyel** [comment]
Please try again using the latest version.
You probably use a digital radio with sref 1:0:A

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/f1cbf2675afc2a0574a318cf43abee5f46e0ddd1

**Comment by kybos** [comment]
Thanks, I will try.
Not sure if the latest version will be installed automatically in VTi or I have to do it manually, I must check.

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/raw/gh-pages/enigma2-plugin-extensions-openwebif_latest_vti.ipk

**Comment by kybos** [comment]
I installed the latest version according to the instructions in the README (1.5.2).

Everything is working as expected now, tested Add Timer both from EPG and through Timers menu.
Even the EPG search is now working for radio channels! This wasn't the case before.

Thanks very much for the fixes. Closing this ticket.
