### ISSUE TITLE
Movie directory - remember path to Owif exit

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#1530]
Could be used last browsed movie directory for whole time when is Owif running (same for new/old) ?

Now it is very uncomfortable - always, when user goes to "Movies", is there set 'default directory for recording' path.
It is very anoying, when user browsing, f.eg. some subdirectory on mounted hdd, then he need check timers or anything in Owif and next visit in "Movies" has again "default directory for recording" and user must browse whole path again.

It would be good, when there will be set last browsed directory to exit Owif. On new start there could be "default directory for recording" again.

**Comment by jbleyel** [comment]
Should be feasible.

**Comment by ims21** [comment]
> Should be feasible.

Thanks ... how soon it could be ? :-)

**Comment by jbleyel** [comment]
This feature is implemented in V 2.0
