### ISSUE TITLE
Ampersand (&) shown in encoded form when editing timer

### ISSUE THREAD

**Issue by mkomko** [E2OpenPlugins/e2openplugin-OpenWebif#1539]
I updated from 1.2.0 to build 1.5.2-git20220718-r2 today and the following problem still exists.

**Affected user interface (delete as appropriate):**
This bug occurs in *both* the `Modern` and `Classic` web interfaces.

**Describe the bug / Actual behaviour:**
When creating a timer by editing it directly from the EPG, the & character (ampersand, and sign) is shown in its encoded form in the title and description. For example "Pain & Gain" becomes "Pain \&amp; Gain".

**Expected behaviour:**
The title and description contains the & sign in its correct form as shown in the EPG.

**Has this issue started to happen just recently?**
No, as written above I had the same issue with version 1.2.0.

**To reproduce:**
1. Go to the EPG
2. Find a TV show containing an ampersand (&)
3. Click on the TV show.
4. Click on edit timer.
5. See title and description.

**Screenshots**
![image](https://user-images.githubusercontent.com/8350714/179602997-d5cae3f4-9cec-4b77-8810-ab4ee6182238.png)
![image](https://user-images.githubusercontent.com/8350714/179603058-9673521f-60c4-4fb8-928a-b5c81aa58c78.png)
![image](https://user-images.githubusercontent.com/8350714/179603126-07984f8e-24c4-4ae2-9097-9707efa95f19.png)

I don't know if the \n is a bug as well or the source is responsible.

**Image (please complete the following information):**
 - OS: VTI
 - Version 15.0.0

**Desktop (please complete the following information):**
Any.

**Comment by wedebe** [comment]
I've got Work in Progress on EPG code so I'll test this when I'm back home with my receiver.

The timer edit dialog is due for modernisation nonetheless.

**Comment by mkomko** [comment]
@wedebe Thanks for your reply! If I can request another little change for the timer edit dialog: Please change the time picker to 5 minute intervals. Usually TV shows don't start at 10:12 or 10:28 but rather 10:15, 10:25 etc.
Should I open a feature request for that?

Right now I'm running a Tampermonkey script to change it on my side ;-).

**Comment by wedebe** [comment]
@mkomko, once you've saved a problematic timer...

...could you go into the timer list in OpenWebif and click `Edit` - does the `&amp;` turn to `&amp;amp;` (or something similar?).

I'm not sure about the cause of all the `\n` (newline) characters - what source do you use for EPG data? (`EPGRefresh` or just satellite EPG feed?)

RE: the time steps, I plan to use the client device's date/time picker. Take a look at the New AutoTimer form and let me know what you think.

**Comment by mkomko** [comment]
Fixed in 1.5.2-git20221029-r2, thank you very much!
