### ISSUE TITLE
PEP8 code style adherence question

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1543]
I've seen a couple of commits in this repo regarding PEP8 preparation. 

There's currently quite a difference of coding styles (to which I'll admit I've added), 
- is PEP8 definitive for new code, 
- will the new version/repo utilise it, 
- will the existing code be updated to suit?
- is there a defined set of exceptions to accommodate OWIF style?

**Comment by jbleyel** [comment]
https://e2openplugins.github.io/e2openplugin-OpenWebif/flake8_report.txt

**Comment by jbleyel** [comment]
We ignore W191,E501,E302,E711,E128,E265 in flake8.
We can also use black instead of flake8.

**Comment by jbleyel** [comment]
We have also autopep8.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/CI/build.sh#L19

**Comment by wedebe** [comment]
Thanks!

For reference:

W191- indentation contains tabs
E501 - line too long (82 > 79 characters)
E302 - expected 2 blank lines, found 0
E711 - comparison to None should be ‘if cond is None:’
E128 - continuation line under-indented for visual indent
E265 - block comment should start with ‘# ‘
