### ISSUE TITLE
Inconsistent use of `#!/usr/bin/python`

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1547]
Some OWIF .py files start with
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```

others with
```
# -*- coding: utf-8 -*-
```

**Comment by jbleyel** [comment]
`#!/usr/bin/python`

can be removed

`# -*- coding: utf-8 -*-`

is needed for python 2 in some cases

**Comment by IanSav** [comment]
The "# -*- coding: utf-8 -*-" should only be required by code that contains raw UTF-8 characters.  In most cases where this has been used it is *not* required.  Most of Enigma2 and its plugins should be written in US English.  This string is used to warn that the file contains raw UTF-8 data that needs to be protected.  (For example when being edited in a text editor - that respects the tag.)

**Comment by wedebe** [comment]
Super, thanks :)
