### ISSUE TITLE
Typo in `P_recordnow` ( undefinitely -> indefinitely)

### ISSUE THREAD

**Issue by wedebe** [E2OpenPlugins/e2openplugin-OpenWebif#1555]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/0cfb76bfb9c9af62a6eaae26d606269aa9bd496d/plugin/controllers/web.py#L1384

**Comment by jbleyel** [comment]
This is an api request parameter and some 3rd party tools may need this typo.

**Comment by wedebe** [comment]
> This is an api request parameter and some 3rd party tools may need this typo.

`indefinitely` should instead be added as an args check

**Comment by jbleyel** [comment]
Not really .. "infinite" is only what we need and "undefinitely" is for backward compatibility from the old DMM web interface.

**Comment by wedebe** [comment]
How about we add a comment to that effect, to dissuade future api consumers from using `undefinitely`?

**Comment by jbleyel** [comment]
You can do this if you like in an api doc file what not exists and no-one reads.

**Comment by jbleyel** [comment]
Please note.. many 3rd party tool have made no updates since years.

**Comment by wedebe** [comment]
What's a doc? 🤣
