### ISSUE TITLE
EPG Refresh seems to be broken

### ISSUE THREAD

**Issue by WanWizard** [E2OpenPlugins/e2openplugin-OpenWebif#1562]
This bug occurs in *both* the `Modern` and `Classic` web interfaces.

![image](https://user-images.githubusercontent.com/456954/188167066-663fc64c-fc5e-4d8a-89dc-48062d68d502.png)

![image](https://user-images.githubusercontent.com/456954/188167238-5235bb3e-356e-4667-8195-d7298a6db0ec.png)

**Comment by jbleyel** [comment]
no issue here
please provide debug log

**Comment by WanWizard** [comment]
What exactly do you mean by "debug log"? There are no errors in the Enigma debug log. Anything else I can debug?

In E2, the plugin works fine:
![image](https://user-images.githubusercontent.com/456954/188190883-b2af2775-a00b-4b1a-9085-2052fa7430fb.png)

![image](https://user-images.githubusercontent.com/456954/188190963-4232421d-fce6-461a-be3e-00d60aa01978.png)

**Comment by jbleyel** [comment]
The link with error 404 must be also in enigma debug log and also in browser developer tools network log.

I cannot help without the link.

**Comment by jbleyel** [comment]
Do you use the latest version from here -> 

https://github.com/oe-alliance/enigma2-plugins/tree/master/epgrefresh

**Comment by WanWizard** [comment]
> The link with error 404 must be also in enigma debug log and also in browser developer tools network log.

As said, there is nothing logged.

> I think you are using this -> https://github.com/OpenPLi/enigma2-plugins/tree/master/epgrefresh or this https://github.com/OpenPLi/enigma2-plugins/tree/python3/epgrefresh

This is OpenPLi (on py3), not OE-A.

It looks like it happens in the OWIF code, "http://172.19.12.60/epgrefresh" works, but "http://172.19.12.60/epgrefresh/get" returns this:
````
No Such Resource
No such child resource.
`````
which imho is an OWIF error?

**Comment by jbleyel** [comment]
No.. it's a problem of the pli plugin.

https://github.com/OpenPLi/enigma2-plugins/blob/python3/epgrefresh/src/plugin.py#L255-L276

**Comment by jbleyel** [comment]
This Pli hack is wrong because this part is implemented in OWIF already.

And this file -> https://github.com/OpenPLi/enigma2-plugins/blob/python3/epgrefresh/src/EPGRefreshResource.py is NOT python3 compatible.

**Comment by WanWizard** [comment]
Was just about to write "wtf does that code do there"?

**Comment by jbleyel** [comment]
You need to fix EPGRefreshResource.py and remove the hack from plugin.py

**Comment by WanWizard** [comment]
Looking into it, thanks for the headsup, and sorry for wasting your time.
