### ISSUE TITLE
Progressbar doesn´t work

### ISSUE THREAD

**Issue by NaseDC** [E2OpenPlugins/e2openplugin-OpenWebif#1574]
Hello,
in the newer versions the progress indicator does not work anymore (runtime in minutes is displayed). This occurs in both classic and modern display. The last version where this was still displayed is to my knowledge the following version.

**1.5.2-git20220722-r10**

Used image is VTi 15 with browser Firefox 104.02
![Unbenannt](https://user-images.githubusercontent.com/5048530/191804669-e643ba0f-45af-470d-8677-0ff754025778.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/5048530/191804675-ad757f25-3484-42ed-933a-95162ea8c227.PNG)

Could this be fixed please?

Thanks in advance

**Comment by NaseDC** [comment]
thx an euch beide! funzt bestens

**Comment by jbleyel** [comment]
Ich hab nix gemacht, denn ich mache nur noch Version 2.x
