### ISSUE TITLE
[EPG] wrong date format

### ISSUE THREAD

**Issue by tinola** [E2OpenPlugins/e2openplugin-OpenWebif#1577]
Hi,

Click in TV channels list EPG icon one of them. The date format is broken.

![ow-date](https://user-images.githubusercontent.com/3160125/196351223-e2d6ad23-8b89-477d-b7db-40f8ba1163ed.png)

"wto 18+paź_" in Polish means "tue 18+oct_".

**Comment by ims21** [comment]
I can confirm it. It is for both version - new and classic.

**Comment by ims21** [comment]
Found it ... [here is my comment](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/bd4c4f6360e41915fd8e98afc9b68a3ebbb4fdce) about it.

**Comment by ims21** [comment]
[fixed](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/1585)
