### ISSUE TITLE
mutated vowel in folder name of recordings won't work

### ISSUE THREAD

**Issue by constlm** [E2OpenPlugins/e2openplugin-OpenWebif#1591]
I have installed OpenATV 7.1 on my two VU+ Duo2 and one VU+ Uno4K SE, and they are up to date.

This bug occurs in the `Classic` web interface of  OWIF 2.0.3. I use Firefox 108.0.2.

If I try to view a folder content in the recordings where the folder name contains a mutated vowel like ä,ü,ö etc. I get a spinning circle but the content is never shown.
When I replace the mutated vowel it works.

example:
"österreichischer Film" doesnt't work
"oesterreichischer Film" works

**Comment by jbleyel** [comment]
fixed here -> https://github.com/oe-alliance/OpenWebif/commit/384bc169d549c850521a8466188f407eaddbc271
