### ISSUE TITLE
settings are not shown as they are set on the box

### ISSUE THREAD

**Issue by constlm** [E2OpenPlugins/e2openplugin-OpenWebif#1592]
I have installed OpenATV 7.1 on my two VU+ Duo2 and one VU+ Uno4K SE, and they are up to date.

This bug occurs in the Classic web interface of OWIF 2.0.3. I use Firefox 108.0.2.

If I open the settings in OWIF a lot of drop down settings are not shown correct.
For example under recordings the folder settings are empty or the time settings before and after recordings all show 0 minutes.
On the box they are shown correct.

![grafik](https://user-images.githubusercontent.com/122689178/212498410-efdb5905-717d-47e8-94e5-c02f93c4bc5d.png)

**Comment by jbleyel** [comment]
fixed in version 2.x you need to wait for the next update

**Comment by jbleyel** [comment]
This needs to improved in the next versions .. it's on my todo list.

**Comment by jbleyel** [comment]
Please create issues for version 2.x only here -> https://github.com/oe-alliance/OpenWebif/issues

**Comment by jbleyel** [comment]
Closed because of a new issue in the correct repository.
