### ISSUE TITLE
EPGRefresh error 

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#1597]
Both modern/classic - EPGRefresh - there are not loaded fields with Bouquets and Services - error under py3 (tried under PLi) only.
Message:
`<html> <head><title>404 - No Such Resource</title></head> <body> <h1>No Such Resource</h1> <p>No such child resource.</p> </body> </html> `

**Comment by jbleyel** [comment]
Looks like a bug in EPGRefresh.

**Comment by ims21** [comment]
No. There in ER.py in render() are returned true data with return six.ensure_binary(''.join(epgrefresh.buildConfiguration(webif=True))) from EPGRefresh:
`b'<?xml version="1.0" ?>\n<epgrefresh version="1">\n\n <e2service>\n  <e2servicereference>1:0:1:5013:2BD:600:E080000:0:0:0:</e2servicereference>\n  <e2servicename>EPG</e2servicename>\n </e2service>\n <e2service>\n  <e2servicereference>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.dbe01.tv" ORDER BY bouquet</e2servicereference>\n  <e2servicename>SK</e2servicename>\n </e2service>\n <e2service>\n  <e2servicereference>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.dbe00.tv" ORDER BY bouquet</e2servicereference>\n  <e2servicename>MS</e2servicename>\n </e2service>\n <e2service>\n  <e2servicereference>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.N.tv" ORDER BY bouquet</e2servicereference>\n  <e2servicename>N</e2servicename>\n </e2service>\n <e2service>\n  <e2servicereference>1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.dbe02.tv" ORDER BY bouquet</e2servicereference>\n  <e2servicename>Sport</e2servicename>\n </e2service>\n</epgrefresh>'
`

**Comment by ims21** [comment]
Found ... I really "like" commented or missing 'print' under exceptions in code ...

**Comment by ims21** [comment]
Btw ... there is not checkbox for begin/end pars, imho => begin/end times are not added to 'reqs' and are not transfered to e2

[https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/c9e073ee4d943fc4fe45c4b7691fc3fb293cd9aa/sourcefiles/js/epgr.js#L232](url)

**Comment by jbleyel** [comment]
> Btw , for classic, [there](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/c9e073ee4d943fc4fe45c4b7691fc3fb293cd9aa/sourcefiles/js/epgr.js#L232) is not checkbox for begin/end pars, imho => begin/end times are not added to 'reqs' and are not transfered to e2

fixed

**Comment by ims21** [comment]
There must be adapted 'toUnixDate' too as:

function toUnixDate(date){
	var datea = date.split(':');
	var d = new Date();
	//d.setFullYear(datea[2],datea[1]-1,datea[0]);
	d.setHours( datea[0] );
	d.setMinutes( datea[1] );
	d.setSeconds( 0 );
	return Math.floor(d.getTime() / 1000);
}

**Comment by ims21** [comment]
thx
