### ISSUE TITLE
unknown compression 'tar.zst'

### ISSUE THREAD

**Issue by NorbertBauer** [E2OpenPlugins/e2openplugin-OpenWebif#1607]
Hi

Did not update for long time, but the last version is not installabel because of tar.zst compression.

Error:

dpkg-deb: error: archive '/tmp/enigma2-plugin-extensions-openwebif_1.5.2-git20221227-r3_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /tmp/enigma2-plugin-extensions-openwebif_1.5.2-git20221227-r3_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /tmp/enigma2-plugin-extensions-openwebif_1.5.2-git20221227-r3_all.deb

**Comment by jbleyel** [comment]
This is the command line to generate the deb file:

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/CI/create_ipk.sh#L140

I have no idea what's wrong here.

**Comment by NorbertBauer** [comment]
Maybe you should add the parameter „-Zxz“ to this command, so it will force tar.xz compression.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: jbleyel ***@***.***>
Gesendet: Sunday, March 12, 2023 9:28:07 AM
An: E2OpenPlugins/e2openplugin-OpenWebif ***@***.***>
Cc: NorbertBauer ***@***.***>; Author ***@***.***>
Betreff: Re: [E2OpenPlugins/e2openplugin-OpenWebif] unknown compression 'tar.zst' (Issue #1607)


This is the command line to generate the deb file:

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/CI/create_ipk.sh#L140

I have no idea what's wrong here.

**Comment by NorbertBauer** [comment]
New deb package works, at least it can be read. Dreambox OS OE2.5 has no python-six 1.14 that you depend on, but thats an other problem. But I did alread ymanage to configure webif thats included in the OS.

Thanks
