### ISSUE TITLE
Q: translating for setup.xml item

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#1614]
Is there way for items in plugin's setup.xml use translate for same items from plugin's .mo translate or no ? 
I think (my be, it is my mistake only), for e2 items it works.  Or there must be something added to plugin?

**Comment by jbleyel** [comment]
Take a look at version 2.0.

https://github.com/oe-alliance/OpenWebif/blob/main/plugin/plugin.py#L133

**Comment by ims21** [comment]
I meant automatic translation of entries written in setup.xml in my plugin - in 'old' Owif. Is it possible or not? I tested that if I change the variables LOCALES_DOMAIN/LOCALES_RELPATH in i18n.py with my plugin variables, then translating works, but that's not the solution.

**Comment by jbleyel** [comment]
I don’t understand the problem because the old OWI has no setup.xml

**Comment by ims21** [comment]
'Old' Owif using setup.xml file for plugins. Plugin can to have setup.xml file (f.eg. Transcode plugin under PLi) and this file is readed in owif in controllers/models/config.py. It adding config items from this setup.xml file to standallone item under "Settings" in owif  (config items in plugin must be readed by enigma before run Owif => must be placed in plugin.py). But there not works translation for it. I can set translating for plugin settings and enigma items or owif and enigma items, but not for enigma, owif and this plugin setting.

**Comment by jbleyel** [comment]
Ah . You mean setup.xml from other plugins.

What image/version do you have?

**Comment by ims21** [comment]
PLi

**Comment by jbleyel** [comment]
What plugin is translated and what is not translated?

**Comment by ims21** [comment]
Is not translated RefreshPlugin (install it from feed, under develop), is not translated Transcoding plugin (but it is not for all boxes)

**Comment by jbleyel** [comment]
Transcoding plugin is translated on my box.
This looks like a bug or missing function in Setup.py in Pli

**Comment by ims21** [comment]
It seems, in PLi is missing all for it ...
