### ISSUE TITLE
OpenWebIF capture

### ISSUE THREAD

**Issue by mihaip1948** [E2OpenPlugins/e2openplugin-OpenWebif#1619]
OpenWebIF produce a bad capture definiton ... texts are pixelated !
The cause is like this ...
- grab is using always a 1280*720 frame buffer
- OpenWebIF decide , from an unknown reason , to upscale the capture to 1920*1080
- the upscale process is poor ! the result is blur video and pixelated OSD

**Comment by jbleyel** [comment]
This is not an issue of openwebif.
Someone needs to rewrite the aio-grab tool.
