### ISSUE TITLE
EPG shows data from yesterday today if older epg data is present

### ISSUE THREAD

**Issue by retoch44** [E2OpenPlugins/e2openplugin-OpenWebif#1626]
**Affected user interface (delete as appropriate):**
This bug occurs in *both* the `Modern` and `Classic` web interfaces.

**Describe the bug / Actual behaviour:**
I configured OpenATV to save older EPG data for 1440 minutes (max). The EPG in OpenWebif for the present day now shows data from yesterday (see picture), following days show correct data. EPG on TV shows always correct data. If save older EPG data is set to 0, EPG for the present day works in OpenWebif. 

**Has this issue started to happen just recently?**
Noted that since upgrading from OpenATV 6.4 to 7.3 in June 2023. With 6.4 it works in OpenWebif.

**Image (please complete the following information):**
 - OS: OpenATV
 - Version 7.3 Build 2023-08-18

**Desktop (please complete the following information):**
 - Browser firefox, vivaldi
 - Version newest

**Additional context**
OWIF 2.0.7
Build: 2.0.7-git106+c2e44ad-r0

![2023-08-19-14 48 22-192 168 0](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/assets/142671411/e7534566-c4ea-4354-a54b-290f886837a0)

**Comment by jbleyel** [comment]
Wrong repro.
Version 2.X is here -> https://github.com/oe-alliance/OpenWebif

**Comment by retoch44** [comment]
Thanks for the hint and sorry.

**Comment by jbleyel** [comment]
No problem.

**Comment by wedebe** [comment]
@jbleyel , could you build an ipk at this point in time, please?

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/cea08803487e3c24592b793b0fd6904e0ed677fe
