### ISSUE TITLE
EOL?

### ISSUE THREAD

**Issue by WanWizard** [E2OpenPlugins/e2openplugin-OpenWebif#1629]
***!*** Please note that this version of OpenWebif is no longer in development ***!***

Log a feature request for OpenWebif v2 instead:
https://github.com/oe-alliance/OpenWebif/issues?q=is%3Aissue

@wedebe @jbleyel 

Why the above? Why no longer "E2Open" but OE-Alliance? Why are image builders using this version not informed / consulted?

**Comment by WanWizard** [comment]
Should OpenPLi switch? Is it, and will it stay compatible?

**Comment by jbleyel** [comment]
It’s up to you.

I have stopped working on version 1.x someone else can take over or you switch to version 2.x

But version 2 is different. Especially for branding.

**Comment by WanWizard** [comment]
Ok.

So I am right in my observation that OpenWebif is no longer open, but is now OEAwebif.

**Comment by WanWizard** [comment]
> But version 2 is different. Especially for branding.

Which is a pain because it is explicitly and purposely designed to ignore our situation, so we can't implement it.

**Comment by jbleyel** [comment]
What?

Are you kidding me?

Take a look at the openpli bb file for Openwebif.

**Comment by jbleyel** [comment]
> > But version 2 is different. Especially for branding.
> 
> Which is a pain because it is explicitly and purposely designed to ignore our situation, so we can't implement it.

This is wrong.
You only need BoxInfo that’s all.

**Comment by jbleyel** [comment]
> Ok.
> 
> So I am right in my observation that OpenWebif is no longer open, but is now OEAwebif.

No.The word Open comes from open source not from OpenPli.

By the way. Most of the distros have switched to version 2.

**Comment by Huevos** [comment]
> Why are image builders using this version not informed / consulted?

I don't know what you mean by this. For more than 10 years we have been trying to persuade OpenPLi implement some form of information system (branding, boxinfo, etc) but OpenPLi team just pontificate and tell us it is unnecessary. We offered many different solutions,but none were good enough. And the OpenPLi team itself has done nothing in this respect. Do you really expect jbleyel to go on and on maintaining code that he don't believe in just to appease people who want to drag there feet? So he has just left the version that is impossible to maintain for those who don't want to keep step with the other distros and moved on to a new cleaner version without the hacky workarounds.

We too at OpenViX had to make a few changes to be with OpenWebIf version 2.0 but that's life if you want to be compatible with newer software and take advantage of the benefits.

There is nothing stopping OpenPLi implementing the code that is needed to be compatible with OpenWebIf version 2.0. OE-Alliance-Core, openatv and openvix are all open source. The code is there for anyone that chooses to implement it in their own repos.

**Comment by WanWizard** [comment]
Bull cookies. We're running around in circles.

I've explained over and over again that we CAN'T implement the system as currently designed, as it REQUIRES a one-on-one between STB model and MACHINE, which OpenPLi doesn't have, doesn't see the need for, and doesn't want to implement. And it makles me sick that people like you then try to shift the blame to us. Especially since you're one of the people we've invited into our kitchen in an attempt to find common ground in these kind of design decitions.

This fact has been ignored time and time again, including by you @Huevos, making it very difficult (if not impossible) for us to implement the current boxinfo design with the static enigma.info file.  It is not us we don't want to implement, it is OE-A who very selfishly can't be bothered to cooperate and take others into account.

My point was that OE-A has invented something that only works for OE-A (based images), and my moving to make a a previously fully open project to depend on that, means it is no longer open, it is OE-A specififc. And OpenVIX is OE-A, which makes your arguments moot.

**Comment by Huevos** [comment]
> we've invited into our kitchen in an attempt to find common ground in these kind of design decisions.

Don't shoot the messenger. I am one of the few non PLi members who has gone out of my why to bring features to PLi.

The truth is jbleyel is the developer and it was his decision to fork it. OE-A members choose which version they use. No one is forcing anyone to do anything.

As far as BoxInfo goes, yes it requires one-to-one, so if PLi's images aren't one to one, use a one-to-one name in BoxInfo. It will work.

I even made a BoxInfo for PLi, complete with all data but it got rejected.

**Comment by WanWizard** [comment]
I have no problem with BoxInfo in itself, I'll trade a global list for an immutable object every day of the week. 

The problem is its source, we can't create the enigma.info file that is not only at the basis of BoxInfo, but is also checked directly at lots of places in the code. We simply don't have the required data at compile time.

There is absolutely no justifiable reason to abandon E2OpenPlugins, and move to an oe-a repo, other than an attempt to close the door for all non-oe-a images, irrespective of the boxinfo discussion. It could have been another branch of the current repo, it could have been another E2Open repo, but it was decided not to. Which means we will be forced to implement every OE-A whim just to remain compatible with something that was Open.

**Comment by WanWizard** [comment]
p.s. it is not only BoxInfo, there are more OE-A specific dependencies, for example with information about RC's.

**Comment by Huevos** [comment]
> p.s. it is not only BoxInfo, there are more OE-A specific dependencies, for example with information about RC's.

That isn't true. On version 2.0 the remote image is virtual.

> Please don't pretend this is new, it is OE-A's signature, fork everything including the kitchen sink, and then make sure it is no longer compatible with the original to prevent others (i.e. OpenPLi) from using it.

So apart from branding what else is not compatible?

![1](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/assets/2067864/dd9bc631-12ed-441b-994d-417593cffdc5)

**Comment by littlesat** [comment]
For what functionality is the branding stuff mandatory for owif? Why was it mandatory to fork development to or-aliance?

**Comment by jbleyel** [comment]
You all miss the point.
I have started the new repro because of this:

* remove all python2 code
* remove all duplicate branding code ( this is already in core enigma2 code)
* remove the remote control images because most of them are bad quality and not useful.
* start a clean git because this here has 7 GB.

**Comment by WanWizard** [comment]
I think you missed mine.

You started it as an OE-A specific project, in an OE-A specific repo, with OE-A specific dependencies. Which happen to be the environment you contribute to in general. 

While the original OpenWebif was really open en available / usable for all distro's.

It is a generic OE-A trend since its conception: fork everything, then make the fork incompatible with the original and the distro's the original is used on.

**Comment by jbleyel** [comment]
> I think you missed mine.
> 
> You started it as an OE-A specific project, in an OE-A specific repo, with OE-A specific dependencies. Which happen to be the environment you contribute to in general.

This is wrong. I have only use the GitHub space of OE-A.

> While the original OpenWebif was really open and available / usable for all distro's.
>

Version 2 is not closed.


> It is a generic OE-A trend since its conception: fork everything, then make the fork incompatible with the original and the distro's the original is used on.

This is also wrong.
