### ISSUE TITLE
Add Satellite position in "Current" service info

### ISSUE THREAD

**Issue by korsanovix** [E2OpenPlugins/e2openplugin-OpenWebif#188]

**Comment by jbleyel** [comment]
Hi @Schimmelreiter , das geht schon .. Dafür müsste man in der satellites.xml die tsid suchen und dann hat man z.B folgende info "Express 3A (11.0W)" / ABER ich hab keine Ahnung wie lange das dauert und ob das so eine gute Idee ist.
Mit xpath sollte das kein Thema sein.
Frag mich aber nicht, was man machen muss wenn es nicht DVB-S ist.
Es gibt da noch eine terrestrial.xml.

**Comment by jbleyel** [comment]
UPDATE:
Ich hab das mal eingebaut.

`
		cur_info = feinfo.getTransponderData(True)
		if cur_info:
			inf['orbital_position'] = cur_info.get('orbital_position', None)

`

**Comment by jbleyel** [comment]
Close with https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/e94cc732d867bcc0ddc1cb68f8a4a6b9b4d9f05f
