### ISSUE TITLE
Make all links relative

### ISSUE THREAD

**Issue by samtap** [E2OpenPlugins/e2openplugin-OpenWebif#190]
Many html links in the template files or created dynamically by js/python code, use absolute paths. For example the stylesheet is loaded from '/css/style.css' which could also be expressed in a relative path as 'css/style.css', dropping the root '/'.

When links are relative, it opens up the possibility to serve OpenWebIf through a reverse proxy. I.e. accessing https://external-host.com/openwebif/ would be forwarded by the proxy to the internal host that runs openwebif on http://192.168.1.1:8080/. This has multiple advantages, making remote access to OpenWebIf more secure (ssl, authentication etc. configured on the proxy) and doesn't require port 8080 to be forwarded through the firewall. I've taken a quick look through the code and the changes required are minimal and non intrusive.

**Comment by pseguy** [comment]
I'm also facing this issue (openwebif css and js unreachable through a reverse proxy). 
I hope you'll be able to fix this (make links relative) one day.
Thanks

**Comment by Schimmelreiter** [comment]
Re-Opened as a reminder.

**Comment by jbleyel** [comment]
Relativ links are not possible.
