### ISSUE TITLE
Have the tuner lines in box-info show their state

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#204]
Hi!

The box info lists all tuners ...
![image](https://cloud.githubusercontent.com/assets/2022025/4874845/7b4c18d0-6275-11e4-9978-c7004d9d03fd.png)
... but doesn't show their state.

There have been multiple situations where I had wished I could easily see if they are occupied or not and if they are partially occupied (On my 4 tuner box), which ones.

I've already looked at NimManager but at a quick glance couldn't find out how to gather those info.
Probably need to pick it up from the frontend rather than them Nim ....

I suggest something like
green = unused
yellow = tuned but not recording
red = recording

If we could see the tuned channels it would be even better.
For example it could help in finding out which cable from the multiswitch to the box needs repair ...

**Comment by jbleyel** [comment]
Was soll ich ändern?
Die Texte bräuchte ich dann auch noch.

<img width="404" alt="bildschirmfoto 2016-11-02 um 18 47 01" src="https://cloud.githubusercontent.com/assets/964927/19940406/d8ec4a9e-a12c-11e6-97e3-4273976fc1fd.png">

**Comment by rdamas** [comment]
Ich persönlich würde es besser finden, wenn die Buttons nicht vor  "Tuner X:" stehen, sondern vor der Beschreibung. Links sollte das Topic/der Key/der Schlüssel oder wie auch immer stehen, rechts dann die Beschreibung/der Wert/was auch immer. Der Status gehört meiner Meinung nach zum Wert, nicht zum Schlüssel.

Legende: hmm. Mal drüber nachdenken.

**Comment by jbleyel** [comment]
Die Bildchen sind links weil der Text links kürzer ist. Siehe Bild

<img width="520" alt="bildschirmfoto 2016-11-02 um 20 13 24" src="https://cloud.githubusercontent.com/assets/964927/19943702/e009545a-a138-11e6-85f9-ffd66d85d780.png">

Ob gelb oder grün ist mir Wurst.

Soll ich die Legende so lassen?

**Comment by jbleyel** [comment]
DONE:
<img width="831" alt="bildschirmfoto 2016-11-02 um 20 49 09" src="https://cloud.githubusercontent.com/assets/964927/19944859/d7ffcbcc-a13d-11e6-91f3-9da63dd1aa0f.png">

**Comment by jbleyel** [comment]
Hier die strings

'free': _("free"),
'live': _("live"),
'record_stream': _("record/stream"),

der 4. bekommt ein +

live + record/stream

**Comment by rdamas** [comment]
+ find ich gut, beim Rest der Legende halt ich mich raus.

Die Buttons sollten wirklich nach rechts vor den Tuner - Platz ist auf der Seite dafür mehr als genug. Ich würde wohl noch etwas margin-right zwischen Button und Tuner-Name setzen. Auch die Legende würde ich noch etwas absetzen, vielleicht sogar die font-size einen Tick kleiner machen. Legende rechtsbündig oder in die Tuner-Spalte sieht vermutlich nicht aus, oder?

**Comment by jbleyel** [comment]
Legende rechtsbündig ist ungünstig. Die Schrift bei der Legende etwas kleiner geht schon. 

Was gehen würde währe. Rechtsbündig und : hinter de Text und dann dahinter das Bild.

Warten wir mal was @Schimmelreiter meint.

**Comment by rdamas** [comment]
Also ich fände auch einen reinen Text-Effekt ala `text-shadow: 0 0 #000, 0 0 20px #0f0, 0 0 8px #0a0` am Tuner-td.inforight nicht schlecht anstelle der Buttons.

**Comment by jbleyel** [comment]
Versteh ich nicht. Ich brauche 3 verschiedene Farben. Wie soll das gehen?
Bitte die Themes nicht vergessen.

**Comment by rdamas** [comment]
Themes ist ein Problem. Da ist die Button Lösung definitiv die bessere. Vergiss meinen Vorschlag ;)

**Comment by Schimmelreiter** [comment]
Mir gefällt's so wie im letzten Bild, also als Symbol vor dem Tuner.
Legende ist unnötig, "aus", "grün" und "gelb/orange" sind selbsterklärend, haben wir bei Current und in LCD4Linux und in Skins auch meist so.

Vielleicht kann man den Info-Bereich "Tuner" ja noch aufklappbar machen wie links die Menüs?

Also so (zugeklappt):
![image](https://cloud.githubusercontent.com/assets/2022025/19953157/47ee7ec4-a16b-11e6-9e0d-0b5fd16478e1.png)

**Comment by Schimmelreiter** [comment]
Aufgeklappt würde dann unter jedem Tuner eine Liste der Sender und Orbitalpositionen/Transponder erscheinen, alles was davon verfügbar ist.
Unter "Vuplus DVB-S ...." stünde dann z.B.
* RTL HD (Astra 19.2°E - 11347 MHz V/L)

**Comment by jbleyel** [comment]
Ich bastel mal was.

**Comment by Schimmelreiter** [comment]
Bastel Du.
Kannst Du denn auch mal in
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/414
reingucken? :)

**Comment by jbleyel** [comment]
Hab ich schon. Das ist mir zu hoch. Das muss jemand anders machen.

**Comment by jbleyel** [comment]
Der Text 
> > RTL HD (Astra 19.2°E - 11347 MHz V/L)

 beim Tuner geht so leider nicht.

Ich habe nur den Name des Senders und die Zahl 192.
Mehr hab ich nicht.

**Comment by jbleyel** [comment]
Wenn sich jemand die Mühe macht und aus den orb Nummern ein Dict baut.
Dann kann ich das einbauen.
In der sattelites.xml müssten alle drin sein.

Ich hab aber keine Ahnung was bei DVB-C und DVB-T passiert.

**Comment by Schimmelreiter** [comment]
Was bei DVB-C passiert kann ich Dir sagen.
Bau das mal so ein, daß da der Name des Senders und ob der aufgenommen wird oder Live TV ist angezeigt wird.
Dazu als Kommentar die Ergänzung. die nötig ist um die Zahl auch anzuzeigen.
Dann probiere ich das hier mal aus.

**Comment by Schimmelreiter** [comment]
Die Zahl scheint identisch zu sein mit dem, was in der satellites.xml unter position= steht.
<sat name="177.0W C-band NSS 9" flags="0" position="-1771">

<sat name="19.2E Astra 1KR/1L/1M/1N" flags="0" position="192">

Bei Cable gibt's aber kein position= ... also muß ich mal sehen, was dann dort rauskommt.

**Comment by jbleyel** [comment]
Warte mal mit .. ich hab was gefunden.
https://github.com/OpenViX/enigma2/blob/895df321e506f25cac2cdd6ca11624941280746a/lib/python/Components/Converter/ServiceOrbitalPosition.py#L39

**Comment by jbleyel** [comment]
Jetzt bis du dran.
Wie soll ich die Zeile formatieren?
Bitte beachten hinten könnten 2 Sender stehen bei orange.
<img width="830" alt="bildschirmfoto 2016-11-03 um 12 28 34" src="https://cloud.githubusercontent.com/assets/964927/19964294/40672a4c-a1c1-11e6-8585-f770dcc0fefe.png">

**Comment by Schimmelreiter** [comment]
So in etwa:
![image](https://cloud.githubusercontent.com/assets/2022025/19964548/97dd5a0c-a1c2-11e6-9c00-0e8211659b63.png)

Der Part "Tuner" soll ausklappbar werden, so wie die Menüs links auch.
Zusammengeklappt soll man nur den höchsten Status sehen (Also idle = grau, live = grün, record = gelb/orange).
Ausgeklappt dann unter jedem Tuner alle darauf laufenden Sender mit dem jeweiligen Status.

Laß die Legende weg, die Farben haben wir sonst auch überall, außerdem wird das am ehesten von Leuten gebraucht, die wissen was sie tun.
Die Info-Seite ist eh schon so lang ...

**Comment by jbleyel** [comment]
Ausklappen find ich nicht so toll.
Wenn wir die Info haben, dann sollte man die auch anzeigen.
Du müsstest dann immer noch mal klicken und das ist nicht UX konform.

Zudem haben wir in der Zeile genügend Platz, wenn der Text "Tuner A..." nicht 50% der Tabelle belegt.

Nach UX wäre dann übrigens auch das der Böbbel ganz links ist.

**Comment by Schimmelreiter** [comment]
Dann Teil die Seite doch mal 1/3 + 2/3
Dann ein lustiges Bullet zwischen die Sender und die Sender hinter den Transponder.

Kein farbiges Bullet für den Transponder, dafür je eines für jeden Sender.

**Comment by sgse** [comment]
![image7462](https://cloud.githubusercontent.com/assets/17575778/19964787/0bd6cd0c-a1c4-11e6-9a82-604604c7e29d.png)

**Comment by Schimmelreiter** [comment]
![image](https://cloud.githubusercontent.com/assets/2022025/19964881/863a79a4-a1c4-11e6-9b3b-7fef1a4dc636.png)

**Comment by jbleyel** [comment]
Ich hab mal den ersten Test eingecheckt.

**Comment by jbleyel** [comment]
Den Sendername bei Live ermitteln war kein Problem.
Bei aktivem Stream hat es mal funktioniert, aber dann nicht mehr. (Keine Ahnung wieso)
Bei recording geht es nicht.
Wenn es jedoch nur einen aktiven Timer gibt, dann kann man von diesem Timer den Sendername holen.
Das muss ich aber noch testen.

**Comment by sgse** [comment]
Beim ersten mal hat er sich "verschluckt"?
Einmal livestream, einmal Aufnahme gestreamt.
![tv12](https://cloud.githubusercontent.com/assets/17575778/19990447/29555d2a-a22e-11e6-82d0-e3979c95433e.png)
Jetzt geht es.
![tv14](https://cloud.githubusercontent.com/assets/17575778/19990487/6076d644-a22e-11e6-828b-72f8c10e20dd.png)
![tv15](https://cloud.githubusercontent.com/assets/17575778/19990495/6bc091e8-a22e-11e6-9c35-5f6a76a54442.png)

**Comment by sgse** [comment]
Wobei ich das Erste live an habe wird ZDF angezeigt auch oben links.


![tv16](https://cloud.githubusercontent.com/assets/17575778/19990636/61a36e14-a22f-11e6-9b58-82cd54020435.png)

**Comment by Schimmelreiter** [comment]
Dir ist schon klar, daß ARD und ZDF in den Morgenstunden das selbe Programm senden?
Bist Du sicher, daß Du nicht nur Programm des Ersten, sondern auch das Erste an sich geguckt hast?

**Comment by sgse** [comment]
;) ja, es war um ca. 01:10 heute morgen.

**Comment by sgse** [comment]
Habe jetzt mal auf WDR geschaltet, es läuft einmal live ONE HD und ein Film wird angezeigt am PC.
Also am TV kann ich WDR sehen am PC eine Aufnahme und einen anderen Sender. Mehr als ich vermutet habe :)  Aufnahmewiedergabe geht also ohne Tuner. 
![tv17](https://cloud.githubusercontent.com/assets/17575778/20002347/ae949882-a280-11e6-810b-d473bad50af9.png)

**Comment by sgse** [comment]
Bei Tuner B müsste eigentlich ONE HD stehen , plus Anzeige das ein Stream läuft. War das "orange"?

**Comment by Schimmelreiter** [comment]
Ja
VTi kann Streams und Aufnahmen nicht unterscheiden.

**Comment by sgse** [comment]
Immer sind die anderen Schuld ;)

**Comment by Schimmelreiter** [comment]
Ne, ist so:
Der streamproxy verbindet sich mit E2 und E2 startet eine Scheinaufnahme, die dann gestreamt wird.

Das ist übrigens unter ATV genauso, wenn Vu+/Dags-Transcoding benutzt wird.

**Comment by Schimmelreiter** [comment]
Ne, ist so:
Der streamproxy verbindet sich mit E2 und E2 startet eine Scheinaufnahme, die dann gestreamt wird.

Das ist übrigens unter ATV genauso, wenn Vu+/Dags-Transcoding benutzt wird.

**Comment by jbleyel** [comment]
Hi @sgse / orange gibt es nicht mehr. Es gibt nur noch Grün und Rot.
Grün ist Live und Rot ist Aufnahme bzw. Stream.
Wenn ich es Schaffe Aufnahmen und Stream zu unterscheiden, dann gibt es vieleicht noch orange für Stream.

**Comment by sgse** [comment]
Jetzt laufen zwei Aufnahmen als stream. Mit meinen zwei tunern verliere ich ja nicht so den Überblick aber die Anzeige verwirrt :)
![tv19](https://cloud.githubusercontent.com/assets/17575778/20003393/87eac6ec-a286-11e6-81d3-9e28841f94b5.png)

**Comment by sgse** [comment]
Man, habe ich ne tolle Box :) 4streams + einmal TV. Ich höre jetzt auf sonst glüht das Teil noch.
![tv21](https://cloud.githubusercontent.com/assets/17575778/20003669/14177cae-a288-11e6-9c0c-3dacdadf2742.png)

**Comment by jbleyel** [comment]
Hi @Schimmelreiter .. kannst du das mal anschauen?
 -> 417

**Comment by Schimmelreiter** [comment]
Erledigt ;)
Ich hatte ihn hierhin verwiesen. :)

**Comment by jbleyel** [comment]
Ich hab glaub vergessen zu sagen, das ich da nix machen kann weil ich kein Windows habe.
Daher die Bitte an dich.

**Comment by Schimmelreiter** [comment]
Ich kann's nur testen.

Wir hatten doch schon einen IE-Workaround eingebaut, vielleicht muß der einfach nur an mehr Stellen kommen?

**Comment by jbleyel** [comment]
Der 1. Fehler war ein javascript funktion, die der IE nicht kann.
Den 2. Fehler versteh ich nicht.
Da muss der IE genau so reagieren wie alle anderen Browser. (sollte)

**Comment by jbleyel** [comment]
Ich bin jetzt durch. Bitte testen.
Besser geht es leider nicht.

**Comment by Schimmelreiter** [comment]
Von der Funktion her gut.
Aber wenn ich ehrlich bin gefällt es mir gar nicht, die Tuner-Modellbezeichnung nach links zu ziehen.

Kann die nicht wieder nach rechts und dann halt in einer zweiten Zeile die Belegung?

Ich werde an anderer Stelle ein paar Zeilen einsparen:
Marke & Modell können in eine Zeile
Chipset und Frontprozessor ebenfalls (Wobei "Frontprozessor" bei Rückgabewert "None" auch gar nicht angezeigt zu werden braucht)
Distro und Version auch in einer
Plattengröße und freier Platz auch
Hauptspeicher und freier Hauptspeicher auch

**Comment by jbleyel** [comment]
Las mich mal was probieren.

**Comment by jbleyel** [comment]
Das sieht für mich irgenwie doof aus.
Zumindest ohne Trennlinie. 
<img width="565" alt="bildschirmfoto 2016-11-04 um 20 47 05" src="https://cloud.githubusercontent.com/assets/964927/20020109/eb7dc53a-a2cf-11e6-976a-d107c3ffb8b8.png">

**Comment by jbleyel** [comment]
Schöner wirds nicht.
Border kannste vergessen.
<img width="583" alt="bildschirmfoto 2016-11-04 um 21 02 26" src="https://cloud.githubusercontent.com/assets/964927/20020544/131f9dc8-a2d2-11e6-9f50-2e40e227273a.png">

**Comment by jbleyel** [comment]
Final!

<img width="959" alt="bildschirmfoto 2016-11-04 um 21 08 09" src="https://cloud.githubusercontent.com/assets/964927/20020691/da354e62-a2d2-11e6-98ea-d875e551e78a.png">

**Comment by jbleyel** [comment]
Ich sehe gerade das die Version nicht stimmt. Ich hab 9.0.3 auf der Box und nicht 9.0.1.

**Comment by sgse** [comment]
![tv25](https://cloud.githubusercontent.com/assets/17575778/20020821/6a27671c-a2d3-11e6-8b0d-b847d206f8ee.png)
Auch einen anderen Kernel als ich.

**Comment by Schimmelreiter** [comment]
3.14.x ist normal bei der Solo 4k

**Comment by rdamas** [comment]
Bei mir steht auch 9.0.1, hab auch 9.0.3 drauf...

**Comment by Schimmelreiter** [comment]
Die VTi-Version wird aus /etc/vtiversion.info gelesen.
Wenn also bei den Boxinfos was Falsches steht, dann wird das auch dort falsch drinstehen.

**Comment by jbleyel** [comment]
JO hast recht.

**Comment by jbleyel** [comment]
Ich mach den issue hier mal zu mit dem nächsten commit.
