### ISSUE TITLE
Suggestion for box UI

### ISSUE THREAD

**Issue by Priskvark** [E2OpenPlugins/e2openplugin-OpenWebif#207]
In the setup window when entering OpenWebif plugin there is an instruction how to reach the box: OpenWebif url: http://yourip:port

The plugin has already identified the box-ip (In Box Info window) and the port number is defined by the plugin itself.

Suggestion: For the less experienced user it may be better to see the box IP and port number, as it is currently defined/setup in the box.

Then the info could look like something like this: Connect to your box at url:192.168.1.39:80 (or showing all port numbers except the default 80-port)

**Comment by jbleyel** [comment]
Nice request.

BUT
There are 4 different urls if https is enabled and ipv6 is available

**Comment by Schimmelreiter** [comment]
Additionally, if your LAN setup isn't totally fucked up, the easiest way to access your box is using
http://hostname/
i.e.
http://vusolo2/
