### ISSUE TITLE
List satellites in an ordered manner

### ISSUE THREAD

**Issue by AbuBaniaz** [E2OpenPlugins/e2openplugin-OpenWebif#212]
A feature request:
Is it possible for the satellites to be listed based on their orbital position when the satellites tab is clicked? Terrestrial and cable being placed at the top.

At the moment, there is no order and the satellites are all over the place.

Thanks in advance.

![webif sat list](https://cloud.githubusercontent.com/assets/6644489/5013761/3e099cd4-6a88-11e4-8334-f0331f52efad.png)

**Comment by AbuBaniaz** [comment]
Is this the file that needs to be edited?
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/views/ajax/satellites.tmpl

Thanks in advance

**Comment by jbleyel** [comment]
no i don't think so. this is only the template

the values will be collected here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/services.py#L219

**Comment by Huevos** [comment]
Done it. Will commit when fully tested.

**Comment by Huevos** [comment]
Fix on OE-A GiT.

https://github.com/oe-alliance/e2openplugin-OpenWebif/commit/72573c94a53ad159d88c43c9fa8496928762f285

**Comment by AbuBaniaz** [comment]
Please double check this pull request
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/240

**Comment by AbuBaniaz** [comment]
Many thanks.
