### ISSUE TITLE
Use own SSL Certificate 

### ISSUE THREAD

**Issue by timo0** [E2OpenPlugins/e2openplugin-OpenWebif#215]
Is there a opportunity to use a own SSL Certificates  instead of the self-signed Certificate?

**Comment by soysanti** [comment]
don´t work :( help please 



I create my own CA:
openssl req -x509 -newkey rsa:2048 -days 3650 -keyout CAXplotaKey.pem -out CAXplotacert.pem

Create private key and certificate for my domain:
openssl genrsa -des3 -out key.pem 2048
openssl req -new -key key.pem -out certificado.pem

create configservidor.cnf :
basicConstraints = critical,CA:FALSE
extendedKeyUsage = serverAuth

Signing certificate:
openssl x509 -CA CAXplotacert.pem -CAkey CAXplotaKey.pem -req -extfile configservidor.cnf -in certificado.pem -days 3650 -CAcreateserial -sha1 -out cert.pem


Rename (by backup before) files

/etc/enigma2/key.pem
/etc/enigma2/cert.pem


Nothing .... Enigma2 not start, so I replaced it with the backup and at least enigma2 start.


I need help please
thanks

**Comment by stefan1983** [comment]
> If you also put the ca cert as /etc/enigma2/ca.pem and enable HTTPS Client Cert auth in settings you can even login using Client certs signed by the same CA auth.

Hello there, after searching on "how to" configure Client Cert auth, I found this comment here which finally got me in the right direction and able to get it working. 
I didn't find it anywhere else, so might be a good thing for an OpenWebIF WIKI (if there is any!?).

Thanks
