### ISSUE TITLE
problem after reinstalling on openpli italysat

### ISSUE THREAD

**Issue by robvamos** [E2OpenPlugins/e2openplugin-OpenWebif#233]
The problem i have is this   http://forums.openpli.org/topic/34513-error/

tried reinstall clean ecc. the solution is 

Posted 1 August 2014 - 22:29
change the line manually self.putChild('tmp', File('/tmp'))
to
self.putChild('tmp', static.File('/tmp'))
in the file "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/BQE.py", line 270
and it will work and dont update until it is fixed.

but that file is BQE.pyo on my system (is compiled) how can i solve? could you recompile a .ipk with the  modified line ?

**Comment by jbleyel** [comment]
no update since years
