### ISSUE TITLE
Bug: Editing timer events not possible under certain conditions

### ISSUE THREAD

**Issue by Priskvark** [E2OpenPlugins/e2openplugin-OpenWebif#235]
Environment:  Vu+ Solo2, Firefox 34 (IE 11)

Scenario 1: 
Open OWIF in a browser
Chose Autotimer in left menu
Chose Timer button
From the popup window select one of the events by clicking the pen icon (edit)
Bug 1: No edit window shows up but the main browser window returns to top of form.

After this happens
Select Timer in left menu
Select one of the events by clicking the pen icon (edit)
Bug 2: No edit window shows and no other action is visible. The edit window is locked out and not available until you start a new session (new tab or close web browser and then enter OWIF)

Scenario 2: 
Open OWIF in a browser
Chose Timer in left menu
From the list select one of the events by clicking the pen icon (edit)
The edit popup window shows. Close it without any further action
Chose Autotimer in left menu
Chose Timer button
From the popup window select one of the events by clicking the pen icon (edit)
Edit is possible because the edit window has been used in Timer first.

Edit a character in the name and save.
Bug 3: After saving the Autotimer window disappears and the Timer Window opens.
Bug 4: You cannot select the Autotimer Window until you first selected another topic from the left menu.

(Suspected) Bug5: All those status messages ims21 made translatable the other day will not show up anywhere because status messages are no longer displayed in any dialog (that I am aware of).

These are not serious bugs but more of a nuisance.

**Comment by jbleyel** [comment]
!! Strange !!
If i open edit timer in timerlist first then i have no issue.
If i open edit timer in autotimer timer list then i have the same issue. (Bug1,Bug2)

Bug3 and Bug4 are not present on my side. -> Chrome

**Comment by jbleyel** [comment]
This issue should be also closed with the last commits.
