### ISSUE TITLE
Broken transcoding due to changes to STATICBOXINFO['model'] value

### ISSUE THREAD

**Issue by macnuts** [E2OpenPlugins/e2openplugin-OpenWebif#236]
OpenWebif transcoding support is broken in vu+ *'2' family boxes (like my duo2). Other boxes might be affected too.

The problem is **STATICBOXINFO['model']** value in **getTranscodingSupport()** in file **./controllers/models/info.py**, line 363 below:
```python
359. def getTranscodingSupport():
360.        global STATICBOXINFO
361.        if STATICBOXINFO is None:
362.                getInfo()
363.        if STATICBOXINFO['model'] in ("solo2", "duo2", "solose", "vusolo2", "vuduo2", "vusolose", "hd2400", "xpeedlx3", "gbquad", "gbquadplus"):
364.                return True
365.        return False
```
The problem is that **STATICBOXINFO['model']** is **"Duo²"** there due to **model** being decorating at:
```
./controllers/models/owibranding.py:85:         model = procmodel.title().replace("olose", "olo SE").replace("olo2se", "olo2 SE").replace("2", "²")
```
It is part of **GetAllInfo** definition.

It looks like solo2, solose and solo2se are also affected. Moreover, other boxes might be affected as well (see other parts of **GetAllInfo** definition).

I was able to confirm that adding **"Duo²"**  or **"Duo\xc2\xb2"** to the list restored transcoding in OpenWebIf, like in the code below:
```python
359. def getTranscodingSupport():
360.        global STATICBOXINFO
361.        if STATICBOXINFO is None:
362.                getInfo()
363.        if STATICBOXINFO['model'] in ("Duo²", "solo2", "duo2", "solose", "vusolo2", "vuduo2", "vusolose", "hd2400", "xpeedlx3", "gbquad", "gbquadplus"):
364.                return True
365.        return False
```

**Comment by macnuts** [comment]
Thanks for a "quick fix" for vu+ brand. It was quick indeed.

**Comment by Schimmelreiter** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/49d8ab1f2e7c547ea21365904f40876b11f9c400
