### ISSUE TITLE
Feature Request: Bouquet Editor- option to "Add place holder"

### ISSUE THREAD

**Issue by AbuBaniaz** [E2OpenPlugins/e2openplugin-OpenWebif#239]
![request_add place holder](https://cloud.githubusercontent.com/assets/6644489/5619678/01df8246-951c-11e4-8d02-8b11aa3d6c02.png)
Hello, I would like to request an additional feature for bouquet editor. Can we add a button to add place holders in the area marked in picture.

Slight issue is that we cannot see them in openwebif boquet editor. And eventually someone will also ask for a delete option.

Many thanks

**Comment by jbleyel** [comment]
What you mean with "placeholder"?

**Comment by AbuBaniaz** [comment]
Sorry, my mistake. The correct name is "number marker". as shown by the attached picture.
![pli hide marker](https://cloud.githubusercontent.com/assets/6644489/5621178/d5a780a2-952a-11e4-9ff9-2e98060df587.jpg)


OE-A use  #SERVICE 1:832:d:0:0:0:0:0:0:0: and Lraizer's Autobouquets E2 use teh same one. These are invisible in the bouquet but maintain the channel ordering.

**Comment by jbleyel** [comment]
Correct me, if im wrong.
Do you want an additional button "add number marker" to create an 1:832:d:.. service in the selected bouquet.
Are you sure about the 3rd part of the serviceref, is this really a 'd' on each marker or are they different.
The add of these markers should be not a problem.
!! BUT !!
Delete,rename and move of such marker is not possible while these markers are not shown in the list of the bouqueteditor.

**Comment by AbuBaniaz** [comment]
Hi, 
Yes, to add number marker.
Yes, the d is there.

**Comment by Schimmelreiter** [comment]
@jbleyel : The idea behind that is that in some parts of the world people are still addicted to strict number zapping, even for hundreds of channels.
So the channel with the number 262 (on the Sky receiver) has to be channel 262 for them even if dozens of channels in between are missing.

Maybe this can be implemented in a slightly different way without having to show the bogus filler services and still allowing to delete them:
1. Don't add a button to add a filler but instead add a right-aligned button "Toggle number zap view"
2. In number zap view, show the current channel number in front of the channel name and two buttons plus/minus next to the drag/drop anchor:
Plus adds a filler right before the channel, minus removes one filler (until there are no fillers anymore between this channel and the previous real channel.

Example:
![image](https://cloud.githubusercontent.com/assets/2022025/5625409/8d04259e-957a-11e4-861c-e17304c7e267.png)

See that channels for which there are no fillers in between them and the next channel (BBC News HD on that picture) don't have a plus button and channels with no fillers right before them have no minus button (Like NHK World HD on this picture). Channels which are in enclosed by other true channels have neither button (Like RT HD).

**Comment by jbleyel** [comment]
Hi Schimmelreiter, 
the + - buttons in the list are very difficult. It's better to add + and - as button below.
Where can i get these numbers? 
Can i enable this feature in OpenATV?

I think it will be better to show the filler in the list and do not hide them.
Then we can use a - below to remove the selected filler.
The + will be add a filler above the selected channel or filler.

**Comment by Huevos** [comment]
jbleyel is in OpenViX and OpenPLi so it is highly likely it is in OpenATV too.

**Comment by jbleyel** [comment]
i don't find the setting in openatv

**Comment by IanSav** [comment]
@jbleyel:  I would treat the spacer entries exactly like markers.  With markers you have a "(M)" to indicate it is a marker.  For the spacer entries hide them everywhere but in the Bouquet Editor.  In the editor show each entry with a "(S)" (for Spacer).  The entries can be created with a new "Add Spacer" to match the "Add Marker" except there is no need to name the spacer.

Like Markers the Spacers can be removed by selecting them in the list and clicking "Delete".

If you want to optimise the display you can have all adjacent spacers shown as a single entry in the list with the number of spacers in that position shown as a number before the "(S)" label.  E.g. "30 (S)".  If you add a spacer to an existing group of spacers then don't add a line on the display, simply add 1 to the spacer count.  If "Delete" is clicked decrease the count by 1 until all the spacers are removed then remove the spacer line from the display.

If possible the above process could be improved if when the "Add Spacer" or "Delete" buttons are clicked when a line with spacers is selected the user gets a pop up asking how many spacers are to be added or deleted.  If the spacers are moved then the single line moves them all as one group.

This is just a quick outline suggestion on how the user interface could work.

**Comment by jbleyel** [comment]
I will rename the delete button and the delete question to:
"Delete"
"Do you .. delete the selected items?"

Then i wil add a new button "Add Spacer".
 

** Now the Problem:
If i will display the channel numbers i can only show the numbers from 1 to x for each bouquet.

**Comment by Schimmelreiter** [comment]
> ** Now the Problem:
If i will display the channel numbers i can only show the numbers from 1 to x for each bouquet.

Hm?
Where is the problem?

**Comment by jbleyel** [comment]
Normaly sould be the number of the first channel of the second bouquet = last number of the last channel of the first bouquet.
That's the Problem.

**Comment by Schimmelreiter** [comment]
I see.
Ich glaube, in Bochum ist gerade eine Bratwurst geplatzt!

Skip the channel numbers then. Since when OWIF is supposed to be a one man show?
If any of the Britons or Aussies really cares, he will provide a patch/pull request.

The whole concept of letting the provider dictate the channel numbers is entirely weird, why should **we** solve the problems it causes?

**Comment by sgse** [comment]
So, das Internet habe ich durch, zumindest den Erotikbereich :-D . Was mach ich jetzt???

**Comment by Schimmelreiter** [comment]
Ich hab grad meinen Brazzers-Zugang verlängert ...

**Comment by Schimmelreiter** [comment]
In Garmisch ist eine Weiche eingefroren und in Grönland kotzt ein Schlittenhund.

**Comment by jbleyel** [comment]
Hab schon verstanden.
Ich musste den BQE sowieso ändern.
Daher hab ich gleich mal diesen alten issue ausgekramt.

**Comment by jbleyel** [comment]
Was ist sonst noch offen für die 1.1?

**Comment by Schimmelreiter** [comment]
#500 würde ich sagen.

**Comment by Huevos** [comment]
The provider is not dictating the numbering. Some people choose to follow the numbering of the provider. If there is an advert for a program on channel 127, people expect to be able to key in 127 and be transferred to that channel.

**Comment by jbleyel** [comment]
There is a Problem here -> 

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/1.1-DEV/plugin/controllers/BouquetEditor.py#L332

Crash if you call this:
```
service_str = '1:832:D:0:0:0:0:0:0:0:'
eServiceReference(service_str)

```
Don't ask me why?

**Comment by IanSav** [comment]
Sorry I missed the E-Mail about activity in this thread.

The issue of numbering and padding is definitely a local problem for a few markets.  The underlying problem is something for another day.   :wink:

To address the issue of channel numbering and spacing in OpenWebif perhaps you can look at the value of "config.usage.alternative_number_mode" if it is enabled/true then every bouquet starts numbering channels at 1.  This is the only reliable or meaningful way to make spacing generate useful channel numbers.

For OpenWebif why not only allow the number and spacing options only if "config.usage.alternative_number_mode" is set and the first channel in the bouquet has the number 1.

**Comment by Huevos** [comment]
It has nothing to do with alternative numbering. The point is to be able to skip numbers between channels. And also to be able to put hidden seperator bouquets that contain spacers so the next bouquet has the correct number. I.e sky movies is 301 and in movies bouquet and sky sports is in sports bouquet and numbered 401. These should have correct numbers following from first channel in bouquet one. In alterative mode both would be number 1.

**Comment by IanSav** [comment]
Okay, I see the difference.  In Australia we usually start all bouquets at 1 to get the numbering schemes we want.
 I can't wait for the day the Enigma2 captures LCN data as part of the scan.  I described my proposal for handling the issue here: http://www.beyonwiz.com.au/forum/viewtopic.php?p=145826#p145826

**Comment by Schimmelreiter** [comment]
Capturing LCN doesn't help much:
There might be multiple providers on one Sat and several people get multiple Sats.
That results in colliding LCNs.

We have that shit here too, just nobody uses it.
Why would I want to keep stations I never watch on the low numbers and the regular ones on high ones?

**Comment by IanSav** [comment]
@Schimmelreiter: Colliding LCNs should automatically be handled.  Once you have the scans complete simply rename / renumber all the channels as you want and where you want and then the changes should stay as you set them.

**Comment by Huevos** [comment]
> We have that shit here too, just nobody uses it.

Speak for yourself. Lots of people want their bouquets to follow the broadcaster's LCNs.

**Comment by Schimmelreiter** [comment]
Speaking about "here" as in "not there".

**Comment by AbuBaniaz** [comment]
The bouquet editor in openwebif does not automatically create any bouquets.

The purpose of this request was to allow those who want to, the option to to do so. Nobody will be forced to put them in.

**Comment by Schimmelreiter** [comment]
So what?
It's being looked at and WIP.

It's just a bit hard for us that aren't used to programme numbers within the hundreds and endless gaps to consider all the needs of those that use it.

The best would be that someone from the circle of potential users provides a patch or you get what we deem fit for this purpose.

**Comment by jbleyel** [comment]
This issue is not fixed.
I will do one thing first.

checkbox show/hide spacers.

add and move of spacers is not working.

add will crash the box  here :
```
service_str = '1:832:D:0:0:0:0:0:0:0:'
eServiceReference(service_str)
```
 
move will move anything but not the spacer.

mutableBouquetList needs all items to be different.
but the spacers are all the same.

**Comment by Schimmelreiter** [comment]
Could it be that spacers have a counter, like markers do?

**Comment by jbleyel** [comment]
Wieso hast du immer die gleiche Idee wie ich?
Guck mal.

service_str = '1:832:D:%d:0:0:0:0:0:0:'% cnt

**Comment by jbleyel** [comment]
ich teste das gerade.

**Comment by Schimmelreiter** [comment]
Ich seh hier auch grad einen Pull Request hier, den Du zuvor in identischer Form in oe-a gemerged hast.
Merge den bitte auch hier, denn wenn ich später wieder von hier nach oe-a merge, würde ich im Zweifel die Version von hier behalten. ..

**Comment by jbleyel** [comment]
done

**Comment by Schimmelreiter** [comment]
Ist dieses Thema nicht durch?

**Comment by jbleyel** [comment]
Eigentlich JA, der Kollege @AbuBaniaz möge mal Rückmeldung geben.

**Comment by Schimmelreiter** [comment]
@AbuBaniaz 
Is the current spacer support the way you wanted it?

**Comment by Schimmelreiter** [comment]
If not: Re-open the issue :)

**Comment by IanSav** [comment]
If I may contribute a comment on the current implementation (in 1.2).  The feature is fantastic and works very well.  There is one change I would like to request.  The Marker (or Name) records do not consume a LCN number slot in the on screen UI.  By assigning them a number the BouquetEditor it is pushing the number range out by 1 for every marker record displayed.

**Comment by jbleyel** [comment]
The marker should have no number, correct?

**Comment by IanSav** [comment]
I don't think it should but this is AbuBaniaz's request so he should have the final say on what he wanted.   :)

(If you look at a bouquet with markers in the UI you should see a paper clip icon and not a number in the LCN column.)

**Comment by Schimmelreiter** [comment]
"Markers" or "separators" are shown but get no numbers,
"fillers" are not shown but get numbers.

**Comment by IanSav** [comment]
This is the same bouquet as above but seen in BouquetEditor:
![be](https://cloud.githubusercontent.com/assets/6904736/20978288/68e1fb5e-bcfc-11e6-8f1b-212f69d1f3db.jpg)

**Comment by Schimmelreiter** [comment]
jbleyel: Um Dir die Zeit zum Raten zu sparen:
"Terrestrial TV LCN" soll nicht 1 sein, sondern "ONE" soll die 1 sein.

**Comment by jbleyel** [comment]
okay .. sollte kein Problem sein.

**Comment by IanSav** [comment]
Thank you jbleyel.

**Comment by AbuBaniaz** [comment]
Thanks for the work done, I'll need to test it on a build that has it.

**Comment by AbuBaniaz** [comment]
> "Markers" or "separators" are shown but get no numbers,
> "fillers" are not shown but get numbers.
Yes, that is correct. But it seems you have also allocated numbers to the bouquet names.

Enigma2 gives the services cumulatively. So if the first bouquet had a total of 300 services/fillers, the next bouquet should start at 301. The bouquet name and or markers must not be given a number.

Many thanks for the work done so far, but the issue is not resolved.

N.B
Alternative numbering in Enigma2 makes every bouquet start at 1 on OpenATV, OpenVix and OpenPLI .

I have attached a picture of the bouquet on the receiver and the openwebif bouquet editor. 

![bouquets in e2](https://cloud.githubusercontent.com/assets/6644489/20993136/3deca0fa-bce0-11e6-923c-e83624312b97.jpg)

![untitled](https://cloud.githubusercontent.com/assets/6644489/20993141/4228033a-bce0-11e6-8588-3a40155ffe17.png)

**Comment by Schimmelreiter** [comment]
> Yes, that is correct. But it seems you have also allocated numbers to the bouquet names.

Nope, bouquet names do not get a number.
What your screenshot shows is actually a marker/separator too.

**Comment by AbuBaniaz** [comment]
Can you enlighten me as to why it has number 1 please?

This is the entry from the bouquet file
```
#SERVICE 1:64:1:0:0:0:0:0:0:0:
#DESCRIPTION 28.2E -- Movies --
```

**Comment by Schimmelreiter** [comment]
It shouldn't have a number, as it is a marker.
I was just making clear that it **is** a marker and **not** the bouquet name.

The **bouquet name** entry looks like this:
`#NAME Favoriten (TV)`

**Comment by Huevos** [comment]
Has this request been abandoned?

Can channel numbers in OpenWebIF not be made to correspond with the channel numbers that enigma2 uses on the receiver?

**Comment by jbleyel** [comment]
Hi @Huevos, are you kidding me?

**Comment by AbuBaniaz** [comment]
No, he is not kidding you.

**Comment by AbuBaniaz** [comment]
Is there any update on this? Can you at least re-open the issue?

**Comment by jbleyel** [comment]
Spacer Support is integrated.
What do you need more?

**Comment by Schimmelreiter** [comment]
Er spricht von der kack alternativen (= nicht in jedem Bouquet neu beginnenden) Nummerierung.

**Comment by AbuBaniaz** [comment]
Please look at the pictures on post of  08 Dec 2016.
We have made the numbering as if alternate numbering is on.
We are also assigning a number to the first item (marker), when it is not a service/spacer

**Comment by jbleyel** [comment]
We have only 2 small flaws.

A) the marker should have no number
B) every bouquet begins with 1

A - can be easy fixed via javascript on the client side but we need a a reload after every change
Thats the reason why i don't have made this now.

B - very difficult .. only via py on the box .. the OSD numbers are cached in memory and are not accessible.

**Comment by AbuBaniaz** [comment]
B: Can we do the same thing as what settings editors do? Surely if they can read the numbers, we can do it too?

**Comment by jbleyel** [comment]
B:
We need all channels and all bouquets with the correct sort order to get the correct number.
We need to get these information on every change.
This is not the right way for web applications.

You can't compare apples with pears.
This issue is not so easy as you think.

And we need A before we can do B.
