### ISSUE TITLE
 time changed for on/off timer

### ISSUE THREAD

**Issue by Dima73** [E2OpenPlugins/e2openplugin-OpenWebif#243]
http://forums.openpli.org/topic/20164-openwebif-e2openplugins/?view=findpost&p=468824
--- plugin/controllers/models/timers.py
+++ plugin/controllers/models/timers.py
@@ -316,6 +316,7 @@
 			else:
 				timer.disable()
 				effect = "disabled"
+			rt.timeChanged(timer)
 			return {
 				"result": True,
 				"message": _("The timer '%s' has been %s successfully") % (timer.name, effect),

**Comment by jbleyel** [comment]
http://forums.openpli.org/topic/20164-openwebif-e2openplugins/page-71#entry471255

**Comment by jbleyel** [comment]
Is this issue fixed?

**Comment by Dima73** [comment]
maybe yes
