### ISSUE TITLE
Installation / upgrade on Technomate TM-Twin-OE

### ISSUE THREAD

**Issue by olivogt** [E2OpenPlugins/e2openplugin-OpenWebif#246]
Hi - not sure if this is the right place...

Since upgrading the software on my TM-Twin-OE OpenWebif does not stream any more but I have version OWIF 0.1.2 - How can I upgrade to the latest version and hopefully this will fix it...

Thanks,
O.

**Comment by jbleyel** [comment]
Please ask your image provider to build a newer version for you.
