### ISSUE TITLE
Transcoding ET10000

### ISSUE THREAD

**Issue by cobusr** [E2OpenPlugins/e2openplugin-OpenWebif#248]
I want please that the transcoding option in the webif for the et10000

**Comment by cobusr** [comment]
Openpli 4

**Comment by Schimmelreiter** [comment]
Either fixed by https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/f71b5706460b06eb4f389b5fde6218dde10a7497 / #259 or not OWIF related.
