### ISSUE TITLE
Feature Request : Keyboard

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#25]
Hi,

is it possible to integrate a full QUERZ Keyboard View?
I have try something but enigma2 will not do what i want.

WHY? : The input of Text is very difficult with the remote control keys.

Thanks

**Comment by jbleyel** [comment]
Ich hab keine Ahnung wie und wo man das einbauen könnte, daher hab ich den issue hier auf gemacht.
Aktuell sehe ich nur folgende Möglichkeit:

Sende Key Code 3 -> Taste 2  
Sende Key Code 3 (2mal) -> A

Das ist nicht nur doof sondern auch für jede Sprache anders.

Siehe hier -> VirtualKeyBoard.py

**Comment by Schimmelreiter** [comment]
Hilft das hier?
http://lxr.free-electrons.com/source/include/uapi/linux/input-event-codes.h#L74

Wenn Du mal die remotes mit den Key Codes abgleichst, wirst Du feststellen, daß das der verwendete Satz ist. EPG => 0x16d usw.
Da stehen auch die Scancodes für A, B, C, ...
Ist die Frage, ob E2 die grundsätzlich annimmt.

**Comment by jbleyel** [comment]
Nein geht nicht, wenn du eActionMap keyPressed mit irgendetwas ausser den codes von der FB aufrufst, dann kommt ein kleines X.

Das da geht auch nicht.
```

	elif type == "ascii":
		amap.keyPressed(remotetype, key, 4)
```

**Comment by jbleyel** [comment]
Glaub mir, ich hab schon alles versucht.

**Comment by Schimmelreiter** [comment]
Läßt VTi Dich die Fernbedienung auf diese hier umstellen:
https://www.amazon.de/VU-Ultimo-Original-Fernbedienung-Tastatur/dp/B008KA6DJO/ref=sr_1_5?ie=UTF8&qid=1478368891&sr=8-5&keywords=Fernbedienung+Vu%2B
![image](https://cloud.githubusercontent.com/assets/2022025/20032448/5acd4766-a38a-11e6-9fd1-4885f1d3eb32.png)

Die muß ja alle Tastencodes abkönnen.
Den Quälcode dazu bräuchtest Du ...

**Comment by jbleyel** [comment]
Nein, die VU+ FB geht auch nicht.

Kann man eigentlich auf session -> VirtualKeyboard zugreifen.
Schau mal hier...

		from Screens.VirtualKeyBoard import VirtualKeyBoard
		self.session.openWithCallback(self.createDirCallback, VirtualKeyBoard,
			title = _("Please enter the name of the new directory"),
			text = "")

Wenn ich dann auf das Object VirtualKeyBoard komme, dann komme ich der Sache näher.
Was macht openWithCallback ? Und wo ist dann die Instanz VirtualKeyBoard?

**Comment by Schimmelreiter** [comment]
Es ruft "VirtualKeyboard" mit einem Callback auf.
D.h. VirtualKeyboard wird geöffnet und man kann dann allen Scheiß eintippen.
Wenn man das VirtualKeyboard dann schließt, wird "createDirCallback" aufgerufen.

Also praktisch brauchst nicht Du VirtualKeyboard, sondern Du müßtest E2 in diesem Moment eigentlich vorgaukeln, VirtualKeyboard zu sein.

Aber ich glaube, VirtualKeyboard ist eh die falsche Baustelle.
Dabei wird ja eine Tastatur eingeblendet, die eigentlich nur mit den Pfeiltasten und OK bedient wird.

Was Du brauchst ist eine Umschaltung in den Modus, in dem E2 auch die ganzen anderen Scancodes akzeptiert.
Den gibt es unter VTi garantiert, ich weiß nur nicht, ob nur auf der Ultimo oder auch bei den anderen Boxen (Für die man die Ultimo-FB ja auch benutzen und daher nachkaufen kann).

**Comment by jbleyel** [comment]
Die VTi FB habe ich probiert, den Source hab ich mir auch angeschaut.
Wenn du der Box diese FB vorgaukelst, denn siehst du auf der Box im OSD gar kein Keyboard mehr.
Weder das normale noch das Virtuelle.
Das ist keine gute Idee.

**Comment by jbleyel** [comment]
Ich wiederhole mich ungern.  ICH HAB WIRKLICH ALLES SCHON PROBIERT.

**Comment by jbleyel** [comment]
Das einzige was geht ist sende key code x mal um dann den Buchstabe zu bekommen, den man will.
Die Übersetzungstabelle ist in VirtualKeyboard drin.
Ich hab das in meiner App nachprogrammiert.

KEIN WITZ.

**Comment by jbleyel** [comment]
Wenn ich also auf VirtualKeyboard komme oder die Klasse laden kann, dann kann ich den Buchstabe rückwärz übersetzen.

**Comment by Schimmelreiter** [comment]
> Wenn du der Box diese FB vorgaukelst, denn siehst du auf der Box im OSD gar kein Keyboard mehr.
Weder das normale noch das Virtuelle.
Das ist keine gute Idee.

Wieso?
Du siehst dann deshalb keine Tastatur auf dem Bildschirm, weil Du eine in der Hand hast.
Oder zeigt Dir DreckOS/X Deine physische Tastatur irgendwo auf dem Monitor an? :)

**Comment by Schimmelreiter** [comment]
Ich weiß es wirklich nicht besser, aber ich **könnte mir vorstellen**, daß Du gerade den Wald vor lauter Bäumen nicht mehr siehst.

Also: E2 kann ja auch mit Blauzahn-Tastaturen umgehen. Ich weiß nicht, wie es die handhabt, da ich keine habe.
Aber ich wüßte nicht, wieso es bei Benutzung einer physischen Tastatur noch irgendwas einblenden sollte, außer dem Eingabefeld an sich. Man hat die Tastatur ja wahrhaftig in den Fingern.

**Comment by jbleyel** [comment]
Wenn du ein BT oder eine VU+ FB Tastatur hast, dann kann man das nicht im laufenden Betrieb ändern. d.H. wenn du einmal gesagt hast, das du so eine Tastatur hast, dann kannst du die Codes von der normalen FB nicht mehr benutzen.

Entweder / Oder.

Ich will aber UND.

**Comment by Schimmelreiter** [comment]
Das konnte man definitiv, zumindest bei der Vu+ Ultimo FB.
Ich hatte ja als erste Box eine Ultimo ...

Auf der Rückseite ist links unten auch eine Sperrtaste, die die QWERTZ-Tastatur sperrt, damit man nicht versehentlich Tasten darauf betätigt, während man die "normale" Seite benutzt.

**Comment by jbleyel** [comment]
Dann verstehe ich den Source code nicht. Da findet man NIX. Denn Theoretisch müsse die FB über Infrarot einfach zusätzliche Codes senden, die man dann relativ leicht auch simulieren könnte.
Das ist aber offensichtlich nicht so.
Ich meine da brauchte man ein extra plugin.
Das finde ich aber nicht mehr.

**Comment by Schimmelreiter** [comment]
Ich spiel die Tage mal mit meiner Ultimo-FB rum.

**Comment by jbleyel** [comment]
Thanks...

**Comment by Schimmelreiter** [comment]
Also:
Die Ultimo-FB/Tastatur sendet tatsächlich die ganz normalen keystrokes, so wie das bei einer Bluetooth-Tastatur wohl auch wäre.

Prinzipiell bräuchte man für eine Tastatur im OWIF also auch nur die bekannten KEY_CODEs schicken.

Das Problem liegt im Image, das mit den Keycodes nichts macht:
```
15:17:56.393 [   ] driver/rcinput.cpp:23 handleCode 1 22 1
15:17:56.395 {   } Screens/InfoBarGenerics.py:207 actionA KEY: 34 0 KEY_G
15:17:56.577 [   ] driver/rcinput.cpp:23 handleCode 0 22 1
15:17:56.578 {   } Screens/InfoBarGenerics.py:207 actionA KEY: 34 1 KEY_G
15:17:56.579 {   } Screens/Screen.py:151 show [SCREENNAME]  UnhandledKey
15:17:57.791 [   ] driver/rcinput.cpp:23 handleCode 1 1e 1
15:17:57.792 {   } Screens/InfoBarGenerics.py:207 actionA KEY: 30 0 KEY_A
15:17:57.957 [   ] driver/rcinput.cpp:23 handleCode 0 1e 1
15:17:57.958 {   } Screens/InfoBarGenerics.py:207 actionA KEY: 30 1 KEY_A
15:17:57.959 {   } Screens/Screen.py:151 show [SCREENNAME]  UnhandledKey
15:17:59.139 [   ] driver/rcinput.cpp:23 handleCode 1 21 1
15:17:59.141 {   } Screens/InfoBarGenerics.py:207 actionA KEY: 33 0 KEY_F
15:17:59.305 [   ] driver/rcinput.cpp:23 handleCode 0 21 1
15:17:59.307 {   } Screens/InfoBarGenerics.py:207 actionA KEY: 33 1 KEY_F
```

**Comment by jbleyel** [comment]
In der Screen.py gibt es eine Funktion setKeyboardModeAscii . Ich denke da könnte man ansetzen. Ohne den Enigma2 Source anzupassen. Oder bin ich da schon wieder falsch abgebogen.

**Comment by Schimmelreiter** [comment]
Weiß ich ehrlich gesagt nicht :)
Warum bist Du wohl assigned und nicht ich? :)

**Comment by jbleyel** [comment]
Du kennst doch bestimmt jemanden, der an engima2 mit rummacht.
Und der da etwas tiefer drin ist.
Und der mir da evtl. helfen kann.

**Comment by Schimmelreiter** [comment]
Die brauche erstmal ich, um PLi Fehler von 2011/2012 auszubügeln, damit endlich das Transcoding der Quadbox nutzbar wird.
Deshalb reagiere ich so gereizt auf die Jungs.
Vertagen wir das Problem doch erstmal, Milestone ist eh 2.0.0 **g**

**Comment by jbleyel** [comment]
Kein Thema.

**Comment by jbleyel** [comment]
Ich habs gefunden.
http://code.vuplus.com/gitweb/?p=vuplus_dvbapp;a=blob_plain;f=lib/python/Components/config.py

suche nache ->  rckeyboard_enable

**Comment by Schimmelreiter** [comment]
Eigentlich ist da gar nicht viel gefummelt.

Im Abschnitt "vukeymap_us_de = {" werden den Scancodes einfach nur die passenden ASCII-Zeichen zugeordnet und zwar für 4 Ebenen:
- Normal
- (Left) Shift
- AltGr (Right Alt)
- (Left) Shift + AltGr (Right Alt) oder (Left) Alt (Vermutlich die "Fn"-Taste)

Was die da mappen deckt sich aber absolut mit der input.h von Linux:
http://lxr.free-electrons.com/source/include/linux/input.h?v=2.6.38

Ich werde einfach mal versuchen, die entsprechenden Passagen in OpenATV einzubauen, mit ein paar "if" weniger, die sind da nämlich teilweise nur als künstliche Einschränkung.

**Comment by jbleyel** [comment]
Ich denke das hilft mir aber nicht weiter.
Ich will eigentlich folgendes:

```
	amap = eActionMap.getInstance()
	amap.keyPressed(remotetype, 65, 4)
	amap.keyPressed(remotetype, 65, 1)
```
65 = 'A'

Wenn ich dann aber den 1. Kommentar in der Datei lese, dann ist mir alles klar.

https://github.com/openatv/enigma2/blob/3953d04af3a2bbb335e5de3cc3dbd04fdd035539/lib/actions/action.cpp

**Comment by AbuBaniaz** [comment]
Now that IanSav's work on virtual keyboard is in PLi/Vix/ATV as well as those who pick from them, can progress be made on this issue?

**Comment by jbleyel** [comment]
Maybe.
This is my problem.

I wanna call this:

```
amap = eActionMap.getInstance()
amap.keyPressed("ascii", 65, 4)

```
and i expect the letter A as a result in any textinput box via OSD.

Or much better:

```
amap = eActionMap.getInstance()
amap.keyPressedAscii("This is my Text")

```

This needs to implement in "enigma2/lib/actions/action.cpp" and NOT in any python module.
