### ISSUE TITLE
Creating Timer from EPG

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#251]
when is created timer from EPG, could be there displayed screen with parameters and then user must not edit it from Timers again ? In most cases is needed sets times etc...
May be - add new icon side by side existing Timer's icon in EPG and in this way open screen with timer parameters ?

**Comment by jbleyel** [comment]
Hello ims21,
please check out the new epg list and tell me what you think about it.

**Comment by ims21** [comment]
Good works.
-may be, helptext for button could be "Create Timer" instead "Edit Timer".
-could be options for VPS in create timer in one line ?

btw - is it in progress, because it does not create timer yet (EditTimer from EPG) ?
VPS is not set too.

**Comment by jbleyel** [comment]
Thanks.
I think this is a javascript problem
I will take a look.

**Comment by jbleyel** [comment]
Done

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/beae98c2d794143bd115a7334ebf4b42a29e30af

**Comment by ims21** [comment]
vps_safe mod is opaque vps_overwrite.  vps_overwrite is "all is controlling by broadcasting", not safe mod. Safe mod create overwrite flag now. May be, rename text to vps_overwrite or it must be negate. (better would be negate it and there in Autotimer negate it too and rename it to Safe mode too. And could be it in one row on screen ?

And could you add timer icons into MultiEPG too ?

thx.

**Comment by ims21** [comment]
for now I changed it to VPS owerwrite.

**Comment by ims21** [comment]
There is "Timerkonflikt" problem with creating via Timer Bearbaiten - All fields are filed well from EPG, but "Kanal" is "Nichts" and is nothing in channel box. Could you see on it ?

Via Timer hinzufuegen is all right.

What I known - when is not possible create timer (missing kanal), close window with timer and epg, use refresh in webbrowser, go again to same service and then will be kanal filed and all is ok. But when you use next kanal, you must repeat same way ( = refresh and then it works from this time for this channel)

**Comment by ims21** [comment]
1) cosmetic - when is edit existing timer (created from stb) and it has VPS checked, missing checkbox for Safe mode. When is created one timer from OpenWebif with VPS, from this time are checboxes displayed well.

2) try this: TV - select bouquet , then some channel's EPG, create timer, close EPG => you are in Timers. Try choose TV again => fault - nothing happend, not switched to tv bouquets. You must choose Radio and then TV and then are displayed tv bouquets again

**Comment by jbleyel** [comment]
Is this issue gone with my last commit?

**Comment by ims21** [comment]
ad 1 ) fixed by me

ad 2) I cannot to know it, because before it there was not this window :-)

**Comment by ims21** [comment]
ad 2 ) but after Add Timer (without window) it is same.

**Comment by jbleyel** [comment]
i can't reproduce 2)

TV -> open a bouquet -> open a channel epg -> click "edit timer" -> the new timer window appears -> close (not save) -> close epg -> select another bouquet -> open a channel epg -> click "edit timer" -> the new timer window appears again

**Comment by ims21** [comment]
create timer ( and do not use "close (not save)")... then you going into timers, and is not possible get bouquets pressing on TV

**Comment by jbleyel** [comment]
correct!!

but i think the error is not "don't open tv"
the left menu items (tv,radio,timer,recordings,..) are not reloaded if they are currently selected
the display of the timerlist after create timer and close epg list is not needed i think

**Comment by ims21** [comment]
I think, timerlist after creating is good - user can see, if was created timer well.

**Comment by ims21** [comment]
Btw - could be added "Timer Edit" into popup window in MultiEPG too ? There is Add Timer only.

Thanks.

**Comment by jbleyel** [comment]
the multiepg event info pupup needs to be complete redesigned

this need some time and many cup of coffee.

**Comment by jbleyel** [comment]
done

**Comment by Schimmelreiter** [comment]
Darfst auch gerne ins oe-a git mergen :)
Alles außer transcoding.py und plugin.py ist identisch und in plugin.py ist auch nur die überflüssige Auswahl der codepage im oe-a git auskommentiert.
