### ISSUE TITLE
vps and partnerbox

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#254]
@jbleyel : 
could we together to make forwarding vps info into remote timer with partnerbox (via OpenWebif) ? I think, first shot in partnerbox I have, but now must be changed some in openwebif ( your cup of tee ) :-)

**Comment by ims21** [comment]
vps info will be on end of this line in partnerbox: 
sCommand = "%s/web/timeradd?sRef=%s&begin=%d&end=%d&name=%s&description=%s&dirname=%s&eit=0&justplay=%d&afterevent=%s&vps=%s" % (http, service_ref,begin,end,name,descr,dirname,justplay,afterevent,vps)

**Comment by ims21** [comment]
in web.py:  def P_timeradd

		vps = ""
		if "vps" in request.args.keys():
			vps = request.args["vps"][0]

and add vps to end of return addTimer ?

**Comment by ims21** [comment]
could you add some web function returning vps status on local box, (enabled/disabled) ?

**Comment by jbleyel** [comment]
what vps info do you need?
i have add an vps channel status info
-> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/web.py#L660
 
Do you need more?

**Comment by ims21** [comment]
detecting if is VPS spend time to time so much time, i think...

I need, if on remote receiver is installed and enabled VPS plugin (=can be created remote timer with VPS) => if yes, only in this case will be on local receiver displayed "Enable VPS" (yes, yes(safe mode), no ) item in creating remote timer.

**Comment by ims21** [comment]
btw, what happens, if on remote box is not VPS plugin activated/installed ? Is created standard timer ?

**Comment by jbleyel** [comment]
all vps parameter will ne ignored if the vps plugin is not installed

**Comment by ims21** [comment]
great, then is not needed this detecting...

**Comment by jbleyel** [comment]
Is this issue closed?
