### ISSUE TITLE
Rename recording

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#257]
The movierename api will successfully rename the files but not the title of the reording in meta file.
The title in meta file is only the last part of the filename.

**Comment by Schimmelreiter** [comment]
Fixed by assigning jbleyel ;)

**Comment by jbleyel** [comment]
Spassvogel. ;-)

**Comment by jbleyel** [comment]
Ich bin mir nicht sicher ob das reicht:
Zeile 243 in movies.py

```
							if fileExt == '.ts.meta':
								fin = open(src)
								fout = open(srcpath + newname + suffix, "wt")
								for line in fin:
									fout.write( line.replace(name, newname) )
								fin.close()
								fout.close()
							else:
								move(src, srcpath + newname + suffix)
```

**Comment by Schimmelreiter** [comment]
fout.write( line.replace(name, '') )
sollte es auch tun.

Der Titel der aufgenommenen Sendung kommt bis zu 2x vor:
- Einmal als Originaltitel in Zeile 2, der gehört aber m.E. nicht geändert.
- Ein zweites Mal gegen Ende der ts.meta, dort so modifiziert, daß er zum Dateinamen paßt, also z.B. Leerstellen, Fragezeichen und Doppelpunkte zu Underscores umgewandelt.

Diesen zweiten Treffer finde ich aber z.B. nicht in Dateien, die vom Autotimer programmiert wurden ... also kommt E2 offenbar auch ohne diese Angabe aus.

**Comment by jbleyel** [comment]
Ich hab mal ein meine meta Files geprüft.
Bei mir steht der Titel nur ein mal in der 2. Zeile und da ohne Zeit und Sender bei den Aufnahmen mit VTi Image.
Die Aufnahmen mit openatv haben in der 5. Ziele den Titel ohne Leerzeichen noch mal drin stehen.

Nur wenn ich den Titel in der 2. Zeile anpasse, dann stimmt die Anzeige.
Wenn ich den Titel in der 2. Zeile lösche, dann ist der Titel der komplette Dateiname.

Die Frage ist jetzt nur ob Rename, nur den Titel oder den kompletten Dateiname umbenennen sollte.

**Comment by Schimmelreiter** [comment]
In der 2. Zeile ändern und in der 5. löschen, wäre jetzt meine Idee.
OpenATV kommt auch ohne das zweite Auftreten klar und bevor man da einen Fehler reinstrickt läßt man es besser weg.

**Comment by jbleyel** [comment]
so ?
'''
							if fileExt == '.ts.meta':
								lines = []
								with open(src, "r") as fin:
									for line in fin:
										lines.append(line)
								lines[1]=newname
								lines[4]=''
								with open(srcpath + newname + suffix, 'w') as fout:
									fout.write('\n'.join(lines))

'''

**Comment by jbleyel** [comment]
Done

**Comment by Schimmelreiter** [comment]
Darfst auch gerne ins oe-a git mergen :)
Alles außer transcoding.py und plugin.py ist identisch und in plugin.py ist auch nur die überflüssige Auswahl der codepage im oe-a git auskommentiert.

**Comment by jbleyel** [comment]
Done

**Comment by jbleyel** [comment]
Auf dem Feed für openatv stimmt was mit dem openwebif nicht ganz.
Da fehlen 3 Bilder.

**Comment by Schimmelreiter** [comment]
Wie meinen?
Aber im oe-a git sind sie drin?
Welche Bilder denn überhaupt?

**Comment by jbleyel** [comment]
Im oe-a sind sie drin.
Seit gestern.

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/e2openplugin-OpenWebif/commit/805578fa098735fd0b667e1e0f9ef6bcaea503c5

**Comment by Schimmelreiter** [comment]
Der OpenATV-Feed ist seit gestern platt:
http://www.opena.tv/allgemeine-informationen/14158-europa-openatv-server-ist-gerade-info-15-02-2015-23-00-uhr.html

D.h. das OpenWebif in OpenATV ist auch erst einmal noch von vorgestern.
