### ISSUE TITLE
Issue streaming recordings OpenWebIF ET10000

### ISSUE THREAD

**Issue by itsjohan** [E2OpenPlugins/e2openplugin-OpenWebif#259]
After flash this weekend I cannot anymore stream recordings from OpenWebIF on my ET10000, error as in attached image. Stream of live TV works OK.
Version: OWIF 0.4.6, openpli 4.0
Driver date: 3.14.16+20141029-r0.5 
Kernel version: 3.14.16 
Gui version: 2015-02-21 

![stream_error](https://cloud.githubusercontent.com/assets/11157960/6326410/a448de96-bb51-11e4-9c61-05eac2437153.png)

**Comment by jbleyel** [comment]
Link #248 #247

**Comment by jbleyel** [comment]
What happens with openpli and et1000.
Is this a real oe-openwebif issue or should this issue closed with the openpli fork?

**Comment by jbleyel** [comment]
The device request arg is missing.
Why?

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/public/js/openwebif.js#L1130

**Comment by Schimmelreiter** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/f71b5706460b06eb4f389b5fde6218dde10a7497

**Comment by itsjohan** [comment]
Thank you very much, it is working OK now !

**Comment by Schimmelreiter** [comment]
No problem.
The impossible will be handled immediately,
miracles take a bit longer.
Witchcraft will be practised on request.
;)
