### ISSUE TITLE
Feature Request: Timer settings: TimerType 'Zap and Record'

### ISSUE THREAD

**Issue by Cebenpeter** [E2OpenPlugins/e2openplugin-OpenWebif#260]
Hello,

on my Box (Edision Optimuss 3+) there is a third option of TimerType: 'Zap and Record'. I use this option to record encryptet TV-channels like german Sky. The recorded files are always encrypted with only 'Record' as timertype . 
Unfortunately the OpenWebif timer programming does'nt have this option. It is possible to add this option to the timer settings? 

In the timers.xml the option 'always_zap' has set to 1. 

Regard
Steffen

![sc](https://cloud.githubusercontent.com/assets/11194541/6372559/606fdc0a-bd05-11e4-9777-4b00772a416f.jpg)

**Comment by jbleyel** [comment]
coming soon

**Comment by Cebenpeter** [comment]
Sounds good!

Thanks
Steffen
