### ISSUE TITLE
SF8 HD octagon image

### ISSUE THREAD

**Issue by JanGruuthuse** [E2OpenPlugins/e2openplugin-OpenWebif#264]
box is nearly identical to xp1000 and is recognized as xp1000s in OpenPLi 4.0 -> Infos -> Box Info
Please find attached image (xp1000s.jpg) of this box for eventual inclusion on:
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/public/images/boxes
![xp1000s](https://cloud.githubusercontent.com/assets/5527586/6868569/f0fdeb56-d48c-11e4-911c-6d0b103eea5c.jpg)

**Comment by Schimmelreiter** [comment]
Then please ask OpenPLi then to include the box, if they didn't do so already.
Box images and remotes should be provided by the teams building for them.
