### ISSUE TITLE
Streaming Authentication

### ISSUE THREAD

**Issue by Mega93NoName** [E2OpenPlugins/e2openplugin-OpenWebif#265]
Hi Guys,

when I set a password for Streaming, i have the problem, that only the Windows Media Player on Windows and the Totem Video Player on Linux works. The VLC Player won´t accept the right username and password, even if I use older versions. I think I have tested more than 30 Versions. Other players have the same problem, that they can´t indicate the streaming informations.... 

Next problem with the streaming authentication: If it is turned on, it is not possible to use the transcoding. Only the default port 8001 without transcoding is working.

I have 2 GigaBlue HD Quad Plus running in my local network ;) When I want to use the GigaBlue IPBox, they won´t find any Streaming Server if I activate the Streaming Authentication. Only if it is dissabled, it is possible to find the Server Box. It is possible to import the bouquets via FTP, but than I can´t get the stream anyway.

If I can help, please tell me, what to do ;) Sorry for my bad english ;)

**Comment by Schimmelreiter** [comment]
Please give more details about your setup (Box, image used).

Also try the following:
When vlc prompts for the password, enter it again and again, do not stop before the 20th or even 30th attempt.
Does it ever succeed?
If so: This is a known bug in E2s streaming broken by PLi but used in about all images nowadays.
