### ISSUE TITLE
feature request: add timeline EPG 

### ISSUE THREAD

**Issue by B3rt** [E2OpenPlugins/e2openplugin-OpenWebif#267]
Is it possible to add timeline EPG?

Most boxes or software also have an so called timeline EPG (horzontal view) of the EPG, so each channel on 1 horizonal line with a vertical time line.

For example see:
https://tvheadend.org/attachments/download/1775/epg-timeline-mockup.jpg

Is it possible to add this to webif also?

**Comment by gomble** [comment]
i want that feature too

**Comment by gomble** [comment]
Is this feature planned ?

**Comment by jbleyel** [comment]
Close with https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/d73f8d94f12393584d064f4c51b807d2e2624225
