### ISSUE TITLE
Maturity level - No way to stream/switch via Webif

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#268]
Now that the maturity level (Kindersicherung) in OpenWebif actually works, you can not switch to or stream channels with active protection anymore.

To-Do:
Add a PIN pop-up.

**Comment by jbleyel** [comment]
Bitte unten ausfüllen.

Kindersicherung ist an:
Sender A ist gesperrt
Sender B nicht

Was passiert im Moment im Openwebif
Zap zu A -> ...
Zap zu B -> ...

Start Stream von A-> ...
Start Stream von B-> ...

Was soll passieren im Openwebif
Zap zu A-> ...
Zap zu B-> ...

Start Stream von A-> ...
Start Stream von B-> ...

**Comment by Schimmelreiter** [comment]
Ist eher über unterschiedliche Linux-User zu lösen.

Ein Grundgerüst habe ich in oe-a schon eingebaut, Samba und vsftpd kennen da root und "kids".
kids kann keine Dateien/Verzeichnisse mit mode 700 erreichen, root schon.

Das müßte man analog auch für Sender machen, die in keinem Bouquet sind und für Sender, die blacklisted sind.

**Comment by Schimmelreiter** [comment]
Vorerst ist der ganze Kindersicherungskram in E2 einfach nur Müll.
Wenn von einem blacklisted Sender aufgenommen wird, muß z.B. auch die Aufnahme blacklisted sein.

Bevor das nicht ist, kann man den Pipifax eigentlich auch ganz rauslassen.
