### ISSUE TITLE
cosmetic - toggle standby and red/green button

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#269]
toggle standby from menu change red/green button (top-right) after some time and not immediately

**Comment by jbleyel** [comment]
Hi @ims21 , do you switch to/from standby inside the openwebif or via other things?

**Comment by Schimmelreiter** [comment]
From menu = Über das Menü, also auf der Box selber.

**Comment by jbleyel** [comment]
Dann wird das nix.
Der Refresh ist 15 Sekunden.
Das sollten wir auch so belassen oder sogar Vergrössern.

**Comment by Schimmelreiter** [comment]
@ims21: The refresh interval for the box state (changed elsewhere than in OWIF) is 15 seconds.
It should remain that high or even be increased for responsiveness and reduced system load.
