### ISSUE TITLE
Exeption at hdd.findmount() in info.py

### ISSUE THREAD

**Issue by blackoutsystem** [E2OpenPlugins/e2openplugin-OpenWebif#271]
With the new version an exception from type AttributeError occurs 'Harddisk Instance has no Attribute findMount' at the start. The error is in the module info.py 

/usr/lib/python2.7/site-packages/twisted/web/server.py, line 132 in process
130    try:
131      resrc = self.site.getResourceFor(self)
132      self.render(resrc)
133    except:
/usr/lib/python2.7/site-packages/twisted/web/server.py, line 167 in render
165    """
166    try:
167      body = resrc.render(self)
168    except UnsupportedMethod, e:
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py, line 155 in render
153                                else:
154                                        if self.withMainTemplate:
155                                                args = self.prepareMainTemplate()
156                                                args["content"] = out
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py, line 202 in prepareMainTemplate
200                ret['boxname'] = getBoxName()['boxname']
201                if not ret['boxname'] or not ret['customname']:
202                        ret['boxname'] = getInfo()['brand']+" "+getInfo()['model']
203                ret['box'] = getBoxType()
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/info.py, line 273 in getInfo
271        info['hdd'] = []
272        for hdd in harddiskmanager.hdd:
273                dev = hdd.findMount()
274                if dev:

I'm using a dm800hd with an internal HDD. The image used is newenigma2 v4.0.12 from January  2015.
The Hdd is mounted, recording on HDD is possible.

Do you need more information?

With kind regards,

Mr. Black

**Comment by jbleyel** [comment]
Is this issue fixed?

**Comment by jbleyel** [comment]
Please reopen if the issue still exist.
