### ISSUE TITLE
there are two bugs(authentication streaming and json UnicodeDecodeError)

### ISSUE THREAD

**Issue by osj8876** [E2OpenPlugins/e2openplugin-OpenWebif#272]
bug 1
When i click the icon in webif for transcode using my iPhone
It shows this line:
http://192.168.100.137:8002/1:0:1:CA:1:1:822B84:0:0:0: (authentication for streaming enable NO)
http://192.168.100.137:8002/1:0:1:CA:1:1:822B84:0:0:0: (authentication for streaming enable YES)

authentication for streaming enable "NO" is streaming ok. but authentication for streaming enable "YES" is not streaming. 
Is not that putting the username and password to create a response? like below 
http://username: password@192.168.100.137:8002/1:0:1:CA:1:1:822B84:0:0:0:
---

bug 2
I think there is a problem with the latest commit (20ccadc28c79ef1307c8b4292a0d1c42cd555994)
@@ -150,8 +144,13 @@ def getAllInfo():
                procmodel = f.readline().strip()
                f.close()
                model = procmodel.upper().replace("GBQUAD", "Quad").replace("PLUS", " Plus")
-       elif fileExists("/proc/stb/info/vumodel"):
-               brand = "Vu+"
-               f = open("/proc/stb/info/vumodel",'r')
-               procmodel = f.readline().strip()
-               f.close()
-               model = procmodel.title().replace("olose", "olo SE").replace("olo2se", "olo2 SE").replace("2", "<B2>")   <<<<<<<<<---------------------- **********\* I think part of the problem

elif fileExists("/proc/stb/info/boxtype"):
-               # boxtype exists on nearly every E2 box, if we have nothing better for detection we need to analyse its content
              f = open("/proc/stb/info/boxtype",'r')
              procmodel = f.readline().strip().lower()
              f.close()

If i access "http://192.168.100.137/api/deviceinfo", exceptions.UnicodeDecodeError occur. 
below error message on the web browser.
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py:132 in render
131 request.setHeader("content-type", "text/plain")
132 request.write(json.dumps(data))
133 request.finish()

could you explain this problem? 

thank you.

**Comment by jbleyel** [comment]
Bug 2 is not reproducable.

Bug 1 is not fixable / user and password as string are not available.
