### ISSUE TITLE
No bouquet full list ParentalControl protection

### ISSUE THREAD

**Issue by verbal666** [E2OpenPlugins/e2openplugin-OpenWebif#276]
Hi guys.
When i protect a full bouquet with a P.C. code, and a get it ON on Webif

http://i58.tinypic.com/6i905s.jpg

protection is ok on single channels, but not in bouquet link.

I mean, single channels at right are correctly protected, not the full bouquet (at left), opening this link Webif permit to load the full channels bouquet without protection.

http://i57.tinypic.com/2unzvjr.jpg

Thanks.

**Comment by jbleyel** [comment]
Hello @verbal666 , your pictures are no longer available.

**Comment by Schimmelreiter** [comment]
Let's handle this as a variant of #283
