### ISSUE TITLE
Chance for some new links in Openwebif?

### ISSUE THREAD

**Issue by fidelcastro54** [E2OpenPlugins/e2openplugin-OpenWebif#277]
HI.
Is it possible to get new Links under extras e.g. to the Oscam WebIf and to the webradiofs?

Thx 
Fidelcastro

Btw. the vu_duo2.png must be copied manually? Ist that normal?

**Comment by jbleyel** [comment]
possible? YES.
BUT: the links should only set visible if the target exists
e.g. lcd4linux

**Comment by MDXDave** [comment]
@fidelcastro54 try [ModernWebif[(https://github.com/MDXDave/ModernWebif), fork of OpenWebif with themed style.

**Comment by jbleyel** [comment]
Oscam is now inside.

For all other please open a new issue with all needed information.

The image problem is not related to openwebif itself.
You need to contact your image provider.
