### ISSUE TITLE
Problem with timer for streams

### ISSUE THREAD

**Issue by betacentauri** [E2OpenPlugins/e2openplugin-OpenWebif#280]
I have recognized that timer for streams are not created properly. 
E.g. serviceref is:
#SERVICE 1:0:0:000:0:0:000:0:0:0:http%3A//blablablabla.bla%3A33221/bla.ts
#DESCRIPTION: Test

OpenWebIf creates this timer:
<timer begin="1434189302" end="1434192902" serviceref="1:0:0:0:0:0:0:0:0:0:" repeated="0" name="dddd" description="" afterevent="auto".....
So stream URL is deleted.
When you remove line 136 in plugin/controllers/models/timers.py "unquote(serviceref)" it works properly.

I looked into E2 code. OpenWebIf reads servicerefs. These servicerefs are quoted by E2. When you create timer you create new ServiceReference. E2 excepts a quoted serviceref (see in E2 lib/service/service.cpp), but you unquote it before. So E2 sees ":" in stream URL as delimiter.

I saw that unquote was added because of this issue:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/18

**Comment by Schimmelreiter** [comment]
You are likely to find a valid fix faster than me :)
But please do not break alternatives in the process ...

**Comment by betacentauri** [comment]
Fast fix would be removing unquote. But it seems that alternatives need it. Problem is that I have not much knowledge about alternatives...

**Comment by jbleyel** [comment]
You can only remove the unquote if you have detect a stream ref. 
e.g if http in sref then to not unquote else do unquote

**Comment by Schimmelreiter** [comment]
It's easy:
#SERVICE 1:134:1:0:0:0:0:0:0:0:FROM BOUQUET "alternatives.RTLHD.tv" ORDER BY bouquet

An alternative will always have 134 as second element.
On the other hand, programming timers for alternatives works and the resulting timer looks like this:

<timer begin="1434380100" end="1434387900" serviceref="1:134:1:0:0:0:0:0:0:0:FROM BOUQUET &quot;alternatives.VOXHD.tv&quot; ORDER BY bouquet" repeated="31" name="Mein himmlisches Hotel" description="Robert Neubauer:Der Potsdamer Makler Robert Neubauer bekommt es heute mit einer geballten Ladung Frauenpower zu tun. Die Femen Aktivistinnen Zana Ramadani und Ksenia Porechina wollen gemeinsam mit einem Freund eine WG gründen, am liebsten mitten in Berlin. Aber die Besichtigung wird schnell zur Nebensache, denn der Makler möchte mehr wissen über die Damen. Schließlich haben sie schon vor Angela Merkel, Wladimir Putin und Heidi Klum oben ohne für die Rechte der Frauen protestiert. Robert Ne" afterevent="auto" eit="21741" tags="Mein_himmlisches_Hotel" disabled="0" justplay="0" always_zap="0" descramble="1" record_ecm="0" isAutoTimer="0">

So I would say timers for streams should behave identical to make things consistent.

**Comment by Schimmelreiter** [comment]
IMHO the solution would be to urlencode the URL and urldecode it inside E2 when needed/timer starts.
Probably that's even the reason why it's called urlencode/decode ;)

**Comment by betacentauri** [comment]
Detecting stream ref is not sooo easy and reliable. I'm working on IPTV recording in E2. So it could be http://, rtmp://, rtsp://,.... and so on.
I try to find the reason why alternatives need other processing than stream refs. Currently I see no reason why.

**Comment by Schimmelreiter** [comment]
And simply URLdecoding the serviceref wouldn't be an option?
I think you have to URLdecode anyways, for the :// in every URL ...

**Comment by betacentauri** [comment]
I have added alternative via E2. E2 has created a file named 
alternatives.das_erste.tv
Without "serviceref = unquote(serviceref)" line everything works fine. Timers for alternatives and streams can be created. 

Then I read again your old issue: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/18
I saw that you have an alternative filename which contains uppercase characters. So I tested it by renaming the file to: alternatives.DAS_erste.tv
With uppercase characters it don't work (e2 get into endless loop). But also with "serviceref = unquote(serviceref)" line it don't work. But I don't know why. E2 works itself works properly with uppercase chars. I also see in JSON data http://et8500/api/getallservices the correct name:
{"servicereference": "1:134:1:0:0:0:0:0:0:0:FROM BOUQUET \"alternatives.DAS_erste.tv\" ORDER BY bouquet", "servicename": "Das Erste"}
But when I debug the timer box in OpenWebIf I can see that it uses "alternatives.das_erste.tv". So everything in lower case. Which part converts the name? I don't see it.

**Comment by Schimmelreiter** [comment]
Simple: It's not inside OWIF.
<timer begin="1434391800" end="1434396000" serviceref="1:134:1:0:0:0:0:0:0:0:FROM BOUQUET &quot;alternatives.**RTLCrimeHD**.tv&quot; ORDER BY bouquet" repeated="1" name="Person of Interest" description="Steuerung-Alt-Löschen" afterevent="auto" eit="5578" tags="" disabled="0" justplay="0" always_zap="0" descramble="1" record_ecm="0" isAutoTimer="0">

**Comment by betacentauri** [comment]
My fault.... I didn't restart my browser and old serviceref was in cache. So no problem with uppercase chars.
I have created pull request (my first I hope it's ok). I have tested with alternatives and streams and it seems to work.

**Comment by Schimmelreiter** [comment]
If it doesn't, the eternal hate of my wife will follow you ...

**Comment by betacentauri** [comment]
Oh, oh ... ;-)
I hope I have tested everything (timer create, edit, status toogle, delete). Well, you can revert quickly if something don't work.
