### ISSUE TITLE
No Record/Play-Pause/Stop/FF/RW buttons on the Webif Remote Control

### ISSUE THREAD

**Issue by polkwan** [E2OpenPlugins/e2openplugin-OpenWebif#282]
Hi all,
 
As I tried to mention it in the title and in this topic on OpenPli.org (http://forums.openpli.org/topic/38245-no-recordplay-pausestopffrw-buttons-one-the-webif-remote-control/), I've got a small problem with the Remote Control on the Webif.
 
The full remote doesn't have those buttons and I find this a bit annoying. 
 
Is it normal ? Is there smth I can do ?
 
Thank you in advance for considering my issue ;)

PS: I'm on Dreambox 8000 and I know it's not really offcially supported anymore...

**Comment by Schimmelreiter** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/f419d7aefddf8ad03cf8e23a97e61d3b9f017ee6
