### ISSUE TITLE
Autotimer encoding

### ISSUE THREAD

**Issue by Dima73** [E2OpenPlugins/e2openplugin-OpenWebif#285]
AT options "EPG encoding" value always ISO8859-15.
Why is that?

**Comment by Schimmelreiter** [comment]
It's not really ...
There is a bug across all pages of OWIF which makes a lot of dropdown selections always appear to be set to the first option rather than the truely selected one.
So it's a cosmetical bug ... although a truely annoying one.

**Comment by Dima73** [comment]
Storing a value does not work either.
We can do so:
https://schwerkraft.elitedvb.net/plugins/scmgit/cgi-bin/gitweb.cgi?p=enigma2-plugins/enigma2-plugins.git;a=commit;h=941663bae9b9b908e0137b99bd2750fc13a9acf8

**Comment by jbleyel** [comment]
Sure?
Where are the combo boxes with wrong start value.
The encoding can be removed.

**Comment by Schimmelreiter** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/38ef8535b27fd20539f198e0db87eaef75242231
