### ISSUE TITLE
Autotimer location

### ISSUE THREAD

**Issue by Dima73** [E2OpenPlugins/e2openplugin-OpenWebif#287]
If location autotimer not in config.movielist.videodirs.value, this location not in option list.
The same problems of the standard timer.

More in detail here https://sourceforge.net/p/openpli/enigma2/ci/0eb39a5fb3c9e6fe60b167b64f5b5c012c7ae33a/

It can be fixed?

**Comment by Dima73** [comment]
and detail here
https://sourceforge.net/p/openpli/plugins-enigma2/ci/e76dec4ed452b055b5a46d70315a171bb49cabae/

**Comment by Dima73** [comment]
I tried to fix this problem yourself, but nothing came of it.
plugin/controllers/views/ajax/at.tmpl
								<br><label for="Location">$tstrings['at_location']:</label>
								
								<input type="checkbox" name="Location" id="Location" value="" class="checkbox ui-widget-content ui-corner-all">
									<span id="LocationE">
									<label for="location"></label>
									<select name="location" id="location">
										#for $location in $locations
											<option value="$location">$location</option>
										#end for
									</select>
									</span>
Where is the variable with the current value this autotimer?

**Comment by jbleyel** [comment]
The location from the autotimer.xml is set in javascript and not python template.
Please check your autotimer.xml if there is a custom location.

**Comment by Schimmelreiter** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/884906afd425f10254bc1b2c094328def1564a7b
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/6056ecd0bbf17b7316deab617ea7f3d477f4fd2b
