### ISSUE TITLE
Internet Explorer 11: Symbols in Timer view are not correct

### ISSUE THREAD

**Issue by Ted0815** [E2OpenPlugins/e2openplugin-OpenWebif#292]
In the webinterface under "Timer" the 3 symbols for edit, delete and deactivate are not shown correct. Firefox and Chrome are showing those symbols correct, but not the new Internet Exlorer.
![timer](https://cloud.githubusercontent.com/assets/13438009/8806083/3a3dce0a-2fd5-11e5-98db-54c654736dd0.PNG)

**Comment by jbleyel** [comment]
is this the only problem with IE11?
do you have enabled any compat mode in IE11?

**Comment by Ted0815** [comment]
I have disabled the Option "Show Intranetsites in compatibility view". If I leave this enabled (which is the standard) then the Webinterface is not working at all. No menu is working.
Only by disabling this option 
![compatibility view](https://cloud.githubusercontent.com/assets/13438009/9021637/3e7851ea-384d-11e5-8f6c-5afd8848094b.PNG)
it is usable at all, but then the corrupt Icons appear in the timer view.
Best would be if you could fix both the regular view as well as the compatibility view.
BTW: The the Edge-Browser from Windows 10 is working perfect.

**Comment by jbleyel** [comment]
The Icons are new in Version 1.0
<img width="81" alt="bildschirmfoto 2016-10-14 um 21 36 59" src="https://cloud.githubusercontent.com/assets/964927/19400411/67b0b200-9256-11e6-9eec-31e727fcf869.png">

**Comment by Schimmelreiter** [comment]
I don't really know why there is a strong tendency to develop GUIs "back to the 80s" now:
![image](https://cloud.githubusercontent.com/assets/2022025/19408857/2d2bce3c-92c7-11e6-8050-9e96f39bd644.png)
