### ISSUE TITLE
Add AutoTimer from Multi EPG doesn't work

### ISSUE THREAD

**Issue by ArowonA** [E2OpenPlugins/e2openplugin-OpenWebif#293]
When you click the AT button from within the EPG page nothing happens, looks like it tries to load in the content_container element which doesn't exist in the multiepg2 file.

**Comment by jbleyel** [comment]
I think we should remove the Autotimer Button in fullscreen Mutli EPG.
The Multi EPG as extra window don't have all objects.
The inline Mutli EPG works as expected.

**Comment by Schimmelreiter** [comment]
Adding regular timers neither works ...
... I think we should fix that, rather than removing the buttons.

**Comment by ArowonA** [comment]
That worked great cheers. 

one minor thing, I don't if you prefer I open a new issue, but if you try and add an autotimer and the program contains a ' then it fails.

Thanks again

**Comment by jbleyel** [comment]
this is a different issue and this could be a problem on more than one place in openwebif
