### ISSUE TITLE
Unable to scroll the channel list on an iPad

### ISSUE THREAD

**Issue by WanWizard** [E2OpenPlugins/e2openplugin-OpenWebif#294]
See screenshot. There is no scrollbar on the right, making it impossible to scroll down the channel list.

![image1](https://cloud.githubusercontent.com/assets/456954/9748057/df1ccf0a-5679-11e5-8487-ddd7476dc17c.PNG)

**Comment by HDMU** [comment]
you have to use two fingers to scroll in a frame

**Comment by jbleyel** [comment]
"Achtung Schleichwerbung" 
You can also use my app. ;-) 
-> https://itunes.apple.com/us/app/e2remote-pro-for-dreambox/id574507135?l=de&ls=1&mt=8

**Comment by jbleyel** [comment]
Please use the latest version and reopen if you stil have this problem.
