### ISSUE TITLE
epgsearchcaps in searchMenu

### ISSUE THREAD

**Issue by iwkse** [E2OpenPlugins/e2openplugin-OpenWebif#302]
Hi,
I was trying to update my OpenWebif plugin on a cloudibox3 but I get this error:

NameMapper.NotFound: cannot find 'epgsearchcaps' while searching for 'searchMenu'

Do you have an hint?

Regards

**Comment by jbleyel** [comment]
we need the complete error

**Comment by jbleyel** [comment]
Please reopen with the full error.
