### ISSUE TITLE
Returning wrong number of locations?

### ISSUE THREAD

**Issue by cowst** [E2OpenPlugins/e2openplugin-OpenWebif#303]
Hi,
I was trying to figure why I could not refresh the list of my movies folders from DreamDroid and I realized that the receiver sends back only 5 of them.

http://myIp/web/getlocations

/hdd/movie/cartoons/
/hdd/movie/cartoons/Toy story/
/hdd/movie/series/Die fantastische Welt von Gumball/
/hdd/movie/storage/
/hdd/movie/toWatch/

Can this be related to this plugin?
If not, any hint to try to narrow down the issue?

**Comment by jbleyel** [comment]
The getlocations api is a result of the file /etc/enigma2/movielocations and NOT a list of folders.
