### ISSUE TITLE
Red and Yellow button is wrong for ET9200

### ISSUE THREAD

**Issue by demosat** [E2OpenPlugins/e2openplugin-OpenWebif#309]
Hi,
On my ET9200, the functions of the red and yellow buttons openwebif are not the same as that of the remote control.
Please watch screen capture video deposit on Openpli forum.
http://forums.openpli.org/topic/39466-openwebif-yellow-button-et9200/
http://forums.openpli.org/topic/39482-openwebif-red-button-et9200/
Regards.

**Comment by jbleyel** [comment]
Here are the correct remote codes of enigma2

red = 398
green = 399
yellow = 400
blue = 401

If your box do other things then you should check your box image.
The openwebif remote control is correct.

**Comment by demosat** [comment]
De : Jörg Bleyel <notifications@github.com>
 À : E2OpenPlugins/e2openplugin-OpenWebif <e2openplugin-OpenWebif@noreply.github.com> 
Cc : demosat <samy_laglue2000@yahoo.fr>
 Envoyé le : Vendredi 20 novembre 2015 18h03
 Objet : Re: [e2openplugin-OpenWebif] Red and Yellow button is wrong for ET9200 (#309)
   
Here are the correct remote codes of enigma2red = 398
green = 399
yellow = 400
blue = 401If your box do other things then you should check your box image.
The openwebif remote control is correct.—
Reply to this email directly or view it on GitHub.  
This is info on my stb.But this problèm existe for long time, i have verified with different backup image.

**Comment by demosat** [comment]
Hi,
Please contact another utilisateur ET9000 ou ET9200 and test this commande. 
this commande start timeshift.

http://_IP_OF_YOUR_STB_/web/remotecontrole?commande=400 

Regards



      De : Jörg Bleyel <notifications@github.com>
 À : E2OpenPlugins/e2openplugin-OpenWebif <e2openplugin-OpenWebif@noreply.github.com> 
Cc : demosat <samy_laglue2000@yahoo.fr>
 Envoyé le : Vendredi 20 novembre 2015 18h03
 Objet : Re: [e2openplugin-OpenWebif] Red and Yellow button is wrong for ET9200 (#309)
   
Here are the correct remote codes of enigma2red = 398
green = 399
yellow = 400
blue = 401If your box do other things then you should check your box image.
The openwebif remote control is correct.—

**Comment by ims21** [comment]
I think, it is wrong setting for RC of this model in OpenWebif imho... Same problem was with DM800SE. I think, cca one year ago I made it for DM800SE. But it is so much time ago... I think, there must be set similar flag ... look for it, I am very busy.

**Comment by jbleyel** [comment]
Dissagree!
all other html files for the remotes have also
red = 398
green = 399
yellow = 400
blue = 401

i have checked dmm.html dmm1.html dmm2.html vu_duo2.html vu_normal.html et9x00.html

**Comment by jbleyel** [comment]
https://github.com/OpenPLi/enigma2/blob/d6900189761037d175ef6b764c1e2bf02950f418/keyids.py

**Comment by demosat** [comment]
They are a problèm, because i have another STB AZBOX with image openrsi.
The key openwebif red = 398, green = 399, yellow = 400, blue = 401 is correct.
But on Xtrend ET9x00 the key red = 398 and yellow = 400 is wrong fonctionnality.

**Comment by jbleyel** [comment]
Then i will say, the problem is on the image.
All other boxes and images will work with these key codes.
Why should we change the key code for this image?

The only solution is:
Fix the openpli fork of openwebif.

**Comment by ims21** [comment]
@jbleyel : it was nothing about keykodes, but some about "extended" x standard RC. "Extended" RC has standalone play, pause ... buttons, standard RC has it under color butons. And when is used box with "extended" RC, still is used matrix for standard RC.

**Comment by ims21** [comment]
I think, it is there:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/58d0eef9a18249c1d7891b12eccbb37a77626d54

and

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/fc0e278c239360b7694b305c405bf8e67c874dfa

**Comment by jbleyel** [comment]
d´accore

**Comment by pr2git** [comment]
I just test and as suggested by IMS, adding "et9000" to the file: plugin/controllers/models/control.py line 116 does the trick for me on my ET9000 can you please add it to the list.
We need to know which model is returned for demosat ET9200 to add it too.
Thanks

**Comment by demosat** [comment]
Thanks pr2
For me 			if HardwareInfo().get_device_model() in ("xp1000", "formuler1", "formuler3", "et9200"):

**Comment by jbleyel** [comment]
done

**Comment by demosat** [comment]
Merci à tous :-)

**Comment by pr2git** [comment]
No you should add both:  "et9000" and "et9200" and not replace et9000 by et92000.

I have an et9000 and demosat has a et9200 they are two different boxes with the same problem.
