### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte on request for services

### ISSUE THREAD

**Issue by shaxxx** [E2OpenPlugins/e2openplugin-OpenWebif#310]
OpenWebIf returns Server error (HTTP Code 500) with message
UnicodeDecodeError: 'utf8' codec can't decode byte on request for services
when http://address/web/getservices or http://address/web/bouquets is requested

Error is raised in
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/services.py:377 in getServices

To reproduce it:

1.) open some settings *.tv file
2.) insert special character (for example https://en.wikipedia.org/wiki/Degree_symbol) in first line (bouquet title)
3.) convert file from UTF-8 to ANSII encoding
4.) save file, upload it to receiver, restart enigma
5.) load http://address/web/getservices

Complete Traceback

/usr/lib/python2.7/site-packages/twisted/web/server.py:189 in process 
188 
189 
190 
/usr/lib/python2.7/site-packages/twisted/web/server.py:238 in render 
237 
238 
239 
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py:105 in render 
104 
105 data = func(request) 
106 if data is None: 
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/web.py:217 in P_getservices 
216 self.isGZ=True 
217 return getServices(sRef, True, hidden) 
218 
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/services.py:377 in getServices 
376 service['servicereference'] = sitem[0].encode("utf8") 
377 service['servicename'] = sitem[1].encode("utf8") 
378 services.append(service)

**Comment by jbleyel** [comment]
Please try this again with the latest version of services.py.

**Comment by shaxxx** [comment]
I can confirm it's working.
