### ISSUE TITLE
Transcoding playback via OpenWebif icon link not working

### ISSUE THREAD

**Issue by outrageuk** [E2OpenPlugins/e2openplugin-OpenWebif#317]
If you try and open transcoding via the icon within OpenWebif, it does not work.

However, if you open the stream direct with credentials in the URL, it does work - ie box transcoding is definitely working ok (http://username:password@ip:8002/service_ref)

Coincidence maybe, this started after updating OpenVIX which included new drivers and a 4.x.x kernel.

HTTP Authentication is NOT enabled, and this issue is recent.

Box: GigaBlue Quad Plus
Driver: 18/12/2015
Kernel: 4.0.1
Image: OpenVIX 3.2.032 (29/12/2015)

**Comment by jbleyel** [comment]
This is not a http/https authentication problem. There exist a setting for streaming authentication too.
