### ISSUE TITLE
TypeError: arg 'source' must be string or None

### ISSUE THREAD

**Issue by knowthelist** [E2OpenPlugins/e2openplugin-OpenWebif#322]
23:38:59.401 { D }   File "/home/oe1/nightly51/build-enviroment/builds/openatv/release/vusolo2/tmp/work/vusolo2-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+80a8fe82ac-r0/git/plugin/controllers/views/web/signal.py", line 58, in __init__
23:38:59.402 { D }   File "/usr/lib/python2.7/site-packages/Cheetah/Template.py", line 1172, in __init__
23:38:59.403 { D } TypeError: arg 'source' must be string or None
23:38:59.404 [ E ] python/python.cpp:209 call (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session instance at 0x64fcf2d8>>,()) failed)

**Comment by knowthelist** [comment]
sorry, github version works. The problem occurs on the openatv build only

**Comment by Schimmelreiter** [comment]
How to reproduce it (on OpenATV)

**Comment by knowthelist** [comment]
- OpenATV newest version (5.1) installed
- E2 MediaPortal Plugin installed
- E2 OpenWebIF installed
- Homeautomation FHEM Enigma2 Modul installed on FHEM system (http://fhem.de/commandref.html#ENIGMA2), which periodically requests to OWIF
- go to E2 menu > Plugins > MediaPortal
- E2 crashes before MediaPortal is started

Other users suffer also from this issue: http://www.opena.tv/openatv-5-1-rueckmeldungen/18409-5-1-auf-quad-plus-bluescreen-zw-mediaportal-und-openwebif-2.html

**Comment by Mooni123** [comment]
I can confirm this problem with OpenWebIF on OpenATV5.1 but also on VTI 9.2.1

**Comment by plnick** [comment]
Should be solved with: 0cd75b1f3f0ca1b9b3fe916da51ffd7489ffb40d
