### ISSUE TITLE
Adding Autotimer with weekday

### ISSUE THREAD

**Issue by MDXDave** [E2OpenPlugins/e2openplugin-OpenWebif#323]
If you want adding a new autotimer with weekday filter you must save the autotimer and edit it in order to set the weekday because the select box for the weekday is not available when adding autotimer.

**Comment by jbleyel** [comment]
I don't think so.

<img width="631" alt="bildschirmfoto 2016-02-18 um 21 30 14" src="https://cloud.githubusercontent.com/assets/964927/13157216/e93fd2b0-d686-11e5-9770-e7a6e3612f8e.png">

**Comment by MDXDave** [comment]
Versuch mal den Wochentag direkt beim hinzufügen zu wählen. 😉

**Comment by jbleyel** [comment]
Das Problem ist ein anderes, denn wenn man einen Wochentag Filter auf einen anderen Filter umstellt und zurück wird die Textbox bzw. die Auswahl nicht geändert.

Hat aber nix damit zu tun ob es ein neuer ist oder ob man den Autotimer nachträglich bearbeitet.

Ich schau mir das mal an.
