### ISSUE TITLE
AutoTimer list bug when initializing.

### ISSUE THREAD

**Issue by Priskvark** [E2OpenPlugins/e2openplugin-OpenWebif#332]
Since about 2 weeks, OpenWebif does not show any entries in the AutoTimer List when I select AutoTimer in the menu.  I have to click on the Reload-button to make the list visible. 

I'm using a Vu+ Solo2 with OpenPLI 4

**Comment by jbleyel** [comment]
please check this or provide the xml here.
http://<IP:PORT>/autotimer

IP from the box and Port from openwebif

**Comment by Priskvark** [comment]
Is this what you asked for?  XML-file and hardcopy from web browser inside .zip

[autotimer issue 332.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/163859/autotimer.issue.332.zip)

**Comment by jbleyel** [comment]
Please change the at-1.7.min.js with the attached js file.
-> /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/public/js

1. close the browser and reopen the browser.
2. goto the openwebif startpage.
3. start the javascript console of the browser
4. select the autotimer menu

Send me the console output.
[at-debug.js.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/163999/at-debug.js.zip)

**Comment by Priskvark** [comment]
Sorry, this took me a while. The problem was how to open a Java Console in Firefox (or IE).

I hope this output from Firefox is what you asked for.

[at-debug.js.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/164157/at-debug.js.zip)

**Comment by jbleyel** [comment]
how many channels do you have?
how long does this request take. ->  http://IP:PORT/api/getallservices

**Comment by Priskvark** [comment]
Number of channels total: 841
Used channels: 69
Time to load getallservices:  0,388 sec

I observed that after pressing "Reload" when AT shows there is no channel info whatsoever in the AT list. I can't even select a channel to record...

**Comment by jbleyel** [comment]
the page init loads the tags first and then all channels and then the list of the autotimer
the tags and the channels will be loaded async and i think this is the problem
i see no "finished loading" of the channels in your console log
i need to change the async to sync

i will provide a new js for testing

**Comment by jbleyel** [comment]
Please try this js and provide the console log again.

[at-debug.js.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/165921/at-debug.js.zip)

**Comment by Priskvark** [comment]
And here is the log:

[at-debug.js_Log_2.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/165941/at-debug.js_Log_2.zip)

**Comment by jbleyel** [comment]
Okay.. then we have a different problem.
the request 
http://IP:PORT/api/getallservices
is a non valid json

please provide me the browser result of
http://IP:PORT/api/getallservices

**Comment by Priskvark** [comment]
![_api_getallservices](https://cloud.githubusercontent.com/assets/9423289/13649220/dc36060a-e63c-11e5-9dad-a3f59e9ed8d9.jpg)

**Comment by jbleyel** [comment]
please disable the option "rename service for xmbc" in openwebif settings
there is a bug

**Comment by Priskvark** [comment]
Very good! Now i'm fine again. Thank you for your efforts. 

And this was interesting for me to watch and learn how you can debug those plugins…

**Comment by Priskvark** [comment]
I close this issue even if you maybe want to investigate the bug further.
