### ISSUE TITLE
No error message (too many Timer)

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#339]
No more error message if more timers at the same time (or overlap) are programmed as on the receiver are possible. Sorry if this is already known. Sorry for my bad english

Edit:
In TV-Browser it work.

![ff54](https://cloud.githubusercontent.com/assets/17575778/19696959/b200f0ea-9ae9-11e6-8afa-f8698197bcdd.png)

**Comment by jbleyel** [comment]
Hi @sgse .  Was muss in der Liste der Konflikte alles drin stehen und soll man da auch was machen können? (z.B Deaktivieren, Löschen,etc)

Deaktivieren ist ganz einfach.
Löschen sollte auch kein Problem sein.
Alles andere wird schwierig.

**Comment by Schimmelreiter** [comment]
Ich wäre ja für
Timererstellung abbrechen
+
Timer deaktiviert hinzufügen

**Comment by sgse** [comment]
Hallo, guten morgen ;)
Wenn sich wie oben ein Fenster öffnet (Nichts geht mehr ;-) ) und man die Möglichkeit bekommt in die Timer-Liste zu wechseln oder abzubrechen weil man merkt das die bisher gesetzten Timer bleiben sollen.
Wichtig ist aber nur die Mitteilung **"Weitere Timer nicht möglich"**, man kann ja dann selbst in "Timer" nachschauen :)

**Comment by jbleyel** [comment]
Hi @sgse , Timer und Play Timer aus EPG Liste hat jetzt die Prüfung drin. Was noch fehlt ist die Prüfung beim Timer Bearbeiten bzw. Anlegen + Bearbeiten.

Die ersten beiden kannst du schon mal testen.
