### ISSUE TITLE
possible Deny of Service

### ISSUE THREAD

**Issue by holgerlembke** [E2OpenPlugins/e2openplugin-OpenWebif#345]
Hi!

While researching how to request the EPG data via webif I seem to managed to stop my receiver. As far as I see, webif is dead after that and front display clock stops running (not sure about that, can clock be off more than 10 minutes?). Receiver needed reboot.

I somthing like used 

   http://tvbox/web/epgmulti?bRef=1:0:1:67:437:1:C00000:0:0:0:

and

  http://tvbox/web/epgservice?sRef=1:0:1:67:437:1:C00000:0:0:0:

It might be invalid, but still it should not kill anything.

**Comment by jbleyel** [comment]
Sure?
the first link works but takes some time
the second link will also work after 1-2 seconds
No freeze, no crash.
Your box is too slow If the second link takes more than 5 seconds.

**Comment by holgerlembke** [comment]
Not sure. 

But. Receiver is a Edision OS mini, latest openatv/webif. And I'm currently developing some stuff using the /web/-Interface mainly (some /api/ calls) and this was the last call the box got before it stopped responding. I waited about 20 to 30 seconds and made a reboot.

Yesterday I had a crash that killed /web/movielist, receiver never recovered from that and needed restart, too. Movielist gave back malformed answers.

**Comment by jbleyel** [comment]
This is not an openwebif issue.
You should check your calls.
Your problem sounds like a wrong usage of the python twisted webservice.
Too many calls and/or parallel calls.

**Comment by holgerlembke** [comment]
Ok, interesting approach.

For a system that is exposed to the net I expect it to be as robust as possible to requests from the net.

Even for home nets/non-hostile-environments I can imagine enough situations where bad intents might have the idea to kill the receiver by a simple command.

**Comment by jbleyel** [comment]
Once again, the openwebif is a simple web interface and mainly not designed as rest api interface.
You need to integrate the intelligence in your application.
I had to do this in my app as well.

**Comment by holgerlembke** [comment]
I fully understand that on the first hand I have to create valid software with valid access.

My last comment was more targeted to devices that are exposed to the net. It shouldn't be possible to kill a device by simple bad formated web query commands.
