### ISSUE TITLE
Back button does not work on mobile version after zapping to a channel

### ISSUE THREAD

**Issue by baba-yaga** [E2OpenPlugins/e2openplugin-OpenWebif#350]
Open OpenWebIF with a smartphone to get to a mobile version, choose a channel from, say, Favourites, click on Zap in the upper-right corner. The receiver changes to the corresponding channel ok, and the openwebif goes to the channel's page (with title Zapped to:ZZZZ etc.) but the Back button in the upper-left corner does not work, so to zap to another channel is impossible.

**Comment by jbleyel** [comment]
This is not reproduceable with the latest version
But the zap needs a little bit improvement and should not open a new window.

**Comment by jbleyel** [comment]
closed with https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/df8253e96a896556b62548fee59c556c98550870
