### ISSUE TITLE
Change streaming port

### ISSUE THREAD

**Issue by tro69** [E2OpenPlugins/e2openplugin-OpenWebif#351]
I want to change streaming port to 8001 to 7777.
I've VU+Zero with Blackhole 3.0.2.
I edited this line on /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/plugin.py file:
`config.OpenWebif.streamport = ConfigInteger(default = 8001, limits=(1, 65535) )`
to 
`config.OpenWebif.streamport = ConfigInteger(default = 7777, limits=(1, 65535) )`
and this line on /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/web.py file:
`services["host"] = "%s:8001" % request.getRequestHostname()`
to
`services["host"] = "%s:7777" % request.getRequestHostname()`
then I deleted /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/plugin.pyo and /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/web.pyo files and I rebooted STB but I got this error messages on VLC:
>http error: cannot connect to 192.168.0.8:7777
access_mms error: cannot connect to 192.168.0.8:7777
core error: open of `http://192.168.0.8:7777/1:0:1:FA5:3AC:110:EEEE0000:0:0:0:' failed

**Comment by Schimmelreiter** [comment]
OpenWebif does not create the streaming port, it just provides links to it.
Streaming is provided by the multitranscoding (XTrend and some others), streamproxy (Vu+) or E2 itself (PLi) resp. Erik Slagters multitranscoder (Also PLi).

You have to change the streaming port within the appropriate setup (Multitranscoder, ...).

**Comment by imporio** [comment]
Do you know what file to search for in order to change streaming port on VU+ Solo 4K with BH 3.0.2?

**Comment by Schimmelreiter** [comment]
Dunno about Vu+ Solo 4k.
Might be it's using the transspreamproxy.

Try looking at /etc/inetd.conf
Find a line like this:
`8002            stream  tcp6    nowait  root    /usr/bin/transtreamproxy        transtreamproxy`

Modify or duplicate it to
`9999            stream  tcp6    nowait  root    /usr/bin/transtreamproxy        transtreamproxy`
where 9999 is the port you desire.

AFAIR OpenWebif does nothing to detect the actual Vu+ transcoding port however, so you might need to patch it to use the new port.

**Comment by imporio** [comment]
Thanks for a reactive reply!

Streaming's port is the one I need to change, so I tried both duplicating and modifying from 
`8001 stream tcp nowait root /usr/bin/streamproxy streamproxy`
to
`8003 stream tcp nowait root /usr/bin/streamproxy streamproxy`

Both duplicated and modified lines are reverting edited port to the original one (8001) after reboot.

**Comment by sebseb2020** [comment]
Hi,

did you find the solution?
