### ISSUE TITLE
OpenWebif assumes 4 tuners instead of detecting all

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#353]
OpenWebif is fixed to assuming 4 tuners, rather than detecting the true amount of tuners.

This box has 6 tuners:
![image](https://cloud.githubusercontent.com/assets/2022025/16123735/6471d0d8-33ec-11e6-87bd-9a120e7cb2c8.png)

Tuners E and F are not contained within the graphical representation and the tuner number 4 exceeds the claimed limit of tuners 0-3 ...

This box has 2 tuners:
![image](https://cloud.githubusercontent.com/assets/2022025/16123866/c904fcfa-33ec-11e6-8f58-c805db68fea8.png)

Tuners C and D are shown although they do not exist.
The limit for tuner numbers is also 0-3, although it truely is 0-1.

There would be space enough left on the right side of the graphics to move the Dolby/Subtitle and so on pictures to the right and add tuners E+F.
For boxes with less tuners, we could overlap the area used by the non-existant tuners with blue blank space to cover the letters ...

As this is a graphical issue, it's nothing I can do myself ...

**Comment by jbleyel** [comment]
We need to redesign the Tuners. I have 8.
The next VU+ Ultimate 4K will have 3 Slots and then you can have 24 Tuners.
I think 24 letters are looking BAD.
