### ISSUE TITLE
Unable to open stream from multiepg2 event detail

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#356]
In multiepg2, when trying to open a stream from event detail, a JavaScript exception is thrown. A stream won't be opened consequently. The exception using Chrome: "openwebif-1.1.min.js:1 Uncaught TypeError: Cannot read property 'ref' of undefined".

**Comment by jbleyel** [comment]
MultiEPG 2 will gone with Version 1.0
