### ISSUE TITLE
Feature Request: EPG Modification

### ISSUE THREAD

**Issue by acandido** [E2OpenPlugins/e2openplugin-OpenWebif#36]
Would it be possible to change the EPG to have the times horizontally along the top and the channels vertically on the left side?  Seems to make more sense going that way.

Thanks

**Comment by gomble** [comment]
i also would like a time line like sky in openwebif

**Comment by jbleyel** [comment]
close with https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/d73f8d94f12393584d064f4c51b807d2e2624225
