### ISSUE TITLE
Openwebif timering problem

### ISSUE THREAD

**Issue by Atomantiii** [E2OpenPlugins/e2openplugin-OpenWebif#367]
I've installed yesterday's version of open pli and I've found a mistake in it. When I add a timer for recording in openwebif and later I'd like to change the starting time of recording the hour is changed to 12 and not remain in 24 hours format.

First picture: I've added a timer for 21:50
<a href='https://postimg.org/image/4b29m3i39/' target='_blank'><img src='https://s10.postimg.org/4b29m3i39/image.jpg' border='0' alt='postimage'/></a>

Second picture: When I'd like to change it the hour is not OK, it will be 09:50 and not 21:50
<a href='https://postimg.org/image/tyw47kyi3/' target='_blank'><img src='https://s9.postimg.org/tyw47kyi3/image.jpg' border='0' alt='postimage'/></a>

**Comment by jbleyel** [comment]
This is not reproducible.
<img width="790" alt="bildschirmfoto 2016-10-15 um 01 29 18" src="https://cloud.githubusercontent.com/assets/964927/19405342/d6a13fb6-9276-11e6-933e-e15ff033f997.png">
