### ISSUE TITLE
Themed vu_duo2 rmote (Fernbedienung)

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#368]
Hello,
If interested my remotes may be installed.
Thanks for your good work here.
The .xml does not need to be adjusted.
rmote must be remote, sorry :)
Goodbye
sgse

![vu_duo2](https://cloud.githubusercontent.com/assets/17575778/19640197/e614019c-99db-11e6-9929-e38400a902e8.png)
[vu_duo2.png.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/547335/vu_duo2.png.zip)

16,2 KB scaled

**Comment by jbleyel** [comment]
Duplicate #148
