### ISSUE TITLE
Themed OpenWebif Remote (ow_remote.png)

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#369]
Hello,
If interested my remotes may be installed.
Thanks a lot for your good work here.
The .xml does not need to be adjusted.

Goodbye
sgse

https://www.vuplus-support.org/wbb4/index.php?thread/99180-themed-openwebif-remote/&postID=1369625#post1369625

![ow_remote-cool_blue](https://cloud.githubusercontent.com/assets/17575778/17906320/15534b9c-6977-11e6-8e1a-6d96f37d1fef.png)
![ow_remote-cool_black](https://cloud.githubusercontent.com/assets/17575778/17906323/188a805a-6977-11e6-9c98-7274cf2909dd.png)

**Comment by RobvanderDoes** [comment]
It would be very nice if you would be able to create a generic 'full' remote.
Problem is that currently (bad) pictures of real RC's are being used; but they are very hard to read and hence impossible to use (plus several boxes can come with more than 1 RC).
 A generic RC (more or less in the same style as the current small RC, but holding many (but not necessarily all) possible buttons (like F1, HDMI-in etc etc) would make the use of any RC much more easy. There is absolutely no reason why the full RC should be a lookalike of the real thing: it's functionality that counts.

**Comment by sgse** [comment]
I like to help, 
Problem, I use only Duo2, my knowledge about etc,etc is less. HDMI-in you mean the "AV" key?
So I need:
1. How many F-keys
2. What resolution is attached, DPI
3. Which extra keys (Menu, Exit, **etc.**) or icons (Mute, ON/Off, **etc**.) you need?
4. Preferred color (blue ;) )
5. The new full RC replaces the ow-remote and box.png?
About branding, if I change the vu+ RC (without Logo) you will take it in OpenWebif?
My mother tongue is German, would be easier for me ;-) .
Da ich nur die begrenzte RC der Duo2 kenne wäre es hilfreich mir für die neutrale full RC die gewünschten Tasten-Piktogramnamen zu nennen, damit ich nicht eine nutzlose erstelle.

**Comment by RobvanderDoes** [comment]
I can name a few 'extra' buttons, but IMHO it is not required at all for a generic full RC to contain all possible buttons of all possible STB's:
Subtitle, Audio, PVR (or list or Media), TV, Radio, PVR-buttons (play/pauze/stop/fastForward/FastBackward/record), EPG, Volume Up/Down, Channel Up/Down.
Maybe the buttons I named earlier (like F1, HDMI-in) aren't required at all, but others might think otherwise.

I really would like to hear other suggestions.

I can't promise anything, as I don't have commit-rights on this repro, but this idea has been discussed earlier. Main break point by then was the lack of a decent design.

**Comment by RobvanderDoes** [comment]
@NietGiftig: I asked for suggestions, so please go ahead. But of the 5 buttons you name, I already suggested 4 :)
My contributions can be found on many places on GITHUB, but not on the WEB-IF, although I completely fail to see the relevance of that. A good design can only exist thanks to good thinking in advance, before any code is even thought at.

**Comment by RobvanderDoes** [comment]
@sgse 
FYI: some time ago there was a discussion with members of the web-if team, in which there was consensus about the requirement to introduce a generic full-RC. Reasons were the bad readability & diversity of RC's per STB (as I mentioned above) and the amount of coding involved at the moment a new box was to be supported.
At that time lack of design-power was the reason that this has not yet been done.
So when I noticed your design, that seemed the perfect opportunity for me to ask if you would/could create such an RC. I still hope you can, but if not, or if the nasty response in this thread diminishes your enthusiasm, please feel free to say so.
After all I'm steeling your thread, taking away attention from your suggestion.

**Comment by sgse** [comment]
I wrote before, I like. But I must know the name of the extra button etc. . 
Simple or decent is not the problem ;) 
Screenshot for example.

![simple](https://cloud.githubusercontent.com/assets/17575778/17630225/ac263802-60be-11e6-86bd-dfe4b7fb83e1.png)

**Comment by RobvanderDoes** [comment]
OK, thanks for remaining enthusiastic :+1: 
In addition to the already mentioned buttons I can think of: F1, F2, F3, Fav, Info, Timer, Text (Teletext), Help, Timer, LAN, Back, Home, End, Next, Previous, Timeshift, Search, Sleep, Power.
These are the buttons I could find so far. As I said: it would be nice if others would chip in to discuss if all of them really should go in.
Maybe even a 3-fold RC could be used: _**small**_ (is the one you showed in here), _**medium**_ (with all common buttons) and _**full**_ (with all possible buttons). But obviously that will require some re-coding as well.

**Comment by sgse** [comment]
Two times Timer will confused the user ;-)
If the members of the web-if team are ready I will start then to fix my pattern.

![muster](https://cloud.githubusercontent.com/assets/17575778/17642017/505da1f8-6137-11e6-9a2d-dd166d48aca7.png)

**Comment by Schimmelreiter** [comment]
Hmmmm .... not too exciting.

**Comment by Schimmelreiter** [comment]
"Full mode" keys should be added below. And Play/Pause and Stop should be seperate keys.
I think 4 columns for added keys would be more desirable than just three.

**Comment by ims21** [comment]
If you will make this universal RC, will make is as optionaly - some as "use Universal RC"... I want to have same RC as in real...

**Comment by sgse** [comment]
Wie ich schon sagte, ich mach sie fertig wenn ihr euch einig seid was alles reinkommt, auch beim wo bin ich flexible ;) . Die vu_duo2.png ist schon fertig. Da 1 zu 1 umgesetzt bräuchte man da auch nicht diskutieren nur die files tauschen.

**Comment by AbuBaniaz** [comment]
IMO..
Coloured buttons in one row would be better. Maybe put Vol+/- and CH +/- in their place?
< > should be on keypad, you can maybe move the others.

If you are so inclined, having buttons openwebif (when viewed on mobile) would be be a good addition too.

**Comment by RobvanderDoes** [comment]
> Hmmmm .... not too exciting.

Well, the idea was to make it good and clear, not exiting :(

Good to see others chipping in; this needs to be thought through by real WEB-IF users (I hardly ever use it; I only hear from users that the photographic version can't be read, which is indeed easy to see).

**Comment by sgse** [comment]
It is only an example !!!! My reason is only a better resolution when zooming, see Post 1. Fore myself I use 288 dpi, and I have only the duo2, don't know from F1 and other keys they are not on the duo2.
So again, if you are ready with all the keys and places, give me a list and I will fix it :)
This is 200 dpi , but key position failed.

![g12943](https://cloud.githubusercontent.com/assets/17575778/17642417/0b288602-6146-11e6-89ed-2687cb9478bb.png)

**Comment by RobvanderDoes** [comment]
A few personal ideas:
1- Extra buttons (extra with respect to the compact RC) should be folded out to the bottom, not to the top.
2- General extra buttons (PVR-buttons, audio, subtitle etc (buttons that all STB (should) have)) should be in the next 'layer' (so directly under the existing compact RC).
3- More specific buttons (many are already mentioned above; in fact most of them are simply 'shortcuts' to functions that are available via the menu) should be in the bottom layer.
4- Play/pause (and other) PVR-buttons should be separate buttons, not combined.
5- IMHO a short text on the buttons is better than an icon (but curious what others think about that). This doesn't apply to the PVR-buttons: those icons are well known and widely used.


PS: About adding the general RC to the existing 'real' RC's: although not a coder, I think that should be possible from a technical point of view. However: when doing so one looses the advantage of less coding when new hardware is being added.

**Comment by sgse** [comment]
Maybe have your interest to use this template (72 dpi). If possible in a new thread. As long until there is an agreement, you could use my template in # 1 Transitional.

![g12252](https://cloud.githubusercontent.com/assets/17575778/17645018/33ce5b24-6199-11e6-9f2d-1ae675614582.png)

**Comment by jbleyel** [comment]
Die mini FB hat eine andere Grösse wie das Original.
Die sollte 135*183 sein.
Und die Imagemap muss auch passen.

**Comment by sgse** [comment]
Die wird skaliert und funktioniert bei mir (aus post #1) genauso wie meine vu_duo2.png .
Bei beiden muss die remote .html nicht angepasst werden.
Habe jetzt alle pyo gelöscht. pyc's habe ich nur unter
/usr/lib/python2.7/site-packages/requests/api.pyc auf der Box.
Kann daher dein Werk nicht bewundern. Hast du evtl. eine IPK für mich? :)
Habe vom branch gebaut aber bin nicht so firm was github angeht.
gruss sgse

**Comment by jbleyel** [comment]
IPK kann ich dir keine machen.
Es kann jedoch sein, das du ein Box image hast wo das openwebif erst gepatcht werden muss
Dann startet es aber gar nicht.

Die Installation geht aber auch manuell.
Einfach das ZIP runterladen.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/archive/Theme.zip
Dann das zip entpacken.

Dann alle Files aus dem Order "plugin" auf die Box in den Ordner 
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif
kopieren.

Dann die GUI neu starten.

Es kann aber sein, das es trotzdem nicht geht wenn du die py und pyo Files der templates nicht löschst.
Diese liegen unter
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views
Die __init files aber nicht löschen.
Nur die Dateien wo es auch eine tmpl Datei gibt.

**Comment by sgse** [comment]
Vielen Dank für die ausführliche Beschreibung. :-) Jetzt muss es klappen :-D
pyc war wohl ein Schreibfehler. 
Die mini FB läuft nicht nur bei mir, oATV und VTi Anwender nutzen es zum Teil schon. oATV hat nur eine andere file Struktur was die vu_du2.png angeht.

**Comment by jbleyel** [comment]
Das mini Bild kann ich einbauen, ABER ich hab lieber ein png ohne Scallierung.
Die grössere Auflösung ist nicht notwendig.
Je kleiner die Datei (KB) um so besser.

**Comment by sgse** [comment]
Meine Augen sind nicht mehr die Besten ;) , wenig KB ist für Boxen mit wenig Speicher ja auch sinnvoll.
Bei oATV ist die vu_duo2.png grotten schlecht, die bei VTi ist besser hat mich aber auch genervt :-)
So, einmal hab ich OpenWebif schon zerschossen ;) jetzt bau ich mal neu aus dem Hauptthread. Oder ich muss warten bis es im Image übernommen wird. Da hatte ich bisher 0.4.8 statt 0.4.9 .
Danke noch mal an dich und das team hier, ihr macht gute Arbeit :-)

**Comment by jbleyel** [comment]
Welches Image hast du?
Kannst du enigma2 mit debug starten?

**Comment by sgse** [comment]
![jbleyel](https://cloud.githubusercontent.com/assets/17575778/19317679/1e69a5f4-90a6-11e6-8ac3-d392de326e34.png)
135x183 Nur für dich :-) ;-)

**Comment by sgse** [comment]
Oder wolltest du ein log file haben?

**Comment by jbleyel** [comment]
geht auch

**Comment by sgse** [comment]
Mehr kommt nicht, oder ich verstehe miss.
root@vuduo2:~# init 4
root@vuduo2:~# enigma2
PYTHONPATH: /usr/lib/enigma2/python
[VTi] change debug mode --> console: 0
[VTi] change debug mode --> file: 0
[glClass] Selected config: R=8 G=8 B=8 A=8 Depth=24 Stencil=0
[glClass] ANIMATION #6 selected
executing main
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: cHRM chunk does not match sRGB
Restarting internet superserver: inetd .
hbbtv.app: no process found
unknown client
unknown client
write ret : 192000
write to /dev/lcd2 : 192000
write ret : 192000
write to /dev/lcd2 : 192000
write ret : 192000
write to /dev/lcd2 : 192000
[glClass] ANIMATION #1 selected
write ret : 192000
write to /dev/lcd2 : 192000
write ret : 192000
write to /dev/lcd2 : 192000

**Comment by jbleyel** [comment]
Du musst in den VTi system settings den debug auf console umstellen.
Dann bekommst du mehr log.
Das ganze Log bitte nicht hier rein, sondern nur den Teil vom openwebif

**Comment by sgse** [comment]
Ok, muss zum essen ;) log kommt danach.
Die klitzekleine Grafik hast du gesehen, weiter oben?

**Comment by sgse** [comment]
Alles was im linken Menü zu sehen ist habe ich angeklickt. wrong hw konnte ich nicht reproduzieren.

```
01:00:47.517   [e2-core] resolve: resolve ${libdir}/enigma2/python/Plugins/Extensions/OpenWebif/pluginshook.src
01:00:47.517   [e2-core] resolve: -> /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/pluginshook.src
01:00:47.529 [e2-python] [OpenWebif] started on 80
01:00:47.545   [e2-core] (0)fe event: status 1f, inversion off, m_tuning 2
01:00:47.545   [e2-core] OURSTATE: ok
01:00:47.546   [e2-core] [eDVBCAService] channel 0x19503e8 running
01:00:47.546   [e2-core] [eDVBLocalTimerHandler] channel 0x19503e8 running
01:00:47.547   [e2-core] no version filtering
18:55:58.028 [e2-python] [OpenWebIf] wrong hw detection
18:55:59.614   [e2-core] child has terminated
18:55:59.614   [e2-core] pipes closed
18:56:01.053 [e2-python] playing service..
```

**Comment by jbleyel** [comment]
Hier gehts weiter -> #384
