### ISSUE TITLE
Signal strength info

### ISSUE THREAD

**Issue by makaveli96** [E2OpenPlugins/e2openplugin-OpenWebif#374]
When going to http://IP_address/web/signal to view signal strength info, the CPU usage for enigma2 spikes up and the box becomes unresponsive for sometime. How does openwebif obtain the signal info data? Is there a command I can run directly on the box (eg. cat /proc/something....) to see if it's something with the receiver itself or openwebif?

**Comment by rchovan** [comment]
Hi, 
could you please implement this api web/signal into OpenWebif interface ? I´d like to too see signal strength. I´ll appreciate if I can monitor signal from CLI with curl, or other script. 

Thank You

**Comment by jbleyel** [comment]
Please ask someone of the enigma2 developer of your image.

This is the code part for /web/signal

	service = session.nav.getCurrentService()
	if service is None:
		return inf
	feinfo = service.frontendInfo()
	frontendData = feinfo and feinfo.getAll(True)

	if frontendData is not None:
		inf['tunertype'] = frontendData.get("tuner_type", "UNKNOWN")
		inf['tunernumber'] = frontendData.get("tuner_number")

	frontendStatus = feinfo and feinfo.getFrontendStatus()


But your problem sounds like an issue of the twisted python web service.
