### ISSUE TITLE
owibranding misses from HEAD

### ISSUE THREAD

**Issue by athoik** [E2OpenPlugins/e2openplugin-OpenWebif#375]
Hello, 

Did anyone by mistake deleted owibranding?

The file plugin/controllers/models/owibranding.py doesn't exist any more in current HEAD.

**Comment by Schimmelreiter** [comment]
Should be fixed by https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/c63ebb9d533316eca546d134b6d4e49dca332231
Sorry.
If you find any more problems, let me know.

It's just that there seems to be no switch to let git add --all really add ALL as in ALL files.
