### ISSUE TITLE
Bouquet-Editor: Adding channel on last position or moving channels over 4 positions not possible

### ISSUE THREAD

**Issue by stefanex** [E2OpenPlugins/e2openplugin-OpenWebif#377]
I try to sort channels in my bouqet ... but it does't work well.
Every channel I add was inserted on first position, but i want it on last.
So I try to move down channel but only moving about 4 positions on one try not at last position as I drag with mouse.

Please fix this and add function for adding channel on last position or add after selected channel

**Comment by stefanex** [comment]
Moving more than one selected channel isn't possible too

**Comment by rdamas** [comment]
Thats by intention; better: the underlying API can't handle that today.
I have a patch ready for submission for the first issue though.
