### ISSUE TITLE
openwebif Branch ?

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#385]
I will create a new branch based on current master named "Version 0.x".
This branch is only for maintenance of version 0.x

The master branch will be Version 1.0.0. with all changes of Theme branch.

Any objections?

**Comment by Schimmelreiter** [comment]
Ja:
Erst, wenn die bekannten Fehler behoben sind
und
Was meinst Du mit "Will not work without internet for the first time"?

**Comment by jbleyel** [comment]
Das jquery und jquery UI als CDN geht nur wenn du Internet hast.
Evtl. baue ich das aber wieder um und lade die Files doch von der Box wie vorher.
Fehler sind keine mehr drin, nur noch paar farbliche Problemchen.

Ich hab auch keine Funktionen umgebaut, sondern nur die UI.
