### ISSUE TITLE
MultiEPG fixed header

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#387]
The window will not resized correct on increasing the browser window.
* Update: Firefox will not work as expected

**Comment by rdamas** [comment]
Will have a look at the issue later today.

**Comment by rdamas** [comment]
This almost fixes it:

```
function fixTableHeight() {
    var addScrollBarWidth = scrollBarWidth;
    if (\$('#tbl1').width() <= \$("#tvcontent").width()){
        addScrollBarWidth = 0;
    }
    var newh = \$("#tvcontentmain").height() - \$("#navepg").height() - 2*\$("#tbl1 thead").height() - addScrollBarWidth - 1;
    if (\$('#toolbar-header').is(':visible')) { 
        newh -= \$('#toolbar-header').height();
    }
    \$("#tbl1body").height( newh + "px");
}
```
But there seems still something wrong with the calculations done in ExpandMEPG() and CompressMEPG() regarding `$("#tvcontentmain").css()`.

**Comment by jbleyel** [comment]
The compress and expand was not called on page load.
But the height of tvcontentmain is NEW in css
#tvcontentmain { height :calc(100vh - 200px);}
