### ISSUE TITLE
AutoTimer Settings

### ISSUE THREAD

**Issue by EMJB** [E2OpenPlugins/e2openplugin-OpenWebif#389]
The poll interval is stated to be "(in h)" which I take to be hours, but actually the setting is in minutes so "(in m)" would be more appropriate.

I am using "OWIF 0.4.8" on Firefox with Windows 10 with OpenVix 4.0 running on an Xtrend 10K.

EMJB

**Comment by jbleyel** [comment]
This is right but also not right. It depends on the version of the autotimer.
The setting of the original DMM autotimer plugin is "config.plugins.autotimer.interval" and this value is in hours.

**Comment by EMJB** [comment]
Many thanks for quick reply. Since you have left the issue open, I assume you will correct this in due course (but obviously it is not a high priority).

**Comment by jbleyel** [comment]
Please update the autotimer plugin to a valid and supported version.
We can't support all versions of 3rd party plugins.

So we think it's not openwebif related.
Sorry. ...
