### ISSUE TITLE
Error When Changing AutoTimer Settings

### ISSUE THREAD

**Issue by EMJB** [E2OpenPlugins/e2openplugin-OpenWebif#390]
When I change a parameter on the AutoTimer settings screen and click on "Save" a red message appears below - e.g when changing Max Days from 0 to 6:

`<html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b> <div> <style type="text/css"> div.error { color: red; font-family: Verdana, Arial, helvetica, sans-serif; font-weight: bold; } div { font-family: Verdana, Arial, helvetica, sans-serif; } div.stackTrace { } div.frame { padding: 1em; background: white; border-bottom: thin black dashed; } div.frame:first-child { padding: 1em; background: white; border-top: thin black dashed; border-bottom: thin black dashed; } div.location { } span.function { font-weight: bold; font-family: "Courier New", courier, monospace; } div.snippet { margin-bottom: 0.5em; margin-left: 1em; background: #FFFFDD; } div.snippetHighlightLine { color: red; } span.code { font-family: "Courier New", courier, monospace; } </style> <div class="error"> <span>exceptions.ValueError</span>: <span>invalid literal for int() with base 10: '6true'</span> </div> <div class="stackTrace"> <div class="frame"> <div class="location"> <span>/usr/lib/python2.7/site-packages/twisted/web/server.py</span>:<span>189</span> in <span class="function">process</span> </div> <div class="snippet"> <div class="snippetLine"> <span class="lineno">188</span> <code class="code"></code> </div><div class="snippetHighlightLine"> <span class="lineno">189</span> <code class="code"></code> </div><div class="snippetLine"> <span class="lineno">190</span> <code class="code"></code> </div> </div> </div><div class="frame"> <div class="location"> <span>/usr/lib/python2.7/site-packages/twisted/web/server.py</span>:<span>238</span> in <span class="function">render</span> </div> <div class="snippet"> <div class="snippetLine"> <span class="lineno">237</span> <code class="code"></code> </div><div class="snippetHighlightLine"> <span class="lineno">238</span> <code class="code"></code> </div><div class="snippetLine"> <span class="lineno">239</span> <code class="code"></code> </div> </div> </div><div class="frame"> <div class="location"> <span>/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimerResource.py</span>:<span>361</span> in <span class="function">render</span> </div> <div class="snippet"> <div class="snippetLine"> <span class="lineno">360</span> <code class="code"></code> </div><div class="snippetHighlightLine"> <span class="lineno">361</span> <code class="code"></code> </div><div class="snippetLine"> <span class="lineno">362</span> <code class="code"></code> </div> </div> </div> </div> <div class="error"> <span>exceptions.ValueError</span>: <span>invalid literal for int() with base 10: '6true'</span> </div> </div> </body></html> `

When I go back the setting is unchanged.

I am using "OWIF 0.4.8" on Firefox with Windows 10 with OpenVix 4.0 running on an Xtrend 10K.

**Comment by jbleyel** [comment]
This issue need's to fix in autotimer plugin. 
Or you have a modified openwebif.
This git version have no issue.

**Comment by jbleyel** [comment]
Your autotimer plugin looks like the old plugin
https://github.com/oe-alliance/enigma2-plugins/tree/master/autotimer

This is the right one.
https://github.com/oe-alliance/enigma2-plugins/tree/2.3/autotimer

But CAUTION, i don't know if this version is compatible with OpenVix.

**Comment by EMJB** [comment]
Many thanks for quick response - will take this up with the OpenVix team.
