### ISSUE TITLE
Review EPG Refesh Display

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#394]
Und ich möchte nochmal das Thema EPGRefresh ausgraben ...

Meines Erachtens sieht das deutlich besser aus, wenn man nicht oben eine Zeile für jede Option macht und damit auch die ausgewählten Favoriten/Sender unnötig nach unten schiebt, sondern die Darstellung insgesamt kompakter gestaltet:
![image](https://cloud.githubusercontent.com/assets/2022025/19627839/acbeda1a-9950-11e6-8028-2e8e8ec987ee.png)

Außerdem ist mir grad aufgefallen, daß die Felder neben "Favoriten" und Kanäle" zueinander versetzt sind, die sollten doch eigentlich exakt untereinander sein.

**Comment by jbleyel** [comment]
Hi @Schimmelreiter  ->

Mockup:

<img width="1178" alt="bildschirmfoto 2016-10-24 um 12 17 52" src="https://cloud.githubusercontent.com/assets/964927/19642107/018928f0-99e4-11e6-87a4-04ad3afc31ce.png">

**Comment by Schimmelreiter** [comment]
Schon besser.
Wobei ich "Method" noch in der dritten Zeile verorten würde und die beiden AutoTimer-Integration (Quasi in und out) auch in einer.

**Comment by jbleyel** [comment]
Sollte kein Problem sein. Aber wieso Method in die 3. Zeile. und nicht in die 1.

**Comment by Schimmelreiter** [comment]
Geht auch.

**Comment by jbleyel** [comment]
EPGRefresh ist für's erste ok, aber etwas stark zerfleddert.
Kann man aber für den Moment so lassen.
