### ISSUE TITLE
"zap before Stream"

### ISSUE THREAD

**Issue by Dima73** [E2OpenPlugins/e2openplugin-OpenWebif#395]
offer...
1)When "zap before Stream" is yes
2)When box standby mode and use stream, after stop stream the current service is running
Need stop current service after stream when box is  standby mode.

**Comment by jbleyel** [comment]
Hi @Dima73 , one possible option:

If zap before Stream is ON and the box is in standby, then don't call zap.
This should fix your problem.

**Comment by Dima73** [comment]
The solution of course is very simple.
But strimining will work without having to  zap on channel?

**Comment by jbleyel** [comment]
Hi @Dima73 , you are wrong. The stream will not work if you have no free tuner.

**Comment by Schimmelreiter** [comment]
To point this out:
Of course streaming works without zapping to channel first.

The only reason to zap before stream is:
You have a box with only **one** tuner **and** the box is **not** in standby.

Unused tuners can stream anything, so
- a box with multiple tuners will simply use any other tuner for streaming than that being used for live TV on the box
and
- for a box in standby even the only one tuner is free/unused
