### ISSUE TITLE
EPG Detail GUI

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#396]
![ff42](https://cloud.githubusercontent.com/assets/17575778/19658427/3751a91e-9a28-11e6-9956-7280e39fdfb0.png)

Soll  das "SchließenTeil", hellgrau, X ist dort für schließen, schmaler sein als das Fenster darunter?

**Comment by sgse** [comment]
Nichts mehr, hatte schon mal geschrieben, dass es ja (jetzt?) mittig darüber steht und gut aus sieht. Ist ja konsequent im Theme.
![tv34](https://cloud.githubusercontent.com/assets/17575778/20036535/d1e2aae6-a40a-11e6-91c7-3198c4d7b481.png)

**Comment by jbleyel** [comment]
Soll ich bei Bildschirmfoto den oberen Balken weg machen?
Der ist eigentlich nicht notwendig.
Den Balken bei EPG Detail kann man auch etwas dicker machen.

Es geht ja nur noch um Feinschliff.

**Comment by sgse** [comment]
Gute Idee, habe (gerade auf die Schnelle) auch nichts mehr gefunden wo diese Welle als 3D Reflektion auf den Balken ist.

**Comment by sgse** [comment]
Ups
![tv36](https://cloud.githubusercontent.com/assets/17575778/20036653/30d557e4-a40e-11e6-9087-88e11fd63ab7.png)

**Comment by jbleyel** [comment]
Was meinst du mit upps?

**Comment by sgse** [comment]
Habe noch was angehängt. Na diese theme-Welle.

**Comment by sgse** [comment]
Hier ist die Welle im Balken, muss ja evtl. so sein :)
![tv38](https://cloud.githubusercontent.com/assets/17575778/20036676/526246e6-a40f-11e6-9c4b-2d0106baf057.png)

**Comment by sgse** [comment]
Hier nur unter "Fernsehen"
![tv39](https://cloud.githubusercontent.com/assets/17575778/20036729/a2860cec-a410-11e6-8dae-35d87a87e786.png)

**Comment by jbleyel** [comment]
Jo, bei TV soll das so sein.
Eigentlich soll das bei jedem Balken oben so sein.

**Comment by jbleyel** [comment]
AHH du meinst den Verlauf unterhalb vom Menü.

**Comment by jbleyel** [comment]
Hi @sgse , ich finde die Welle nicht so schlimm.
Falls du aber ein Theme findest wo die Well wirklich schlecht ausschaut, dann mach kurz einen Screenshot und nenne mir das Theme.

**Comment by sgse** [comment]
Kein Ding, hat mich nur gewundert da einige, die ich durchgeschaut habe, keine haben.
Bin auf vader fixiert :-) und ich gehe mal davon aus, da es genug themes gibt, dass sich hier drüber keiner beschweren kann von den Nutzern.
