### ISSUE TITLE
Timer-Edit-Dialog

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#398]
Improve Edit Timer dialog for huge list of tags.

**Comment by jbleyel** [comment]
![ff48](https://cloud.githubusercontent.com/assets/17575778/19663757/b912c158-9a3d-11e6-8a22-2dd5966971c9.png)

**Comment by Schimmelreiter** [comment]
The list isn't huge ... it's the default set ...

**Comment by jbleyel** [comment]
Wieso ist die Auswahl vom Sender so breit.
Gibt es da einen Sender der da nicht in die Liste rein gehört.
Schaut mal die Liste durch.

**Comment by Schimmelreiter** [comment]
Die ist so breit, damit der Sendername nicht abgeschnitten werden muß.
![image](https://cloud.githubusercontent.com/assets/2022025/19695973/7d52bb8e-9ae5-11e6-99d9-886d207c6538.png)

**Comment by sgse** [comment]
![ff53](https://cloud.githubusercontent.com/assets/17575778/19695994/948559ba-9ae5-11e6-9b6a-309ac2cce0bf.png)

**Comment by jbleyel** [comment]
Okay .. das ist definitv lang.
Da hilft nur eins, das ganze Fenster etwas breiter.

**Comment by sgse** [comment]
WebCam?

**Comment by Schimmelreiter** [comment]
Mein Reden seit Anno Leipzig/Einundleipzig

**Comment by Schimmelreiter** [comment]
Und höher muß es auch, damit die Tag-Cloud paßt.

**Comment by Schimmelreiter** [comment]
Sogar ein ganzes Stück höher, denn eventuelle Fehlermeldungen (Konflikt) werden ja unten dazugeblendet.

**Comment by sgse** [comment]
@Schimmelreiter Die "Stichworte" sind in allen Images enthalten oder bei nur bei mir nicht?

**Comment by Schimmelreiter** [comment]
Also bei mir waren sie bisher überall drin.
Stehen in /etc/enigma2/movietags:
```
Action
Krimi
Horror
Drama
Komödie
Liebe
Serie
SciFi
Familie
Kinder
Erotik
Fußball
Tennis
Golf
Simpsons
Airwolf
Hulk
News
Doku
Film
Musik
Quiz
Casting
Talkshow
```
Da ich bestimmt nicht mehr Airwolf gucke sieht man gut, daß das noch die Muster-Bestückung ist.

**Comment by Schimmelreiter** [comment]
Hab grad mal auf einer Box mit VTi geguckt, da scheinen sie tatsächlich generell zu fehlen.

**Comment by Schimmelreiter** [comment]
Prinzipiell sind Tags schon 'ne klasse Sache, wenn sie denn überall unterstützt werden.
Zum Stöbern in einem Archiv gibt es nix besseres, als sich über Tags zum Ziel durchzuhangeln ...

Aber wie so vieles in E2 ist es auch nur angefangen und nie fertig gemacht worden.

**Comment by sgse** [comment]
![g7165](https://cloud.githubusercontent.com/assets/17575778/19697738/dd87ce2a-9aec-11e6-97a9-17a6026ce409.png)
Das bekommt man bestimmt besser hin, habe keine Ahnung wie hoch das sein darf. Als Textersatz für Umstelltaste um alles in eine Zeile zu bekommen.

@Schimmelreiter Danke fürs suchen :)

**Comment by Schimmelreiter** [comment]
Manchmal nervst Du :)
Einmal mit der Umschalttaste und einmal mit dem Bild von der Duo².
Was gefällt Dir denn an dem Bild der Duo² in oe-a nicht?

Auf jeden Fall schöner als der schwarze Klotz bei VTi.

**Comment by sgse** [comment]
Du wolltest doch Platz sparen in der Höhe ;)

**Comment by Schimmelreiter** [comment]
Jetzt paßt es aber ...
Von mir aus kann der Text aber auch ganz weg oder durch ein Mouse-Over ersetzt werden.

Ich würde nur die Umschalttaste nicht grafisch repräsentieren, auf manchen Tastaturen steht auch "Shift".

**Comment by Schimmelreiter** [comment]
Zum Bild der Vu+ Duo²:

Ganz voooooorsichtig!

https://github.com/oe-alliance/branding-module/commit/0d9421001d5d43458572b5067ba7df3daf3d9a95

**Comment by sgse** [comment]
Ich spreche von der Fernbedienung, die Bilder der Boxen sind gut !!!!!

**Comment by jbleyel** [comment]
Nehmt euch doch ein Zimmer. * lach *
In dem Issue sollte eigentlich nur das Problem mit der Timer Edit Ansicht rein.

**Comment by sgse** [comment]
ROFL, ich habe keinen Überblick mehr mit den ganzen #... ;)

**Comment by Schimmelreiter** [comment]
Ja dann mach doch endlich fertig, wir sabbeln hier doch nur aus Langeweile, weil sich nix tut!
**vbeg**

**Comment by jbleyel** [comment]
OK warte..

**Comment by sgse** [comment]
Wenn ich immer gleich eine Antwort bekäme müsste ich nicht zum zweiten mal Fragen ;)
Nochmal falls unter gegeangen. FB https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/368

**Comment by Schimmelreiter** [comment]
@sgse: Das Thema "web-optimized remote" hatten wir doch schon.
Vertagt.

Und "verfälschte Originalfernbedienungen" gibt nur Streß mit den Usern:
Entweder radikal (Also web-optimiert) oder gar nicht (Also weiterhin Original, selbst wenn eigentlich ungeeignet).

Wobei ich dachte, daß Du längst am Zeichnen wärst.

**Comment by Schimmelreiter** [comment]
@jbleyel 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/7eda857eafe8a28d191a488fa878880c7a5c401f
Danke.
Wenn Du wüßtest, wie oft ich heute schon nach neuen Commits geguckt habe ...

Kannst Du den Timer-Edit-Dialog nicht einfach quick'n'dirty 'n Schlag größer machen, damit wir 1.0.0 erstmal abhaken können?

**Comment by Schimmelreiter** [comment]
Spinner/spin6 und Timer-Edit-Dialog-Größe.

Danach wie unter Linux: It compiles, first screen comes up, ship it!

**Comment by sgse** [comment]
Ich habe nicht an den Boxen-Fotos rum gemäkelt und dachte du verwechselst es mit den FB. Ich lösch gleich mal meine Kommentare dazu.

**Comment by jbleyel** [comment]
Hi @sgse  was ist damit -> #339

**Comment by sgse** [comment]
Eben nochmal getestet, ich kann bis zum abwinken timer setzen, kommt keine Fehlermeldung. TV-Browser merkt es.

**Comment by Schimmelreiter** [comment]
Also ich kann nicht mehr Timer setzen, als meine Tuner abkönnen.
Aber man wundert sich einfach nur, daß sie nicht da sind, eine deutlich sichtbare Meldung fehlt.

**Comment by jbleyel** [comment]
<img width="768" alt="bildschirmfoto 2016-10-25 um 21 31 59" src="https://cloud.githubusercontent.com/assets/964927/19701180/8becb3b0-9afa-11e6-8c01-cc0ac96a0f87.png">

Was soll ich noch ändern?

**Comment by Schimmelreiter** [comment]
Start und Endzeit stehen irgendwie dumm da rum.

**Comment by jbleyel** [comment]
Ich bin für jeden Vorschlag offen.

**Comment by sgse** [comment]
Untereinander, Platz genug.
Warum 2 mal Umschaltt.?

**Comment by jbleyel** [comment]
Der 2. soll zap+record sein, hab ich noch nicht gemacht.

**Comment by Schimmelreiter** [comment]
Zeit: [Startzeit] bis [Endzeit]
Das Starteit-Feld dabei unter das Eingabefeld darüber.
Und "Wiederhole" direkt darunter.

**Comment by sgse** [comment]
@jbleyel . So gan isch ned arbeide ;)

**Comment by jbleyel** [comment]
Wo soll ich dann die 3 Schalter hin?

**Comment by jbleyel** [comment]
Ganz Oben?

**Comment by sgse** [comment]
Wo soll die Frage,  "Aufnahmen" merkt sich nicht die letzte Sortiereinstellung, hin.

**Comment by jbleyel** [comment]
Ist nicht implementiert, mach einfach einen neunen Issue auf.

**Comment by sgse** [comment]
Sortiert ja sehr schnell neu. :)

**Comment by jbleyel** [comment]
JA, die neue Funktion macht das ohne die Seite neu zu laden.

**Comment by jbleyel** [comment]
Ist auch Feature für 1.0.x

**Comment by jbleyel** [comment]
Hier der letzte Stand vom Timer.
<img width="752" alt="bildschirmfoto 2016-10-25 um 22 18 45" src="https://cloud.githubusercontent.com/assets/964927/19702731/450dbae6-9b01-11e6-8a06-f6dfec2995f2.png">

**Comment by Schimmelreiter** [comment]
Checkbox hinter "Aktiviert" zu nah dran.

**Comment by jbleyel** [comment]
Was noch?

**Comment by Schimmelreiter** [comment]
Ich hätte es jetzt nicht wirklich ganz nach oben geschoben, aber was soll's.

**Comment by sgse** [comment]
O.K. 
Nur bei TV Radio ist das Kästchen davor bei allen anderen dahinter.

**Comment by jbleyel** [comment]
Die Frage ist ob wir da überhaupt 2 brauchen, oder nur einen für Radio.

**Comment by sgse** [comment]
Gut ausgewichen ;)

**Comment by jbleyel** [comment]
<img width="749" alt="bildschirmfoto 2016-10-25 um 22 51 21" src="https://cloud.githubusercontent.com/assets/964927/19703829/98113160-9b05-11e6-8b29-ddf88bd143d2.png">

**Comment by sgse** [comment]
Ich würde jetzt Start Ende in zwei Zeilen mit großem Abstand machen

**Comment by jbleyel** [comment]
Wieso zwei Zeilen? Das ist Platzverschwendung.

**Comment by sgse** [comment]
Kommt unten noch Werbung hin?

**Comment by jbleyel** [comment]
Muhaha

**Comment by jbleyel** [comment]
Du hast keine Tags ODER?

**Comment by sgse** [comment]
Nö, du auch nicht.

**Comment by jbleyel** [comment]
Und ganz unten ist noch eine Error Box, die man sonst nicht sieht.

**Comment by sgse** [comment]
Muß einem doch gesagt werden ;)

**Comment by sgse** [comment]
Ich kann auch nicht wissen ob du evtl. das Fenster zum Schluß evtl. kleiner machst. Ich schau nur was dort geht.

**Comment by jbleyel** [comment]
<img width="638" alt="bildschirmfoto 2016-10-25 um 22 59 29" src="https://cloud.githubusercontent.com/assets/964927/19704107/bee665fc-9b06-11e6-8a15-b5575456a904.png">

**Comment by sgse** [comment]
Dann das Start rüber und nicht so einsam da stehen lassen.

**Comment by jbleyel** [comment]
<img width="748" alt="bildschirmfoto 2016-10-25 um 23 03 35" src="https://cloud.githubusercontent.com/assets/964927/19704243/49e93c4c-9b07-11e6-8424-8d97c284d226.png">

**Comment by jbleyel** [comment]
Ich check das jetzt so ein. OK???
Ihr habt 30 Minuten für VETO.

**Comment by sgse** [comment]
Umschaltt. könnte man ausschreiben. Platz ist ja da.

**Comment by sgse** [comment]
Ihr schreibt
Timer
ZAP
Record
aber Shift geht nicht, da muss es Umschalttaste sein. Ich glaube das färbt hier auf mich ab von Schimmelreiter ;)

**Comment by Schimmelreiter** [comment]
Mir ist damals beim Übersetzen nix besseres eingefallen.
Was soll man denn statt Timer schreiben?

"Geplante Aufnahme" ... da gibt es aber ein Problem mit gettext:
gettext übersetzt denselben Text an jeder Stelle gleich, was z.B. ein Problem mit "clear" gibt, beim Wetter heißt das "klar", bei Eingaben "löschen", dann kann es Verb oder Adjektiv sein, usw. usf.

Halt alles nur halbgares Zeug, wie immer in der *ix-Welt.

**Comment by Schimmelreiter** [comment]
"Damals" war kein Platz für "Umschalttimer" in ausgeschrieben.

**Comment by Schimmelreiter** [comment]
"Zap+Record" ist übersetzt auch zu lang, "Umschalten und Aufnehmen" paßte nicht.

**Comment by sgse** [comment]
Ich meine das ja auch nicht destruktiv, wenn man die gebräuchlichen kurzen Varianten in englisch nimmt wäre den "Leuten" auch shift zu zumuten :)

**Comment by Schimmelreiter** [comment]
@jbleyel : Kauf Dir mal 'ne Uhr, die 30 Minuten sind längst rum.

Nene, wenn man hier nicht alles selber macht ;)

**Comment by sgse** [comment]
Wobei ich mir nicht sicher bin ob es mit shift nicht auch zwei Zeilen werden. :D

**Comment by Schimmelreiter** [comment]
Ich bin mir ziemlich sicher, daß es dabei zwei bleiben.
Heulsuse.

**Comment by sgse** [comment]
Er hat gerade was gemacht. brauchts einen GUI-Start?

**Comment by Schimmelreiter** [comment]
Für mich braucht's was mehr :)
git pull upstream Theme
git push
[andere Session]
MACHINE=vusolo2 DISTRO=openatv make image

**Comment by sgse** [comment]
Ich muss immer die Changes.md ändern (heul)

**Comment by Schimmelreiter** [comment]
Supi, laufende Aufnahmen ...

**Comment by sgse** [comment]
me too, deshalb die GUI Frage

**Comment by Schimmelreiter** [comment]
Überhaupt ein Geburtsfehler von E2, daß "GUI neustarten" nicht nur die GUI neustartet ...
Hatte ich ja schon im ATV-Forum was zu gesagt.

**Comment by sgse** [comment]
Suche ich später mal nach.

**Comment by Schimmelreiter** [comment]
Quintessenz daraus:
Wenn man schon ein so schlechtes System wie Linux als Basis nimmt, dann hätte man zumindest die gebräuchliche Trennung in Daemon und Client übernehmen können.
transmission-daemon bricht auch keine Downloads ab, wenn ich transmission-gui (Oder "Transmission Remote GUI" auf meinem richtigen Betriebssystem) neu starte oder gar beende.

**Comment by Schimmelreiter** [comment]
Man hat praktisch bei allen Architekturen das jeweils Schlechteste abgekupfert :)

**Comment by sgse** [comment]
Muss ich schon wieder googlen ;)

**Comment by sgse** [comment]
![ff56](https://cloud.githubusercontent.com/assets/17575778/19706028/0b855edc-9b10-11e6-9c43-9f0f008788bb.png)
Ich kann nichts in Stichworte schreiben, normal?
Und Umschalttimer würde passen.

**Comment by Schimmelreiter** [comment]
Ja, das ist normal.
Man wählt aus den vorhandenen Schlagworten die aus, die passen.

Das Prinzip der Schlagwortwolke/Tag Cloud hat gegenüber strengem Kategorisieren den Vorteil, daß ein Objekt, hier also eine Aufnahme, mehrere Eigenschaften haben kann.

Spätere Suche nach den Tags findet dann genau das passende, also würde z.B.
Action+Komödie Actionkomödien anzeigen, aber keine Liebeskomödien.

Klassisch müsstest Du Dich beim Archivieren ja entscheiden, ob Du den Film unter "Action" oder unter "Comedy" ablegst.

**Comment by Schimmelreiter** [comment]
Ich weiß wohl ehrlich gesagt nicht, wie man dann auf der Box nach diesen Tags sucht.
Es wäre ja sinnvoll, man könnte seine Liste aller aufgenommenen Filme nach solchen Tags filtern.

**Comment by Schimmelreiter** [comment]
Wie Du ja vielleicht an den Screenshots bemerkt hast, ist mein zweites Hobby das Sammeln von Dokumentationen zu den Themen Anthropologie und Reproduktionsbiologie.

Da wären solche Tags auch sehr praktisch, denn strikte Kategorien stoßen dabei schnell an ihre Grenzen:
So habe ich Lieblingsdarstellerinnen (u.a. Bunny de la Cruz und April Flores), mag Krankenschwestern und dicke Hupen sowie Moppelchen.

Wo kommt aber nun "Hooter Hospital" hin?
a.) Bunny de la Cruz spielt mit, also in das Verzeichnis mit ihren filmischen Werken?
b.) zu den Krankenschwestern?
c.) zu den dicken Hupen?
d.) zu dem Moppelchen?

**Comment by sgse** [comment]
Gefällt mir gut jetzt so. 
Wenn es nicht geht wozu werden die dann angelegt?

LOL Du hast es nicht leicht. Ich helfe mir dann mit Ordnern und finde dann auch nichts :)
Searchmonky rettet mich manchmal.

Reproduktionsbiologie könnte mir auch gefallen :) ich schlaf mal ne Nacht drüber :D

**Comment by Priskvark** [comment]
Sorry for entering your conversation. 

But please consider all aspects of assembling a group of fields horizontal, for example: Zeit: …. Start …. Ende.

These text fields may require more space in other languages if you want a good translation. Are the data fields aligned dynamic in respect to the text fields or are they at fixed positions?

**Comment by jbleyel** [comment]
Hi @Priskvark could you please show me your Dialog.
Only the 1. row has a fixed size but i can change this if i have an example.

**Comment by Schimmelreiter** [comment]
First row fixed is crap.
Now as there is more free space, we should change the translation in German too:
"Umschalttimer" and "Umschalten und aufnehmen".
The old translation (or non-translation) was already only due to lack of space ...

**Comment by jbleyel** [comment]
Sorry, the first column is fixed. my fault
<img width="410" alt="bildschirmfoto 2016-10-26 um 00 33 46" src="https://cloud.githubusercontent.com/assets/964927/19706774/0a0c84e6-9b14-11e6-8116-ecc9363fa4c4.png">

**Comment by Schimmelreiter** [comment]
At least it's wider than before.

**Comment by jbleyel** [comment]
YES !!!

**Comment by Schimmelreiter** [comment]
Why is it still twice "Umschaltt."?

**Comment by sgse** [comment]
![ff57](https://cloud.githubusercontent.com/assets/17575778/19706832/50844922-9b14-11e6-84ff-d6b2ae4db6f4.png)
Bei mir noch nicht.
Habe ich vorhin schon geschrieben, er ist noch nicht fertig.

**Comment by Priskvark** [comment]
I am actually not worried for that line in Swedish. It will probably fit. It’s more of a principle when you work with user interfaces that you should not put the fields to tight together. I use to joke that it should even fit with a Finnish translation to be OK.

But this should be considered in other places in the interface now that you are rebuilding it :-)

**Comment by Schimmelreiter** [comment]
Poah, so schwierig, heutzutage noch gutes Personal zu kriegen ;)

**Comment by jbleyel** [comment]
Ich hab die local.py nicht getauscht, daher der falsche text.

**Comment by Schimmelreiter** [comment]
Hast Du uns noch lieb?

**Comment by sgse** [comment]
We 
![herz400](https://cloud.githubusercontent.com/assets/17575778/19706955/183243e8-9b15-11e6-9f05-6e44ab6c74ef.png)
@jbleyel

**Comment by sgse** [comment]
Eingetragen wird es. 
![ff58](https://cloud.githubusercontent.com/assets/17575778/19707135/2f12352c-9b16-11e6-9a7d-9907f501ba1c.png)

**Comment by Schimmelreiter** [comment]
Was wird eingetragen?

**Comment by sgse** [comment]
Na der timer, beim deaktivieren macht FF da wieder was falsch. Teste gleich Chrome.

**Comment by jbleyel** [comment]
Was macht der FF falsch????

**Comment by Schimmelreiter** [comment]
Bei mir läuft immer noch eine Aufnahme, eine Reportage über die Arbeitsbedingungen der weiblichen Mitarbeiter mit prägnanten Mammae in einem Wellness-Betrieb .... (Big Boobs in Uniform).

**Comment by Schimmelreiter** [comment]
Was der Firefox falsch macht?
Er vergißt, beim Start darauf hinzuweisen besser mal Chrome zu installieren :)

**Comment by sgse** [comment]
![ff60](https://cloud.githubusercontent.com/assets/17575778/19707258/e07cc822-9b16-11e6-9b7c-7b17954fe4ae.png)
Nimmt den Haken nicht raus, Chrome stzt keinen Neuen.

**Comment by Schimmelreiter** [comment]
In 11 Minuten kann ich testen ...

**Comment by jbleyel** [comment]
Ich Gucke.

**Comment by jbleyel** [comment]
Habs gefunden.
Ich mach aber keinen extra commit.
Ihr findet sicher noch was anderes.

**Comment by Schimmelreiter** [comment]
Wenn Du eh grad nix zu tun hast, kannst Du ja mal de.po anpassen und da aus "Record+ZAP" "Umschalten und aufnehmen" und aus "Umschaltt." "Umschalttimer" machen.
:)

**Comment by Schimmelreiter** [comment]
Dann sieht man, wie's würgt, äh, wirkt.

**Comment by jbleyel** [comment]
Jo mach ich.

**Comment by sgse** [comment]
Das ich das Fenster stauchen kann hat er gesehen?

**Comment by Schimmelreiter** [comment]
Immer noch was zu klein, das Fenster:
![image](https://cloud.githubusercontent.com/assets/2022025/19707702/637fb2a0-9b19-11e6-892c-3f3880cc604c.png)

**Comment by Schimmelreiter** [comment]
Der Haken nach deaktivieren/reaktiveren in der Liste sitzt sonstwo:
![image](https://cloud.githubusercontent.com/assets/2022025/19707732/996d2712-9b19-11e6-8e2e-68b87ba24509.png)

**Comment by jbleyel** [comment]
Dann mach ich die Tags etwas kleiner in der Höhe und das Fenster noch etwas grösser.

Timerliste hab ich schon gefixt.

**Comment by sgse** [comment]
01:35 bin ich raus ;)
White Noise - Schreie aus dem Jenseits
Der effektvolle Gruselthriller war ein Überraschungshit an den Kinokassen.

**Comment by Schimmelreiter** [comment]
Ich bin dienstbereit.
Allzeit breit quasi.

**Comment by Schimmelreiter** [comment]
Wenn sgse sich raushält kriege ich vielleicht auch ein einziges Mal das Symbol, das ich mir wünsche **g**

**Comment by Schimmelreiter** [comment]
34 Minuten seit dem letzten Commit, jbleyel is mal wieder im Bummelstreik ;)

**Comment by Schimmelreiter** [comment]
@sgse "Grusel" ist ja voll Deins, gell?
Sonst würdest Du ja auch nicht VTi nehmen ;)

**Comment by sgse** [comment]
Mich stört auch nicht der Laserpointer an der Duo² :D

**Comment by Schimmelreiter** [comment]
Der is ja wieder weg.

**Comment by sgse** [comment]
FF dreht jetzt völlig durch, habe "meine" Pics geladen und alle Menüs sind nicht mehr lesbar. Chrome nimmts klaglos.

**Comment by jbleyel** [comment]
Hä?

**Comment by sgse** [comment]
Ist ein insider.

**Comment by Schimmelreiter** [comment]
@jbleyel Falls Du den Laserpointer meinst:
Eines Tages hatte ich an der Duo² die 10-Gigawatt-Standby-LED an und zwar auch im Betrieb. Ziemlich nervig. War aber nach zwei Tagen auch wieder weg.

**Comment by Schimmelreiter** [comment]
Bei LEDs muß ich immer dran denken, daß ich sooooo alt bin, ich kenne noch LEDs, da mußte man die Raumbeleuchtung ausschalten um zu sehen ob sie an sind.

**Comment by sgse** [comment]
Auch im letzten Jahrhundert geboren? ;)

**Comment by Schimmelreiter** [comment]
Wirklich helle LEDs gab's dann zuerst in Radioweckern.
Die konnte man dann meistens umschalten von "Interstellare Laserkanone" zu "Jedi-Schwert".

**Comment by Schimmelreiter** [comment]
Im letzten Jahrtausend sogar!

**Comment by jbleyel** [comment]
Ich geht jetzt pennen. Die letzten Änderungen sollten alle offenen Probleme fixen.

**Comment by Schimmelreiter** [comment]
Mein erster Computer hatte 128kB RAM und ein 180kB-Diskettenlaufwerk.

**Comment by sgse** [comment]
Hätte ich mal nix vom Film geschrieben ;)

**Comment by sgse** [comment]
128 KB

**Comment by Schimmelreiter** [comment]
Jau, das nimmt @jbleyel jetzt direkt als Feierabendglocke ...

**Comment by sgse** [comment]
5 1/4 Zoll Wabbel

**Comment by Schimmelreiter** [comment]
Ne, 3"

**Comment by Schimmelreiter** [comment]
![image](https://cloud.githubusercontent.com/assets/2022025/19708260/8a53b56c-9b1d-11e6-83f5-2e62fde6dda5.png)

**Comment by sgse** [comment]
Ich hatte immer die falschen Atari 520 ST und nicht Commodore 64

**Comment by Schimmelreiter** [comment]
Dann hattest Du immerhin den gleichen Soundchip wie meiner:
Schneider/Amstrad CPC6128 hatte auch den AY.

**Comment by Schimmelreiter** [comment]
3-Kanal-Stereo: Links, rechts, beide/Mitte
Hatte ich damals tatsächlich schon über die Stereoanlage laufen :+1:

**Comment by sgse** [comment]
Ich bin erst mit 26  eingestiegen :) mein bester Kumpel war 14 und hat mich nass gemacht am PC

**Comment by Schimmelreiter** [comment]
Mit Tricks konnte man die Disketten hochformatieren ... 43 statt 40 Spuren und ich meine auch 10 statt 9 Sektoren/Spur.
War aber vom Laufwerk abhängig, nicht jedes Laufwerk hat Kopfbewegungen bis Spur 43 mitgemacht.

**Comment by sgse** [comment]
Genau :D 

Mein erster schlepptop hatte 33 MHz

**Comment by Schimmelreiter** [comment]
Außer vom themed background her paßt jetzt soweit alles:
![image](https://cloud.githubusercontent.com/assets/2022025/19708421/acc6a0ea-9b1e-11e6-9edd-b3127ea0d00b.png)

**Comment by sgse** [comment]
Dann zieh ich mal die Version runter wenn alles soweit drin ist und räume hier auf.

**Comment by Schimmelreiter** [comment]
Batman?

**Comment by sgse** [comment]
Neee der Horrorfilm

**Comment by Schimmelreiter** [comment]
Have you ever danced with the devil in the pale moonlight? :)
![image](https://cloud.githubusercontent.com/assets/2022025/19708568/c270462a-9b1f-11e6-9889-48291122bf03.png)

**Comment by sgse** [comment]
Sie ist glaub ich in meinem alter ;) muss mal schauen

**Comment by Schimmelreiter** [comment]
"Gotham" dürfte mal weitergehen ...

**Comment by sgse** [comment]
Sie ist älter aber nicht viel :D

**Comment by Schimmelreiter** [comment]
Wer ist in Deinem Alter?
Vicky Vale aka Kim Basinger?

**Comment by sgse** [comment]
ja

**Comment by sgse** [comment]
Kimila „Kim“ Anna Basinger [ˈbeɪsɪŋɡəɹ] (* 8. Dezember 1953 in Athens, Georgia)

**Comment by jbleyel** [comment]
Hi @Schimmelreiter / Schau mal durch wo das Problem mit dem Hintergrund noch ist. NUR bei deinem Theme ich ändere das dann für alle.

**Comment by Schimmelreiter** [comment]
eggplant, ui-darkness und suchend ...

**Comment by Schimmelreiter** [comment]
south-street, cupertino, da aber schlecht zu sehen.

mint-choc, le-frog, humanity, excite-bike, dot-luv

**Comment by Schimmelreiter** [comment]
Außerdem sind in eggplant in EPGRefresh die Farben bei der Auswahl von Favoriten/Kanälen kaum lesbar:

Ausgewählte Kanäle erscheinen weiß auf weiß, noch nicht ausgewählte hellgrau auf weiß:
![image](https://cloud.githubusercontent.com/assets/2022025/19728384/738b814a-9b93-11e6-90a0-5795bfdf5318.png)
