### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#402]
- mute picture
- improve protection (Kindersicherung)
- ...

**Comment by Schimmelreiter** [comment]
Farbe im AutoTimer:
![image](https://cloud.githubusercontent.com/assets/2022025/19826224/cdfdb190-9d85-11e6-8484-3c0737d6f853.png)

**Comment by Schimmelreiter** [comment]
Selbe Kombi auch im EPG-Refresh:
![image](https://cloud.githubusercontent.com/assets/2022025/19826248/1f22a454-9d86-11e6-8944-0e6306ddf9c8.png)

**Comment by Schimmelreiter** [comment]
Und der Screenshot von der Senderliste in der README ist nicht Up-To-Date :)

**Comment by Schimmelreiter** [comment]
"Openwebif Browser settings" und "Show Picon in channel list" darin sind nicht übersetzt.

**Comment by sgse** [comment]
Na ihr Nachteulen :)
@Schimmelreiter Sie haben Post :)

**Comment by rdamas** [comment]
"Improve protection" relates to issues #283, #184 and probably #276, 268?

Maybe this can be achieved in Python using decorators; an easy example:

```python
def grantAccess(func):
    def checkAccess(*args, **kwargs):
        # print "check access"
        if func.__name__ == 'doSomething':
            raise Exception('Access not granted')
        return func(*args, **kwargs)
    return checkAccess

@grantAccess
def doit():
    print "do it"

@grantAccess
def doSomething():
    print "do something"

try:
    doit()
except:
    print "You don't have access"

try:
    doSomething()
except:
    print "You don't have access"
```

This delegates checking access to a decorator function, which in this case will raise an exception, when you don't want to grant access if conditions are not met. Maybe we can capsule protection in a similar way to a wrapper/decorator function, without having to change the logic of the methods to be protected? Works pretty much like AOP in Java.

Just an (implementation) idea...

**Comment by jbleyel** [comment]
Sorry ..  my fault.
Protection means ->  Kindersicherung.
