### ISSUE TITLE
Zeitbalken im grafischen EPG verschiebbar

### ISSUE THREAD

**Issue by zeini1** [E2OpenPlugins/e2openplugin-OpenWebif#407]
Man kann nun in der grafischen EPG-Einstellungen auch einen Zeitbalken für die momentan laufenden Sender einblenden. Das muss man in den Einstellungen umstellen. Kann man diese Änderung der EPG-Ansicht nicht auch direkt im EPG auswählen? Rechts neben den Wochentagen wäre da genug Platz.

Außerdem wäre es schön, wenn man den Zeitbalken verschieben könnte, oder und die Wunschzeit des Balkens eingeben könnte. Sollte auch bei einem anderen Wochentag als beim aktuellen funzen.

**Comment by jbleyel** [comment]
Hier ein Mockup.

Für Mode 1 und 2 brauche ich noch treffendere Namen.
Vorschläge willkommen.

<img width="1179" alt="bildschirmfoto 2016-11-01 um 13 00 18" src="https://cloud.githubusercontent.com/assets/964927/19889097/4ec7bfe6-a033-11e6-92c7-45d116b67978.png">

**Comment by Schimmelreiter** [comment]
Mode 1:
eng.: TV Guide
deu.: Fernsehzeitschrift (Oder auch nur "Zeitschrift")

Mode 2:
eng.: Timeline
deu.: Zeitstrahl

Und:
Vertausch doch bitte noch die Zeilen für Datum und Uhrzeit.
Die Uhrzeit näher am Programm erscheint mir logischer, da die Uhrzeit ja nunmal schneller verläuft als das Datum.

**Comment by jbleyel** [comment]
Modus umschalten ist drin.

Nur mit der Zeitleiste scrollen geht nicht.
Allerdings kann man den kompletten Inhalt scrollen.

Prime Time ist in Arbeit.

**Comment by Schimmelreiter** [comment]
Kannst Du die Umschaltung des Anzeigemodus "Zeitschrift"/"Zeitstrahl" nach rechts verschieben?
Press an den Wochentagen dran sieht nicht so prall aus.

Warum kann man eigentlich nur eine Woche durchklitschen?
Ich meine die öffentlich-rechtlichen z.B. senden das EPG für bis zu 4 Wochen im voraus ...

**Comment by jbleyel** [comment]
Mehr als 7 Tage werde ich nicht einbauen.
Umschaltung nach rechts geht nicht so einfach wegen den buttons rechts.
