### ISSUE TITLE
Problems with channellist in desktop mode on iPhone

### ISSUE THREAD

**Issue by betacentauri** [E2OpenPlugins/e2openplugin-OpenWebif#408]
Hi,

I open WebIf in desktop mode on my iPhone. I can scroll up and down in the channel/bouquet list when I touch a bouquet name. But when I e.g. open first bouquet with 50 channels, I cannot scroll down. I always see the first 10-20 channels.

Tested with OpenATV 5.3 (with default bouquets).

**Comment by Schimmelreiter** [comment]
Me <- Android :)

**Comment by jbleyel** [comment]
This is not reproducable on my iPhone 6 (iOS10) but the desktop version is not really for phone display's.

It's only for desktops or tablets.

There is no plan to optimize the desktop version for mobil phones.

You can use e2remote for example. (Schleichwerbung)

**Comment by Schimmelreiter** [comment]
Moment, einen hab ich noch:
![image](https://cloud.githubusercontent.com/assets/2022025/19889035/f967f8a4-a032-11e6-942e-13ee2d23d2ea.png)

***vbeg***

**Comment by betacentauri** [comment]
:-(

And how to start streaming/transcoding in mobile version? I can only switch channel and create a timer. Or what do I miss?

**Comment by jbleyel** [comment]
Transcoding start is possible, this should be not a big problem.
I will take a look.

Timer creation too, but prio very very low.

**Comment by Schimmelreiter** [comment]
Indeed, mobile view lacks buttons for streaming/transcoding.

**Comment by jbleyel** [comment]
Hi @Schimmelreiter, kannst du das mit dem transcoding für mobil machen?

**Comment by Schimmelreiter** [comment]
But I can scroll, open, stream just nice using the desktop version ... though my video player seems to lack a way to query credentials, so the downloaded link file is useless.

**Comment by Schimmelreiter** [comment]
Nope.
1. Ich schiebe doch schon die ganze Zeit Web-Design auf Dich ab, was glaubst Du, wieso ich das mache? :)
2. Der Grund, wieso betacentauri streamen und transkoden will ist der, daß das Transcoding in OpenATV grad im Ar.... ist und er will's - auch auf meine Bitte hin - debuggen.
Er muß also erst fertig werden, damit ich sowas testen könnte, also ist das ein ein-Loch-ist-im-Eimer-Problem.

**Comment by jbleyel** [comment]
Dann mach ich das.

**Comment by Schimmelreiter** [comment]
Da hör' ich Dich!

**Comment by Schimmelreiter** [comment]
Wenn Du jemals Deine App für richtige Smartphones gemacht hättest, würde ich im Gegenzug glatt Schleichwerbung dafür machen :)

**Comment by betacentauri** [comment]
Timer kann man erstellen. Es fehlen "nur" die Links für Streaming und Transcoding.

Ich glaub ich muss mal mein iPhone 6 aktualisieren. Vielleicht liegt es an der alten Version, dass es nicht geht....

**Comment by jbleyel** [comment]
Hi @betacentauri , ich bau mal was ein.
