### ISSUE TITLE
Autotimer improvement suggestions

### ISSUE THREAD

**Issue by Priskvark** [E2OpenPlugins/e2openplugin-OpenWebif#409]
Thank you for all your efforts creating this new UI. It’s really great!

May I make this “tiny” suggestion about one of the components the AutoTimer layout.
Autotimer is essentially made of two parts, the list of items to the left and the details about each item to the right.

To improve the readability shouldn’t there at least be a vertical line between the sections?

But it may even be possible to improve the layout further. The list has virtually no limits in size and would be awkward to handle when it is populated with more items than 20-30. When you select an item at the end of the list you can no longer view its details because they are “scrolled” out of sight.

Would it be possible to define a separate scroll region for the left part, the list, and always keep the item details in sight at the right side of the layout?

This really is an issue for me keeping quite fair amount of autotimers in the list…

**Comment by jbleyel** [comment]
i will do my best

**Comment by Priskvark** [comment]
Then I am shore it will be a very nice solution!
