### ISSUE TITLE
2 timers at exactly the same day and time are handled simultaneously in “Timerlist”, Bug.

### ISSUE THREAD

**Issue by Priskvark** [E2OpenPlugins/e2openplugin-OpenWebif#410]
How to reproduce:
* Add two timers from different channels at exactly the same date AND time (start and stop time).
* Open the Timerlist in OWIF.
* Click “Disable timer” for one of the timers with the same time. Now you can se that the other timer also changed to “disabled”. The same result if you enable it.

**Comment by jbleyel** [comment]
investigating ........

**Comment by jbleyel** [comment]
Found !!
Will be fixed soon.

**Comment by jbleyel** [comment]
closed with https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/2032e0f034044181ca441cddd6cf2c5f565828df
