### ISSUE TITLE
Disabled timers, unexpected behavior

### ISSUE THREAD

**Issue by Priskvark** [E2OpenPlugins/e2openplugin-OpenWebif#411]
Pending timers in Timerlist (marked Disabled) get status Finished even though the timer has not yet passed the programmed event. Should it not have status waiting?

**Comment by jbleyel** [comment]
Here is the code of timer state.

```
							#if $timer.state == 0
								$tstrings['waiting']
							#elif $timer.state == 2
								$tstrings['running']
							#elif $timer.state == 3
								$tstrings['finished']
							#end if

```

**Comment by jbleyel** [comment]
wrong issue ...

**Comment by jbleyel** [comment]
Hi @Priskvark .. thanks for the tests.
