### ISSUE TITLE
senkrechter Laufbalken im EPG links plazieren und Senderfokus bei Tagwechsel

### ISSUE THREAD

**Issue by zeini1** [E2OpenPlugins/e2openplugin-OpenWebif#412]
Im EPG ist der senkrechte Laufbalken am äußerst rechten Rand (Achtung ich meine den Laufbalken innen für das EPG, nicht den für den gesamten Schirm). Hat man nun mehr Sender im gewählten Favoriten als der Bildschirm anzeigen kann, sieht man vorerst den rechten Laufbalken nicht. Er wird erst sichtbar wenn man mit dem unteren waagrechten Laufbalken ganz nach rechts geht.
Ich denke, dass es besser wäre diesen Laufbalken links vom EPG zu plazieren. Und er soll weiterhin sichtbar bleiben, auch wenn man weiter auf die äußeren rechten Sender scrollt.

Steht man jetzt im EPG bei einem Sender, der nicht auf der ersten linken Seite sich befindet, sondern man hat mit dem Laufbalken unten rechte Sender eingeblendet und wechselt jetzt den Wochentag, dann sollte weiter der Fokus auf den gleichen Sendern bleiben, die man gerade angezeigt bekommen hatte. Derzeit wechselt das Fenster zwar im gleichen Bouquet, geht aber immer auf die ersten Sender die sich links befinden.

**Comment by jbleyel** [comment]
Das Problem mit dem Wechsel vom Tag ist schon immer so und bedarf etwas mehr Aufwand.
Ohne Garantie das das umsetzbar ist.

**Comment by jbleyel** [comment]
Der Scrollbalken links ist nicht üblich und löst das Problem nicht.
Allerdings sollte der Scrollbalken für (Hoch/Runter) nicht ganz rechts sein.

Hier reagiert jeder Browser anders.
Wir brauchen da einen Screenshot und die Info.
Welcher Browser und welches OS.

**Comment by zeini1** [comment]
Der rechte Laufbalken für den EPG ist auf keinem Browser zu sehen, wenn ich nicht ganz rechts im EPG stehe. Hier mal 3 Screenshots vom Firefox, IE11 und Opera
![firefox_openwebif_ohne_rechten_laufbalken](https://cloud.githubusercontent.com/assets/23186640/19926285/f991b02e-a0f3-11e6-862b-83b46b4dbb70.JPG)
![ie11_openwebif_ohne_rechten_laufbalken](https://cloud.githubusercontent.com/assets/23186640/19926286/f99e24da-a0f3-11e6-9737-42e8ecde73b9.JPG)
![opera_openwebif_ohne_rechten_laufbalken](https://cloud.githubusercontent.com/assets/23186640/19926287/f99e7548-a0f3-11e6-963d-a22795172cd9.JPG)

Erst wenn man ganz rechts im EPG steht, wird der sichtbar. Und der sollt imho immer sichtbar bleiben, auch wenn ich nicht ganz rechts stehe. Hier die 3 Browser, wenn ich ganz rechts stehe im EPG.
![firefox_openwebif_epg_mit_rechten_laufbalken](https://cloud.githubusercontent.com/assets/23186640/19926317/3509c592-a0f4-11e6-91e1-83dbdf84a2fc.JPG)
![ie11_openwebif_mit_rechten_laufbalken](https://cloud.githubusercontent.com/assets/23186640/19926318/350ff926-a0f4-11e6-9d41-52a4bb371460.JPG)
![opera_openwebif_mit_rechten_laufbalken](https://cloud.githubusercontent.com/assets/23186640/19926319/35138c58-a0f4-11e6-949e-e73fe956a74f.JPG)

**Comment by sgse** [comment]
Lösung 1, weniger als 8 Sender ;)

![tv](https://cloud.githubusercontent.com/assets/17575778/19927955/96eccc7a-a0fc-11e6-8c78-87b27d2af138.png)

Lösung 2 Java, Die Scrollbalken sind immer zu sehen, klickt man rechts auf ein Sender-picon, wird der Programminhalt mittig angezeigt (außer bei den ganz äußeren :) ).
Sprungmarken zur Primetime und weitere können selbst angelegt werden. Ich nutze den TV-Browser gern als Ergänzung zu OWIF.
  
![tv1](https://cloud.githubusercontent.com/assets/17575778/19927973/b56285b4-a0fc-11e6-82de-e9ac7fd0d427.png)

**Comment by jbleyel** [comment]
Hi @sgse
- Lösung 1 (Spassvogel)
- Lösung 2 kannste vergessen (nicht mit mir)

**Comment by jbleyel** [comment]
Hi @zeini1,
danke für die Screenshots.

Der äussere Scrollbalken rechts auf dem Bild kommt von der kleinen Auflösung.
Der innere rechte Scrollbalken ist in der Tat ganz hinten.

Ich schau mir das mal an ob der Scrollbalken links nicht doch eine Gute Idee ist.

**Comment by sgse** [comment]
Nur so nebenbei, links bringt er auch nur etwas wenn er **immer** sichtbar ist. Wenn man ein paar Sender nach rechts geht ist er auch wieder weg. Wenn es möglich ist ihn **immer** anzuzeigen sollte er **rechts** bleiben.

**Comment by sgse** [comment]
Nur so nebenbei, links bringt er auch nur etwas wenn er **immer** sichtbar ist. Wenn man ein paar Sender nach rechts geht ist er auch wieder weg. Wenn es möglich ist ihn immer anzuzeigen sollte er rechts bleiben.
Und den unteren Scrollbalken nach oben/permanent sichtbar.

**Comment by jbleyel** [comment]
Scrollbalken links geht nur über einen kompletten Umbau und ein 3rd party control.
Wenn sich jemand die Mühe machen will, das einzubauen, dann möge er sich bitte melden.
Ich habe da leider keine Zeit, denn das ist ein relativ grosser Aufwand.
Es kann sogar sein, das dann die fixed Header Funktion dabei flöten geht.

Sorry.
