### ISSUE TITLE
new-theme web-if & oscam_atv

### ISSUE THREAD

**Issue by RobvanderDoes** [E2OpenPlugins/e2openplugin-OpenWebif#415]
This issue is on current ATV (2016-11-02 on Xtrend 8k):
When Oscam_atv 1.2 11214 is active, the web-if shows:

```
web.Server Traceback (most recent call last):

ConfigParser.ParsingError: File contains parsing errors: /usr/keys/oscam_atv/oscam.conf [line 22]: '['
/usr/lib/python2.7/site-packages/twisted/web/server.py:190 in process
189
190
191
/usr/lib/python2.7/site-packages/twisted/web/server.py:241 in render
240
241
242
/home/oe1/nightly53/build-enviroment/builds/openatv/release/et8000/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+a08b1288b6-r0/git/plugin/controllers/base.py:173 in render
172
173
174
/home/oe1/nightly53/build-enviroment/builds/openatv/release/et8000/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+a08b1288b6-r0/git/plugin/controllers/base.py:286 in prepareMainTemplate
285
286
287
/usr/lib/python2.7/ConfigParser.py:324 in readfp
323
324
325
/usr/lib/python2.7/ConfigParser.py:546 in _read
545
546
547
ConfigParser.ParsingError: File contains parsing errors: /usr/keys/oscam_atv/oscam.conf [line 22]: '['
```
As soon as I disable Oscam, the WEB-IF is fine.
Maybe related: I use port #16002 for Oscam.

**Comment by Schimmelreiter** [comment]
You seem to have a lonely "[" in line 22, which causes parsing errors.
I do not have that in a fresh oscam-atv.

I'll wrap the parsing attempt inside try except, but the root cause is something wrong in your oscam.conf, which makes ConfigParser fail but that oscam still accepts.

**Comment by RobvanderDoes** [comment]
> You seem to have a lonely "[" in line 22

Indeed there was, and deleting it fixes the issue.
Nevertheless: a configuration that's fine for Oscam itself, should also be fine for the web-if.

**Comment by RobvanderDoes** [comment]
But: issue closed, was a user-error.

**Comment by Schimmelreiter** [comment]
Fixed with https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/9d94d9769254dcfc043d811db8b533ab31743027
Simply using our oscaminfo code :)

**Comment by RobvanderDoes** [comment]
Thanks for the swift solution.
