### ISSUE TITLE
Bedienung funktioniert mit Win7 IE11 nicht bzw. nur teilweise....

### ISSUE THREAD

**Issue by iPkay** [E2OpenPlugins/e2openplugin-OpenWebif#417]
1. Bildschirmfoto (unterhalb FB) geht nur 1x nach Start dann nicht mehr - oberhalb vom Schnappschuss funktioniert es weiterhin
 2. FB leitet Befehle nicht weiter. Beispielsweise MyMetrixLite (openATV) öffnen bekommt man noch hin (grün -> Pfeiltasten -> ok-Taste), dann grün für Anwenden übernimmt er nicht mehr bzw. gibt es nicht an die Box weiter. (Bild aktualisiert, Aktion wird nicht ausgeführt) -> ab diesem Zeitpunkt spinnt die FB komplett (nur sporadisch bzw. wie beschrieben)

Gegentest mit Firefox ergab keine dieser Probleme.

**Comment by jbleyel** [comment]
Fehler 1. ist gefixt in einem der nächsten commits.

**Comment by Schimmelreiter** [comment]
Der 2. Fehler wird ein Riesenspaß zu debuggen:
Schaltet man die Entwicklertools ein, dann ist der Fehler nämlich weg.
Sobald man sie wieder ausschaltet, ist er wieder da.

Meines Erachtens gehört der IE einfach nur verboten.

**Comment by jbleyel** [comment]
Bitte man testen ob der Fehler bei Screenshot Hacken AUS auch da ist.

**Comment by Schimmelreiter** [comment]
Ja, ist er.
Aber irgendwie ist es so, daß hin und wieder doch ein FB-Befehl durchkommt.
So ungefähr jeder 10.

**Comment by Schimmelreiter** [comment]
Fehler besteht übrigens auch in Edge 14.

**Comment by jbleyel** [comment]
Ich fasse mal zusammen:
Nur IE11 oder Edge, nur bei Debug aus und egal ob Screenshot an oder aus.
Richtig?

**Comment by Schimmelreiter** [comment]
Richtig.

**Comment by Schimmelreiter** [comment]
```
-	var jqxhr = $.ajax( url ).done(function() { 
+	var jqxhr = $.ajax({ url: url, cache: false, async: false}).done(function() { 
```

heißt das jetzt, daß wegen dem schrottigen IE auf allen Browsern weniger gecached wird als eigentlich möglich wäre?
Oder wäre das nie aus dem Cache gekommen, nur dem IE muß man es explizit sagen?

**Comment by jbleyel** [comment]
Nein, genau anders. Der IE hat die Seite aus dem Cache geholt und den Request nicht zur Box gesendet. Daher hat jede Taste immer nur ein mal funktioniert.
Alle anderen Browser haben die ajax requests immer zu box gesendet, so wie es sein sollte.

Die ajax Request dürfen nicht gechached werden, sonst würdest du immer alte Daten bekommen.
Ich hab noch nicht alle geändert, daher kann es durchaus sein, das die eine oder andere Funktion die mit $.ajax Daten von der Box holt, beim IE nur ein mal geht und dann die Daten aus dem Cache holt.

**Comment by Schimmelreiter** [comment]
Ah, ok.
Dann: Weitermachen! :)
