### ISSUE TITLE
Responsiveness of selecting "all channels" element in Bouquet Editor

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#419]
If you select a channel item in Bouquet Editors "All Channels" list after narrowing down the list by a search, selecting a channel item is deadly slow.

![bildschirmfoto 2016-11-04 um 19 49 03](https://cloud.githubusercontent.com/assets/15088943/20018413/de111ca6-a2c7-11e6-96ae-20337a6f8d9f.png)

The screenshot is from Firefox Javascript Profiling Console. 

I have no idea what happens here in jQuery and jQuery UI - do you? 

I'd say low priority.

**Comment by jbleyel** [comment]
Chrome : -> 
<img width="964" alt="bildschirmfoto 2016-11-04 um 20 03 48" src="https://cloud.githubusercontent.com/assets/964927/20018849/d7f35a44-a2c9-11e6-9d78-0c7b688d0ed5.png">

**Comment by jbleyel** [comment]
Search event is here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/public/js/bqe.js#L702

and the function is here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/public/js/bqe.js#L480

**Comment by rdamas** [comment]
Searching text is not the issue (its fast enough); searching text and _then_ selecting an item is the issue. Selecting the item takes around 4 seconds here on my Macbook in the "All Channels" list.

**Comment by jbleyel** [comment]
Yes..it's reproducable.
We can do one thing.
Do not show/hide the list items.

Read all channels to a temp array and then display the list from the array.
Search text inside the array and build a result array then remove the complete list and redraw from filtered array.

**Comment by jbleyel** [comment]
Please check this. ;-)
[bqe.js.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/572806/bqe.js.zip)

**Comment by rdamas** [comment]
Eine Verbesserung um 1000% ;-) 👍

**Comment by jbleyel** [comment]
Hi @rdamas , wenn es dir langweilig ist, dann kannst du mal $.getJSON auf $.ajax umstellen.
Für die Requests auf der Linken Seite würde ich cache auf true stellen und für die rechts auf false.
An den Request auf der Linken Seite dann ?date=xxx anhängen und als xxx nur den Tag, das dürfte reichen. Als Basis kannst du ja meine neue nehmen.
Das min File mach ich dann.

**Comment by rdamas** [comment]
- $.getJSON eliminiert
- encodeURIComponent elimiert
- alles einmal getestet (hoffe, ich hab nichts übersehen)

[bqe.js.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/573306/bqe.js.zip)

**Comment by Schimmelreiter** [comment]
encodeURIComponent elimiert
^ Sicher, daß das so in Ordnung ist?

An vielen Stellen ist das wegen "Alternativen" drin, da müssen Gänsepaddels uriencoded werden.

**Comment by rdamas** [comment]
Klar. Solange man die Argumente via $.ajax( url: ..., data { arg: gaensepaddelarg } ) übergibt, kümmert sich jQUery um das escapen oder url-encoden.

**Comment by Schimmelreiter** [comment]
Ok
Will nur nicht, daß das wieder kaputtgemacht wird :)

Gibt zwar genug Plugins, die den Nutzen von "Alternativen" kaputtmachen, aber beim OWIF war es meine erste Amtshandlung, das zu reparieren.

**Comment by rdamas** [comment]
Ich hab's jetzt nicht in jeder Kombination mit Betriebssystem und Browser getestet (Windows und IE z.B. kann ich auch nicht testen), aber überall sonst hat alles funktioniert, was ich getestet habe. Und ich bin durch hoffe ich alle Optionen einmal durchgegangen. Und da jQuery bei solchen Sachen eigentlich immer erfolgreich vom Browser abstrahiert, sehe ich keine Probleme.

Vielleicht möchtest Du selber auch noch einmal testen ;-)

**Comment by jbleyel** [comment]
Ich hab keine Fehler gefunden.
Ich teste es mal bei mir und dann mach ich den commit.
