### ISSUE TITLE
Broken image osminiplus?

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#420]
/plugin/public/images/boxes/

![tv27](https://cloud.githubusercontent.com/assets/17575778/20029130/b3197674-a344-11e6-92cb-2610f1a4ca74.png)
It is a .png file.

**Comment by Schimmelreiter** [comment]
It's a PNG and it's even transparent.

**Comment by Schimmelreiter** [comment]
Could we even delay moving around box and remote images until there are all and make that ONE commit?
It makes merging into oe-a more complicated because we have the images in branding, thus I need to stash all image changing commits there, so it would be better only one.

**Comment by jbleyel** [comment]
Die Box Images auf png und Transparenz umstellen ist nicht für jedes Bild eine gute Idee.
Ich würde sogar überlegen ob wir das einfach so lassen.
Ein Rahmen um den weissen Hintergrund sieht auch nicht so schlecht aus.
Da können wir alle jpegs so belassen.

Was meint ihr?

**Comment by Schimmelreiter** [comment]
Is mir wumpe, wir nutzen die Bilder von hier eh nicht.
Nur bitte möglichst wenig Commits für die Umstellung.

**Comment by jbleyel** [comment]
Was meinst du mit Bilder nicht von hier?

**Comment by Schimmelreiter** [comment]
oe-alliance hat keine Bilder im Paket OWIF, sondern im Paket oe-alliance-branding.
Deshalb können wir auch auf allen Boxen, sogar eigentlich baugleichen mit unterschiedlichen Gehäusen/Fernbedienungen, die richtige Box/Fernbedienung anzeigen, während sich OpenPLi und andere sich jedes Mal die Ohren beim Anpassen der owibranding.py brechen.

Nur: Jedes Mal, wenn hier ein Bild zugefügt wird, dann kommt das beim Merge auch rüber und muß gelöscht werden, daher: Nicht jedes einzeln committen, bitte!

**Comment by jbleyel** [comment]
Okay ... habs verstanden.
Wenn also ein Bild hier geändert wird, was schon da ist.
Dann ist das Wurst.

Nur Hinzufügen ist schlecht.

**Comment by Schimmelreiter** [comment]
Bin mir da nicht sicher.
Also bei allen Box- und Fernbedienungsbildern lieber mal Commits bündeln.
Kommt ja dabei nicht auf 'nen Tag an.

**Comment by jbleyel** [comment]
OK

**Comment by athoik** [comment]
Hi,

We need jpg image back please, now the image misses, because it searches for osminiplus.jpg in UI. 

Can somebody change convert png to jpg?

**Comment by jbleyel** [comment]
The jpg is back.

**Comment by athoik** [comment]
:+1:
