### ISSUE TITLE
Mobile - Exception beim Klick auf ein Bouquet in Favoriten

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#426]
Eine Exception im Mobile-Controller, beim Klick in Favoriten auf ein Bouquet.

```controllers/mobile.py:46
P_channels
46		channels['transcoding'] = getTranscodingSupport()
exceptions.NameError: global name 'channels' is not defined
```

**Comment by Schimmelreiter** [comment]
Mit welchem OWIF-Stand?

**Comment by rdamas** [comment]
Hab ich gestern aus dem Repo installiert. Schau Dir den Code in https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/mobile.py#L39 an - channels wird geschrieben obwohl nicht definiert!?

**Comment by jbleyel** [comment]
Ich fix das heut Abend

**Comment by Schimmelreiter** [comment]
Ich schätze, da fehlt in mobile.py die Zeile
`channels = getChannels(idbouquet, stype)`
vor
`channels['transcoding'] = getTranscodingSupport()`

Wie kann ich den Fehler reproduzieren, um zu prüfen ob das so ist?

**Comment by rdamas** [comment]
Ich hab einfach im Mobile-View auf Favoriten geklickt und dann auf ein beliebiges Bouquet. Da erscheint ein kleines Overlay mit "Error Loading Page", der Fehler wird aber geloggt, wenn Du Dir die Netzwerk-Requests anzeigen läßt.
