### ISSUE TITLE
Exception: exceptions.UnboundLocalError: local variable 'port' referenced before assignment

### ISSUE THREAD

**Issue by lukaswindner** [E2OpenPlugins/e2openplugin-OpenWebif#427]
I installed the latest version of the openwebif, than i got the following errors:

/usr/lib/python2.7/site-packages/twisted/web/server.py:190 in process
189
190
191
/usr/lib/python2.7/site-packages/twisted/web/server.py:241 in render
240
241
242
/home/oe1/nightly53/build-enviroment/builds/openatv/release/9900lx/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+d4e5d7c47f-r0/git/plugin/controllers/base.py:173 in render
172
173
174
/home/oe1/nightly53/build-enviroment/builds/openatv/release/9900lx/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+d4e5d7c47f-r0/git/plugin/controllers/base.py:303 in prepareMainTemplate
302
303
304
exceptions.UnboundLocalError: local variable 'port' referenced before assignment

**Comment by Schimmelreiter** [comment]
?
Why in line 303?

**Comment by rdamas** [comment]
Maybe you need to move "url" assignment down to `if webif:` clause. Maybe @lukaswindner doesn't have webif support compiled in?

**Comment by Schimmelreiter** [comment]
base.py checks the oscam.conf for a [webif] section.
There shouldn't be any when no webif support is present.

But oscam also has a default webif port of 8888 if no other port gets defined.

**Comment by Schimmelreiter** [comment]
... but I've now also included a check for oscams without webif (Who on earth would build such a crap?).

**Comment by Schimmelreiter** [comment]
Try latest version.

**Comment by lukaswindner** [comment]
i will try it tomorrow, than i will give you a feedback, if it works now ok not.

**Comment by lukaswindner** [comment]
it still the same :(
i have the build 2260

**Comment by Schimmelreiter** [comment]
Your oscam must be seriously borked.

Please paste the output of
`cat /tmp/.oscam/oscam.version`
(use telnet or ssh to enter this on your box)

**Comment by lukaswindner** [comment]
Version:        oscam-1.20-unstable_svn-r11108
Compiler:       mipsel-unknown-linux-gnu
Box type:       9900lx (generic)
PID:            1
TempDir:        /tmp/.oscam
ConfigDir:      /usr/lib/enigma2/python/Plugins/Extensions/camInfo/

Web interface support:                   no
LiveLog support:                         no
jQuery support intern:                   no
Touch interface support:                 yes
SSL support:                             no
DVB API support:                         yes
DVB API with AZBOX support:              no
DVB API with MCA support:                no
DVB API with COOLAPI support:            no
DVB API with COOLAPI2 support:           no
DVB API with STAPI support:              no
DVB API with STAPI5 support:             no
DVB API read-sdt charsets:               yes
Irdeto guessing:                         yes
Anti-cascading support:                  yes
Debug mode:                              no
Monitor:                                 no
Loadbalancing support:                   yes
Cache exchange support:                  yes
CW Cycle Check support:                  yes
LCD support:                             no
LED support:                             no
Clockfix with realtime clock:            yes
IPv6 support:                            no

camd 3.3x:                               no
camd 3.5 UDP:                            yes
camd 3.5 TCP:                            yes
newcamd:                                 yes
CCcam:                                   yes
CCcam share:                             yes
gbox:                                    yes
radegast:                                yes
scam:                                    yes
serial:                                  yes
constant CW:                             yes
Pandora:                                 yes
ghttp:                                   yes

Reader support:                          yes

Nagra:                                   yes
Irdeto:                                  yes
Conax:                                   yes
Cryptoworks:                             yes
Seca:                                    yes
Viaccess:                                yes
NDS Videoguard:                          yes
DRE Crypt:                               yes
TONGFANG:                                yes
Bulcrypt:                                yes
Griffin:                                 yes
DGCrypt:                                 yes

cardreader_phoenix:                      yes
cardreader_internal_azbox:               no
cardreader_internal_coolapi:             no
cardreader_internal_coolapi2:            no
cardreader_internal_sci:                 yes
cardreader_sc8in1:                       yes
cardreader_mp35:                         yes
cardreader_smargo:                       yes
cardreader_pcsc:                         no
cardreader_smartreader:                  no
cardreader_db2com:                       yes
cardreader_stapi:                        no
cardreader_stapi5:                       no
cardreader_stinger:                      yes

**Comment by Schimmelreiter** [comment]
**Web interface support: no**

Who on earth compiles such a pile of junk?
