### ISSUE TITLE
Mobile - "dlg is not defined"

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#428]
Und noch einer - diesmal ein Javascript-Error. Reproduzieren im Mobil-View:
* Klick auf Favoriten
* Klick auf ein beliebiges Bouquet
* Rechts neben einem beliebigen Kanal: Klick auf das Zahnrad (was soll da überhaupt passieren? Timer definieren oder so?)

```
Uncaught ReferenceError: dlg is not defined(…)
onclick @ channels?id=1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.a4e39.tv" ORDER BY bouquet:1
```

**Comment by Schimmelreiter** [comment]
Kriegt der Jörg ja doch noch was zum Fixen :)

**Comment by rdamas** [comment]
Das geht bestimmt schnell :)

**Comment by Schimmelreiter** [comment]
Dann mach Du doch ...
... nicht immer nur kaputtsuchen ;)

**Comment by jbleyel** [comment]
Bitte prüf mal die mobile/channels.tmpl, die ist wohl nicht aktuell.

**Comment by rdamas** [comment]
Hmm; das war das Problem - da muss ich mal schauen, was beim Kompilieren mit cheetah-compile auf dem Mac schief läuft.

**Comment by Schimmelreiter** [comment]
Ich habe da zwar keine Fehlermeldung, aber das Zahnrad tut gar nix.

**Comment by rdamas** [comment]
Jep, war bei mir auch so, den Fehler siehst Du nur in der Javascript-Konsole. 

Ich versteh immer noch nicht, dass es jetzt funzt - bis auf die __CHEETAH_-Kommentare sind die kompilierten .py-Files identisch. Muss ich jetzt nicht verstehen.

**Comment by rdamas** [comment]
Nochmal getestet - der Dialog kommt jeweils immer erst dann, wenn ich die Seite einmal neu lade. Beim ersten Öffnen tut sich nichts.

**Comment by Schimmelreiter** [comment]
Dann ist es vielleicht relatex zu meiner neuen Issue.

**Comment by Schimmelreiter** [comment]
#430

**Comment by jbleyel** [comment]
Der Fehler dlg not found ist bei mir auch, aber nur alle 10 mal.
Ich suche mal.

**Comment by jbleyel** [comment]
Ich versteh es nicht das Javascript im im template drin und wird ab und zu nicht geladen ???
HÄ??

**Comment by jbleyel** [comment]
Ich hab was gefunden.
Jquery mobile löscht script tags aus der Seite.

Schön das das bis jetzt niemand gemerkt hat.

**Comment by rdamas** [comment]
FYI: Zum Thema "jquery mobile löscht script tags aus der Seite" hab ich folgendes gefunden - vielleicht war der Fehler, dass die Script-Tags kein type-Attribut hatten?

https://bugs.jquery.com/ticket/6765

**Comment by jbleyel** [comment]
Hat er jetzt auch nicht, aber den Bug gibt es auf jeden Fall.
