### ISSUE TITLE
Mobile - mobile/timerlist ist nicht gestyled

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#429]
Und noch einer:
* Klick auf Favoriten
* Klick auf ein beliebiges Bouquet
* Klick auf einen bliebigen Kanal
* Unter "nachfolgende Sendungen" rechts auf den Pfeil klicken, um in die Event-View zu gelangen
* Dort Klick auf "Timerliste"
Dieser View fehlen zumindest die Style-Sheets.

**Comment by Schimmelreiter** [comment]
Herrlich wie einfach sich die Bugs für mich erledigen ... ***duckundwech***

**Comment by jbleyel** [comment]
Hi @rdamas / hast du bugs bei mobile, wenn ich schon mal dabei bin.
Die Timerliste hab ich gefixt.

**Comment by rdamas** [comment]
Nein, ich bin alles einmal durch und hab nichts mehr gefunden.

**Comment by Schimmelreiter** [comment]
Kann man eigentlich jquery nicht ins OWIF kopieren, damit man nicht vom Internet abhängig ist?

**Comment by jbleyel** [comment]
Du meinst jquery mobile?

**Comment by jbleyel** [comment]
Ich schau mal.
Das Problem wird das css sein.

**Comment by Schimmelreiter** [comment]
Alle externen Resourcen.
Wenn der Captain erfährt, daß das OWIf aktuell Internet erfordert, reißt er mir den Kopf ab.
Die Boxen müssen auch ohne laufen, daß wollen diverse Boxenhersteller so, die ATV mit ausliefern.

**Comment by jbleyel** [comment]
Ich bau es ein, aber testen muss es jemand anders.

**Comment by Schimmelreiter** [comment]
Wieso muss es jemand anderes testen?

**Comment by jbleyel** [comment]
Weil ich keine Zeit habe. ;-)

**Comment by Schimmelreiter** [comment]
Ach so.
