### ISSUE TITLE
uno4k

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#432]
/plugin/public/images/boxes/

![rect7055](https://cloud.githubusercontent.com/assets/17575778/20113391/940df5d0-a5f0-11e6-915f-06cc26cf7f7f.png)

comming soon, my second box :)

**Comment by jbleyel** [comment]
looks nice ;-)

**Comment by sgse** [comment]
[http://www.opena.tv/vu-uno-4k/29204-vu-uno-4k-die-ersten-original-bilder-von-hm-sat-shop-post257943.html#post257943](url)

**Comment by Schimmelreiter** [comment]
Viel zu teuer.
Wenn sie wirklich kommen sollte, kriegt man für wenig Geld mehr eine echte Dreambox (DM900).

**Comment by sgse** [comment]
**_Wenn ich von allem so viel hätte wie Geld ;)_** 
Die Händler schreiben 23/28.11.2016
Ich denke die halten sich noch geschlossener, was Treiber etc. angeht, als VU+?
Für Kabel reicht VU+ und mit meiner duo2 bin ich sehr zufrieden.
Dann noch ein NAS zu Weihnachten und **mehr Zeit** alles bisher aufgenommene schauen zu können :D .

**Comment by Schimmelreiter** [comment]
Bzgl. Issue:
Wenn die Box draußen ist, wird VTi das für VTi 10.x auch einpflegen. None of our businesses.
