### ISSUE TITLE
BoxInfo - TunerState wrong

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#435]
Shows two recordings for Passion XXX, which is of course wrong:
![image](https://cloud.githubusercontent.com/assets/2022025/20147286/c6caf9c0-a6a7-11e6-8fa9-3d2f1e10a562.png)

Tuner A is in fact still streaming and should show:
![image](https://cloud.githubusercontent.com/assets/2022025/20147326/eb4e0936-a6a7-11e6-9971-e648903b2d04.png)

The funny thing is: It did so, **before** the recording on Tuner B started.

Side note: The box is in playback, so no tuner used for Live TV ATM.

**Comment by rdamas** [comment]
There's another bug present at the exact same place; when playing a mkv (don't know if that is important) `'NoneType' object has no attribute 'getTransponderData'` is shown in the tuner section:

![screenshot](https://cloud.githubusercontent.com/assets/15088943/20149457/a427a1fc-a6b1-11e6-9981-c86372498ec7.jpg)

Sorry for hijacking your bug report :-)

**Comment by jbleyel** [comment]
Hi @rdamas  .. this error should fixed now.

**Comment by jbleyel** [comment]
Hi @Schimmelreiter  : no plan.

**Comment by jbleyel** [comment]
Hi @Schimmelreiter : wenn ich das bei mir nachstelle, dann passt die Anzeige.
* Box nur playback -> kein Tuner aktiv
* Box playback + Stream -> Der Stream wird angezeigt
* Box auf Sender A + Stream auf Sender B -> Beide Tuner werden richtig angezeigt

Das einzige was ich noch nicht geprüft habe ist ein aktiver Timer.

**Comment by Schimmelreiter** [comment]
Also ein Fehler scheint schonmal zu sein, daß der 1. Kabel-Tuner und der 1. Sat-Tuner vermengt werden:
![image](https://cloud.githubusercontent.com/assets/2022025/20244353/885264b0-a97e-11e6-97f8-96fdbc39bf0f.png)

Vivid kann natürlich nur auf Tuner A (Sat) sein, nicht aber auf Tuner E (Kabel).

**Comment by jbleyel** [comment]
Das ist doch eine Aufnahme oder nicht.
Hast du das Problem auch beim Stream, wenn keine Aufnahme läuft?

**Comment by jbleyel** [comment]
Pack mal diese info.py auf dein Box und schick mir das debug log.
Wenn die Boxinfo so aussieht, wie auf dem Bild.
[info.py.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/587725/info.py.zip)

**Comment by Schimmelreiter** [comment]
Ich habe die info.py mal mit gemerged.
Erstens werde ich nicht der Einzige mit dem Problem bleiben - im Gegenteil, ich werde da noch mit am wenigsten mit haben - und zweitens ist sie sonst längst wieder weg, wenn ich einen relevanten Status habe.

**Comment by sgse** [comment]
Auszug debuglog
[debug.txt](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/589042/debug.txt)

Siehe auch #422

**Comment by Schimmelreiter** [comment]
So, jetzt habe ich noch mal die Situation, daß mir zwei mit demselben Sender belegte Tuner angezeigt werden:
![image](https://cloud.githubusercontent.com/assets/2022025/21292452/a96e418e-c506-11e6-9d4e-5a2826b22de8.png)

Vivid wird tatsächlich gerade aufgenommen, aber sicher nicht mit zwei Tunern.
Ich vermute, daß der zweite Tuner in Wirklichkeit von einer EPGRefresh-Scheinaufnahme belegt wird.
Das deckt sich auch mit meinem CardServer, der gerade zwei verschiedene Sender entschlüsselt.

Debug-Output:
```
09:42:46.219 {   } plugin/controllers/models/info.py:339 getInfo [OpenWebif] -D- tuner '0' 'Vuplus DVB-S NIM(AVL6222)' 'Tuner A'
09:42:46.220 {   } plugin/controllers/models/info.py:339 getInfo [OpenWebif] -D- tuner '1' 'Vuplus DVB-S NIM(AVL6222)' 'Tuner B'
09:42:46.220 {   } plugin/controllers/models/info.py:339 getInfo [OpenWebif] -D- tuner '2' 'Vuplus DVB-S NIM(AVL6222)' 'Tuner C'
09:42:46.221 {   } plugin/controllers/models/info.py:339 getInfo [OpenWebif] -D- tuner '3' 'Vuplus DVB-S NIM(AVL6222)' 'Tuner D'
09:42:46.222 {   } plugin/controllers/models/info.py:339 getInfo [OpenWebif] -D- tuner '4' 'Sundtek DVB-C (III) (1/0) (USB)' 'Tuner E'
09:42:46.222 {   } plugin/controllers/models/info.py:339 getInfo [OpenWebif] -D- tuner '5' 'Sundtek DVB-C (III) (2/0) (USB)' 'Tuner F'
09:42:46.372 {   } plugin/controllers/models/info.py:513 getInfo [OpenWebif] -D- streamList count '0'
09:42:46.372 {   } plugin/controllers/models/info.py:527 getInfo [OpenWebif] -D- s_name ''
09:42:46.372 {   } plugin/controllers/models/info.py:538 getInfo [OpenWebif] -D- timer 'Vivid'
09:42:46.373 {   } plugin/controllers/models/info.py:546 getInfo [OpenWebif] -D- recs count '2'
```

**Comment by jbleyel** [comment]
Dann ist jetzt die Frage, ob wir das Problem überhaupt fixen können.
Das Problem ist das recs array, denn dort sind 2 objekte drin.

**Comment by Schimmelreiter** [comment]
Geht das ggf. per Plausibilitätskontrolle?
Die Aufnahme, die keine ist, gehört i.d.R. EPG-Refresh, so oder so ist es aber keine Aufnahme.

**Comment by jbleyel** [comment]
Wenn man das in dem recs array rausbekommt, dann geht das.
Eine Abfrage ob gerade EPGRefresh läuft würde ich eher nicht empfehlen.

**Comment by Schimmelreiter** [comment]
Ich werde aus dem Debug-Output nicht wirklich schlau ...
Ich sehe da nur, daß es zwei Aufnahmen geben *soll*, aber bei timer nur einen String.

Also jetzt mal ins Unreine gesprochen:
Wenn das Array sagt "2 Recordings", aber es gibt keinen zweiten Namen, dann muß der doch leer sein, oder?
Kann man nicht leere Namen einfach als "Fake Recording" anzeigen lassen?
Dann ist es wurscht, woher diese Aufnahme kommt.
Echte Aufnahmen sollten aber doch wohl immer einen Namen haben, oder sehe ich das falsch?

**Comment by jbleyel** [comment]
Das geht leider nicht so einfach.
Der Name des Senders kommt entweder aus einem Timer oder aus einem Stream.
Man könnte natürlich hier -> 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/info.py#L548
in der Schleife nur den 1. Eintrag nutzen und dann raus gehen.

Aber nur in der Annahme, das das 1. Objekt in recs auch eine Aufnahme ist.

**Comment by jbleyel** [comment]
Mit anderen Worten ..
hier -> 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/info.py#L555
aus der for Schleife für recs raus.

**Comment by jbleyel** [comment]
Allerdings sind bei dir vermutlich wirklich 2 Tuner belegt.
Nur das der Sendername nicht stimmt.

Es kann also sein das der Sender den 2. Tuner belegt und das Fake Recording belegt den 1. Tuner.

Theoretisch. !!

**Comment by Schimmelreiter** [comment]
Mal andersherum gefragt:
Wie kommt der eigentlich bei der zweiten Aufnahme überhaupt auf "Vivid" als Sender?

Das ist doch der springende Punkt und das hüpfende Komma.
Eigentlich hat für eine der beiden Aufnahmen ein leerer String als Name zu kommen, da es eine Scheinaufnahme ist.
Unabhängig davon, ob es die 1. oder die 2. ist.

**Comment by Schimmelreiter** [comment]
Und: Ja, es sind zwei Tuner belegt.
Einer durch die Aufnahme und einer durch die Scheinaufnahme von EPG-Refresh (Der übrigens auch einen Hau hat und während einer laufenden Aufnahme seine Scheinaufnahme nicht beendet, jedenfalls klebte der die ganze Zeit auf demselben Sender, seh ich ja in oscam).

**Comment by jbleyel** [comment]
Letzteres ist mir eigentlich Wust.
Ich denke das liegt an der Implemetierung von dem Thread.
Der Autotimer hat übrigens auch ein ähnliches Problem.
Die beiden Schwerkraft Plugins haben das Problem übrigens nicht.

Der Name wird nicht aus der Aufnahme (recs) geholt, da der dort nicht drin steht und daher kann man das nicht so einfach machen.
Daher sieht die info.py auch so krank aus.
Wenn es mehrere Infos gibt, also mehrere Tuner belegt sind, dann braucht man eigentlich eine Glaskugel.

**Comment by Schimmelreiter** [comment]
Ok, dann vielleicht erst einmal zu wichtigeren Dingen:
Kriegst Du den AutoTimer sk:oe-a noch weiter synchronisiert, trotz dieses doofen Commits hier:
https://github.com/oe-alliance/enigma2-plugins/commit/f16ab523126b818ecb7cb09464a24b74a9644db2
?

Und ich weiß jetzt auch, wieso /autotimer/test nicht ging ... ganz einfach weil es in OWIF nicht als Child geputtet wird!
https://github.com/oe-alliance/e2openplugin-OpenWebif/blob/Theme/plugin/controllers/AT.py#L25-L30

Ich habe das testweise eingebaut und danach konnte ich /autotimer/test aufrufen.
Führt allerdings zu einem Crash.

Da wir ja jetzt wissen, wie's geht, können wir gerne da weitermachen, wenn/sobald Du Zeit hast :)

**Comment by jbleyel** [comment]
Jo der Commit ist extrem sinnbefreit.

existing und skipped ist das gleiche. *grrrr*

/test habe ich in meimen openwebif auch schon drin, bin aber nicht weiter gekommen.

Ich hab grad nicht viel Zeit.

**Comment by Schimmelreiter** [comment]
Ok, dann tu Dich mal melden tun, wenn Du mehr Zeit hast.
Fände das total toll, wenn wir zumindest mal bei den Kern-Plugins im Laufenden wären.

**Comment by jbleyel** [comment]
Können wir das zu machen?
