### ISSUE TITLE
EPG: Timeline scrollbar

### ISSUE THREAD

**Issue by AbuBaniaz** [E2OpenPlugins/e2openplugin-OpenWebif#441]
Is it possible to have the timeline scrollbar at the top, just below the timeline bar?

At the moment, you have to scroll all the way down to see it. The channel you were looking at will then not be viewable unless you have a very small bouquet or channel is at the bottom of bouquet. To see the channel, you will have to vertically scroll up.

Thanks in advance for considering.

![owif epg timeline](https://cloud.githubusercontent.com/assets/6644489/20242978/bc59a168-a93a-11e6-9aa8-54ec41ccd479.png)

**Comment by IanSav** [comment]
Rather than moving the scroll bar I suggest that both the horizontal and vertical scroll bars be taken out of the EPG grid and be available at all times.  See Issue #457
