### ISSUE TITLE
disable root logins on the web interface

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#443]
Hi all,
I'm trying to disable root logins on the web interface.
I have created a new user and enabled from the plugin config "disable root access".
However now i can login with both root and the new user.
Why it is not working?

Edision os mini combo with openatv 5.3, openwebif 1.0.3
by  http://www.opena.tv/plugins/29554-openwebif-disable-root-login-post261546.html#post261546

**Comment by Schimmelreiter** [comment]
Cached previous login probably.
I've just tried, it works as designed.

BTW: This does not affect the streaming login on OpenPLi, OpenATV, ... streaming allows root logins even if disabled for OWIF :(
