### ISSUE TITLE
WebTV: Missing last subdirectory of any current directory

### ISSUE THREAD

**Issue by Priskvark** [E2OpenPlugins/e2openplugin-OpenWebif#446]
In Web TV tab using Movie button:
If I choose Movies and click on “Select an Option” I can see just one subdirectory of the 2 allocated.
If I then go to the only subdirectory shown, no further subdirectories show up.
All subdirectories are shown if I select Movies tab in the Main menu. It seems to be an issue just in the Web TV tab.

**Comment by Schimmelreiter** [comment]
Not able to reproduce:
![image](https://cloud.githubusercontent.com/assets/2022025/20361706/e22a87da-ac38-11e6-8c8f-9f3fbd50bc00.png)

And inside "Serienreste":
![image](https://cloud.githubusercontent.com/assets/2022025/20361726/fa8f3550-ac38-11e6-90a4-73fa8961ff40.png)

**Comment by Priskvark** [comment]
OK, the analysis could be more thorough…

Could you please check if this new information can help finding the problem (and hopefully we use the same version).

It’s the “last” subdirectory that is hidden. When I have just one subdir nothing gets visual. While 2 shows the first.

It’s like that even in the root directory of my hard drive if I try to browse from there.

I don’t know what directories you have on your box so I can’t tell from you pictures.

**Comment by Schimmelreiter** [comment]
Yes, I can reproduce **that**.
