### ISSUE TITLE
Offline themes

### ISSUE THREAD

**Issue by Tony-il-Capo** [E2OpenPlugins/e2openplugin-OpenWebif#449]
Hi
The other day OpenWebif was not opening, hanging, internet somehow was down, then I realized that it was trying to connect to 'googleapis' because of the theme.

I think it's not a good idea to get themes from external sources. Would be nice to have the new themes available for offline use, many people have their E2 boxes on LAN only setups, this adds an internet dependency.

Of course there's always the original theme to use but that should not be the fix for the problem.

**Comment by jbleyel** [comment]
The original theme needs no internet.
All other themes needs internet only for the first time and should use the browser cache otherwise.

**Comment by Tony-il-Capo** [comment]
Like I said before, making offline users use the original theme only doesn't seem like  real a solution...
There's should be a warning on OpenWebif settings about this.

If there's no internet connection I can't even connect to OpenWebif if I configured it before to use one of the new themes,  browser hangs like forever.

**Comment by Schimmelreiter** [comment]
@jbleyel : What did I tell you? :)

**Comment by Schimmelreiter** [comment]
@jbleyel 
Kann man einen Fallback machen? Wenn die Dateien für das gewählte Theme nicht geladen werden können, erfolgt Rückfall auf "original"?
Oder wie groß sind diese Themes? Sonst könnte man die ja auch ins OWIF mit reinnehmen oder das gewählte Theme nach /etc/enigma2/.owif runterladen ...

**Comment by jbleyel** [comment]
Ich schau mal wie gross ein theme ist und dann können wir entscheiden ob wir es reinlegen.
Das css wird wohl nicht das Problem sein, sondern die Bilder.

**Comment by Schimmelreiter** [comment]
Klingt nach Arbeit.
Wie wäre es mit Auto-Rückfall auf original und Ausblenden der Option bei fehlender Internet-Verbindung?

**Comment by jbleyel** [comment]
Nein, das geht so nicht.
Denn das css muss im header sein und dort kann man keine inet prüfung einbauen.
Das müsste der Browser machen und dafür müsste ein css tag eine art fallback haben.
Gibt es aber nicht.

**Comment by jbleyel** [comment]
Arbeit ist das mir dem offline nicht viel ich muss nur alle Images in einen Order kopieren.
Dann alle theme css umbenennen und auch in einen Ordner.

**Comment by Schimmelreiter** [comment]
Sollte nur nicht in die Megabytes gehen.

**Comment by Schimmelreiter** [comment]
Denk dran, nicht jeder hat eine Solo 4k mit weißnichtwieviel Flash.
Ich habe jetzt schon auf 128-MB-Boxen (z.B. die alte Duo) Probleme, die vernünftig einzurichten.

**Comment by jbleyel** [comment]
Der theme Images Order hat aktuell 34 KB.
Wenn ich alle Images rein kopiere sind es 1,4 MB.

Allerdings kann man die Icon Images die eine ähnliche Farbe haben auch konsolidieren.
Jedes Image für die Icons hat ca. 6KB und ich hab beim Überfliegen ca. 5 fast gleiche Gelbtöne gefunden.

d.H. wir kommen am Ende vermutlich auf ca. 500KB oder sogar weniger.

Das CSS für jedes Theme ist comprimiert ca. 14 KB.
Somit sind das dann noch mal ca. 300KB.

Das ist doch nicht so viel wie ich anfangs dachte.

**Comment by Schimmelreiter** [comment]
Kann man die nochmals optimieren, indem man aus den CSS rausstreicht, was nicht benutzt wird?
Geht sowas automatisch?
Und bei den Bildern: Dieser eigentlich störende Farbverlauf im Hintergrund bei z.B. eggplant, ist das vielleicht auch ein Bild? Das kann auf jeden Phall weg!

**Comment by jbleyel** [comment]
Der Farbverlauf ist nur ein paar byte groß, da lohnt sich der Aufwand nicht.

**Comment by Schimmelreiter** [comment]
Ok.
Das ist eh allein Deine Baustelle, ich habe da rein gar keine Ahnung von.

**Comment by Schimmelreiter** [comment]
Hehe

**Comment by Schimmelreiter** [comment]
Geht doch, **geht doch**.
:)

**Comment by jbleyel** [comment]
So toll ist die Lösung aber nicht.

**Comment by Schimmelreiter** [comment]
Ich find's ok.
Die meisten dürfte es ja eh nie treffen.

Ein alert wäre vielleicht ganz nett, damit der User weiß, warum er wieder "original" zu sehen bekommt.

**Comment by Tony-il-Capo** [comment]
From what I could understand that is not a real solution but more like a 'workaround' (fallback to original theme)

A real solution would be a **full standalone** and **fully featured** web interface, no need for external sources (internet) to get extra features (eg. themes) working

**Comment by Schimmelreiter** [comment]
It is a lot.
Even boxes with 128 MB of Flash have already reached a critical point with some images/setups.

And then we still have those die-hard DM800/DM800se clones around ...

**Comment by Schimmelreiter** [comment]
Doesn't work.
Does *always* reset to original.

**Comment by Tony-il-Capo** [comment]
I have a GI Avatar 2 with 128 MB flash, running OpenATV 5.3 with some 3rd party plugins installed and I still have around 50 MB of free space, a box less than 128 MB then it's a bigger problem.

**Comment by jbleyel** [comment]
I have collected all theme images and i think we can reduce the size.
Some of the jquery UI image files are very similar.
This needs some modifications.

**Comment by Schimmelreiter** [comment]
*If* the current workaround works, I think we should live with it for the moment and finish Web TV first.
Else we get too many construction sites at the same time.

**Comment by jbleyel** [comment]
Step 1 -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/6fa2db0c40ddd5a572db6e97106e62e4e51c4f35

**Comment by Tony-il-Capo** [comment]
@jbleyel Great job, many thanks.
