### ISSUE TITLE
FanControl2

### ISSUE THREAD

**Issue by RobvanderDoes** [E2OpenPlugins/e2openplugin-OpenWebif#453]
Would it be possible to add an extra entry for FanControl2 when it's installed (IP-box/fancontrol), just as is the case for Oscam, L4L and several other plugins?

**Comment by jbleyel** [comment]
It will be the right time to discuss about openwebif plugins.
A base feature for plugins are already included but not finished yet.
There is was also a missing example plugin.

I have planed a first plugin and move the package manager feature out of the openwebif into this first plugin.

!!!! PLANED !!!!!

**Comment by RobvanderDoes** [comment]
Thanks.

**Comment by jbleyel** [comment]
Hi @RobvanderDoes, please try the new 1.1 branch version.
It's not the right way but should work as new browser window.

The webif of the fancontrol needs a complete rebuild to use it as inline feature like autotimer. 
The current webif of fancontrol is crappy and from the last century. ;-)

**Comment by RobvanderDoes** [comment]
Hmmm, sorry to say, but I copied all the files from the plugin-folder of the 1.1 branch to my box and no Fancontrol2 shows up under 'Extra's'.

**Comment by jbleyel** [comment]
please call ../api/external and provide the result here

**Comment by jbleyel** [comment]
The current solution will only work if you have only the openwebif installed and NOT the Webinterface plugin.

**Comment by RobvanderDoes** [comment]
> please call ../api/external and provide the result here

web.Server Traceback (most recent call last):
exceptions.TypeError: FilePath('/usr/lib/enigma2/python/Plugins/Extensions/FanControl2/data') is not JSON serializable
/usr/lib/python2.7/site-packages/twisted/web/server.py:190 in process
189
190
191
/usr/lib/python2.7/site-packages/twisted/web/server.py:241 in render
240
241
242
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py:152 in render
151 request.setHeader("content-type", "text/plain")
152 request.write(json.dumps(data))
153 request.finish()
/usr/lib/python2.7/json/__init__.py:244 in dumps
243
244
245
/usr/lib/python2.7/json/encoder.py:207 in encode
206
207
208
/usr/lib/python2.7/json/encoder.py:270 in iterencode
269
270
271
/usr/lib/python2.7/json/encoder.py:184 in default
183
184
185
exceptions.TypeError: FilePath('/usr/lib/enigma2/python/Plugins/Extensions/FanControl2/data') is not JSON serializable

**Comment by jbleyel** [comment]
Okay .. the loaded_plugins var is not empty.
For testing i have called 
loaded_plugins.append( ("fancontrol", None, "Fan Control 2", '11') )
in base.py of openwebif and i get the menu entry.

Strange ????

**Comment by jbleyel** [comment]
I think there is a little bug near by
https://github.com/OpenPLi/enigma2-plugins/blob/master/fancontrol2/src/plugin.py#L1253

If you only call this ..
addExternalChild( ("fancontrol", root) )

**Comment by RobvanderDoes** [comment]
But I use https://github.com/oe-alliance/enigma2-plugins/tree/2.3/fancontrol2

**Comment by jbleyel** [comment]
It's the same code.

Do you have this file on your box?
/usr/lib/enigma2/python/Plugins/Extensions/WebInterface/web/external.xml

Do you have this file?
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/pluginshook.src

And is this
/usr/lib/enigma2/python/Plugins/Extensions/WebInterface/WebChilds/Toplevel.py
File exactly the same like this
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/pluginshook.src

**Comment by jbleyel** [comment]
The fancontrol writes logs -> FClog 
Please check the log for:
use new WebIF
use old WebIF
use new OpenWebIF

**Comment by RobvanderDoes** [comment]
Log has "use new OpenWebIF" entries.

> Do you have this file on your box?
> /usr/lib/enigma2/python/Plugins/Extensions/WebInterface/web/external.xml
> 
No: where should I get it from?

> Do you have this file?
> /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/pluginshook.src
> 
Yes

> And is this
> /usr/lib/enigma2/python/Plugins/Extensions/WebInterface/WebChilds/Toplevel.py
> File exactly the same like this
> /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/pluginshook.src

The first one is a symbolic link to the latter.

**Comment by RobvanderDoes** [comment]
> >     Do you have this file on your box?
> >     /usr/lib/enigma2/python/Plugins/Extensions/WebInterface/web/external.xml
> 

> No: where should I get it from?


Found it, but adding that makes no difference.

**Comment by jbleyel** [comment]
The log should say "use new OpenWebIF" if you have no external.xml .. this is correct.
The external.xml file existence means you have the DMM webinterface.

I will do some prints inside the openwebif for debugging.

**Comment by jbleyel** [comment]
please get the latest versio of 1.1 and check the debug output of base.py

**Comment by RobvanderDoes** [comment]
Now Fancontrol2 shows neatly under 'Extra's'.
Thanks!

**Comment by jbleyel** [comment]
Okay.. i close this issue here and remove the debug print.
