### ISSUE TITLE
Improve text for long press

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#455]
The text prompt below the button map is "(shift + click for long pressure)" this could be improved to "(Shift + Click for Long Press)" to better match the wording in the UI.

![keypad](https://cloud.githubusercontent.com/assets/6904736/20612429/f53b6566-b30d-11e6-9a03-42af43d15558.jpg)

**Comment by IanSav** [comment]
I can not see a commit with the fix for this issue.  Has this been closed because the item has been fixed?  If not, may I please know why the issue was closed.

If there is a problem with my report I would like to know so I can improve future reports.

**Comment by jbleyel** [comment]
-> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/f39adab3049eb60a8a0e0ad1d20bf5cfdb15196b
