### ISSUE TITLE
Some panels are too tall

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#456]
Some panels used to hold the payload (data) of the screen are drawn too tall such that the "credits" line is drawn outside the browser window triggering a scroll bar.

On short displays like the "Television" or "Radio" screens the panel holding the payload of the screen can easily fit within the window but the panel is shown full height and the "credits" area is drawn below the panel and outside the window causing an unnecessary vertical scroll bar.

This is an example of a problem screen "Television".  The scroll bar is used to gain access to the "credits" information even though the panel used for the payload only needs the top quarter of the window.
![television](https://cloud.githubusercontent.com/assets/6904736/20612797/9626a65e-b311-11e6-95f6-99df19f0e9a3.jpg)

This is an example of a working screen where the payload panel is sized to suit the payload such that the "credits" line can be shown within the window and a scroll bar is not required.
![epgrefresh](https://cloud.githubusercontent.com/assets/6904736/20612799/9c28926a-b311-11e6-9c7d-9f196ac8f0a9.jpg)

The browser window horizontal and vertical scroll bars should only be used as a last resort.  The payload scroll bars should be used in preference to give access to payload (data) that doesn't fit within the panel when the panel is at its maximum size within the current browser window.

**Comment by jbleyel** [comment]
This issue is well known, and needs some html reorg of the main page.
Not so easy.

**Comment by IanSav** [comment]
I now understand that this issue is well known.

Shouldn't there be an open issue so that new users, like myself, can see that the issue is already known.

**Comment by jbleyel** [comment]
This issue is fixed in version 1.1 -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/f8df3bbc5a4c1a8feac9403e3ca3431481f27fa1

**Comment by Schimmelreiter** [comment]
I've cherry-picked the two bug-fixes to master.
All other commits in 1.1-DEV seem to depend on the new structure.
