### ISSUE TITLE
Keep both horizontal *and* vertical EPG scroll bars visible at all times

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#457]
With the current EPG implementation for the "TV Guide" the horizontal scroll bar is kept on screen at all times and the vertical scroll bar is only visible when the horizontal scroll bar is set to the extreme right position. When in "Timeline" mode it is the vertical scroll bar that is kept on screen at all times and the horizontal scroll bar is only displayed when the vertical scroll bar is set to the extreme bottom position.

In both modes can the horizontal and vertical scroll bars please be drawn outside the EPG grid so that both scroll bars can remain visible at all times.

This is an image of the "TV Guide" scenario.  The similar situation exists for the "Timeline" version.
![epg](https://cloud.githubusercontent.com/assets/6904736/20613462/5e4012b4-b318-11e6-9bac-78d2abb637c7.jpg)

In the image above I drew the new vertical EPG scroll bar from the top of the EPG header line the bottom of the EPG footer line. In doing this I do NOT intend for the header or the footer to scroll. They should remain fixed as they are now.  If a full height vertical scroll bar is seen as inappropriate or too difficult then please resize it to fit the scrollable EPG data.

**Comment by IanSav** [comment]
In the image above I drew the new vertical EPG scroll bar from the top of the EPG header line the bottom of the EPG footer line.  In doing this I do NOT intend for the header or the footer to scroll.  They should remain fixed as they are now.

If a full height vertical scroll bar is seen as inappropriate or too difficult then please resize it to fit the scrollable EPG data.

**Comment by IanSav** [comment]
The above report has been updated to account for a related issue in both the "TV Guide" and "Timeline" modes.

**Comment by sgse** [comment]
It was fixed in 1.1.0? Example
![net7](https://cloud.githubusercontent.com/assets/17575778/20641111/6aca0038-b3f1-11e6-97b8-c8f29492fb44.png)

**Comment by IanSav** [comment]
Is there also a vertical scroll bar?  If not, can we please have one.

**Comment by sgse** [comment]
I use the mouse-wheel on PC and on tablet it was useless, my two cents.

**Comment by IanSav** [comment]
I also use the arrow buttons to move around.  :wink:

I think that having both scroll bars will allow users using a non scroll wheel mouse to better use the EPG.  (As developers we need to consider users who may do things differently from what we do or expect. :smile:)

**Comment by sgse** [comment]
It's always good to think of everyone :-)
arrow button  = never thought about :-D

**Comment by Schimmelreiter** [comment]
But mice without scroll wheel? Stolen from a museum or what?

**Comment by sgse** [comment]
Apple :-)

**Comment by IanSav** [comment]
They are out there.

**Comment by IanSav** [comment]
There have been a number of complaints about the scroll bars on the Beyonwiz forums.

(For most of the time we were stuck on an old build of OpenWebif.  We have only just switched to the 1.0.4 build.  I didn't want to raise the issues until we were using current code.)
