### ISSUE TITLE
Submenü direkt anzeigen, wenn ich auf einen Menüpunkt gehe

### ISSUE THREAD

**Issue by zeini1** [E2OpenPlugins/e2openplugin-OpenWebif#458]
Schön wäre es wenn ich links auf einen Menüpunkt gehe, dass sich hier sofort die Submenüs öffnen würden, so daß ich gleich so einen Submenüpunkt auswählen könnte. Also wenn ich zum Beispiel mit der Maus auf Fernsehen gehe, dass sofort angezeigt wird die Auswahlmöglichkeit - Aktuell - Favoriten - Anbieter - Satelliten - Alle Sender - EPG

Um es zu veranschaulichen wie ich das meine schaut euch mal folgende Seite an.
http://v55.hdfreaks.cc
Gehe ich hier links auf einen Boxenhersteller mit der Maus, dann öffnet sich sofort ein Submenü mit den Auswahlmöglichkeiten für die entsprechenden Boxen, für die hier ein Image downloadbar ist.

**Comment by sgse** [comment]
Für downloads praktisch aber hier wäre mir das zu hektisch ;-) , das Gezappel :-). 
Wenn ich an den Punkt "Einstellungen" denke, da würden bei mir aktuell 20 Untermenüs auf gehen, am PC noch machbar aber wie geht das am Tablet ohne Stift?

**Comment by Schimmelreiter** [comment]
Ich muß mich da sgse anschließen.
