### ISSUE TITLE
Timers not shown in all EPG views

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#460]
The EPG "Timeline" view does not have an indication of timers booked for any of the events in the grid.  (There is an indicator in the "TV Guide" view.)

Also the event details pop up does not indicate any indication of a timer being defined.

**Comment by IanSav** [comment]
On thinking about this some more.  Rather than using the red "Timer" flag would it be possible to set the background colour of the EPG grid cell to show that a timer is reserved.

The backgrounds could be:
- Red for a RECORD timer
- Green for a ZAP timer
- Yellow for a disabled timer
- Blue for an AutoTimer timer (if you can tell that the timer was created by an AutoTimer).

In Australia we have another timer type called IceTV.  I will ask one of the other developers if there is a way you can identify these timers.

**Comment by jbleyel** [comment]
TODO: color for different states

**Comment by jbleyel** [comment]
Hi @IanSav , can we close this issue?

**Comment by IanSav** [comment]
The issues / suggestions are still outstanding.
