### ISSUE TITLE
Bouquet filler data not being ignored/hidden

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#461]
The "Television" and "Radio" Bouquets lists do not ignore or hide "#SERVICE 1:832:D:0:0:0:0:0:0:0:" filler entries.  The filler entries create empty cells that consume space in the bouquet service list.

**Comment by jbleyel** [comment]
Please provide a screenshot.

**Comment by IanSav** [comment]
In Australia we commonly use LCN numbers as broadcast by the broadcasters.  Enigma2 does not respect these assigned LCN numbers so we commonly pad the bouquets with fillers to make the displayed LCNs match the broadcast assigned LCNs.  This filler data is corrupting the OpenWebif display.  (Hopefully a future version of Enigma2 will capture and use the broadcast LCN data.  This will eliminate our need for padding.)
![filler](https://cloud.githubusercontent.com/assets/6904736/20640509/a872cbbc-b433-11e6-8e58-767741f9418f.jpg)

**Comment by jbleyel** [comment]
i need the bouquet file of this bouquet.
-> /etc/enigma2/userbouquet....
The full filename of the bouquet file can be found here -> /etc/enigma2/bouquets.tv 

please provide this as zip here.

**Comment by IanSav** [comment]
The bouquet you need to examine is "userbouquet.terrestrial_lcn.tv".  The "userbouquet.terrestrial_lcn.radio" also uses filler data.  The others are simple bouquets but provided for completeness.

The system is not allowing me to add the ZIP file!   :(  I have placed the file on a web server for your access: [Bouquets.zip](http://users.tpg.com.au/iansav/Bouquets.zip)

**Comment by jbleyel** [comment]
fixed in 1.1 -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/fd74b1adec7c7a633717141141ac9192411015b1

**Comment by Schimmelreiter** [comment]
Jbleyel : Also have a look at #239 , it's related:
#239 asks for the ability to add those fillers in BQE which this request wants to be hidden in the station lists.

**Comment by IanSav** [comment]
I would be quite happy to see the request in #239 implemented.  It is complementary to this request.

For the bouquet displays like "Television", "Radio" etc don't show the markers but in the BouquetEditor they can be listed as a type "(H)" to match the "(M)" in the marker entries.

**Comment by Schimmelreiter** [comment]
They don't necessarily need to be visible for this to work (Makes the list ugly).
We need two things:
An option "Show channel numbers" yes/no and if set to yes a function "pad to channel number" + query for a number.
If the entered number is lower, equal or only one higher than the channel before, remove all fillers between selected and previous channel.
If the difference is >1, add as many fillers between previous chan and current chan to make current chan get this number.
