### ISSUE TITLE
Normal EPG view does not have a "Refresh" button

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#462]
When you maximise the EPG window there is a "Refresh" button shown to the left of the "Restore" button.  This "Refresh" button is missing from being next to the "Maximise" button in the normal EPG view.

**Comment by jbleyel** [comment]
What you mean with "normal" EPG?

**Comment by IanSav** [comment]
This is the maximised EPG view that has a Refresh button:
![maximisedepg](https://cloud.githubusercontent.com/assets/6904736/20640470/b8ae40ca-b432-11e6-8ba1-38635e4a9330.jpg)

This is the normal EPG view that is missing the Refresh button:
![normalepg](https://cloud.githubusercontent.com/assets/6904736/20640473/d0552356-b432-11e6-9f66-63fa13dd6c4d.jpg)

**Comment by jbleyel** [comment]
Should be fixed in 1.1
