### ISSUE TITLE
Enhancement: Allow a default EPG bouquet to be defined

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#465]
Could we please have an enhancement where a user can define a default bouquet in "Settings > OpenWebif Settings" that can be used as the default or starting bouquet in the EPG display.

As an alternative offer a check box ( [] Set as default ) on the right size of the bouquet line in the EPG display.

**Comment by IanSav** [comment]
I should also add (ask) if we can please also have a default view "TV Guide" or "Timeline" that is used by default for the EPG screen.

**Comment by jbleyel** [comment]
No so easy...

**Comment by IanSav** [comment]
Would it be easier to remember the last bouquet that was selected?

This would be an improvement while we wait for a nominated default.
