### ISSUE TITLE
Enhancement: Add a NOW button in the EPG display

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#466]
Could we please have a button labelled "Now" in the EPG display that positions the current time time line in the middle (or just to the left of the middle) of the screen.

The "Now" button could be located to the left of the day buttons at the top of the EPG display.

**Comment by jbleyel** [comment]
Screenshot for better understanding please..

**Comment by IanSav** [comment]
Does this image help?  If you want ore please ask.  :)
![now](https://cloud.githubusercontent.com/assets/6904736/20641215/72dd747a-b447-11e6-8aeb-459d56eecc3c.jpg)

By the way, thank you for your prompt attention to my comments and suggestions.  :smiley:  All your Australian users appreciate your help.

**Comment by jbleyel** [comment]
I will try to put this before "06:00" als 4th primetime

**Comment by IanSav** [comment]
Can you try putting "Now" at the end of the "Primetimes" list with a little space between "20:00" and "Now"?

I don't think "Now" looks right as a "Primetime".  :wink:

**Comment by jbleyel** [comment]
fixed in version 1.1
