### ISSUE TITLE
403.6 IP address rejected

### ISSUE THREAD

**Issue by fbradyirl** [E2OpenPlugins/e2openplugin-OpenWebif#467]
I am away from the house all week and I remotely upgraded the box using the virtual remote on Openwebif. 

After upgrade I cannot access any of the web interfaces including fan control, lcd4linux, etc. 

I get the following message in the browser:

"Forbidden

403.6 IP address rejected"

I am able to ssh to the box but couldn't find anything in the logs about this. Any ideas? Does the latest update use access control lists for accessing it?

OpenVix 4.2.018
Vu Duo2

Also reported here
http://www.world-of-satellite.com/showthread.php?54330-Getting-forbidden-on-web-interfaces&p=426658&viewfull=1#post426658

http://www.world-of-satellite.com/showthread.php?54336-403-6-IP-address-rejected&p=426703#post426703

**Comment by sgse** [comment]
OWIF has new secure settings, see screenshot from @Schimmelreiter 
![owipass](https://cloud.githubusercontent.com/assets/17575778/20641806/3ad0dc80-b400-11e6-9db0-2f87ccc17f7b.jpg)

**Comment by fbradyirl** [comment]
Thanks for this. Any way I can configure that over ssh remotely?

**Comment by Schimmelreiter** [comment]
You could use ssh port tunneling.

**Comment by jbleyel** [comment]
I think @fbradyirl .. will change the openwebif settings over ssh.

**Comment by Schimmelreiter** [comment]
He got help in the ViX forum.
Closed as this is desired behaviour.
