### ISSUE TITLE
Minor English corrections and suggestions

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#468]
In e2openplugin-OpenWebif/plugin/local.py there are a few items that you may want to consider changing / improving:
- Line 82 "'disabled': _("disabled"),", should this be "Disabled" to match the "Enabled" on line 94?
- Line 97 "'epgsearch': _("Epg Search"),", this should be "EPG Search" as EPG is an acronym.
- Line 102 "'finished': _("finished"),", should this be "Finished" to match the existing style?
- Line 109 "'gui_version': _("Gui version"),", this should be "GUI version" as GUI is an acronym.
- Line 119 "'info': _("Infos"),", would this be better as "Info" or "Information"?
- Line 125 "'loading': _("loading"),", should this be "Loading" to match the existing style?
- Line 138 "'no_description_available': _("no description available")," should this be "No description available" to match the existing style?
- Line 141 "'nothing_play': _("Nothing playing."),", should this be "Nothing playing" to match the existing style (no punctuation in the translation text)?
- Line 167 "'running': _("running"),", should this be "Running" to match the existing style?
- Line 176 "'seconds': _("seconds"),", should this be "Second" to match "Minute" on line 130?
- Line 208 "'timer_preview': _("Autotimer Preview"),", should this be "AutoTimer Preview" to match the existing style?
- Line 235 "'waiting': _("waiting"),", should this be "Waiting" to match the existing style?
- Line 239 "'zapbeforestream': _("zap before Stream"),", should this be "Zap before Stream" to match the existing style?
- Line 257 "'at_partial_match': _("partial match"),", should this be "Partial match" to match the existing style?
- Line 258 "'at_exact_match': _("exact match"),", should this be "Exact match" to match the existing style?
- Line 259 "'at_description_match': _("description match"),", should this be "Description match" to match the existing style?
- Line 260 "'at_title_or_description_match': _("title or description match"),", should this be "Title or Description match" to match the existing style?
- Line 261 "'at_title_or_short_description_match': _("title or short description match"),", should this be "Title or Short Description match" to match the existing style?
- Line 262 "'at_short_description_match': _("short description match"),", should this be "Short Description match" to match the existing style?
- Line 263 "'at_start_match': _("start match"),", should this be "Start match" to match the existing style?
- Line 265 "'at_case_sensitive': _("case-sensitive search"),", should this be "Case-sensitive search" to match the existing style?
- Line 266 "'at_case_insensitive': _("case-insensitive search"),", should this be "Case-insensitive search" to match the existing style?
- Line 268 "'at_record': _("record"),", should this be "Record" to match the existing style?
- Line 269 "'at_zap': _("zap"),", should this be "Zap" to match the existing style?
- Line 277 "'at_timer_offset': _("Custom offset"),", this should be "Custom margin" to match the prompt in the UI.
- Line 278 "'at_timer_offset_before': _("Offset before recording (in m)"),", this should be "Margin before recording (in minutes)" for clarity and to match the prompt in the UI.
- Line 279 "'at_timer_offset_after': _("Offset after recording (in m)"),", this should be "Margin after recording (in minutes)" for clarity and to match the prompt in the UI.
- Line 282 "'at_after_event_standard': _("standard"),", should this be "Standard" to match the existing style?
- Line 283 "'at_after_event_auto': _("auto"),", should this be "Auto" to match the existing style?
- Line 284 "'at_after_event_nothing': _("do nothing"),", should this be "Do nothing" to match the existing style?
- Line 285 "'at_after_event_standby': _("go to standby"),", should this be "Go to Standby" to match the existing style?
- Line 286 "'at_after_event_deepstandby': _("go to deep standby"),", should this be "Go to Deep-Standby" to match the existing style?
- Line 287 "'at_event_timespan': _('Execute "after event" during timespan'),", should this be "Execute "After event" during timespan" to match the existing style?
- Line 288 "'at_event_timespan_begin': _('Begin of "after event" timespan'),", should this be "Begin of "After event" timespan" to match the existing style?
- Line 289 "'at_event_timespan_end': _('End of "after event" timespan'),", should this be "End of "After event" timespan" to match the existing style?
- Line 291 "'at_left': _("Amount of recordings left"),", would this be better as "Number of recordings left"?
- Line 304 "'at_select_tags': _("select Tags"),", should this be "Select Tags" to match the existing style?
- Line 306 "'at_select_channels': _("select Channels"),", should this be "Select Channels" to match the existing style?
- Line 308 "'at_select_bouquets': _("select Bouquets"),", should this be "Select Bouquets" to match the existing style?
- Line 312 "'at_filter_title': _("in Title"),", should this be "In Title" to match the existing style?
- Line 313 "'at_filter_short_desc': _("in Shortdescription"),", should this be "In Short Description" to match the existing style?
- Line 314 "'at_filter_desc': _("in Description"),", should this be "In Description" to match the existing style?
- Line 315 "'at_filter_day': _("on Weekday"),", should this be "On Weekday" to match the existing style?
- Line 326 "'at_delete_autotimer_question': _("Do you really want to delete the AT")," should this be "Do you really want to delete the AutoTimer" for clarity?
- Line 331 "'ats_interval': _("Interval (in h)"),", should this be "Interval (in hours)" for clarity?
- Line 335 "'ats_show_in_extensionsmenu': _("Show in Extensionsmenu"),", should this be "Show in Extensions menu" for clarity?
- Line 340 "'ats_add_autotimer_to_tags': _("Add Autotimer to Tags"),", should this be "Add AutoTimer to Tags" to match the existing style?
- Line 348 "'ats_editor_wizzard': _("Wizzard"),", this should be "Wizard".
- Line 360 "'er_inherit_autotimer': _("Inherit Autotimer"),", should this be "Inherit AutoTimer" to match the existing style?
- Line 361 "'er_parse_autotimer': _("Parse Autotimer"),", should this be "Parse AutoTimer" to match the existing style?
- Line 398 "'via': _("via"),", should this be "Via" to match the existing style?
- Line 399 "'record_zap': _("Record+ZAP"),", should this be "Record + Zap" to match the existing style?
- Line 400 "'pmt_pid': _("Pmtpid"),", this should be "PMT PID" as this is an acronym and to match the UI.
- Line 401 "'a_pid': _("Apid"),", this should be "Audio PID" as this is an acronym and to match the UI.
- Line 402 "'v_pid': _("Vpid"),", this should be "Video PID" as this is an acronym and to match the UI.
- Line 403 "'pcr_pid': _("Pcrpid"),", this should be "PCR PID" as this is an acronym and to match the UI.
- Line 404 "'ts_id': _("Tsid"),", this should be "TSID" as this is an acronym and to match the UI.
- Line 405 "'on_id': _("Onid"),", this should be "ONID" as this is an acronym and to match the UI.
- Line 406 "'s_id': _("Sid"),", this should be "SID" as this is an acronym and to match the UI.
- Line 410 "'tstr_error_load_page': _("error! Loading Page"),", should this be "Error loading page" to match the existing style?
- Line 420 "'display_duration_s': _("Display duration (s)"),", should this be "Display duration (seconds)" for clarity?
- Line 429 "'using': _("using"),", should this be "Using" to match the existing style?

I have created this list for you to consider.  I did not want to make changes directly in case I have misunderstood the context or what you are intending to say.

**Comment by IanSav** [comment]
If you like, and to save you time, I can edit a copy of the file and post it back for your consideration.

**Comment by jbleyel** [comment]
Hi @IanSav, the changes of local.py is not all. 
This needs also change all po files and in the source file if the text is not only defined in local.py.
This is a huge work.

You can make a fork here and then make the changes in this fork and then make a pull request.

Example:
_("disabled") is only in local.py and needs to change in local.py in pot and in all po files.

 _("seconds") is in screenshot view and must be seconds and not second

You See, i'ts not so easy.

**Comment by IanSav** [comment]
Understood.

It is very late here and I need some sleep.  I will look at creating a fork and try to make the English changes for you.

**Comment by IanSav** [comment]
I have attached my proposed changes to the local.py file.  When you have a chance can you please check the file to see if all the changes are acceptable.  If you agree I will then fork the repository and work on integrating the changes across all the languages.  I will also ask some local associates to check my work to see if they also agree with my corrections.  If they have any more corrections I will recheck the proposals *before* I make changes to the repository.

By the way, you should consider adding en_GB and en_US (and possibly en_AU) language files to your build so that users can make local modifications to the basic English if they so choose.

[local.py.txt](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/614769/local.py.txt)

**Comment by IanSav** [comment]
Proposed language file in previous post has been updated.
