### ISSUE TITLE
Less KB as possible for .png

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#469]
I found 2 times not_found.png with 145.2 kB, one not_found.jpg with 36,8 kB
![net11](https://cloud.githubusercontent.com/assets/17575778/20642247/217175f6-b40a-11e6-8f56-b9a912299818.png)
New one not_found.png with 53,3 kb if necessary two times.
![not_found-fs8](https://cloud.githubusercontent.com/assets/17575778/20642250/3bbaa0ea-b40a-11e6-98bb-35501c103b3b.png)

**Comment by jbleyel** [comment]
The png should only exist in themes folder.
The jpg is for lower package size without themes.

**Comment by sgse** [comment]
Ich hab nichts gemacht ;-) Vorhin noch den OWIF Ordner komplett gelöscht, jetzt sehe ich da das Datum von gestern? 
Bei einem png wären das immer noch 92 kB :)
Please excuse the error.
