### ISSUE TITLE
HD51 is not fully supported( yet?)

### ISSUE THREAD

**Issue by Pedro-Newbie** [E2OpenPlugins/e2openplugin-OpenWebif#470]
For the Mutant HD51 there are some issues:
- There is no picture of the make and model
- Where the make and model is displayed right under: Open Source web interface voor Linux set-top boxen is now displayed Unknown Unknown
- The full remote is missing, in the folder public/images/remotes/ is a picture hd1x00.png which seams the correct remote but the OWIF wants to load dm_normal.png which is not present

<a href='https://postimg.org/image/z8m2bynmj/' target='_blank'><img src='https://s17.postimg.org/3ow11vhgf/OWIF_HD51.png' border='0' alt='OWIF-HD51'/><br /><a target='_blank' href='https://postimage.org/'>upload images free</a><br /><br />

**Comment by Pedro-Newbie** [comment]
![hd51](https://cloud.githubusercontent.com/assets/1159961/20646514/b11bc290-b47a-11e6-99cd-4fd94c69c5c5.png)
Enclosed a picture of the HD51

**Comment by sgse** [comment]
On your number two it must look like
![net14](https://cloud.githubusercontent.com/assets/17575778/20647058/7ee6adac-b48a-11e6-8548-0519674ffad6.png)

1. Try delete browser cache. 
Same error? Try
2. Deinstall OWIF + delete in /usr/lib/enigma2/python/Plugins/Extensions/  **OpenWebif** folder
3. Install OWIF. Clean Browser cache.

If fails, please write your OWIF Version.

**Comment by Pedro-Newbie** [comment]
1 - 3 Done, same errors
OWIF is version git 2269
Boxes folder is empty so no picture of Mutant HD51 available further same errors as above.
Running current Openpli 4 with today's update 

If I change line 406 of owibranding.py from
	elif procmodel in ("hd1100", "hd1200", "hd1265"):
in
	elif procmodel in ("hd1100", "hd1200", "hd1265", "hd51"):
the remote problem is solved

Also if I add some lines in the same owibranding.py after line 257 like this
<a href='https://postimg.org/image/5uxwsehmp/' target='_blank'><img src='https://s16.postimg.org/n88779cxx/owibranding.png' border='0' alt='owibranding'/><br /><a target='_blank' href='https://postimage.org/'>free image hosting</a><br /><br />

The problems are solved as far as I can see, if I make these alterartions

**Comment by Pedro-Newbie** [comment]
![hd51](https://cloud.githubusercontent.com/assets/1159961/20647473/66c783e4-b495-11e6-98c4-8da460db1c71.png)
And if course when I place this picture in boxes

**Comment by Pedro-Newbie** [comment]
Made a pull request
