### ISSUE TITLE
Feature Request: Export/Import of Timers/AutoTimers

### ISSUE THREAD

**Issue by rklrkl** [E2OpenPlugins/e2openplugin-OpenWebif#471]
If I save all my settings, reflash my E2 box, but then only want to restore the Timers/AutoTimers (e.g. the reflash may have been to go to defaults because of some bad settings that would come back on a full restore of the old settings), I can't easily do that at the moment.

Like the Export/Import option in the BouquetEditor, I would like to see a similar Export/Import option for Timers/AutoTimers. The export/import should save/load both the Timers and AutoTimers together, regardless of whether you're in the Timers or AutoTimers section. I can't ever see a need to export them separately - would painfully need 2 exports and 2 imports and people would forget to do both.

**Comment by jbleyel** [comment]
duplicate -> #535
