### ISSUE TITLE
Channel selection not shown when editing existing AutoTimer

### ISSUE THREAD

**Issue by rklrkl** [E2OpenPlugins/e2openplugin-OpenWebif#472]
If I go to edit an existing AutoTimer that has a channel allocated to it (i.e. the Channel: field is ticked), the actual channel name isn't shown in the Channel: field and I get a truncated "select Chan" string there instead. I can click in the text field and select a channel of course, but I don't know if I'm supposed to do that or not due to the incorrect truncated string.

**Comment by jbleyel** [comment]
Please provide a screenshot with this issue.
