### ISSUE TITLE
Movie Tags should be added to the translation database

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#474]
When adding or editing AutoTimers some of the tags offered require translation.

**Comment by jbleyel** [comment]
Please DO NOT...The tags needs to untouched.

**Comment by IanSav** [comment]
Please consider finding a way to make the tags meaningful in the user's language.

I accept it is was probably difficult which is why you haven't done it already.   :wink:

**Comment by jbleyel** [comment]
Please check /etc/enigma2/movietags
This is the only place to be.
And don't change the values in the webif.

**Comment by IanSav** [comment]
Don't worry, I won't change or do anything without asking first.  :smile:

This is an issue I will not pursue.

**Comment by jbleyel** [comment]
It's by design. ;-) And should be as it is.
