### ISSUE TITLE
AutoTimer "After event" is not saved

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#475]
When creating an AutoTimer with OpenWebif the selection of the "After event" is not saved.  If the AutoTimer is created in the GUI then the correct setting is shown in OpenWebif.

**Comment by jbleyel** [comment]
@rdamas  --> kannst du dir das mal anschauen.
Bitte im 1.1 DEV branch ändern und nicht im master branch.

**Comment by rdamas** [comment]
Jep, ich schau mir das gleich an.

**Comment by jbleyel** [comment]
fixed in version 1.1
