### ISSUE TITLE
AutoTimer margin time text boxes too big

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#478]
The text boxes used to capture the custom offset (padding) before and after an AutoTimer allow a huge number of digits.  These boxes should be made smaller and accept at most three or four digits.  Usually two digits should be more than enough.

![textboxes](https://cloud.githubusercontent.com/assets/6904736/20648724/02989606-b503-11e6-9274-4f7417c08483.jpg)

The same issue also applies to the "Only match during timespan" and "Begin / End of "After Event" timespan" fields.

**Comment by jbleyel** [comment]
fixed in version 1.1
