### ISSUE TITLE
AutoTimer poll interval is in minutes not hours

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#482]
The AutoTimer settings screen suggests that the polling interval value is in hours (h).  It is actually in minutes (m).

**Comment by jbleyel** [comment]
This is a problem of your autotimer plugin.
The correct value is in hours.

You are using a non supported old version of autotimer plugin.

**Comment by IanSav** [comment]
Thank you for this information.

I will investigate with our image maintainer.

**Comment by IanSav** [comment]
I just loaded the very latest build of OpenViX and the polling interval is definitely in minutes not hours.  Also the two editor options are definitely "Classic" and "Wizard".

Are you sure that the issue is not within OpenWebif?

**Comment by Schimmelreiter** [comment]
One of the advantages of the oe-a forks of some plugins is, that we can make changes to them without PLi starting a discussion. 
The disadvantage is, that once you fork and change, you do not automatically get the latest changes. And once there are multiple changes on both sides,  merges become harder and harder. 

That way, some plugins heavily drift apart. 
I spent weeks on getting E2openplugins' and oe-a's OWIF in sync again.
For xmltvimport it were some days too.
Chances are, that Autotimer suffers from the same drift problem.

**Comment by IanSav** [comment]
This is the AutoTimer we use on the Beyonwiz build:
# opkg info enigma2-plugin-extensions-autotimer
Package: enigma2-plugin-extensions-autotimer
Version: 2.0+git6190+3bda30d-r10.8
Depends: enigma2-plugin-systemplugins-mphelp, python-codecs, python-difflib, enigma2-plugin-systemplugins-toolkit, python-xml, python-re, python-threading
Status: install ok installed
Section: base
Architecture: inihdx
Maintainer: OE-Alliance team
MD5Sum: 18250dc683e79bbec6b1e80a6133402b
Size: 290146
Filename: enigma2-plugin-extensions-autotimer_2.0+git6190+3bda30d-r10.8_inihdx.ipk
Source: git://github.com/beyonwiz/enigma2-plugins.git;protocol=git;branch=2.3 file://pluginnotwanted.patch
Description: extensions-autotimer  Automatically add Timers based on simple rules
Installed-Time: 1479896475

The beyonwiz/enigma2-plugins is forked from oe-alliance/enigma2-plugins and only 7 commits behind.

This is the AutoTimer we on my OpenViX build:
# opkg info enigma2-plugin-extensions-autotimer
Package: enigma2-plugin-extensions-autotimer
Version: 5.0+git6176+b2f29ae-r0
Depends: enigma2-plugin-systemplugins-mphelp, enigma2-plugin-systemplugins-toolkit, python-codecs, python-difflib, python-re, python-threading, python-xml
Status: install ok installed
Section: base
Architecture: inihdx
Maintainer: OE-Alliance team
MD5Sum: 8af2841d78ccf223db2f69a1c95dbe52
Size: 288674
Filename: enigma2-plugin-extensions-autotimer_5.0+git6176+b2f29ae-r0_inihdx.ipk
Source: git://github.com/oe-alliance/enigma2-plugins.git;protocol=git;branch=2.3 file://pluginnotwanted.patch
Description: extensions-autotimer  Automatically add Timers based on simple rules
Installed-Time: 1480327587

It looks like we are all working with the same / closely related source.

**Comment by Schimmelreiter** [comment]
Not really:
The original is that on Schwerkraft git (Dream Multimedia) and then there is also OpenPLi's fork of it.
So there are at least 4 variants around. 

The point of attack should be the AutoTimer forks, they should match the original from Schwerkraft git as closely as possible.

**Comment by IanSav** [comment]
I don't think the Beyonwiz people will go much further than the OE-Alliance an OpenViX repositories.

**Comment by Schimmelreiter** [comment]
That will be their problem then.

**Comment by IanSav** [comment]
Probably.  I woll pass on your suggestion.

By the way, have you seen my comments on #499, I don't think that issue should be closed.

**Comment by Schimmelreiter** [comment]
I'll try to get the oe-a fork in sync with schwerkraft **and** OpenPLi as good as possible.

**Comment by Schimmelreiter** [comment]
BTW: beyonwiz is not 34 commits behind, but ahead.

That doesn't mean anything though, two forks can be completely in sync and still be commits apart, as merging also counts as 1 commit:
OWIF oe-a is 142 commits ahead of E2Open-OWIF, but in reality it's even.

You create a fork -> fork is even
master gets updated -> master is 1 commit ahead
fork merges master -> fork gets 1 commit from master plus the merge -> is 1 commit ahead
master gets updated -> master looks even (but is 1 commit ahead)
fork merges master -> fork gets 1 commit from master plus the merge -> is 2 commit ahead
and so on.

It's the true code drift which matters.
long-term forks are just evil.

**Comment by arn354** [comment]
https://github.com/oe-alliance/enigma2-plugins/commit/b5277b35229106f90f0b786b16c1e213edb46fad
jörg commited himself the change from hour to minutes

**Comment by Schimmelreiter** [comment]
Pfui Jörg, schäm Dich!

**Comment by jbleyel** [comment]
Upps.. :D

I have compared the 2.3 oe and 2.3 beyonwiz branches.
There are not really a difference.

here are minutes:
https://github.com/beyonwiz/enigma2-plugins/blob/2.3/autotimer/src/AutoTimerSettings.py#L47
https://github.com/oe-alliance/enigma2-plugins/blob/2.3/autotimer/src/AutoTimerSettings.py#L47

and here are hours
https://github.com/OpenPLi/enigma2-plugins/blob/master/autotimer/src/AutoTimerSettings.py#L55
https://schwerkraft.elitedvb.net/plugins/scmgit/cgi-bin/gitweb.cgi?p=enigma2-plugins/enigma2-plugins.git;a=blob;f=autotimer/src/AutoTimerSettings.py;h=c3b76ee5dcffa4e8758a1809975b7c00d8ea216f;hb=HEAD#l42

I think we should sync this and go back to hours for oe too.

**Comment by jbleyel** [comment]
We can also get some additional settings from pli.

The oe and pli version is 4.1.2 the schwerkraft is 4.0.8

But the pli and oe code is much different.

The schwerkraft and oe looks similar.

**Comment by jbleyel** [comment]
Frag mich bitte nicht wieso ich vor 2 Jahren das von h auf min umgestellt habe.
Ich hatte da sicher meine Gründe. :D

**Comment by sgse** [comment]
Du warst jung und brauchtest das Geld :-D

**Comment by jbleyel** [comment]
Ja, klar. Auf das Geld warte ich bis heut. *lol*

**Comment by IanSav** [comment]
It looks like some of the issues need to be fixed and synchronised upstream.  Eventually the Beyonwiz will get the update too.

**Comment by jbleyel** [comment]
We have 3 different versions of autotimer and a complete sync is impossible in case of different thread integrations.

**Comment by IanSav** [comment]
When you release OpenWebif 1.1 I can test it against the current OpenViX and Beyonwiz builds and let you know if I still see issues.

You and the team have done so much good work on the updates that perhaps the issues I saw will have sorted themselves out.   :smile:

**Comment by Schimmelreiter** [comment]
schwerkraft und oe-a sind nahezu direkt mergebar.
Unterschiede gibt es bei ConfigYesNo/ConfigEnabledDisabled/ConfigOnOff und der in OpenViX/OpenATV fehlenden Suche in Beschreibungen und sehr viel in den Übersetzungen. 

Das einzige was die oe-a-Version schwerkraft voraus hat ist die Funktion, beim Löschen eines AutoTimer auch die von ihm erzeugten Timer mit zu löschen und "silent" im Hintergrund bleiben zu können  (Ohne Popup).

Mir ist es nur etwas zuviel. .. wäre schön gewesen, das hätte jemand kontinuierlich beibehalten.

**Comment by Schimmelreiter** [comment]
@jbleyel 
Kann ich Dich dazu bewegen, den oe-a AutoTimer zu machen?
- So schwerkraftig wie möglich
- So oe-a-konservierend wie nötig (Ich sehe da keine echten Fixes von Andy, aber falls Du was siehst, muß der oe-a-Fix bleiben, sonst dreht OpenViX am Rad)
- So PLi-lastig wie sinnvoll (Nur echte Fixes/Verbesserungen)
?

**Comment by jbleyel** [comment]
oe-a autotimer ist jetzt wieder etwas näher an schwerkraft.

**Comment by Schimmelreiter** [comment]
Top!

**Comment by jbleyel** [comment]
Bei Schwerkaft gibt es eine umfangreiche Änderung mit Logging .. brauchen wir das auch.
Wenn ja, dann wird der Diff deutlich einfacher.

**Comment by Schimmelreiter** [comment]
Ich sag mal so: Wenn es damit nicht schlechter läuft, kann eigentlich alles rein.
Morgen könnte ich aber auch testen, AutoTimer ist ja mal was, das ich auch wirklich nutze.
Nur heute abend hat mich meine Chefin schon in Beschlag.

**Comment by jbleyel** [comment]
Danke.
Das was ich bis jetzt gemacht habe sollte keinerlei Auswirkungen haben.
Es sind quasi nur Vorbereitungen.

**Comment by IanSav** [comment]
I know that merging the builds, or at least bringing them closer is a big effort but once done moving forward should be so much easier.  The Beyonwiz builds will follow the OpenViX / OE-Alliance versions as they are updated.

Danke for your efforts.   :smile:
