### ISSUE TITLE
Normal logical files names instead of the stupid "file" (without .TS extension) or "ts.m3u"

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#485]
Can there normal files names what someone says about the content instead of the stupid "file" (without .TS extension) or "ts.m3u" files names?

**Comment by Schimmelreiter** [comment]
I wouldn't want to change this, as it is historically grown (Was like that in Dream Webif already) and might break 3rd party functionality.

**Comment by rocco99222** [comment]
Also not the .TS extension?
