### ISSUE TITLE
Option to create animated gif or small mp4/avi file from GUI.

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#487]
Instead of only a JPEG still.

**Comment by Schimmelreiter** [comment]
Huh?
Where?

**Comment by rocco99222** [comment]
To the add create screenshot menu under section remote in the Web-If.

**Comment by Schimmelreiter** [comment]
Screenshots are created by aio-grab, different package. No influence on that and what it does support.
