### ISSUE TITLE
Time sheduled planned message.

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#488]
Nog you can send a message to the box, but can't send a shuduled message. Want option to send out sheduled messages on settings times, daily or weekly or specifick times same as recording.

**Comment by jbleyel** [comment]
I think this is not really needed.

**Comment by rocco99222** [comment]
I think it is useful as alternative for the zapp timer?

**Comment by jbleyel** [comment]
This needs a new timer type "notify" and afterwards we can implement this new timer type.
The hole thing needs to run on the box and not in a browser.

Close Browser -> Timer Gone.

**Comment by rocco99222** [comment]
Timers saving already on the box.

**Comment by rdamas** [comment]
Right, but there currently is no such thing as a notification timer.

**Comment by jbleyel** [comment]
This is not quiet correct .. some distros have a notify timer type.

**Comment by rdamas** [comment]
Ok, didn't know :-) - so make it an optional addition for the distros that support them sounds like the right thing to do then; probably by extending the "send message" form, but there obviously should be a means of editing or deleting notifications from the timer list as well.

Low Priority for me, 2.0 feature.

**Comment by jbleyel** [comment]
openpli / openatv have : (zap,rec,zap+rec)
VTi have notify too.
@plnick -> correct?

**Comment by rdamas** [comment]
Just tested it myself: yes, VTi has notify timers, but to use them as scheduled messages, probably needs work; looks like this:

![1_0_19_11f_c_85_c00000_0_0_0](https://cloud.githubusercontent.com/assets/15088943/20866348/d145fc14-ba2b-11e6-9797-c03064046022.jpg)
