### ISSUE TITLE
File browser in the Web-If

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#489]
Can they add a file browser in the Web-If who can, copy, move, or delete every file?

Thank you!

**Comment by rdamas** [comment]
Please don't - it probably open's up a huge security hole again and imho has nothing to do in _Web interface_. If you want to copy around files, do this with the tools that are appropriate for it: Windows Explorer, Mac OS Finder, FileZilla and co, Plugins on your box. The _Web Interface_ should not offer an API to do so.

**Comment by jbleyel** [comment]
+1000

**Comment by Schimmelreiter** [comment]
We already have that in some way:
An IPK can contain **any** kind of instruction inside it's preinst-, prerm-, postinst-, postrm-Scripts.

So security is no argument here anymore: Pandora's box is already open.

That was exactly what alerted me to quickly stop allowing users to open OWIF to the outside world too easily.

**Comment by Schimmelreiter** [comment]
As we now have the option to open a terminal right inside of OWIF and users can execute Midnight Commander through it, I see no reason why to re-invent the wheel.
