### ISSUE TITLE
I see time but no data, day.

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#491]
In the Web-If EPG, mode TV guide (only when adding timer see full date)

**Comment by rocco99222** [comment]
data, sorry is mistake mean date.

**Comment by jbleyel** [comment]
Screenshot?

**Comment by rocco99222** [comment]
See here: http://www.enigma2.cz/webif-epg-2.jpg
NO date.

**Comment by jbleyel** [comment]
I think the Mo,Di,... should be enough.
No one have missed this.
