### ISSUE TITLE
Video still instead (or in addition to) the picon.

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#492]
Only see picons now, want to see channel stils instead (or in addition) to the picons. Maybe can also been add to the recording. Thanks. There is also no channel picons at the recordings.

Do also miss some shorting options (currently only see name and date) such as duration, file size or channel name.

**Comment by Schimmelreiter** [comment]
Stills for TV stations would be highly inefficient. 
Page would take ages to (re)load.

Stills for recordings could be doable.
Jbleyel should decide.

**Comment by rocco99222** [comment]
Can you ask Jbleyel? Thanks!

UPC Go use video stills: https://www.ziggogo.tv/nl/tv-kijken.html

**Comment by Schimmelreiter** [comment]
Ziggo doesn't have to tune each and any station using usually 1-4 tuners inside a cheap consumer receiver in order to create the stills.
Sorry, but this idea is crap.
