### ISSUE TITLE
Left bar, missing "Recycle bin". (.Trash folder)

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#493]
Missing the recycle bin under: Hoofd (Dutch language, same menu as recordings and Web TV) in left bar.

**Comment by Schimmelreiter** [comment]
I guess you are using Enhanced Movie Center. Correct?

**Comment by rocco99222** [comment]
No Open web-If
(ofcourse known can access recyclebin with recordings> folder: $RECYCLE.BIN, but hope on direct link)

**Comment by Schimmelreiter** [comment]
I mean on the box.
The recycle bin resp. its existence and name depend on which plugin(s) are used for movie playback. 
That make it somewhat hard to decide how to handle it (and file deletions).

**Comment by rocco99222** [comment]
Used the standard OpenPli movie player accessed with recording list remote button.

http://www.satking.de/out/pictures/z1/sol_zubfer-074_pic1_z1.png

Button under EPG behind Menu and Audio.

Plugin Media Player:
http://i1230.photobucket.com/albums/ee496/DreamBox-Zone/OPENPLi/2OPENPLi_plugins_all.jpg

**Comment by rocco99222** [comment]
# **Sorry files deleting folder is ".Trash" folder NOT "$RECYCLE.BIN"**

Mistake be me, sorry!

**Comment by Schimmelreiter** [comment]
That's Enhanced Movie Center then.

**Comment by Schimmelreiter** [comment]
Uhm ... what are you refering to when you say "left bar"?

**Comment by rocco99222** [comment]
This: https://s19.postimg.org/xqef7twdv/leftbar.png

**Comment by Schimmelreiter** [comment]
Hm, I wouldn't add it there.

How about either showing the Trashcan as one of the subdirs in "Recordings" or as a separate button?
It could share the look of the normal recordings list, just that each recording would get an undelete button instead of (or additional to) a trashcan ...

That's how I would like to see it.

**Comment by rocco99222** [comment]
Seperate button for Trashcan is great!! (Trashcan can already been seen as a subdir)

**Comment by rocco99222** [comment]
It could share the look of the normal recordings list, just that each recording would get an undelete button instead of (or additional to) a trashcan ...

That's how I would like to see it.

I think then must be the letters define another collor (think red) to prevent confusion.

**Comment by rocco99222** [comment]
Oh... It it right subdir .trash is not available to seen as a subdir confusse it with the $RECYCLE.BIN directory.
Maybe also a idea to hide the $RECYCLE.BIN directory so no one can confusse it?

**Comment by Schimmelreiter** [comment]
There is no directory named $RECYCLE.BIN on normal E2 installations.

That's a Windows specific folder, you might have had that harddisk attached to a Windows machine before.

**Comment by rocco99222** [comment]
Yes i have attach the disk to Windows machine.

Alo hope on more sorting options as: channel, file size (bitrate), resolution and lenght.
(now is only Date and Name the options)

**Comment by rocco99222** [comment]
Miss also free disk space and file size here.

**Comment by jbleyel** [comment]
Upload IPK is there. All other things should be done by FTP.
Free Space is on box info.
File Size is in now.

Anything else????
