### ISSUE TITLE
Suggestion: Reorganise the "EPG Search" window to save space

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#494]
Would it be possible to move the recording control icons to the right side of the program name area so that the height of each program cell is reduced to eliminate all the wasted space.  The IMDb icon can be made wider to fill the space under the station Picon.

![epgsearch](https://cloud.githubusercontent.com/assets/6904736/20649318/1e88335e-b511-11e6-9c02-3b818234b2a5.jpg)

**Comment by jbleyel** [comment]
@rdamas -> Can you do this?

@Schimmelreiter , @sgse : what you think?

**Comment by Schimmelreiter** [comment]
Right side is shit: Longe mouse ways on larger monitors, much to scroll on tablets using Desktop mode and we just moved the function icons to the left inside the favourites lists.

The mentioned free space in the list also doesn't really exist, the screenshot uses a news channel with a short generic text "propaganda all day long".
There isn't nearly that much space on full programme stations with movie descriptions and so on.

We could make the icons a bit smaller and maybe omit the separate icon for zap timers. They are a relict from analog times where you had your analog set top box tune the channel at a given time, while the video CASETTE recorder recorded its SCART input ...
They can still be set using Add+Edit timer or you could also add it as Shift+Click on Add timer icon.

**Comment by IanSav** [comment]
Please don't remove the Zap timer.  It is still very handy for people who use their PVR as a wake-up timer etc.  When the Zap timer fires the unit turns on and in turn turns on the TV.   :wink:

**Comment by IanSav** [comment]
To save some space in the timer icons the clock face can be made smaller so that the "function" element of the icon can stand out while making the overall image smaller.

**Comment by IanSav** [comment]
By the way, the timer icons could be moved next to the Picon so that the user does not need to move the mouse so far.

(I am still using 1.0.4 so I can't yet see all the new fixes.)

**Comment by jbleyel** [comment]
Imdb and all buttons depending on the title -> right
All Buttons depending on the channel and all Timer Buttons -> left.
