### ISSUE TITLE
When used stream option can't use the external SRT subtitle file. 

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#495]
But can use that when open with Windows Explorer.

Is that a issue related to VLC and media player classic or can this been solved?

Also can not download the SRT file trough the Web-If.

**Comment by rocco99222** [comment]
Hello,

I really believe you should talk to the Enigma people, and not us.


On Sun, 27 Nov 2016, at 16:56, ** wrote:
Dear VLC

With the Enigma 2 Web-If can stream files trough downloading M3U file. But then can't use the SRT subtitle file.
Ofcourse can read it manually. To load subtitle (menu: Subtitle>Add subtitle file)
But hope it can automatically. exsample: http://192.168.0.100:80/file?file=/media/usb/jill/std.20141209.m4v

192.168.0.100 is the box adres, where 80 is the stream port. /media/usb/jill/ is the folder where the file is stored.
It is saved on a external device that is mounted under /usb
std.20141209.m4v is the file name. Subtitle file is \\VUSOLOSE\Root\media\usb\jill\std.20141209.srt (windows path)
or /media/usb/jill/std.20141209.srt (device path)

Thanks,

**Comment by Schimmelreiter** [comment]
You can not compare streaming and direct file access.
The whole streaming is provided by E2 itself and not the Webif.
We just provide links to it in OWIF.

**Comment by rocco99222** [comment]
What is OWIF?

**Comment by rocco99222** [comment]
O, OWIF is Open Web Inter Face.
