### ISSUE TITLE
WoL

### ISSUE THREAD

**Issue by RobvanderDoes** [E2OpenPlugins/e2openplugin-OpenWebif#498]
Is adding a 'Wake on (Wireless) LAN'-button an option?

AFAIK the Wireless-WoL only applies to the Ultimo 4k.

**Comment by Schimmelreiter** [comment]
How is this supposed to work?
If you can access a box in order to access any of its controls - incl. a WOL button - it's already on.

If you ever find me someone to assist with a proper network browser, we could rather easily add WOL capabilities  (to wake up OTHER known machines than that we are running on) to it.
And through OWIFs new plugin interface we could integrate both functions (Browsing for shares/machines and WOL) to OWIF afterwards.

**Comment by RobvanderDoes** [comment]
The WoL command can be received (by WoL-capable receivers) while being in 'deep sleep, because the NIC is reachable (when WoL has been enabled). 
The plugin 'WoL' wakes up WoL-capable boxes (but lacks a decent control), PLi's recently updated Partnerbox does it as well as several PC-programs (like "SoftPerfect Network Scanner").
So IMHO this should be possible.

**Comment by Schimmelreiter** [comment]
No it's not. The box being in deep stand-by (or rather WOL standby) and the OWIF already up and running are mutually exclusive. 
As I said: Another box can send the WOL sequence, but the box can not wake up itself (Just turn off your alarm and try waking up yourself tomorrow. Let me know yozr boss'

**Comment by Schimmelreiter** [comment]
Your boss' opinion about it)

**Comment by RobvanderDoes** [comment]
LOL, of course I'm talking about waking up another box :)
So again: I fail to see a reason why a WoL-command button wouldn't be possible.

But now you mention it: it happens quite often that I have the WEB-IF still open in the browser while the box is already in deep. So adding a WoL-button for the box itself is not a bad idea either.

In other words: A WoL-button should have a configurable MAC-address (And preferably more then just one).

**Comment by Schimmelreiter** [comment]
You know your MAC addresses by heart? Impressive :-)
As I said: If this feature is going to make sense, it better becomes part of a network manager which also does other things (Like creating mounts) in a network overview style way.

**Comment by RobvanderDoes** [comment]
> You know your MAC addresses by heart?

No, and luckely there's no need for that either: e.g. the WEB-IF tells me the value, and allows to copy & paste it

> Impressive :-)

Indeed :)
