### ISSUE TITLE
Some translation strings do not appear to be used

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#499]
On the "Box Info" screen the translation strings "fp_version" and "ipv4only_network" do not appear to be used.  There may be others not used but they have not shown up in the testing I can do on my hardware.

**Comment by Schimmelreiter** [comment]
fp_version only appears on boxes reporting anything but 0 or none for the Front Processor.
That's probably only genuine clones of Dreamboxes  and their non-counterfeit originals.

"IPv4 only network" is only shown when running inside a, well, IPv4 only network.

**Comment by IanSav** [comment]
I an seeing the untranslated strings!  It is the translated text that is not appearing.

**Comment by IanSav** [comment]
See my proposed translations in "local.py" as detailed in #468.

![translation](https://cloud.githubusercontent.com/assets/6904736/20658527/b0f0f214-b591-11e6-940e-0b8181d80090.jpg)

**Comment by IanSav** [comment]
Does the image help explain my observation?

**Comment by IanSav** [comment]
I have now implemented an Australian "en_AU" language file "OpenWebif.mo" for my personal testing.  In that file I have the following translations:
> #: plugin/controllers/models/info.py:331 plugin/local.py:104
> msgid "Frontprocessor Version"
> msgstr "Front Panel Version"

> #: plugin/controllers/models/info.py:169 plugin/local.py:116
> msgid "none/IPv4-only network"
> msgstr "None / IPv4-only network"

> #: plugin/controllers/base.py:288
> msgid "BouquetEditor"
> msgstr "Bouquet Editor"

When using this language file the strings indicated in the image above, plus the "BouquetEditor" menu item are not being changed.  I had a quick look at the source code and it looks okay.  I can't see an obvious reason why these strings are not being translated.
