### ISSUE TITLE
Move icons missing from the BouquetEditor

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#500]
In Issue #239 the image shows that there are up/down arrow markers or grab handles for the bouquets and channels to allow the order of the items to be changed.  In my version of OpenWebif 1.0.4 these icons are not present.  Is this a local build problem?

![arrows](https://cloud.githubusercontent.com/assets/6904736/20663722/9d3409b2-b5ac-11e6-9fd4-7b1120a9871a.jpg)

**Comment by Schimmelreiter** [comment]
I can confirm this.

**Comment by jbleyel** [comment]
fixed with -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/ada30db9a3596ef51e169919dfe116bfb1e6b13a
