### ISSUE TITLE
Link zur Mobile Version in der Desktopversion

### ISSUE THREAD

**Issue by zeini1** [E2OpenPlugins/e2openplugin-OpenWebif#502]
Es wäre öfters nützlich, wenn man von der Desktopversion auf die mobile Version wechseln kann. Da findet man sicherlich auf der Einstiegsseite einen Platz wo man nen Link setzen könnte (Evtl. unter dem Suchbutton). Kann imho auch bei denen aufscheinen, die tatächlich auf einem Desktop arbeiten.

Von mobiler Version zur Desktopversion gibts das ja.

**Comment by jbleyel** [comment]
Klick auf das Openwebif Logo oben links.

**Comment by Schimmelreiter** [comment]
Bei Click auf "OpenWebif" wird nur die Seite neu geladen, nicht die mobile Ansicht.

**Comment by jbleyel** [comment]
Wo hast du das getestet?

**Comment by jbleyel** [comment]
Auf dem iPhone funktioniert das.

**Comment by Schimmelreiter** [comment]
Klar funktioniert das da, da ist ja "mobile Ansicht" auch der Standard.
Es ging ja darum, die mobile Ansicht per Link erreichen zu können, wenn "auto-detect" die Desktop-Ansicht nehmen würde.

**Comment by jbleyel** [comment]
Das war nicht die Anforderung.

**Comment by zeini1** [comment]
Hmm, auf meinem Handy funzt es schon. Sowohl mit Firefox, Chrome als auch Dolphinbrowser. Auf dem Desktop allerdings nicht.

**Comment by jbleyel** [comment]
Wer bitte will auf dem Desktop die Mobile Ansicht ????

**Comment by zeini1** [comment]
Ja, war nicht Anforderung. Wäre aber zumindest kein Fehler denke ich. 
Vielleicht wollen es einige, wenn es dort die neue Fernbedienung gibt.

**Comment by jbleyel** [comment]
Dann sollen die /mobile eingeben.

**Comment by jbleyel** [comment]
Wenn es mir mal richtig langweilig ist, dann bau ich die komplette Seite auf bootstrap um.
Dieses Jahr nicht mehr und nächstes Jahr nicht gleich. :D

**Comment by zeini1** [comment]
Man könnte ja auch in der mobilen Ansicht oben wo OpenWebif steht, das verlinken zur Desktopversion und dort eben umgekehrt.

**Comment by zeini1** [comment]
Ich persönlich bin aber auch so schon zufrieden wie es ist.

**Comment by Schimmelreiter** [comment]
Sinnig wäre es dort, wo jetzt
E2OpenPlugins | openATV | Black Hole | OpenDroid | EGAMI | OpenHDF | openMips | OpenPli | Sif | OpenSpa | OpenViX | VTi | Über
steht.

In der mobilen Ansicht ist der Wechsel zur Desktop-Version ja auch ganz unten.

Und der Wechsel macht schon Sinn:
Wir haben die Erkennung für mobile Browser ja schon in der 1.0 so abgeändert, daß auch Tablets die Desktop-Ansicht bekommen, wenn der User Agent das so sagt und da kann der Wechsel zur mobilen Ansicht schon Sinn machen.

**Comment by jbleyel** [comment]
Es macht nur dann Sinn, wenn jemand die Mobile Ansicht haben will der diese über UserAgent ncith bekommt. Aber auf dem Tablet will doch keiner die Mobile Ansicht haben. Oder doch?

Ich würde sagen wir lassen das mal so.
