### ISSUE TITLE
No full remote and box info image

### ISSUE THREAD

**Issue by ivos83** [E2OpenPlugins/e2openplugin-OpenWebif#506]
Hi,

After fixing Open Webif with the instructions found on the OpenPLI forum I noticed something strange.
The images at Full remote control and Box info are not showed anymore.

I tried the flash OpenPLI version of before the 24th of November unfortunately without result. 
Anyone have an idea what is going wrong? I'm convinced that this was working OK some versions ago...
![hd500c_11_12](https://cloud.githubusercontent.com/assets/24251604/20715654/2b672d24-b650-11e6-98f1-3b6192233ebd.JPG)

**Comment by AbuBaniaz** [comment]
Which receiver are are you using?

**Comment by AbuBaniaz** [comment]
Saw your thread in OpenPLI. See this as an example of what needs to be done for you Mutant 500C
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/385f64ceb7eb09ee11fedd6611be230e3fd04856

**Comment by ivos83** [comment]
Hi! Thank your for responding and i'm sorry to not provide the required info like model name.
I already changed to code like indicated in the article. After a reboot the Box info shows the correct model and model type. The image files are missing, can they be downloaded somewhere?

Thank's in advance!

**Comment by AbuBaniaz** [comment]
What do you get if you paste this command in putty/DCC

cat /proc/stb/info/boxtype

**Comment by ivos83** [comment]
> 
root@hd500c:/# cat /proc/stb/info/boxtype
hd500c
root@hd500c:/#

**Comment by AbuBaniaz** [comment]
Is this the remote?
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/385f64ceb7eb09ee11fedd6611be230e3fd04856/plugin/public/images/remotes/hd1x00.png

**Comment by ivos83** [comment]
Yes thats the one, i have placed the file in the correct folder and it works just fine!
For the Box info image I took some .JPG file that I found through Google.

Thank you for your help.
