### ISSUE TITLE
No module named ipaddress after VU+ Duo2 OpenPLI update

### ISSUE THREAD

**Issue by Erfeniuses** [E2OpenPlugins/e2openplugin-OpenWebif#507]
VU+ Duo2 29.11.2016 update broke the OpenWebif so that system hails for 
"No module named ipaddress"
Can this be fixed somehow?

**Comment by Schimmelreiter** [comment]
Yes, by installing the package python-ipaddress though
`opkg install python-ipaddress`

I guess though, you are trying to update OpenWebif on a machine beyond the version that the distro provides.
All images that actually ship recent versions of OWIF also have python-ipaddress inside the depends, so it would get auto-installed.

**Comment by Erfeniuses** [comment]
THANK YOU!!!
SSH to Device, Root in and "opkg install python-ipaddress" and reboot! FIXED! THANK FOR A MILLION!
