### ISSUE TITLE
Finish new security settings

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#508]
What do we here -> 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/plugin.py#L64

**Comment by Schimmelreiter** [comment]
Nichts.
Diese Fake-Einstellung ist nur da, um eine Zeile reinen Erklärbär-Textes als Hinweis einzublenden.

**Comment by jbleyel** [comment]
Geht das nicht besser?
Sonst kommt die Frage. 
Wieso kann ich da nix einstellen?
Du kennst doch unseres Pappenheimer.

**Comment by Schimmelreiter** [comment]
Da steht aber keine Frage oder keinerlei Indiz dafür, daß man da etwas einstellen könnte, sondern ein Satz mit Ausrufungszeichen ....

Man sieht überhaupt nicht, daß es eine verkappte Auswahl ist:
![image](https://cloud.githubusercontent.com/assets/2022025/20724397/52500514-b66e-11e6-89f7-e1ff47760438.png)

**Comment by Schimmelreiter** [comment]
Und die Frage, ob das nicht besser geht, müßte ich zurückgeben ...
Wenn Dir etwas besseres einfällt um eine Zeile Hinweistext zuzufügen, was dann aber bitteschön auch in OpenPLi, OpenATV, OpenViX, OpenHDF, OpenBH, BetonWitz, EGAMI, VTi, Black Hole, DreamGrSatoderso, ... funktionieren muß, dann kannst Du das gerne ändern.

Ich habe mich umgeguckt und das nur in CoolTVGuide gefunden und da wurde es genau so gemacht.

**Comment by jbleyel** [comment]
Ok Ok, ich dachte du wolltest da noch was machen.
Und Close, weil nicht editierbar.
