### ISSUE TITLE
EPG in OpenWebif

### ISSUE THREAD

**Issue by doglover3920** [E2OpenPlugins/e2openplugin-OpenWebif#51]
Open Webif does not represent the epg properly.
In order to have some formatting in the epg control charachters \n or \r\n of \n\r are used.
Also line feeds CHR(10) and CHR(13) are used.  These are added to obtain a little of bit formatting and increase the readability

All these are not properly displayed in the epg presentation of OpenWebif.
See the attached screenshots.
In Enigma these are properly presented.  (line feeds)

These \n \r tags are currently present when importing the rytecxmltv in numerous channels.
één (HD) en Nederland1 (HD) to name two

Could this be fixed.

Willy

![epg](https://f.cloud.github.com/assets/3510990/139284/00aa4560-71eb-11e2-9552-b395a9899c33.jpg)
![epg2](https://f.cloud.github.com/assets/3510990/139285/0365b79e-71eb-11e2-8d45-c79ab63a9de9.jpg)

**Comment by jbleyel** [comment]
Can this issue be closed?

**Comment by Schimmelreiter** [comment]
I would say:
If we currently *filter* \n and \r, we should replace them by actual new lines, then this issue would be solved.
Or if we do not currently filter \n and \r but they are gone from the E2 EPG completely, this issue *is* already solved, because it's not our beef then.
