### ISSUE TITLE
1.1: Fallback to original Theme not complete

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#512]
If a different theme than original was chosen and the "Themes" package gets deleted, OWIF only partly switches back to "original":
![image](https://cloud.githubusercontent.com/assets/2022025/20746353/bc65488e-b6e5-11e6-87d1-7b7641bfb87f.png)

Toggling between clear and original once fixes the problem:
![image](https://cloud.githubusercontent.com/assets/2022025/20746440/22117d1a-b6e6-11e6-8be1-c78138006536.png)

**Comment by Schimmelreiter** [comment]
Leute, irgendjemand muß auch mal testen, ob wir jetzt die Themes und das Web TV wirklich einfach so rausschneiden können.

Meine 2. Solo² läuft momentan ganz ohne WebTV, das scheint auch soweit problemlos zu funktionieren, die 1. Solo² ohne Themes, mit dem o.g. Problem.
Irgendjemand sollte auch mal ohne beides testen.

**Comment by jbleyel** [comment]
Kann ich gerade nicht. -- DANKE TELEKOM --

**Comment by jbleyel** [comment]
Wenn der Theme Ordner auf der Box nicht da ist, dann darf nur "Original" und "Clean" zur Auswahl kommen.

Sollte vor dem Löschen ein anderes Theme ausser die beiden eingestellt sein, dann muss beim Neustart der GUI auf Original umgestellt werden.
Ich vermute da liegt das Problem.

**Comment by jbleyel** [comment]
Ich glaube da ist nur ein kleiner Fehler in der base.py ab Zeile 315.
Die Variable theme bleibt auf dem alten wert obwohl der Ordner weg ist.
Da passt wohl was mit dem if in Zeile 321 nicht.

**Comment by Schimmelreiter** [comment]
Die Telekom versucht wahrscheinlich gerade, die SpeedRotz-Router vor Mirai zu schützen ...
Einen besseren Zeitpunkt zum hardening von OWIF konnte es nicht geben, als den, in dem eine **knappe Million** Kunden wegen wildgewordener Set-Top-Boxen ohne Telefon und Internet dasteht, nur einen Monat nachdem dieselben wildgewordenen Router Twitter, Netflix und Github abgeschossen hatten :)

**Comment by Schimmelreiter** [comment]
> Sollte vor dem Löschen ein anderes Theme ausser die beiden eingestellt sein, dann muss beim Neustart der GUI auf Original umgestellt werden.
Ich vermute da liegt das Problem.

Du hast das erwünschte Verhalten perfekt beschrieben :)

**Comment by Schimmelreiter** [comment]
Es heißt mal
ret['theme']
und mal
ret['theme**s**']

Fehler oder Absicht?

**Comment by sgse** [comment]
`rm -r /home/mint/Downloads/e2openplugin-OpenWebif-1.1-DEV/plugin/public/webtv/*`
Habe ich seit 2 Tagen, auf FF läuft bei mir alles wunderbar.

**Comment by sgse** [comment]
Info @jbleyel seit heute Nacht habe ich https://www.vuplus-support.org/wbb4/index.php?thread/102581-neues-vti-vu-team-image-vti-11-0-x/&postID=1430605#post1430605
drauf. **Sie haben OWIF 1.x eingebunden.**
```
Software
OE-System: 	OpenVuplus 2.1
Firmware-Version: 	VTi-Team Image 11.0.0 (2016-11-29-vti-master (0cf9c86))
Kernel / Treiber: 	3.13.5 / 3.13.5-20151201.r0
```
Vergessen falls schon bekannt ;)

**Comment by jbleyel** [comment]
Einmal theme und einmal themes ist noch eine altlast. Kein Tippfehler.
Das Problem liegt wo anders.
Die Variable "themes" war dafür gedacht um zu enscheiden ob es themes überhaupt gibt.
Das ist nicht notwendig.

Der Fehler ist also nur in Zeile 321.

-- 

Ich kann aber heute nix machen.
Ich habe aber keinen Speedport, bei mit hat es die Leitung zerrissen. *grrrrr*

**Comment by jbleyel** [comment]
Wenn man das Original Theme eingestellt hat und danach erst den Ordner Löscht dann gibt es keine Probleme.

Den kleinen Fehler mit dem Theme schau ich mir an.
Ich kann das aber vermutlich erst morgen einen commit machen.

Bitte testet die anderen beiden Dinge.
WEBTV, MOBIL

**Comment by Schimmelreiter** [comment]
Was gibt's denn bei mobil zu testen?

**Comment by jbleyel** [comment]
public/mobile
löschen und prüfen was passiert auf einem mobilen Gerät es darf kein Fehler kommen.

Wenn keine Fehler mehr drin sind, dann mache ich den Merge auf 1.1 am Freitag oder Samstag.

**Comment by Schimmelreiter** [comment]
Ah, mobile als Modul habe ich jetzt gar nicht mehr berücksichtigt.

**Comment by Schimmelreiter** [comment]
Siehe hier:
https://github.com/oe-alliance/oe-alliance-core/commit/38876a37918e94941602f78331bddda39468a3bd

Ich habe -themes, -webtv und weiterhin -vxg vorgesehen.

Ohne alles sind wir bei ~ 800kB, die hatten wir mit 0.4.x auch schon.

**Comment by jbleyel** [comment]
vxg ist bei webtv mit drin.
Wollen wir das separieren?
mobile lohnt sich wirklich.
Schau mal wie gross der Ordner ist.
Dagegen sind die themes ein Witz.

**Comment by Schimmelreiter** [comment]
vxg hatten wir ja vorher auch ganz separat, sind halt 1,4 MB ...
Haste den Check auf die .pexe etwa rausgenommen?
Dann muß der bis 1.1 wieder rein.

Sonst muß man ja vxg immer mitinstallieren, wenn man WebTV haben will, selbst wenn nur Firefox oder Safari verwendet werden sollen.
Mach ich zwar, weil ich Firefox nur im Ausnahmefall und IE nur als abschreckendes Beispiel benutze, aber deshalb muß man das ja nicht allen Benutzern aufzwingen.

"mobile" mag sich lohnen, aber ich weiß nicht so recht, das ist schon ewig drin ...

**Comment by Schimmelreiter** [comment]
mobile hat zip-komprimiert 88 kB. Wenn ich nicht komplett falsch liege, komprimiert auch ubifs, die Ersparnis wäre demnach eher überschaubar.
Und bringen tut's auch nur dann was, wenn es irgendeine Distro oder irgendein User wirklich wegläßt.

**Comment by jbleyel** [comment]
Dann prüfe mal wieviel themes bringt wenn man es weg lässt.
vxg wird separat geprüft ist aber in dem ordner webtv drin.
d.H. man kann ohne webtv und ohne vxg.
Zur Vereinfachung würde ich aber vxg in einen extra Ordner legen.

**Comment by jbleyel** [comment]
Ich würde sogar sagen, das wir webtv immer drin lassen und nur vxg abtrennen.
Webtv alleine braucht fast keinen Platz.

**Comment by Schimmelreiter** [comment]
Ich hab's jetzt schon so in oe-a eingebaut:
https://github.com/oe-alliance/oe-alliance-core/commit/d612516b381a8382ad1b5aa34ad1c9e1882a4e1d

(Basis) +
-themes
-webtv
-vxg

Ja, im Prinzip ist -webtv ein Witz (18kB), aber vielleicht will ein Team das ja **wenn** dann komplett weglassen, damit es keine Beschwerden gibt "Web TV funktioniert bei mir mit Chrome nicht".
Und -vxg war jetzt einmal als Paket da und sollte auch bleiben, weil opkg sehr blöd ist.

**Comment by Schimmelreiter** [comment]
Ich hab's aus dem Grund auch bei -vxg statt -webtv-chrome oder -webtv-vxg belassen, weil opkg eben kaum mit sich ändernden Paketen klarkommt.

**Comment by jbleyel** [comment]
Soll ich dann vxg in einen Extra Ordner legen?
Das macht es beim Löschen einfacher.
Du muss das nur einen Ordner löschen und nicht 4 Dateien einzeln.

**Comment by Schimmelreiter** [comment]
Ich war mir nicht sicher, ob Du die vxg* und media_player* überhaupt verzichtbar gemacht hast, deshalb habe ich weiterhin nur media_player.pexe abgespalten und nicht alle 4 Dateien.

Extra-Ordner wäre sicherlich einfacher gewesen, dann muß ich aber wohl beide Rezepte (In den Branches 3.4 und 4.0) wieder anpassen.

Scheiß drauf, setz die Dateien um, aber dann bitte frühestens Samstag switchen!

**Comment by jbleyel** [comment]
Okay.. ich mach mal.
