### ISSUE TITLE
Link in Web-If to open VU+ Root or USB drive in Windows Explorer.

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#513]
And files/folder locations (locate file)

Instead of manual go to \\VUSOLOSE\Root or \\VUSOLOSE\Root\media\usb etc.

**Comment by rdamas** [comment]
I'm against such an addition to _Web Interface_; it's bloat and has nothing to do with either the API or the browser. The network links should be auto found by WIndows Explorer and Mac OS Finder (the latter I can confirm) and even Linux Desktop.

**Comment by jbleyel** [comment]
+1000

**Comment by Schimmelreiter** [comment]
Such a feature is impossible (now):
Security policies in browsers prevent opening file:// links externally.
You would just get an FTP-like view inside the browser.
