### ISSUE TITLE
WebTV: Don't count markers as stations

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#517]
See that "kabel eins doku" is channel 35 in WebTV:
![image](https://cloud.githubusercontent.com/assets/2022025/20843112/5f818836-b8ba-11e6-8bbf-bda3b3416a75.png)

But channel 34 in reality:
![image](https://cloud.githubusercontent.com/assets/2022025/20843119/64717658-b8ba-11e6-9b37-12f69944306d.png)

Obviously WebTV counts the marker "Doku/Wissen/Themen" as 34.

**Comment by jbleyel** [comment]
Die Nummer gehört da gar nicht hin.
Ist gefixt mir dem nächsten commit.

**Comment by Schimmelreiter** [comment]
Zitat aus dem Forum:
"Dafür auch großen Dank. Wobei die Lösung suboptimal ist. Statt die Zählweise zu korrigieren, und/oder die Marker mit einzublenden, ist die Übersichtlichkeit der Schlichtheit gewichen. Wenn man die Marker sieht, weiß man in welchem Teil seiner Senderliste man rumsurft. Wenn man die Nummern etwas kennt, weiß man, ab Nr. xy kommen Kabelsender, danach DVB-T. So muß man nicht einzelnde Bouquets anlegen, behält aber dennoch den Überblick. Ohne Nummern/Marker nun ist das keine saubere Lösung, weil z.B "Das Erste HD" hier dreimal in der Liste steht (DVB-S/C/T2). Eventuell kann man die Nummern plus Marker nochmal auf die ToDo-Liste mit geringerer Prio setzen..."

**Comment by jbleyel** [comment]
Ich schau mal.

**Comment by Schimmelreiter** [comment]
Es lebt!

Hast Du meine eMail nicht bekommen?

**Comment by jbleyel** [comment]
Ich hab schon geantwortet.

**Comment by Schimmelreiter** [comment]
Hm, dann hab ich Deine Antwort nicht bekommen ...

**Comment by jbleyel** [comment]
Spamfilter?

**Comment by Schimmelreiter** [comment]
Hab ich schon geguckt. ..
Schick doch bitte einfach nochmal. ..

**Comment by jbleyel** [comment]
Done

**Comment by Schimmelreiter** [comment]
Email war beim 2. Mal im Spam-Folder.
Jetzt sitze ich am Handy, aber ich schreibe Dir morgen mal, wie Du gezielt nur oscam bauen kannst.

**Comment by jbleyel** [comment]
Thanks...
Ich hab es zwar geschafft das ganze Image zu bauen nur nicht ohne Eingriff.
2 bb Files musste ich anpassen.

Ich hab auch noch mal komplett von Vorne angefangen.
Mit etwas mehr Speicher und CPU hat es auch nur 16 Stunden gedauert.

**Comment by jbleyel** [comment]
Ich hab das Problem gefixt.
Ein Punkt ist aber noch offen.

Wenn z.B. ein Sender Ref in mehreren Bouquets drin ist, dann wird der 1. Sender in der Liste angezeigt und der 2. Eintrag nicht. dadurch entsteht eine Lücke beim 2. Bouquet.
Da wird es dann wieder ein paar Heuler geben die dann sagen "Da fehlt was in der Liste"

**Comment by Schimmelreiter** [comment]
Diese Issue müßte doch dann jetzt eigentlich erledigt sein, oder?

**Comment by jbleyel** [comment]
YES
