### ISSUE TITLE
Timer / Screen Overlap

### ISSUE THREAD

**Issue by hd75hd** [E2OpenPlugins/e2openplugin-OpenWebif#519]
Wenn man die normalen Timer aufruft ( Firefox ),
dann überlappt unten die Ansicht mit der Fußzeile

![owebif](https://cloud.githubusercontent.com/assets/14372018/20865160/e80dc420-ba0a-11e6-87a2-8a4a028f4f9e.png)

**Comment by jbleyel** [comment]
Hast du wirklich den letzten Stand?

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/515
