### ISSUE TITLE
OpenwebIF - NFS Netzwerkfreigaben mehrfach

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#521]
Dieter sieht seine Freigaben gleich dreimal im Web-Interface: https://www.vuplus-support.org/wbb4/index.php?thread/103024-openwebif-nfs-netzwerkfreigaben-3-fach/

Und hier die dazugehörigen Bilder:

![img_0498](https://cloud.githubusercontent.com/assets/15088943/20900894/57dfc91c-bb30-11e6-8d05-4aa2ba7f4f70.jpg)

![img_0501](https://cloud.githubusercontent.com/assets/15088943/20900803/fd17baa8-bb2f-11e6-9405-4addc4c383c4.png)

Da scheint mir glob() "Schuld" dran zu sein.

**Comment by Schimmelreiter** [comment]
Den Fehler hat plnick eingebaut:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/6c524e6d9911ead3795ceaa9a10202a02a8e9671

Ich habe das ursprünglich nur die richtige Datei auto.network auswerten lassen und damit hätte es auch gepaßt.
Aber VTi mußte ja unbedingt wieder was anders machen, als man mit Jahren Verspätung autofs-Support auch offiziell nachgereicht hat, und eine zweite auto.network - ich meine auto.network_vti - einbringen. 
Durch das blöde Wildcard werden jetzt natürlich auch diverse Mülldateien mit ausgewertet:
.old
.bak
~

**Comment by Schimmelreiter** [comment]
Statt Wildcards zu benutzen wäre eine Schleife über die wirklich in Frage kommenden Dateien sinnvoller gewesen.
