### ISSUE TITLE
Feature Request: Radio EPG

### ISSUE THREAD

**Issue by Cordhose** [E2OpenPlugins/e2openplugin-OpenWebif#522]
Hi there,

I'm listening to radio quite often. While there's a very good EPG overview for the TV bouquets, there's no EPG for the radio stations (just for single radio stations).  Maybe that's due to the fact that most radio stations don't transmit EPG data. But over here in Germany, all puplic radio stations do transmit EPG and for several days in advance.

Would it be possible to implement a Radio Guide just as the one that's available for TV channels?

Greetings,
Cordhose

**Comment by Cordhose** [comment]
Just wanted to say thank you for implementing the radio EPG!

Greetings,
Cordhose

**Comment by Schimmelreiter** [comment]
Ich mach das wohl rückgängig **g**

Es gibt da nämlich eine kleine Inkonsistenz:
Wenn man auf "Fernsehen" geht, dann auf "EPG" und dann mittels des Buttons "TV/Radio" auf das Radio-EPG wechselt, dann sieht man Radio, ist aber immer noch im Modus Fernsehen.

Das merkt man dann, wenn man links (noch mal) auf "Fernsehen" geht:
Es tut sich nichts, denn obwohl Radio angezeigt wird, wähnt sich OWIF noch im Fernseh-Modus.

Ich bau stattdessen einen "EPG"-Button in die "Radio"-Ansicht (Die ist nun identisch mit der "Fernsehen"-Ansicht), was uns zum nächsten Punkt bringt:
Ggf. sollte man statt der zwei Menüpunkt "Fernsehen" und "Radio" nur einen Menüpunkt "Sender" machen.
Die TV/Radio-Umschaltung wäre dann abgesetzt aber in derselben Zeile wie "Aktuell", "Favoriten", "Anbieter", "Satelliten", "EPG" sinnvoll.

Also so:
![image](https://cloud.githubusercontent.com/assets/2022025/21302264/c18eae2a-c5b5-11e6-84af-bbfa8c4f9414.png)

**Comment by jbleyel** [comment]
Warte mal..

**Comment by Schimmelreiter** [comment]
Stunden zu spät :)

**Comment by jbleyel** [comment]
Ich hab mir mal den letzte Stand geholt und keinen Fehler.
d.h Ich würde auf jeden Fall das Menü links so belassen mit Fernsehen und Radio.
Und den Button TV/Radio links neben "Aktuell" NICHT einbauen.

**Comment by Schimmelreiter** [comment]
Den Fehler hab ich ja auch ausgebaut.
Man kommt jetzt nicht mehr über Fernsehen -> EPG -> TV/Radio in eine Ansicht, in der man glaubt, im Radio-Modus zu sein, aber im Fernsehmodus ist.

**Comment by jbleyel** [comment]
Okay.. dann habe ich den Fehler wohl gar nicht mitbekommen.

**Comment by Schimmelreiter** [comment]
Ich habe wohl noch etwas rausgenommen:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/960b332f42fa921b1896551420d6813ce855bf77/sourcefiles/js/openwebif.js#L1391-L1395

Das "Last Bouquet" kann beides sein, TV oder Radio.
War das Last Bouquet ein TV-Bouquet und man ging ins Radio-EPG, hatte man trotzdem das EPG vom TV-Bouquet.
Vielleicht haste ja Nerv, das so umzuschreiben, daß es wieder genutzt wird, wenn es zum Modus TV/Radio paßt und nur dann ignoriert wird, wenn es vom anderen Modus stammt.

**Comment by jbleyel** [comment]
Mach ich.

**Comment by Schimmelreiter** [comment]
Und denk noch mal über "Sender" statt "Fernsehen" **und** "Radio" nach.
Spart einen Menüpunkt und im Moment sind tv.tmpl und radio.tmpl nahezu 100% code duplication.
Auch in ajax.py ist da duplicate code deswegen.

**Comment by jbleyel** [comment]
Okay..das ist nicht von der Hand zu weisen.
Radio.tmpl und tv.tmpl sowie ajax.py kann man auch ohne den einen Menüpunkt vereinfachen.

Den TV/Radio Button links neben "Aktuell" finde ich grafisch nicht so schön, denn die 5 Buttons sind jetzt zentriert und dann nicht mehr.
Evtl. bekommt man das aber doch irgendwie hin.

Mir ist es komplett Wurst, denn ich nutze Radio überhaupt nicht -> Vermutlich wie 80% der User.
Von mir aus kann das komplett raus.

**Comment by Schimmelreiter** [comment]
Ich benutze es nicht häufig, aber schon hin und wieder.

**Comment by jbleyel** [comment]
Ich Schau mal ob die beiden neuen Buttons etwas besser plaziert bekomme.
Dann kann man das machen.

Die directlinks muss ich dann auch alle umbauen.

**Comment by sgse** [comment]
Hi, ist bestimmt falsch hier ;)
Erster Timer wird schön in rot eingetragen, der zweite zur selben Zeit nicht (Timer wird gesetzt aber nicht im EPG in rot mit "Timer" ergänzt). Erster Timer auf Pro7.

![vpn35](https://cloud.githubusercontent.com/assets/17575778/21325082/c43608ac-c624-11e6-9f9b-09d23765daa9.png)

**Comment by jbleyel** [comment]
War der Timer schon da oder hast du den erst angelegt?

**Comment by sgse** [comment]
Gute Frage.
Ich habe versucht es nach zu stellen. Alles wieder gut. Sogar mit Meldung Timerkonflikt ;;-). 
Es liegt dann wohl am Browser/Mint 18.1 oder am Wetter.  
Wenn ich das wieder mal alleine hatte, sorry.

**Comment by jbleyel** [comment]
Ich mach das mal zu...
