### ISSUE TITLE
OpenWebif crash with oscam

### ISSUE THREAD

**Issue by OpenSPA** [E2OpenPlugins/e2openplugin-OpenWebif#523]
OpenWeif crashes when you are using oscam, and oscam.conf doesn't exists in oscam config folder.

![image](https://cloud.githubusercontent.com/assets/2924560/20931419/496276b8-bbd1-11e6-8eca-2cdaad6dedcf.png)

Solution may be change line 273 of base.py, 

from 		if  self.oscamconf is not None:
to 		        if fileExists(self.oscamconf) and self.oscamconf is not None:

**Comment by Schimmelreiter** [comment]
I'm getting a headache trying to construct a condition under which this would happen.
If oscam is not running, there is no file oscam.version and if there is no oscam.version, self.oscamconf is None, which is already checked.
And if oscam is running, there must be an oscam.conf too.

**Comment by OpenSPA** [comment]
Not exact, you can use oscam without oscam.conf, and oscam runs with default config (we suppose). Oscam.version exists, so system reads it but ospath can exist or not. If not exists you can't use openwebif. Is not a normal condition, I know, but it's possible, so we send this issue. One user from our forum has had this issue so we have found the problem.

**Comment by Schimmelreiter** [comment]
That can hardly be a legit and original oscam.
But I'll apply a proper fix (Your suggestion will crash for everyone who does not use oscam).

**Comment by OpenSPA** [comment]
Our oscam is legit and original, is the 12179 build. If you need binary file, we can send it.

**Comment by Schimmelreiter** [comment]
Doesn't matter.
I now intercept the strange condition that oscam.version exists but oscam.conf doesn't.

I use my own oscam btw: https://github.com/Schimmelreiter/oscam-schimmelreiter
The bitbakes from sample-bb can be used directly with our build-env.

It's in sync with trunk but has gorgone's modern webif and emu support.
