### ISSUE TITLE
Suggestion: Rewrite api for node.js

### ISSUE THREAD

**Issue by bozzzi** [E2OpenPlugins/e2openplugin-OpenWebif#525]
I would like to rewrite complete api from scratch for node.js.

Any suggestion? Pros/Cons?

**Comment by rdamas** [comment]
Why?

**Comment by jbleyel** [comment]
The rest api is running on the box via phyton twisted web service and needs to be untouched in case of 3rd party usage.

Or what api do you mean?
You wan't rewrite all jquery UI controls, are u sure?

**Comment by bozzzi** [comment]
As you know enigma2 has great API (STB_IP/web/), my idea was to install node on STB, start web server running on node (Express) and not Phyton, create UI to graphically expose enigma API options to end users.  Why does it need to be untouched?

@rdamas 
Why? - To try to exclude python include node and all event-driven, non-blocking I/O thing about it, and on the other side use only Javascript as development technology.

**Comment by rdamas** [comment]
Question: how do you plan to connect the enigma2 session to your node server? I see only one way: use the existing API. If only for that reason, a switch is pointless IMO.

I don't give a cent on anyone promising 5 times lower heap, 10 times faster load times. You have to prove that. Besides of that: I love Python, and I'm all but a fan of prototype based object oriented programming like you have to do in Javascript :-)

But: in the end it's open source software and it is free to you to create something that you can present. This is my 2 cent, and I'll leave the discussion from here.

**Comment by bozzzi** [comment]
Thx for comments. 

When I prepare something for presentation, I will be glad to let you know.

Just two more things if you can help me with:

1. Do I need to join some kind of enigma developer program in order to be able to compile source (Licences, ETC).

2. What do I need to do in order to allow remote access to web interface like from local network? Currently server is blocking remote connections (403.6 IP address rejected).

Thank you once again

**Comment by jbleyel** [comment]
Hi @bozzzi , you need to check a few things first.
* does node.js running on all boxes / low cpu and very low "disk" space
* is node.js available for all platforms (arm,mips,...)
* can node.js use enigma2 api 
* do you have python skil

For all point's i will say. -> 'Forget it'
