### ISSUE TITLE
Question : Change themes

### ISSUE THREAD

**Issue by OpenSPA** [E2OpenPlugins/e2openplugin-OpenWebif#526]
We have tried to change themes but can only use original and clear, but base.py code is written to do exactly that. 

if not os.path.exists(getPublicPath('themes')):
			if not ( theme == 'original' or theme == 'clear'):
				theme = 'original'
				config.OpenWebif.webcache.theme.value = theme
				config.OpenWebif.webcache.theme.save()

theme public folder doesn't exists, so always execute the conditional. Why have you written these lines?

**Comment by OpenSPA** [comment]
sorry, I have just seen theme folder in GIT

**Comment by Schimmelreiter** [comment]
Also see:
https://github.com/oe-alliance/oe-alliance-core/commit/d612516b381a8382ad1b5aa34ad1c9e1882a4e1d
https://github.com/oe-alliance/oe-alliance-core/commit/1d940c46487ee5a0e86db0f4f674b4e33f60c7ce
