### ISSUE TITLE
Can't change recording location in open Web-If

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#529]
(How) can i change recording location in open Web-If? Don't see option for it.

**Comment by sgse** [comment]
![vpn21](https://cloud.githubusercontent.com/assets/17575778/21056080/5d9734d8-be34-11e6-87ee-7c30bc80de41.png)
In Settings -> Record/s/ing, do not know in english.
![vpn22](https://cloud.githubusercontent.com/assets/17575778/21056188/dc248800-be34-11e6-9cb1-c487d619db5b.png)

**Comment by rocco99222** [comment]
Don't see that option.

<img width="691" alt="openwebif" src="https://cloud.githubusercontent.com/assets/23723818/21058663/58e49556-be3f-11e6-9a47-8c0a075db044.PNG">

**Comment by sgse** [comment]
Maybe ask the manufacturer of your box-image. I use VTi with EMC.

**Comment by rocco99222** [comment]
I have VU+ Solo SE with OpenPli 4.
But VU+ never response on email mesages.

**Comment by sgse** [comment]
Sorry about my English, ask Openpli 4, developer of your image.

**Comment by rocco99222** [comment]
Don't know who the developer is. (my English is bad too)

**Comment by sgse** [comment]
http://forums.openpli.org/
![vpn24](https://cloud.githubusercontent.com/assets/17575778/21064053/209c3a2c-be59-11e6-83c4-98fd3398d69e.png)

**Comment by rocco99222** [comment]
There saying that they don't create the Webif.

**Comment by Priskvark** [comment]
Not all system settings are supported in OWIF. I am not sure what setting you are looking for? If you mean the default location of recordings it must be set in your BOX-interface (not from OWIF): Settings => System => Recording Paths. For most users this is a “set it and forget it” value. 

If you want to set a path different from the default for some recordings just follow the instructions from sgse.

You can also set a path in Auto Timer-recordings. This is set just above the ”Labels” entry in OWIF interface. You will easily find it…

**Comment by rocco99222** [comment]
What/where is "Labels" entry in OWIF interface? Don't found anything.

**Comment by sgse** [comment]
Change the image (openATV / VTi etc.) for your receiver if your current version is not so comfortable for you.

**Comment by rocco99222** [comment]
Sorry, no hate VTi.

**Comment by Priskvark** [comment]
@rocco99222 "What/where is "Labels" entry in OWIF interface? Don't found anything.". 

I agree - one can feel that it’s hard to find that word. I just did a fast spontaneous late night translation from my Swedish user interface to English and it became a bit confused. 

Please instead try to find “Tags”, or even better find the text “Use a custom location” and from there you will find how to change the location of an Auto Timer recording

**Comment by rocco99222** [comment]
Please explain with picture. Thanks.

**Comment by Schimmelreiter** [comment]
Continue in #534
