### ISSUE TITLE
Timer/Autotimer Backup + Restore

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#535]
Allow copy timer,autotimer from one box to another via backup.gz.

**Comment by rklrkl** [comment]
Isn't this the same as issue #471 that I opened more than 2 weeks earlier?

**Comment by jbleyel** [comment]
No, it's only similar and not the same and needs to split.
A full backup and restore of all settings is not planed.

Bouquets backup and restore is included already.
Autotimer Backup and Restore needs a modification of the autotimer integration.
Timer Backup and Restore needs some more things to do.

The major problem is : You can't backup or restore some files if enigma2 is running.

**Comment by Schimmelreiter** [comment]
This brings us back to the topic that E2 is badly coded.
E2 would just need to handle signals like SIGUSR1, SIGUSR2 and SIGHUP correctly.

**Comment by jbleyel** [comment]
BQE and AT have a backup and restore function.
We only need to use this.

Timer backup/restore -> NO Plan.
