### ISSUE TITLE
add webradioFS?

### ISSUE THREAD

**Issue by fs-plugins** [E2OpenPlugins/e2openplugin-OpenWebif#537]
Hello,
Is it possible to add the webradioFS link to the webinterface?
(IP:port/webradiofs)
Can / should I do something for it?

or in your plugin controllers/base.py add?:
`		if fileExists(resolveFilename(SCOPE_PLUGINS, "Extensions/webradioFS/webradioFSSite.pyo")):
			webradiofs_key = "webradiofs"
			if fileExists(resolveFilename(SCOPE_PLUGINS, "Extensions/WebInterface/plugin.pyo")):
				try:
					webradiofs_port = "http://" + ip + ":" + str(config.plugins.Webinterface.http.port.value) + "/"
					webradiofs_key = lcd4linux_port + 'webradiofs'
			except KeyError:
					webradiofs_key = None
			if webradiofs_key:
				extras.append({ 'key': webradiofs_key, 'description': _("webradioFS") , 'nw':'1'})`

**Comment by jbleyel** [comment]
Where is the source code of this plugin?

**Comment by RobvanderDoes** [comment]
LOL... it's a 'closed source' plugin.

**Comment by jbleyel** [comment]
Then I will certainly not install on my box.

**Comment by RobvanderDoes** [comment]
Correct :)
Te same applies to other plugins from the same author; for one of which he even asks money.....

**Comment by Schimmelreiter** [comment]
I could decompyle it for ya ;)

**Comment by RobvanderDoes** [comment]
LOL, yeah, that's not the point. The point is the attitude to supply closed source plugins (for free and even for money) to a huge Open Source community who does all for free and in the open.

**Comment by jbleyel** [comment]
No Source -> No Support .. That's my position.

**Comment by Schimmelreiter** [comment]
Where can I find the E2/dvbapp2 sources for VTi? *vbeg*

**Comment by RobvanderDoes** [comment]
LOL.... You can't .....
Same shame.

**Comment by jbleyel** [comment]
VTi let all py files on the box.

**Comment by RobvanderDoes** [comment]
True, but that's only part of the source.

**Comment by jbleyel** [comment]
You can ask @plnick for the rest.

**Comment by RobvanderDoes** [comment]
I've done that, several times. No joy, only reference to 'the sources on the box'.

**Comment by Schimmelreiter** [comment]
And E2s original licence mandates that sources are published under the GPL ...
... so actually VTi is not only closed-source but also violating the GPL.
A plugin author on the other hand can chose whatever licence he deems fit.

**Comment by RobvanderDoes** [comment]
When I mentioned this on their forum I was banned. Not that I miss it, but it shows their attitude,

**Comment by fs-plugins** [comment]
Is understandable, thanks for the information

**Comment by jbleyel** [comment]
You are not 100% correct.
http://www.zebradem.com/archive/index.php/t-63963.html

**Comment by Schimmelreiter** [comment]
That's a different topic.
It's just about the use of the name "Enigma2".

It even says:
"Und da die verwendete Software nun einmal von Dream Property als Enigma bezeichnet wurde, darf der rechtmäßige Verwender der freien Software diese auch als Enigma bezeichnen. Voraussetzung ist jedoch, dass die **Lizenzbedingungen der GPLv2 vollständig eingehalten** wurden."
(And as the software used was referred to as Enigma, the user of this software can refer to it as Enigma as well. **Condition is, that the conditions of the GPLv2 are fully met.**)

By now referring to Enigma2 as dvbapp2, they are avoiding contradicting this, but they are still in violation of the GPLv2.

**Comment by jbleyel** [comment]
Ich bin kein Markenrechtsexperte.
Bei enigma2 gab es mal ein Problem und bei einigen Plugins auch.

Wieso hat OpenPLI das webinterface Plugin nicht drin?
Ich meine genau deswegen.

**Comment by Schimmelreiter** [comment]
Richtig.
OpenPLi hält sich absolut sklavisch an die Lizenzbedingungen.
VTi hingegen überhaupt nicht.

**Comment by RobvanderDoes** [comment]
That was indeed a different issue: Dream claimed the name 'Enigma' to be theirs..
VU supplies their software under GPLv2 and that software(source) is used by VTi as basis for their images. By not providing their source under GPLv2  they violate that license. And they know it otherwise they wouldn't have banned me from their forum after politely asking for their repository

**Comment by jbleyel** [comment]
Wayne? I have switched from VTi to OpenATV.

**Comment by Schimmelreiter** [comment]
Meinst Du den hier?
![image](https://cloud.githubusercontent.com/assets/2022025/21398847/4af8f266-c7a9-11e6-9a5c-dc4141e0bfc0.png)

:)

**Comment by Schimmelreiter** [comment]
![image](https://cloud.githubusercontent.com/assets/2022025/21398878/6fc5ecde-c7a9-11e6-949a-255b1569f982.png)

**Comment by jbleyel** [comment]
YES.. ABSOLUTLY .. RIGHT. !!!!
