### ISSUE TITLE
EPG Search should return results in overall date order

### ISSUE THREAD

**Issue by rklrkl** [E2OpenPlugins/e2openplugin-OpenWebif#538]
If I type a keyword (e.g. "alpine") in the EPG Search that matches multiple programmes in multiple channels (e.g. in Eurosport 1 and 2), then the results returned are shown date-ordered per channel (e.g. all of Eurosport 2's matches in date order then all of Eurosport 1's). This is very inconvenient because you've got to keep scrolling up and down to plan your viewing/recording schedule and also see if there's clashes.

It would much better if the results could be returned in overall date order (e.g. mixing Eurosport 1 and 2 results so you have a true strict timeline across all the channels without the time "resetting" half way through like it currently does).

**Comment by rdamas** [comment]
Yeah, I totally agree; the necessary change is a one liner:
```diff --git a/plugin/controllers/ajax.py b/plugin/controllers/ajax.py
index bbd9689..d92f80c 100644
--- a/plugin/controllers/ajax.py
+++ b/plugin/controllers/ajax.py
@@ -127,7 +127,7 @@ class AjaxController(BaseController):
                        if "full" in request.args.keys():
                                fulldesc=True
                        ev = getSearchEpg(request.args["sstr"][0],None,fulldesc)
-                       events = ev["events"]
+                       events = sorted(ev["events"], key=lambda ev: ev['begin_timestamp'])
                at = False
                if len(events) > 0: 
                        t = getTimers(self.session)
```

**Comment by Schimmelreiter** [comment]
Can you also add "channels from boquets only"? :)
One annoyance is that I usually get hits from lots of foreign stations too.

**Comment by RobvanderDoes** [comment]
You already have the following choices before executing the search:
![search_epg_choices](https://cloud.githubusercontent.com/assets/1040294/21338260/da8bb96c-c674-11e6-87a1-ba1a8527b762.jpg)

So what are you still missing?

**Comment by Schimmelreiter** [comment]
Uhm, Rob, we are on the OWIF git here :)

**Comment by RobvanderDoes** [comment]
And OWIF doesn't adhere to the settings made in E2?

**Comment by RobvanderDoes** [comment]
Ah, OK, OWIF uses it's own search....

**Comment by rdamas** [comment]
Will build a patch later :-)
