### ISSUE TITLE
Day of the week should be shown in Movies and Timers lists

### ISSUE THREAD

**Issue by rklrkl** [E2OpenPlugins/e2openplugin-OpenWebif#541]
If I click on the Movies or Timers links in the Web interface, the programmes are shown with the date, but bizarrely without the day of the week (e.g. "Mon"). Could the day of the week be added to the Movies/Timers lists please - the EPG has the day of the week displayed after all :-)

**Comment by rocco99222** [comment]
I totaly agree, please add day to that!
