### ISSUE TITLE
Rename Recording on NAS failed

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#542]
Rename on in internal HDD works

NAS is Not readonly - > delete is working

Image: OpenATV 5.3

**Comment by doubleO8** [comment]
I suppose using `os.rename` may cause problems here.
Quoting the [python documentation](https://docs.python.org/2/library/os.html#os.rename):  _The operation may fail on some Unix flavors if src and dst are on different filesystems_. The latter is the case as the renaming operation will be from an `ext4` filesystem to something like `cifs` or `nfs`.
If the rename operation actually fails one could fall back to copying the source file(s) to the remote filesystem and delete the source(s) on local filesystem afterwards. [shutil](https://docs.python.org/2/library/shutil.html#shutil.copyfile) is your friend.
