### ISSUE TITLE
Enigma2 websockets

### ISSUE THREAD

**Issue by ddemon7** [E2OpenPlugins/e2openplugin-OpenWebif#545]
Is there a way to communicate with Enigma2 using websockets? Or another way of having the receiver itself push information when something changes?

I'm developing a client app that communicates with my receiver using the OpenWebif API. The problem is that when I'm acting on changes (for example the box is turned on or off, channel changes, volume level changes, etc.) I have to **poll** the receiver. It would be nice if my app could receive changes in realtime. 

BTW, if the goal of OpenWebif is not to provide such functionality (ever), I appreciate it if you could push me in the right direction (for example, letting me know if polling is the only way to go). Thanx!

**Comment by jbleyel** [comment]
No way. 
-> Openwebif uses python twisted webservice without any async features
-> engima2 have no socket interface

You can write your own plugin with your own async socket but this plugin needs to make the pull.
