### ISSUE TITLE
Why diffent sections don't have own link?

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#546]
#Exsample:  http://122.160.6.543/EPG

Only OScam webif have own link.

**Comment by jbleyel** [comment]
What is your exact problem?

**Comment by rocco99222** [comment]
Want to go with link directly to a section, currently that isn't possible.

**Comment by jbleyel** [comment]
* jump to a page directly
1. param (tv,radio,movies,timer)
2. param (mepg,mepgfull)

Call : http://<IP>/#<1.param>#<2.param>

**Comment by Schimmelreiter** [comment]
That doesn't work, at least not for timers
