### ISSUE TITLE
Recordings do not show recording day.

### ISSUE THREAD

**Issue by rocco99222** [E2OpenPlugins/e2openplugin-OpenWebif#547]
Why not?

**Comment by rklrkl** [comment]
This is a duplicate of issue #541 that I raised a week ago.

**Comment by jbleyel** [comment]
Please check your recordings.

<img width="439" alt="bildschirmfoto 2016-12-28 um 23 44 19" src="https://cloud.githubusercontent.com/assets/964927/21533114/9669abec-cd57-11e6-9c8a-f32ac5c87b07.png">

**Comment by jbleyel** [comment]
If you mean the weekday -> #541
