### ISSUE TITLE
API call for timeshift

### ISSUE THREAD

**Issue by fabsi88** [E2OpenPlugins/e2openplugin-OpenWebif#551]
Is there any way to initiate a timeshit via api calls? Right now we are not able to find any method for triggering the pause except for faking it via remotecontrol (which is not reliable enough in my opinion).

**Comment by Extrawurst** [comment]
or are the remotecontrol buttons for pause/play uniformly working across different hardware ?

**Comment by Schimmelreiter** [comment]
They should, if you send "Play" and "Pause" key codes and not the "Play/Pause" key code, even if the box' remote only has a Play/Pause button.

Background: "Multi-Vendor-Distros" usually use the same keymap for all boxes. Key codes for non-existant buttons inside the keymap do not matter, as the corresponding button simply can not be pressed and thus the event can never occur, but they should work anyways if send verbatim using the OWIF.

Example:
```
		<key id="KEY_PLAYPAUSE" mapto="playpauseService" flags="m" />
		<key id="KEY_PAUSE" mapto="pauseService" flags="m" />
		<key id="KEY_PLAY" mapto="playpauseService" flags="m" />
```
While my Vu+ doesn't have a separate "Pause" button, they keymap contains an action for it anyways.

Please note that the "Play" and "Play/Pause" buttons are mapped to the same action ... playpauseService, so you can not be sure that the box is in Playing state after sending "Play", it might as well be in Pause state, as it actually is a toggle button.

So for "Play" you should actually send "Pause" followed by "Play" to make sure "Play" toggles from Pause to Play and not vice versa.

This might fail however for images specifically made for only one brand, e.g. Black Hole and VTi, as they do not need to care about key codes for non-existant buttons.

**Comment by fabsi88** [comment]
Thank you for the detailed reply :) Obviously the toggle mode is a con :( But we will give it a try. Is there any possibility to enhance the owif for an rest api call? 
I hope my Vu+ (with VTi) will handle it like the "common" boxes.

**Comment by Extrawurst** [comment]
+1 for a REST call

**Comment by jbleyel** [comment]
Check the last commit.
