### ISSUE TITLE
Versions shown in Package Manager/ipkg do not reflect true version

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#555]
E.g.:
Version shown: busybox (1.24.1-r0.31)
True version installed: busybox (1.24.1-r0.32)

Reloading page or deleting cache has no influence.

**Comment by jbleyel** [comment]
Schau mal was da steht .../ipkg?command=list_installed

**Comment by Schimmelreiter** [comment]
Im Moment die richtigen Versionen.
Ist schon ein paar Tage her, daß ich diese Sache beobachtet habe.

Ich melde mich einfach, wenn's das nexte Mal nicht mehr paßt.

**Comment by Schimmelreiter** [comment]
So:
Einstellungen -> Packages -> Installed -> E im OWIF zeigt:
enigma2 (5.3+git23553+a204ba9-r3)

Update gemacht, OWIF zeigt immer noch
enigma2 (5.3+git23553+a204ba9-r3)

/ipkg?command=list_installed hingegen zeigt:
enigma2 - 5.3+git23562+882c607-r3

**Comment by Schimmelreiter** [comment]
Öffnen in anderem Browser zeigt aber auch
enigma2 (5.3+git23562+882c607-r3)
Also ist es ein Cache-Problem, würde ich sagen.

**Comment by jbleyel** [comment]
Jo hast recht, die Liste wird im Browser gecached, sonst würde es zu lange dauern.
Ich meine das der Cache nach 1 Tag verworfen wird.
Ich bau da mal ein Cache clean ein.

**Comment by Schimmelreiter** [comment]
Kannste mal? :)

Die Benutzer nutzen dieses Feature tatsächlich und sind durch die abweichenden Versionen verwirrt.

Vielleicht kann man dem Browser ja den Timestamp der entsprechenden Dateien mitgeben, damit nur so lange gecached wird, wie sich nix ändert ...

Für die installierten Versionen wäre das die Datei `/var/lib/opkg/status` und für die verfügbaren das Dateidatum der neuesten Datei im Verzeichnis `/var/lib/opkg/lists/`.

**Comment by jbleyel** [comment]
Ich schau mir das heute mal an.

**Comment by jbleyel** [comment]
Cache ist jetzt eine Stunde.

**Comment by Schimmelreiter** [comment]
Kriegt man die Änderung nicht in Echtzeit hin, wenn man das Dateidatum der entsprechenden Dateien irgendwie mit einbezieht?

**Comment by jbleyel** [comment]
Du kannst es ja mal versuchen.
Dazu müsste man unter /opkg/lists alle Dateien prüfen und die neuste rausfinden.
Dann dieses Datum in ajax/settings übergeben.
Dieses Datum kann ich dann anstatt der einen Stunde benutzen.

**Comment by jbleyel** [comment]
os.path.getmtime(file)

**Comment by jbleyel** [comment]
http://stackoverflow.com/questions/168409/how-do-you-get-a-directory-listing-sorted-by-creation-date-in-python

**Comment by jbleyel** [comment]
Den javascript Teil übernehme ich.
