### ISSUE TITLE
picon path not working

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#556]
/media/usb/picon 
not working on OpenATV.

**Comment by Schimmelreiter** [comment]
It definitely does work... that's the path that I use ... on 4 boxes ... plus I set it up on many more that way.

**Comment by jbleyel** [comment]
Ja..die Box hat sich heute mal wieder weggehängt und nach dem Reboot sind die Picons auf einmal da. 
Gestern ging es definitiv NICHT.
Im OSD waren die Picons da und im openwebif nich.

Ich hab aber vorgestern erst den USB Stick rein und die Picons draufkopiert.
Nachdem ich das 5.3 Image wieder neu draufgespielt hatte.

Mir ist dabei aufgfallen, das man die EPG.DAT NICHT auf den USB Stick legen kann.
BUG oder FEATURE????

**Comment by Schimmelreiter** [comment]
OWIF entscheidet sich nach meiner Erinnerung nach genauso wie E2 einmalig beim Start für den/die zu verwendenden Picon-Pfad(e).
Nachträglich hinzugefügte Speicherorte werden erst beim nächsten Neustart berücksichtigt. 
Kann man als Bug oder als Feature sehen ...
