### ISSUE TITLE
Crash when creating screenshots in quick consecution

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#559]
Since https://github.com/oe-alliance/e2openplugin-OpenWebif/commit/9ee5b2d86cf1cf35ec04b2acfa767afc427463e9
creating screenshots in quick consecution (E.g. double clicking the "Refresh" button) makes OWIF crash:

```
03:08:31.4688 { D } Traceback (most recent call last):
03:08:31.4690 { D }   File "/home/ziggy/E2/atv60.test/build-enviroment/builds/openatv/release/hd2400/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+5f5cf81137-r1/git/plugin/controllers/models/grab.py", line 67, in grabData
03:08:31.4696 { D }   File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 220, in write
03:08:31.4701 { D }   File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 955, in write
03:08:31.4707 { D } AttributeError: 'NoneType' object has no attribute 'writeSequence'
03:08:31.4770 [   ] python/python.cpp:209 call (PyObject_CallObject(<bound method grabScreenshot.grabData of <Plugins.Extensions.OpenWebif.controllers.models.grab.grabScreenshot instance at 0x7135a738>>,('\xf0\xf1u\x95E\xcb\x13\xb1x\xde\xfeh`\xb1\xb5o8\x90\x8aVR\xdb\xc7\xe28\xfaW\xd2\x1f\xb2\xdf\xec\x1f\xe2?\x8a\x97\x16\xda\xe7\x8c|\x1f\xaa[i!\x84\xb2\xddZ\xd9y\xaf*\xf5]\xbd\x07=\xfau\xa7|\x17\xfd\x9c4\xcf\x0bX\xdb\xeb\xfe$\xba\x96{\xa4\nZ4\xc4b6\xc7+\x94bx<u\xaf\xb2~\x00|N\xd3&\xd3`\xf0]\xd6\xadqn\x17j[+j\x97\x188\x18\x03\x05\xb6\x9a\xe8\xa3QJ\xa5\x8f:\xb5\x1a\xb4)\xf3X\xf4?\x82^\x05?\n|;\x1f\x84\xfc\x0c\xd2\xe9\xd6Gh{Y\xb4X-\x98\x80\xb8\xcb:\xeei\x1b\xea}\xf3^\x87\xa5i6\xfa\x04\r%\xbc\x0c\xd7w\x07t\xb3\x94\xf39<\x91\xce\x08\xfc\xe9\x9a\x04QYBZv\xdf69\xcfsW<\xe6-\xbd\x83\x02y#y\xeb^\xbcm\x1d\x8f"R\x94\xb75,e1\xdb\xc6d\x19m\x83=\xb1\xc7\xa0\xe9Wm\xef\xe3\xdd\xc9#\x9a\xc3\x17\xa0/+\xcd*_\xec\xe4\n\xbd\x0c9U\xce\xb2\xca\xf0O*\x94p\x02\xf1\xf3U\xf6\xd4\xe3RT\xb1\xe3\xd2\xb8\xe8\xb56@\x1c\x10\x0e=\xeaa\xac\x0cs \xe9\xcd_\xb6I\x19l\xce\xad\xb58\x90\x02X\xf3Y\
```

Previous code crashed due to missing file, new code seems to crash on missing/bad object.
I suppose the object crash is less likely, so we can keep this variant, but it should get fixed.

**Comment by milosoftware** [comment]
And it was supposed to make things better :)

I'll look into it.

**Comment by milosoftware** [comment]
I could reproduce this using a command like this:
wget http://vusolo4k.local/grab?format=bmp & wget http://vusolo4k.local/grab?format=jpg

This crashes enigma, or creates invalid image files, and things like that.

After the above commit, it doesn't crash and delivers two valid image files (though one of them lacks the video data, probably because the grab program itself cannot run twice...)

**Comment by Schimmelreiter** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/9dd3241ab041fb25a5fa31af6963fb4b025d8657
makes things better, I can even do an auto-refresh every 0.1 (zero dot one) seconds, buuuuuut:

Fast click multiple (MANY) times on the refresh button: Crash with same message as above.

**Comment by jbleyel** [comment]
This should be the right way.

https://github.com/opendreambox/enigma2-plugins/blob/master/webinterface/src/WebChilds/Screenshot.py

BUT DMM have some things done in enigma2
-> from enigma import ePixmap, getDesktop, eSize

**Comment by Schimmelreiter** [comment]
They rewrite the whole screenshot API, so nothing to compare in their code here ...

**Comment by jbleyel** [comment]
There is a simple solution.
-> https://github.com/OpenPLi/aio-grab
1. split main.c and move the code to an external lib + add some functions to use memory output
2. import the lib and send the memory buffer from the lib directly as web response.

I can do 2. but 1. sould be done by someone else.
