### ISSUE TITLE
Restart loop with mismatched versions enigma2/OpenWebif

### ISSUE THREAD

**Issue by hvdijk** [E2OpenPlugins/e2openplugin-OpenWebif#560]
After updating my VU+, I got:

```
<    38.247> Traceback (most recent call last):
<    38.248>   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in __call__
<    38.248>   File "/usr/lib/enigma2/python/Components/Console.py", line 56, in finishedCB
<    38.248>   File "/usr/lib/enigma2/python/Components/Network.py", line 131, in routeFinished
<    38.249>   File "/usr/lib/enigma2/python/Components/Network.py", line 226, in loadNetworkConfig
<    38.249>   File "/usr/lib/enigma2/python/Components/Network.py", line 673, in msgPlugins
<    38.249>   File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/plugin.py", line 187, in IfUpIfDown
<    38.250>     HttpdStart(global_session)
<    38.250>   File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/httpserver.py", line 164, in HttpdStart
<    38.251>     temproot = buildRootTree(session)
<    38.251>   File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/httpserver.py", line 88, in buildRootTree
<    38.252>     root = RootController(session)
<    38.252>   File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/root.py", line 40, in __init__
<    38.252>     self.putChild("grab", grabScreenshot(session))
<    38.252>   File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/grab.py", line 23, in __init__
<    38.253>     self.container.setBufferSize(32768)
<    38.253> AttributeError: 'eConsoleImpl.eConsoleAppContainer' object has no attribute 'setBufferSize'
```

The call to `setBufferSize` was added in https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/9a3286809b35db1b6433595c63683a4aced44336, and the method itself was added in https://github.com/OpenPLi/enigma2/commit/c9c24733ebc1d3be8e4636785b9d4050841a30a8. When updating, OpenWebif installed successfully, but enigma2 did not. I'm not sure what happened the log shows a problem with `glibc-gconv` that I have yet to look into, but the old version of enigma2 remained on the system. As a result, it ended up stuck in a never-ending restart loop until I commented out the call to `setBufferSize`.

For safety, to prevent others from ending up with the same problem, the call to `setBufferSize` should be guarded.

**Comment by milosoftware** [comment]
Commit 9dd3241ab041fb25a5fa31af6963fb4b025d8657 also solves this by no longer calling this while initializing, but only once the screenshot is requested.
