### ISSUE TITLE
Timer window in WEB-IF

### ISSUE THREAD

**Issue by RobvanderDoes** [E2OpenPlugins/e2openplugin-OpenWebif#562]
Is there a specific reason why the window in which the timers show is so small?

![owebif-timers](https://cloud.githubusercontent.com/assets/1040294/22183958/bb4b765e-e0c9-11e6-9743-c9e49745c5ee.png)

It would be highly appreciated if that window could be larger (in height).

**Comment by RobvanderDoes** [comment]
BTW: This issue doesn't only apply to the timer window, but to all main windows: a short scrollable window inside a large space.

**Comment by Schimmelreiter** [comment]
I can not reproduce this.
![image](https://cloud.githubusercontent.com/assets/2022025/22192643/f1c9f676-e135-11e6-9fd7-90566a602011.png)

**Comment by RobvanderDoes** [comment]
Which browser are you using?
I can reproduce this for all my boxes running current versions of PLi (Vs 4), ViX (Vs 4.2&5.0) & ATV (Vs6.0) using IE, FF & Chrome.

**Comment by Schimmelreiter** [comment]
Current OpenATV 5.3 or 6.0, browser Chrome plus "current" IE and current CrashFox.

**Comment by RobvanderDoes** [comment]
Then I have no idea what triggers this issue. In the mean time I tried another PC, but the result is the same.

**Comment by jbleyel** [comment]
Hi Rob, please close/hide the extras or FB menu then reload the page and try timer again.

**Comment by RobvanderDoes** [comment]
Hi, closing any or all of the 'side windows' and reloading makes no difference.
Also tried this on all browsers and on all boxes using the same images as before.
The main-windows remains small (short) whatever lay-out I choose.

**Comment by jbleyel** [comment]
Hi Rob,
do you use the exact source from here without any modifications?
Please try a different theme.

**Comment by RobvanderDoes** [comment]
Hi Jörg,
1- I'm using current PLi, ViX & ATV without any modifications, so I presume the original files are being used.
2- Changing theme (and restarting the web page) makes no difference.

As I'm using 3 different images on 10 different STB's in 5 different browsers (also Pale Moon now) on 2 different computers I find it hard to believe I'm the only one who suffers from this phenomenon :)

**Comment by Schimmelreiter** [comment]
Variant 1 (Less timers than what would fit on one page):
![image](https://cloud.githubusercontent.com/assets/2022025/22293211/134e0b68-e30f-11e6-8d22-4dca3f5e5e2d.png)

Variant 2 (More timer than what would fit on one page):
![image](https://cloud.githubusercontent.com/assets/2022025/22293245/3b176662-e30f-11e6-942d-f27a9e5f9373.png)

**Comment by Schimmelreiter** [comment]
I get the same result on ANY box I try.

**Comment by jbleyel** [comment]
very strange ????

**Comment by sgse** [comment]
Wenn ich OWIF in einem verkleinertem Fenster starte, dann Full-Window, merkt sich der Browser das kleine Fenster. Siehe
![my_picon2](https://cloud.githubusercontent.com/assets/17575778/22295723/305d9b8e-e318-11e6-8541-292e14c4149b.png)

**Comment by jbleyel** [comment]
Hi @sgse , das ist normal und schon immer so und auch nicht so einfach zu lösen.
Dazu müsste man die komplette Hauptseite umbauen.
Das traue ich mir aktuell nicht, denn das ist richtig aufwändig.
Zudem sollte man dann evtl. über bootstrap nachdenken.

**Comment by sgse** [comment]
Ich finde es super so wie es jetzt ist, keine Probleme, danke noch mal für Deinen/Euren Einsatz hier.
Ich wollte nur zeigen wie man das Bild von Rob nach stellen kann ;)

**Comment by jbleyel** [comment]
Anscheinend hat der Rob aber das Problem das selbst beim Refresh die Liste nicht grösser wird.
Das versteh ich nicht.

**Comment by Schimmelreiter** [comment]
Well, what to do?
Nobody but Rob can reproduce the problem.

**Comment by jbleyel** [comment]
Hi Rob,

i can check this only if i can get access to one of your boxes (openwebif).

**Comment by RobvanderDoes** [comment]
Hi Jörg,
sounds like a good plan. You would need to catch me on Skype (Skype name = robvanderdoes) to make the appropriate arrangements.
I'm available tomorrow morning from 07.00 till 12.00 but of course we can arrange an other time as well.

**Comment by jbleyel** [comment]
Hi Rob, i'm there. Do you have time?

**Comment by RobvanderDoes** [comment]
Yes!

**Comment by RobvanderDoes** [comment]
I invited you on Skype (hoping that's you indeed :)  )

**Comment by RobvanderDoes** [comment]
Jörg has seen and confirmed the issue, but apparently fixing this is quite some work.

**Comment by jbleyel** [comment]
Das Problem äussert sich wie folgt.
Wenn das Browserfenster zu klein ist und ganz rechts ist ein Scrollbalken, dann passt der rechte Teil vom openwebif nicht. Es wird nicht komplett ausgefüllt.
Das ganze lässt sich jedoch nicht so einfach lösen, denn dafür darf das Menü links nicht länger als das Browserfenster sein.

Dafür müsste man das komplette Hauptfenster umbauen oder das Menü kürzen.
Oder einen grösseren Monitor nehmen.
Oder den Zoom vom Browser nutzen.
Letzteres fand der Rob nicht so toll.

**Comment by Schimmelreiter** [comment]
Hm, ich hab das jetzt gerade mal mit einem kleinen Browser-Fenster ausprobiert, aber das Ergebnis ist für mich stimmig:
Die Timerliste ist dann so lang, daß sie von der Höhe her in dieses Browser-Fenster paßt.

Das einzige, was nicht stimmig ist:
Wird das Fenster danach vergrößert, paßt sich der rechte Bereich nicht an die neue Größe an, bis man die Seite neu lädt.

**Comment by jbleyel** [comment]
Ja, genau das ist das was den Rob stört.
Das geht aber nicht anders umzusetzen.
Es sei denn man macht rechts in der Liste keinen inneren Scrollbalken rein.
d.H. es gibt nur noch einen Scrollbalken ganz rechts.
Dann scroll man aber das komplette Fenster incl. Header und Menü.

Oder man baut die komplette Seite um.
Dafür muss aber das Menü kürzer werden, das es auch für "mini" Auflösungen passt.
Unter 1100px Höhe gibt es Probleme.

Beim Header könnte man 50px sparen.
Das Menü selber haben wir schon extrem optimiert.

**Comment by Schimmelreiter** [comment]
Erledigt *g*

**Comment by RobvanderDoes** [comment]
Jedenfalls freut es mir das der Jörg das Problem bestätigt hat; dank dafür.
Aber seine Lösung entweder sehr stark aus zu zoomen oder eine Laptop mit eine 33 Zoll Bildschirm zu kaufen gefällte mich weniger :)

**Comment by Schimmelreiter** [comment]
The simple solution is not to start with a small window and then make it larger but to directly start with an enlarged view (Or to reload the page after resize).

**Comment by RobvanderDoes** [comment]
Nope, that doesn't work.
