### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#563]
What do you think about having terminal/shell access in OWIF?

![image](https://cloud.githubusercontent.com/assets/2022025/22208394/05d5f528-e183-11e6-9e33-e95d643e66bf.png)

**Comment by Schimmelreiter** [comment]
BTW: The screen shot is **not** a mockup ...

**Comment by sgse** [comment]
Why not? ;-) Is it possible to change the color (blue)? 
Wer sich mit der shell auskennt braucht es vermutlich nicht, den Rest verwirrt man :-) . 
Falls du es schon fertig hast, her damit :-D und als Zusatzsoptionsfeature ein schönes Gimmick.
So, jetzt schau ich mal nach was "mockup" ist.

**Comment by Schimmelreiter** [comment]
Blau ist vom Midnight Commander.
Es gibt zwei Standard-Schemata: Schwarz auf weiß (Igitt) und weiß auf schwarz, also normal.
Ist aber per CSS auch änderbar.

**Comment by jbleyel** [comment]
Ich bin wieder da.

*Mit welchem Control soll das terminal umgesetzt werden?
*SSH oder Telnet?
*Wie sieht es mit der Sicherheit aus?

Beim Webadmin plugin ist ein ganz komisches Java control drin.
Das werde ich aber nicht einbauen.

Ich würde folgendes nehmen.
https://github.com/nickola/web-console

**Comment by Schimmelreiter** [comment]
Also letztendlich habe ich das Terminal schon fertig.
Ich frage nur nach Meinungen :)

**Comment by jbleyel** [comment]
Und mit welchem Source?
Meinungen gebe ich dir sofort, wenn ich es getestet habe.

**Comment by Schimmelreiter** [comment]
Dann baue ich es einfach mal ein, die Existenz verhindern kann man immer noch durch Nichtinstallieren des Daemons.

**Comment by Schimmelreiter** [comment]
So, ist soweit drin.

Für mips32el habe ich hier ein IPK, für ARM muß ich erst noch bauen ...
[shellinabox_2.20+git0+5c7fb5cde2-r0_mips32el.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/727420/shellinabox_2.20.git0.5c7fb5cde2-r0_mips32el.zip)

**Comment by Schimmelreiter** [comment]
Ladet Euch das ipk mal runter, ich möchte das gleich wieder löschen, es ist nämlich etwas anders gebaut, als es später auf der Box gebaut werden soll.

**Comment by Schimmelreiter** [comment]
So, da ARM immer noch baut gehe ich mal auf die Rückfragen ein:

> Wer sich mit der shell auskennt braucht es vermutlich nicht, den Rest verwirrt man :-) .

Naja, es ist schon gerade für die gedacht, die sich mit der Shell auskennen.
So hat man jederzeit einen Terminal-Zugang, ohne erst ZOC, putty, o.ä. installieren zu müssen.
Wenn man mal bei Eltern, Onkel, Tante zu Besuch ist und was an der Box machen soll, was man lieber per Shell macht, hat man so rucki zucki Zugriff.

> *Mit welchem Control soll das terminal umgesetzt werden?

Das ist "shellinabox" mit zwei zusätzlichen Patches.

> *SSH oder Telnet?

Weder noch.
shellinaboxd läuft auf der Box als Web-Server und OWIF 'reverse-proxied' dorthin.

> *Wie sieht es mit der Sicherheit aus?

Wenn man Zugriff auf das OWIF erlangt, so oder so lausig.
Aber ob der Angreifer jetzt erst noch über Deinen Paketmanager OpenVPN mitsamt einem Profil zum Verbinden ins Botnetz einspielen muß oder ob er gleich auf die Shell kann macht den Kohl auch nicht fett.
Shell-In-A-Box ist nicht zusätzlich von außen zu erreichen, man kommt nur über das OWIF dran, damit ist es genauso sicher oder unsicher wie das OWIF selber.
Wer als Login root:root oder root:dream setzt, hat so oder so verloren.

> Beim Webadmin plugin ist ein ganz komisches Java control drin.

Das funktioniert eh nicht mehr.
Man kann Java nicht mehr dazu überreden, selbst-signierte Applets auszuführen.
Das jetzt von mir eingebaute Shell-In-A-Box wird aber seit neuestem auch vom Webadmin verwendet.

**Comment by Schimmelreiter** [comment]
Hier das ipk für ARM-Boxen (Solo 4k, Uno 4k, ...):
[shellinabox_2.20+git0+5c7fb5cde2-r0_cortexa15hf-neon-vfpv4.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/727514/shellinabox_2.20.git0.5c7fb5cde2-r0_cortexa15hf-neon-vfpv4.zip)

**Comment by jbleyel** [comment]
Thanks .. ich teste mal

**Comment by jbleyel** [comment]
root@vusolo4k:/tmp# opkg install shellinabox_2.20+git0+5c7fb5cde2-r0_cortexa15hf-neon-vfpv4.ipk 
Not selecting shellinabox 2.20+git0+5c7fb5cde2 due to incompatible architecture.
Installing shellinabox (2.20+git0+5c7fb5cde2-r0) on root.
Downloading http://feeds2.mynonpublic.com/5.3/vusolo4k/armv7ahf-neon/shellinabox_2.20+git0+5c7fb5cde2-r0_armv7ahf-neon.ipk.
Not selecting libssl1.0.0 1.0.2g as installing it would break existing dependencies.
Not selecting libssl1.0.0 1.0.2g as installing it would break existing dependencies.
Not selecting libpam 1.2.1 as installing it would break existing dependencies.
Not selecting libpam 1.2.1 as installing it would break existing dependencies.
Not selecting libc6 2.23 as installing it would break existing dependencies.
Not selecting libc6 2.23 as installing it would break existing dependencies.
Not selecting libcrypto1.0.0 1.0.2g as installing it would break existing dependencies.
Not selecting libcrypto1.0.0 1.0.2g as installing it would break existing dependencies.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shellinabox:
 *      libssl1.0.0 (>= 1.0.2g) *       libpam (>= 1.2.1) *     libc6 (>= 2.23) *       libcrypto1.0.0 (>= 1.0.2g) * 
 * opkg_install: Cannot install package shellinabox.
root@vusolo4k:/tmp#

**Comment by Schimmelreiter** [comment]
Mach mal in / direkt vom Feed:
`opkg install shellinabox`
wurde ja inzwischen anscheinend schon auf dem Feed gebaut.

Mein Build ist für OpenATV 6.0

**Comment by jbleyel** [comment]
Sieht gut aus.
Kann man eigentlich so lassen.

**Comment by jbleyel** [comment]
Nur eins..
Wenn ich auf dem Terminal angemeldet bin und dann den Browser zu mache oder im openwebif auf was anderes umschalte, dann ist die Session weg.
Evtl. sollte man das Terminal als Popup Fenster umsetzten.

**Comment by Schimmelreiter** [comment]
Genau dieses gepoppe mit den Ups geht mir beim Dream Webif auf den Sack, z.B. die nervige fliegende Fernbedienung.

Wenn man eine Fullscreen-Session will, kann man ja auf
http(s)://hostname_der_box/terminal
gehen.

**Comment by Schimmelreiter** [comment]
Es gibt wohl einen kleinen Fehler im CSS:
Der rot markierte Bereich wird nicht genutzt, aber einmalig (Beim ersten Anzeigen des Prompts) rutscht der erste Buchstabe vom Benutzernamen dorthin.
![image](https://cloud.githubusercontent.com/assets/2022025/22288178/04df39f8-e2f6-11e6-8354-4b0da516bc31.png)

Das hier ist das CSS:
https://github.com/oe-alliance/oe-alliance-core/blob/367ae0730f4ccdb3c7513fa287f0f5e39d3ce9c0/meta-oe/recipes-connectivity/shellinabox/shellinabox/styles.css

Es ist zwar in shellinabox einkompiliert, man könnte es aber ändern und die geänderte Fassung als Parameter an ShellInABox übergeben.

**Comment by jbleyel** [comment]
Bei mir passiert das nicht. (Chrome)
Ich hab auch keine Scrollbar.

**Comment by Schimmelreiter** [comment]
Seltensam.

**Comment by jbleyel** [comment]
Wenn ich nach dem Passwort Enter gleich noch mal Enter drücke, dann ist es nicht.

**Comment by jbleyel** [comment]
Das ist wohl offensichtlich nicht der einzigste Fehler. 
*grins*
https://code.google.com/archive/p/shellinabox/issues

**Comment by Schimmelreiter** [comment]
Der Unterschied zwischen der Fassung von shellinabox die ich hier hochgeladen hatte und der auf dem Feed ist übrigens:
Die Version auf dem Feed ignoriert das Weglassen des Parameters --locahost-only und lauscht trotzdem nur auf localhost bzw. ::1.

Nachdem betacentauri uns einen Anti-Idioten-Patch in busybox-telnet eingebaut hat, der das Freigeben von Telnet nach draußen unmöglich macht, wollte ich mit shellinabox keine Alternative für die Idioten einbauen.
Ohne --localhost-only kann man normalerweise auch direkt mit `http://hostname_der_box:4200` auf shellinabox zugreifen ... dann hätten die Leute statt Port 23 halt Port 4200 freigegeben ... das wollte ich verhindern.

**Comment by Schimmelreiter** [comment]
> https://code.google.com/archive/p/shellinabox/issues

Falsche Quelle.
Das ist unser shellinabox: https://github.com/shellinabox/shellinabox

**Comment by jbleyel** [comment]
Ist aber nicht die offizielle Version.

**Comment by Schimmelreiter** [comment]
Die offizielle wird ja seit Jahren nicht mehr gepflegt.
Unser shellinabox ist der gleiche, wie ihn Dream verwendet, plus IPv6-Patch plus Enforce-localhost-only-Patch plus anständiges Default-CSS (White-on-Black).

Das Tool das Du vorgeschlagen hattest wäre nicht einmal eine echte Shell gewesen (Da hätte nicht einmal vi funktioniert).

**Comment by jbleyel** [comment]
Der Fehler mit dem r rechts sieht nicht nach css aus.
Der Fehler ist im HTML und das wird serverseitig generiert.

**Comment by jbleyel** [comment]
Mal was ganz anderes.

Schau mal hier...

https://github.com/opendreambox/enigma2-plugins/commit/15d61957dee1e38b0feffdf383b2fceb2a456b8c

**Comment by Schimmelreiter** [comment]
Was willst Du mir damit sagen?

**Comment by jbleyel** [comment]
Beim Durchsuchen der Änderungen von DMM ist mir das aufgefallen.
Die haben wohl alle Übersetzungen aus den Plugins raus und in eine Globale PO Datei rein.
Ich frage mich wieso?
Platz Sparen???

**Comment by Schimmelreiter** [comment]
Naja, es gibt da das Problem, daß das Zugreifen auf Übersetzungen über Plugin-Grenzen hinweg ein Problem ist.
Das siehst Du im OWIF z.B. bei "Einstellungen -> Transcoding Setup".
Die Übersetzungen für Transcoding Setup liegen in den jeweiligen Plugins (Multitranscoding Setup oder Transcoding Setup). OWIF sieht die aber nicht, da es in einer anderen Textdomäne arbeitet.

Dream hat da aber den Teufel mit dem Beelzebub ausgetrieben:
Wenn ich alle Übersetzungen zusammenklatsche, dann steigt das Risiko von Widersprüchen.
gettext ist da eine echte Krankheit, es kann denselben Text nur dann unterschiedlich übersetzen, wenn man explizit auch programmiertechnisch einen getrennten Kontext benutzt.

Wobei einem das schmerzlich auffällt ist z.B. beim Wort "clear".
Das kann ja wirklich alles heißen, von "klar" wie in Wetter bis hin zu "löschen" von Eingaben in einem Dialog ....
Irgendein Wetterservice liefert z.B. das Wetter in einem XML in Klartext (Statt eindeutiger IDs), also z.B. auch "clear" für klare Sicht. Wenn auf der Dreambox demnächst das Wetter "löschen" bzw. "zurücksetzen" ist, weißt Du jetzt, warum ;)

**Comment by jbleyel** [comment]
Das blöde ist jetzt nur, das ich beim Sync von DMM nach OE keine Übersetzungen mehr finde.

**Comment by Schimmelreiter** [comment]
Wurscht.
Die Übersetzungen reichen die User schon nach, oder sie gucken sich die Texte halt in Englisch an ;)

**Comment by Schimmelreiter** [comment]
Einen nervigen Quirk habe ich gefunden und ich muß zugeben, daß ich damit überfordert bin, ihn zu beheben:

Wenn man auf der Seite "Terminal" stehen bleibt, insbesondere wenn die Sitzung durch Timeout beendet wird, was man besonders schnell reproduzieren kann, indem man sich gar nicht erst einlogged, wird das Log mit dem Mist hier geflutet:

```
--- <exception caught here> ---
  File "/usr/lib/enigma2/python/e2reactor.py", line 181, in _doReadOrWrite
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 578, in dataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 532, in rawDataReceived
    
  File "/usr/lib/python2.7/site-packages/twisted/web/proxy.py", line 77, in handleResponsePart
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 220, in write
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 940, in write
    
exceptions.AttributeError: 'NoneType' object has no attribute 'writeHeaders'

18:44:11.3381 { E } /usr/lib/python2.7/site-packages/twisted/logger/_file.py:66 __call__ Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 121, in runReactor
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1195, in run
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1207, in mainLoop
    
  File "/usr/lib/enigma2/python/e2reactor.py", line 165, in doPoll
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    
  File "/usr/lib/enigma2/python/e2reactor.py", line 193, in _doReadOrWrite
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 478, in connectionLost
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 486, in connectionLost
    
  File "/usr/lib/python2.7/site-packages/twisted/web/proxy.py", line 87, in handleResponseEnd
    
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 231, in finish
    
  File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 863, in finish
    
exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

@jbleyel Fällt Dir dazu was ein?

**Comment by jbleyel** [comment]
Vielleicht hier ->

http://stackoverflow.com/questions/10710047/twisted-http-server-error

https://twistedmatrix.com/trac/ticket/4901

**Comment by Schimmelreiter** [comment]
Tut mir leid, bin ich zu blöd für, das auf dieses Problem zu übertragen.
Zuviel syntaktisches Salz in Python.

**Comment by jbleyel** [comment]
LOG Trace:
Ich hab versucht ReverseProxyResource umzuschreiben um den Fehler abzufangen. -> Ohne Erfolg
Dann hab ich versucht den Fehler in der e2Reactor.py abzufangen, das hat zwar funktioniert aber dann schiert das Teilt trotzdem ab. 
Ich bin daher hier mit meinem Latein am Ende.

**Comment by jbleyel** [comment]
CSS bzw. Javascipt  .. Login issue : 
Das ist ein Bug von shellinabox JS und muss dort gefixt werden.
