### ISSUE TITLE
Inconsistencies in Bouquet Editor

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#564]
![image](https://cloud.githubusercontent.com/assets/2022025/22302522/784bfd34-e32f-11e6-80c0-1321d54f20ba.png)

**Comment by jbleyel** [comment]
Up/Down arrow : d'accord
But what you mean with left/right action exactly?
I'm at a loss. A little bit.

Buttons with left arrow and button with right arrow in the middle between the lists? or what?

**Comment by Schimmelreiter** [comment]
Nein, ich will nicht, daß Du daraus Up/Down-Pfeile machst, sondern den Kreuzpfeilen einen Sinn verpaßt :)
Wir bräuchten "Anbieter als Bouquet hinzufügen" gar nicht als Button, wenn man den Anbieter einfach rüberziehen könnte.
Und genauso könnte man Bouquets löschen, indem man sie aus der Bouquet-Liste rauszieht.

Und Sender könnten zugefügt werden, indem man sie aus der linken Liste in die rechte zieht ...
... usw.

**Comment by jbleyel** [comment]
Drag'n'Drop zwischen den 4 Listen geht nicht, das geht nur innerhalb einer Liste.
Daher gibt es die Buttons.

**Comment by jbleyel** [comment]
Die Pfeile hab ich auf dem Plan.
Ich hab nur noch keine passenden Bilder gefunden.

http://fontello.com/

**Comment by jbleyel** [comment]
Pfeile - done with the last commit.
Die Buttons lass ich so.
