### ISSUE TITLE
small settings flaw

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#566]
enable http auth
then disable https auth
then disable https

-> you will see the problem

**Comment by Schimmelreiter** [comment]
Du meinst, daß der "Ohne Authentifizierung ist nur lokaler Zugriff möglich"- und "Auch Zugriff aus VPNs erlauben"-Kram stehenbleibt, obwohl die Authentifizierung an ist?

**Comment by jbleyel** [comment]
JA, http auth ist ON, https auth is OFF aber https ist komplett OFF.

**Comment by Schimmelreiter** [comment]
Beheb ich.
Ist ja nur ein De Morgan'scher Fehler :)

**Comment by jbleyel** [comment]
deshalb -> flaw :D

**Comment by Schimmelreiter** [comment]
Fixed by https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/c4cded2cb90d35066c222d5cb75906e89a2a91f4
