### ISSUE TITLE
OpenWebif Logo 

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#570]
Please, Vote against the empty space ;-) 

![vorher](https://cloud.githubusercontent.com/assets/17575778/22614909/e70166e0-ea89-11e6-9e37-a010bf02f6d4.png)
![bsp](https://cloud.githubusercontent.com/assets/17575778/22614910/f20106cc-ea89-11e6-908d-e51e62c2eec9.png)

[http://www.opena.tv/sonstiges/28610-themed-openwebif-remotes-duo-solo-solo-4k-ow_remote-post281374.html#post281374](url)

**Comment by jbleyel** [comment]
Hi @sgse : versteh ich nicht.
Und .. Keine gute Idee.

<img width="785" alt="bildschirmfoto 2017-02-04 um 22 04 49" src="https://cloud.githubusercontent.com/assets/964927/22621525/0a64a3c6-eb26-11e6-88f5-0dd5555e39aa.png">

Such dir mal eine Sendung mit längerem Text und dann wirst merken was ich meine.

Der ganze Header gehört komplett umgebaut (html,css). 
Dann ist das Thema vermutlich sowieso erledigt.

**Comment by sgse** [comment]
Wollte eigentlich nur das Logo ins Spiel bringen ;) , als ich alles hochgeladen hatte ist mir auch eingefallen das es z.B. am Tablet nicht praktikabel ist.
Ein Logo hat OpenWebif aber noch nicht, oder? ;)
Ich mach dann hier zu.

**Comment by jbleyel** [comment]
Das Logo ansich ist kein Problem.
Der komplette Header sollte jedoch eine Frischzellenkur bekommen.
Dann hat sich auch der leere Raum erledigt.

z.B. könnte man die Höhe verkleinern, wenn das Fenster breiter ist.
Das Stichwort ist Responsive Design.

Auch der Rest der Seite ist bei kleinerem oder sehr grossem Browserfenster nicht optimal.

**Comment by sgse** [comment]
Wieder was dazu gelernt, danke.
CSS3  Media Queries,   HTML5. 
Ich habe mir immer alles mit "Selfhtml" zusammen gebastelt, ist gefühlte 50 Jahre her ;)

**Comment by Schimmelreiter** [comment]
Mit den zusätzlichen Möglichkeiten, die das OWIF inzwischen hat, wäre ein Logout-Button auch nicht verkehrt.

**Comment by jbleyel** [comment]
Was soll bei dem Logout genau passieren?
Wir haben doch keine "richtige" aktive Session, ausser beim Terminal.

**Comment by Schimmelreiter** [comment]
Ich meine schon ...
Bei logout müßte OWIF den key "logged" vergessen.

**Comment by thawtes** [comment]
hi, friends. i'm front-end coder...
I think I will soon re-code the owif html+css. new code HTML+CSS3.
a person can integrate the template :)   (I can do it if I have time)
I hope it will be a nice and fun work.
I will share it with you when finished.
Goodbye to see you soon ...

**Comment by sgse** [comment]
I'm waiting here ;-) and I'm really looking forward to testing it :-)

**Comment by sgse** [comment]
Lange nicht gesehen und doch gefunden :-)

![openwebifhd](https://cloud.githubusercontent.com/assets/17575778/22652324/4cf2bdde-ec86-11e6-8f15-0beb9d032869.png)
![rect7795](https://cloud.githubusercontent.com/assets/17575778/22654266/8c9d86c0-ec8c-11e6-8c83-3d2ccb37ddbc.png)

**Comment by sgse** [comment]
@thawtes Can you please define for me your "soon"? ;-)

@Schimmelreiter Wenn ich angemeldet bin und den Browser schließe kommt die Meldung ob ich die Seite verlassen möchte. Mit dem Button spart man sich dann das "exit" im Terminal oder die blöde Abfrage, richtig? 
Nice to have :-D

Ich schließe hier mal weil das Logo obsolet ist, der "Button" und "Responsive Design" bräuchten ihr eigenes issue.

**Comment by thawtes** [comment]
I'll start coding at a reasonable time after I have finished my work.
