### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Martyin** [E2OpenPlugins/e2openplugin-OpenWebif#572]
Dear readrs, 

Is it possible to make the current sattelite info, displayed when you look (click) at the box info link on the left in the menu, also visable in the top of the window , when you click Television on the left in the menu, then "current" on the top, shows only the current channel name.
It would be nice if you also could see the current sat on witch the current channel resides...
I believe it is the same info that comes from the tuner info displayed when the correct class is used. That gives for example 
							"2" class="ui-widget-header">Tuners
							<td class="infoleft" style="vertical-align:text-top;">Tuner A</td>
							<td class="inforight">
								AVL6211 (DVB-S2)
										<div class="tled-box"><div class="tled green"></div></div>19.2° E / MTV Dance<br>
							
							
Thank you.

Martyin

**Comment by jbleyel** [comment]
It's there already -> Orbital Position: 192
