### ISSUE TITLE
disable root user access

### ISSUE THREAD

**Issue by daveraver** [E2OpenPlugins/e2openplugin-OpenWebif#577]
I put yes on disable root access and it doesnt work. this option disable root user acces or disable root access?? I can acces with root and other username, when the option disable root acces is on 'yes'. Has anybody test it??? thank you.

**Comment by Schimmelreiter** [comment]
Local and private networks are exempt from this rule.
This is due to many E2 tools on the PC not being able to handle different logins for telnet, ftp and web.
So locally, root can still login to OWIF.

**Comment by daveraver** [comment]
I am streaming to external network. thank you.

**Comment by Schimmelreiter** [comment]
A change introduced by PLi snatched the streaming auth away from OWIF, so OWIF can not control access to streaming on images that merged those changes and can not revert them.
