### ISSUE TITLE
Pass-Through IPTV Streams

### ISSUE THREAD

**Issue by Lostish** [E2OpenPlugins/e2openplugin-OpenWebif#578]
I want to add feature like TV Headend passing through IPTV streams.
The stream works via HDMI direct connected box.
But i want it to work so i can restream to a remote connected device like kodi/tv/dreamdroid app
So the exported IPTV bouquet in m3u format is working remote

For selected ACTIVE channel, works like a charm.
In open webif if i click on stream when having a real DVB channel the stream link is,
http://192.168.1.10/web/stream.m3u?ref=1:0:19:ED9:45:46:E080000:0:0:0:&name=SVT1%20HD

On a IPTV stream with service id 4097 the link url is
http://192.168.1.10/web/ts.m3u?file=
The original url for the ip tv looks something like this,
http://ipsatpro.info:8000/live/user/password/1118.ts

So if i export the IPTV 
The exported m3u file does not work, wit links like this.
http://192.168.1.10:8001/4097:0:1:0:0:0:0:0:0:0:http%3a//ipsatpro.info%3a8000/live/user/password/1118.ts

It works when i Zap to the IPTV channel i can watch the output via HDMI
None works when i want to stream the content via exported m3u or live stream. /web/stream.m3u
( as the web/stream.m3u does not add the 4097 service )

So i would like a feature or a correction to get the IPTV stream to work via webif.
Preferably with m3u, i dont want to have the stream "actively" displaying on the DVB setbox ( /web/stream.m3u )
So the stream would look something like this but for the external IPTV stream, but working.
http://192.168.1.10:8001/4097:0:1:0:0:0:0:0:0:0:http%3a//ipsatpro.info%3a8000/live/user/password/1118.ts

Thanks

**Comment by jbleyel** [comment]
This should not be a problem but only for free streams without any authentication methods.
