### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by spaJR** [E2OpenPlugins/e2openplugin-OpenWebif#579]
Can change this at es.po?

#: plugin/local.py:148 plugin/plugin.py:123
msgid "Custom box name"
msgstr "Nombre personaliza del deco"

by this?
#: plugin/local.py:148 plugin/plugin.py:123
msgid "Custom box name"
msgstr "Nombre personalizado del deco"

**Comment by Schimmelreiter** [comment]
Sure, but please also provide the new translation for this changed string:
```
 #: plugin/plugin.py:133
 -msgid "Disable access for user root"
 +msgid "Disable remote access for user root"
```

Note the newly added "remote"!

**Comment by Schimmelreiter** [comment]
PS:
You can as well edit the translation file yourself, just as if you had write access, and create a pull request in the end.
I will merge in no time :)

**Comment by spaJR** [comment]
#: plugin/plugin.py:133
 -msgid "Disable access for user root"
 +msgid "Deshabilitar acceso remoto para el usuario root"

**Comment by spaJR** [comment]
I'm seeing a lot of msgid without translation. I look at it and try to edit.

**Comment by Schimmelreiter** [comment]
Wait a moment, I'll apply the two changes ...

**Comment by Schimmelreiter** [comment]
You can start now :)

**Comment by jbleyel** [comment]
Please use POEdit and make a pull. Thanks
