### ISSUE TITLE
Autotimer: Unable to add new one if title contains & sign

### ISSUE THREAD

**Issue by martinr92** [E2OpenPlugins/e2openplugin-OpenWebif#581]
I'm unable to add a new autotimer, if the title of the show contains a "&" sign.

The following message in the JavaScript console appears:
`Uncaught Error: Invalid XML: <timers><timer name="Schulz & Böhmermann" match="Schulz & Böhmermann" enabled="yes" id="6" from="23:15" to="00:15" searchType="exact" searchCase="sensitive" justplay="0" overrideAlternatives="1" ><e2service><e2servicereference>1:0:19:2B7A:2719:F001:FFFF0000:0:0:0:</e2servicereference><e2servicename>zdf_neo HD</e2servicename></e2service></timer></timers>
    at Function.error (jquery.min.js:2)
    at Function.n.parseXML (jquery.min.js:4)
    at addAT (eval at <anonymous> (jquery.min.js:2), <anonymous>:12:11634)
    at Parse (eval at <anonymous> (jquery.min.js:2), <anonymous>:12:7386)
    at Object.success (eval at <anonymous> (jquery.min.js:2), <anonymous>:12:12480)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at y (jquery.min.js:4)
    at XMLHttpRequest.c (jquery.min.js:4)`

The generated XML at 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/ef2227bc751f601a86a9f12a3f3ed74416f2ecc5/sourcefiles/js/at.js#L706
is invalid. There needs to be some kind of escaping for the variable "evt.name".

**Comment by Schimmelreiter** [comment]
The & character is not XML safe, as it starts a special character.
E.g. ä becomes &auml; ö becomes &ouml; and so on.
The & itself has to be written as &amp; inside XML.

**Comment by jbleyel** [comment]
The xml needs to looks like this:

`<timer name="TEST &amp; äöü" match="TEST &amp; äöü" enabled="no" id="12" encoding="UTF-8" overrideAlternatives="1"></timer>
`

Your autotimer plugin needs to fix.
I'ts not openwebif releated.

**Comment by martinr92** [comment]
@jbleyel You're right. & -> &amp;
But the XML is created by the at.js in this repository. So why is this an issue of the autotimer plugin?

**Comment by jbleyel** [comment]
No, your are totaly wrong.
The xml is the /etc/enigma2/autotimer.xml on your box.
And this file will only be read and written by the autotimer plugin.

**Comment by martinr92** [comment]
Ok, seems there is a misunderstanding. I'm not talking about already created autotimer. I'm takling about creating a new autotimer using the EPG.
![image](https://cloud.githubusercontent.com/assets/658036/23473523/cc42d556-feb0-11e6-85aa-a501e73216a4.png)
![image](https://cloud.githubusercontent.com/assets/658036/23473529/d1ef8e40-feb0-11e6-8c38-d3da1f669956.png)

**Comment by jbleyel** [comment]
Kommando zurück.
Bitte mal den Autotimer nicht über EPG sondern über Extras / Autotimer anlegen.

**Comment by jbleyel** [comment]
Der Fehler scheint in der EPG Detailansicht zu sein und nicht in at.js.
Da müsste man den Titel encoden.

**Comment by Schimmelreiter** [comment]
Gut, daß Du Dich freiwillig meldest! :+1:

**Comment by jbleyel** [comment]
Wieso immer ich???

**Comment by sgse** [comment]
Du bist der einzige hier, der das kann :)

**Comment by jbleyel** [comment]
So ein Quatsch. ;-)

**Comment by Schimmelreiter** [comment]
Ich hab grad Null Zeit :)

**Comment by jbleyel** [comment]
Immer diese Ausreden. *lach* 
Ich schau mir das an, wenn ich Zeit habe.
