### ISSUE TITLE
Make ports non-configurable

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#582]
I think about removing the settings for changing the default ports from 80 and 443 to something else.

Why?
Because there is no good reason to do so.

Non-standard-ports just make access to the OWIF prone to misconfiguration and it encourages the use of port-forwarding.

The only reasons for making ports selectable are
- to get outside (WAN) and inside (LAN) ports in sync
- to create the false feel of security due to not using default ports

See https://www.shodan.io/search?query=200+OK+open+webif for a proof that continued claims that non-default ports are of **any** value are just false. That search will always return a nice number of (older) OWIFs wide open to the net and 99.9% of them will be on non-standard ports.

On the other hand it breaks potential **useful** features, because a new box B can not rely on an existing box A being reachable on the default port(s).

**Comment by jbleyel** [comment]
I see no problems if the DMM webif plugin is not installed.
But you should only make the setting readonly inside the openwebif setup screen.
Do not remove the setting variable.
