### ISSUE TITLE
New option ipk installer

### ISSUE THREAD

**Issue by Dima73** [E2OpenPlugins/e2openplugin-OpenWebif#586]
Who can create such an option?

**Comment by jbleyel** [comment]
What do you mean with ipk installer?

**Comment by Dima73** [comment]
Open OpenWebif and add / install ipk of  PC.

**Comment by jbleyel** [comment]
already there.
<img width="594" alt="bildschirmfoto 2017-03-12 um 15 38 11" src="https://cloud.githubusercontent.com/assets/964927/23832682/fe20ba20-0739-11e7-9f26-bd0f98b7b26b.png">
