### ISSUE TITLE
services.m3u structure

### ISSUE THREAD

**Issue by estimadarocha** [E2OpenPlugins/e2openplugin-OpenWebif#587]
This is not really an issue, or maybe it is i don't know yet...

i am using authentication on streams, so i want to insert user:password directly on services.m3u

i tried to use user:pass@ip:port/.... and also ip:port/user/pass/... and nothing

Other problem i have is when i try to import services.m3u on tvheadend as source for iptv each channel transforms in multiple ones (23 to be precise) anyone ever tried this?

**Comment by jbleyel** [comment]
The stream auth in services.m3u should be working now.
The format for tvheadend can also be changed, but i need an example.

**Comment by estimadarocha** [comment]
@jbleyel witch of these work?

user:pass@ip:port/....
or
ip:port/user/pass/...
???

**Comment by estimadarocha** [comment]
@jbleyel 

i downloaded a services.m3u and edited it so there's only a channel on it to be easier:

it look's like this:

#EXTM3U 
#EXTVLCOPT--http-reconnect=true
#EXTINF:-1,RTP 1
#EXTVLCOPT:program=811
http://192.168.1.106:8001/1:0:1:32B:24:36:FFFF0000:0:0:0:

if i import that m3u on tvheadend it turns that single channel in these:

http://prntscr.com/fa01wo

any idea why that happens?

**Comment by jbleyel** [comment]
If services.m3u has only one EXTINF entry then you should have only one channel in tvheadend.
The syntax look also correct.
I have no idea whats happened here.
You should ask someone of the tvheadend team

**Comment by jbleyel** [comment]
user:pass@ip:port/....

**Comment by estimadarocha** [comment]
@jbleyel

The problem it's on the services.m3u... allready tried the tvheadend and after some debug... and playing the file on vlc if I go to codec tab each channel it's composed by a lot transmissions and not only the channel streaming... in the case of the picture going to codec tab there's 17 transmissions and just one it's the video streaming... is it possible to eliminate this?

**Comment by jbleyel** [comment]
I don't know how? I need a working example file with minimum 2 channels.

**Comment by jbleyel** [comment]
Please check this .. https://github.com/Bronkoknorb/a1tv-helpers
I think this will help you

**Comment by estimadarocha** [comment]
@jbleyel the problem it's not in tvheadend importing.... thats easy to do with automatic iptv network...

the problem is somehow enigma passe not only the video transport stream but a lot more things.

see the example:

http://192.168.1.106:8001/1:0:1:32B:24:36:FFFF0000:0:0:0:

inside that transport stream theres 17 transmissions and only one is the real stream

if you see in this picture:

http://prntscr.com/fanqm3

only the signaled it's usefull...

**Comment by jbleyel** [comment]
I have installed tvheadend but i'm not able to import a network.
I have no TV adapter.

Can you tell me step by step how to import a channel or list.
I will try this exacly as you do.
