### ISSUE TITLE
AutoTimers not being saved to disk

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#591]
When AutoTimers are managed via OpenWebif the in memory data structures are correctly created and updated.  The problem is that these changes to the data are not save to disk regularly.  If the unit crashes or the user removes power *without* a proper shutdown then AutoTimers created by OpenWebif can be lost.

This request asks that AutoTimers be written to disk more often by OpenWebif.

A current workaround is to execute a shut down to save the data (not very convenient).  Alternatively manipulate an AutoTimer using the GUI and then save the changes (again not very user friendly).

**Comment by prl001** [comment]
It may also be useful for the PVR-end Open Webif code to save timers.xml and bouquets files when they are changed in Open Webif, if that doesn't happen already.

autotimers.xml can also be updated just by opening the AutoTimers list screen and pressing GREEN Save, which is simpler that the methods Ian suggests, but it shouldn't be necessary.

**Comment by jbleyel** [comment]
Auto Save of Autotimer is a very bad idea.
The Autotimer Plugin do some more things if you call save.

There is only one option:
Save the actual AT in browser and remove this after succesfully save.
And then show this AT If you open the Autotimer again and your box is back.

**Comment by IanSav** [comment]
Can you please explain the problem with saving AutoTimers if they are changed via OpenWebif.

I don't understand the option suggested.

**Comment by jbleyel** [comment]
It makes no sense to save an timer before u are finished.
You have also no chance to cancel.
As i understand, you will save the current autotimer from time to time (e.g. every 5 min.).
This can kill your box, trust me.

The openwebif use only the autotimer plugin api and do not write the autotimer.xml.
You can take a look to the autotimer plugin and try to find a way to write the xml on each change.
https://github.com/oe-alliance/enigma2-plugins/blob/2.3/autotimer/src/AutoTimerResource.py

I will close this and you can open this issue for the autotimer plugin.
