### ISSUE TITLE
API for removelocation should have an option to delete the folder.

### ISSUE THREAD

**Issue by jongleur1983** [E2OpenPlugins/e2openplugin-OpenWebif#593]
Hi.
When adding a location using the API /api/addlocation?dirname={dirname}&createFolder={createFolder} it's possible to create the folder that should be added as a new location.
Unfortunately I did not find a way to "revert" that call via the API when the folder was created.

The location can be removed from the locations-list by web/removelocation?dirname={dirname}, but the directory is kept in the file system.

Do I miss anything (I saw that addlocation is in /api/ while removelocation is in /web/, so I might)?
If yes: How can I do that?
If no: Would it be possible to add a deleteFolder-parameter to removelocation?

Unfortunately I'm not a python programmer, so I could try to add it myself to the code, but I don't want to without at least a proper review. On the other hand I would be happy for any feedback (or for the implementation itself of course).

kind regards
Peter

**Comment by jbleyel** [comment]
Hi Peter,

i can do this, but i will only remove the folder if the folder is empty.

**Comment by jongleur1983** [comment]
Hi,
that sounds perfectly reasonable. Thanks.
Unfortunately I'm not sure if that's sufficient.

One questions that come to mind is: What if there is an existing recording timer that is scheduled to store in the given location? This isn't a new question rising with deleting the folder, as a missing location entry might still be a problem already (not sure, didn't test).

Anyway: thanks for the fast response.

Peter
