### ISSUE TITLE
openwebif

### ISSUE THREAD

**Issue by jamesb16** [E2OpenPlugins/e2openplugin-OpenWebif#594]
WHY NOT JUST MAKE A FUCKING IPK THAT CAN BE ADDED, FUCKING PILE OF SHITE

**Comment by sgse** [comment]
Two things are infinite, the universe and human stupidity. With your stupidity, I am sure the infinity is still too small.

**Comment by jamesb16** [comment]
No probs mongo baws

**Comment by jbleyel** [comment]
Please use the plugin from your image feed.
Ask your image provider if this feed is too old or use the build_ipk.sh if your image provider don't have openwebif.
The IPK is a full blown package with all boxes we don't do any brandings here.
