### ISSUE TITLE
Is it possible to mock/simulate a box with openwebif independent of existing hardware?

### ISSUE THREAD

**Issue by jongleur1983** [E2OpenPlugins/e2openplugin-OpenWebif#602]
I'm trying to write software that should access my (or others, if anyone will be interested) tv receiver using the openWebIf API via HTTP.
For writing unit tests it would be great to be able to not depend on the running box hardware usually, but to have a running API independently.

Is it possible to run the openwebif plugin somehow in a way that could provide the API with reasonable (even though not live) data?

**Comment by jbleyel** [comment]
Possible YES. Useable NO.
You can use a simple website and simulate all requests as page.
To get live data you need to run on a enigma2 box.
