### ISSUE TITLE
grabing when is box controlled with virtual RC

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#603]
long time ago (years) I solved problem with grabbing, if is used remote controller quickly. All worked well.

Now, If I am trying f.eg:  Menu-5-1-3, I get as final screen selector on item "3" in submenu, but not screen, where is opened this item - for this I must  use Refresh button. 

Very stupid ... thanks for this "improvement"

**Comment by Schimmelreiter** [comment]
This issue arose when menus started to support two-digit shortcuts.
The menu handler now waits for a given time for a second key press and the screenshot gets done during that timeout period and thus exactly one step before your last key press.

**Comment by ims21** [comment]
hmm .. 5-1-3 ??? Waiting for next digit ? F.eg. 30 items in menu ?

1) I think, waiting will be actual after digit "1" only... did not saw more than 20 items on one screen

2) Btw ... lets wait, but max. 1s and after this time lets make grab... =>always will be actual status

**Comment by Schimmelreiter** [comment]
?
You mean the JavaScript code is compressed?

The non-uglified version is under https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/master/sourcefiles

Yes, a small waiting time was exactly what I was thinking about too.

**Comment by ims21** [comment]
One way is increase delay from 1000 to 2000ms ... It is not comfortable for user
or increased it for 0-9 only
```
	if (code > 1 && code < 12) {
		grabTimer = setTimeout("callScreenShot()", 2000);
	} else {
		grabTimer = setTimeout("callScreenShot()", 1000);
	}
```

But more smart twodigit routine in e2 will be good too ...
