### ISSUE TITLE
Wish: improve package administration

### ISSUE THREAD

**Issue by edelknecht** [E2OpenPlugins/e2openplugin-OpenWebif#608]
Dear OpenWebif dev team, thank you for your great work. I have one wish. Please improve OpenWebif package administartion to be more like webadmin in old webinterface. 

In order to make you understand what I mean have a look at the following video.

https://www.dropbox.com/s/yrx25oldslll8kc/Ashampoo_Snap_Dienstag%2C%2023.%20Mai%202017_10h04m20s_004_.wmv?dl=0

One big and from my point of view the biggest advantage of webadmin is that the user is able to directly filter and search via an input field.  Having to sort alphabetically is not as effective, specially for novice users that dont know package names. 

One more cool feature is that the user can upload and install a package directly. I use this to install stuff for all boxes I administrate via vpn for my family.  

Aditionally I would like to be able to directly filter and instal & uninstall  via + (=  install) / - (= uninstall) 

Use cases I would like to think about...

Seach skin in input field and install skin of choice from skins listed via +... gui reboot etc is automatically offered and list is refreshed. 

Search epg in input and uninstall eg. epgsearch via - button

Users uses update package function and sees update details 

Users uses upgrade all packages function and sees what happends
List installed
List upgradeable
List all skins via entering skins in input field
List all extensions , see above
List all system extensions, see above
List all picon packages, see above
Upload & install & show installation details

Thank you!

[WebAdmin.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/1021467/WebAdmin.zip)

**Comment by jbleyel** [comment]
Do you have check this?

<img width="891" alt="bildschirmfoto 2017-05-23 um 17 15 37" src="https://cloud.githubusercontent.com/assets/964927/26361509/85c6b5d6-3fdb-11e7-8fc6-51be07d6b4f7.png">

**Comment by sgse** [comment]
Hi Tim :-)
Gibt es Probleme bei Parallelinstallation von OWIF (Port 80) und WebAdmin (Port 81)? 
@jbleyel 
OT: Bei mir geht WebTV nicht mehr, kann aber auch an Mint/FF liegen ;-)

**Comment by jbleyel** [comment]
@sgse : WebTV .. kann eigentlich nicht sein.
WebAdmin braucht das DMM Webif und das ist auf vielen Boxen nicht drauf.
Das braucht auch keiner, wenn openwebif drauf ist.

Ausser "Scripts" ist alles aus dem Webadmin im openwebif drin.
Natürlich kann man da evtl. noch was verbessern.

**Comment by sgse** [comment]
Er meint ja wohl auch die Suche :-) OWIF ist unter "E" , das weiß der normal sterbliche nicht. Die sollten aber, so wie ich ich :-D , da nicht rum spielen ;-) .

**Comment by jbleyel** [comment]
Hi @edelknecht, bitte testen.

**Comment by sgse** [comment]
Runter geladen, installiert und Terminal sagt mit schwarzer Schrift auf schwarzem Hintergrund:
![pakete3](https://cloud.githubusercontent.com/assets/17575778/26375292/a49dde44-4008-11e7-8462-0d86fe262672.png)
Per Terminal geht es.
Die Umgebung von packages sieht aus wie bisher. Browser cache hatte ich gelöscht.

**Comment by jbleyel** [comment]
Hä? Terminal ist nicht geändert worden. Ich hab nur die Packages geändert.
Du hat wohl ein Problem mit shellinabox.

**Comment by sgse** [comment]
Die Zeichenkodierung eines Dokuments im Frame wurde nicht deklariert. Das Dokument kann unterschiedlich aussehen, wenn es ohne das umgebende Frame-Dokument angesehen wird.

**Comment by jbleyel** [comment]
"Could not connect" kommt dann, wenn shellinabox nicht funktioniert.
ps -aux | grep 'shellinabox'
netstat -p | grep 'shellinabox'

**Comment by jbleyel** [comment]
Es kann aber auch sein, das der ReverseProxy nicht geht.
Da wurde aber nix geändert.

**Comment by sgse** [comment]
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/  jquery.min.js:4:26272
`root@vuduo2:~# ps -aux | grep 'shellinabox'
nobody     686  0.0  0.1   4940  1644 ?        Ss   22:29   0:00 /usr/bin/shellinaboxd --cert /etc/shellinabox -q --background=/var/run/shellinaboxd.pid -p 4200 --user-css Normal:+/etc/shellinabox/vti.css
nobody     687  0.0  0.0   4940   984 ?        S    22:29   0:00 /usr/bin/shellinaboxd --cert /etc/shellinabox -q --background=/var/run/shellinaboxd.pid -p 4200 --user-css Normal:+/etc/shellinabox/vti.css
root      1933  0.0  0.0   2668   596 pts/0    S+   23:03   0:00 grep shellinabox
root@vuduo2:~# netstat -p | grep 'shellinabox'
unix  3      [ ]         STREAM     CONNECTED       1717 686/shellinaboxd    
unix  3      [ ]         STREAM     CONNECTED       1718 687/shellinaboxd    `

**Comment by jbleyel** [comment]
XMLHttpRequests hat nix damit zu tun.
Du hast da wohl ein anderes Problem.
Wenn http://IP/terminal nicht geht, dann geht entweder shellinabox nicht oder der ReverseProxy.
Und letzteres wurde nicht geändert.

**Comment by jbleyel** [comment]
Lösche mal das openwebif und installiere es neu.

**Comment by sgse** [comment]
Box Neustart, Terminal aufgemacht, hatte noch F12 offen im FF: Meldung
Die Zeichenkodierung eines Dokuments im Frame wurde nicht deklariert. Das Dokument kann unterschiedlich aussehen, wenn es ohne das umgebende Frame-Dokument angesehen wird.

OK mache ich.

**Comment by jbleyel** [comment]
Wenn packages gleich aussieht, dann hast du wieder vergessen die compilierten templates zu löschen.

**Comment by sgse** [comment]
Habe ich schon mal templates gelöscht? ;-)
Was für templates und wo???

**Comment by sgse** [comment]
Das ist jetzt noch drauf, gleich nicht mehr.
`root@vuduo2:~# opkg list | grep openwebif
enigma2-plugin-extensions-openwebif - 1.1.0-e2openpluginsgit20161212-r2-2345+ca51c46 - enigma2-plugin-extensions-openwebif version 1.1.0-e2openpluginsgit20161212-r2-2345+ca51c46
enigma2-plugin-extensions-openwebif - 1.2.0-e2openpluginsgit-r0
enigma2-plugin-extensions-openwebif-theme - 1.0.0-e2openpluginsgit20161123-r0-2244+e6c4361 - enigma2-plugin-extensions-openwebif-theme version 1.0.0-e2openpluginsgit20161123-r0-2244+e6c4361
`

**Comment by sgse** [comment]
Wenn ich hier https://github.com/E2OpenPlugins/e2openplugin-OpenWebif.git den download mache,
ist doch alles enthalten, oder? 
Also auch das
 e2openplugin-OpenWebif/plugin/controllers/views/ajax/settings.tmpl

Ich habe jetzt zweimal alles frisch installiert, keine Änderung.

**Comment by sgse** [comment]
So sieht die in meiner ipk aus, nicht identisch.
usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/

Wird sehr lang wenn ich die hier anfüge.
`#from Plugins.Extensions.OpenWebif.local import tstrings
<style>
/* TODO Theme Support */

.listNav,.ln-letters {overflow:hidden;}
.listNavHide {display: none;}
.listNavShow {display: list-item;}

.ln-letters a { font-size:0.9em;display:block;float:left;padding:2px 6px;border:1px solid silver;border-right:none;text-decoration:none;}
.ln-letters .ln-last { border-right: 1px solid silver;}
.ln-letters a:hover,.ln-selected { background-color:#eaeaea;}
.ln-letters .ln-disabled {color:#ccc;}
#packagelist li.installed {font-weight:bold;}

**Comment by sgse** [comment]
Wenn ich das austausche geht es zwar nicht aber es sieht dann so aus.
![pakete5](https://cloud.githubusercontent.com/assets/17575778/26378493/093999c2-4015-11e7-985d-ba623bda2ba1.png)
Ich gebe fast auf. :-)
Ich schau mal was jetzt ein Neustart bringt, wahrscheinlich muss ich mehr austauschen bei meinem Glück.

**Comment by sgse** [comment]
Schade, "GET /grab?format=jpg&mode=all HTTP/1.1" geht auch nicht mehr "500".
Entweder ich warte auf ein update von VTi oder wechsele auf openATV :-)

**Comment by jbleyel** [comment]
Das ganze klingt dann nach einem Problem mit python twisted von VTi.
Ist aber nur ein Verdacht.
Ich hab OpenATV und bei mit funktioniert alles perfekt.

Obwohl ich immer noch nicht verstehe wieso es vorher ging.

**Comment by jbleyel** [comment]
Hi @sgse , mach mal ein terminal auf.
Dann gehe nach /usr/lib/python2.7/site-packages/twisted/
Dort dann folgendes:
python<ENTER>
import twisted<ENTER>
print twisted.version<ENTER>
ctrl+d

Ich brauche die Versionsnummer.

**Comment by sgse** [comment]
Evtl. an der alten IPK vom Dez.2016? Hatte dieses, deines mache ich gleich :-)

`root@vuduo2:~# opkg list-installed | grep python
enigma2-python - vti-11.0.1-20170410-r0r2
libpython2.7-1.0 - 2.7.9-r1-vuplus1
python-argparse - 2.7.9-r1-vuplus1
python-attrs - 16.2.0-r0
python-audio - 2.7.9-r1-vuplus1
python-cffi - 1.4.1-r0
python-cfscrape - 1.6.6+git0+5da4af148f-r0.1
python-cheetah - 2.4.4-r3
python-codecs - 2.7.9-r1-vuplus1
python-compression - 2.7.9-r1-vuplus1
python-constantly - 15.1.0-r0
python-contextlib - 2.7.9-r1-vuplus1
python-core - 2.7.9-r1-vuplus1
python-crypt - 2.7.9-r1-vuplus1
python-cryptography - 1.5.2-r0
python-ctypes - 2.7.9-r1-vuplus1
python-datetime - 2.7.9-r1-vuplus1
python-difflib - 2.7.9-r1-vuplus1
python-distribute - 0.6.32-ml5
python-distutils - 2.7.9-r1-vuplus1
python-elementtree - 2.7.9-r1-vuplus1
python-email - 2.7.9-r1-vuplus1
python-enum34 - 1.0.4-r0
python-fcntl - 2.7.9-r1-vuplus1
python-html - 2.7.9-r1-vuplus1
python-idna - 2.2-r0
python-image - 2.7.9-r1-vuplus1
python-imaging - 1.1.7-r5
python-incremental - 16.10.0-r0
python-io - 2.7.9-r1-vuplus1
python-ipaddress - 1.0.17-r0
python-js2py - 0.39+git0+144b1701fa-r1.1
python-json - 2.7.9-r1-vuplus1
python-lang - 2.7.9-r1-vuplus1
python-logging - 2.7.9-r1-vuplus1
python-math - 2.7.9-r1-vuplus1
python-mechanize - 0.2.5-r2
python-mime - 2.7.9-r1-vuplus1
python-misc - 2.7.9-r1-vuplus1
python-mutagen - 1.18-r3
python-netclient - 2.7.9-r1-vuplus1
python-netserver - 2.7.9-r1-vuplus1
python-numbers - 2.7.9-r1-vuplus1
python-pickle - 2.7.9-r1-vuplus1
python-pkgutil - 2.7.9-r1-vuplus1
python-pprint - 2.7.9-r1-vuplus1
python-pyasn1 - 0.1.9-r0
python-pyasn1-modules - 0.0.8-r0
python-pycparser - 2.14-r0
python-pycrypto - 2.5-r2
python-pyopenssl - 1:16.1.0-r0.vti01
python-pyusb - 1.0.0a2-r1
python-re - 2.7.9-r1-vuplus1
python-readline - 2.7.9-r1-vuplus1
python-requests - 2.12.4-r0
python-robotparser - 2.7.9-r1-vuplus1
python-service-identity - 16.0.0-r0.vti01
python-shell - 2.7.9-r1-vuplus1
python-simplejson - 2.2.1-r1
python-six - 1.9.0-r0
python-sqlite3 - 2.7.9-r1-vuplus1
python-stringold - 2.7.9-r1-vuplus1
python-subprocess - 2.7.9-r1-vuplus1
python-textutils - 2.7.9-r1-vuplus1
python-threading - 2.7.9-r1-vuplus1
python-twisted-core - 16.2.0-r0.vti04
python-twisted-protocols - 16.2.0-r0.vti04
python-twisted-web - 16.2.0-r0.vti04
python-ultrajson - git-r02015-04-09-vti001
python-unixadmin - 2.7.9-r1-vuplus1
python-wifi - 0.5.0-r2
python-xml - 2.7.9-r1-vuplus1
python-zlib - 2.7.9-r1-vuplus1
python-zopeinterface - 4.1.1-r0
`

**Comment by jbleyel** [comment]
Hast du ein aktuelles VTI Image?

**Comment by sgse** [comment]
[twisted, version 16.0.0]
ja 11.0.1

**Comment by jbleyel** [comment]
Version sieht gut aus.
Das Screenshot Problem hab ich glaube ich gefunden.
Das liegt an der enigma2 version die du hast.
Tausche mal diese Datei im openwebif aus.
Du musst aber vorher das .txt weg machen.
 
[grab.py.txt](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/1026402/grab.py.txt)

**Comment by sgse** [comment]
Hat leider nicht geholfen. 
self.container.stdoutAvail.append(request.write)
#self.container.setBufferSize(32768)

**Comment by sgse** [comment]
Habe was entdeckt ;-)
`'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  jquery-ui.min.css:6:759
Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert.  jquery-ui.min.css:6:3356
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  jquery-ui.min.css:6:12272
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  jquery-ui.min.css:6:18546
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  jquery-ui.min.css:6:18693
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  jquery-ui.min.css:6:19150
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  vader.css:1:3221
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  vader.css:1:3368
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  vader.css:1:3443
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  vader.css:1:3878
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert.  style.min.css:1:180
Unbekannte Eigenschaft '-moz-outline-style'.  Deklaration ignoriert.  style.min.css:1:4169
Unbekannte Eigenschaft '-moz-border-radius'.  Deklaration ignoriert.  style.min.css:1:4195
Ende des Werts erwartet, aber '5' gefunden.  Fehler beim Verarbeiten des Wertes für 'margin'.  Deklaration ignoriert.  style.min.css:1:11229
Ende des Werts erwartet, aber '10' gefunden.  Fehler beim Verarbeiten des Wertes für 'margin'.  Deklaration ignoriert.  style.min.css:1:11283
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert.  style.min.css:1:12551
Unbekannte Eigenschaft 'zoom'.  Deklaration ignoriert.  192.168.178.21
Fehler beim Verarbeiten des Wertes für 'margin'.  Deklaration ignoriert.  192.168.178.21
Unbekannte Eigenschaft 'zoom'.  Deklaration ignoriert.  chosen.min.css:2:98
Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert.  chosen.min.css:2:159
Fehler beim Verarbeiten des Wertes für 'background'.  Deklaration ignoriert.  chosen.min.css:2:997
Farbe erwartet, aber 'top' gefunden.  Fehler beim Verarbeiten des Wertes für 'background'.  Deklaration ignoriert.  chosen.min.css:2:1091
Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert.  chosen.min.css:2:3634
Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert.  chosen.min.css:2:4572
Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert.  chosen.min.css:2:5703
Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert.  chosen.min.css:2:6789
Farbe erwartet, aber 'top' gefunden.  Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert.  chosen.min.css:2:6892
Unbekannte Eigenschaft '-moz-border-radius-bottomright'.  Deklaration ignoriert.  chosen.min.css:2:7517
Unbekannte Eigenschaft '-moz-border-radius-bottomleft'.  Deklaration ignoriert.  chosen.min.css:2:7578
Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert.  chosen.min.css:2:7842
Name einer Medienfunktion erwartet, aber '-webkit-min-device-pixel-ratio' gefunden.  chosen.min.css:2:9843
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-full-screen'.  Regelsatz wegen ungültigem Selektor ignoriert.  vxgplayer-1.8.21.min.css:1:180
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-full-screen'.  Regelsatz wegen ungültigem Selektor ignoriert.  vxgplayer-1.8.21.min.css:1:648
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-full-screen'.  Regelsatz wegen ungültigem Selektor ignoriert.  vxgplayer-1.8.21.min.css:1:708
Farbe erwartet, aber 'none' gefunden.  Fehler beim Verarbeiten des Wertes für 'background-color'.  Deklaration ignoriert.  vxgplayer-1.8.21.min.css:1:68632
Farbe erwartet, aber 'none' gefunden.  Fehler beim Verarbeiten des Wertes für 'background-color'.  Deklaration ignoriert.  vxgplayer-1.8.21.min.css:1:68760

        `

**Comment by jbleyel** [comment]
Hi @sgse, du brauchst nicht selber suchen.
Du suchst an der falschen Stelle.
Ich brauche das neue crash log von grab.

Hast du teamviewer?

**Comment by sgse** [comment]
any desk

**Comment by jbleyel** [comment]
desk name?

**Comment by sgse** [comment]
mint1-6@ad

**Comment by jbleyel** [comment]
Ich brauch noch paar Minuten.

**Comment by jbleyel** [comment]
Jetzt

**Comment by sgse** [comment]
:-)

**Comment by jbleyel** [comment]
logon disallowed

**Comment by sgse** [comment]
DANKE :-)

**Comment by edelknecht** [comment]
Hi, ja warum auch immer muss im VTI OWIF auf Port 81, das alte Webinterface auf 80, und dann kann anschließend dann WebAdmin installieren werden. 

LG

Gesendet von Mail für Windows 10

Von: sgse
Gesendet: Dienstag, 23. Mai 2017 17:16
An: E2OpenPlugins/e2openplugin-OpenWebif
Cc: edelknecht; Author
Betreff: Re: [E2OpenPlugins/e2openplugin-OpenWebif] Wish: improve packageadministration (#608)

Hi Tim :-)
Gibt es Probleme bei Parallelinstallation von OWIF (Port 80) und WebAdmin (Port 81)?
@jbleyel
OT: Bei mir geht WebTV nicht mehr, kann aber auch an Mint/FF liegen ;-)

**Comment by jbleyel** [comment]
Hi, das mit den Ports stimmt nicht so ganz.
Allerdings stellt sich mir die Frage wieso man das DMM Webinterface überhaupt noch zusätzlich braucht.
Die Funktionen vom Webadmin habe ich doch ins OWF eingebaut und zwar genau aus dem Grund.

Die Jungs von VTI sollten nur mal das openwebif aktualisieren.
Es gibt aktuell nur 2 kleine Probleme, terminal und grab.
Das kann man aber relativ einfach mit einen Patch lösen.

**Comment by edelknecht** [comment]
Hi Jörg, mit dem aktuellen Build getestet und funktioniert. Jedoch wäre es mMn. besser wenn es noch zusätzlich oben einen Such-Filter wie im alten Webadmin gäbe. So kann man in jedem Bereich Suchen und Filtern ohne den Packetnamen genau zu kennen. Beispiel: EPG , Alexa, skin, extension, etc.pp. So oder so Danke!

**Comment by edelknecht** [comment]
Hi, noch ein Hinweis. Wenn ich den kompletten Plugin Ordner im Vti ersetzte kann es ich anschließend keine Screenshots mehr erstellen.

**Comment by jbleyel** [comment]
Das ist bekannt siehe -> #610

**Comment by jbleyel** [comment]
Hi @edelknecht , fehlt noch was? Wenn nicht, dann bitte den issue schliessen.

**Comment by edelknecht** [comment]
Hi Jörg, ja mir fehlt noch was. Ein Paket-übergreifender Such-Filter wäre sinnvoll. Es ist viel einfacher mit einem Suchfilter zu suchen. Wäre es möglich das Ihr noch einen Such Filter wie der des Webadmins integriert? 
https://www.dropbox.com/s/lbl8z651k4b9w1b/Ashampoo_Snap_Montag%2C%2029.%20Mai%202017_11h24m30s_004_.wmv?dl=0

LG und danke!

**Comment by jbleyel** [comment]
Hi @edelknecht, ich hab doch eine Suche eingebaut. Das ist doch der Filter.

**Comment by sgse** [comment]
Oder 
opkg list > /media/hdd/opkg.txt
dann kann er in dem Textfile suchen ;-)

**Comment by jbleyel** [comment]
Hi @sgse , dir scheint die Hitze nicht zu bekommen.

**Comment by sgse** [comment]
Bis eine Antwort kommt :-)
Linuxmint, FF, Chromium und Opera, picon und Text passen am Anfang und wandern dann nach rechts.
![icon1](https://cloud.githubusercontent.com/assets/17575778/26581811/b2ecb8f4-453e-11e7-9739-200a5287a1a2.png)
![icon](https://cloud.githubusercontent.com/assets/17575778/26581819/be5a9c38-453e-11e7-9de0-a1b22d7f82aa.png)
Nur bei mir?

**Comment by edelknecht** [comment]
Gug ich mir wenn alles gut läuft morgen mal in Ruhe an. Danke!

**Comment by jbleyel** [comment]
Hi @sgse , ich hab Safari und Chrome auf Mac mit Skin Vader getestet. -> Keine Probleme.
Morgen teste ich mal FF und IE auf Windoof.

**Comment by sgse** [comment]
Oh man, habe mal (FF) runter skaliert auf 67% und wieder rauf auf 120%, jetzt passt es wieder.
Ist wohl wieder nur mein "Problem". Da es aber bei allen Browsern so war bin ich da nicht drauf gekommen.
Eben in Opera geöffnet, war direkt alles wieder an seinem Platz. Verstehe wer will ;-)

**Comment by jbleyel** [comment]
Ich schau mal ob ich was finde.

**Comment by jbleyel** [comment]
Es liegt am Zoom, bei mir ist es mit Chrome auch, wenn ich den Zoom nicht auf 100% stelle.
Ich schau mal....

**Comment by jbleyel** [comment]
Hi @sgse, hab was geändert.
Du kannst hier bei dem Issue alles zu dem Thema Zoom löschen.
Es passt nicht zu Packages.

**Comment by edelknecht** [comment]
Guten Morgen Männers, habe mir eben den aktuellen Stand auf die Box kopiert und finde egal ob Edge oder Chrome keine Suche oder Such Filter ähnlich dem Webadmin Such Filter im Video. Habe auch mit dem original Theme getestet. Sorry falls ich mich dumm an stelle aber wo finde ich die neue Suche? Danke!

**Comment by sgse** [comment]
![icon5](https://cloud.githubusercontent.com/assets/17575778/26627257/1e267b62-45fa-11e7-8bbd-79dde715c11c.png)
Dort :-)

**Comment by edelknecht** [comment]
Jo,  nachdem ich wirklich den kompletten Ordner im VTI gelöscht und nicht drüber kopiert habe funktioniert der Filter nun super und gefällt mir richtig gut. Danke! 

Bug:
Unter Edge und Chrome wird nach einem Upload das hoch geladenen Files erst nach einem manuellem Refresh die Liste richtig aktualisiert angezeigt. siehe
http://snap.ashampoo.com/kUoLfc08

Usability
1. MMn. wäre es optimal wenn All und nicht Update Default wäre. Wie seht Ihr das? Geschmacksache. 
Für mich wäre die folgende Tab-Reihenfolge perfekt. 
**All / Installed / Update / More...**
Da der User auf All alles sieht und die sexy direkte Suche dort am besten zur Geltung kommt würde ich all zum default machen.

2. Mir egal weil ich Chrome User bin. Aber für Edge User eventuell unpraktisch.

Chrome öffnet den Browser Download Ordner nachdem die "Select Ipk File for Upload" Funktion ausgewählt wurde. Perfekt!  

Unter Edge landet man in Dokumente  :/
http://snap.ashampoo.com/JY9htPuu

In der Regel läuft es ja wie folgt. Das Paket will ich noch installieren. Download. Ab in die Paket Verwaltung. Dateien hinzufügen. 

Sprich perfekt wäre wenn man unabhängig vom Browser immer im Browser Download Ordner landet.

**Comment by sgse** [comment]
Nur verrückte nutzen Edge :-D (hoffentlich gibt es jetzt keine Haue von @Schimmelreiter ;-) )

**Comment by edelknecht** [comment]
Unter 10 ist Edge mittlerweile wirklich sehr schnell. ^^

Und noch eine Frage! 
:)
Werden Updates innerhalb der All Liste eigentlich auch mit nem Icon angezeigt`?

http://snap.ashampoo.com/feXSQikC

**Comment by edelknecht** [comment]
Und noch eine Schönheits Idee... Nachdem Upload will der User installieren. Wäre doch nice wenn der User auch hier das Install Icon vor den Paket Namen bekommt. 
http://snap.ashampoo.com/YdUXjtvX

**Comment by sgse** [comment]
Wer dir den Finger reicht sollte auf seinen Arm achten ;-)

Es ist viel zu warm in Deutschland, für mich ;-)

**Comment by edelknecht** [comment]
HI, mir ist noch aufgefallen das bei einem Upgrade ein BR zu viel gesetzt wird. Danke!
![br](https://user-images.githubusercontent.com/13977492/27691627-d96fd49e-5ce4-11e7-8bb5-c6b3f59118e5.png)
