### ISSUE TITLE
DreamStream E2 problem

### ISSUE THREAD

**Issue by antonyb2** [E2OpenPlugins/e2openplugin-OpenWebif#609]
For a while I have installed openpli on my DM 8000, unfortunately I can not run DreamStream E2 well, I tried to change some options in webinterface but unfortunately the program has connection problems ..
What can I do?
Thank you

**Comment by jbleyel** [comment]
You need to ask the developer of DreamStream.

**Comment by antonyb2** [comment]
No, they said the problem is the new OpenWebif..
