### ISSUE TITLE
new Grab not working without enigma2 changes

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#610]
VTi , BH , ... needs to use the old version.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/33184d68f36419b06143adf7dd773214ff1bdf07/plugin/controllers/models/grab.py

**Comment by jbleyel** [comment]
Hi @plnick, kannst du mal schauen ob du das mit einen kleinen Patch lösen kannst und das openwebif für VTi mal aktualisieren. Theoretisch braucht man nur die alte version vom grab.py.

Danke

**Comment by Schimmelreiter** [comment]
Naja, oder VTi baut die notwendige Änderung im enigma2 ein.

**Comment by jbleyel** [comment]
Ich glaube die nutzen das von VU+ und kein eigenes enigma2.
d.H. das müssen die Koreaner machen.

**Comment by jbleyel** [comment]
Hi @Schimmelreiter , der Kollege @sgse hat auch ein Problem mit dem terminal.
Kann es sein, das VTi kein IPv6 hat und daher der Transparent Proxy nicht geht?

**Comment by Schimmelreiter** [comment]
Eins nach zwei anderen ...
... erst einmal die drei Änderungen für grab:

https://github.com/OpenPLi/enigma2/commit/f42cb91d9496083340b4068e169520169957294d
https://github.com/OpenPLi/enigma2/commit/c9c24733ebc1d3be8e4636785b9d4050841a30a8
https://github.com/OpenPLi/enigma2/commit/d06eeb4bf9e3e07701a9fb287ff97a31737f109e

**Comment by Schimmelreiter** [comment]
Wegen terminal:
VTi hat IPv6, nutzt es nur an vielen Stellen nicht.

Bei sgse habe ich in seinem Tasklisten-Auszug schon gesehen, daß der Aufruf von shellinaboxd "falsch" ist:
Irgendwas steht da von "cert", es sieht so aus, als sei sein shellinaboxd für sicheren Fernzugriff (mit SSL) konfiguriert, für die Terminal-Funktion in OWIF ist aber der völlig unsichere Zugriff - dafür nur auf localhost antwortend - nötig.

Da VTi seine Änderungen nicht public macht, kann und will ich da nix machen.

**Comment by sgse** [comment]
Zur Erinnerung, wir haben gestern zu viel gelöscht.
Vor OWIF 1.2.5 hatte ich OpenVuplus 3.0 da stehen, jetzt
OE-System: 	OpenVuplus 2.1
Firmware-Version: 	VTi-Team Image 11.0.1 (2017-04-10-vti-master (1881f27))
Kernel / Treiber: 	3.13.5 / 3.13.5-20161228.r0
Sagt euch wahrscheinlich mehr als mir :-)

**Comment by Schimmelreiter** [comment]
Das verwendete OE wird bei VTi, BH (Nicht OpenBH) und OpenPLi mangels branding eh nur anhand diverser Indizien geraten.

Die Raterei steckt in dieser Datei:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/owibranding.py

owibranding.py kann nur OpenVuplus 2.1 von OE 1.6 unterscheiden, wenn da bei Dir nach Flash OpenVuplus 3.0 stand, bedeutet das, daß VTi auch an der owibranding.py non-public Patches anwendet.

None of our businesses.

**Comment by sgse** [comment]
Umgekehrt, wenn ich OWIF von VTi nehme habe ich da 3.0.
Jetzt mit OWIF 1.2.5 steht da 2.1

**Comment by jbleyel** [comment]
Ich verstehe es bis heute nicht, warum VTi den oe Code, den sie verwenden nicht auf Github legt.
Eigenbrödler.

**Comment by Schimmelreiter** [comment]
Nix umgekehrt, das ist genau das, was ich sagte.
VTi patcht an der owibranding.py non-public rum, d.h. der Code den Du hier öffentlich siehst ist nicht der, den Du mit VTi am Ende tatsächlich 
kriegst.

**Comment by sgse** [comment]
Ah, danke @Schimmelreiter

**Comment by Schimmelreiter** [comment]
Und weil VTi nicht wirklich den Code von hier benutzt, ist es auch nicht in unserer Macht, irgendwas daran zu ändern.

VTi muß für sich entscheiden, ob sie weitere non-public-patches in OWIF einbauen (Also z.B. grab downgraden) oder ihr Enigma2 auf den aktuellen Stand kriegen.

Beides ist non-public und daher für uns irrelevant.

**Comment by jbleyel** [comment]
Ich hab @plnick schon mal gefragt und er meinte, das der Source auf der Box liegt.
d.H. die py Files sind alle auf der Box.
Das macht es aber nicht besser.

engima2 ist vermultlich von hier -> http://code.vuplus.com/

**Comment by Schimmelreiter** [comment]
Nun, bezüglich der owibranding.py ist der Austausch durchaus legitim.
owibranding.py ist ja nur ein schlechter Ersatz (Krücke) für das in VTi, BH und OpenPLi fehlende branding der oe-alliance.

D.h. die owibranding greift auch bei OpenATV, OpenHDF, OpenViX, usw. usf. **nicht**, dort wird stattdessen das branding-Modul verwendet.

Wenn nun irgendein Team die owibranding.py individuell anpaßt - am naheliegendsten wäre die Entfernung aller Boxen, die das Team gar nicht unterstützt - dann ist das ok.
Denkbar wäre z.B. auch, die owibranding.py beim Image-Bau so zu erzeugen, daß sie die beim Bauen verwendeten Infos statisch zurückliefert und gar keine Erkennung mehr durchführt (Das ist letztlich das, was auch oe-alliance-branding macht).

**Comment by Schimmelreiter** [comment]
Beim enigma2 hingegen ist es so, daß VTi **nicht** das E2 von http://code.vuplus.com/ verwendet, sondern einen eigenen Fork oder zumindest einen ordentlich großen Patch-Satz.

Die Werbe-"Erkennung" wird z.B. nachträglich reingepatcht, auf http://code.vuplus.com/ ist sie nicht drin.

Einerseits verstößt das gegen Dreams Lizenz (Die die Freigabe unter GPL erzwingt) und andererseits macht es das auch unmöglich für uns, die für grab notwendigen Änderungen per Pull anzubieten.

Von daher ist das Thema für mich durch.

**Comment by FrancYescO** [comment]
Thanks for the fast fix, but seems that after the first screenshot the image is cached and also pressing the update button will not update the screenshot, the only way to get a fresh screenshot is to refresh the full page :(

**Comment by FrancYescO** [comment]
i've found a solution: 

add this after line 82
```
			self.request.setHeader('Expires','Sat, 26 Jul 1997 05:00:00 GMT')
			self.request.setHeader('Cache-Control','no-store, no-cache, must-revalidate, post-check=0, pre-check=0')
			self.request.setHeader('Pragma','no-cache')
```

**Comment by jbleyel** [comment]
Hi @FrancYescO , do you have test this with (IE,Firefox,Chrome,Safari,Opera,..) on Windows, Linux and Mac? I think not. This is why we don't have implement the header options.
This will also not work if you use a proxy.

**Comment by FrancYescO** [comment]
hem @jbleyel i just stolen the lines from your current code

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/grab.py#L58

**Comment by jbleyel** [comment]
I know but this is the right place to search.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/js/openwebif.js#L848

there is a # + timestamp at the end to prevent cache issues

**Comment by FrancYescO** [comment]
you are probably right cause when i was having the cache issue looking at the img tag and the src value was without the timestam suffix, now is correctly placed, i'm trying to reproduce the bug but with no success
