### ISSUE TITLE
EPGRefresh settings are partly ignored / EPGRefresh Einstellung "Autotimer auswerten" funktioniert nicht

### ISSUE THREAD

**Issue by messer-gernamy** [E2OpenPlugins/e2openplugin-OpenWebif#617]
Hallo,

da ich nicht weiß, ob hier deutsch oder englisch "angesagt" ist, versuche ich es ersteinmal mit deutsch.

**If an English description is needed please let me know.**

Ich nutze derzeit den Receiver "VU+ Ultimo 4K", auf dem folgendes Problem aufgetreten ist:

Beim Zugriff über OpenWebIF auf die EPGRefresh-Einstellungen werden die Angaben für den Punkt "Autotimer auswerten" anscheinend nicht korrekt an den Receiver übertragen.
Egal, welche Option ich über OpenWebIF auswähle, die Receiver-Settings stehen danach immer auf "niemals".
Wenn ich die Einstellung am Receiver auf "Immer" über die Fernbedienung vornehme, dann wird der Wert korrekt abgespeichert.

Es wäre super, wenn dieser (hoffentlich kleine) Fehler behoben werden könnte - danke im Voraus

Beste Grüße
Michael

**Comment by jbleyel** [comment]
Das liegt ganz sicher am EPG Refresh Plugin und nicht am openwebif.
Gerade eben getestet.
Da solltest du mal deine Plugins aktualisieren oder ggf. das Image wechseln.

**Comment by messer-gernamy** [comment]
Hallo Jörg,

danke für die schnelle Antwort!

Ich habe es vor einer Sekunde noch mal überprüft - alle Plugins sind aktuell (keine Updates verfügbar) und die Ultimo4K-Box läuft mit VTi 11.0.2 ... neuer geht's meines Wissens nicht.

Da bei der direkten Parametereingabe (mittels Fernbedienung am Receiver) die Einstellungen richtig übernommen werden, gehe ich davon aus, dass es ein Issue seitens des WebIFs ist.

Beste Grüße
Michael

**Comment by jbleyel** [comment]
Hi Michael,
vermutlich hat VTi wieder mal nicht das aktuelle Plugin.
Wenn du das Plugin von https://github.com/oe-alliance/enigma2-plugins/tree/2.3/epgrefresh nimmst, dann muss es auch gehen.

Mach mal ein zip vom Ordner /usr/lib/enigma2/python/Plugins/Extensions/EPGRefresh und poste es hier.

Gruß
Jörg

**Comment by messer-gernamy** [comment]
Hi Jörg,

danke für's Feedback.
Da muss ich mal schauen, ob ich heute Abend noch an den Receiver dran komme. Der ist aktuell in Betrieb - derzeit unter den Fittichen meiner Holden, die sich mit dem Teil vertraut macht ...

... andernfalls werde ich erst am nächsten Wochenende dazu kommen, da ich beruflich unterweg sein werde.

VG
Michael

**Comment by Schimmelreiter** [comment]
Einfach nur das Plugin zu wechseln wird nicht gehen:
Viele Plugins in den oe-a-Images greifen auf das "branding"-Modul zurück, um sich der Distro anzupassen.
Z.B. werden bei OpenATV alle EPG-Einstellungen auch wirklich unter Einstellungen -> EPG eingeblendet.

Und dieses branding-Modul gibt es bei VTi nicht.

**Comment by messer-gernamy** [comment]
OK, das heißt dann für mich, dass ich schlichtweg die Finger von irgendwelchen Nachinstallationen lasse! 
... und dass Ihr das Thema auf dem Schirm behaltet?

VG
Michael

**Comment by jbleyel** [comment]
Nö. Ich mache da gar nix.
Wenn du mir das zip File hier hochladen kannst, dann schau ich mir das gerne an. Und schicke dir den DIFF.

Wenn dabei rauskommt, das der Code nicht 100% von oe kommt, dann bin ich raus.

**Comment by messer-gernamy** [comment]
So, bin wieder zurück ... und hier kommt dann die Zip-Datei mit den Inhalten des Verzeichnisses /usr/lib/enigma2/python/Plugins/Extensions/EPGRefresh
[EPGRefressh.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/1098028/EPGRefressh.zip)

VG Michael

**Comment by jbleyel** [comment]
Wie erwartet ist das EPG Refresh plugin eine sehr alte Version.
Da musst du dich an das VTi Team wenden.

**Comment by martinr92** [comment]
@messer-gernamy Hast du das VTi-Team irgendwie darüber informiert? Bin heute in genau das selbe Problem gerannt.
Die momentan ausgelieferte Version ist übrigens "vti-11.0.0-20161124-r0".
Also vom letzen Jahr. :-(

**Comment by messer-gernamy** [comment]
@martinr92 
Ich habe das Problem auf der Seite vuplus-support.org zweimal gemeldet ... einmal in einem separaten Thread und einmal in der Wunschliste für neue Images.

Bislang habe ich darauf keine Rückmeldungen erhalten (erwarte ich allerdings mittlerweile auch nicht mehr).

VG Michael

**Comment by martinr92** [comment]
Danke. Ich habe das Thema nochmals im Forum angebracht:
https://www.vuplus-support.org/wbb4/index.php?thread/112349-epgrefresh-plugin-veraltet/
