### ISSUE TITLE
Timer-editor of Open-WebIF 1.2.5 takes wrong channel into the dropdown box

### ISSUE THREAD

**Issue by DocEagle** [E2OpenPlugins/e2openplugin-OpenWebif#624]
Editing any existing timer entry using OpenWebIF 1.2.5 leads to an error concering the assigned channel before. The dropdown box for the TV/radio channel is not filled with this channel, but accidentally with any other.

This also happens when adding a new timer-entry out of the EPG of the WebIF.

The error is reproducable and confirmed by other users.

![img_1229](https://user-images.githubusercontent.com/29797150/27734977-a98bf37a-5d9d-11e7-8f57-630f1079cd29.jpg)
![img_1230](https://user-images.githubusercontent.com/29797150/27734980-ae144992-5d9d-11e7-89d7-362730215ec1.jpg)

**Comment by Schimmelreiter** [comment]
Continued in #631

**Comment by jbleyel** [comment]
Hi @rdamas , bei mir funktioniert deine Änderung nicht.
Ein bestehender Timer geht nicht mehr auf.
Ich hab aber auch einiges geändert.
