### ISSUE TITLE
Refresh automatically executed multiple times

### ISSUE THREAD

**Issue by athoik** [E2OpenPlugins/e2openplugin-OpenWebif#625]
When option Refresh automatically is selected on Screenshot and you press the link Grab Screenshot on the right, then screenshot executed multiple times. 

In order to reproduce click on refresh automatically checkbox and then click several times on grab screenshot.

**Comment by jbleyel** [comment]
not reproducible on my site

**Comment by ims21** [comment]
reproduced ...  open Owif, set Autorefresh (and cca 15s) , press Grab Screenshot and wait for first Autorefresh.
Then press Grab screenshot and then Refresh button ... then you will see, how autorefresh grabs 2x.
Each Grab screenshot + Refresh adds one refresh

**Comment by athoik** [comment]
Thank you for looking on  this!
