### ISSUE TITLE
Spaltenbreite nicht in Ordnung

### ISSUE THREAD

**Issue by Pumuckel65** [E2OpenPlugins/e2openplugin-OpenWebif#627]
In der Version 1.2.5 kommt es zu folgendem Darstellungsfehler im EPG (Zeitschriftenmodus):

- Spaltenbreite für TV-Sender und TV-Programm nicht identisch --> siehe Foto
http://fs5.directupload.net/images/170705/kzdggt2o.jpg

**Comment by Schimmelreiter** [comment]
Kann ich nicht bestätigen:

![image](https://user-images.githubusercontent.com/2022025/27879656-a3812a6c-61c2-11e7-89c1-b739afaeca82.png)

**Comment by Pumuckel65** [comment]
Danke für die schnelle Antwort!
Hmmmmmmm ... komisch

Bis data hatte ich die Version 1.2.1 und da ist die darstellung einwandfrei. Sobald ich die Version 1.2.5 installiere habe ich den Spaltenversatz.

OpenPli 4 mit Version 1.2.1 --> o.k.
OpenPli 6 mit Version 1.2.5 --> fehlerhaft
OpenPLi mit Version 1.2.1 --> o.k.

OpenPLi 4 mit Version 1.2.1
[img]http://fs5.directupload.net/images/170704/johmt66a.jpg[/img]

OpenPLi 6 mit Version 1.2.5
[img]http://fs5.directupload.net/images/170705/kzdggt2o.jpg[/img]

**Comment by jbleyel** [comment]
ist schon gefixt.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/0e990c0575c5f77106e845df36396c09c5ecd8e8

**Comment by Pumuckel65** [comment]
Das Problem ist leider wieder vorhanden und die Zeile 10 in der multiepg.tmpl sieht aber schon wie folgt aus:
[code}
	.service { font-weight: bold; font-size: 12px; line-height:30px; padding-right: 4px; white-space: nowrap; overflow: hidden;}
[/code]

http://www.abload.de/img/09876ohs75.jpg

Wenn ich nun 1x zwischen OWIF-old-design und OWIF-new-design und wieder zurück wechsele, ist der Fehler wieder weg und ich kann ihn bis jetzt auch nicht bewusst reproduzieren ... irgendwann ist der Fehler halt wieder da.

http://www.abload.de/img/098760nrrh.jpg

Version: OWIF 1.3.2
