### ISSUE TITLE
DVB-C and DVB-T namespace, orbital position and SNR

### ISSUE THREAD

**Issue by AbuBaniaz** [E2OpenPlugins/e2openplugin-OpenWebif#630]
Slight issue with the display in openwebif.

1. SNR % falls onto second line for DVB-T. Not had any 100% SNR on satellite, so can't say if this definitely restricted to DVB-T. 

2. Namespace is negative and for both DVB-C and DVB-T and incorrect

3. Orbital position is blank. Can these be filled?

Thanks in advance

![cable](https://user-images.githubusercontent.com/6644489/28242884-d4d78968-69af-11e7-9754-28b8828d3e09.png)

![terrestrial](https://user-images.githubusercontent.com/6644489/28242885-d7436de8-69af-11e7-9333-4430df581ebc.png)

![satellite](https://user-images.githubusercontent.com/6644489/28242886-d9840ac2-69af-11e7-95c4-5a25d3b6d885.png)

**Comment by AbuBaniaz** [comment]
Which file is responsible for this please?

**Comment by athoik** [comment]
Namespace is here: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/views/ajax/current.tmpl#L144
Orbital Position is here: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/views/ajax/current.tmpl#L174

Namespace value initialized here: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/services.py#L59
Orbital Position initialized here: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/services.py#L163

**Comment by jbleyel** [comment]
Orbital Position for DVB-C and T. Are you kidding me?
https://en.wikipedia.org/wiki/Geostationary_orbit

**Comment by jbleyel** [comment]
The SREF  for DVB-C is normaly ...:FFFF0000... and for DVB-C ...:EEEE0000...
This part is the namespace. 
We can show this, but it makes no sense.

I'm not sure about SNR for non SAT channels.

**Comment by AbuBaniaz** [comment]
>Are you kidding me?
So why list DVB-C/DVB-T under satellites in other places?

>The SREF for DVB-C is normaly ...:FFFF0000... and for DVB-T ...:EEEE0000...
>This part is the namespace.
>We can show this, but it makes no sense.

Best not to show gibberish. 
Also, Pli and ViX allow for Namespace subnet
  
>I'm not sure about SNR for non SAT channels.
I *think* there isn't enough space allocated. Most satellite services wont have 100%, so the issue i snot easily seen.

**Comment by athoik** [comment]
>The SREF for DVB-C is normaly ...:FFFF0000... and for DVB-C ...:EEEE0000...

The last two bytes of namespace now are empty now because the "subnetwork" is ignored in isValidOnidTsid, and we always assume the c/t/atsc has always good onid. Something wrong. 

Now there is an option to keep extra information in namespace (the frequency is placed there for c/t/atsc and the frequency + modulation for s).

The Orbital Position is Sat related only, I just point where this value is initialized from. 

Would be nice to display that value like this 28.2° instead 282.

**Comment by jbleyel** [comment]
28.2° fine, i can do this.
But all other things should do someone else.
I don't have DVB-C or T.

**Comment by athoik** [comment]
> 28.2° fine, i can do this.

Here is how it's done on e2 (including east / west)

https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Tools/Transponder.py#L4

```
return pos > 3600 and "N/A" or "%d.%d\xc2\xb0%s" % (pos > 1800 and ((3600 - pos) / 10, (3600 - pos) % 10, "W") or (pos / 10, pos % 10, "E"))
```

**Comment by AbuBaniaz** [comment]
>I think there isn't enough space allocated. Most satellite services wont have 100%, so the issue is not encountered often or seen.

Here is a picture of 100% for sat. The "%" is most likely behind the Dolby sign
![webif sat100](https://user-images.githubusercontent.com/6644489/31579310-a3e0d940-b12b-11e7-8427-87e2beca2921.png)

**Comment by jbleyel** [comment]
orbital position -> DONE

**Comment by jbleyel** [comment]
The rest : someone else.

**Comment by AbuBaniaz** [comment]
Thanks. Needs a tweak. "orbital position:"  is repeated
![webif](https://user-images.githubusercontent.com/6644489/31579575-02e76404-b131-11e7-9073-507846bee97e.png)

**Comment by jbleyel** [comment]
No, you need to refresh the template.

**Comment by AbuBaniaz** [comment]
I updated the .tmpl file before my comment.  If I have not messed up the testing, this 

`
inf['orbital_position'] = _("Orbital Position") + ': ' + orb
`
ought to be changed to 
`
inf['orbital_position'] = orb
`
