### ISSUE TITLE
Timer-editor of Open-WebIF 1.2.5 - changing/deleting repeating Timer Settings 

### ISSUE THREAD

**Issue by FrankBorchers** [E2OpenPlugins/e2openplugin-OpenWebif#631]
When i edit Timer-Settings (created at the stb with repeating timers) with the browser the repeating timers change in the editing form. The repeatings in the timer List are OK when editing (often at the scond opening) the repeating timers will be partly or totaly changed. Suspicies is that the timer works once and is after the recording still in the timers list.

I fully resetted my Vu+ Solo 4K with Vti 11.0.2 with a USB flash and manuell recreating the timers !

It sems to be similar to #624

**Comment by jbleyel** [comment]
not reproducible on my site

**Comment by jbleyel** [comment]
@rdamas : Kannst du dir das mal anschauen?

**Comment by rdamas** [comment]
Jep - ich schau mal ob ich das reproduzieren kann.

**Comment by Schimmelreiter** [comment]
Ich kann ...
Das ist allerdings nicht immer der Fall ...

**Comment by Schimmelreiter** [comment]
Genauer: Ich kann #624 reproduzieren.

Das ist ein richtig ätzender Bug, weil es mir regelmäßig Aufnahmen versaut.
Da wird dann auf einmal eine auf TNT Serie HD programmierte Aufnahme stattdessen auf RTL HD aufgenommen ...

**Comment by rdamas** [comment]
Bisher kann ich das Verhalten auch nicht reproduzieren; allerdings ist mir aufgefallen, dass für die Bearbeitung der Timer /ajax/timers aufgerufen wird, was intern einen Aufruf von getTimers() auslöst. Möchte ich jetzt einen Timer bearbeiten, wird dafür /api/timerlist aufgerufen, was noch einmal getTimers() aufruft. Die Infos vom ersten Aufruf könnte man sicher auch schon alle ins HTML schreiben und dann beim Edit nur noch ein fertiges Timer-Objekt an den Editor übergeben. Ist aber Umbauarbeit.

Was ich mir noch einmal genauer anschauen möchte ist, ob der Aufruf von initTimerEdit() nicht zu Problemen führen kann; ich denke da steht nicht umsonst: "FIXME: async".

Wegen #624: der Fehler tritt bei mir auch nicht mehr auf, seit Jörg einen Fix dafür gebaut hat. Und ja, der Bug war ätzend ;-)

**Comment by rdamas** [comment]
@Schimmelreiter: kannst Du bitte mal versuchen, ob Du #624 mit den beiden Patches aus meinem letzten Kommentar noch reproduzieren kannst?

**Comment by Schimmelreiter** [comment]
Ja, aber leider nicht mehr heute ...

**Comment by jbleyel** [comment]
Hi @rdamas , mit deinem Patch geht bei mir nix mehr.

**Comment by jbleyel** [comment]
Hol dir bitte mal meinen letzten commit. Da hab ich ein paar Fehler gefixt.

**Comment by jbleyel** [comment]
Hi @rdamas, du hast auch die Parameter der editTimer Funktion geändert, das ist wohl der Fehler.

**Comment by rdamas** [comment]
Ich merge mal bei mir; der Patch 30f9dd4 ist auch nicht unbedingt nötig, der sorgt "nur" dafür, dass im Timer-Editor nicht nochmal ein Ajax-Aufruf passieren muss. Alle Infos zum Timer werden ja schon einmal beim Aufruf der Timer-Seite abgeholt.

Der zweite Commit 8ddd610 ist der, der vielleicht einen Fehler fixt. Kannst Du den einmal alleine ohne den ersten versuchen?

**Comment by rdamas** [comment]
Hier mein letzter Patch noch einmal auf dem aktuellen Stand im Repo aufbauend: https://github.com/rdamas/e2openplugin-OpenWebif/commit/47f041285ec25a7e049d049aeae6e15e046753fd  - funktioniert der bei Dir?

**Comment by jbleyel** [comment]
Sieht gut aus.
#631 sollte gefixt sein.
#624 kann ich nicht nachstellen.

**Comment by Schimmelreiter** [comment]
Muß ich über längere Zeit beobachten. 
Da der Fehler nicht immer auftritt, kann man den nicht einfach so nachstellen.

**Comment by jbleyel** [comment]
Wenn du mir sagst ob das nur bei neuen Timern passiert oder nur bei bestehenden, dann wird es schon mal um einiges leichter.
Dann noch folgende Infos:
* Wo genau im openwebif legst du den Timer an (wenn es ein neuer Timer ist)
* Welchen Browser nimmst du
* Hast du den betroffenen Sender von dem Timer nur in einem Bouquet?

**Comment by FrankBorchers** [comment]
Ich habe mit dem aktuellen Update vom 8.9. versucht das Problem zu reproduzieren und kann - wie früher fast jedes mal passiert - aktuell nicht mehr reproduzieren. Auch ich werde es weiter beobachten.

**Comment by Schimmelreiter** [comment]
Ich beschreib's mal ganz genau :)
1. Natürlich Chrome
2. Ich kriege von TV-Wunschliste eine e-Mail, wenn eine Serie auf meiner Wunschliste im TV kommt
3. Wenn es die Erstausstrahlung ist, gehe ich dann ins EPG des Senders (Fernsehen -> Favoriten -> grafischer Button "Zeige EPG für $SENDER".
4. Dort suche ich die Sendung, meistens per Strg+F
5. Klick auf den grafischen "Add+Edit Timer"-Button (Da es eine Serie ist, muß ich ja auch sagen "Jeden Mo/Di/Mi/Do/Fr", daher Add+Edit statt nur Add.
6. In dem Dialog steht (stand?) dann auf einmal ein völlig anderer Sender als der, aus dessen EPG heraus ich den Timer programmiert habe, meistens Platz 1 der Senderliste, waren aber auch schon mal andere.

Ich hatte dabei auch das Gefühl, als würde der Dialog manchmal doppelt gezeichnet, erst richtig und dann auf einmal ändert sich die Drop-Down-Auswahl zum Falschen hin.

Wie schon gesagt, muß erstmal ausgerollt sein, dann kann ich testen.

**Comment by FrankBorchers** [comment]
Ich habs heute auch wieder gehabt :-(((

Ich habe über die Suche den Timer für Inspector Gadget am heutigen Sonntag mit klicken auf den Button hinzugefügt und anschließend über denweiteren  gefundenen Eintrag am Montag dann einen wiederholenden Timer erstellt.

Fehlerablauf:
1) In der Timerliste den ersten Eintrag mit dem Namen Inspector Gadget öffnen ist keine Wiederholung eingetragen (ist ja auch korrekt) und ich beende die Anzeige mit Schließen
2) In der Timerliste den zweiten Eintrag mit Namen Inspector Gadget öffnen dann werden die regelmäßigen Timer nicht angezeigt :-(  sollte aber Mo-Fr sein und wird in der Timerliste auch so angezeigt s. Screenshot)

Wenn ich den Browser schließe und direkt den Schritt 2) mache dann werden die Timer korrekt angezeigt! Diese Verhalten ist bei mir mit Chrome (inkognito Modus) reproduzierbar.

![image](https://user-images.githubusercontent.com/30393405/30783135-5ec5d8a8-a13e-11e7-88ae-a035046da728.png)

**Comment by rdamas** [comment]
Das ist ja krass - ich bekomme es jetzt auch reproduziert. Ich rufe in der Timerliste den ersten Timer (ist aber egal, welcher) zum Bearbeiten auf - alles gut: Wiederholungen werden angezeigt; dann den zweiten: jetzt werden die Wiederholungen nicht mehr angezeigt. Danach auch nicht mehr beim ersten Timer.  Lade ich die Seite mit Shift+Reload neu, wird wieder alles richtig angezeigt. Mal schauen, ob ich herausfinde, was da falsch läuft.

**Comment by Schimmelreiter** [comment]
Der Fehler besteht leider immer noch.

Timer für Hawaii Five-O Mi 11.10.2017 20:10 - 11.10.2017 21:30 angelegt und auf "Mi" geklickt, um den Timer jeden Mittwoch wiederholen zu lassen.
Timer wird angelegt, aber nur für das gewählte Datum, ohne Wiederholungen.

Auch erneutes Öffnen des Timers zur Bearbeitung und nochmaliges Anwählen von "Mi" bringt keine Änderung, es bleibt ein einmaliger Timer.

**Comment by jbleyel** [comment]
Reopen because of monitor for any other issues.
Finally close if all timer edit issues are fixed.
