### ISSUE TITLE
Deleting a recording behaves different compared to deleting with the remote

### ISSUE THREAD

**Issue by sidamos** [E2OpenPlugins/e2openplugin-OpenWebif#633]
I have a VU+ with VTI image, version VTi 11.0.2 (2017-06-21-vti-master (d182006)).
OpenWebif is 1.2.4-e2openpluginsgit20170612-r0-2502+5700f7c-.
I have enabled trashcan for deleting.

When I delete a recording with the remote, then it moves the files to the trash folder and updates the last changed dates. It also moves a preview .jpg, if it exists.

When I delete a recording with OpenWebif, it moves the files to the trash folder without updating the last changed dates. This is not so good for the AutoShredder plugin. Because if I delete an older recording, AutoShredder will purge it from the trash next time, but normally, you want to keep the recording in the trash for X days after deleting, not after a recording.
Also, OpenWebif ignores the .jpg preview image, it does not move it to the trash.

**Comment by jbleyel** [comment]
V 1.2.4 is not the latest build.
We can only support this original source.
You need to contact the VTi team.

**Comment by sidamos** [comment]
Here is no newer release than 1.2.4. 
My OpenWebif -> About says 1.2.5. From the plugin name, I'd say it's from commit 5700f7c of Jun 11, 2017.

**Comment by jbleyel** [comment]
Please upload this file from your box here.
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/movies.py

**Comment by sidamos** [comment]
Attached. Thanks for looking into that!
[movies.py.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/1219823/movies.py.zip)

**Comment by jbleyel** [comment]
This file is the latest version and the move function should work as expected.

Please check the /etc/enigma2/settings file and tell me the value of
config.usage.movielist_trashcan
and
config.usage.movielist_use_trash_dir

**Comment by sidamos** [comment]
config.usage.movielist_trashcan is not in the settings file.
config.usage.movielist_use_trash_dir=true

I cannot find the possibility to change the name of the trashcan dir anywhere in the menus. I just enabled using the trashcan. The trashcan dir is "movie_trash", parallel to the "movie" dir.

**Comment by jbleyel** [comment]
The movie_trash name is defined fixed in the image.
I can't find any coding bugs.
We need to add debug prints in the movies.py and check the enigma2 log.
This log needs to be enabled before.

**Comment by sidamos** [comment]
I have already debug logging enabled. I am getting "dvbapp2_debug_*" files.

Just to make sure, that there is no misunderstanding:
Deleting recordings with Open Webif is basically working. Just the 2 things I mentioned in the bug report are not correct.

**Comment by jbleyel** [comment]
I know.
Delete is not a delete, i'ts a move to trash folder.
The jpg extension is in the list of file extensions for this moving.
The move does not change the date.

**Comment by sidamos** [comment]
OK, so you are saying:
* not moving the .jpg is a bug
* not updating the last change date is not a bug

But deleting by remote in the filmlist is updating the change date.

**Comment by jbleyel** [comment]
The delete function on the box is not comparable with the delete of the openwebif.

I need some files from your box:

/usr/lib/enigma2/python/Tools/Trashcan.py (if exists)
/usr/lib/enigma2/python/Tools/CopyFiles.py
/usr/lib/enigma2/python/Screens/MovieSelection.py
/usr/lib/enigma2/python/Screens/InfoBar.py

**Comment by sidamos** [comment]
Not much luck:
No /usr/lib/enigma2/python/Tools/Trashcan.py.
No /usr/lib/enigma2/python/Tools/CopyFiles.py.
No /usr/lib/enigma2/python/Screens/MovieSelection.py, only /usr/lib/enigma2/python/Screens/MovieSelection.so.
No /usr/lib/enigma2/python/Screens/InfoBar.py, only /usr/lib/enigma2/python/Screens/InfoBar.so.

**Comment by jbleyel** [comment]
Do you really have an VTi Image???

**Comment by sidamos** [comment]
Absolutely. Running on a VU+ Solo4k.

**Comment by jbleyel** [comment]
Then make a backup of /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/movies.py

and change the file with this one -> 

[movies.py.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/1220420/movies.py.zip)

Then restart enigma2 and delete one recording and check the debug log and the trash folder.

**Comment by sidamos** [comment]
[dvbapp2_debug_2017-08-13_141346.log.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/1220442/dvbapp2_debug_2017-08-13_141346.log.zip)

I deleted 2 recordings with your movies.py and it worked correctly. It moved also the .jpg file. Attaching the log.

Then I restored the original movies.py and this one does NOT move the .jpg file.

**Comment by jbleyel** [comment]
Gib mir mal den genauen Dateiname von dem ts File und von dem jpg.
Bitte auch die attribute von dem jpg.
ls -l /.../<name>.* 

Ich werde die neue Version von movies.py so lassen, aber verstehen würde ich es trotzdem gerne.
Bei mir wird das jpg verschoben und daher müsste es auch bei dir gehen.

**Comment by sidamos** [comment]
Deine Version von movies.py funktioniert ja. Nur meine verschiebt es nicht. Aber Du meintest ja, die wären nicht groß unterschiedlich.

Das Aufnahmeverzeichnis ist mit NFS eingebunden. Hier sieht man auch ein .jpg, das beim Löschen mit meinem movies.py nicht verschoben wurde:

-rw-r--r--    1 1000     1000         14416 Aug 11 07:02 20170810_1930_-_RTL_HD_-_GUTE_ZEITEN,_SCHLECHTE_ZEITEN_-_S00E6316_-_DRAUFGAENGER.ts_mp.jpg
-rwxr-xr-x    1 1000     1000           200 Aug 11 19:29 20170811_1930_-_RTL_HD_-_GUTE_ZEITEN,_SCHLECHTE_ZEITEN_-_S00E6317_-_VERSTAENDNIS.eit
-rw-r--r--    1 1000     1000     3933405184 Aug 11 20:25 20170811_1930_-_RTL_HD_-_GUTE_ZEITEN,_SCHLECHTE_ZEITEN_-_S00E6317_-_VERSTAENDNIS.ts
-rw-r--r--    1 1000     1000         53648 Aug 11 20:25 20170811_1930_-_RTL_HD_-_GUTE_ZEITEN,_SCHLECHTE_ZEITEN_-_S00E6317_-_VERSTAENDNIS.ts.ap
-rw-r--r--    1 1000     1000            36 Aug 11 20:25 20170811_1930_-_RTL_HD_-_GUTE_ZEITEN,_SCHLECHTE_ZEITEN_-_S00E6317_-_VERSTAENDNIS.ts.cuts
-rw-r--r--    1 1000     1000           184 Aug 12 18:55 20170811_1930_-_RTL_HD_-_GUTE_ZEITEN,_SCHLECHTE_ZEITEN_-_S00E6317_-_VERSTAENDNIS.ts.meta
-rw-r--r--    1 1000     1000       1319712 Aug 11 20:25 20170811_1930_-_RTL_HD_-_GUTE_ZEITEN,_SCHLECHTE_ZEITEN_-_S00E6317_-_VERSTAENDNIS.ts.sc
-rw-r--r--    1 1000     1000          6758 Aug 12 07:02 20170811_1930_-_RTL_HD_-_GUTE_ZEITEN,_SCHLECHTE_ZEITEN_-_S00E6317_-_VERSTAENDNIS.ts_mp.jpg

**Comment by jbleyel** [comment]
Fehler gefunden, das Bild heist *.ts_mp.jpg und nicht *.jpg?

**Comment by sidamos** [comment]
Ja, ist das nicht normal? Das ist so, wie es der Plugin MovieListPreview erzeugt und braucht.

**Comment by jbleyel** [comment]
Die nächste Version sollte funktionieren.

**Comment by sidamos** [comment]
Super, danke! Kann ich bis dahin Deine movies.py gefahrlos mit meiner Installation verwenden?

**Comment by jbleyel** [comment]
Klar

**Comment by sidamos** [comment]
OK, danke.
