### ISSUE TITLE
Live-Update function - how does it work?

### ISSUE THREAD

**Issue by Joey-1970** [E2OpenPlugins/e2openplugin-OpenWebif#650]
Hello!

I read this:

> One of the major Improvements compared to the Webinterface of enigma1 is the Live-Update functionality. Changes can be automatically delivered to the webinterface without polling the server or reloading the whole page. This is realized by using a never ending Connection which is used to execute the DOM-Manipulation cmds. 

But how can I get this "stream"? 

Joachim

**Comment by jbleyel** [comment]
Live Update isn't planed for the plugin itself.
You need to use the image based update feature for all plugins.
