### ISSUE TITLE
Multiepg: use toplevel service list to switch service

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#656]
Is there anything against using the toplevel (and bottom level) service list elements (the div with class="service") to switch the service? Like in multiepg timer editor?

**Comment by jbleyel** [comment]
kein Problem, aber bitte den Link für Zap nicht im HTML code einbauen, sondern unten als jquery, sonst wird die Seite zu groß.

**Comment by jbleyel** [comment]
Für mode 1 hab ichs mal eingebaut.

**Comment by rdamas** [comment]
Könnte ein Kopie sein von dem was ich vorbereitet habe :-)
Ich habe den zweiten Parameter von zapChannel() noch mit $(this).text() befüllt.

**Comment by jbleyel** [comment]
Deins sieht besser aus. ;-)

**Comment by jbleyel** [comment]
Hi @rdamas , can we close this issue?

**Comment by rdamas** [comment]
Yes, of course.
