### ISSUE TITLE
e2devicename blank

### ISSUE THREAD

**Issue by glotton** [E2OpenPlugins/e2openplugin-OpenWebif#665]
I have a dm800se on which I run the official image from dream.  I also use a Raspberry Pi with Kodi (openelec) to connect from another room and watch the programs.

I have recently installed blackhole 3.2.2D on a dm800 and wanted to use this to stream but Kodi always refused the connection.  I checked the Kodi log and found the following message: ERROR: AddOnLog: VU+ / Enigma2 Client: GetDeviceInfo Could not parse e2devicename from result! 

I checked the /web/devinfo page and saw the following:
                <e2webifversion>OWIF 1.2.5</e2webifversion>
                <e2fpversion>None</e2fpversion>
                <e2devicename></e2devicename>

As you see e2devicename is empty.
I know the box works because
$ cat /proc/stb/info/model
dm800

but it is not propogated down.

Please can you fix the problem so that I can stream from my new installation.

Otherwise thanks for great work.

**Comment by jbleyel** [comment]
We can't fix issues in modified plugin files.
Please ask the blackhole team.
