### ISSUE TITLE
Picon Path

### ISSUE THREAD

**Issue by bigreja** [E2OpenPlugins/e2openplugin-OpenWebif#678]
PiconPath return FIRST hit change on file plugin/controllers/models/info.py produces a runtime error:

/home/oe1/atvm60/build-enviroment/builds/openatv/release/h5/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+7371f8cae0-r1/git/plugin/controllers/models/services.py:915 in getPicon
914
915
916
exceptions.TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
----
Change on file:
- return PICONPATH
+ return None
-----

Previous version would return empty string, now it returns None

When services.py  tries to concat PICONPATH + sname it fails, as iconpath is returning none, it should return a string, or in service it should convert function result to string then concatenate

**Comment by Schimmelreiter** [comment]
Actually services.py should handle "None" instead.

But interesting that you managed to get it to the point where it returns None at all, because the default path should always exist.

**Comment by bigreja** [comment]
i just look at the changes made, return was changed from Return
return PICONPATH
to 
Return None 
and the error on services
exceptions.TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

it's trying to concatenate NoneType and  str,  first argument is PiconPath...
It worked fin a few days ago, i updated last night and it gives this error, maybe the problem is elsewhere, i didn't made any debug, just went through source and recently changed files..

**Comment by bigreja** [comment]
i have made the change on file and its working again, just added 
PICONPATH = ""

and 
return PICONPATH

back to info.py
replaced the file on my enigma, compile it to info.pyo
rebooted
and it's working again!

**Comment by Schimmelreiter** [comment]
Both fix the crash, but this easier way is the logically worse one:
If we assign the empty string to PICONPATH, it will not be tried again to find one.

If we assign None and let functions calling GetPiconPath properly handle it, OWIF will try to locate picons again (and again), until it finds some.

This is especially relevant if box was just flashed and the user puts the picons back in place later.

With this easier solution, WEBIF needs to be restarted (As PICONPATH is now static).

**Comment by bigreja** [comment]
PICONPATH = "" was placed where it was before the changes, i thing it still looks at the icon path, but if it does not finds it will return an empty string and it will concatenate fine on services.py
using 
str(getpiconpath()) + ...

**Comment by jbleyel** [comment]
It makes no sense to build a loop like before.
I prefer my last commit.

**Comment by Schimmelreiter** [comment]
I know, as I told you.

That it worked before doesn't mean it was the best solution.

**Comment by Schimmelreiter** [comment]
@jbleyel:
Beides ist suboptimal:
Wenn wir einen leeren String zurückgeben, wird "" und der Picon-Name verkettet und geprüft, ob die Datei existiert ... **jedes Mal**, wenn ein Picon gebraucht wird.

Kommt "None" zurück (und wird richtig ausgewertet), wird gar nicht erst versucht, ein Picon zu öffnen.

Gut, dafür wird natürlich jedes Mal nach dem Verzeichnis gesucht, aber das kann wenigstens irgendwann zum Ziel führen.
Jetzt bleibt es bis zum nächsten Neustart bei "" und daß da kein Picon ist wird sich nicht ändern.

**Comment by jbleyel** [comment]
Jetzt hab ich dich verstanden.
Dann sollten wir None zurückliefern und auf None prüfen.
Sorry my fault.

**Comment by Schimmelreiter** [comment]
Sag ich doch :)
Hätte ich auch schon gemacht, aber in einer Sitzung baut mein Server Kernel, im anderen löscht er sie wieder und im dritten löscht er anderen Kram.
Also ausgelastet bis unter die Kühlerrippen.

**Comment by jbleyel** [comment]
ich mach das.

**Comment by bigreja** [comment]
Can't you just create a setting value for picon path somewhere?

**Comment by Schimmelreiter** [comment]
Man könnte sich in GetPiconPath auch den Zeitpunkt der letzten Suche merken und erst nach 120 Sekunden wieder die Verzeichnisse durchforsten.
Das wäre vermutlich das Beste, dann kann der Benutzer die Picons zwar später nachreichen, aber beim Aufbau des EPG wird nicht jedes Mal nach einem Pfad gesucht (Länger als 120 Sekunden sollte das ja nicht dauern).

**Comment by jbleyel** [comment]
Schau mal, der Kollege bigreja will auch das Setting was ich eingebaut hatte. *grins*

**Comment by bigreja** [comment]
Or you can just continue to talk in german, i will portuguese myself, obrigado!

**Comment by jbleyel** [comment]
Hi bigreja , i have sayed : The setting was there but only a few hours.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/d03a990ed5e808c2425cfa36948c8da37bafb397

**Comment by bigreja** [comment]
jbleyel I'm Portuguese, so i didn't understand what you wrote before. A user setting is always the best option in my opinion. 
I only got my enigma box a few days ago, i will try to become an contributor ;)

**Comment by jbleyel** [comment]
I have made a setting option but it is not allays the best case.
There are 3 different users.
1) they have no picons
2) they have only one folder with picons for OSD and webif
3) they have 2 different folders for picons one for OSD and one for webif

If you you are 1 or 2 we don't need any setting.
If you are 3 then you have now a folder named owipicon to use a different folder.

**Comment by jbleyel** [comment]
Hi @Schimmelreiter, kannst du bitte den fix beim oe source aktualisieren.

**Comment by Schimmelreiter** [comment]
Done
