### ISSUE TITLE
Size of heaser

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#685]
After last changes on my 21:9 monitor ... wrong display. See screenshot of top screen ... text is under , on right it is shifted ... 

![owif](https://user-images.githubusercontent.com/1208763/31585384-ba4e72ba-b1c0-11e7-887e-b50cc364310d.PNG)

**Comment by jbleyel** [comment]
Do you have the latest commit?
Do you have refreshed the style.min.css file? (clear browser cache)

**Comment by jbleyel** [comment]
@doubleO8 : please check

**Comment by ims21** [comment]
this problem is on my 21:9 (2560 * 1080) only. On full hd is is ok. Today's update, today's build.

**Comment by jbleyel** [comment]
Please check the #header h2 style definition.
min-width:500px ->  OK
width:500px -> NOK (browser cache)

**Comment by ims21** [comment]
ok

**Comment by doubleO8** [comment]
I'm sorry, I cannot reproduce this, even with my ridiculous long prefix it renders correctly.
`<shift-ctrl-r>` is your friend.

![screenshot_2017-10-15_17-53-39](https://user-images.githubusercontent.com/1141561/31586558-e0df6f1c-b1d2-11e7-9fab-0fc6fbc3d442.png)

**Comment by jbleyel** [comment]
@ims21 has closed the issue.

**Comment by doubleO8** [comment]
yes, I realised that right after hitting the 'comment' button.
