### ISSUE TITLE
Strange username/password in m3u8

### ISSUE THREAD

**Issue by imperia777** [E2OpenPlugins/e2openplugin-OpenWebif#696]
I have Require authentication for http streams enabled. When I try to watch stream by clicking the stream link in WebIf the username:password in m3u8 file are wrong:

#EXTM3U 
#EXTVLCOPT--http-reconnect=true 
#EXTINF:-1,MGM
#EXTVLCOPT:program=488
http://-sid:29974d03c0ce49f7cbafc2132579afed@et6x00.imperia.lan:8001/1:0:1:1E8:B:1:186AB7F:0:0:0:

username is always -sid
and password is some hash.

**Comment by Schimmelreiter** [comment]
That's simple:
OWIF performs the password check, but it can not know the true password from the Linux-userdb.

For that reason, it uses a trick when it has to create an URL that will cause another session:
It passes the session ID of the original session plus a hash and will consider this user:pass combination as valid auth in future sessions.

**Comment by Schimmelreiter** [comment]
To be more precise:
There ARE bugs, but they aren't inside OWIF.

OpenPLi made a change to streaming in E2 a long time ago and all other Open*** images have merged this bug:
They snatched away auth from OWIF, effectively breaking any technic to hand over sessions between OWIF and streaming and there is **nothing** we can do about it.

Clicking on stream URLs inside OWIF simply **does not work at all** if streaming auth is enabled in Open*** images, but the -sid:hash cheat at least works if one uses the proper original code (The original streamproxy).

It also worked for transcoding on Vu+ and some other machines, until OpenPLi managed to make Vu+ merge their bug :-|
