### ISSUE TITLE
remote not loading

### ISSUE THREAD

**Issue by lcrosspt** [E2OpenPlugins/e2openplugin-OpenWebif#700]
full remote doesn't load when push button.
stb is Atemio 6200 and is identified correctly in info.(can use remote from - xp1000 img - xp_rc14_normal.png)
not working in V- 20171001 too.

![screenshot_1](https://user-images.githubusercontent.com/33299158/32302251-9eb35218-bf59-11e7-90fc-35b9994ac9ea.jpg)

**Comment by Schimmelreiter** [comment]
Which image?
The remotes and box images are actually maintained by the image makers that do not use boxbranding.

**Comment by lcrosspt** [comment]
Hi the image is Egami, but i don't know if i understand it correctly, because Egami uses box branding, it does identify correctly the box model and display the box foto correctly.
If is necessary to ask to the team to change anything please tell me.thanks

**Comment by Schimmelreiter** [comment]
Then please file a bug report here: https://github.com/oe-alliance/branding-module
That's the correct place if your box used boxbranding.
