### ISSUE TITLE
Implementation of a RESTful API for altering configuration values

### ISSUE THREAD

**Issue by doubleO8** [E2OpenPlugins/e2openplugin-OpenWebif#702]
Comments on #701 expressed the need for a RESTful implementation for accessing _section_ specific configuration values by paths like e.g. `/api/config/{SECTION}`.
In order to achieve this goal I extended the ApiController in such ways that a (skeleton) controller will be accessible at the `/api/configuration` endpoint which implements the needed HTTP GET/POST request handlers in https://github.com/doubleO8/e2openplugin-OpenWebif/tree/feature-configuration-rest-api-skeleton.

What remains to be done:

- add an implementation of _configuration data accessing and altering_ in `rest_api_controller.ConfigurationApiController`
- drop/alter/merge the following methods: `WebController.P_saveconfig`, `WebController.P_config` and `AjaxController.P_config` (There should be only one endpoint for handling configuration data)
- adjust Ajax call(s) on client implementation

> a real REST interface for the new /api/config?section=bla
should be
/api/config/bla
But i have no idea how to.

For `/api/configuration/SECTION` magic one may use the `postpath` attribute of a `Request` object.

**Comment by Schimmelreiter** [comment]
Please **test** your commits in the future ... currently about everything but the most basic functionality is broken:
One can no longer change settings in Extras -> Settings and the Package Manager was (is?) broken too.

**Comment by doubleO8** [comment]
First of all especially this changeset was intended merely as a **blueprint** for implementing configuration change operations in a sane way.
As for the entire REST API implementation: you guys were not forced to accept any of the changes :)

> currently about everything but the most basic functionality is broken:
One can no longer change settings in Extras -> Settings and the Package
> Manager was (is?) broken too.

I was under the impression that _master_ is where **any** (good, bad, ugly)
code contribution is being thrown at. At some point in time the current repository state is considered
"good enough" and tagged as release. So regressions would be acceptable
in this branch.

If this is not the case, why don't you document your development modus operandi either in the [readme](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/README.md) or in some sort of guideline for [repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) to make it easier for contributors?

Maybe you want to apply a different branching model where an unstable branch gets all the brave new contributions and another branch gets all changes after being thoroughly tested? (Have a look at [A successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/) where a really nice approach is described)


Any development progress being made comes with human errrors, breaking changes and regressions sometimes. So instead of whining about regressions write down your expectations (in words, as unit/regression test cases, anything...) and enforce them or just do not blindly merge pull requests :)


> Please test your commits in the future ...

Implying that contributors do not test their stuff will just alienate and keep them from sending patches. 
Personally I don't mind at all but others may do. For what it's worth changes I send are being tested actually twice a day:

The endpoints 

* `/api/getservices` 
* `/api/getservices?sRef=SOME_VALUE` 
* `/api/timerlist` 
* `/api/movielist` 
* `/api/powerstate?newstate=SOME_VALUE` 
* `/api/about` 
* `/api/zap?sRef=SOME_VALUE` 
* `/api/epgsearch?search=SOME_VALUE`

are being visited by a script which will send nasty emails to me if any of them is not working as expected.

As you may notice my focus is obviously not the '(save) settings' feature so it's a good thing that fellow testers did find the "POST not allowed" #706 regression.

_Suggested_ fix: #707 (DANGER, WILL ROBINSON: time for implementation+initial test was less than ten minutes)

**Comment by doubleO8** [comment]
fixed with #717
