### ISSUE TITLE
Package Manager broken after latest API changes

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#704]
Permanent spinner when opening Settings -> Packages

**Comment by jbleyel** [comment]
please check the result of 
/ipkg?command=listall

**Comment by Schimmelreiter** [comment]
You can't comment at this time — your comment is too long (maximum is 65536 characters).

Endless json output.

**Comment by Schimmelreiter** [comment]
It **looks** like a list of packages, so that doesn't seem to be the problem.

**Comment by jbleyel** [comment]
Then i need all other requests after you click on package.

**Comment by jbleyel** [comment]
i need only the request string after ip and port.

**Comment by Schimmelreiter** [comment]
?
What exactly do you need?

BTW: The error arose after double08 latest changes :)

**Comment by jbleyel** [comment]
@Schimmelreiter : please check again with the latest commit.
