### ISSUE TITLE
Changing Log settings causes 405 errors because POST is not allowed

### ISSUE THREAD

**Issue by peterurbanec** [E2OpenPlugins/e2openplugin-OpenWebif#706]
* Go to `Settings / Log Settings`
* Open web console in browser
* Change `Log Location`
* The web console will show a 405 error like this:

```
<html>
  <head><title>405 - Method Not Allowed</title></head>
  <body>
    <h1>Method Not Allowed</h1>
    <p>Your browser approached me (at /api/saveconfig?key=config.crash.debug_path&amp;value=/media/hdd/logs/) with the method "POST".  I only allow the methods HEAD, OPTIONS, GET here.</p>
  </body>
</html>
```

This was introduced sometime between 29 October 2017 and 10 November 2017

**Comment by jbleyel** [comment]
Hi @doubleO8 : please fix .. Thanks

**Comment by jbleyel** [comment]
closed with / https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/6235198a1d5dae2cee9a56badfddbe3d6c121860
