### ISSUE TITLE
Settings section is not working!

### ISSUE THREAD

**Issue by thawtes** [E2OpenPlugins/e2openplugin-OpenWebif#711]
Settings are not saved and there are no changes on e2?

model: vuduo2
image: openATV 6.1 (latest)

**Comment by Schimmelreiter** [comment]
I see no problem with settings not being saved in image 2017-11-12
Note that it **was** broken until 2017-11-11, so you really need todays upgrade.

Re-Open with more detail if the problem persists for you even after upgrade.
