### ISSUE TITLE
AutoTimer: Not able to create AutoTimers with type zap+record

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#712]
The drop down list for the record type only supports the types "zap" or "record", but not the type "zap+record".

**Comment by Schimmelreiter** [comment]
Perfekt.

Hatte ich fast genauso sogar schon vorbereitet, aber mich irgendwie doch nicht getraut ... vor allem weil ich ungern am JavaScript rummache, wegen uglify.

**Comment by jbleyel** [comment]
Kein Thema. War nicht wirklich ein Act. 5 Minuten und fertig. Aber nicht getestet. !!!

**Comment by Schimmelreiter** [comment]
Na das ist ja beruhigend ... :)
