### ISSUE TITLE
Missing webradio / IPTV channels when adding/modifying timers

### ISSUE THREAD

**Issue by hsteinme** [E2OpenPlugins/e2openplugin-OpenWebif#715]
I'm using a Vu+ Solo 4K box with VTI 11.0.2 image and OpenWebIf version 1.2.10. In my bouquets I've integrated some webradio channels, for instance the Swedish webradio of Sveriges Radio P2:

![p2](https://user-images.githubusercontent.com/33778564/32979031-dcc5e48e-cc4d-11e7-960a-983449a65b51.png)

Having a look at the bouquets overview in OpenWebif's main menue these webradio entries are displayed:

![openwebif_1](https://user-images.githubusercontent.com/33778564/32979075-ae381bb8-cc4e-11e7-80de-db3262a12629.png)

But when adding/modifying timers the webradio channels are not shown in the channel selector box:

![openwebif_2](https://user-images.githubusercontent.com/33778564/32979072-a2fe06a4-cc4e-11e7-804b-babe652e46ea.png)

Thus I don't have any chance to add webradio timers via OpenWebif.

**Comment by jbleyel** [comment]
Poste mal die Bouquet Datei von R: Web Radio.
Ich brauche nicht alle aber mindestens einen IPTV Sender + MDR Jump.
Die Datei liegt unter /etc/enigma2 und hat die Endung radio.

Allerdings stellt sich mir die Frage ob ein Timer von einem IPTV Sender überhaupt geht.

**Comment by hsteinme** [comment]
Here are the requested bouquet entries:

#NAME R: Web Radio
...
#SERVICE 4097:0:1:0:100D:0:0:0:0:0:http%3a//sverigesradio.se/topsy/direkt/163-hi-mp3:Sveriges Radio P2
#DESCRIPTION Sveriges Radio P2
...
#SERVICE 1:0:2:6F10:445:1:C00000:0:0:0::Test Satelliten-Sender: MDR JUMP
#DESCRIPTION Test Satelliten-Sender: MDR JUMP

Yes, the VU+ Solo 4K is really capable to deal with IPTV/webradio timers. I used it more than hundred times in the last 12 months - until mid of october. At this time I upgraded the box to VTI 11.0.2 containing the OpenWebIf with a new channel selection method in the adding/modifying timers popup box. Before this time webradio/IPTV channels could be assigned to timers via OpenWebif.

Today I'm forced to create webradio/IPTV timers directly at the box or via dreamEPG on Android.
