### ISSUE TITLE
Disable Terminal Access

### ISSUE THREAD

**Issue by Tony-il-Capo** [E2OpenPlugins/e2openplugin-OpenWebif#716]
Hi
I'm trying to disable Terminal access from OpenWebif, I'm running OpenATV 6.1, as it comes installed by default I can't simply uninstall (openwebif-terminal) package as it warns me openatv-enigma2 depends on it.

Is there a option to disable it without removing it?

**Comment by Schimmelreiter** [comment]
No way to just disable it.
You have to uninstall using --force-depends:
```opkg --force-depends remove enigma2-plugins-extensions-openwebif-terminal shellinaboxd ```

On the other side:
What do you hope to achieve?

You definitely **are** lost as soon as you open the OWIF to the outside world, it has never been optimized for security or rights management.
As soon as anyone gets access to it, he can do everything on your box, no matter what you do.

OWIF is and always was intended for use from inside a trusted LAN (or a trusted *real* VPN) **only**.
The only security considerations we do are to make it as unlikely as possible that it gets unintentially reachable from the outside.

Every toggle you could set to off - i.e. "disable terminal access" - could be set back to on by **anyone** with OWIF access.

**Comment by Tony-il-Capo** [comment]
> You definitely are lost as soon as you open the OWIF to the outside world, it has never been optimized for security or rights management.

I know, I never done it and never will, I don't expose anything to outside world and I always use OpenVPN to reach LAN

> What do you hope to achieve?

I just want to disable terminal access for LAN users to stop them making bad stuff to the stb, like they go to terminal and just write dangerous commands they don't really understand as a 'joke'!
I have SSH set to use keys, but root user as no password (default), but since terminal was added to OpenWebIf anyone can use it via web.

I thing it would be nice if we a had a option to (soft-)disable this. Maybe had it in the configuration plugin? Configuration files?

**Comment by Schimmelreiter** [comment]
There is no use in such an option:
Anyone could change that option ... even through OWIF.

See that you can remote control the box through the built-in remote in OWIF, so you can navigate through all the menus and set the option back to allowed.

If you have people doing nasty stuff to your box even in your LAN, then there is no other chance than
- to either lock everything down using login/password
or
- to beat them up to teach them not to do.

**Comment by Tony-il-Capo** [comment]
Okay, thanks for taking the time.
I think my best option is to remove terminal packages.

**Comment by Schimmelreiter** [comment]
Yes and no.
No, because anyone with access to OWIF or the box at all can just reinstall the package from feed.

**Comment by Schimmelreiter** [comment]
The "beat 'em up" suggestion might be the best solution 😁

**Comment by Schimmelreiter** [comment]
Or as an hommage to your nick:
Cement, nicely wrapped and hardened out around their feet and throwing them from a bridge definitely IS a final solution.
