### ISSUE TITLE
improvment wish by name Picons anzeigen

### ISSUE THREAD

**Issue by edelknecht** [E2OpenPlugins/e2openplugin-OpenWebif#718]
HI, vorab danke für das tolle OPenWebinterface Update für VTI Image. Sieht wirklich toll aus! Klasse Arbeit! 

Im VTI Image gibt es die Möglichkeit "by Name"Picons zu verwenden. Das Praktisch weil sich Sendername in der Regel nur selten ändern und "by Name"Picons gleichermaßen ohne Stress in Kabel, Sat und IPTV Kanallisten benutzen werden können. Sprich der Picon Renderer wurde erweitert so das Kanalreferenz Picons und zusätzlich auch Kanalname Picons ange

zeigt werden. Es wäre wunderbar wenn das Openwebinterface auch mit by name picons umgehen kann. Anbei paar by name Picons von Django. 
[HD Picons 100x60.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/1523902/HD.Picons.100x60.zip)
![byname_keine_anzeige](https://user-images.githubusercontent.com/13977492/33517051-1d6f00ee-d77d-11e7-899f-908aafffdbf3.jpg)
![sky1](https://user-images.githubusercontent.com/13977492/33517052-1d887132-d77d-11e7-9254-201396037fe4.jpg)
![sky1](https://user-images.githubusercontent.com/13977492/33517064-55d86966-d77d-11e7-8d8d-3c8ab9773bd0.jpg)

Danke

**Comment by Schimmelreiter** [comment]
Das ClosedWebif des GPL violator teams hat rein gar nichts mehr mit dem OWIF zu tun.
Wende Dich mit Bug Reports, Verbesserungsvorschlagen, etc. pp. an die GPL violator.

**Comment by edelknecht** [comment]
Oh sorry wusste ich nicht. Schade. Schönes Wochenende!

**Comment by jbleyel** [comment]
Ganz einfach. Gib mir den Source code vom VTi openwebif und ich bau das hier ein.

**Comment by Schimmelreiter** [comment]
Das GPL violator team hat sich den quelloffenen Code des OWIF und eines weiteren Projektes genommen und zu etwas anderem zusammengefügt, ohne die Änderungen wie von der GPL gefordert auch wieder öffentlich zu machen.
Wir haben also keinerlei Einfluß mehr auf das, was mit dem urheberrechtswidrigen Fork vom OWIF passiert.

**Comment by Schimmelreiter** [comment]
Übrigens ist auch schon die Ergänzung "Im VTI Image gibt es die Möglichkeit "by Name"Picons zu verwenden. " widerrechtlich aus GPL-lizensierten Projekten entnommen worden.
Die Änderung stammt aus OpenPLi oder einem anderen legalen enigma2-Projekt.

**Comment by edelknecht** [comment]
Ich steck da nicht drin. Wie gesagt tut mir leid. Wollte Euch nicht auf die Füsse treten. Wusste nicht das das neue Webinterface im VTI nicht von Euch ist. Nichts für Ungut. Auf jeden Fall gut das es Euch und nun auch das neue wirklich schicke VTI Webinterface gibt, MMn wurde viele Schwächen des Openwebinterface verbessert. Vielfalt ist gut. Und son by name Renderer entwickelt jeder x bieliebig Entwickler der was drauf hat 4 Minuten. Da von "entnommen" zu sprechen halte ich für falsch.

**Comment by Schimmelreiter** [comment]
4 Minuten hier, 4 Minuten da ...
Tatsache ist, daß dieses eine Team die x Mal 4 Minuten von *allen* klaut und selbst nichts zurückgibt.

**Comment by edelknecht** [comment]
Kann ich nichts zu sagen. Bin nur User, ist auf jeden Fall geil. Solltet Ihr Euch an schauen. Wer auch immer es weiter entwickelt hat hat ein Auge für Schönheit und richtig Ahnung.
