### ISSUE TITLE
Openwebif missing date notation in EPG

### ISSUE THREAD

**Issue by dutchdreamer** [E2OpenPlugins/e2openplugin-OpenWebif#719]
When i open epg in openwebif (new Style) i can select week number > select weekday

When i select "Timeline" the date is shown (So,12.03)

When i select "TV Gide" there is NO date shown.

Can this be fixed?

**Comment by jbleyel** [comment]
Screenshot please

**Comment by dutchdreamer** [comment]
![date 1](https://user-images.githubusercontent.com/9933169/33525940-12e14c7e-d839-11e7-9c0c-a461bac7ae5f.jpg)
![date 2](https://user-images.githubusercontent.com/9933169/33525941-12feb9d0-d839-11e7-81e7-a8861c3a2244.jpg)

**Comment by jbleyel** [comment]
okay. understud .. no one have missed this before
