### ISSUE TITLE
problem with UTF-8 encoding for JSON on some boxes

### ISSUE THREAD

**Issue by ssbmaccom** [E2OpenPlugins/e2openplugin-OpenWebif#720]
Hi,

I have seen an issue on some Enigma 2 boxes. Most regular on BlackHole images, but sometime also on other images.
When opening <IPOfBox>/api/about in a browser, they receive a Python backtrace mentioning, that the character 0xb2 is not a valid UTF-8 character. 0xb2 is the superscript 2.
I searched the source code and found in owibranding.py line 169, that the 2 in Solo 2 is replaced with the superscript 2:
`		model = procmodel.title().replace("olose", "olo SE").replace("olo2se", "olo2 SE").replace("2", "²")
`
I don't know, why this works on some boxes, while it fails on others.
But maybe the source files are compiled either as UTF-8 on most boxes, while on some it is read as ASCII/latin-1.

Maybe this problem can be solved by changing the string in the last replace() call to u"\u00b2" - which makes sure, that the UTF-8 compatible superscript 2 is used.

**Comment by jbleyel** [comment]
Please test your suggestion within an affected image.
I don't think that's the solution.

You will get the same exception if you call this
`replace("2", "²")`
or that
`replace("2", u"\u00b2")`
cause of the procmodel.title is not UTF8
