### ISSUE TITLE
Future of WebTV

### ISSUE THREAD

**Issue by Schimmelreiter** [E2OpenPlugins/e2openplugin-OpenWebif#723]
Latest releases of Firefox removed support for NPAPI plugins entirely, so I guess WebTV doesn't work in Firefox 57.x and up anymore.

There is still a Firefox 52.x ESR version that gets security updates, so for the moment, one can still have WebTV in Firefox without using versions that are out of support.
Firefox 57.x ESR is projected to be supported until July 3, 2018.
It is also the last version that officially supports Windows XP and Vista (Firefox even automatically upgraded to 52.x ESR instead of later regular versions on those systems).

As Firefox p*ssed of a lot of plugin developers with this step, I expect quite some part of the users to "down"grade to this ESR version for the moment, as also important other plugins like Greasemonkey, VideoDownloadHelper, DownThemAll and so on are affected.

So for the moment, we should just keep the WebTV support, at least until 3rd of July 2018.

----

But also Chrome seems to undergo certain changes that will make VXG stop working, VXG Inc. has posted the following on the OpenPLi forum:
> Hi guys,

> We've had many people message us about our VXG Chrome Plug-in from this thread. As you may have noticed, browsers have slowly been removing third party plugins. This appears to be happening with VXG Chrome Plug-in as well.

> Noticing this trend, our engineering team have developed a solution that will work in all major browsers, without a plugin. If you visit our website - www.videoexpertsgroup.com (http://www.videoexpertsgroup.com/) and sign up for our dashboard, you will be given the option to download something called the VXG Gateway. This seems to be an adequate substitution for our Plug-in customers.

> Feel free to email us at expert@videoexpertsgroup.com (mailto:expert@videoexpertsgroup.com)
Thanks.

I've contacted VXG about VXG Gateway and asked if that can be a solution for our OWIF running on an embedded system with limited CPU power and am awaiting their response.

This issue is there to have a place to discuss the future of the built-in WebTV and possible solutions.

**Comment by kavillock** [comment]
maybe its possible to use transcoding (for suitably strong boxes) to use html5 video?

**Comment by Guenni75** [comment]
WHY VXG Player???? The worst web player ever.

**Comment by Schimmelreiter** [comment]
Which of the many alternatives do you want to see supported?

**Comment by thawtes** [comment]
I think webtv should be able to work without the need for additional 3rd party application (VXG)
is it possible to work using only JS and HTML5?

**Comment by Schimmelreiter** [comment]
> is it possible to work using only JS and HTML5?
No.
Next suggestion.

**Comment by thawtes** [comment]
> Next suggestion.

create a local streaming server?
for example can ffserver be installed?
can be streamed via ffserver
but I have no idea how much this can be.

**Comment by Schimmelreiter** [comment]
The problem is, that most if not all boxes don't have the power to transcode to anything HTML5-compliant.
Transcoding to anything else makes no sense, as we already have that in any E2.

**Comment by Schimmelreiter** [comment]
The problem is, that most if not all boxes don't have the power to transcode to anything HTML5-compliant.
Transcoding to anything else makes no sense, as we already have that in any E2.

**Comment by Schimmelreiter** [comment]
So ... next suggestion.
I heard there is a myriad of alternatives ...

**Comment by thawtes** [comment]
> 
> 
> So ... next suggestion.
> I heard there is a myriad of alternatives ...

the purpose is not video transcoding
getting correct MIME type
if we can get the mime type correctly
html5 video player will work.

**Comment by thawtes** [comment]
> 
> 
> So ... next suggestion.
> I heard there is a myriad of alternatives ...

the purpose is not video transcoding
getting correct MIME type
if we can get the mime type correctly
html5 video player will work.

**Comment by Schimmelreiter** [comment]
HTML5 only supports a limited set of codecs, MPEG2 is not one of them.

**Comment by jbleyel** [comment]
Hi @thawtes, what's the exact purpose?
What device do you use for WebTV?
iPhone/iPad, Windows, Linux, Mac, Android
There is a working alternative for all these clients.

**Comment by thawtes** [comment]
> 
> 
> Hi @thawtes, what's the exact purpose?
> What device do you use for WebTV?
> iPhone/iPad, Windows, Linux, Mac, Android
> There is a working alternative for all these clients.

hi @jbleyel 
what is working alternative?

**Comment by Schimmelreiter** [comment]
To use normal streaming ...

**Comment by thawtes** [comment]
of course :)

I will try an application that can be a solution for HTML Player
I will give feedback if it works ...

**Comment by thawtes** [comment]
I don't use webtv because I don't need it..
for users who want to use webtv, I try to help ...

**Comment by jbleyel** [comment]
Windows -> dreamboxedit, ...
iPhone/iPad -> e2Remote, ...
Android -> Dreamdroid, ..
Mac -> e2Remote (comming soon)
Linux -> ?

**Comment by thawtes** [comment]
> 
> 
> Windows -> dreamboxedit, ...
> iPhone/iPad -> e2Remote, ...
> Android -> Dreamdroid, ..
> Mac -> e2Remote (comming soon)
> Linux -> ?

I agree with you.
I use it this way.
so I'm using normal streaming with the apps you said
I thought the alternative said for openwebif webtv.

**Comment by jbleyel** [comment]
No, there is no real alternative for the WebTV in a browser.
But there are alternatives for the purpose.

**Comment by jbleyel** [comment]
continue here -> #1423

**Comment by wedebe** [comment]
So 4 years after the original post, does anyone actually have WebTV working in any browser?

@jbleyel and I started investigating the removal of the plugin with a view to directing users on how to install it manually. The vast majority of users will never use the feature yet it adds at least 1MB to every image with OpenWebif installed.

**Comment by jbleyel** [comment]
This needs to be done in the bb file on the Buildserver.

@Schimmelreiter can give you more info how to use vxg.
