### ISSUE TITLE
EPG search drops channels with too many hits

### ISSUE THREAD

**Issue by Stomme** [E2OpenPlugins/e2openplugin-OpenWebif#724]
The search results of the EPG search (ctrl-f) drops channels with a large amount of occurrences of the program searched for.  Using vu+ with VTI image OWIF 1.2.8

E.g. searching for "Teleshopping" channels like "ANIXE HD" comes up, but channels like "Sport1" or "5 USA" are not listed.

Other examples are "NCIS" or „Law & Order: Special Victims Unit“ 
tried both classic and new layout.
![epg](https://user-images.githubusercontent.com/34748527/34266174-8cbf82b6-e678-11e7-9d24-9f50ce6dc3cd.PNG)
![search result](https://user-images.githubusercontent.com/34748527/34266175-8ce08a74-e678-11e7-929d-453c858e4279.PNG)

**Comment by atvcaptain** [comment]
vti use his own version of this plugin , send bug report direct to the vti team
