### ISSUE TITLE
Improvement - android

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#727]
As I saw, under Android should be good add some basic remote controller too - I did not found it.

**Comment by jbleyel** [comment]
The new responsive design should be your choice.

**Comment by ims21** [comment]
?

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/responsive

**Comment by jbleyel** [comment]
Can we close this?
