### ISSUE TITLE
Enigma2 Ipbox 55 hd

### ISSUE THREAD

**Issue by stzokev** [E2OpenPlugins/e2openplugin-OpenWebif#729]
I am trying to install OpenWebif on Ipbox 55hd and in fact the installation goes through fine. However, upon opening plugins menu, I get error: Some plugins are not available: Extensions/OpenWebif (No module named ipaddress). I've already found a thread that I should install python ipaddress module, but it just ain't working here:
ipbox55:# opkg install python-ipaddress
Unknown package 'python-ipaddress'.
Collected errors:
 * opkg_install_cmd: Cannot install package python-ipaddress.

I've tried to install it manually from https://pypi.python.org/pypi/ but get different errors:

ipbox55:/tmp/backport_ipaddress-0.1# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

ipbox55:/tmp/ipaddress-1.0.19# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from distutils.core import setup
ImportError: No module named distutils.core

Any suggestions are welcome!

**Comment by Schimmelreiter** [comment]
What distro?
The distro teams are the only ones which can realistically offer such modules on their feeds.

Maybe it will work if you take the package from another distro and install it on your image, but not all packages can be interchanged between distros.

Anyway:
Not an OWIF issue.

**Comment by stzokev** [comment]
That is the thing ... it is in the feed of the distro itself but it cannot install .. Distro is PKT Hyperion 5.5 and version of OpenWebif offered in feed is 1.2.7

**Comment by Schimmelreiter** [comment]
Then you need to ask PKT to include python-ipaddress on their feed.

**Comment by stzokev** [comment]
Thank you for the help so far and sorry for bothering for something clearly not your problem. PKT team are polish and no english posts are welcome, other people have tried, no help has been offered. 

One last question if I may: do you know which is the last version of OpenWebif that does not require ipaddress module, so I can search for it instead?

**Comment by Schimmelreiter** [comment]
Uhm, we added that ages ago ... no idea when, sorry.
