### ISSUE TITLE
file.py allows download of any file

### ISSUE THREAD

**Issue by AxelNennker** [E2OpenPlugins/e2openplugin-OpenWebif#731]
Is it a feature that file.py allows the download of any file e.g. /etc/shadow ?
https://vuabc.dyndns.de/file?action=download&file=/etc/shadow 
I tried this on my vuplus which is accessible on the Internet.

I think it would be more secure to limit file download to the movies directory 

I don't know enough about e2 to write correct code here but I think a "fix" could look like this:

```python
if not os.path.dirname(filename) == "/media/hdd/movies":
    return "forbidden"
```

"real" code would check for the directory as configured from a config file and would a HTTP 403.

kind regards
Axel

**Comment by jbleyel** [comment]
This is well known.
Only include /media/hdd/movie is not an option.
There are much more folders.

PS: If you have access to the box via webinterface you will also have full access to the box.

**Comment by jbleyel** [comment]
We can do one quick fix.
exclude /etc but include /etc/enigma2/
and exclude some more system folders

**Comment by Schimmelreiter** [comment]
I think access to anything was once added for some box-2-box interoperability plugin.

We can't repeat it often enough: Access to the Webif grants access to anything in the end, so never open OWIF to the outside world.

**Comment by AxelNennker** [comment]
My box is located 400km west of my home because only there I can receive the satellite I want.
I enabled auth and ssl permanently by editing the config file. The vusolose otherwise forgot these settings on reboot. So the box is somewhat protected although port 443 is forwarded by the Internet router.
I am enabling/disabling the port forwarding when I need it by creating a SSH forwarding to the Internet router admin interface through the vusolose.

Still, me jumping through all these loops is not this discussion: Which steps can be done to make openwebif more secure? 
Preventing the download of /etc/shadow would be one step that hopefully does not break plugins/apps or box-to-box interoperability?!

A blacklist might be one way to do this.
Sprinkling something like .htaccess file over the file system is probably too ugly.
Can something be done or is the danger to break things too big?

**Comment by edelknecht** [comment]
Use VPN. Opening ports is not recommended. Dont ask for fixes that Limit Users because you are to lazy to implement proper security.

**Comment by AxelNennker** [comment]
I have setup openvpn but that does not change that every "guest" in my local network can access the box. This issue is not about remotely accessing openwebif but whether openwebif should make the user almighty.

Sorry the remote access topic was a distraction.

I think access to media files is OK through openwebif while access to system files is not.
It seems @Schimmelreiter disagrees.
I learned that plugins on the box use the openwebif for all kind of purposes and that restricting this will break apps. So it seems there is not much that can't be done without doing a major overhaul of the interface which is unlikely to happen. 

Most users do not enable SSL and they don't setup auth.
Setting these in the UI does not make them permanent - so these settings do not survive a reboot.

I think that defining the local network as secure is a comfortable lie.
Many users share their Wifi password with friends and now all those devices likely have too much access to the box. Maybe openwebif is then not the user's most severe problem.

Thanks for the discussion.

**Comment by edelknecht** [comment]
If it’s important to you buy proper router that allows VPN configuration and guest Wifi like Fritzbox. Dont forward ports to your box! Its only a matter of time until your box will be hacked and used for crime.

**Comment by AxelNennker** [comment]
Deviating from the issue from the issue whether openwebif should be all powerfull, e.g. by running as root, or allowing system file to be accessed etc... Would you @edelknecht deam a VU+ box running openvpn as secure enough. I have to let UDP 1194 through the router though because that one is not a vpn server.

Coming back to the issue of openwebif to be a atom bomb in the hand of the layman, it seems there can nothing be done about that. Closing this issue. 
Thanks for the discussion.

**Comment by Schimmelreiter** [comment]
> I think that defining the local network as secure is a comfortable lie.

Well, I agree with that.
I've also had made changes to OWIF in the apast to make it a bit more secure, but they got reverted.
The E2 community lives in a magic wonderland, where the own LAN is always secure and there shouldn't be any second line of defense if someone manages to enter the LAN (e.g. by hacking into the WiFi).

There are also never ever any children that at some time should still be kept out by the youth protection pin but are better at circumventing it than the adult user is at setting it up.

The very first time I had a look at the mentioned plugin (I think it does channel sync, it converts the channel list of the one box into an IPTV list on the second one), I just wondered "Why? *Why?*".

Though, I can't change it.
I can not change that people are still stuck in the 90s when they setup the network of their E2 box and I can't keep people from turning E2 boxes into routers. I can neither implement better security in OWIF as long as it breaks silly written plugins. I can't keep people from making silly changes in config, breaking things and then complaining x or y won't work anymore.

To a certain degree, even we devs are restricted to how large the horizon of users and other devs is.

**Comment by AxelNennker** [comment]
A blacklist containing a python pattern matching expression to exclude system files appears to be a minimally invasive step to more security.

re.search(blacklist_pattern, filename)

Another doable step could be to run the HTTP server as a new user "openwebif" and transfer ownership of needed files to that user. Then the OS would take care of permissions.
But it is not unlikely that I underestimate the problem...

But if people believe that all hope is lost anyway then even small steps would be in vain...

**Comment by Schimmelreiter** [comment]
OWIF isn't a standalone process but only a script running inside E2, which is running (and needs to run) as root, due to previous design faults, which can not be made undone without breaking everything.

And sadly in the eyes of the users even the worst and most useless plugin(s) still beats any security consideration.
