### ISSUE TITLE
Streaming audio from a tv-channel

### ISSUE THREAD

**Issue by formtapez** [E2OpenPlugins/e2openplugin-OpenWebif#736]
On Enigma1-boxes it was possible to stream audio-only from a tv-channel by just selecting the audio-PID in the stream-URL.

Can we have such feature again?

**Comment by jbleyel** [comment]
Not here.
You need a player with Audio only playback option.
The stream have always audio and video.

A special transcoding feature can be a solution but this is also not part of openwebif.
