### ISSUE TITLE
Problem with display of current channel information in new design.

### ISSUE THREAD

**Issue by mickeyreg** [E2OpenPlugins/e2openplugin-OpenWebif#739]
OpenWebif 1.3.0 (responsive branch).
New design active.
Polish translation active.

When I'm trying to display current channel information OpenWebif in the browser shows spinner and nothing is displayed. In enigma2 log I can see:

> Unhandled Error
> Traceback (most recent call last):
>   File "./protocols/basic.py", line 571, in dataReceived
>   File "./web/http.py", line 2013, in lineReceived
>   File "./web/http.py", line 2104, in allContentReceived
>   File "./web/http.py", line 866, in requestReceived
> --- \<exception caught here\> ---
>   File "./web/server.py", line 195, in process
>   File "./web/server.py", line 255, in render
>   File "./controllers/base.py", line 195, in render
>   File "./controllers/base.py", line 97, in loadTemplate
>   File "/usr/lib/python2.7/site-packages/Cheetah/Template.py", line 1005, in \_\_str\_\_
>   File "_usr_lib_enigma2_python_Plugins_Extensions_OpenWebif_controllers_views_responsive_ajax_current_tmpl.py", line 268, in respond
> exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 17: ordinal not in range(128)

Maybe the problem is specific to my configuration an is not caused by OpenWebif, but I have no idea where to start searching for the solution :(

When nothing is diplayed (tuner in standby) the Current site is displayed properly.
When "new design" is disabled also Current works properly.

**Comment by jbleyel** [comment]
It's the long description of current channel

This is the line of the "normal" design
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/views/ajax/current.tmpl#L202

This is the line of the "new" design
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/views/responsive/ajax/current.tmpl#L88

This is line 268
`
        _v = VFN(VFN(VFFSL(SL,"getVar",False)("now.longdesc", " "),"replace",False)("\n","<br/>"),"replace",False)(u"\u008a","<br/>") # u'$getVar("now.longdesc", " ").replace("\\n","<br/>").replace(u"\\u008a","<br/>")' on line 88, col 77`


Don't ask my why?

**Comment by jbleyel** [comment]
this
`replace(u"\\u008a","<br/>")
`
or that
`replace("\\n","<br/>")
`

**Comment by jbleyel** [comment]
The current epg long description will be converted to UTF-8 here ->

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/services.py#L591

and here ->

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/services.py#L52

Therefore you don't have the latest version or we have a strange issue here.

Please check again with the latest git version.
