### ISSUE TITLE
No transcoding icon?

### ISSUE THREAD

**Issue by casperse** [E2OpenPlugins/e2openplugin-OpenWebif#740]
Box: Vu+ Uno 4k SE
OE system: | PLi-OE
Firmware version: | OpenPLi 6.1-release (2018-01-07-release-6.1)
Kernel / Driver versionsdato: | 4.1.20 / 4.1.20-20171222.r0.0
OpenWebif : Version: OWIF 1.2.8

For some reason it will only show the icon for streaming without encoding?
For some reason OpenWebif does not recognize that transcoding is supported by this box
and I have confirmed its working! just not any icon with a link?

**Comment by jbleyel** [comment]
Please check if this file exists: 
/proc/stb/encoder/0/bitrate

If not then we have a problem.

Then check if one of these files exists: !! CASE INTENSIVE !!
/usr/lib/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo
/usr/lib/enigma2/python/Plugins/SystemPlugins/TranscodingSetup/plugin.pyo
/usr/lib/enigma2/python/Plugins/SystemPlugins/MultiTransCodingSetup/plugin.pyo

If not then provide your full path of the transcoding setup.

**Comment by casperse** [comment]
> Please check if this file exists:
> /proc/stb/encoder/0/bitrate
**Yes the file exists, but is zero in size**

> Then check if one of these files exists: !! CASE INTENSIVE !!
> /usr/lib/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo
No folder with TransCodingSetup (capitol C) but both files is in the TranscodingSetup folder
> /usr/lib/enigma2/python/Plugins/SystemPlugins/TranscodingSetup/plugin.pyo
YES
> /usr/lib/enigma2/python/Plugins/SystemPlugins/MultiTransCodingSetup/plugin.pyo
NO the above folder dosent exist?

Best regards
Casperse

**Comment by jbleyel** [comment]
You have possibly an issue in this line.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/ad02caa0cb546e156542ba8e0a87ed8939cfb539/plugin/controllers/models/info.py#L538
Don't ask me why.

**Comment by casperse** [comment]
I checked the file and its:
`# TODO: fstab

	info['transcoding'] = False
	#: models transcoding feature
	TC_MODELS = (
		"Uno4K", "Uno4K SE", "Ultimo4K", "Solo4K", "Solo²", "Duo²", "Solo SE",
		"Quad", "Quad Plus"
	)

	#: machinebuilds transcoding feature
	TC_MACHINEBUILD = (
		'inihdp', 'hd2400', 'et10000', 'et13000', 'sf5008', 'xpeedlx3',
		'ew7356', 'dags7356', 'dags7252', 'formuler1tc', 'gb7356', 'gb7252',
		'tiviaraplus', '8100s'
	)

	if info['model'] in TC_MODELS or info['machinebuild'] in TC_MACHINEBUILD:
		if os.path.exists(eEnv.resolve('${libdir}/enigma2/python/Plugins/SystemPlugins/TransCodingSetup/plugin.pyo')) or os.path.exists(eEnv.resolve('${libdir}/enigma2/python/Plugins/SystemPlugins/TranscodingSetup/plugin.pyo')) or os.path.exists(eEnv.resolve('${libdir}/enigma2/python/Plugins/SystemPlugins/MultiTransCodingSetup/plugin.pyo')):
			info['transcoding'] = True
`

**Comment by casperse** [comment]
So are you saying this line is missing?

**Comment by jbleyel** [comment]
No the line is not missing, you have a modified or old file on your box.

**Comment by casperse** [comment]
But the file is from the latest Openpli official supported image and its list all the box models that are compliant to transcode.
Can I overwrite the file with a new one? Sorry this is a little beyond my skill level. I also tried installing the newest packae of OpenWebif but without resolving the problem.

**Comment by jbleyel** [comment]
You can change this line
if info['model'] in TC_MODELS or info['machinebuild'] in TC_MACHINEBUILD:
to this
if fileExists("/proc/stb/encoder/0/bitrate"): 

PLI don't use the latest version of this file.

**Comment by casperse** [comment]
GREAT - NOW IT WORKS!!!! Thanks this have been driving me crazy....

**Comment by casperse** [comment]
Wait the link from the transcode icon is wrong, it uses 8001 and not 8002 so I got the icon back but the link is not the trancoded one

**Comment by jbleyel** [comment]
You need to change some more, but this needs to be done by the PLI team.

**Comment by WanWizard** [comment]
We have to do what where?

OpenWebIf in OpenPLi is directly built from this master branch?

**Comment by jbleyel** [comment]
Hi @WanWizard, this is what i thought.
Hi @casperse, you have an old version.

**Comment by WanWizard** [comment]
Problem seems to be the version wasn't bumped in OpenPLi 6.1-release, so our fault. 6.2 is due any day, and will be up to date again.
