### ISSUE TITLE
OpenWebIF zeigt falschen Freien HDD Speicherplatz an

### ISSUE THREAD

**Issue by LevelOne2k** [E2OpenPlugins/e2openplugin-OpenWebif#741]
Das OpenWebIF zeigt eine große Differenz von freien Festplattenspeicher an.

VTi Systeminformationen zeigen an: 34.4 GB freier Festplattenspeicher.

Konsole "df -h" gibt aus: 34.4G freier Festplattenspeicher.

OpenWebIF zeigt an: 53.0 GB freier Festplattenspeicher.

**Comment by jbleyel** [comment]
bitte folgendes machen.
mit telnet oder ssh verbinden
dann 
`python`
dann 
`import os`
dann 
`print os.statvfs('/dev/sda1')` 

Dann die Ausgabe hier posten.
Bei /dev/sda1 muss natürlich die Platte rein um die es geht.

**Comment by LevelOne2k** [comment]
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=168180L, f_bfree=168180L, f_bavail=168180L, f_files=87787L, f_ffree=87218L, f_favail=87218L, f_flag=4096, f_namemax=255)

**Comment by jbleyel** [comment]
mein Fehler
noch mal:
```
python
import os
stat = os.statvfs('/media/hdd')
print int((stat.f_bfree/1024) * (stat.f_bsize/1024))

```

Wenn es um /media/hdd geht.

**Comment by LevelOne2k** [comment]
`root@vuultimo4k:~# python
Python 2.7.9 (default, Nov 14 2017, 18:15:52) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> stat = os.statvfs('/media/hdd')
>>> print int((stat.f_bfree/1024) * (stat.f_bsize/1024))
54120`

**Comment by LevelOne2k** [comment]
Da kommt dann 54120 raus

**Comment by doubleO8** [comment]
The function `statvfs()` returns information about a **mounted file system**. [[linux.die.net/man/2/statvfs](https://linux.die.net/man/2/statvfs)]
Thus calling `os.statvfs('/dev/sda1')` will return unexpected results.

```
struct statvfs {
    unsigned long  f_bsize;    /* file system block size */
    unsigned long  f_frsize;   /* fragment size */
    fsblkcnt_t     f_blocks;   /* size of fs in f_frsize units */
    fsblkcnt_t     f_bfree;    /* # free blocks */
    fsblkcnt_t     f_bavail;   /* # free blocks for unprivileged users */
    fsfilcnt_t     f_files;    /* # inodes */
    fsfilcnt_t     f_ffree;    /* # free inodes */
    fsfilcnt_t     f_favail;   /* # free inodes for unprivileged users */
    unsigned long  f_fsid;     /* file system ID */
    unsigned long  f_flag;     /* mount flags */
    unsigned long  f_namemax;  /* maximum filename length */
};
```

```
# df -h output example
Filesystem                          Size  Used Avail Use% Mounted on
[...]
/dev/sda1                            35G   32G  1.7G  96% /
```

```
# python code example
>>> s = os.statvfs("/")
>>> avail_bytes = s.f_bavail * s.f_bsize
>>> avail_bytes
1746116608
>>> float(avail_bytes) / 10**9 # Gigabyte
1.746116608
>>> float(avail_bytes) / 2**30 # Gibibyte
1.6261978149414062
```
(one might use `f_bfree` here as we are root anyway)

byte values conversion table [de.wikipedia.org/wiki/Byte#Vergleichstabelle](https://de.wikipedia.org/wiki/Byte#Vergleichstabelle)

**Comment by LevelOne2k** [comment]
Und was heißt das jetzt?

**Comment by jbleyel** [comment]
Wenn bei statvfs für /media/hdd bei deiner Box 54120 (53 GB) raus kommt, dann stimmt was mit deiner Box nicht, denn genau diese Funktion wird vom openwebif benutzt.
Was genau kann ich nicht sagen.
Sorry

**Comment by LevelOne2k** [comment]
Und was genau soll mit der Box nicht stimmen? Auf meiner anderen Box und bei bekannten gibt es auch Abweichungen.

**Comment by jbleyel** [comment]
Ich wollte sagen, da stimmt was anderes mit der Box nicht bzw. mit der Funktion
Keine Ahnung, warum statvfs einen falschen Wert liefert.
Die statvfs Funktion um den freien Plattenplatz zu nutzen hat nix mit dem openwebif zu tun.

**Comment by doubleO8** [comment]
As shown in example above, `df`seems to be using the **f_bavail** member, while the OpenWebif is using the **f_bfree** member in order to compute the free disk space value.

So .. **not** an issue/error, no _broken_ device, no _wrong_ values being returned by `statvfs` - just different approaches and side effects of linux/ext4 internals.

**Comment by AdlerCentauri** [comment]
Bei mir wird auch eine andere Zahl im OpenWebIF angegeben als in Wirklichkeit belegt/frei ist. 

Das OpenWebIF zeit an: 442.2 GB

Der Receiver zeigt an: 423.6G

Warum ist das so?

**Comment by Schimmelreiter** [comment]
Weil E2 stellenweise falsch rechnet.

**Comment by AdlerCentauri** [comment]
Also das OpenWebIF zeigt es richtig und das E2 falsch oder wie muss ich das verstehen?

**Comment by jbleyel** [comment]
Das openwebif nutzt python os.statvfs .

Hierrmit kann man das testen. 
```
import os
stat = os.statvfs('/media/hdd')
print int((stat.f_bfree/1024) * (stat.f_bsize/1024))

```
Wenn da falsche Werte raus kommen, dann ist der Fehler in python.

OpenATV E2 Timeshift nutzt diese function
freespace = stat.f_bfree / 1000 * stat.f_bsize / 1000

OpenATV Software Manager Image Backup:
space = (statdev.f_bavail * statdev.f_frsize) / 1024

Flash Online:
space = (statdev.f_bavail * statdev.f_frsize) / 1024

Record Timer:
s = os.statvfs(dirname)
(s.f_bavail * s.f_bsize) / 1000000

Info Panel:
df -h ( das machen wir im openwebif ganz sicher nicht)

**Comment by jbleyel** [comment]
Wenn man die Doku von statvfs mal genauer liest, dann sieht man das Problem.
https://docs.python.org/2/library/statvfs.html

**Comment by AdlerCentauri** [comment]
Und wer zeigt mir nun den richtigen freien Speicher an?

**Comment by jbleyel** [comment]
Beide.. Abhängig von dem was man wissen will.
Steht doch in der Doku.
Es gibt auch noch Rundungsfehler.

**Comment by AdlerCentauri** [comment]
Wie kann denn beide richtig sein?

Das OpenWebIF zeit an: 442.2 GB

Der Receiver zeigt an: 423.6G

Entweder habe ich 443GB frei oder 423GB

**Comment by Schimmelreiter** [comment]
Von wieviel ingesamt?

Es gibt mehrere mögliche Abweichungen:
1. Je nachdem, wie man formatiert, werden 5% des Platzes für den Benutzer root reserviert und dann je nach verwendeter Funktion nicht als verfügbar angezeigt.
2. E2 rechnet an einigen Stellen mit 1000 Bytes pro kB, obwohl es 1024 Bytes sein müßten.
Das machen die Festplattenhersteller zwar auch (Eine Festplatte die mit 1 TB beworben wird, hat in Wirklichkeit nur 930 GB), nachträglich haben die Hersteller für diesen Betrug zwar den Segen der Elektriker (IEC) bekommen, was aber eben nichts dran ändert, daß nur 930 GB drauf passen.

**Comment by AdlerCentauri** [comment]
383.1 GB frei / 1.8 TB ("2 TB") insgesamt (/media/hdd)

**Comment by jbleyel** [comment]
Bitte das mit python testen:

```
import os
stat = os.statvfs('/media/hdd')
print stat.f_bfree * stat.f_bsize / 1024. / 1024. / 1024.
print stat.f_bavail * stat.f_frsize / 1024. / 1024. / 1024.

```

und dann noch in der console das da
df -h /media/hdd

Den output hier posten.

**Comment by AdlerCentauri** [comment]
root@vuultimo4k:~# import os
-sh: import: command not found

**Comment by jbleyel** [comment]
das ist python code da muss man vorher schon python starten

**Comment by AdlerCentauri** [comment]
Ja und wie?

**Comment by jbleyel** [comment]
https://www.google.de/search?q=how+to+start+python+shell&oq=how+to+start+python

**Comment by koivo** [comment]
Steht doch auch oben im zweiten Beitrag.

**Comment by AdlerCentauri** [comment]
>>> print stat.f_bfree * stat.f_bsize / 1024. / 1024. / 1024.
374.110641479

>>> print stat.f_bavail * stat.f_frsize / 1024. / 1024. / 1024.
355.464851379

Filesystem                Size      Used Available Use% Mounted on
/dev/sda1                 1.8T      1.5T    355.4G  81% /media/hdd

**Comment by jbleyel** [comment]
Danke ich bau das um.

**Comment by AdlerCentauri** [comment]
Danke für die Unterstützung. Gibst du ein Feedback wenn es umgebaut ist?

**Comment by Schimmelreiter** [comment]
Eigentlich sollten die beiden Zahlenwerte (nahezu) identisch sein:
```>>> print stat.f_bfree * stat.f_bsize / 1024. / 1024. / 1024.
77.0179252625
>>> print stat.f_bavail * stat.f_frsize / 1024. / 1024. / 1024.
77.0179252625```

Wenn sie es nicht sind, wurde das Medium eingeeignet formatiert.
