### ISSUE TITLE
missing remote control image

### ISSUE THREAD

**Issue by s3n0** [E2OpenPlugins/e2openplugin-OpenWebif#756]
Hello.

When I click on the button to open the zoomed RC, the RC image will not be displayed (empty space). I have checked the presence of two files - the PNG image and the HTML website for "formuler1" (used for my Formuler F3 device), and there are both:
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/public/images/remotes/formuler1.png
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/public/static/remotes/formuler1.html

My set-top-box is Formuler-F3 with OpenATV 6.1 image. If I need to provide some DebugLOG or debug code from a web page (I use Mozilla Firefox), I can provide them. I do not know well about website programming, so in this case I will ask for instructions.

Does anyone know what to do ? Is this a BUG ? 

Thanks.

![missing_image_of_the_rc](https://user-images.githubusercontent.com/13181404/35711157-bdf8ad1c-07bb-11e8-967a-61addabcba4d.png)

**Comment by s3n0** [comment]
So I uninstalled OpenWebif through "-force-removal-of-dependent-packages". I installed it again, including its addictions, but I used the installer from the OpenATV 6.1 feed and again I see the remote control.

When uninstalling OpenWebif with "force-removal-of-dependent-packages", the "oe-alliance-enigma2" package was also removed. So I had to go back to install it. :-)

I tried to remove OpenWebif also with "--autorem" parameter, and it did remove the python-cheetah and python-misc packages.

The problem with the remote control has been resolved... however, I'm working on OpenATV OpenWebif now.

The error will, IMHO, somewhere in device detection / branding.

**Comment by jbleyel** [comment]
I think this is a image build issue and here is not the right place for that.

**Comment by s3n0** [comment]
Well thank you.

It's okay now. It does not matter. I use OpenWebif from OpenATV and this works correctly.

When I install OpenWebif - the original, then I do not see the remote control. I did not find out why this is happening - neither on this GitHub nor on the OpenATV discussion. I'm glad it works. Apparently, this is a minor bug in the OpenATV image.

**Comment by arn354** [comment]
Which original openWebif do you refer to?
If you run openatv (or any other oe-a image) you have to use the version from the feeds. On build of a oe-a image remote-control related stuff gets added to the openwebif package.

What are you trying to achieve?

**Comment by s3n0** [comment]
Yup... I know.

The content of the OpenATV feed-server does not have the same OpenWebif as the GitHub OpenWebif server (ipk package). In addition, there are some additional OpenWebif packages available on OpenATV feed-servers:
```
root@formuler3:~# opkg list | grep webif
enigma2-plugin-extensions-openwebif - 1.3.0+git3026+706a140-r0 - extensions-openwebif
 extensions-openwebif
enigma2-plugin-extensions-openwebif-terminal - 1.3.0+git3026+706a140-r0 - enigma2-plugin-extensions-openwebif version 1.3.0+gitAUTOINC+706a14066e-r0
enigma2-plugin-extensions-openwebif-themes - 1.3.0+git3026+706a140-r0 - extensions-openwebif (Additional themes for OpenWebif)
 extensions-openwebif (Additional themes for OpenWebif)
enigma2-plugin-extensions-openwebif-vxg - 1.3.0+git3026+706a140-r0 - extensions-openwebif (WebTV for Google Chrome)
 extensions-openwebif (WebTV for Google Chrome)
enigma2-plugin-extensions-openwebif-webtv - 1.3.0+git3026+706a140-r0 - extensions-openwebif (WebTV for OpenWebif)
 extensions-openwebif (WebTV for OpenWebif)
```
OpenATV developers do not merge the original OpenWebif code every day, but only occasionally (once a month, for example?). And apparently after testing OpenWebif in OpenATV.

I tried everything possible. Uninstall OpenWebif with OPKG Manager or even completely delete the OpenWebif directory (after stopping the enigma, of course, and after rebooting). I then tried to reinstall OpenWebif again from the GitHub server, but also from the OpenATV feed-server. The remote driver was unable to show even after applying many solutions (found through Google with this exact problem).

**Comment by teamblue-e2** [comment]
Sorry but you are completely wrong - the package ist exactly the same - at least since a few days. Before it was simply build from branch "responsive" here.

The additional packages are simply a split - not ship everything to every box.
https://github.com/oe-alliance/oe-alliance-core/commit/8560349d871d78eac1edc99a1716e35c1476ac77

MODULE = "OpenWebif"
BRANCH="master"
SRC_URI = "git://github.com/E2OpenPlugins/e2openplugin-${MODULE}.git;protocol=git;branch=${BRANCH} \
           file://transcoding.py"

**Comment by s3n0** [comment]
Not and not and not. 

I recently asked to add two additional power modes to the OpenWeb interface. My request (modified code) was met. However, when I used the current OpenWebif installation package from the OpenATV feed server, I did not see any change there (two additional power modes). Only when using the OpenWebif generated IPK package from the GitHub server was the change seen. About 2 weeks later, the OpenWebif change was also finally seen after an update on the OpenATV feed-server.

So again:

OpenATV developers do not merge the code from OpenWebif GitHub into any OpenATV build, but only occasionally into some versions of OpenATV (after testing and not immediately upon the release of the new build-version of OpenWebif).

A minor error that still exists (no longer relevant to me):

After installing the original OpenWebif from the GitHub server, I do not see the remote controller (OpenATV 6.1 | Formuler F3). And I do not care. I'm using OpenWebif from the OpenATV feed-server when the OpenATV developers finally accepted a new version of the OpenWebif (2 weeks after it was released). So now it's irrelevant.

**Comment by teamblue-e2** [comment]
this is not the truth, sorry.
There is not much to discuss about a bitbake recipe. It is executed on every image build.
There is no pinned SRC_REV - so it picks up any change from branch master here.

**Comment by arn354** [comment]
since Schimmelreiter committed on 11 Dec 2017 openwebif got build from repository here: https://github.com/oe-alliance/oe-alliance-core/commit/768877bd53a6d96e23685a082e9cc67df64a012d#diff-0b9b07e71f726855de99f7628512d3c0
since then openatv used branch responsive: https://github.com/oe-alliance/oe-alliance-core/commit/05b1ad2b8b4599cc65ca7a0842dab182d67d009d#diff-0b9b07e71f726855de99f7628512d3c0

since i commited 8 days ago the switch to branch master openwebif is build from here branch master: https://github.com/oe-alliance/oe-alliance-core/commit/8560349d871d78eac1edc99a1716e35c1476ac77#diff-0b9b07e71f726855de99f7628512d3c0
