### ISSUE TITLE
Openwebif progress bar update in the movies section is not working

### ISSUE THREAD

**Issue by joniale** [E2OpenPlugins/e2openplugin-OpenWebif#757]
Dear OpenPli/Openwebif developer,

Openwebif only shows the progress-bar for the movies that have been reproduced directly from the box. However, if you start watching a recorded movie from the Openwebif interface (using the VLC player) then the progress bar is not updated. What i mean is downloading the .m3u8 and streaming the movie selected with VLC player .

The progress bar in the openwebif must not be accurate, at least we need a flag to know that the movie has already been watched. This is very useful if you have a serie and a lot of chapters. You are interested to know which chapters have already been seen.

Besides, you would also like to reset actively the progress bar somehow from the openwebif. This is for privacy reasons. Maybe, this is possible through extra buttons if this is not possible to do through the data collected from the box.

This feature has been discussed on
https://forums.openpli.org/topic/20164-openwebif-e2openplugins/?view=findpost&p=833867

I would appreciate this feature because i think it is really a basic feature that should be in the openwebif interface.

I am looking forward your answer
Thanks for your work
Best regards,
Joniale

**Comment by jbleyel** [comment]
This is impossible.
The file stream is a progressive download and not a real stream.
There is no information about the last position on the box available if you download a file.

The only way is:
Inform the box about a new last position.
This must be done by your player and this is not possible except you are using your own developed player.

**Comment by joniale** [comment]
Hi, and would not be possible to just detect the start of the progressive download and flag the file as seen by choosen an arbitrary progress bar of 25%. That would be better than doing nothing.

**Comment by jbleyel** [comment]
I'm pretty sure you can't detect the current position after you have canceled the download.
But this is what you need.

**Comment by joniale** [comment]
Yes i understand that. Did you read my previous comment? **I am sure** you can detect when the user clicked to start the download. On that point, you can just flag the progress bar of that file to for example, 25% progress independently of the **true** progress bar. As i wrote above, that is much better than doing nothing. This flag will be used by the user to know that this file have been watched already. The user should be able to actively reset the status bar from the openwebif interface (a new button in the openwebif interface will do that)

**Comment by jbleyel** [comment]
25% will be wrong and nothing is better than wrong.
But anyway this is also not so easy to implement.
Currently only enigma2 is modifying the xyz.ts.ap file. This is the file with the last position info.
Openwebif reads this file but do never modify this file for some good reasons.

**Comment by joniale** [comment]
Yes i think 25% is wrong but 'nothing' is also equally wrong. 
I see two solutions
1) Enigma2 image does something to modify that file so that it is recognized by openwebif interface plugin. I mean now including a new flag in this file that shows if something was streamed/downloaded from that file. Besides, it should be possible to delete that flag by playing locally that file or by any command that the plugin can send.
2) Another solution would be to store that streaming information in the plugin openwebif in an extra layer. Each time a movie file is downloaded/streamed will be created a new file. The plugin will detect which movies have been streamed by looking if that file exists. Openwebif will show a flag in the GUI so that the user can see it.
I insist on that feature because i see that this is really needed.
Thanks
