### ISSUE TITLE
Search on tittle and EPG of recorded movies

### ISSUE THREAD

**Issue by joniale** [E2OpenPlugins/e2openplugin-OpenWebif#758]
Dear Developers,
Sometimes an autotimer records the same chapter many times under the same name o very similar names. It would be good to have the option to search and filter the matches in tittle or EPG information for the recorded movies. In that way, we can easily see/check the recorded chapters that are duplicated. Besides, it makes easy to find specific chapters.
The search should have the option to include subfolders.
Besides, it would be good to have the option to select multiple movie files to be deleted/copied/moved from the Openwebif interface.
Best regards,
Joniale

**Comment by jbleyel** [comment]
This is a autotimer feature request, please open an issue here -> 
https://github.com/oe-alliance/enigma2-plugins

**Comment by joniale** [comment]
Maybe, i didn´t express me well. It would be good to be able to search not only on the EPG of the bouquets as we have on the openwebif interface but to be able to search on the recorded movies section. That is currently not possible on openwebif and this has nothing to do with autotimer.
If you say that something needs to be develop **first** on the enigma2 side then i understand but this is something that is missing in the openwebif too.
The same for the second part of the request. Which is being able to select multiple files on the openwebif interface. Currently is not possible to delete multiple files selection.

**Comment by jbleyel** [comment]
Again, this is a missing feature of autotimer and not openwebif.

**Comment by jbleyel** [comment]
This  -> " it would be good to have the option to select multiple movie files to be deleted/copied/moved from the Openwebif interface." is a different feature request and this is owf related.

**Comment by joniale** [comment]
I don´t understand why do you say that searching on the EPG of the recorded movies is something related to autotimer. You can record a movie, **manually, without using autotimer**. Maybe, you meant that this needs to be in the enigma2 issue thread. In other words, that needs to be implemented first in the core of enigma2 so that you can use this in openwebif afterwards. 
Can´t you search only in the EPG of recorded movies without having that feature on enigma2? How does it work? Do you have a single EPG database to search? where is the recorded movie EPG information saved?
I am looking forward your answers

**Comment by jbleyel** [comment]
You have written this:

> Sometimes an autotimer records the same chapter many times under the same name o very similar names

--

For "normal" timers or manual recordings you should ask the box image provider if they are see any possibilities to fix your double recording issue.   

--

The EPG data of an recording are only in xyz.ts.meta file except you are using EMC or AMC, but this is a different story.

**Comment by joniale** [comment]
This feature (searching on your recorded movies of your box hard drive), is not only useful **to eliminate duplicated** chapters. It is really useful for many things, like finding an specific chapter. If you have 1 Tera of series in your hard drive and you want to find a chapter, then it is difficult without a proper search function on EPG. 
Besides, i think it would not be so difficult to just search on xyz.ts.meta file for a text match and then find the corresponding filename match in the harddrive.
