### ISSUE TITLE
Issue: Name of the downloaded m3u8 file used for openwebif streaming is always the same

### ISSUE THREAD

**Issue by joniale** [E2OpenPlugins/e2openplugin-OpenWebif#759]
Dear Developers,

As you know, each time we want to stream a channel or a movie form the openwebif interface, the file of the downloaded stream will be "stream.m3u8" in case of TV channel or in case of a recorded movie then "ts.m3u8".
It would not be so difficult to rename that downloaded file and display that file using the channel tv name or bouquet name. Besides, It should be possible to disable that feature for the openwebif so that the privacy is kept.

In case you want to download a movie. I think the best way would be to rename the ts.m3u8 filename to a new name that uses the name of the file concatenated with the first 30-55 characters (without spaces or new lines) of the EPG if available (normally the tittle of the show) or just name of the file, which unfortunately in case of a recorded serie is always the same (therefore, i recommend to use the EPG info to make names unique).

The reason for that is that we can easily keep track of the last shows we have seen. This can be known through the file download history and recall what did we watched. (we should be able to disable that feature for privacy reasons). Besides, you can reuse that file in case you want to restart the connection to that specific channel or movie.

I think that is not a high effort thing and will bring a nice feature.

Best regards,
joniale

**Comment by jbleyel** [comment]
We have discuss this.
A new naming of m3u file will break some 3rd party tools.

**Comment by joniale** [comment]
That is a pity.
Now it is a little messy because either all the files overwrite themselves or they are automatically renamed (as windows does). I wonder how this automatic renaming of windows is not having problems with these 3rd party tools (btw which tools?). I don´t understand it.  A proposal is then to create folders with the proposed EPG information and the file without modification inside. Maybe, that is better than the current automatic renaming in windows or overwrite.

If you can´t implement this then i think it is needed some kind of tracking of the files that have been streamed for the streamer client side. The client side is interested to know what has been streamed to not repeat the same chapter. This can be done storing this data e.g. with cookies in the client side (just a proposal). I have described this under my last comment on this thread
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/757

The intention behind this request is to let the user easily know what has been seen, the same for the ticket of the progress bar. Both tickets are closed by you . I think implementing something to solve this problem  **would generate a lot nicer experience than what we have now**. However, even if i propose some solutions it seems there is no option to solve this feature problem.

**Comment by arn354** [comment]
I know a lot of users and no one has your needs/usecases.
A lot of plugins and also apps for android/ios use the existing functionality - which is for normal usecases simply plain enough.
You should use kodi or anything else to stream from there - simply mount your /hdd/movies folder from there.

**Comment by joniale** [comment]
Ok. I cannot tell you about the number of people interested in but for me this feature has a lot of sense. The same sense that the progress bar has in the enigma2 image (to know that something was seen or partially seen). But anyway, i will not insist anymore.
Thanks for your time.

**Comment by arn354** [comment]
![07-02-_2018_20-45-24](https://user-images.githubusercontent.com/4148122/35938116-7f68dce8-0c48-11e8-9087-f316e07e90b0.png)

which progress bar is missing? I have one ?

**Comment by joniale** [comment]
If this progress bar is for a movie in the hard drive of your box then that is what i want yes.

I only have that bar availabe if the movie is played **directly from stb itself**. That progress bar doesn´t display/update/work if you use the stream function from the openwebif interface. That was the point of my other ticket https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/757 reporting this.

No. I don´t want to track different progresses for different streaming users, i just want to have any information about what has been watched.  The progress bar would do it if it works for streaming from client. 
Is this progress bar (you have shown) from a streaming or from something you played directly on the stb?
How did you achieve that?
-->I use VLC player, which other players would make the progress bar to work?
Looking forward your answers
Thanks

**Comment by arn354** [comment]
Quote: sure it does not reflect streaming progress.

**Comment by joniale** [comment]
So it is not possible and you don´t see any gain on this feature. 
Well, i can only repeat myself and say that this is in fact a great feature for users that stream movies/files from the stb (not directly being there). It is the same point why i also see the progress bar useful when i watch movies directly from the stb.

**Comment by wedebe** [comment]
Filename can be modified via url parameter `fname`, eg:
`/web/stream.m3u?ref=1:0:19:52D0:814:2:11A0000:0:0:0:&name=Channel%204%20HD`
to
`/web/stream.m3u?ref=1:0:19:52D0:814:2:11A0000:0:0:0:&name=Channel%204%20HD&fname=customFilename`

I reckon a config pref would be able to make use of this to automatically save as channel/movie name
