### ISSUE TITLE
A Powertimer shuts down the box during streaming from openwebif

### ISSUE THREAD

**Issue by joniale** [E2OpenPlugins/e2openplugin-OpenWebif#760]
Dear Developers,

It would be good if you could configure your power timer (hibernate) to avoid its execution in case the box is being streamed from any place, e.g. openwebif or other box. This should be easy to detect. Another option would be to create a pop up window in the openwebif interface so that the user is requested to confirm the power timer. This is in the same way it is currently done in the enigma box.

Lastly, it would be good to have a wakeonlan feature in the enigmabox so that we are able to wake the box from hibernate mode sending a LAN command. Currently, this only work for standby mode.

Best regards,
joniale

**Comment by jbleyel** [comment]
The powertimer support via openwebif is not finished cause of some missing changes in enigma2.

**Comment by joniale** [comment]
I copied here my answer to the same ticket on the main enigma2 thread:

"Yes i understand. There are some boxes that supports WoL as i commented in my previous email. That means, there are enigma2 compatible boxes that have that hardware.
I guess a PC connected to the box by LAN could generate that package. The question is if it would be easy to generate that package and if that could be just a composed URL that can be saved in favorites or it needs to be something more complex and a external program needs to be created. That script could be provided automatically by the openwebif and can be stored in the PC for future usage.
If you say that there are no many boxes that supports that and it is not worth to develop that feature then i understand. However, the WoL is only a part of this ticket. This ticket is really about poping a message on the openwebif interface so that users can cancel the powertimer.

Most of the streaming software only buffer miliseconds of the source file. It is not downloading the whole file and then playing it. Therefore, it should be possible to detect if there is a streaming ongoing by spying the outgoing ethernet interface. If something is outgoing to any other IP then is is being used."

**Comment by jbleyel** [comment]
What do you mean with:
> in case the box is being streamed from any place

* Recording or Live?
* Transcoding or not?
* Stream Client?
* How do you start the stream exactly?

**Comment by joniale** [comment]
The main usage of this feature is to avoid that a stream client (somebody that is **streaming/watching something from the hard drive of the box)** is stopped to do this because the box has been shut down in deep standby. It would be good if you can configure the powertimer to avoid that this happens and/or display a message to the stream client to warn him that the powertimer has been activated and give him the option to disable it.
The way to start the streaming i use is. 1.  download the file stream.ts with the URL from the file in the box and start the streaming with a stream player like VLC. 
But i think that should not be constrained to what i describe all your listed cases are also applicable.

**Comment by jbleyel** [comment]
The shutdown/deep standby action can't be prevent if the box doesn't know about usage.
Usage is: active timer recoding / timer planned in the next few minutes
Usage is not:  Download a file from hdd or any shared folder on the box (e.g. nas) 

The live stream can be detect by enigma2 but an active live stream doesn't care anybody and the shutdown will not be canceled.

**Comment by joniale** [comment]
We are talking about powertimers (scheduled powerdown) **not a manual shutdown/deep standby**.
I think it cares. It is important for streamer client. In my opinion, streamer clients are also users of the box and they should not be treated as second class users.
What about openwebif  displaying a popup in the webbrowser to the streamer client (the user of the openwebif interface). This can be done, because openwebif should know about all the powertimers and can know when one is coming.  Then the user can decide to actively disable this powertimer.

**Comment by joniale** [comment]
Hi, i have already understood all what you have said. 
As i wrote in my previous comment you don´t need to know any status of the streaming but just have a javascript o some script in your openwebif interface that recognize your powertimers and display a **message/popup** to the user so that he can actively cancel the coming deep standby powertimer (maybe just by pushing a yes or no). The same the enigma2 image does to the local user. A separated window is important so that it comes in front of the maximized player application.

**Comment by jbleyel** [comment]
And how you think should we do this?

The powertimer is a function in enigma2 and there is no way to send an event to the openwebif.
There is no communication channel from enigma2 to the web client like a push notification.

The only way is a polling, but this bad coding and will not help here.
All events in between the poll will be ignored.
We will certainly not integrate a polling which can cause the box to crash in case of a to short interval.

**Comment by joniale** [comment]
My opinion.
Solutions would be 
1) enigma2 implements that trigger like push notification, easier for you
2) you poll all the powertimer data configurations. I mean **NOT a polling to know if any event has happened or not as i think you suggest**.
With the powertimer info configuration and the current time you can predict when a powertimer will be executed exactly. This is simple a function that calculates the next time event of a powertimer and schedule a popup message to the calculated time. You can also know/use the configured GMT time on the stb so that you calculate the correct time. You don´t need to calculate all events just the next.

Anyway i am sure you will find a problem :)

**Comment by jbleyel** [comment]
Yes, it can be possible if enigma2 can calculate the exact execution date and time of an powertimer action including an info if these action can interrupt a stream or what ever.
This needs to implement in enigma.

Then we can implement a kind of stream start pre check if this data above is available.
And yes i have a problem.

The popup will only shown if you start the stream via browser.

**Comment by jbleyel** [comment]
I have take a look inside the source of the powertimer from openatv.
There is a network traffic check already implemented.
Therefore i will close this here.
