### ISSUE TITLE
Provide a new skin where white picons with transparent background are visible 

### ISSUE THREAD

**Issue by joniale** [E2OpenPlugins/e2openplugin-OpenWebif#763]
Dear developers,
Currently, white picons with transparent background are not visible with the skins provided.
Maybe it would be easy to just modify the dark skin that is already delivered with the plugin and provide a little more darker background to the bouquet channel lists so that a white picon with transparent background would be visible.
Best regards,
joniale

**Comment by jbleyel** [comment]
Please provide a screenshot.
But i think there are many skins and you will find one with a sufficient dark background.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/screenshots/SCREENSHOTS.md

**Comment by joniale** [comment]
Below,  a small screenshot that shows the problem. Anyway, i think you are right and there should be other skins a sufficient dark background. I didn´t know that there was other skins available. My openwebif interface plugin only has two skins. The original and the clear skin which is a little darker. I guess i can download more skins from the extension menu.
**Sorry for this ticket, you can close it!**

![2018-02-07 22_09_26-vu solo4k - openwebif](https://user-images.githubusercontent.com/16894469/35941819-e64abb38-0c53-11e8-9fdd-ed5ac1462ea3.png)
