### ISSUE TITLE
API endpoint to fetch bouquet files and the lamedb

### ISSUE THREAD

**Issue by WanWizard** [E2OpenPlugins/e2openplugin-OpenWebif#766]
Currently there are a lot of ways, from using CIFS / NFS shares or solutions based on FTP, to access bouquet files or the lamedb.

Are there any objections against creating an API endpoint to fetch a bouquet file or the lamedb/lamedb5, so plugins like ChannelImporter, RemoteStreamConverter and others have more easy ways to access the required data to improve integration between Enigma systems?

**Comment by jbleyel** [comment]
What you exactly mean with "fetch ..".
Do you want the files as download or do you want the data inside of the files in a different format?

**Comment by WanWizard** [comment]
download, in "plain/text" format. 

Preferrably without creating security issues, such as allowing the download of /etc/passwd.

I'm looking for a way to have a client fetch these files from a server without having to resort to using FTP or a more complicated protocol, much more prone to errors than HTTP(S).

**Comment by jbleyel** [comment]
The file api is able to download the files.

http://.../file?file=/etc/enigma2/lamedb

**Comment by WanWizard** [comment]
Ah, didn't find that one.

Is that unrestricted? So I can download /etc/passwd if I want?

**Comment by WanWizard** [comment]
Appearently so. Isn't is a good idea to only expose this endpoint if the webif is secured with a username/password? 

At least it is clear that this way any box found on the internet can get its softcam config ripped in seconds. ;-)

**Comment by jbleyel** [comment]
This is a endless discussion.
We have only basic clear text as password.
If you don't want an open box in the internet you need to use VPN.

**Comment by WanWizard** [comment]
Clear, and agreed. Just wanted to check. ;-). 

Thanks.
