### ISSUE TITLE
OpenWebIf 1.3.0 looks broken on Cyberfox (Firefox ESR)

### ISSUE THREAD

**Issue by Tony-il-Capo** [E2OpenPlugins/e2openplugin-OpenWebif#768]
Hi
After trying the new OpenATV 6.2 beta that comes with OpenWebIf 1.3.0, I have this weird looking page on a Firefox based browser, but opens OK on a Raspberry Pi 3 using Chromium browser.
See screenshot:
![openwebif](https://user-images.githubusercontent.com/15948151/36446477-4963a9e4-1679-11e8-852d-9d946c0a5310.jpg)

I'm not sure what is the problem, I still have an STB running outdated OpenATV 6.1 with an older OWI version and it opens normally using the same browser.
Any help is appreciated.

**Comment by jbleyel** [comment]
This image looks like a CSS issue with your browser.

**Comment by Tony-il-Capo** [comment]
Yes, many thanks for your answer... I had already tried to clear all caches before and did not resolve the problem,
Now I hit Ctrl+Shift+R (Reload (override cache) shortcut) and the page just shows up normally. Hallelujah! 😆
