### ISSUE TITLE
Ordner in Aufnahmen auflisten lassen

### ISSUE THREAD

**Issue by LevelOne2k** [E2OpenPlugins/e2openplugin-OpenWebif#769]
Hallo,

wie lautet der URL Befehl um mir die angelegten Ordner in "/media/hdd"  im Browser als XML oder JSON auflisten zu lassen? also z.B. "/media/hdd/ORDNER"

Gibt es dafür eine überhaupt eine Api?

Danke

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/wiki/OpenWebif-API-documentation

**Comment by LevelOne2k** [comment]
Und welcher Befehl davon ist das?

**Comment by jbleyel** [comment]
Steht doch alles da?

/api/movielist?dirname=/media/hdd/....
