### ISSUE TITLE
Characters & and " not properly escaped 

### ISSUE THREAD

**Issue by spathi85** [E2OpenPlugins/e2openplugin-OpenWebif#772]
Hi,

since an update last year (I would say around March 2017) the characters & and " are displayed as `&amp;` and `&quot;` in the epg of streaming clients. On the receiver and directly in the webinterface everything ist displayed correctly.

Here's an example from Kodi 17.6 with PVR Plugin for Vu+:
![img_20180306_210158](https://user-images.githubusercontent.com/37122035/37057134-a367197c-2186-11e8-8cb6-4df8037cb664.jpg)

And one from "Dream Droid" for Android:
![screenshot_20180306-210423](https://user-images.githubusercontent.com/37122035/37057153-b8d31018-2186-11e8-9dfb-6f572a8c27a9.png)

Thanks.

**Comment by jbleyel** [comment]
These encoded signs are valid for xml and we have no intention to change this.
Some foreign language needs this to prevent xml parsing errors.
You have to fix this issue in the 3rd party applications.

**Comment by jbleyel** [comment]
The code inside of openwebif is here. -> 

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/services.py#L46

!!CAUTION!!
The result needs to be encoded for valid json and xml results.

Please provide channel name and date of some epg item for testing.
This example needs to be sat ( astra 19,2 ) and in some days.

**Comment by zehnerGIT** [comment]
Thanks for the feedback

I've tested the url http://vuplus/web/epgservice?sRef=1%3A0%3A1%3A445E%3A453%3A1%3AC00000%3A0%3A0%3A0%3A (that's Kabel 1 for me) and there are many entries (e.g. a reocurring entry is Navy CIS: L.A. with the line `Linda Hunt (Henrietta &amp;quot;Hetty&amp;quot; Lange)`). My tests are on Ubuntu with CURL, WGET, Chromium and Firefox and all show the same behaviour.

**Comment by jbleyel** [comment]
I think i have found the root cause.
The Cheetah template to build the xml have a feature named websafe.
This filter encodes the text again and therefore we have double encoding.
I will try to fix this.

**Comment by jbleyel** [comment]
please check the latest version
