### ISSUE TITLE
Openwebif change standard player for movie record playback using webif controls

### ISSUE THREAD

**Issue by chrisoutwright** [E2OpenPlugins/e2openplugin-OpenWebif#774]
Is it possible to choose EMC as standard player as executable to the ajax implemented function playRecording(sRef) as defined in /js/openwebif.js ?

I am using Alexa Echo and would like to use voice commands, yet fiddling directly with .py files in the extensions folder seems to fail me, although I have taken a look in the E2 folder /plugin/controllers/web.py, see [Link.](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/275930de919054e5a964c6e11127e8c1a596905a/plugin/controllers/web.py)
Would it be possible to have the most important functions usable in openwebif, instead of creating a separate web.py for EMC?

**Comment by jbleyel** [comment]
This is the right entry point to start a recording -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/controllers/models/control.py#L113

I don't find a similar function in EMC source to start playback if EMC is not started.
You need to ask the EMC developer.

**Comment by chrisoutwright** [comment]
Sadly the EMC developers have closed my request, see [Link](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/issues/233)

I hope still that it is doable even if it has to be without them.

**Comment by jbleyel** [comment]
No, the direct start needs to implement in EMC. 
We can only call an existing function, but it does not exist.
