### ISSUE TITLE
Feature Request: option to Manual typing recording path.

### ISSUE THREAD

**Issue by rocco99-2** [E2OpenPlugins/e2openplugin-OpenWebif#779]
Don't easy to select own path. Path can been retrieved with Windows Explorer, MacOSX Finder or Nemo/Nautilus/Caja/Thunar in Linux.
So want a box to type or paste in a manual path, to record to path that is not displayed in the choose box. 

It is very difficult to add other paths to the timer select box, the only way to do that in the web-if is with the box interface themselves. Refresh screenshot every second _sreenshot section in web-if), and then go to the timer section to create a bookmark.

This must to make doing to do easyer.

![image](https://user-images.githubusercontent.com/37477335/37556405-a83268b8-29f5-11e8-85fd-4599d2b0fadc.png)

![image](https://user-images.githubusercontent.com/37477335/37556381-6efb3c64-29f5-11e8-890b-4a1163cc3190.png)

**Comment by jbleyel** [comment]
There is a new setting to modify bookmarks.
Define a manual path in timer edit is not the right place.
