### ISSUE TITLE
Woher kommt das yaunel.com?

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#793]
Hallo liebe Leute :)
![bildschirmfoto vom 2018-04-05 21-10-24](https://user-images.githubusercontent.com/17575778/38386773-18519c5c-3916-11e8-8d68-bb75cd9f7719.png)

uMatrix hat das Laden der folgenden Seite verhindert: (yaunel.com)

https://www.doubleclickbygoogle.com/
Gruß sgs

**Comment by jbleyel** [comment]
Keine Ahnung was du da meinst.
Bei mir ist das nicht.

**Comment by sgse** [comment]
Danke Jörg, war nur gestern auf Manjaro Deepin 17.1.7, auch nach Neustart. Heute ist alles o.k.
Bei Manjaro XFCE und Mint 18.3 hatte ich es nicht. Schaun mer mal, ob es noch mal kommt :-)
