### ISSUE TITLE
cosmetic- helptexts (alt=) on rc buttons hidden

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#797]
As I saw, help texts (alt="xxxxxxx") under rc buttons are not displayed. 
I think,long time ago it worked. May by, some changes in Webbrowsers or what ?

It is pitty, because texts on buttons are still smaller and smaller...

**Comment by jbleyel** [comment]
Hi @ims21, please provide a screenshot with some more info.

**Comment by ims21** [comment]
I do not know, if it worked under Owif or where I saw it...

Easy - if you are several seconds with mouse cursor in defined remote controller button area, then display small label with text (wroted as alt text in rc file) ... example: in "alt="video" => display label with "VIDEO".

Similar, as it works here for owif's controll items - f.eg. when is cursor on envelope is displayed "Send a Message".
