### ISSUE TITLE
What problem today with Owif ?

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#799]
> web.Server Traceback (most recent call last):
exceptions.ImportError: No module named local
/usr/lib/python2.7/site-packages/twisted/web/server.py:189 in process
188
189
190
/usr/lib/python2.7/site-packages/twisted/web/server.py:238 in render
237
238
239
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py:222 in render
221 args["content"] = out
222 nout = self.loadTemplate("main", "main", args)
223 if nout:
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py:103 in loadTemplate
102 if fileExists(getViewsPath(path + ".pyo")):
103 template = imp.load_compiled(module, getViewsPath(path + ".pyo"))
104 else:
/home/martin/oe5/build/tmp/work/vs1500-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+abf6016435-r0/git/plugin/controllers/views/main.py:26 in <module>
25
26
27
exceptions.ImportError: No module named local

**Comment by ims21** [comment]
Now:
web.Server Traceback (most recent call last):
exceptions.ImportError: No module named controllers.i18n

**Comment by ims21** [comment]
git/plugin/controllers/views/responsive/index.py:26 in <module>

**Comment by jbleyel** [comment]
Please close if fixed on your box

My test box is "green".

**Comment by hd75hd** [comment]
OpenWebIf start now after the last commits ..
but now i have english language in OWIF

**Comment by ims21** [comment]
Yes, works now ... is possible change old/new design now too.

One note ... not very happy new size of full RC in new design ...  Why there must be "Materialize ...." instead enlarge full RC ?

**Comment by jbleyel** [comment]
Hi @ims21 , the responsive design is a 99% copy of the vti fork without UI changes.

**Comment by ims21** [comment]
I hope, old design will be still useable ... I do not know why are trends make all as for childs, wasting a place etc...

**Comment by jbleyel** [comment]
The new responsive web is much better to prevent screen size issues.
But some parts are not as good as the old web UI. 

I'm not impressed to maintain 2 different interfaces but not all users likes the new resposive design.
Me too if not all issues are fixed.

**Comment by hd75hd** [comment]
with the last commits , the language is taken correctly
thx

**Comment by ims21** [comment]
About new design: 
- screenshot is not possible scalling with Ctrl+/-  ... all is scalled, screenshot is still same size :-(
- fonts are worse readable
- info about box ... funny ...

**Comment by jbleyel** [comment]
.. and many other things ;-)

But the whole thing is not bad.

I will try to fix these issues but only if we plan to remove the whole old UI.
