### ISSUE TITLE
latest master doesn't work on vu+ duo2

### ISSUE THREAD

**Issue by ShareScene** [E2OpenPlugins/e2openplugin-OpenWebif#800]
web.Server Traceback (most recent call last):
<type 'exceptions.ImportError'>: No module named local

/usr/lib/python2.7/site-packages/twisted/web/server.py, line 132 in process
130    try:
131      resrc = self.site.getResourceFor(self)
132      self.render(resrc)
133    except:
/usr/lib/python2.7/site-packages/twisted/web/server.py, line 167 in render
165    """
166    try:
167      body = resrc.render(self)
168    except UnsupportedMethod, e:
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py, line 241 in render
239                                                args = self.prepareMainTemplate(request)
240                                                args["content"] = out
241                                                nout = self.loadTemplate("main", "main", args)
242                                                if nout:
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py, line 113 in loadTemplate
111                if fileExists(getViewsPath(path + ".py")) or fileExists(getViewsPath(path + ".pyo")):
112                        if fileExists(getViewsPath(path + ".pyo")):
113                                template = imp.load_compiled(module, getViewsPath(path + ".pyo"))
114                        else:
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/main.py, line 26 in
24import Cheetah.Filters as Filters
25import Cheetah.ErrorCatchers as ErrorCatchers
26from Plugins.Extensions.OpenWebif.controllers.i18n import tstrings
27from json import dumps
<type 'exceptions.ImportError'>: No module named local

**Comment by jbleyel** [comment]
please remove all compiled templates like this ->
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/main.py
or this
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/main.pyo
