### ISSUE TITLE
infinite loop when loading schedule

### ISSUE THREAD

**Issue by ShareScene** [E2OpenPlugins/e2openplugin-OpenWebif#801]
you can sit for hours seeing this loading but it never ends:
![sin titulo](https://user-images.githubusercontent.com/38386511/38780410-f5ed7c7c-40d5-11e8-941d-5c813010ffe6.jpg)

**Comment by jbleyel** [comment]
You need to remove all compiled templates .. see #800

**Comment by ShareScene** [comment]
I really removed both of them but still nothing... is there any other one I need to remove?

**Comment by ShareScene** [comment]
ok I found the solution you need to remove all .py and .pyo from /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/

**Comment by jbleyel** [comment]
YES!!

ALL compiled templates in folder 
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/
and any subfolders

If there is a new tmpl file, you need to remove the py or pyo file with the same name.
