### ISSUE TITLE
wrong firmware (image) detection

### ISSUE THREAD

**Issue by giljotina** [E2OpenPlugins/e2openplugin-OpenWebif#806]
![openwebif](https://user-images.githubusercontent.com/39020927/39670645-b198dad2-5109-11e8-932d-587b1ead9b2c.jpg)
Hi,
on my VU+ I'm using OpenPLI 6.2. rc version,when I switched OpenWebIf to show new design I noticed that   it detects my image as OpenHDF instead of OpenPLI.
Nothing serious , but still...

**Comment by teamblue-e2** [comment]
As System OE is also recognized as OE-Alliance 4.1 - this image is not a openPLi image as openPli is not build from oe-alliance.

**Comment by giljotina** [comment]
Image is definitely OpenPLI, could it be becaouse of the skin I'm using
![1_0_19_1c06_29_46_e080000_0_0_0_20180506114019](https://user-images.githubusercontent.com/39020927/39671993-7074b120-5122-11e8-8ff1-46b0a042f897.jpg)

**Comment by jbleyel** [comment]
The generation of the image distro name is wrong.
See here ->
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/777c742744bf4a1f42bcb9df5d05918bde3e8620/plugin/controllers/models/owibranding.py#L124

**Comment by pr2git** [comment]
Did you play with OpenMutlboot with OpenPLi in Flash and do you have installed OpenHDF as a multiboot image?
Because I had exactly the same issue with OpenATV, I need to reflash my OpenPLi in flash to retrieve a clean situation.

**Comment by jbleyel** [comment]
closed because of no update
