### ISSUE TITLE
dm800se is without rc

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OpenWebif#807]
Due [this ](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/ca3f59e0bf110e2006e4cbd5cc2ec325ff66b64c#diff-8f1cc3e5085842b3311f4f8bf8ed3f33)is dm800se without rc picture under owif

**Comment by jbleyel** [comment]
owbranding is part of the image provider and not releated to the base source
