### ISSUE TITLE
WebUI nach Aktualisierung auf 1.3.2 nicht mehr erreichbar

### ISSUE THREAD

**Issue by LevelOne2k** [E2OpenPlugins/e2openplugin-OpenWebif#809]
Hallo, ich habe das OpenWebIF von hier geladen:

"enigma2-plugin-extensions-openwebif_1.3.2-e2openpluginsgit20180509_all.ipk"

Und auf meiner Vu+ Ultimo 4K mit aktuellem VTI Image installiert. Seitdem kann ich das WebUI nicht mehr erreichen. Über Apps funktioniert die Steuerung des Receivers noch ohne Probleme.

<img width="851" alt="bildschirmfoto 2018-05-10 um 16 41 00" src="https://user-images.githubusercontent.com/25386824/39875454-f9818cee-5470-11e8-8cfa-5c7d351ad237.png">

**Comment by LevelOne2k** [comment]
Kann niemand helfen?

**Comment by LevelOne2k** [comment]
???

**Comment by e2world** [comment]
Kann nicht am OWIF 1.3.2 liegen, auf einer Ultimo4k mit OATV6.1 kein Problem.

**Comment by LevelOne2k** [comment]
Ich habe kein OATV installiert, sondern VTI.

**Comment by madieatv** [comment]
dann frag doch bitte im vti. so weit ich weiß bauen sie aus einem eigenen fork.

**Comment by jbleyel** [comment]
Der Fehler kommt wenn du die compilierten templates nicht löschst.
Am besten du löschst das openwebif und installierst es neu.

Das ipk von hier ist nicht zur Installation gedacht, sondern nur für debug Zwecke.
Du musst schon das passende ipk von deinem Feed nutzen.
