### ISSUE TITLE
Movies sub-directory selector broken in "Materialize design" UI

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#812]
Using the "Materialize design" version 1.0.1 UI for OpenWebif version 1.3.0 the sub-directory selector in  the "Movies" section of OpenWebif is broken. The selections in the drop down list box are not being actioned.

I am testing with Chrome Version 66.0.3359.170 on Windows 10.

There is no issue in the old / classic UI.

**Comment by ims21** [comment]
it is not broken, it is feature ... there are missing functions for this "cool" new design ...
