### ISSUE TITLE
WebIF liefert falsche werte beim SleepTimer

### ISSUE THREAD

**Issue by Kinzal16** [E2OpenPlugins/e2openplugin-OpenWebif#813]
Hallo, das WebIF liefert beim SleepTimer falsche werte.

Wenn man den SleepTimer deaktiviert, dann wird er sozusagen aktiviert. 

Wenn man den SleepTimer aktiviert, dann wird er sozusagen deaktiviert. 

Jedenfalls sind so die Meldungen. Am Receiver wird kein SleepTimer gesetzt.

Installierte OpenWebIF Version 1.3.2

![bildschirmfoto 2018-05-17 um 21 58 20](https://user-images.githubusercontent.com/22612289/40201343-1be2efcc-5a1f-11e8-9b21-ed05ce9f8e2b.jpeg)

**Comment by AdlerCentauri** [comment]
Ist bei mir auch so. Wurde das schon gefixt?

**Comment by jbleyel** [comment]
Ich habe kein Image mit sleeptimer, daher kann ich das nicht testen und fixen.
Das muss jemand anders machen.

**Comment by AdlerCentauri** [comment]
Und wer?

**Comment by arn354** [comment]
Welches Image?

Ich denke eher das hier im Image configEnableDisable falsch verstanden/interpretiert wird (Unterschied enable/enabled und disable/disabled).

EnableDisable ist zu übersetzen - Enable = aktivieren (funktion ist aus, configwert ist TRUE), Disable = deaktivieren (funktion ist an, configwert ist FALSE).

So wie TRUE/FALSE oftmals verwendet wird sollte es eher configEnabledDisabled heißen:
Enabled = aktiviert (funktion ist an, configwert ist TRUE), Disabled = deaktiviert (funktion ist aus, configwert = FALSE)

**Comment by jbleyel** [comment]
Hallo zusammen,

1. Auf der Box mit der FB den Sleeptimer AUS.
2. diesen Link im Browser eingeben: http://<IP>/api/sleeptimer
3. Auf der Box mit der FB den Sleeptimer AN (60 Minuten).
4. diesen Link im Browser eingeben: http://<IP>/api/sleeptimer

Danach beide Results vom Browser hier posten.
Danke

**Comment by LevelOne2k** [comment]
1. Auf der Box mit der FB den Sleeptimer AUS.
Gemacht...
2. diesen Link im Browser eingeben: http:///api/sleeptimer
{
 "action": "standby", 
 "minutes": 30, 
 "message": "SleepTimer deaktiviert", 
 "enabled": false
}
3. Auf der Box mit der FB den Sleeptimer AN (60 Minuten).
Gemacht...
4. diesen Link im Browser eingeben: http:///api/sleeptimer
{
 "action": "standby", 
 "minutes": 60, 
 "message": "SleepTimer aktiviert", 
 "enabled": true
}

**Comment by jbleyel** [comment]
Hi @LevelOne2k ,
danke für die Results.
Ich sehe da keinerlei Fehler.
Und somit ist die Abfrage der Sleeptimer Settings korrekt.
Zumindest auf deiner Box mit deinem Image.
Du kannst die beiden Request noch mal xml machen, aber ich denke das Ergebnis ist das gleiche.
-> http:///web/sleeptimer

Im Browser musst du da aber vermutlich (Rechte Maus + Source) anschauen.
Da kommt eine XML wie oben hier in dem issue.

**Comment by LevelOne2k** [comment]
Da kommt dasselbe bei raus:

<e2sleeptimer>
<e2enabled>True</e2enabled>
<e2minutes>60</e2minutes>
<e2action>standby</e2action>
<e2text>SleepTimer aktiviert</e2text>
</e2sleeptimer>

<e2sleeptimer>
<e2enabled>False</e2enabled>
<e2minutes>30</e2minutes>
<e2action>standby</e2action>
<e2text>SleepTimer deaktiviert</e2text>
</e2sleeptimer>

Ich kann den Sleeptimer nirgendwo setzen, er wird nicht aktiviert. Weder in e2Remote Pro noch in sonst irgendeiner App
![screenrecording_07-14-2018 00-50-20](https://user-images.githubusercontent.com/25386824/42717290-480a6130-8700-11e8-91ea-b0a8077f58f7.gif)

**Comment by jbleyel** [comment]
Bitte diese beiden Links testen und vorher auf der Box den Sleeptimer AUS.

http:///api/sleeptimer?cmd=set&action=standby&time=60&enabled=True
-> Danach sollte der Sleeptimer an ist

http:///api/sleeptimer?cmd=set&action=standby&time=60&enabled=False
-> Danach sollte der Sleeptimer wieder aus sein

**Comment by LevelOne2k** [comment]
Hi,

"http:///api/sleeptimer?cmd=set&action=standby&time=60&enabled=True" habe ich ausgeführt, dass Ergebnis ist:

`{
 "action": "standby", 
 "minutes": 30, 
 "message": "SleepTimer wurde deaktiviert", 
 "enabled": false
}`

Auf dem Receiver ist der Sleeptimer auch deaktiviert.

Wenn ich "http:///api/sleeptimer?cmd=set&action=standby&time=60&enabled=False" ausführe, ist das Ergebnis:
`{
 "action": "standby", 
 "minutes": 60, 
 "message": "SleepTimer eingestellt auf 60 Minuten", 
 "enabled": true
}`

Und der Sleeptimer auf dem Receiver ist aktiviert.

**Comment by jbleyel** [comment]
Ich hab den Fehler gefunden und gefixt.
Das ist die Sache mit dem Wald und den Bäumen. ;-)
