### ISSUE TITLE
Pipgrab/openwebif issue

### ISSUE THREAD

**Issue by heisert** [E2OpenPlugins/e2openplugin-OpenWebif#816]
Screenshots/live picture (with third party apps etc) didnt work anymore

web.Server Traceback (most recent call last):
exceptions.UnboundLocalError: local variable 'mode' referenced before assignment
/usr/lib/python2.7/site-packages/twisted/web/server.py:195 in process
194
195
196
/usr/lib/python2.7/site-packages/twisted/web/server.py:255 in render
254
255
256
/home/oe1/atv62/build-enviroment/builds/openatv/release/hd51/tmp/work/all-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.0+gitAUTOINC+094e9fb277-r0/git/plugin/controllers/models/grab.py:108 in render
107
108
109
/home/oe1/atv62/build-enviroment/builds/openatv/release/hd51/tmp/work/all-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.0+gitAUTOINC+094e9fb277-r0/git/plugin/controllers/models/grab.py:61 in __init__
60
61
62
exceptions.UnboundLocalError: local variable 'mode' referenced before assignment

**Comment by ims21** [comment]
Should be fixed now ...

**Comment by heisert** [comment]
Thanks! Work again!
