### ISSUE TITLE
I'm gettin' a new error with latest build

### ISSUE THREAD

**Issue by ShareScene** [E2OpenPlugins/e2openplugin-OpenWebif#817]
It doesn't work at all, look at this error: 
![20180522_150813](https://user-images.githubusercontent.com/38386511/40364532-df7c76ae-5dd2-11e8-91e2-427c877acc09.jpg)

**Comment by jbleyel** [comment]
I think there are some missing twisted files or you have a very old twisted version.
This is not really owf related.

**Comment by ShareScene** [comment]
I'm using BlackHole 3.0.5k on vu+ duo2, could it be an issue from this BlackHole version?

**Comment by jbleyel** [comment]
Yes, it could be.
Please contact the provider of your image and ask them this question:

_Why do i don't have twisted.web.resource.EncodingResourceWrapper on my box?_
