### ISSUE TITLE
improve make ipk

### ISSUE THREAD

**Issue by jbleyel** [E2OpenPlugins/e2openplugin-OpenWebif#819]
TODO: 
* Add pre setup command to remove the compiled templates.
* ...

**Comment by ShareScene** [comment]
What is the priority for this issue?

**Comment by faihung** [comment]
root@imx6ulevk:/tmp# opkg install libc_1.1.19-1_arm_cortex-a9_neon.ipk 
Collected errors:
 * open_outer: Failed to open package 'libc_1.1.19-1_arm_cortex-a9_neon.ipk': Unrecognized archive format
 * pkg_extract_control_file_to_stream: Failed to extract control.tar.gz from package 'libc_1.1.19-1_arm_cortex-a9_neon.ipk'.
 * pkg_init_from_file: Failed to extract control file from libc_1.1.19-1_arm_cortex-a9_neon.ipk.


why

**Comment by atvcaptain** [comment]
box and image you have ?

**Comment by ShareScene** [comment]
is there any chance to take a look on this? is almost one year with this issue

**Comment by jbleyel** [comment]
what box and image you have ?

**Comment by ShareScene** [comment]
Vu+ Duo2 with Black Hole 3.0.8b

**Comment by jbleyel** [comment]
Then you should ask the black hole team.
IPK build is part of the image build.
