### ISSUE TITLE
Spaltenbreite nicht in Ordnung

### ISSUE THREAD

**Issue by Pumuckel65** [E2OpenPlugins/e2openplugin-OpenWebif#820]
[Das Problem](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/627) ist leider wieder vorhanden und die Zeile 10 in der multiepg.tmpl sieht aber schon wie folgt aus:

.service { font-weight: bold; font-size: 12px; line-height:30px; padding-right: 4px; white-space: nowrap; overflow: hidden;}

http://www.abload.de/img/09876ohs75.jpg

Wenn ich nun 1x zwischen OWIF-old-design und OWIF-new-design und wieder zurück wechsele, ist der Fehler wieder weg und ich kann ihn bis jetzt auch nicht bewusst reproduzieren ... irgendwann ist der Fehler halt wieder da.

http://www.abload.de/img/098760nrrh.jpg

Version: OWIF 1.3.2

**Comment by jbleyel** [comment]
Mit dem neusten Chrome Browser ist der Fehler nicht nachstellbar.

**Comment by Pumuckel65** [comment]
Ich selber schaffe es ja zur Zeit auch nicht den Fehler zu reproduzieren. Gibt es irgendetwas, was ich tun könnte, wenn der Fehler wieder vorhanden ist, was Euch bei der Analyse helfen würde?

**Comment by Pumuckel65** [comment]
Aktuell ist der Fehler leider wieder vorhanden und es ist mir auch nicht möglich diesen zu beseitigen. Ich habe es sowohl mit FireFox als auch mit dem Internet Explorer getestet. Was könnte ich noch versuchen um den Fehler einzukreisen odergar zu beseitigen?

**Comment by jbleyel** [comment]
Ich kann das leider nicht testen/fixen, denn ich habe weder FF noch IE.
Das muss sich jemand mit CSS/JAVA Script Skill machen der einen Windoof Rechner hat.

**Comment by Pumuckel65** [comment]
Vielleicht noch eine kleine Zusatzinfo für Euch:
Früher, wenn der Fehler auftrat, konnte ich ihn immer **dauerhaft** (bis zum nächsten Update) beseitigen, wenn ich die multiepg.pyo aus dem openwebif 1.2.1 auf die Box spielte. Bei der aktuellen OpenWebif-Version führt dies aber dazu, dass überhaupt kein EPG mehr dargestellt wird. Ggf. könnt ihr aber die Differenz zwischen der alten Datei und der neuen finden und somit die Neue fixen.

**Comment by Pumuckel65** [comment]
Jetzt ist der Fehler wieder weg und ich habe keine Ahnung warum ... ich habe nichts gemacht, ausser "F5" gedrückt und dies hatte ich vorher auch x-mal schon gemacht. Irgendwann wird er dann wieder da sein ....

**Comment by Pumuckel65** [comment]
Heute ist der Fehler wieder da ... da ich fast jeden die Box/OpenWebif nutze kann man also sagen, dass der Fehler einmal im Monat aufgetreten ist (was die Sache zum lokalisieren ja nicht einfacher macht).

Ich bin aber einen kleinen Schritt weiter bzw. weiß ich jetzt, warum der Fehler "auf einmal" wieder verschwunden ist --> es liegt am Datum bzw. am zeitlichen Ablauf des EPGs. Wenn ich heute den EPG darstelle ist der Fehler wieder zu sehen --> http://fs5.directupload.net/images/180728/kz2i86ao.jpg
Wenn ich aber dann auf den EPG vom Sonntag schalte, ist das Bild wieder i.O. --> http://fs1.directupload.net/images/180728/jnaswh72.jpg

Hilft Euch das weiter?

**Comment by Pumuckel65** [comment]
Heute kann ich das Phänomen vom Wochenende bestätigen --> der EPG von heute wird spaltenmäßig falsch dargestellt, aber ab morgen ist wieder alles o.k. . Dies kann ich heute so oft wie ich will nachstellen, aber ab morgen wieder nicht mehr.

**Comment by Priskvark** [comment]
This has been an issue for some time for me to. It’s “only“ a visual problem and I can live with it. But seeing Pumuckel65 struggling with it together with jbleyel maybe I can help?

This is always, every day, happening for me. And it makes no difference what Web browser I use for example Firefox, Internet Explorer, Chrome or Edge. And it looks the same on different hardware (Windows PC: s, Android phones, Tablets) with different operating systems.

This makes me believe that the problems origin may be found in Owif.

I have noticed that the “long” program description are very tight to the right border of the columns. But I’m not sure why this would impact the width.

I have also noticed that every now and then the headers are suddenly getting broader than normal witch makes the process of columns getting out of sync start on a new cycle.

![owif sample](https://user-images.githubusercontent.com/9423289/43610505-9b22794c-96a6-11e8-9415-eaf8a6f608d7.png)

Could we help jbleyel by sending a copy of our channel list together with a copy of the epg.dat for testing or is Owif not using the files when composing the web layout?

**Comment by Pumuckel65** [comment]
Vielen Dank für Eure Bemühungen!!
Leider haben die Änderungen bei mir keinen Erfolg gebracht. Ich habe beide Dateien ausgetauscht und den Receiver neu gestartet. Da heute der Fehler wieder sichtbar ist, kann ich derzeit gut testen.

EPG vom Samstag:
http://fs1.directupload.net/images/180804/xvheghx2.jpg

EPG vom Sonntag:
http://fs5.directupload.net/images/180804/z32ojhzh.jpg

**Comment by Pumuckel65** [comment]
Nocheinmal ... vielen Dank für Eure Hilfestellung (ich weiß das wirklich zu schätzen)!

Leider hat auch das löschen der multiepg.pyo keien Erfolg gebracht. Folgendes habe ich versucht:
1. Versuch
- /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/multiepg.pyo gelöscht
- EPG-Browsaerseite aktualisiert --> eine neue multiepg.pyo wird erzeugt aber Spaltenbreite n.i.O.

2. Versuch
- /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/responsive/ajax/multiepg.pyo gelöscht
- /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/multiepg.pyo gelöscht
- EPG-Browsaerseite --> eine neue views/ajax/multiepg.pyo wird erzeugt 

aber Spaltenbreite n.i.O., eine neue responsive/ajax/multiepg.pyo wird scheinbar nicht erzeugt
- nun wieder die alte /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/responsive/ajax/multiepg.pyo zurück kopiert --> Spaltenbreite n.i.O.

Alle Rechte dieser genannten Dateien liegen auf "644" und dies sollte ja wohl auch o.k. sein.

Gerne suche ich den Fehler auch bei mir (;-) ), aber ich weiß nicht wo. Was mache ich falsch? 
Ichhabe Euch mal mein ganzes Verzeichnis angehängt.

[OpenWebif.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/2259434/OpenWebif.zip)

**Comment by jbleyel** [comment]
Wenn der Fehler auftritt die komplette Seite mir dem Browser speichern.
Chrome / Datei / Seite speichern unter .. (Format Webseite vollständig)
 
Dann die html und der Ordner als zip hier rein.

**Comment by Pumuckel65** [comment]
gerne

[Vu+ Solo SE - OpenWebif-Dateien.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/2259442/Vu%2B.Solo.SE.-.OpenWebif-Dateien.zip)

**Comment by jbleyel** [comment]
Diese 4 Dateien löschen.

/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/multiepg.py
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/multiepg.pyo

/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/responsive/ajax/multiepg.py
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/responsive/ajax/multiepg.pyo

Dann Engima neu starten.

**Comment by Pumuckel65** [comment]
Treffer ... versenkt!!

![smilie](https://user-images.githubusercontent.com/29928422/43676174-0fc7617c-97ec-11e8-9608-1543fe7bbc32.jpg)

Vielen lieben Dank!!
