### ISSUE TITLE
Date/Time picker in timer-edit is so annoying

### ISSUE THREAD

**Issue by formtapez** [E2OpenPlugins/e2openplugin-OpenWebif#822]
When you want to change the start time of a timer event, you have to click through so many unneccesary things (Month, Day, Hour, Minute, ...) so many things can go wrong (accidently click on wrong day or so), and then the same clicks again (Month, Day, Hair color, Weight, Size, Hour, Minute, ...) for the end time. This annoys the hell out of me every time.
And then you can´t even select a time you want (only in 2-minute resolution).

Please replace that Date/Time picker rubbish with two independent things. One normal date-picker and another for the time (maybe a free-text field).

And please respect regions which have the monday as start of week. (The actual date picker starts at sunday)

**Comment by jbleyel** [comment]
What Datetime Picker do you mean?
Screenshot please.

**Comment by formtapez** [comment]
![image5](https://user-images.githubusercontent.com/5630762/43676096-abd91242-97ea-11e8-9ced-ed12fead4fef.png)

**Comment by jbleyel** [comment]
This part is from VTi team, please contact them to fix this.
