### ISSUE TITLE
Reverse proxy (also for raw and transcoded streams)

### ISSUE THREAD

**Issue by giopas** [E2OpenPlugins/e2openplugin-OpenWebif#826]
Hi folks,

I am running OWIF 1.3.3 on my Open Black Hole and I would like to use it behind a reverse proxy in order to have just one port open in the firewall.

In particular, I am using Caddy [1] and this is the configuration which offers plain access to the WebUI:

```
owif.domain.com {
  proxy / https://192.168.1.100 {
    transparent
    websocket
    insecure_skip_verify
  }
}
```

The problem however arises in case I want to actually stream raw or transcoded streams as I would need to also open port 8001 and 8002.

As far as I can see the m3u8 file is in the following format:

> #EXTM3U 
> #EXTVLCOPT--http-reconnect=true 
> #EXTINF:-1,CNN HD
> #EXTVLCOPT:program=7801
> http://owif.domain.com:8001/1:0:1:F49:1470:13E:820890:0:0:0:

However, would not be possible to use the same (80 or 443) port to stream the content. Maybe just a flag `raw` or `transcoded` would determine the quality of the streaming?

This, in addition to html5 transcoding [2], would dramatically improve the security and use case of this service.

Do you have any idea on how to achieve this? Is there maybe other plugin which would serve this purpose?

Thanks

[1] https://github.com/mholt/caddy
[2] https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/723

**Comment by fnordism** [comment]
Try it with a subdomain e.g stream.yourhost.com and proxy port 8002 to your reverse proxy appliance on port 443, i did the same stuff for a shoutcast stream
