### ISSUE TITLE
No more image for Solo4K in about STB

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-OpenWebif#829]
I just saw that there is no more image for the Solo4K in OpenWebif in the About STB.

**Comment by jbleyel** [comment]
No, you are wrong here.
This is an issue on your image provider.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/plugin/public/images/boxes/solo4k.png

**Comment by pr2git** [comment]
Problem araised after I install OpenATV in Multiboot. This has a lot of border effect, now OpenPLi in flash is reported as OpenATV 6.1 in OpenWebif. I will need to reflash my Solo4K and avoid this Multiboot stuff.
