### ISSUE TITLE
Add a screen to help antenna pointing

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-OpenWebif#830]
Add a screen to be able to use our PC to point properly antenna thanks to OpenWebif.

So have the SNR / AGC / dB displayed in real-time through OpenWebif + some options to easily zap between different services/satellite/TP from this screen.

**Comment by pr2git** [comment]
I was not aware that this one exist:

http://my_box/mobile/satfinder

Would be nice to have a direct link to it somewhere in OpenWebif to unhide this function, and have its equivalent in the standard (non mobile) page.

**Comment by jbleyel** [comment]
Will be fixed in 2.0
