### ISSUE TITLE
Return the direct IPTV URL instead of the re-stream URL

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-OpenWebif#831]
When clicking on the TV or Mobile icon to start a stream, return the original URL of the stream instead of a re-stream URL from the STB.

Today an IPTV stream generate this .m3u file:

> #EXTM3U 
> #EXTVLCOPT--http-reconnect=true 
> #EXTINF:-1,TV-Channel
> #EXTVLCOPT:program=17314 http://192.168.1.201:8001/1:0:1:43A2:0:0:0:0:0:1:http://provider:8000/live/login/password/17314.ts:TV-Channel

I would like to have an option that will let me set OpenWebif to return this kind of .m3u:

> #EXTM3U 
> #EXTVLCOPT--http-reconnect=true 
> #EXTINF:-1,TV-Channel
> #EXTVLCOPT:program=17314
> http://provider:8000/live/login/password/17314.ts

I think that there is no added value to re-stream a stream from the STB OpenWebif, it is better to provide the direct external link. Moreover most IPTV providers forbid to re-stream so most of the time this simply doesn't work.

**Comment by Schimmelreiter** [comment]
The added value is that it works for streams that can only be received on a specific line ... e.g. Telekom Enterpain TV can only be received on a Telekom internet connection.
If you are outside and connected to e.g. o2 cellular network or some WiFi which doesn't connect to the internet through Telekom, streaming of such a stream would fail.

Another benefit is, that some streams require additional work, e.g. setting up udpxy or stuff like that and thus plain won't work on other networks than the one you prepared for it.

And another one:
Some streams are restricted to specific regions. On the receiver you probably will have set up either only streams that work at the receiver's location .... or you will have performed steps to make them work ... the same can not be necessarily said about the client trying to stream via the OWIF.

The only advantage of passing the original URL on the other hand is that the stream doesn't need to go through the receiver's location upstream ... so yes, an option would be nice, but really just an option, as on the other hand, if you can stream it directly there is hardly any use for making things more complicated by fetching the URL from OWIF.

**Comment by pr2git** [comment]
Thanks for your explanation then I suggest to have another icon specific that will return the original URL so we keep all possibilities and we can also try them all because a global parameter won't satisfy all possible case if you mix-up different sort of streams.
And we should also extend this for service type 4097, 5001 & 5002.

**Comment by jbleyel** [comment]
One important hint.
IPTV sref have start with 4097.
Your example 
1:0:1:43A2:0:0:0:0:0:1:http://provider:8000/live/login/password/17314.ts:TV-Channel
is wrong and have to be 
4097:0:1:0:0:0:0:0:0:0:http://provider:8000/live/login/password/17314.ts:TV-Channel
or
4097:0:0:0:0:0:0:0:0:0:http://provider:8000/live/login/password/17314.ts:TV-Channel

**Comment by pr2git** [comment]
The stream are in .ts format so they can be played by the SoC like any other .ts stream.
4097 are used for other type than .ts to be played by Servicemp3.
Please explain why it is wrong.

**Comment by jbleyel** [comment]
IPTV sref have to start with 4097.
You can read the enigma2 source code and you will find out.
Many plugins and 3rd party tools need this.

**Comment by pr2git** [comment]
Yes because they are using other format than .ts (transport stream) if the format is not .ts than 4097 must be used.

**Comment by jbleyel** [comment]
/*
 * UNUSED variable from service reference is now used as buffer flag for gstreamer
 * REFTYPE:FLAGS:STYPE:SID:TSID:ONID:NS:PARENT_SID:PARENT_TSID:UNUSED
 *   D  D X X X X X X X X
 * 4097:0:1:0:0:0:0:0:0:0:URL:NAME (no buffering)
 * 4097:0:1:0:0:0:0:0:0:1:URL:NAME (buffering enabled)
 * 4097:0:1:0:0:0:0:0:0:3:URL:NAME (progressive download and buffering enabled)
 *
 * Progressive download requires buffering enabled, so it's mandatory to use flag 3 not 2
 */

**Comment by pr2git** [comment]
I know those options, but thanks ;-)
