### ISSUE TITLE
Make distinction between channels in the channel list

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-OpenWebif#832]
I have a channel list that mix up channels from:
DVB-C, DVB-S(2) (from different satellite) (and IPTV) for exemple TF1.

I can receive it from my cable provider, 19.2E, 13.0E, 5.0W when I am in the channel list on my STB it is easy for me to make the distinction between each channels by enabling the icon in front of the name.

But on OpenWebif I just saw this:

<img width="545" alt="capture d ecran 2018-08-05 a 00 31 40" src="https://user-images.githubusercontent.com/13857365/43680968-2e2cf400-9847-11e8-8d71-2ab9b58054f4.png">

Do you think possible to display an icon in front of the name to make a distinction between each different type?

**Comment by pr2git** [comment]
Here is what I saw in my STB channel list:

<img width="235" alt="capture d ecran 2018-08-05 a 00 37 31" src="https://user-images.githubusercontent.com/13857365/43680997-fc6e5fd4-9847-11e8-868b-cbe5ec3d47dd.png">

**Comment by jbleyel** [comment]
We can add an extra setting switch like "show picons" and the we can add the orbital position at the end of the channel name. The orbital position can also be DVB-C,DVB-T or IPTV.
Many users don't need this because they don't have different namspaces.

**Comment by pr2git** [comment]
It would be nicer to have it before the channel name because with a 5 digits approach you can cover them all:
xxx.xE
yyy.yW
DVB-T
DVB-C

So we have a nice alignment for this information.

But you can reuse the E2 settings, which is: 
Icon to the left of the service name:   config.usage.servicetype_icon_mode=1
Icon on the right of the service name: config.usage.servicetype_icon_mode=2
No icon:  config.usage.servicetype_icon_mode=0

This makes sense to reuse it since people that enable it, would probably like to see it too in OpenWebif.

**Comment by jbleyel** [comment]
We definitely do not use settings from the OSD GUI for the webinterface.
Icon on right needs a complete redesign.

You can switch to the theme "original-small-screen".

**Comment by pr2git** [comment]
Thanks I just test your change but this mention DVB-S or DVB-C... but the orbital position is not displayed. So it is an improvement, thanks but I am still unable to make a distinction between the different satellites for the same channel name.
For DVB-S I suggest that DVB-S test is replaced by the orbital position (which can be retrieve by the Namespace).

<img width="572" alt="capture d ecran 2018-08-09 a 00 40 38" src="https://user-images.githubusercontent.com/13857365/43868273-26dda374-9b6d-11e8-82c6-a24c7e4eb72d.png">

**Comment by jbleyel** [comment]
IPTV is 4097:xxx and not 1:xxx
That's  by definition and you have to change your bouquets.
The orbital position will be displayed if your namespace is correct.
You have to get the latest version.

**Comment by pr2git** [comment]
Enigma2 source code detect the IPTV channel by looking at "%3a//" or "%3A//" or "://" (since %3A is no longer mandatory) this is the proper way to check the service type for IPTV.

**Comment by pr2git** [comment]
Someone reusing the service reference of a DVB-S or DVB-C channel to assign it to the same channel in IPTV will saw wrong informations if you don't check properly for IPTV.

**Comment by jbleyel** [comment]
No, you are wrong.
Please check the code and test the latest source on your box first before you write something.


```
			#if '4097:' in $channel.ref
				<span class="channel-tag ST-IPTV">IPTV</span>
			#elif $channel.has_key('ns')
				#set $ns="DVB-S"
				#if 'DVB' in $channel.ns
					#set $ns=$channel.ns
				#end if
				<span class="channel-tag ST-$channel.service_type">$channel.service_type</span><span class="channel-tag NS-$ns">$channel.ns</span>
			#end if
```

**Comment by pr2git** [comment]
Just test an indeed end-user report was wrong, sorry next time I will test myself.
