### ISSUE TITLE
OWIF 1.3.3 unable to install wrong .ipk

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-OpenWebif#838]
I try to install manually the latest OWIF version and here is the result, based on the one found here:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/gh-pages
(Following the README.md explanation - Latest Package but adapted to pick up the very last one)

root@vusolo4k:/media/hdd/OWIF# opkg install ./enigma2-plugin-extensions-openwebif_1.3.3-e2openpluginsgit20180827_all.ipk 
Collected errors:
 * open_outer: Failed to open package './enigma2-plugin-extensions-openwebif_1.3.3-e2openpluginsgit20180827_all.ipk': Unrecognized archive format
 * open_outer: Failed to open package './enigma2-plugin-extensions-openwebif_1.3.3-e2openpluginsgit20180827_all.ipk': Unrecognized archive format
 * pkg_extract_control_file_to_stream: Failed to extract control.tar.* from package './enigma2-plugin-extensions-openwebif_1.3.3-e2openpluginsgit20180827_all.ipk'.
 * pkg_init_from_file: Failed to extract control file from ./enigma2-plugin-extensions-openwebif_1.3.3-e2openpluginsgit20180827_all.ipk.

Another command:

root@vusolo4k:/media/hdd/OWIF# ar -x enigma2-plugin-extensions-openwebif_1.3.3-e2openpluginsgit20180827_all.ipk 
ar: invalid ar magic
root@vusolo4k:/media/hdd/OWIF# ls -Fal enigma2-plugin-extensions-openwebif_1.3.3-e2openpluginsgit20180827_all.ipk 
-rw-r--r--    1 root     root         69981 Aug 28 09:16 enigma2-plugin-extensions-openwebif_1.3.3-e2openpluginsgit20180827_all.ipk

**Comment by jbleyel** [comment]
Duplicate #819
