### ISSUE TITLE
BouquetEditor: enable a on-mouseover on channel to see the channel details

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-OpenWebif#840]
When in the BouquetEditor, if we have several time the same channels (for exemple TF1) there is no way to make a distinction between the different one.
Would be nice to have the channel full details with a on-mouseover style pop-up.

Provider type frequency polarisation SR FEC Modulation InputStream Orbital position

And the URL for the IPTV channels.

**Comment by pr2git** [comment]
Thanks for the change but there are 3 problems:
- DVB-C channels are I think reported has Nan W
- The channels really West the orbital is not properly displayed should be 5.0°W in my case
- Only providing the orbital is not enough, on 5°W I can receive TF1 twice from different providers. Perhaps include the TP frequency can give an indication.
<img width="546" alt="capture d ecran 2018-09-14 a 22 55 13" src="https://user-images.githubusercontent.com/13857365/45575004-3339ab00-b872-11e8-9eb7-54c66ff9d33d.png">

**Comment by jbleyel** [comment]
Please provide the sref of the affected TF1 channels.

**Comment by pr2git** [comment]
Here it is:

On 5.0°W: not working
#SERVICE 1:0:19:601:6:20FA:DDE0000:0:0:0:
#SERVICE 1:0:19:191:4FB0:55F:DDE0000:0:0:0:

On DVB-C: not working
#SERVICE 1:0:1:2A31:6C:1:FFFF0000:0:0:0:
#SERVICE 1:0:19:4E88:C9:1:FFFF0000:0:0:0:

**Comment by jbleyel** [comment]
I need your lamedb and lamedb5 (if exists) 
/etc/enigma2/...

**Comment by pr2git** [comment]
No problem here it is.
[lamedb-Pr2.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/2385834/lamedb-Pr2.zip)

**Comment by pr2git** [comment]
Thanks but the HD / SD has now become totally meaningless, since we saw that channels start to use 1:0:1: for HD channels.  And I am still unable to make distinction between the same channels appearing several times on the same satellite but from different providers.

**Comment by jbleyel** [comment]
We don not remove the channel type.
see here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/js/bqe.js#L788
Thats a request of other users.

The provider is there. TOOLTIP!!!
