### ISSUE TITLE
Responsive-WebIF Design  didnt´t work at several boxes at openatv

### ISSUE THREAD

**Issue by mastertape** [E2OpenPlugins/e2openplugin-OpenWebif#841]
Since a few days the Responsive-WebIF Design didn´t work it will not load...
Some Reports are here..:
https://www.opena.tv/openatv-6-2-image-rueckmeldungen/42562-probs-mit-responsive-webif-und-stummschaltung-nach-update.html

**Comment by arn354** [comment]
No idea why it tries to load openwebif-1.2.17.min.js - as it should be at 1.2.18
obenwebif is enigma2-plugin-extensions-openwebif - 1.3.0+git3162+f4fa1e7-r0 
f4fa1e7 is latest commit hash

**Comment by arn354** [comment]
main.tmpl and main.pyo still have 
	<script type="text/javascript" src="js/openwebif-1.2.17.min.js"></script>
main.tmpl and main.pyo is current date

but it is build from f4fa1e7

**Comment by Schimmelreiter** [comment]
Vermutlich mal wieder shitquake ... im Quellcode steht ganz klar 1.2.18

**Comment by arn354** [comment]
nö -wohl übersehen - https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/d98545485ecac15449b3c056333fe46d9768e0bd

**Comment by mastertape** [comment]
Leider bin ich kein versierter coder... Da mein Bugreport nun geschlossen ist - bedeutet dies es gibt ne Lösung?

**Comment by madieatv** [comment]
ja.
