### ISSUE TITLE
[Request] Implement HLS to create an HTML5 player in OWiF

### ISSUE THREAD

**Issue by giopas** [E2OpenPlugins/e2openplugin-OpenWebif#845]
I'd like to propose the implementation of an HTML5 player within OWIF. The advantage would be to do not open different ports (8001 and 8002) anymore and to allow streaming contents within OWiF itself.

To do so it would probably needed to implement (either in OWiF or in the decoder firmware) a HLS protocol service and then to create an HTML5 interface (maybe using video.js).

What do you think?

**Comment by jbleyel** [comment]
I think you should read a little bit more about streaming, HLS, transparent proxy, python twisted web and you should know something about the stream format of your STB.

You can answer your request by yourself if you have done this.

Here are my answers depending on your box hardware and your box image:
* NO WAY
* ONLY TRANSCODING
* ONLY WITH A DIFFERENT STREAMPROXY

**Comment by giopas** [comment]
Thank you for your answer @jbleyel and yes, you are right that I have very limited knowledge of these things. The only thing I know is that there are players, like streamio[1], who can read video files in a repository, they are working on transcoding but they do not support streaming protocols.

As OWiF already provides a web interface to enigma2 systems, I was wondering if it could not possible to kind of merge the two features and make OWiF a full HTML5 video players of content received/streamed by the decoder.

Thanks

[1] https://www.stremio.com/
