### ISSUE TITLE
Expose genre from EPG

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#847]
Hi,

Would it be possible to expose the genre value stored in the EPG?

Such as having an `<e2genre>` tags in calls like epgnownext and epgservice?

Thanks in advance

**Comment by jbleyel** [comment]
The EPG have description and extended description and no genre.
Therefore -> NO

**Comment by phunkyfish** [comment]
Hmmm, then I don't understand why in EPG settings there is an option to select the "Country for EPG event genre information" and also an option in in UI settings to "Show event genre information".

I can see genre_id defined in: https://github.com/OpenViX/enigma2/blob/master/lib/dvb/epgcache.cpp

`typedef struct epgdb_title_s
{
	uint16_t	event_id;
	uint16_t	mjd;
	time_t		start_time;
	uint16_t	length;
	uint8_t		genre_id;
	uint8_t		flags;
	uint32_t	description_crc;
	uint32_t	description_seek;
	uint32_t	long_description_crc;
	uint32_t	long_description_seek;
	uint16_t	description_length;
	uint16_t	long_description_length;
	uint8_t		iso_639_1;
	uint8_t		iso_639_2;
	uint8_t		iso_639_3;
	uint8_t		revision;
} epgdb_title_t;`

Also there is https://github.com/OpenViX/enigma2/blob/master/lib/python/Components/Converter/genre.py which let's you convert from the genre id to the text (fist 4 bits is major genre number and the second 4 are minor genre).

**Comment by phunkyfish** [comment]
Why not include the tag if the image supports it (i.e. it exists), and omit
if it doesn't?

Tag could be <e2genre type="genreId">Converted Text</e2genre>

**Comment by jbleyel** [comment]
I think you don't understand my change.
You need to use /api requests and not /web.
XML is from the 80s.

**Comment by phunkyfish** [comment]
I'm working on the Enigma2 PVR plugin for Kodi. They use XML for
everything. I could change to JSON but it would take me an amount of time
as everything from OpenWebIf is XML currently. Do you plan to retire the
XML API?

**Comment by phunkyfish** [comment]
Could also use a default entry for when there is no genre tag.

**Comment by jbleyel** [comment]
no .. xml will not removed but it's old school .. api first and then xml

**Comment by phunkyfish** [comment]
Got you. So changes go to API first and then to XML. Cool.

I will put it on the backlog to move to Json.

**Comment by jbleyel** [comment]
Do you have any astra 19,2 channel and a event with epg including genre info? 
I don't find one.

**Comment by phunkyfish** [comment]
I’m on 28,2.

I’m currently using XMLTV to get genre. Let me switch to OpenTV using crossEPG and I’ll check.

**Comment by jbleyel** [comment]
I can only test on astra 19,2.

**Comment by phunkyfish** [comment]
Crap, so what do we do?

**Comment by phunkyfish** [comment]
How about a script to randomly add genre IDs to your EPG?

**Comment by jbleyel** [comment]
I have found some channels.
Please test the last commit?

**Comment by phunkyfish** [comment]
Amazing. Works really well. Here's an example: 
`<e2eventgenre>Leisure hobbies: gardening</e2eventgenre>`

Would it also be possible to get the genre id included? So for the above genre it's 0xA7 or 167. Essentally just the byte value

So either:

`<e2eventgenre id=167>Leisure hobbies: gardening</e2eventgenre>`

Or

`<e2eventgenre>Leisure hobbies: gardening</e2eventgenre>
<e2eventgenreid>167</e2eventgenreid>`

**Comment by phunkyfish** [comment]
Decimal or hex for the ID, either would be perfectly fine. This allows users to do their own mappings on the client side if they wish.

**Comment by jbleyel** [comment]
The id is a two part integer.
Main genre and sub genre.
Where do you find the number 167?

**Comment by phunkyfish** [comment]
Each number is 4 bits. So with 0xA7, the first number is 10 and the second
is 7. So (10 x 16) + 7 = 167.

0xA7 == 167 == 10100111

So you have hn is 1010 and ln is 0111, make sense?

**Comment by phunkyfish** [comment]
hn is an unsigned integer from 0-15
ln is an unsigned integer from 0-15

**Comment by jbleyel** [comment]
Got it.
I will check this.

**Comment by phunkyfish** [comment]
Thanks!

**Comment by zehnerGIT** [comment]
Thanks for the addition. 
I've updated OpenWebIf from https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/gh-pages/enigma2-plugin-extensions-openwebif_1.3.5-e2openpluginsgit20181008_all.ipk and can see genres even with my pure epg (no xmltv or rytec updates).

Perhaps two small issues:

- We have 3 big players here in germany, Public-Broadcasting-Services, RTL-group and Pro7-Sat1-group. I can find genres in PBS (I've checked ARD, ZDF, arte) and in RTL (I've checked RTL, RTLII), but Pro7-Sat1 is always empty (I've checked Sat1, Pro7, Pro7 Maxx). Don't they send the id or is this a problem in the code?

- `<epgmulti>` should be the fastest way to read all epg data. Perhaps you should integrate the genre tags there too, then all clients can use it

**Comment by phunkyfish** [comment]
Not all providers supply a genre ID. 

On the second point I’ll leave that to @jbleyel

**Comment by phunkyfish** [comment]
@jbleyel saw your latest commit. Will test this evening.

**Comment by phunkyfish** [comment]
This works really well. Thank you. I did not find any issues. 

Can I ask if this information is also stored in recordings?

**Comment by jbleyel** [comment]
No recordings do not have this info.
This needs to be changed in enigma2
