### ISSUE TITLE
error after install (cannot import name Encoding Resource Wrapper)

### ISSUE THREAD

**Issue by mallaiko** [E2OpenPlugins/e2openplugin-OpenWebif#848]
I have this error after install (cannot import name Encoding Resource Wrapper).

how do I do?
![img_3705](https://user-images.githubusercontent.com/43883685/46537867-4a384f80-c8aa-11e8-8276-9f2fe0f88d87.JPG)

**Comment by jbleyel** [comment]
You have not all needed python twisted modules.
Please contact you image provider.
