### ISSUE TITLE
/web/deviceinfo add drive path/mount to Hdd tags

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#850]
Only model, free and total space are given. Could drive path/mount also be included similar to the Box Info screen on the UI?

**Comment by phunkyfish** [comment]
What I want to do is derive a total for drives that are used for recordings.

**Comment by zehnerGIT** [comment]
Perhaps you can use "web/about" for this. If I look at the "e2hddinfo"-element there, it lists only my hdd, not my also connected usb stick, only "deviceinfo" lists both.
"web/settings" has many info about drives, but most of them depend on installed addons, so not ideal to get a value for all distributions

**Comment by phunkyfish** [comment]
I saw that but that assumes it's the installed HDD is what is used for recordings. If they are using USB it wouldn't list there.

**Comment by jbleyel** [comment]
The request /web/about needs to redesign if you need more info.
This will breaks 3rd party usage.
Therefore we do not change the result of /web/about.

You have 2 options:
* use /web/deviceinfo
* use /api/about

**Comment by phunkyfish** [comment]
So the info could be added to /web/deviceinfo?

**Comment by jbleyel** [comment]
What info? Mount? -> see last commit

**Comment by phunkyfish** [comment]
You are way ahead of me!
