### ISSUE TITLE
Befehl zum stoppen einer Aufnahme

### ISSUE THREAD

**Issue by AdlerCentauri** [E2OpenPlugins/e2openplugin-OpenWebif#851]
Hallo, gibt es einen direkten Befehl den ich z.B. in einen Browser eingeben kann um eine aktuell laufende Aufnahme zu stoppen? Danke

**Comment by jbleyel** [comment]
/api/timertogglestatus
oder
/web/timertogglestatus

Damit wird der Status von einem Timer geändert.
Die Parameter sind **sRef**, **begin** und **end**

Über /web/timerlist oder /api/timerlist kann man die Werte bekommen.
