### ISSUE TITLE
EPG-Details, leeres PopUp Fenster. EPG empty popup.

### ISSUE THREAD

**Issue by sgse** [E2OpenPlugins/e2openplugin-OpenWebif#855]
Hello :-)
wenn da mal bitte jemand nach sehen würde was da hakt.

https://www.opena.tv/openatv-6-2-image-rueckmeldungen/43327-webif-zeigt-keine-epg-details.html#post371592

Danke.

**Comment by arn354** [comment]
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: http://gbquad4k.local/themes/absb/plugins/bootstrap/css/bootstrap.min.css
Source-Map-Adresse: bootstrap.min.css.map[Weitere Informationen]

**Comment by arn354** [comment]
Fehler ist nur im responsive design
