### ISSUE TITLE
Nicht alle Ordner in 3rd Party Apps sichtbar

### ISSUE THREAD

**Issue by Krocko** [E2OpenPlugins/e2openplugin-OpenWebif#856]
Wenn ich im Movie Player einen neuen Ordner erstelle (also direkt auf der Box), dann ist dieser Ordner auch im OpenWebif und in externen Apps sichtbar.
Erstelle ich aber die Ordner über einen FTP Clienten, sind sie zwar im OpenWebif sichtbar, nicht aber in externen Apps.
Ich glaube, das Problem ist das gleiche wie #303. 
Der Abruf der Ordner erfolgt ja in den externen Apps über `<box>/api/getlocations`.
Wo ist jetzt der Unterschied, das die Ordner in OpenWebif sichtbar sind?

**Comment by jbleyel** [comment]
/getlocations liefert die Liste der "Recording Locations" -> /etc/enigma2/settings -> config.movielist.videodirs

Das steht in #303 auch schon drin.
