### ISSUE TITLE
Per Api prüfen ob ein Transponder belegt ist, möglich?

### ISSUE THREAD

**Issue by iBoarder** [E2OpenPlugins/e2openplugin-OpenWebif#857]
Hallo, gibt die Api die Möglichkeit zu prüfen, ob Transponder belegt sind?

Als bsp. Receiver mit Single-Tuner: RTL wird aufgenommen, dann sind die ProSieben Transponder belegt und nicht anzuschauen. Kann man das Abfragen?

Danke

**Comment by jbleyel** [comment]
Nein, das ist nicht als API verfügbar.
