### ISSUE TITLE
Set config.recording.margin_before and config.recording.margin_after using /web

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#859]
Looking to be able to change these from the Enigma2 addon in Kodi.

I can read the config in /web/settings however I can't see from the code how to set them.

**Comment by phunkyfish** [comment]
Did not realise saveconfig was POST. Closing 😉

**Comment by phunkyfish** [comment]
Re-opening, saveconfig is not accessible via the web api.

Would it be possible to expose these as recording config possibly?

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/7fd4226ce3c1118a0a670fb0126cd9dbb7e40094/plugin/controllers/web.py#L1822

**Comment by phunkyfish** [comment]
I’ve tried to POST to this with a key and value but I get a page not found error.

Also tried with a Get request, no joy.

**Comment by jbleyel** [comment]
I think you are doing something wrong.
See here -> 

function saveConfig(key, value) {
	$.ajax({ url: "/api/saveconfig?key=" + escape(key) + "&value=" + escape(value), cache: false, async: true, type: "POST"}).done(function() { 
		if (key == "config.usage.setup_level") {
			// TODO: refresh the menu box with new sections list
			$("#content_container").load(lastcontenturl);
		}
	});
}

**Comment by phunkyfish** [comment]
Ah, I'm using /web, that's the problem!

Thanks!

**Comment by phunkyfish** [comment]
This is what confused me:

Args:
			request (twisted.web.server.Request): HTTP request object
		Returns:
			HTTP response with headers
		.. http:post:: /web/saveconfig

The code says /web!
