### ISSUE TITLE
DreamOS!

### ISSUE THREAD

**Issue by Billy3182** [E2OpenPlugins/e2openplugin-OpenWebif#860]
Hallo

Gibt es das Plugin auch für das DreamOS OE 2.5?

**Comment by koivo** [comment]
Wozu? Die Dreamleute machen doch sonst auch alles selber und "viel" "viel" besser als jemand anders.
Zumindest behaupten die das immer.

**Comment by Billy3182** [comment]
was soll ich jetzt sagen?
wollte den Alexa Skill nutzen, aber das funktioniert mit dem OE2.5 nicht.

**Comment by koivo** [comment]
Ist der Alexa Skill nicht exklusiv nur für dieses vti Image?
Ansonsten installiere eben ein Image aus der Open Alliance und es ist dabei.

**Comment by Billy3182** [comment]
Die Images funktionieren nicht richtig, hab es probiert!
Mit den Satip Client gibt's Probleme.

**Comment by koivo** [comment]
Es geht hier um das opewebif. Frag im entsprechenden Forum nach wo der Satip Client nicht funktioniert.
