### ISSUE TITLE
Move recording to other folder?

### ISSUE THREAD

**Issue by DrMichael** [E2OpenPlugins/e2openplugin-OpenWebif#862]
Would it be possible to add the possibility to move recordings to another folder?

**Comment by jbleyel** [comment]
Do you have an iPhone or iPad?

**Comment by littlesat** [comment]
Yep... see timeredit

**Comment by jbleyel** [comment]
Then u should use e2Remote Pro. ;-)

**Comment by jbleyel** [comment]
will be fixed in 2.0
