### ISSUE TITLE
Welches ist die aktuelle Openwebif Version?

### ISSUE THREAD

**Issue by iBoarder** [E2OpenPlugins/e2openplugin-OpenWebif#865]
Hallo, was ist denn die aktuelle stabile Openwebif Version? Und wo bekommt man die her?

Danke

**Comment by danyial** [comment]
Schließe mich an... Die 1.3.5 ist leider nicht lauffähig

**Comment by atvcaptain** [comment]
in denen openATV image wird täglich gebaut und hat immer die aktuelle version , gibt es für jede box das image also schaut da einfach

**Comment by iBoarder** [comment]
VTi Image hat leider nur 1.2.8 drin

**Comment by atvcaptain** [comment]
vti ist close image und alles geheim wenn es nicht geht bitte mit vti klären
