### ISSUE TITLE
Add e2serviceprovider to getservices call when an sRef is passed as an argument

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#884]
I can't see any other way to get provider name outside of the current live channel.

**Comment by jbleyel** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/7fd4226ce3c1118a0a670fb0126cd9dbb7e40094/plugin/controllers/web.py#L487

**Comment by phunkyfish** [comment]
Sorry, my statement was ambiguous.

I’m not looking to pass provider to the API call I’m looking to return it with each service name and reference in the result.

**Comment by phunkyfish** [comment]
Ah, I should have spent a bit more time reading the code.

If I append “&provider=1” to the API call I don’t see the extra info added to the result.

**Comment by jbleyel** [comment]
Picon and provider are optional and therefor you have to use the json api.

**Comment by phunkyfish** [comment]
So no way to retrieve via XML? The kodi PVR subsystem only provides for XML parsing not JSON so anything bar the simplest json os cumbersome to process.

**Comment by phunkyfish** [comment]
Any reason why it’s optional and not default?

**Comment by jbleyel** [comment]
To prevent errors on 3rd party usage.
Therefore you need to use json  /api/...

**Comment by phunkyfish** [comment]
Ok, thanks
