### ISSUE TITLE
New Stream Info in /api/about, error on channel name

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#892]
Just got a chance to test this. It works well for satellite tuners but for terrestrial the name is "(unknown service)".

Is Type = S supposed to mean satellite and Type = T for terrestrial?

Running on a Ultimo4k with latest OpenVix

**Comment by jbleyel** [comment]
S = Stream , T = Transcoding

**Comment by phunkyfish** [comment]
Thanks!

**Comment by phunkyfish** [comment]
@jbleyel I've found the issue. It's nothing to do with DVB-T vs DVB-S it's to do with the service reference.

For example for the channel "BBC One NI HD" the stream API returns the ```1:0:1:1B1F:802:2:11A0000:0:0:0``` as the service reference. The reference is in fact ```1:0:19:1B1F:802:2:11A0000:0:0:0```. If the lookup was only on the unique part ```1B1F:802:2:11A0000``` it should work ok.

**Comment by phunkyfish** [comment]
I think the same behaviour happens with Tuner Info.

**Comment by jbleyel** [comment]
What you mean with "stream api returns"?

**Comment by phunkyfish** [comment]
In these lines:

```
					for x in streamServer.getConnectedClients():
						servicename = ServiceReference(x[1]).getServiceName() or "(unknown service)"
```

x[1] is ```1:0:1:1B1F:802:2:11A0000:0:0:0``` instead of ```1:0:19:1B1F:802:2:11A0000:0:0:0```

**Comment by phunkyfish** [comment]
At least think that's what's happening. For any channels that start with ```1:0:1:``` and end with ```:0:0:0``` it works just fine.

**Comment by phunkyfish** [comment]
It could also be fixed in ServiceReference. I will create an upstream issue for it.
