### ISSUE TITLE
Web Inteface not loading on latest IPK 2019-04-01

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#893]
Mobile UI, XML and JSON Apis are ok.

Just the main desktop gui does not load:

![screen shot 2019-01-05 at 11 22 45](https://user-images.githubusercontent.com/4601187/50723918-4e0f8400-10dc-11e9-9c21-06ee4cb65144.png)

**Comment by phunkyfish** [comment]
openwebif-1.2.18.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):198 Uncaught ReferenceError: initJsTranslation is not defined
    at (index):198
(index):225 Uncaught ReferenceError: SetLSValue is not defined
    at (index):225
(index):209 Uncaught ReferenceError: directlink is not defined
    at HTMLDocument.<anonymous> ((index):209)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.K (jquery.min.js:2)

**Comment by phunkyfish** [comment]
Only openwebif-1.2.19.min.js is in that directory and not openwebif-1.2.18.min.js

**Comment by jbleyel** [comment]
This is an installer issue.
You need to remove the compiled cheetah templates if they where updated.
In this case:
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/main.pyo

**Comment by phunkyfish** [comment]
Might just be a caching problem

**Comment by jbleyel** [comment]
Yes .. old browser cache can also cause this issue.

**Comment by phunkyfish** [comment]
I tried clearing the cache but no change. Your solution fixed it. Thanks you.
