### ISSUE TITLE
request of an additional language parameter for transcoding setting

### ISSUE THREAD

**Issue by anudanan** [E2OpenPlugins/e2openplugin-OpenWebif#895]
A user can´t select today by transcoded streaming of channels or recorded movies with more than one audiostream which audiostream is used by in the transcoded stream. After discussion with erik slagter it is random today which language goes into the transcodes stream.
So it would by usefull to select under the transcoding settings a preferred language to integrate into the transcodes stream. This preferred language can also be include in the URL together with the other parameter which is implemented in stream.py
Maybe it is a good idea to define with Erik which language tokens are userfull to use. I don´t know the number or enums for the languages. My VLC shows me for german audio stream the word "Deutsch", for english "Englisch" and for french "Französisch"

On optional idea may be to have a second parameter to define which audiostream (0,1,2 ..) will by used as a fallback if language token can´t found correctly

**Comment by anudanan** [comment]
If seen that streamproxy goes through the different streams and give the hardware one of the found audio PID to transcode that. It seem so that is only possible for one audio PID. The language parameter which I requested can give the streamproxy a change to found a  audiostream with a matching language. It is not to important which audiostream is used if there a more than one with the same language. But today often you get a false language stream.

For me and erik has a similar feeling is that a quick ease solution.  The language parameter do the same as the other parameter of the transcoding setup in openwebif. They give the transcoding code some more informations which it can use
 
A better solution is to integrate the transcoding code into enigma but that is a hard work.
Today I have no save way to see transcodes streams from movies with different languages included when I would like to get germen language. In the most time I get english audio.

**Comment by jbleyel** [comment]
Hi @anudanan,

A default language parameter in transcoding settings sounds good to me.
In my case.
Many channels have german and english but german is the first audio.
I prefer english if available.
Therefor i can't use transcoding for these channels.
A def lang can fix this by setting to english.

**Comment by anudanan** [comment]
Yes, that was also my thought

**Comment by jbleyel** [comment]
This needs to integrate in enigma2 first if possible.

**Comment by anudanan** [comment]
Why is it better in enigma2? OWIF has some other parameter for transcoding, why is the language parameter to different from that idea. It is a parameter to give some informations to the transcoding part which handels the stream and can then better select the language stream for transcoding, The transcoding HW can only transcode one audio stream

**Comment by jbleyel** [comment]
I think you don't understand. The extra option/parameter in OWF has no effect.
All existing parameters are checked and apply in enigma2.
The audio selection needs to implement here ->
https://github.com/eriksl/streamproxy
and here -> 
https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/streamserver.cpp
and in all other distros. OpenVix, OpenATV, ...

**Comment by anudanan** [comment]
yes, I know that the selection of the audiostream must implement in the streamproxy. But the suggestion which language the user want is similar to the bitrate and other parameter which are configured in OWIF. That was the idea to give only a suggestion to streamproxy and that the streamproxy can select the right one if possible.

**Comment by jbleyel** [comment]
No, this extra setting needs to implement in transcoding settings plugin.

**Comment by anudanan** [comment]
That is an other option. I discuss it with erik
thanks
