### ISSUE TITLE
Location to store timer?

### ISSUE THREAD

**Issue by DrMichael** [E2OpenPlugins/e2openplugin-OpenWebif#901]
Would it be possible im OWIF to provide the location, where the timer would be stored? Possibly with the possibility to change it?

**Comment by jbleyel** [comment]
It's there already. Timeredit -> Location

**Comment by DrMichael** [comment]
Hmmm, do I have an old version?

![2019-01-13 19_00_59-vu solo4k - openwebif](https://user-images.githubusercontent.com/8087682/51088887-b0642680-1765-11e9-8389-915c2ca96462.png)

**Comment by DrMichael** [comment]
But I cannot set a new arbitrary location, right?

**Comment by jbleyel** [comment]
Yes, new location can be set here.
<img width="224" alt="bildschirmfoto 2019-01-13 um 19 08 31" src="https://user-images.githubusercontent.com/964927/51088996-b60e3c00-1766-11e9-941d-27c921978da6.png">

This is not available for new design.
