### ISSUE TITLE
Grab screenshot save as... doesn't save the current image but the next one

### ISSUE THREAD

**Issue by pr2git** [E2OpenPlugins/e2openplugin-OpenWebif#902]
Connect to OpenWebif  (it is set for High Resolution)
Watch image on the TV and press refresh button in OpenWebif
Wait for the image to change on your TV and press the right click and select save as... in your browser.

Check the save as... resulting image, it is not the one currently displayed in OpenWebif but the image that was broadcasted when right click - save as... was selected.

So it's not possible to save the image that is currently displayed in OpenWebif, there is some sort of automatic refresh done before saving.

Can you please fix this so that we are able to save the image displayed in OpenWebif grab screen?

**Comment by ims21** [comment]
I have saved always it, what was in owif in window. I can save picture f.eg. 5 minuts old...
Try uncheck "Actualise each x seconds" for it.

**Comment by pr2git** [comment]
Of course Automatic refresh is not enable otherwise this ticket won't make sense.
I try it with Google Chrome both on Mac, Windows and I have the same issue.

**Comment by RobvanderDoes** [comment]
I can confirm this issue. I've noticed this since aong time.
On saving the current image is grabbed and saved, not the one displayed in OWEBIF.
This is browser independant.

**Comment by ims21** [comment]
I cannot confirm it.

I tried wait 2 minuts now again and still is stored picture displayed in Owif in "Screenshot (All)".
Save as ... put name ... store ... then open in W10 on notebook and same picture as i have still in Owif.

W10 + any my box with PLi + Firefox.

Tried save still same picture in Owif once - with service_ser as name ... stored, open in W10 - staill same.

**Comment by pr2git** [comment]
Firefox is not affected by this bug I just try it and you are right no bug with it.
So the problem seems specific to Google Chrome.
I want to give a try with M$ Edge (I only use it to download Google Chrome) but it doesn't seem capable to access any on my local devices thanks to there IP address so I cannot test it.

**Comment by RobvanderDoes** [comment]
I can't confirm Firefox not being affected by this. It's my commonly used browser, and it surely shows this bug.

**Comment by ims21** [comment]
M$ Edge works well too (it do not put service_ref as filename only). I am not using moloch-chrome, but I could try it on son's pc home

**Comment by ims21** [comment]
Tried Chrome - problem exist. 


Firefox  - ok
Edge - ok
Chrome - problem

**Comment by ims21** [comment]
I put debug string to grab.py to class GrabRequest under init and saw, when is run grabing.

For chrome is called grabing once again !!!, when is used "right-Save picture as..." 
It must be somewhere in .js for part for "right-save as" and for Chrome only, imho

**Comment by jbleyel** [comment]
This is probably by design and can be fixed by changing the header.

This is the current header for the grab request.
_Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0_

**Comment by ims21** [comment]
As I saw, Firefox take it from cache and save true picture. When is in FF cache disabled and cleared, it call with "SaveAs" new grab same as crome and is saved new (wrong) picture.  But chrome with enabled/disabled cache do not take it from cache, but always run grab (=> save wrong picture).

It means, that chome only respects header for grab request ?

**Comment by RobvanderDoes** [comment]
Ah, that explains it. I have cache disabled in FF.

**Comment by ims21** [comment]
In this time in Chrome you can use: R-'Copy Image' and then somewhere Paste...

As I tried, for Chrome helps remove in header 'no-store' only, but then not works Refresh and Autorefresh more for Chrome.

**Comment by jbleyel** [comment]
Please test!!!
You need to refresh the js or clear the cache.

**Comment by pr2git** [comment]
For Google Chrome it is fixed, so i will close this ticket.
Thanks for your investigations and solution.

**Comment by RobvanderDoes** [comment]
But using Firefox I still experience the same issue.
