### ISSUE TITLE
FB Mut@nt HD60 falsche Tastenbelegung bei vollständiger Fernbedienung im OpenWebIF

### ISSUE THREAD

**Issue by 420Dope** [E2OpenPlugins/e2openplugin-OpenWebif#907]
Die Tastenbelegung von der Mut@nt HD60 bei der vollständigen Fernbedienung im OpenWebIF sind falsch.
https://www.opena.tv/mut-nt-hd60/45296-flasche-tastenbelegung-bei-vollstaendiger-fernbedinung-im-openwebif.html

**Comment by jbleyel** [comment]
Einfach die passende html Datei hier suchen.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/master/plugin/public/static/remotes
Dann die Codes auf der Box ändern und wenn die passen, dann hier als pull senden.
