### ISSUE TITLE
ConfigText is not possible to use in OWIF setting Menus

### ISSUE THREAD

**Issue by anudanan** [E2OpenPlugins/e2openplugin-OpenWebif#917]
If a plugin has a setup.xml file for using by OWIF setting menu, the plugin parameter type ConfigText does not work in OWIF.   
I think in config.tmpl there is not template for ConfigText parameter

Is not urgent, but I have seen is by testing some new parameters for trancodingsetup plugin

**Comment by jbleyel** [comment]
What exactly setting do not work?

**Comment by anudanan** [comment]
Example

a additional line in
plugin.py of transcodingsetup plugin


`config.plugins.transcodingsetup.testtext= ConfigText(default = "xxx")`

in setup.xml of that plugin then add  the line for testtext

`<setupxml>
	<setup key="transcoding" title="Transcoding Setup" showOpenWebIF="1">
		<item level="0" text="Bitrate">config.plugins.transcodingsetup.bitrate</item>
		<item level="0" text="Resolution">config.plugins.transcodingsetup.resolution</item>
		<item level="0" text="Language">config.plugins.transcodingsetup.testtext</item>
	</setup>
</setupxml>

After that in OWIF no parameter testtext is in the transcodingsetupmenu seen.
`
If have debugged getConfigs in controllers/models and the parameter was collected in config but the template config.tmpl has no methode for text type, only for select, checkbox, multicheckbox and number

`<div id="content_main">
	<h3 class="ui-widget-header">$title</h3>
	<table id="configuration">
		#for $config in $configs:
			#if $config.data.type == "select"
				$select($config)
			#elif $config.data.type == "checkbox"
				$checkbox($config)
			#elif $config.data.type == "multicheckbox"
				$multicheckbox($config)
			#elif $config.data.type == "number"
				$number($config)
			#end if
		#end for
	</table>
</div>`

**Comment by jbleyel** [comment]
do you have any other setting with ConfigText
I don't have "config.plugins.transcodingsetup.testtext"

**Comment by anudanan** [comment]
Do you have the plugin .py ans setup.xml of transcodingsetupplugin?

I think you can modify the config.plugins.transcodingsetup.port from ConfigInteger zu ConfigText in the beginning of plugin.py
With ConfigInteger you see the port and with ConfigText no in OWIF

You must include ConfigText from config in plugin.py

**Comment by jbleyel** [comment]
i will check this

**Comment by jbleyel** [comment]
Please try this config.tmpl ->
```

#def select($config)
<tr>
<td>$config.description</td>
<td>
	<select id="$config.path" onchange="saveConfig('$config.path', this.value);">
		#for $choice in $config.data.choices
			#if $config.data.current == $choice[0]
				<option value="$choice[0]" selected="true">$choice[1]</option>
			#else
				<option value="$choice[0]">$choice[1]</option>
			#end if
		#end for
	</select>
</td>
</tr>
#end def

#def checkbox($config)
<tr>
<td>$config.description</td>
<td>
	#if $config.data.current
		<input type="checkbox" id="$config.path" checked="true" onclick="saveConfig('$config.path', this.checked);" />
	#else
		<input type="checkbox" id="$config.path" onclick="saveConfig('$config.path', this.checked);" />
	#end if
</td>
</tr>
#end def

#def multicheckbox($config)
<tr>
<td>$config.description</td>
<td>
	#for $choice in $config.data.choices
		#if $choice in $config.data.current
			<input type="checkbox" id="${config.path}_${choice}" checked="true" onclick="saveConfig('$config.path', $choice);" />
		#else
			<input type="checkbox" id="${config.path}_${choice}" onclick="saveConfig('$config.path', $choice);" />
		#end if
		$choice
	#end for
</td>
</tr>
#end def

#def number($config)
<tr>
<td>$config.description</td>
<td>
	<input type="text" id="${config.path}" value="$config.data.current" onkeydown="numberTextboxKeydownFilter(event);" onchange="saveConfig('$config.path', this.value);">
</td>
</tr>
#end def

#def text($config)
<tr>
<td>$config.description</td>
<td>
	<input type="text" id="${config.path}" value="$config.data.current" onchange="saveConfig('$config.path', this.value);">
</td>
</tr>
#end def

<div id="content_main">
	<h3 class="ui-widget-header">$title</h3>
	<table id="configuration">
		#for $config in $configs:
			#if $config.data.type == "select"
				$select($config)
			#elif $config.data.type == "checkbox"
				$checkbox($config)
			#elif $config.data.type == "multicheckbox"
				$multicheckbox($config)
			#elif $config.data.type == "number"
				$number($config)
			#elif $config.data.type == "text"
				$text($config)
			#end if
		#end for
	</table>
</div>
```

**Comment by anudanan** [comment]
That works. Thanks
