### ISSUE TITLE
Choices with empty string "" doesn´t work

### ISSUE THREAD

**Issue by anudanan** [E2OpenPlugins/e2openplugin-OpenWebif#918]
The autolanguage choices for the 4 autolanguage options in openpli are

`("", _("None")),
		("orj dos ory org esl qaa und mis mul ORY ORJ Audio_ORJ", _("Original")),
		("ara", _("Arabic")),
		("eus baq", _("Basque")),
		("bul", _("Bulgarian")),
		("hrv", _("Croatian")),
		("chn sgp", _("Chinese - Simplified")),
		("twn hkn",_("Chinese - Traditional")),
		("ces cze", _("Czech")),
		("dan", _("Danish")),
		("dut ndl nld", _("Dutch")),
		("eng qaa", _("English")),
		("est", _("Estonian")),
		("fin", _("Finnish")),
		("fra fre", _("French")),
		("deu ger", _("German")),
		("ell gre", _("Greek")),
		("heb", _("Hebrew")),
		("hun", _("Hungarian")),
		("ind", _("Indonesian")),
		("ita", _("Italian")),
		("lav", _("Latvian")),
		("lit", _("Lithuanian")),
		("ltz", _("Luxembourgish")),
		("nor", _("Norwegian")),
		("fas per fa pes", _("Persian")),
		("pol", _("Polish")),
		("por dub Dub DUB ud1", _("Portuguese")),
		("ron rum", _("Romanian")),
		("rus", _("Russian")),
		("srp", _("Serbian")),
		("slk slo", _("Slovak")),
		("slv", _("Slovenian")),
		("spa", _("Spanish")),
		("swe", _("Swedish")),
		("tha", _("Thai")),
		("tur Audio_TUR", _("Turkish")),
		("ukr Ukr", _("Ukrainian"))]`

The default is none with value ""
In OWIF it is possible to change to other values but a change back to none is not possible. The old value was not changed

Testcase:
Goto autolanguage parameter 1:
change from none to german
goto an other paramater
goto to autolanguage parameter 1
change from german to none
no erro comes but if you go later to this parameter is has the german value "deu ger"

I think the handling of an empty string is the reason for that.

I´ve haven´t found it by myself in your sources so I hope you found the reason

**Comment by anudanan** [comment]
I´ve make a little debugging and found out that this saveConfig
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/c72c4c01e69e69adea8501df3238594dbacc3dd1/plugin/controllers/models/config.py#L124
wasn´t called if the choice has an empty string "". Only a call is seen if the string is not empty

**Comment by jbleyel** [comment]
I have test this with openatv and i can't reproduce your problem.
The request for "None" in my openwebif is "---" and not ""

<img width="533" alt="bildschirmfoto 2019-02-24 um 19 55 48" src="https://user-images.githubusercontent.com/964927/53303729-42377700-386e-11e9-83ce-0b14a2715c73.png">

**Comment by anudanan** [comment]
Ah, than it is logical that you can´t reproduce it
Can you change the python file with the definition of the choices of openatv to reproduce st?

**Comment by anudanan** [comment]
Here is the openatv lib/python/Components/UsageConfig.py file
https://github.com/openatv/enigma2/blob/6.2/lib/python/Components/UsageConfig.py
you can copy it to your box into the 
/usr/lib/enigma2/python/Components 
directory and change the "---" into "" for none in line 868  to reproduce it

**Comment by jbleyel** [comment]
This is not an option for me.
Please add a print here (after line 156).

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/c72c4c01e69e69adea8501df3238594dbacc3dd1/plugin/controllers/models/config.py#L156

`print value
`

and check if this line was called on your box.

**Comment by anudanan** [comment]
If have made a print after line 124 direct as the first line of configSave some hours ago and have seen that there is only a call to saveConfig if the value is not ""

def saveConfig(path, value):
	print value
try:
		cnf = get_config_attribute(path, root_obj=config)
	except Exception as exc:

So the problem must be earlier in the code

**Comment by jbleyel** [comment]
please add a print here.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/8b92fc05ac5fbd49a1f518ebeca4f5fe353dd7bb/plugin/controllers/web.py#L1877

**Comment by anudanan** [comment]
ok, I will do it tomorrow. My boxes are in used this evening
Thanks for supporting

**Comment by jbleyel** [comment]
i have found the problem.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/8b92fc05ac5fbd49a1f518ebeca4f5fe353dd7bb/plugin/controllers/web.py#L70

**Comment by anudanan** [comment]
If red the source code 
what do you think about this codeline here?
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/8b92fc05ac5fbd49a1f518ebeca4f5fe353dd7bb/plugin/controllers/web.py#L70

**Comment by anudanan** [comment]
I will change my code tommorrow with your commit changes and see if it works ;-)

thx

**Comment by anudanan** [comment]
If have tested it now. It works. thx
