### ISSUE TITLE
Bug - First two events in call to /web/epgservice or /api/epgservice will have no e2eventgenre

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#919]
Regardless of the channel selected this will be the case. I wonder is this somehow overwritten by the now and next updates to the EPG?

For any I have checked there is a genreid associated with the events in prior calls to epgservice.

**Comment by jbleyel** [comment]
I get genre for the first 2 items if i call /epgservice.
YES. It's now and next.

**Comment by phunkyfish** [comment]
Hmmm, ok. Let me dig a bit further. It’s possible my provider does not include genre for now and next.

**Comment by phunkyfish** [comment]
Here's a snippet, no matter which sref I call against the first 2 are always 0:

`<e2eventlist>
<e2event>
<e2eventid>901</e2eventid>
<e2eventstart>1551106800</e2eventstart>
<e2eventduration>3600</e2eventduration>
<e2eventcurrenttime>1551107044</e2eventcurrenttime>
<e2eventtitle>Rumpole of the Bailey</e2eventtitle>
<e2eventdescription>
Rumpole and the Blind Tasting: Rumpole's latest case sees him defending Hugh Timson who is suspected of harbouring stolen wine. Meanwhile, Rumpole has concerns over his new pupil. (S4 Ep2)
</e2eventdescription>
<e2eventdescriptionextended/>
<e2eventservicereference>1:0:1:D07F:83E:2:11A0000:0:0:0:</e2eventservicereference>
<e2eventservicename>True Ent</e2eventservicename>
<e2eventgenre id="0"/>
</e2event>
<e2event>
<e2eventid>1034</e2eventid>
<e2eventstart>1551110400</e2eventstart>
<e2eventduration>3600</e2eventduration>
<e2eventcurrenttime>1551107044</e2eventcurrenttime>
<e2eventtitle>Murder, She Wrote</e2eventtitle>
<e2eventdescription>
Murder Through the Looking Glass: Jessica hears the dying confession of a hit-man while at a convention in Connecticut, leading her to uncover a mysterious house and a foreign dignitary. (S4 Ep16)
</e2eventdescription>
<e2eventdescriptionextended/>
<e2eventservicereference>1:0:1:D07F:83E:2:11A0000:0:0:0:</e2eventservicereference>
<e2eventservicename>True Ent</e2eventservicename>
<e2eventgenre id="0"/>
</e2event>
<e2event>
<e2eventid>21550</e2eventid>
<e2eventstart>1551114000</e2eventstart>
<e2eventduration>3600</e2eventduration>
<e2eventcurrenttime>1551107044</e2eventcurrenttime>
<e2eventtitle>Hamish Macbeth</e2eventtitle>
<e2eventdescription>
The Great Lochdubh Salt Robbery: Police Constable Hamish Macbeth investigates a bizarre theft and a mysterious disappearance. Are the two cases linked? Robert Carlyle stars in the title role. (S1 Ep1)
</e2eventdescription>
<e2eventdescriptionextended/>
<e2eventservicereference>1:0:1:D07F:83E:2:11A0000:0:0:0:</e2eventservicereference>
<e2eventservicename>True Ent</e2eventservicename>
<e2eventgenre id="48">Show/Games show: show/game show (general)</e2eventgenre>
</e2event>
<e2event>
<e2eventid>21549</e2eventid>
<e2eventstart>1551117600</e2eventstart>
<e2eventduration>3600</e2eventduration>
<e2eventcurrenttime>1551107044</e2eventcurrenttime>
<e2eventtitle>Born and Bred</e2eventtitle>
<e2eventdescription>
The Best Man: Dr Tom Gilder returns to Ormston when he is asked to be best man at a friend's wedding. Will the pull of village life convince him and his family to stay? (S1 Ep1)
</e2eventdescription>
<e2eventdescriptionextended/>
<e2eventservicereference>1:0:1:D07F:83E:2:11A0000:0:0:0:</e2eventservicereference>
<e2eventservicename>True Ent</e2eventservicename>
<e2eventgenre id="48">Show/Games show: show/game show (general)</e2eventgenre>
</e2event>
<e2event>
<e2eventid>21548</e2eventid>
<e2eventstart>1551121200</e2eventstart>
<e2eventduration>1800</e2eventduration>
<e2eventcurrenttime>1551107044</e2eventcurrenttime>
<e2eventtitle>M*A*S*H</e2eventtitle>
<e2eventdescription>
The Consultant: Hawkeye and Trapper meet Dr Borelli, a veteran doctor in Tokyo, whom they convince to visit the 4077th. Borelli intervenes when Frank is about to amputate a crushed leg. (S3 Ep17)
</e2eventdescription>
<e2eventdescriptionextended/>
<e2eventservicereference>1:0:1:D07F:83E:2:11A0000:0:0:0:</e2eventservicereference>
<e2eventservicename>True Ent</e2eventservicename>
<e2eventgenre id="48">Show/Games show: show/game show (general)</e2eventgenre>
</e2event>
<e2event>
<e2eventid>21547</e2eventid>
<e2eventstart>1551123000</e2eventstart>
<e2eventduration>1800</e2eventduration>
<e2eventcurrenttime>1551107044</e2eventcurrenttime>
<e2eventtitle>M*A*S*H</e2eventtitle>
<e2eventdescription>
House Arrest: Hawkeye is put under house arrest for punching Frank but is treated like a conquering hero. Meanwhile Hot Lips is nervous about a visit from Colonel Reese, the head of nurses. (S3 Ep18)
</e2eventdescription>
<e2eventdescriptionextended/>
<e2eventservicereference>1:0:1:D07F:83E:2:11A0000:0:0:0:</e2eventservicereference>
<e2eventservicename>True Ent</e2eventservicename>
<e2eventgenre id="48">Show/Games show: show/game show (general)</e2eventgenre>
</e2event>
<e2event>
<e2eventid>21546</e2eventid>
<e2eventstart>1551124800</e2eventstart>
<e2eventduration>3600</e2eventduration>
<e2eventcurrenttime>1551107044</e2eventcurrenttime>
<e2eventtitle>Randall and Hopkirk (Deceased)</e2eventtitle>
<e2eventdescription>
My Late Lamented Friend and Partner: When private eye Marty Hopkirk is murdered during an investigation, he returns as a ghost to help his partner, Jeff Randall, bring his killer to justice. (S1 Ep1)
</e2eventdescription>
<e2eventdescriptionextended/>
<e2eventservicereference>1:0:1:D07F:83E:2:11A0000:0:0:0:</e2eventservicereference>
<e2eventservicename>True Ent</e2eventservicename>
<e2eventgenre id="48">Show/Games show: show/game show (general)</e2eventgenre>
</e2event>
<e2event>
<e2eventid>21545</e2eventid>
<e2eventstart>1551128400</e2eventstart>
<e2eventduration>5400</e2eventduration>
<e2eventcurrenttime>1551107044</e2eventcurrenttime>
<e2eventtitle>Taggart</e2eventtitle>
<e2eventdescription>
Mind Over Matter: DS Reid goes undercover to find the killer of a teenager. But as more people are discovered, the case starts to impact on her personal and professional life. (S20 Ep5)
</e2eventdescription>
<e2eventdescriptionextended/>
<e2eventservicereference>1:0:1:D07F:83E:2:11A0000:0:0:0:</e2eventservicereference>
<e2eventservicename>True Ent</e2eventservicename>
<e2eventgenre id="48">Show/Games show: show/game show (general)</e2eventgenre>
</e2event>
<e2event>`

**Comment by phunkyfish** [comment]
Do your first two events have a genre id that is not zero?

**Comment by phunkyfish** [comment]
Ok, this looks like a provider issue. Sorry for the disturbance.
