### ISSUE TITLE
using -sid transient user fails

### ISSUE THREAD

**Issue by anudanan** [E2OpenPlugins/e2openplugin-OpenWebif#925]
If I use an user with a login shell over HTTPS. OWIF creates an -sid:pw user for the M3U file, for recorded movie streamung which can used later for streaming. But it doesn´t work

If I use the m3u file with -sid user for direct streaming, the VLC ask me for a new user/password, because die -sid user doesn´´t work

If I comment out the try statement here
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/9077b7afaf72406a9f0bbad1d30d761a06ab29c3/plugin/httpserver.py#L341
I got an python error
`--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 190, in process

  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 826, in getResourceFor

  File "/usr/lib/python2.7/site-packages/twisted/web/resource.py", line 98, in getChildForRequest

  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/httpserver.py", line 345, in getChildWithDefault
    oldsession = site.getSession(sid).sessionNamespaces
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 784, in getSession

exceptions.KeyError: 'd25ff77fa26f8e7c4c46866c9d2ac9f14b2c7a3d70c94d664afe11905f768a1c'

The httpserver.py runs until this line
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/9077b7afaf72406a9f0bbad1d30d761a06ab29c3/plugin/httpserver.py#L360

and gives an auth error

How is the way to use -sid user?

I have a feeling there is a bug around -sid user handling

`

**Comment by Schimmelreiter** [comment]
How did you test?
Locally or remote?
Transcoded or untranscoded?
Which distro?

It works w/o problem for me.

**Comment by anudanan** [comment]
Issue closed 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/dea9a921540a9aff91fdaa46be00802eabde0f81
