### ISSUE TITLE
API for storing last playback position for recordings 

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#928]
Hi, I maintain the kodi addon for Enigma2.

A useful feature would to be able to store the last playback position, so just a number.

A simple key value store managed by OpenWebIf would be a great solution to this. It could support numerous types and expiry if required.

**Comment by jbleyel** [comment]
You have to use /api/movielist.

**Comment by phunkyfish** [comment]
Sorry, I don’t mean last played back on the E2 device. I mean played back via streaming to kodi.

Unless there is an API to set this value, then it would work.

**Comment by jbleyel** [comment]
If you playback (stream) in a different device you have to do it on your device.
The last position on the box and the last position on a remote device can be in sync but the user should have the option to choose if he don't want that.

**Comment by jbleyel** [comment]
/api/movieinfo can get and set the cuts.
one cut is the last position

**Comment by phunkyfish** [comment]
Yes, it already exists locally. Many users have a number of kodi instances in their homes and want to start watching in the sitting room and continue in the bedroom. Which is why I suggested a separate KV store API so the device value would not be affected.

The user could then have the option of:

1 - start from beginning
2 - start from local offset
3 - start from remote offset

**Comment by phunkyfish** [comment]
Amazing, I didn’t realise it was possible to add cuts. I could also use the tags field I guess.
