### ISSUE TITLE
Finding channel from event name, eventId, starttime and endtime

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#930]
Hi,

I'm trying to figure out if there is quick way to find the event service reference having only the following fields: event name, eventId, startTime and endTime

I have been using epgsearch but for some entries it can take a long time. Any ideas?

Possibly some optional arguments to the epgsearch json API?

**Comment by phunkyfish** [comment]
Reason for not having channel is that in kodi an any channel timer can be created and it will lack this one piece of context,

**Comment by jbleyel** [comment]
Please try /api/event or /web/event

**Comment by phunkyfish** [comment]
I use those already but don’t have an Sref so not suitable.

However, I incorrectly used endTime instead of endtime as an argument to epgsearch. With this fixed the execution time is vastly improved.

So, I’ll close this now.
