### ISSUE TITLE
Formuler F1 use wrong port for file streaming with openATV

### ISSUE THREAD

**Issue by anudanan** [E2OpenPlugins/e2openplugin-OpenWebif#936]
I´ve had a thread about a streaming problem with recorded movies on a formuler F1 box with a user of this box
He uses the OpenAtv 6.3(formuler1tc) Date 20190314144220 Image

https://www.opena.tv/formuler-f1/46420-streamen-von-aufnahmen-auf-laptop-mit-openwebif-geht-nicht.html

I´ve found out that this box can only stream recorded movies over the OWIF ports for HTTP/HTTPS and not over the streaming port (normally 8001). 
With the current OWIF version 1.3.6 the M3U file for file streaming includes the streaming port,
The reason is these box don´t have the driver 
/dev/bcm_enc0 but has the driver /dev/encoder0 and the file /proc/stb/encoder/0/apply.
Therefor the stream.py insert in these codeline
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/ca5d6eef1515b2ff5804aa43a3853f8cd36b1c95/plugin/controllers/models/stream.py#L185
the streamingport and the the later code don´t set the OWIF port for streaming
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/ca5d6eef1515b2ff5804aa43a3853f8cd36b1c95/plugin/controllers/models/stream.py#L210

I don´t know which boxes use only the streamingport for file streaming and the codeline here is neccessary for these boxes
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/ca5d6eef1515b2ff5804aa43a3853f8cd36b1c95/plugin/controllers/models/stream.py#L185

My idea is to delete these codeline or include more conditions into the previous if statement to find out that some boxes use the streaming port for filestreaming or not

I have given the user a patched stream.py (which don´t set the streaming port) to verify if it works and I got the feedback that it works.

**Comment by jbleyel** [comment]
Please start the openwebif in a browser.
Goto recordings
Click on the TV button right behind the play button of a recording.
Check the ts.m3u file.

**Comment by anudanan** [comment]
The user from the openatv forum posted in the past the ts.m3u file

here is the content of it

#EXTM3U 
#EXTVLCOPT--http-reconnect=true 
#EXTINF:7028,Ghost in the Shell
#EXTVLCOPT:program=61301
http://IP der Box:8001/file?file=/media/hdd/movie/20190311%200047%20-%20ProSieben%20HD%20-%20Ghost%20in%20the%20Shell.ts


I also get the Port 80 is I do that on my uno4kse, but the user of the F1 Box get an 8001.

Did you made your test with the F1 Box?

**Comment by ims21** [comment]
May be, user has in F1 driver supporting transcoding? One or two version F1's drivers had this feature.

**Comment by Schimmelreiter** [comment]
oe-a images for various Formuler can be build in two variations, e.g.:
http://images.mynonpublic.com/openatv/6.3/index.php?open=formuler1
http://images.mynonpublic.com/openatv/6.3/index.php?open=formuler1tc

Formuler 1 with or without transcoding.
https://github.com/oe-alliance/oe-alliance-core/tree/4.2/meta-brands/meta-formuler/recipes-drivers

**Comment by anudanan** [comment]
Die User has installed 
Version 6.3TC from 31.03.2019

I think that is the trancoded version

**Comment by Schimmelreiter** [comment]
Correct.

**Comment by anudanan** [comment]
Does that means there is a bug inside openwebif to use streaming port (8001) for movie streaming instead of using the openwebif port (80)  for the F1 box with the tc-firmware version.

Or do you think the tc-firmware has a bug by streaming movies over the streaming port (8001)

**Comment by ims21** [comment]
Owif works well for me with both - with transcoding (f.eg. H9S - 8001) or without transcoding (80).

**Comment by anudanan** [comment]
You mean normal moviestreaming over port 8001 or trancoded noviestreaming over  port 8001 with transcoding parameter? I don´t know the port structur of H9S for direct or trancoding.

I have heared there a two different port structures in the enigma box world

1:
Port 8001: direct live streaming, sometime also direct moviestreaming
Port 80: direct moviestreaming
Port 8002: transcoed live and movie streaming

2.
Port 8001 can use for all streaming modes and the mode depends on some additional parameters for transcoded streaming
Port 80 works also for direct  movie streaming

**Comment by atvcaptain** [comment]
all boxes use port 8001 only vu gb and dags models use 8002 for transcoding

**Comment by Schimmelreiter** [comment]
For live TV ... for recorded movies (untranscoded) the normal HTTP or HTTPS port is used.

**Comment by anudanan** [comment]
But OWIF in the F1 Box of the user with the 6.3TC firmware uses 8001 for untranscoded recorded movies and it works only with my patch decribed in post ä1 of this issue. Only the patched OWIF creates now a ts.m3u with port HTTP/HTTPS 

So what is wrong?

**Comment by t5k6** [comment]
I have OpenATV on formuler1tc, and all my streams are on port 8001 (transcoded recording, raw recording, and live TV)

**Comment by anudanan** [comment]
The question is why it doesn‘t work on the box of the user in the Openatv Forum. May be he Must tested it with current firmware?

**Comment by anudanan** [comment]
Here is a next user with the same problem

https://www.opena.tv/formuler-f1/46420-streamen-von-aufnahmen-auf-laptop-mit-openwebif-geht-nicht-5.html#post416408

Do you have any idea so help the user and why he must change the ports in the m3u file for streaming?
