### ISSUE TITLE
Question: How Channel Numbering (pos) in api/getservices converts to matching channel number on STB

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#939]
A call to each service reference using `/api/getservices?sRef=` contains a service list and the highest pos in the service list. Each service in the list will tend to start at pos 1 and count up from there.

For any given bouquet how do you calculate the offset from which the channel number on the STB can be derived?

I would have thought that a call to `/api/getservices` would list the bouquets and each of the starting positions (i.e. offsets) but it does not.

It would be possible to follow the order in `/api/getservices` but it would meaning reading each full bouquet of channels to derive the numbers. E.g. if you are only interested in bouquets 1 and 4 you must read 1,2,3,4 to be able to derive the channel numbers.

**Comment by phunkyfish** [comment]
Amazing, thanks!

**Comment by phunkyfish** [comment]
I just tested this but the startpos appears incorrect. I would have expected the startpos of the first bouquet to be 0 and the for the second the final pos value from `/api/getservices?sRef=secondbouquet`

If I calculate it via using only calls to `/api/getservices?sRef=` it's correct using the order from `/api/getservices`.

**Comment by jbleyel** [comment]
startpos of the bouquet + position of the channel = channel number

**Comment by phunkyfish** [comment]
Correct, but this is not working correctly for me.

**Comment by jbleyel** [comment]
On my box i get this:
The first bouquet ends with channel 63 and the second starts with 64.

The api request for the second bouquet has startpos = 63
And this is correct.

**Comment by phunkyfish** [comment]
Ah, so I only see startpos when I call `/api/getservices`. I do not see it when individually calling each bouquet.

E.g. /api/getservices

```
{
 "services": [
  {
   "servicereference": "1:64:0:0:0:0:0:0:0:0::FreeSat UK", 
   "startpos": 0, 
   "program": 0, 
   "servicename": "FreeSat UK", 
   "pos": 0
  }, 
  {
   "servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.abm.sat_282_freesat.main.tv\" ORDER BY bouquet", 
   "startpos": 847, 
   "program": 0, 
   "servicename": "FreeSat UK - All channels", 
   "pos": 1
  }, 
```

And /api/getservices?sRef=somebouquet

```
{
 "services": [
  {
   "servicename": "FreeSat UK - Music", 
   "servicereference": "1:64:0:0:0:0:0:0:0:0::FreeSat UK - Music", 
   "pos": 0, 
   "picon": "/images/default_picon.png", 
   "program": 0, 
   "provider": ""
  }, 
  {
   "servicename": "The Vault", 
   "servicereference": "1:0:1:CC47:83D:2:11A0000:0:0:0:", 
   "pos": 1, 
   "picon": "/picon/1_0_1_CC47_83D_2_11A0000_0_0_0.png", 
   "program": 52295, 
   "provider": "Freesat"
  }, 
  {
   "servicename": "KEEPITCOUNTRY", 
   "servicereference": "1:0:1:C49B:811:2:11A0000:0:0:0:", 
   "pos": 2, 
   "picon": "/picon/1_0_1_C49B_811_2_11A0000_0_0_0.png", 
   "program": 50331, 
   "provider": "Freesat"
  }
 ], 
 "pos": 2
}
```

**Comment by jbleyel** [comment]
The startpos will ONLY displayed in bouquet list.
The calculation for single bouquet is too difficult.

**Comment by phunkyfish** [comment]
Ok, makes sense.

The first start pos front the bouquet list above is 847. However the first pos in that bouquet is 1, and that is also the channel number on the STB so startpos should be zero. The last pos in this bouquet is 998.

The next bouquet’s start pos is 1845. “1845 - 847 = 998”. So the channel numbering is off by 847 from the start, but is consistently off by the same number. Could it be the leading separator causing the issue?

Here is the full output of the bouquet list call:

```
{
 "services": [
  {
   "servicename": "FreeSat UK - Music", 
   "servicereference": "1:64:0:0:0:0:0:0:0:0::FreeSat UK - Music", 
   "pos": 0, 
   "picon": "/images/default_picon.png", 
   "program": 0, 
   "provider": ""
  }, 
  {
   "servicename": "The Vault", 
   "servicereference": "1:0:1:CC47:83D:2:11A0000:0:0:0:", 
   "pos": 1, 
   "picon": "/picon/1_0_1_CC47_83D_2_11A0000_0_0_0.png", 
   "program": 52295, 
   "provider": "Freesat"
  }, 
  {
   "servicename": "KEEPITCOUNTRY", 
   "servicereference": "1:0:1:C49B:811:2:11A0000:0:0:0:", 
   "pos": 2, 
   "picon": "/picon/1_0_1_C49B_811_2_11A0000_0_0_0.png", 
   "program": 50331, 
   "provider": "Freesat"
  }
 ], 
 "pos": 2
}
```

**Comment by phunkyfish** [comment]
@jbleyel any idea why there is an offset of 847 in my use case?

**Comment by AbuBaniaz** [comment]
@phunkyfish 
Is this resolved satisfactorily for you?

**Comment by phunkyfish** [comment]
No, it is not. I get an offset in the first bouquet which does not make sense. Output is above, you’ll see the startpos is 847 but should be 1.

**Comment by jbleyel** [comment]
Please remove the first bouquet "1:64:0:0:0:0:0:0:0:0::FreeSat UK" and test again.

**Comment by phunkyfish** [comment]
Will do. It’s auto generated by ABM so wouldn’t be able to remove permanently.

**Comment by AbuBaniaz** [comment]
I tried to explain a few years ago that these "blanks" are part of Enigma2 coding.

It would be great if they could be ignored.

**Comment by AbuBaniaz** [comment]
I mean ignored by OWIF

**Comment by phunkyfish** [comment]
If I manually remove the blank the output is as expected. However the best solution would be to ignore the blank bouquet.

**Comment by AbuBaniaz** [comment]
Not all countries have channels listed by numbers. An explanation of LCN on a previous attempt got sidetracked because someone else posted where they use a different implementation.

In ABM, we add the separators and spaces to ensure numbers match. Hopefully, recognising the blanks and ignoring them can be implemented.

Just to repeat, the blanks are part of E2 coding that ABM uses.

**Comment by phunkyfish** [comment]
And this is exactly what I do in the kodi Addon, ignore the blanks and count from one. It’s not perfect but it covers most use cases while waiting for this feature.

**Comment by phunkyfish** [comment]
Maybe this issue should be reopened.

**Comment by jbleyel** [comment]
try the last commit

**Comment by phunkyfish** [comment]
Will check tomorrow, code looks correct though.

**Comment by phunkyfish** [comment]
Works perfectly, thanks. Confirmed.

@jbleyel when do you usually increase version number?

I need to be able to tell the difference between the latest commit being included and not included.

Would a 1.3.7 version bump be possible?

**Comment by jbleyel** [comment]
The last commit ignores all non "real" bouquets.
