### ISSUE TITLE
Wrong times when exporting epg to xmltv format 

### ISSUE THREAD

**Issue by diogosena** [E2OpenPlugins/e2openplugin-OpenWebif#945]
Already fixed and tested for weeks in #940, but the fix was not merged.

Tested in android iptv, kodi iptv simple client, emby, jellyfin, perfect player and many others, they all worked correctly only after this fix.

The xmltv should have the program time in any timezone, and the offset should reflect that timezone, so the client device can understand correctly, and display in local timezone for the user.

**Comment by jbleyel** [comment]
#940 is not merged because i'ts not working correctly using sat epg data.

**Comment by diogosena** [comment]
Can you tell me exactly what's the problem? I'm testing with data extracted directly from DVBC source, using EIT trough tvheadend.

**Comment by jbleyel** [comment]
Please try Astra 19,2 and open the link in a browser. (not tvheadend)
I have test this an i get wrong time values.

**Comment by diogosena** [comment]
Can you please just send me the .xmltv file so I can take a look?

**Comment by jbleyel** [comment]
current code:

```
	<programme start="20190607213000 +0200" stop="20190607230000 +0200" channel="1:0:19:283D:3FB:1:C00000:0:0:0:">
		<title lang="de">Schutzpatron. Ein Kluftingerkrimi</title>
		<sub-title lang="de">Fernsehfilm Deutschland 2016</sub-title>
	</programme>

```

after your change:

```
<programme start="20190607233000 +0200" stop="20190608010000 +0200" channel="1:0:19:283D:3FB:1:C00000:0:0:0:">
		<title lang="de">Schutzpatron. Ein Kluftingerkrimi</title>
		<sub-title lang="de">Fernsehfilm Deutschland 2016</sub-title>
	</programme>

```

The correct start time is 23:30 CET.

**Comment by diogosena** [comment]
that's exactly what my modification is doing, +2 is representing the timezone offset that's already added to start time, generating 23:30 for the client.
There's any program that work with old behaviour and don't work with my change ?

**Comment by Schimmelreiter** [comment]
> There's any program that work with old behaviour and don't work with my change ?

We'll have to check against TV-Browser, which can also import EPG from an E2 box.
