### ISSUE TITLE
Include option 0 ("nothing") for timer "afterevent" field in XML API

### ISSUE THREAD

**Issue by HSE83** [E2OpenPlugins/e2openplugin-OpenWebif#951]
Hello,

OpenWebIF does support setting the "nothing" option for a timer's "afterevent" field. This is not reflected by the API, though. For example, the "timeradd" API only allows options 1, 2, and 3. This should be fairly easy to implement: Just add "0" in /controllers/web.py, line 1016.

Would be glad if this could be implemented since my box shuts down after every recording, unable to wake up again. So each timer I add without this option kills every event scheduled after..

Best,
Tobi

**Comment by jbleyel** [comment]
What image do you use?
