### ISSUE TITLE
api/epgsearch: JSON result with unescaped double quotes in values

### ISSUE THREAD

**Issue by TheMicroDevil** [E2OpenPlugins/e2openplugin-OpenWebif#954]
api/epgsearch returns an invalid JSON (values with unescaped double quotes)

Shortened example:
{......, "longdesc": "..........Morgan Freeman (Ned Logan)\nJaimz Woolvett **("Schofield Kid")**\nRichard Harris (English Bob)\nSaul Rubinek .....",...........}

Should be 
{......, "longdesc": "..........Morgan Freeman (Ned Logan)\nJaimz Woolvett **(\\"Schofield Kid\\")**\nRichard Harris (English Bob)\nSaul Rubinek .....",...........}

**Comment by jbleyel** [comment]
I cannot reproduce this without sample epg data via astra 19.2.
