### ISSUE TITLE
Streams with 5002 indications

### ISSUE THREAD

**Issue by doglover3920** [E2OpenPlugins/e2openplugin-OpenWebif#957]
When using a stream with 5002 denotion the result is as illustrated in the attached screenshot
![Owif](https://user-images.githubusercontent.com/3510990/62621592-8ef2a400-b91c-11e9-84dd-7aa3db36d777.PNG)

The bouquet is as follows:

```
#NAME Last Scanned
#SERVICE 5002:0:1:5221:C99:3:0:0:0:0:http%3a//live-vrt.akamaized.net/groupc/live/8edf3bdf-7db3-41c3-a318-72cb7f82de66/live_aes.isml/playlist.m3u8?fluxustv.m3u8:een HD
#DESCRIPTION één HD
#SERVICE 1:0:19:5221:C99:3:EB0000:0:0:0:
#DESCRIPTION één HD
```

PS: when using a 4097 stream denoting the result is OK

**Comment by jbleyel** [comment]
This needs to fix in enigma2.
See here -> 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/75e74a3a86092f71f5acd2a51d49c5b250626ade

**Comment by phunkyfish** [comment]
This may also be the cause of this issue: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/964

Any pointers on who/where to raise this as an issue in enigma2?

**Comment by phunkyfish** [comment]
@AbuBaniaz I think the handling of IPTV service refs may be the reason why streaming for IPTV does not work through OpenWebIf.

**Comment by AbuBaniaz** [comment]
We made a commit elsewhere that dealt with non-dvb service types as a whole instead of listing 5001, 5002 and 4097 individually.

But it still begs the question as to why not view stream directly on PC? Surely there is no need to involve the satellite receiver?

**Comment by phunkyfish** [comment]
Because it gets maintained in one place and the user experience is consistent with one reliable feature set.

**Comment by phunkyfish** [comment]
This is the experience you get when viewing directly on the receiver. Why not the same remotely?

**Comment by jbleyel** [comment]
Please don't mix different issues.
This issue here is only about wrong channel name for an IPTV service.
Maybe an encoding issue.
This needs to fix in enigma.

Issue #964 is about iptv channel detection in openwebif and needs to fix in openwebif.

**Comment by phunkyfish** [comment]
Apologies
