### ISSUE TITLE
Kanalinfo per api abrufbar?

### ISSUE THREAD

**Issue by LevelOne2k** [E2OpenPlugins/e2openplugin-OpenWebif#959]
Hallo! Kann man sich die Kanalinfos so wie auf dem Screenshot zu sehen auch per Api JSON oder XML anzeigen lassen?
![B4F8D951-1C1C-4A92-BF19-C77601753F65](https://user-images.githubusercontent.com/25386824/63725782-a8bc4280-c85b-11e9-9e6b-806a3cb95e2f.png)

**Comment by rdamas** [comment]
Bis auf die Satlevel-Info ist alles in /api/about drin.
