### ISSUE TITLE
Bug in save settings in Autotimer dialog?

### ISSUE THREAD

**Issue by rdamas** [E2OpenPlugins/e2openplugin-OpenWebif#960]
The code in lines from https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/master/sourcefiles/js/at.js#L1161 looks wrong - the two options add_autotimer_to_tags and add_name_to_tags may not be set correctly?

**Comment by jbleyel** [comment]
Is this a javascript issue?

**Comment by rdamas** [comment]
Yes. Look at lines 1161 to 1164 - the option value is put to the request before option name.
