### ISSUE TITLE
stream.m3u created for transcoded & original stream equal

### ISSUE THREAD

**Issue by validom** [E2OpenPlugins/e2openplugin-OpenWebif#965]
in channel overview, there are two buttons to stream a channel. One which provides the original (non-transcoded) stream, another one which provides the transcoded stream (e.g. lower bitrate for mobile usage). But both buttons create an stream.m3u file with the same content.

Transcoding is configured to use port 8001. On 8002, the non-transcoded stream is available. 

Openwebif should respect this configuration and create different stream.m3u files.

Box: Vu+ Duo2, Image VTi 14.

**Comment by jbleyel** [comment]
Do you have the latest version of openwebif from here or do you use the VTi version?

**Comment by validom** [comment]
VTi Version.
Do I understand the question right, that I should ask the VTi Team instead?

**Comment by jbleyel** [comment]
Simple answer.
VTi don't use this source here.
