### ISSUE TITLE
M3U mit Komma im Namen, Download faild per Webif

### ISSUE THREAD

**Issue by Joerg1909** [E2OpenPlugins/e2openplugin-OpenWebif#967]
Hallo Entwickler,
der Download der Bouquets als M3U über das Webif mit Komma oder ' im Namen ist nicht mehr möglich im OpenATV 6.3.
Der Fehler ist hier sehr gut beschieben:

https://www.opena.tv/plugins/43816-webif-bouquets-mit-komma-im-namen-nicht-mehr-downloadbar.html#post375057

Vielen Dank und mit freundlichen Grüßen
Joerg1909

**Comment by jbleyel** [comment]
Wo ist das Komma drin? Im Sendername oder im Bouquetname.
Welcher Download genau geht dann nicht?

**Comment by Joerg1909** [comment]
Entschuldigung für die verspätete Rückmeldung da ich im Krankenhaus bin.
Das Problem sind die Bouquetnamen.
Hier ein Paar Beispiele:

#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.06Nachrichten, Business, Politics.tv" ORDER BY bouquet
#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.14Cultural, History, Lifestyle.tv" ORDER BY bouquet
#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.15Religious, Presentations.tv" ORDER BY bouquet
#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.16Game, Erotic.tv" ORDER BY bouquet

Vielen Dank für Deine Arbeit!

**Comment by cptechnik** [comment]
Ich persönlich würde gar keine Kommas verwenden...
...und mein Firefox im ubuntu-mate nimmt das bis zum Komma an...
...und speichert.
