### ISSUE TITLE
The Enigma2 Bouquet Editor is not compatible with Internet Explorer 11

### ISSUE THREAD

**Issue by wiensha** [E2OpenPlugins/e2openplugin-OpenWebif#971]
In Google Chrome en Microsoft Edge the online Bouquet Editor works, but in Internet Explorer 11 (Windows 10) it doesn't work.

If you select a provider the list of channels is not showing up. Also this list is not showing when one selects All channels.

**Comment by Schimmelreiter** [comment]
Easy: Do not use IE.

**Comment by rdamas** [comment]
I cannot agree more. And you already mentioned it: _IE is not compatible_ and a dead child that thankfully doesn't receive development anymore. If you've ever tried to maintain compatibility regarding JS and CSS for IE, you know why no one seriously cares about IE.

**Comment by doglover3920** [comment]
But the same problem is also present in Chrome and Firefox.

**Comment by doglover3920** [comment]
Traced it back to a bouquetfile.
Problem is what is wrong with this bouquet (so I can avoid it in the future)
BTW: this bouquetfile comes straight for the Hans list
[userbouquet.sky_italia.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/3706579/userbouquet.sky_italia.zip)

**Comment by teamblue-e2** [comment]
#NAME Italië
?

**Comment by doglover3920** [comment]
Ok replaced it with Italia and the problem seem to be solved.
But why does it not want to accept ë ?

Alternatively, I changed the codepage to UTF-8 instead of ANSI Windows-1252.  And now it is accepted.

**Comment by technl** [comment]
I can't find a bouquet named userbouquet.sky_italia in Hanssettings ... can you give me the exact name of the bouquet so I can fix it in the 'Hanssettings'.

**Comment by doglover3920** [comment]
It is now called (I installed it some time ago) userbouquet.ital_.tv
And it is already in UTF-8.  So it should work now.

**Comment by technl** [comment]
Ah, I was assuming that the problem was present in the current Hanssettings but it was a local issue :)
