### ISSUE TITLE
Generate XSPF playlist instead of M3U8?

### ISSUE THREAD

**Issue by mensa84** [E2OpenPlugins/e2openplugin-OpenWebif#972]
Hello,

is it possible, that one can generate XSPF playlist files instead of M3U8 files?
It would be better because then also VLC player would be able to display Picons from URLs which are included in XSPF file in `<image>` tag.

VLC is not able to display Picons which are included in M3U8 file in tvg-logo tag.

Do you plan to provide also XSPF playlist file download for Bouquets? That would be really great!

**Comment by jbleyel** [comment]
It's possible.
Please provide an example xspf file.

**Comment by mensa84** [comment]
How ist it possible? Where to click to gete XSPF?

**Comment by jbleyel** [comment]
not now .. i need an example file first to finish the generation

**Comment by mensa84** [comment]
Ok, now I opened the M3U file from OpenWebif in VLC and saved the playlist as XSPF file. In the XSPF fille I added the <image> tag and it is wokring for example like that:

```
<?xml version="1.0" encoding="UTF-8"?>
<playlist xmlns="http://xspf.org/ns/0/" xmlns:vlc="http://www.videolan.org/vlc/playlist/ns/0/" version="1">
	<title>Wiedergabeliste</title>
	<trackList>
		<track>
			<location>http://user:pass@vu-plus:8001/1:0:19:132F:3EF:1:C00000:0:0:0:</location>
			<title>ORF1 HD</title>
			<image>https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/ORF1_logo.svg/1200px-ORF1_logo.svg.png</image>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>0</vlc:id>
				<vlc:option>program=4911</vlc:option>
			</extension>
		</track>
		<track>
			<location>http://user:pass@vu-plus:8001/1:0:19:33F8:3ED:1:C00000:0:0:0:</location>
			<title>ORF2O HD</title>
			<image>https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/ORF-2-Logo.svg/1200px-ORF-2-Logo.svg.png</image>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>1</vlc:id>
				<vlc:option>program=13304</vlc:option>
			</extension>
		</track>
	</trackList>
	<extension application="http://www.videolan.org/vlc/playlist/0">
		<vlc:item tid="0"/>
		<vlc:item tid="1"/>
	</extension>
</playlist>
```

**Comment by jbleyel** [comment]
Do we realy need this?

```
	<extension application="http://www.videolan.org/vlc/playlist/0">
		<vlc:item tid="0"/>
		<vlc:item tid="1"/>
	</extension>

```

and this?
```

			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>1</vlc:id>
				<vlc:option>program=13304</vlc:option>
			</extension>
```

**Comment by mensa84** [comment]
I am not sure, like I said it was generated by VLC.

**Comment by jbleyel** [comment]
Please test and close the issue if it works.

**Comment by mensa84** [comment]
Thank you, but how may I test?
I have openATV 6.3. Will I get the new OpenWebif version by online update in the image?

**Comment by jbleyel** [comment]
OpenATV 6.3 and 6.4 should have the latest version on the feed.

**Comment by mensa84** [comment]
Bei mir ist OpenWebif 1.3.5+git3390 installiert. Ist das eine Version, in der XSPF schon möglich sein soll?
Finde ich das im neuen Design auch, oder müsste ich vorher aufs alte Design wechseln?

**Comment by jbleyel** [comment]
Nein, das geht erst mal nur mit dem alten Design.

**Comment by mensa84** [comment]
Ist OpenWebif 1.3.5+git3390 überhaupt die passende Version? Sollte es da schon eingebaut sein und wo genau wäre es zu finden?

**Comment by jbleyel** [comment]
-> Einstellungen / Openwebif Einstellungen / Playlist Format

Im Neuen Design gibt ein keine Möglichkeit zum Download von der Playlist.

**Comment by mensa84** [comment]
Ist OpenWebif 1.3.5+git3390 überhaupt die passende Version?

**Comment by jbleyel** [comment]
Nein die ist zu alt. Die Version muss 1.3.9 sein.

**Comment by mensa84** [comment]
Oje, die kriegt man aber leider nicht über den Feed, oder?

**Comment by jbleyel** [comment]
Ich hab openatv 6.4 und die Version 1.3.9. vom Feed.
Da müsstest du dich mal im Openatv Forum melden.

**Comment by mensa84** [comment]
Ich hab 6.3 und leider nix aktuelleres über den Feed bekommen.

Ist eigentlich geplant, dass der Doenload auch ins neue Design des OpenWebif kommt?

**Comment by jbleyel** [comment]
kommt heute rein.

**Comment by mensa84** [comment]
Cool, danke :)

**Comment by mensa84** [comment]
Wo kann ich das aktuellste IPK denn downloaden und manuell installieren? Ich finde leider nichts hier.

**Comment by jbleyel** [comment]
Bitte im openatv forum fragen, warum die neue version nicht auf dem feed ist.
Bei 6.4 ist es die version 1.3.8 und nicht die 1.3.9.
d.H. auch bei 6.4 ist es nicht die allerneuste.

IPK runterladen geht nicht so einfach.

**Comment by nickersk** [comment]
there is SRCREV = "${AUTOREV}" in bitbake recipes, so openwebif is always newest version. 1.3.5 or    1.3.8 in ipk name is not important.

**Comment by jbleyel** [comment]
The version in bb file is now 1.3.9. And the feed for openatv 6.3 will be updated soon.
Thanks to Captain.

**Comment by mensa84** [comment]
Ich hab mittlerweile 1.3.9 drauf und die Funktion für das neue Format gibt es leider noch immer nicht. Was passt da nicht?

**Comment by jbleyel** [comment]
Gibt es diese Einstellung?
Wenn nicht, dann ist es nicht die neuste Version.
Dort muss man das Format umstellen.
M3U ist default.

<img width="962" alt="Bildschirmfoto 2020-04-24 um 19 51 30" src="https://user-images.githubusercontent.com/964927/80242109-16c43e00-8665-11ea-9cba-5894a02839cf.png">

**Comment by mensa84** [comment]
Danke, ich hab's gefunden. (Dachte vorher, ich würde diese Einstellung auch direkt im Menü des Receivers finden, aber gibt's anscheinend nur im Webif).

Es kommen aber diese Fehler, wenn ich eine Playlist downloaden möchte:

```
web.Server Traceback (most recent call last):
NameMapper.NotFound: cannot find 'bname' while searching for 'services.bname'
/usr/lib/python2.7/site-packages/twisted/web/server.py:197 in process
196
197
198
/usr/lib/python2.7/site-packages/twisted/web/server.py:257 in render
256
257
258
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/base.py:204 in render
203
204
205
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/base.py:119 in loadTemplate
118
119
120
/usr/lib/python2.7/site-packages/Cheetah/Template.py:1005 in __str__
1004
1005
1006
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/views/web/servicesxspf.py:98 in respond
97
98
99
NameMapper.NotFound: cannot find 'bname' while searching for 'services.bname'

```

**Comment by jbleyel** [comment]
Bitte mal diese beiden Dateien löschen.

/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/bouquets.pyo
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/responsive/ajax/bouquets.pyo

Die werden automatisch wieder erstellt.

**Comment by mensa84** [comment]
Gerade gemacht, jetzt kommen diese Fehler:

```
web.Server Traceback (most recent call last):
NameMapper.NotFound: cannot find 'bname' while searching for 'services.bname'
/usr/lib/python2.7/site-packages/twisted/web/server.py:197 in process
196
197
198
/usr/lib/python2.7/site-packages/twisted/web/server.py:257 in render
256
257
258
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/base.py:204 in render
203
204
205
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/base.py:119 in loadTemplate
118
119
120
/usr/lib/python2.7/site-packages/Cheetah/Template.py:1005 in __str__
1004
1005
1006
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/views/web/servicesxspf.py:98 in respond
97
98
99
NameMapper.NotFound: cannot find 'bname' while searching for 'services.bname'

```

**Comment by jbleyel** [comment]
Dann mal diese Datei 
/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/web.py

Durch diese 

https://raw.githubusercontent.com/E2OpenPlugins/e2openplugin-OpenWebif/master/plugin/controllers/web.py

ersetzen.

Danach die Box neu starten.

**Comment by mensa84** [comment]
Es gibt keine web.py sonder nur eine web.pyo
Was soll ich somit machen?

**Comment by jbleyel** [comment]
Meinen Kommentar genau lesen. ;-)

**Comment by mensa84** [comment]
Ja, aber soll ich die .pyo dann einfach unverändert liegen lassen und die .py nur zusätzlich erstellen?

**Comment by mensa84** [comment]
Gemacht wie du gesagt hast - jetzt diese Fehler:

```
web.Server Traceback (most recent call last):
NameMapper.NotFound: cannot find 'bname' while searching for 'services.bname'
/usr/lib/python2.7/site-packages/twisted/web/server.py:197 in process
196
197
198
/usr/lib/python2.7/site-packages/twisted/web/server.py:257 in render
256
257
258
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/base.py:204 in render
203
204
205
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/base.py:119 in loadTemplate
118
119
120
/usr/lib/python2.7/site-packages/Cheetah/Template.py:1005 in __str__
1004
1005
1006
/home/oe1/atv63/build-enviroment/builds/openatv/release/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/1.3.9+gitAUTOINC+872a540cbf-r0/git/plugin/controllers/views/web/servicesxspf.py:98 in respond
97
98
99
NameMapper.NotFound: cannot find 'bname' while searching for 'services.bname'

```

**Comment by jbleyel** [comment]
Einfach nur die py erstellen bzw. überschreiben, wenn die schon da ist.

**Comment by mensa84** [comment]
Ich habe die .py erstellt und die .pyo einfach liegen gelassen + neugestartet.
Fehler kommen noch immer.

**Comment by jbleyel** [comment]
Dann ist da was anderes faul.
Muss ich prüfen.

**Comment by mensa84** [comment]
Danek :)

**Comment by jbleyel** [comment]
Bitte auf die nächste Version warten.

**Comment by mensa84** [comment]
XSPF zum Download funktioniert jetzt und läßt sich abspielen, es werden jedoch leider die Sendernamen nicht angezeigt, mit M3U aber schon:

https://i.imgur.com/1lLpzg1.png
