### ISSUE TITLE
Bouquet editor, numbering, 320 markers

### ISSUE THREAD

**Issue by AbuBaniaz** [E2OpenPlugins/e2openplugin-OpenWebif#973]
Is it possible that the numbering in Bouquet editor can also count the 320 markers? They are there to make up numbers, so excluding them from OWIF numbering does do tehm justice.

Thanks in advance

[userbouquet.abm.sat_282_sky_uk.101.tv.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/3719887/userbouquet.abm.sat_282_sky_uk.101.tv.zip)

![OWIF 320 markers](https://user-images.githubusercontent.com/6644489/66689964-5016fc80-ec85-11e9-89c6-fc144b110888.png)

**Comment by AbuBaniaz** [comment]
Oops, I forgot to attach the picture of how the bouquets actually appear on the receiver. As you can see, Eden should be 166

![OWIF 320 markers 2](https://user-images.githubusercontent.com/6644489/66708664-da299880-ed4b-11e9-83b0-576f0ac06991.png)

**Comment by jbleyel** [comment]
Please check again using the latest version.

**Comment by AbuBaniaz** [comment]
It is still not right. Just to clarify, In Enigma2 the 320 markers are counted but not visible in the normal viewing mode. When you go to edit, they become visible (otherwise you would not be able to see where you are putting them)

In OWIF Bouquet Editor, they are currently visible, but are still not counted. They must be counted. I suspect that all markers are being treated the same when the are different types. For example 064 markers should be visible but not counted..

I hope this commit explains things better. We added it to Vix last year, but it has been in PLI for many years.
https://github.com/OpenViX/enigma2/commit/8d9cf312f628173297bf8ea5706ccc79a716951d

**Comment by AbuBaniaz** [comment]
Better still
https://github.com/OpenPLi/enigma2/blob/develop/lib/service/iservice.h#L28:L48

64 = marker
256 = is numbered marker

64+256 = 320

**Comment by jbleyel** [comment]
I have only one question.
Why do you have 320 and not 832?

I'm pretty sure that your number markers should be hidden or am i wrong?

**Comment by AbuBaniaz** [comment]
832 are permanenty hidden and not visible while moving/editing using remote in Enigma2.
320 can be toggled to be visible in normal viewing.  They are always visible in editing mode, there is no choice in editing mode.

**Comment by jbleyel** [comment]
Okay.

This is the current code.
 
```
sref = citem[0].toString() 
hs = (int(sref.split(":")[1]) & 512) 
sp = (sref[:7] == '1:832:D') 
if not hs or sp:  # 512 is hidden service on sifteam image. Doesn't affect other images 
	oPos = oPos + 1 
	if not sp and citem[0].flags & eServiceReference.isMarker: 
		oPos = oPos - 1 
```
I think this code can be easy optimized.
Maybe:

```
if int(sref.split(":")[1]) <> 64:
 oPos = oPos + 1 

``` 
What you think?

**Comment by AbuBaniaz** [comment]
I am not a coder, so can't comment decisively. We need to apply the different types of marker correctly instead of grouping them incorrectly. Some are visible and not counted, others are invisible but counted.

However, to repeat what was said earlier, all markers must be visible in edit mode.

I hope that helps. If not I can ask others to comment.

**Comment by jbleyel** [comment]
I can make the change but i cannot test.

**Comment by AbuBaniaz** [comment]
If you upload the file, I can test. Thanks

P.S
I commented in the remote commit if you get a moment.

**Comment by Huevos** [comment]
I have fixed this in eListboxService where the problem was. Current openvix dev image should now work properly.

https://github.com/OpenViX/enigma2/commit/41320646128af00497778a216f39dcd57074bf88

**Comment by Huevos** [comment]
And this suggestion above `if int(sref.split(":")[1]) <> 64:` should be `if int(sref.split(":")[1]) != eServiceReference.isMarker:`

**Comment by AbuBaniaz** [comment]
The OWIF bouquet editor issue fixed by these commits:

https://github.com/oe-alliance/OpenWebif/commit/0915762bc8a2e9b4bff2af945b40d615446c7c7b
https://github.com/oe-alliance/OpenWebif/commit/0fc956e216feb31c850fe143686052eac251a7e2

Many thanks

![1_0_1_1966_7E6_2_11A0000_0_0_0_20231029134046](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/assets/6644489/9b64a4b0-6735-4256-bd7d-6f7e1c0b704a)

![Screenshot 2023-10-29 134028](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/assets/6644489/5393beef-179f-4c17-9af8-3cfd5f168b5e)

**Comment by AbuBaniaz** [comment]
The navigation issue within sections in E2 has been fixed in Vix. Thanks
