### ISSUE TITLE
Add api endpoint to retrieve EPG in XMLTV format

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#975]
Used in conjunction with servicesm3u there would then be a generic output format for both channels and EPG.

**Comment by zehnerGIT** [comment]
You can try `/web/epgxmltv?bRef=xxx&lang=en` as a starting point. 
It's only for simple epg data in combination with a separate m3u, so no channel logos, genres, etc.

**Comment by phunkyfish** [comment]
That’s great. The channel logo is already in the servicesm3u call so really all that is missing is the genre ID/description!

**Comment by phunkyfish** [comment]
Figured out how to add genre as a category: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/977

**Comment by jbleyel** [comment]
You can add all what you need in epgxmltv what you want and then create a pull request.

**Comment by phunkyfish** [comment]
Yes, I did. Thanks 😊
