### ISSUE TITLE
API für Streamanzeige?

### ISSUE THREAD

**Issue by LevelOne2k** [E2OpenPlugins/e2openplugin-OpenWebif#978]
Hallo! Gibt es eine API für die Streamanzeige so wie man sie im Webif auch sehen kann?

<img width="367" alt="Bildschirmfoto 2019-11-05 um 22 25 36" src="https://user-images.githubusercontent.com/25386824/68247486-3d40df00-001b-11ea-8946-81e080f13a6b.png">

<img width="917" alt="Bildschirmfoto 2019-11-05 um 22 24 37" src="https://user-images.githubusercontent.com/25386824/68247487-3dd97580-001b-11ea-9c02-299a193fd7a6.png">

**Comment by jbleyel** [comment]
Welches webinterface ist das?
Vermutlich VTI und daher bitte das VTI Team fragen.

**Comment by LevelOne2k** [comment]
Ja VTI. Das gehört dann zu VTI das man dort die Streams sieht und nicht zum OpenweIF von Dir?

**Comment by jbleyel** [comment]
Das openwebif ist nicht nur von mir.
Ich werde mich zum Thema VTI und openwebif nicht mehr äussern.
Ich sage nur "Kindergarten".

**Comment by LevelOne2k** [comment]
Kann ich die Version hier installieren? https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/blob/gh-pages/enigma2-plugin-extensions-openwebif_1.3.8-e2openpluginsgit20191101_all.ipk

**Comment by jbleyel** [comment]
Vermutlich wird die nicht 100% gehen ich kann es nicht testen.

**Comment by LevelOne2k** [comment]
Echt affig. https://www.vuplus-support.org/wbb4/index.php?thread/135286-warum-gibt-es-im-vti-nicht-die-aktuelle-version-vom-openwebif/

**Comment by LevelOne2k** [comment]
Echt affig. https://www.vuplus-support.org/wbb4/index.php?thread/135286-warum-gibt-es-im-vti-nicht-die-aktuelle-version-vom-openwebif/

**Comment by jbleyel** [comment]
Ich hab plnick mehrfach angeboten die Versionen anzugleichen.
Keine Antwort und daher offensichtlich kein Interesse.

**Comment by atvcaptain** [comment]
vti sieht sich als was besseres, mit dir redet soweit kommt es noch

**Comment by LevelOne2k** [comment]
Echt schade.

**Comment by jbleyel** [comment]
Hi @LevelOne2k , der Kollege plnick ist wohl nicht mehr bei VTI. Man könnte also das Thema openwebif angeilchen noch mal angehen.
Ich werde jedoch bei VTI keinen mehr anschreiben, denn die Reaktion war bisher gleich 0.

**Comment by LevelOne2k** [comment]
Hi @LevelOne2k , es wäre natürlich gut wenn immer die aktuelle Version ins VTI einfließt, jedoch habe ich dort keinen Ansprechpartner. Ich denke, Du kennst dort mehr Leute die was zu sagen haben.

**Comment by LevelOne2k** [comment]
Hi @jbleyel , es wäre natürlich gut wenn immer die aktuelle Version ins VTI einfließt, jedoch habe ich dort keinen Ansprechpartner. Ich denke, Du kennst dort mehr Leute die was zu sagen haben.

**Comment by jbleyel** [comment]
Nein, ich kenne dort niemanden.

**Comment by LevelOne2k** [comment]
Dann wird sich das Thema wohl erledigt haben.
