### ISSUE TITLE
Software Update via Webinterface

### ISSUE THREAD

**Issue by walter-in-space** [E2OpenPlugins/e2openplugin-OpenWebif#979]
Is there a link or button to start the update via webinterface? It would be nice to upgrade my boxes without running through the house or do it by a central cron.

**Comment by rdamas** [comment]
You mean selecting Settings->Packages->Update/Upgrade from the OWIF main menu? (Translated from german, may show up slightly different in your browser...)

**Comment by walter-in-space** [comment]
Exactly... But... because I think updates are important there should  be one button near on/off to update/upgrade including reboot. „Clickreduction“ make things more usable. This is one thing. The other is to call this function from a simple link for automation. What do you think of this idea?

**Comment by Schimmelreiter** [comment]
Obviously what you want is
```init 4 && opkg update && opkg upgrade && sync && reboot```
which is a shell command line which can easily be issued via ssh.

**Comment by walter-in-space** [comment]
This will solve the job. Thanks, I will try. What about automatic updates like AVM Fritzbox with email when it is finished?

**Comment by kkro** [comment]
Ok, I testet. Do you see a chance that I get a resultcode from "opkg upgrade" to decide wether only to restart enigma or if there were upgrades to reboot? About reboot: to be perfect I need to save the standby-state and decide what to do after reboot: standby or be online. How can I find out in which state the box is? I know: http://boxip/api/powerstate can do this, but I want a commandline thing.

A little hint for all others reading this: /sbin/init oder /sbin/reboot helps.

**Comment by Schimmelreiter** [comment]
As a side note:
No image team recommends doing opkg update && opkg upgrade (Or its E2-GUI counterpart)!

You are advised to backup settings, flash and restore instead, which is a pretty much straightforward process in at least OpenATV.
