### ISSUE TITLE
WebTV not working anymore?

### ISSUE THREAD

**Issue by mensa84** [E2OpenPlugins/e2openplugin-OpenWebif#984]
Hello,

as it seems WebTV is not working anymore with any newser browser.
Or could anyone please explain how WebTV could be used again with modern browsers?

**Comment by jbleyel** [comment]
https://www.videoexpertsgroup.com/vxg-chrome-plugin/

**Comment by mensa84** [comment]
I did read this. But what does this mean now?
Is there any working solution or not?

There is also a link which should work in any browser: https://www.videoexpertsgroup.com/vxg-platform-player/

Will that work for OpenWebif alos or what is the plan? Make WebTV work again or remove it completely?

**Comment by jbleyel** [comment]
The platform player is not free and needs an extra server.
There is no solution except for transcoded stream.

**Comment by mensa84** [comment]
Then better remove it when not working anymore, or why not find an working solution?

**Comment by jbleyel** [comment]
Transcoded stream should work using html5 player.

**Comment by Schimmelreiter** [comment]
For the moment it still **does** work.
So far, the NativeClient (Which is what VXG uses) can still be enabled under chrome://flags

**Comment by jbleyel** [comment]
chrome://flags/#enable-nacl

**Comment by mensa84** [comment]
Can I enable the native client also in Firefox?

How can I use "HTML5 Player" for WebTV in OpenWebif?

**Comment by jbleyel** [comment]
FF? No idea? Cause i don't use this.

HTML5 player only works with transcoded stream.

**Comment by mensa84** [comment]
I have transcoding active. Where can I enable the HTML5 player for WebTVin OpenWebif?

**Comment by Schimmelreiter** [comment]
![image](https://user-images.githubusercontent.com/2022025/71324845-55de5900-24e4-11ea-8355-32547dbc9982.png)

**Comment by Schimmelreiter** [comment]
That is WaterFox 2019.12 using the VLC plugin.
Pale Moon should work too.

**Comment by Schimmelreiter** [comment]
And this is latest Chrome (With nacl activated):
![image](https://user-images.githubusercontent.com/2022025/71325720-0eaa9500-24f1-11ea-8e85-225f711c2963.png)

**Comment by mensa84** [comment]
Is there also a solution to get it to work in browsers which are used by "normal" people?
I mean Firefox, Chrome, Safari and Edge!?

Ok, there is a solution for Chrome with nacl. But what about the others? Does it just not work in the main browsers?

When I want to stream in the browser I am often not able to choose the browser and of course not to enable any special settings, cause sometimes I use public PCs. Is there a solution for normal "standard" browsers?

**Comment by Schimmelreiter** [comment]
It's not any decision made by us but by the makers of the browsers.

It originally worked in Chrome and Firefox, until **they** decided to break the NPAPI plugin support (Firefox) or deprecate their own nacl (Chrome).

I fear that there will not be any simple solution for the mass market browsers anytime soon, as the "new" interfaces the browser vendors deem a decent replacement for the removed APIs are not really mature and functional enough for the vendors of media players to create new plugins.

The only way to seemlessly stream video inside a browser appears to be HTML5, but the telestreams we want to stream are not HTML5 compliant and some of the boxes do not have the power to make them comply (by transcoding them).

**Comment by mensa84** [comment]
I absolutely understand, that this was not your decision.

How could I test the HTML5 player?
I have a Vu+ Uno 4K. I think it should be powerful enough, right?
And I think the powerful boxxes will grow a lot in future.

So I think the target should be HTML5 player. For example Youtube also just works in any browser.

Please explain me how I can use HTML 5 player with transcoding?

**Comment by jbleyel** [comment]
This is not a problem of you box.
The transcoded stream format is not 100% HLS and therefore you aren't able to use HTML5 player.

Chrome, Safari -> no playback
Firefox -> ?
IE11 -> ?
Edge -> ?

**Comment by mensa84** [comment]
But @Schimmelreiter posted above, that an enough powerful box would be able to transcode the stream to comply with HTML5 player.
Isn't that right?
