### ISSUE TITLE
Remote control in mobile view

### ISSUE THREAD

**Issue by AbuBaniaz** [E2OpenPlugins/e2openplugin-OpenWebif#986]
A feature request: Is it possible that we can have a remote function using mobile webif? We have the control function, but that is very limited. I was thinking of one similar to the  virtual remote in Dreamdroid.

Thanks in advance

**Comment by e2world** [comment]
use http://ip/mobile

**Comment by AbuBaniaz** [comment]
Thanks for that. However, if you just enter your IP address on your mobile address, you are taken to the mobile view anyway. I am not asking how to acccess the mobile version of openwebif, I am asking to have a virtual remote.

**Comment by AbuBaniaz** [comment]
Something similar to these
`https://apps.apple.com/us/app/dreamote-remote-dreambox-vu/id924059278`
`https://www.enigma2.net/android-dream-remote-control/`
`https://play.google.com/store/apps/details?id=baront.enigma.rc&hl=en_GB`

**Comment by rdamas** [comment]
See https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/989 and decide yourself, if it is useful. The images of the remote controls are of limited quality, so...

**Comment by AbuBaniaz** [comment]
Many thanks. I will test later

**Comment by AbuBaniaz** [comment]
The actual remote on a small screen is not what I had in mind. Some remotes physically have lots of buttons and will make them too small on the mobile.

Anyway, a change in the right direction.

**Comment by AbuBaniaz** [comment]
I tried transferring the files manually, there was no remote option. I will await for official integration into the OE-A fork of the plugin

**Comment by jbleyel** [comment]
LINK 
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/503

**Comment by jbleyel** [comment]
LINK
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/148
