### ISSUE TITLE
Remote control templates

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#991]
In the remote control template files, "**remote.html**", used by OpenWebif what is the purpose of the "**alt**" attribute in the "area" tag?

These "**area**" tags are a map overlay coordinates over an image of the remote control.  Is the "**alt**" attribute being used in some way by the OpenWebif code?

If the purpose was intended to be a hover help for the areas being mapped out then the correct attribute should be "**title**".

**Comment by jbleyel** [comment]
There are some html files with only "title" and some with "alt" and "title".
This looks like a copy paste issue.
We don't need the "alt" attribute.

**Comment by IanSav** [comment]
Thank you.  I will remove the "alt" attributes from my recent Zgemma update.

**Comment by IanSav** [comment]
@jbleyel, as we correct and update remote controls we are now converting alt= attributes into title= attributes.

There is one more question:  Some remote controls have an id= attribute and many do not.  Is the id= attribute used by OpenWebif or can it be removed?  (The value, when it is used, appears to be the same as that used in the pressMenuRemote() function.

**Comment by jbleyel** [comment]
The id attribute is not needed.

**Comment by IanSav** [comment]
Thank you for the confirmation.  We will drop the id= tag from all updated remote controls.
