### ISSUE TITLE
Request: Return single movie instead of full list

### ISSUE THREAD

**Issue by phunkyfish** [E2OpenPlugins/e2openplugin-OpenWebif#995]
@jbleyel 

I maintain the kodi addon for enigma2 and would like to be able to retrieve a single movie's details instead of the full list. The reason for this is that retrieving the entire list can be a lot of data and the information I'm looking for is just a single movie's current size.

Maybe this is already possible but I'm not seeing from the source that it is.

Thanks in advance.

**Comment by jbleyel** [comment]
I have add moviedetails api.

/api/moviedetails?sref=

/web/moviedetails?sref=

**Comment by phunkyfish** [comment]
Amazing. Thanks. Will test shortly

**Comment by phunkyfish** [comment]
@jbleyel just one issue. Filesize is always reporting as zero.

**Comment by phunkyfish** [comment]
Other than that it's correct.

**Comment by phunkyfish** [comment]
It looks like the leading `/` get's stripped somehow so it can't stat the file.

**Comment by phunkyfish** [comment]
You beat me to it ;)

**Comment by phunkyfish** [comment]
One more thing. Result is returned as false even when it finds the entry.

**Comment by jbleyel** [comment]
anything else?

**Comment by phunkyfish** [comment]
No, everything else is perfect. Thanks so much for this!
