### ISSUE TITLE
API: get timeshift status

### ISSUE THREAD

**Issue by gahujipo** [E2OpenPlugins/e2openplugin-OpenWebif#996]
Is there any way to get the timeshift status via the API? A 
```JSON
"isTimeshift": true
```
would be great.

**Comment by jbleyel** [comment]
Please try /api/tsstate

**Comment by gahujipo** [comment]
That gives me a 404 error. Did that come with a certain newer version?

**Comment by jbleyel** [comment]
The commit is from 2017

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/430758cb267630e2bd3d43de27e935f8bf8a9ae6

You may have a very old version.

**Comment by gahujipo** [comment]
I just upgraded this weekend to a current version. And indeed you were right. 

I see this:
```JSON
"timeshiftEnabled": 1
```
 I habe enabled automatic timeshift after 20 seconds. So this gives me the info whether a timeshift file has begun. In my case this is always after 20 seconds. Is there a way to get the info whether the picture is live or timeshifted?

**Comment by jbleyel** [comment]
Sorry. I don't know how.
Someone of the enigma2 source developer may help.

**Comment by jbleyel** [comment]
Closed because of not reproducible

**Comment by gahujipo** [comment]
@jbleyel what do you mean by "not reproducible"? Do you need further information on this problem?

**Comment by jbleyel** [comment]
If you can reproduce the please describe more detailed.
And provide your image infos.

**Comment by jbleyel** [comment]
By the way. There are complete different implementations for permanent timeshift out there and the OWF will only support the image internal implementation.
