### ISSUE TITLE
Openwebif - Timer PIP ZAP

### ISSUE THREAD

**Issue by demosat** [E2OpenPlugins/e2openplugin-OpenWebif#997]
Hi,
Can you add in the openwebif interface the functions for the timer pip zap please.
I can't find a possibility for PIP ZAP programming with openwebif.

https://zupimages.net/viewer.php?id=20/14/vl9x.png

https://zupimages.net/viewer.php?id=20/14/k3ra.jpg

**Comment by jbleyel** [comment]
What image do you have?

**Comment by demosat** [comment]
I use openpli and satdreamgr

**Comment by demosat** [comment]
Thanks for #997 but isn't finish.
I remove openwebif in my image and i reboot.
I install enigma2-plugin-extensions-openwebif_1.3.9-e2openpluginsgit20200408_all.ipk
https://zupimages.net/viewer.php?id=20/15/s5zr.jpg

And they are not possibility for selecting pip zap timer on interface graphic.
No icon for pip zap timer and no case for selecting.
https://zupimages.net/viewer.php?id=20/15/oibz.gif

**Comment by jbleyel** [comment]
I have add the api support first.
The web timer edit needs to be changed.

**Comment by demosat** [comment]
Thanks Jbleyel

**Comment by demosat** [comment]
Hi,
For translate language, you can add "Use as PiP if possible" in i18.py please
